window.HIST_DATA = {
  meta: {
    title: "La Sinistra storica. Riformare lo Stato liberale",
    shortTitle: "Sinistra storica",
    storageKey: "storia-sinistra-storica-v1",
    question: "La Sinistra storica rese davvero più democratico lo Stato liberale, oppure ne allargò soltanto la base senza cambiarne la natura?",
    thesis: "Fra il 1876 e il 1887 la Sinistra storica realizzò un'apertura concreta: rafforzò l'obbligo scolastico, ampliò il suffragio, abolì il macinato e portò nel Parlamento una società più articolata. Non costruì però una democrazia di massa. Monarchia, Senato regio, centralismo, notabilato ed esclusione femminile restarono intatti; il trasformismo stabilizzò il centro ma indebolì l'alternanza, mentre protezionismo e colonialismo trasferirono costi su gruppi e territori diversi.",
    workshopIntro: "Non scegliere fra celebrazione e condanna. Una tesi storica deve misurare insieme apertura e continuità: quali diritti aumentarono, chi rimase escluso, come cambiarono le maggioranze, chi beneficiò delle scelte economiche e perché la politica estera divenne più aggressiva.",
    previous: { title: "Destra storica", url: "../Destra-storica/" },
    next: { title: "L'età di Crispi - tappa futura", url: "#" }
  },
  lessons: [
    {
      id: "rivoluzione-parlamentare", number: 1, title: "Una rivoluzione senza barricate", eyebrow: "La Sinistra arriva al governo", period: "1875-1876",
      question: "Perché il 1876 fu una svolta politica reale pur senza cambiare costituzione, dinastia e classe sociale dominante?",
      lead: "Il 18 marzo 1876 la Camera sconfisse il governo Minghetti sulla gestione delle ferrovie. Il passaggio a Depretis avvenne entro lo Statuto: fu la prima alternanza del Regno, ma non l'ingresso delle masse nello Stato.",
      sections: [
        { title: "Il mondo precedente: uno Stato costruito dalla Destra", paragraphs: ["Nel 1876 il Regno possedeva ormai un'amministrazione uniforme, una capitale a Roma, un esercito nazionale e un bilancio ricondotto al pareggio. La Destra aveva reso lo Stato più solido, ma lo aveva governato con suffragio ristretto, accentramento e imposte che pesavano anche sui consumi popolari.", "La Sinistra cresceva soprattutto fra notabili meridionali, ex democratici, garibaldini e liberali progressisti. Non era un partito organizzato: come la Destra, viveva di gruppi parlamentari, legami personali e influenza locale."], summary: "La svolta nacque dentro uno Stato già consolidato, ma socialmente e politicamente stretto." },
        { title: "Le fratture: ferrovie, bilancio e maggioranza", paragraphs: ["La proposta di riscattare e gestire direttamente alcune ferrovie divise la maggioranza. Il 18 marzo 1876 Minghetti fu battuto alla Camera e si dimise. La crisi mostrò che il governo dipendeva ormai dalla fiducia parlamentare di fatto, benché lo Statuto non la formulasse esplicitamente.", "Il re incaricò Agostino Depretis. Non ci furono insurrezioni né rotture istituzionali: proprio per questo i contemporanei parlarono di rivoluzione parlamentare, cioè di un'alternanza prodotta dal voto della Camera."], summary: "Il meccanismo parlamentare sostituì una classe di governo senza abbattere il regime." },
        { title: "Attori, gruppi e conflitti: chi era la Sinistra", paragraphs: ["Depretis era un uomo del Risorgimento e aveva già ricoperto incarichi ministeriali. Accanto a lui agivano personalità molto diverse: Cairoli, Crispi, Nicotera, Zanardelli e Baccarini condividevano l'opposizione alla Destra, non una disciplina di partito.", "L'elettorato restava una minuscola minoranza maschile. Proprietari, professionisti e notabili continuarono a dominare Parlamento e amministrazioni. Il cambiamento politico fu dunque più ampio del semplice ricambio personale, ma più ristretto di una trasformazione sociale del potere."], summary: "La Sinistra era più eterogenea della Destra, non socialmente rivoluzionaria." },
        { title: "Il processo storico: dal programma di Stradella al governo", paragraphs: ["Nel discorso di Stradella del 1875 Depretis aveva promesso suffragio più largo, istruzione elementare più efficace, alleggerimento delle imposte indirette e maggiori autonomie locali. Il programma collegava cittadinanza politica, scuola e consenso.", "Le elezioni del novembre 1876 diedero alla Sinistra una larga maggioranza. Tuttavia l'assenza di partiti stabili e la competizione fra gruppi personali resero difficile trasformare le promesse in una linea coerente."], summary: "La vittoria aprì una stagione riformatrice, ma la stessa composizione della Sinistra ne preparò le tensioni." },
        { title: "Conseguenze e nuovo assetto: l'alternanza diventa possibile", paragraphs: ["Per la prima volta dall'Unità, la Destra lasciò il governo senza che lo Stato entrasse in crisi. Questo rafforzò la natura parlamentare del regime e dimostrò che il sistema poteva assorbire una maggioranza diversa.", "Restarono però monarchia, Statuto, Senato di nomina regia, prefetti e centralismo. L'alternanza riguardava l'area liberale costituzionale; repubblicani, socialisti, cattolici intransigenti, donne e gran parte dei lavoratori rimasero fuori dal potere."], summary: "Il 1876 normalizzò il ricambio di governo, non democratizzò da solo lo Stato." },
        { title: "Conclusione: una svolta dentro la continuità", paragraphs: ["Chiamare il 1876 rivoluzione non significa equipararlo al 1789 o al 1848. La parola indica un cambiamento decisivo nel funzionamento del Parlamento: una maggioranza poteva sostituirne un'altra senza cambiare il quadro costituzionale.", "La domanda successiva diventa allora inevitabile: la Sinistra userà il governo per includere nuovi cittadini o per allargare soltanto il consenso dell'élite liberale?"], summary: "La Sinistra conquistò il governo; doveva ancora dimostrare se sapeva cambiare il rapporto fra Stato e società." }
      ],
      source: { id: "sinistra-depretis", title: "Sinistra storica e programma di Depretis", prompt: "Distingui la composizione sociale del raggruppamento dalle promesse con cui si presentò al paese." },
      activity: { title: "Rivoluzione: parola appropriata?", prompt: "Formula due argomenti a favore e due contro l'espressione rivoluzione parlamentare. Concludi definendo con precisione che cosa cambiò e che cosa rimase." },
      coordinates: ["Stradella, 10 ottobre 1875: programma di Depretis", "18 marzo 1876: caduta del governo Minghetti", "25 marzo 1876: primo governo Depretis", "Novembre 1876: vittoria elettorale della Sinistra", "Statuto Albertino e monarchia restano in vigore"],
      essentials: ["La Sinistra storica non era un partito di massa.", "Il governo Minghetti cadde su una votazione parlamentare legata alle ferrovie.", "Rivoluzione parlamentare indica alternanza senza rottura costituzionale.", "Depretis aveva già esperienza di governo.", "Il programma di Stradella univa suffragio, scuola, fisco e autonomie.", "La classe dirigente restò composta soprattutto da notabili.", "Il 1876 consolidò la prassi parlamentare del Regno."],
      vocab: { Rivoluzione_parlamentare: "Passaggio di governo prodotto da una nuova maggioranza della Camera senza rottura costituzionale.", Sinistra_storica: "Raggruppamento liberale costituzionale, eterogeneo e notabilare, al governo dal 1876.", Notabile: "Persona influente localmente per ricchezza, professione, prestigio e relazioni.", Alternanza: "Sostituzione pacifica di una maggioranza di governo con un'altra.", Programma_di_Stradella: "Discorso del 1875 nel quale Depretis presentò le principali riforme della Sinistra." },
      answer: "Il 1876 fu una svolta perché rese possibile l'alternanza entro il sistema parlamentare e aprì un programma riformatore. Non fu una rivoluzione sociale: la Sinistra apparteneva allo stesso mondo liberale e notabilare della Destra e conservò i pilastri dello Stato costruito dopo l'Unità.",
      connections: { map: "L'allargamento del suffragio", people: ["depretis", "minghetti", "crispi"] }
    },
    {
      id: "economia-crisi", number: 5, title: "Proteggere l'economia, dividere gli interessi", eyebrow: "Agricoltura, ferrovie e dazi", period: "1877-1887",
      question: "Quando lo Stato protegge l'economia nazionale, protegge davvero tutti nello stesso modo?",
      lead: "La Sinistra aumentò spesa pubblica e infrastrutture, studiò l'agricoltura, affidò l'esercizio ferroviario a società private e nel 1887 scelse il protezionismo. Ogni provvedimento distribuì benefici e costi in modo diseguale.",
      sections: [
        { title: "Il mondo precedente: un'economia rurale e differenziata", paragraphs: ["L'Italia era un paese prevalentemente agricolo. Pianura padana irrigua, mezzadria centrale, latifondi meridionali e insulari, piccola proprietà e colture specializzate formavano sistemi diversi: parlare di un'unica agricoltura italiana nasconde più di quanto spieghi.", "La Destra aveva privilegiato pareggio, liberismo e credibilità finanziaria. La Sinistra ereditò infrastrutture insufficienti, domanda interna debole e una crescente pressione per usare la spesa pubblica come leva di modernizzazione."], summary: "La politica economica doveva agire su territori e gruppi con interessi non coincidenti." },
        { title: "Le fratture: la crisi agraria globale", paragraphs: ["Dagli anni Settanta cereali americani e russi, trasportati a costi più bassi, raggiunsero l'Europa. La caduta dei prezzi colpì aziende indebitate e poco produttive; proprietari e lavoratori reagirono in modo diverso.", "Alcune imprese innovarono o si specializzarono, altre ridussero salari, licenziarono o chiesero dazi. Crebbero conflitti rurali ed emigrazione. La crisi fu internazionale, ma le sue conseguenze dipendevano dalle strutture locali."], summary: "Un mercato mondiale più integrato trasformò differenze produttive in conflitti politici nazionali." },
        { title: "Attori, gruppi e conflitti: l'Inchiesta Jacini", paragraphs: ["L'Inchiesta agraria, istituita nel 1877 e presieduta da Stefano Jacini, pubblicò quindici volumi tra 1881 e 1884. Raccoglieva dati su tecniche, contratti, salari, abitazioni, malaria, credito e usi civici.", "La documentazione mise in luce povertà contadina e divari, ma rifletteva anche domande e categorie delle élite agrarie. Fu insieme grande strumento conoscitivo e fonte da leggere criticamente, chiedendosi chi osservava e chi veniva osservato."], summary: "Lo Stato conobbe meglio le campagne, senza per questo risolvere i rapporti di potere che l'inchiesta descriveva." },
        { title: "Il processo storico: ferrovie private, proprietà e sussidi pubblici", paragraphs: ["Le convenzioni ferroviarie del 1885 divisero la rete fra grandi società concessionarie per lunghi periodi. Lo Stato conservava la proprietà di molte linee e garantiva sussidi: non era né piena privatizzazione né nazionalizzazione.", "La soluzione permetteva investimenti e gestione unitaria, ma creava obblighi costosi e rapporti opachi fra politica e imprese. Le ferrovie erano infrastruttura economica e strumento di consenso territoriale."], summary: "La modernizzazione ferroviaria combinò capitale privato, garanzie pubbliche e negoziazione politica." },
        { title: "Conseguenze e nuovo assetto: la tariffa del 1887", paragraphs: ["La nuova tariffa alzò i dazi su siderurgia, tessili e cereali. Favorì l'industria protetta e i grandi produttori di grano; poteva sostenere investimenti e occupazione in settori strategici.", "Aumentò però il prezzo dei cereali per i consumatori e danneggiò colture meridionali d'esportazione esposte alle ritorsioni. La guerra doganale con la Francia, iniziata nel 1888, rese visibili i costi territoriali della scelta."], summary: "Il protezionismo costruì una coalizione di interessi, non un vantaggio uniforme per la nazione." },
        { title: "Conclusione: economia nazionale, vincitori concreti", paragraphs: ["Dire che una politica favorisce l'industria nazionale è insufficiente: bisogna chiedere quali industrie, quali proprietari, quali lavoratori e quali consumatori. Lo stesso dazio può proteggere un produttore e impoverire una famiglia.", "La Sinistra abbandonò il rigore della Destra e usò più attivamente bilancio e protezione. Questa modernizzazione selettiva accelerò alcuni settori e approfondì altri squilibri."], summary: "Ogni scelta economica è anche una scelta sociale e territoriale, anche quando viene presentata come interesse nazionale." }
      ],
      source: { id: "jacini", title: "L'Inchiesta Jacini: conoscere per governare", prompt: "Valuta che cosa l'inchiesta permette di sapere e quali limiti derivano dagli osservatori, dalle categorie usate e dalla varietà delle campagne." },
      activity: { title: "Una tariffa, quattro bilanci", prompt: "Costruisci il bilancio della tariffa del 1887 per un siderurgico, un grande cerealicoltore, un viticoltore meridionale e una famiglia operaia. Indica guadagni, costi e possibili alleanze." },
      coordinates: ["1877: istituzione dell'Inchiesta agraria", "1881-1884: pubblicazione dei quindici volumi", "1885: convenzioni ferroviarie", "Anni Ottanta: crisi agraria europea", "1887: tariffa doganale protezionistica", "1888: inizio della guerra doganale con la Francia"],
      essentials: ["L'agricoltura italiana era composta da sistemi regionali diversi.", "La crisi agraria dipese anche dall'arrivo di cereali extraeuropei.", "L'Inchiesta Jacini fu istituita nel 1877.", "Le fonti dell'inchiesta vanno lette considerando il punto di vista degli osservatori.", "Le convenzioni del 1885 combinarono gestione privata e sostegno pubblico.", "Il protezionismo favorì siderurgia, tessile e cerealicoltura.", "I consumatori pagarono prezzi più alti per alcuni beni.", "Le colture meridionali d'esportazione furono esposte alle ritorsioni francesi."],
      vocab: { Crisi_agraria: "Caduta prolungata di prezzi e redditi agricoli con effetti diversi secondo colture e territori.", Inchiesta_Jacini: "Indagine parlamentare sulle campagne italiane avviata nel 1877.", Convenzione_ferroviaria: "Contratto che affida l'esercizio della rete a società concessionarie con obblighi e garanzie pubbliche.", Protezionismo: "Uso di dazi per difendere produttori nazionali dalla concorrenza estera.", Guerra_doganale: "Conflitto commerciale nel quale Stati si colpiscono con dazi e restrizioni reciproche." },
      answer: "Lo Stato non protegge tutti allo stesso modo perché l'economia nazionale contiene interessi concorrenti. La tariffa del 1887 sostenne industria e grandi cerealicoltori, ma trasferì costi sui consumatori e sulle produzioni esportatrici. La modernizzazione fu reale e selettiva.",
      connections: { map: "Benefici e costi del protezionismo", people: ["depretis", "minghetti", "crispi"] }
    },
    {
      id: "triplice", number: 6, title: "Dall'isolamento alla Triplice Alleanza", eyebrow: "Mediterraneo ed Europa", period: "1878-1887",
      question: "Perché l'Italia si alleò con l'Austria-Ungheria, lo Stato contro cui aveva combattuto per l'unificazione?",
      lead: "Berlino, Tunisia ed Egitto alimentarono la percezione di isolamento. Nel 1882 l'Italia entrò nel sistema di Bismarck con un patto difensivo che offriva garanzie contro la Francia ma contraddiceva l'irredentismo.",
      sections: [
        { title: "Il mondo precedente: completare l'Unità o cercare potenza?", paragraphs: ["Dopo Roma capitale, la politica estera non poteva più limitarsi al completamento dell'unificazione. Il governo doveva decidere se restare prudente, difendere l'equilibrio mediterraneo o partecipare alla competizione coloniale.", "L'Italia disponeva di risorse militari e finanziarie inferiori alle grandi potenze, ma cercava riconoscimento. Francia, Austria-Ungheria e Gran Bretagna erano al tempo stesso interlocutori, rivali e possibili garanti."], summary: "La nuova Italia cercava uno status internazionale superiore alle proprie capacità materiali." },
        { title: "Le fratture: mani nette e schiaffo di Tunisi", paragraphs: ["Al Congresso di Berlino del 1878 il ministro Luigi Corti non avanzò richieste territoriali. La politica delle mani nette evitava avventure costose, ma fu interpretata come prova di debolezza quando altre potenze ottennero vantaggi.", "Nel 1881 la Francia impose il protettorato sulla Tunisia, dove viveva una numerosa comunità italiana. Lo schiaffo di Tunisi fece cadere Cairoli e trasformò la rivalità con Parigi in un problema di prestigio nazionale."], summary: "La prudenza diplomatica apparve isolamento quando la Francia occupò uno spazio desiderato dall'Italia." },
        { title: "Attori, gruppi e conflitti: Bismarck, Vienna e gli irredentisti", paragraphs: ["Bismarck voleva isolare la Francia e consolidare il sistema delle alleanze. L'Austria-Ungheria offriva accesso al blocco tedesco, ma governava Trentino e Trieste, rivendicati dagli irredentisti italiani.", "Monarchia e moderati cercavano sicurezza; radicali e repubblicani denunciavano l'accordo con Vienna. La politica estera divideva quindi l'idea stessa di nazione: sicurezza dello Stato o liberazione delle terre italiane?"], summary: "L'alleanza risolveva un isolamento e apriva una contraddizione nazionale." },
        { title: "Il processo storico: il patto del 20 maggio 1882", paragraphs: ["Italia, Germania e Austria-Ungheria firmarono a Vienna un trattato segreto e difensivo. Italia e Germania si sarebbero aiutate in caso di aggressione francese; un attacco di due grandi potenze a uno dei contraenti avrebbe attivato il sostegno degli alleati.", "Negli altri casi era prevista almeno neutralità benevola. Una dichiarazione richiesta dall'Italia escludeva che l'alleanza potesse essere diretta contro la Gran Bretagna, indispensabile per l'equilibrio mediterraneo."], summary: "La Triplice non obbligava a seguire qualsiasi guerra: clausole, aggressore e numero delle potenze contavano." },
        { title: "Conseguenze e nuovo assetto: sicurezza, dipendenza, rinnovo", paragraphs: ["L'Italia uscì dall'isolamento e ottenne una garanzia contro la Francia. Divenne interlocutrice nel sistema europeo, ma vincolò parte della propria libertà di manovra e accentuò la distanza diplomatica da Parigi.", "Nel rinnovo del 1887 ottenne clausole migliori su Balcani e Mediterraneo. La Triplice non cancellò la collaborazione informale con la Gran Bretagna: le alleanze ottocentesche non erano blocchi automatici e immutabili."], summary: "La sicurezza aumentò, insieme alle dipendenze e alle contraddizioni." },
        { title: "Conclusione: allearsi con l'avversario", paragraphs: ["Gli Stati non scelgono alleati in base alla sola memoria delle guerre passate. Nel 1882 la minaccia percepita proveniva soprattutto dalla Francia, mentre la Germania appariva il centro del nuovo equilibrio continentale.", "L'accordo con Vienna era quindi razionale sul piano della sicurezza e problematico sul piano nazionale. Proprio questa tensione spiega meglio la scelta di quanto faccia l'accusa di incoerenza."], summary: "La Triplice fu una risposta strategica plausibile che trasformò un problema di isolamento in un problema di contraddizione politica." }
      ],
      source: { id: "triplice-fonte", title: "La Triplice Alleanza: un trattato segreto e condizionato", prompt: "Distingui aggressione, sostegno, neutralità e dichiarazione britannica. Poi verifica se il patto equivale a un automatismo militare." },
      activity: { title: "Consiglio della Corona, 1882", prompt: "Prepara una nota per il re con tre vantaggi, tre rischi e un'alternativa alla Triplice. Usa Tunisia, Francia, Austria e Gran Bretagna come variabili reali." },
      coordinates: ["1878: Congresso di Berlino", "1881: protettorato francese in Tunisia", "1882: occupazione britannica dell'Egitto", "20 maggio 1882: Triplice Alleanza", "1887: primo rinnovo con clausole più favorevoli"],
      essentials: ["La politica delle mani nette fu prudente, non semplicemente passiva.", "Il protettorato francese in Tunisia aggravò la rivalità con l'Italia.", "Bismarck mirava a isolare la Francia.", "La Triplice era segreta e difensiva.", "L'aiuto dipendeva dalle condizioni del trattato.", "L'alleanza non doveva essere rivolta contro la Gran Bretagna.", "L'accordo con l'Austria contraddiceva l'irredentismo.", "Il rinnovo del 1887 migliorò la posizione italiana."],
      vocab: { Mani_nette: "Formula della prudenza italiana al Congresso di Berlino del 1878.", Protettorato: "Controllo esercitato da una potenza su uno Stato formalmente esistente.", Irredentismo: "Movimento per l'annessione all'Italia di territori considerati italiani ma soggetti ad altri Stati.", Triplice_Alleanza: "Patto difensivo del 1882 fra Italia, Germania e Austria-Ungheria.", Neutralita_benevola: "Non intervento accompagnato da un atteggiamento favorevole verso uno dei belligeranti." },
      answer: "L'Italia si alleò con l'Austria perché dopo la Tunisia percepiva la Francia come minaccia immediata e cercava protezione nel sistema tedesco. La scelta aumentò sicurezza e prestigio, ma entrò in conflitto con l'irredentismo e ridusse la libertà diplomatica.",
      connections: { map: "Dall'isolamento al Mar Rosso", people: ["depretis", "crispi", "minghetti"] }
    },
    {
      id: "colonialismo", number: 7, title: "Il colonialismo alla prova di Dogali", eyebrow: "Assab, Massaua, Etiopia", period: "1869-1887",
      question: "Perché uno Stato ancora povero e attraversato dall'emigrazione scelse di impiegare risorse in un'espansione coloniale?",
      lead: "Dopo la Tunisia, l'Italia guardò al Mar Rosso. Interessi commerciali, posizione strategica e desiderio di prestigio si combinarono; a Dogali incontrarono la resistenza di uno Stato africano indipendente e militarmente organizzato.",
      sections: [
        { title: "Il mondo precedente: il Mar Rosso dopo Suez", paragraphs: ["L'apertura del canale di Suez nel 1869 aumentò l'importanza delle rotte fra Mediterraneo e Oceano Indiano. Nello stesso anno la compagnia Rubattino acquistò la baia di Assab come scalo commerciale privato.", "Il Corno d'Africa non era uno spazio vuoto. Potenze locali, Impero etiopico, Egitto, ottomani, commerci regionali e società costiere avevano propri interessi e conflitti. La cartografia coloniale europea tendeva a cancellare questa complessità."], summary: "La presenza italiana entrò in uno spazio politico già organizzato, non in una terra disponibile." },
        { title: "Le fratture: dalla società privata allo Stato", paragraphs: ["Nel 1882 lo Stato italiano acquistò Assab dalla Rubattino. Nel 1885 occupò Massaua, evacuata dagli egiziani durante la crisi mahdista, con il consenso britannico.", "La trasformazione di scali in basi territoriali modificò i rapporti con l'Etiopia. Roma presentava l'avanzata come sicurezza e commercio; le autorità etiopiche la leggevano come minaccia alla sovranità."], summary: "Il passaggio dal commercio alla presenza militare trasformò la relazione in conflitto territoriale." },
        { title: "Attori, gruppi e conflitti: ras Alula e lo Stato etiopico", paragraphs: ["Ras Alula Engida governava l'Hamasien per l'imperatore Giovanni IV ed era un comandante esperto. Definirlo semplicemente capo indigeno riduce una struttura politica e militare capace di mobilitare forze, controllare territori e perseguire una strategia.", "In Italia sostenitori dell'impresa promettevano mercati, terre e prestigio; oppositori radicali, repubblicani e socialisti denunciavano costi, violenza e distrazione dai problemi interni."], summary: "Il conflitto contrappose progetti statali e produsse divisioni anche nella società italiana." },
        { title: "Il processo storico: Saati e Dogali", paragraphs: ["Nel gennaio 1887 le tensioni attorno al presidio italiano di Saati esplosero. Il 26 gennaio una colonna di circa cinquecento uomini comandata da Tommaso De Cristoforis, diretta a sostenere il forte, fu intercettata dalle forze di ras Alula.", "La colonna venne quasi interamente distrutta. L'episodio non fu un incidente contro bande disordinate: dimostrò che l'espansione incontrava capacità militare e decisioni politiche africane."], summary: "Dogali infranse l'idea di una conquista facile e mise in luce l'autonomia strategica etiopica." },
        { title: "Conseguenze e nuovo assetto: lutto, rivincita, dissenso", paragraphs: ["La notizia produsse lutto e indignazione, ma il linguaggio del sacrificio nazionale alimentò anche richieste di vendetta. La maggioranza votò rinforzi e crediti, trasformando una sconfitta in argomento per proseguire.", "Andrea Costa e altri oppositori chiesero il ritiro. La controversia rese il colonialismo una questione pubblica: prestigio internazionale contro investimenti interni, emigrazione reale contro promesse di colonie di popolamento."], summary: "La sconfitta non fermò l'espansione; rese più visibile il costo politico e umano della scelta." },
        { title: "Conclusione: una periferia che cambia il centro", paragraphs: ["Il colonialismo non fu un'aggiunta marginale alla storia nazionale. Modificò bilanci, propaganda, esercito, relazioni internazionali e rappresentazioni razziali, mentre imponeva guerra e subordinazione alle società coinvolte.", "Dogali costringe a rovesciare lo sguardo: non soltanto che cosa voleva l'Italia, ma come le potenze africane difendevano sovranità e territori."], summary: "L'espansione coloniale cercava prestigio, ma incontrò soggetti storici capaci di opporsi e di cambiare la politica italiana." }
      ],
      source: { id: "dogali-fonte", title: "Dogali: due sguardi sulla stessa battaglia", prompt: "Confronta il racconto italiano della sconfitta con la ricostruzione del ruolo politico e militare di ras Alula." },
      activity: { title: "Cambiare il punto di vista", prompt: "Scrivi due titoli di giornale del 27 gennaio 1887: uno da Roma e uno dalla regione governata da ras Alula. Poi spiega quali parole rivelano il punto di vista." },
      coordinates: ["1869: acquisto privato della baia di Assab", "1882: Assab passa allo Stato italiano", "1885: occupazione italiana di Massaua", "25 gennaio 1887: scontro a Saati", "26 gennaio 1887: battaglia di Dogali", "Etiopia governata dall'imperatore Giovanni IV"],
      essentials: ["Suez accrebbe l'importanza strategica del Mar Rosso.", "Assab nacque come acquisto commerciale privato.", "Lo Stato acquisì Assab nel 1882.", "Massaua fu occupata nel 1885.", "L'Etiopia era uno Stato indipendente e organizzato.", "Ras Alula agiva come governatore e comandante.", "Dogali avvenne il 26 gennaio 1887.", "La sconfitta rafforzò sia l'opposizione sia il desiderio di rivincita.", "Il colonialismo va studiato anche dal punto di vista delle società africane."],
      vocab: { Colonialismo: "Conquista e controllo politico, militare ed economico di territori esterni.", Corno_d_Africa: "Regione dell'Africa orientale comprendente l'area fra Mar Rosso e Oceano Indiano.", Ras: "Titolo dell'aristocrazia e del comando politico-militare etiopico.", Sovranita: "Potere di uno Stato di decidere sul proprio territorio senza autorità superiore.", Dogali: "Battaglia del 26 gennaio 1887 in cui le forze di ras Alula distrussero una colonna italiana." },
      answer: "L'Italia cercò nel colonialismo prestigio, rotte e mercati che riteneva necessari per essere una grande potenza. La scelta era controversa in un paese povero e fu fondata su una sottovalutazione delle società africane. Dogali mostrò che l'Etiopia possedeva sovranità, strategia e forza militare.",
      connections: { map: "Dall'isolamento al Mar Rosso", people: ["depretis", "crispi", "pio-ix"] }
    },
    {
      id: "bilancio", number: 8, title: "Più democrazia o liberalismo allargato?", eyebrow: "Il bilancio della stagione", period: "1876-1887",
      question: "Quale formula descrive meglio la Sinistra storica: democratizzazione, continuità liberale o modernizzazione contraddittoria?",
      lead: "Il bilancio non può essere un elenco di meriti e colpe. Bisogna collegare riforme, strutture rimaste intatte, nuove organizzazioni sociali, trasformismo, scelte economiche e ricerca di prestigio.",
      sections: [
        { title: "Il mondo precedente: l'eredità della Destra", paragraphs: ["La Sinistra ricevette uno Stato centralizzato, finanziariamente credibile, territorialmente quasi completo e amministrativamente uniforme. Ricevette anche suffragio minimo, scuola debole, fratture territoriali e un rapporto spesso coercitivo con la popolazione.", "Non distrusse questa architettura. La usò per riformare e governare, mostrando che Destra e Sinistra appartenevano a una stessa area liberale pur rappresentando interessi e stili diversi."], summary: "La Sinistra cambiò la direzione del governo senza rifondare lo Stato." },
        { title: "Le fratture: quattro aperture, quattro limiti", paragraphs: ["Scuola più obbligatoria ma finanziata da comuni diseguali; voto triplicato ma ancora maschile e minoritario; abolizione del macinato ma ritorno del deficit; maggiore spesa ma dipendenza da mediazioni e appalti.", "Ogni riforma creò capacità nuove e lasciò un confine. Il limite non annulla il risultato; il risultato non cancella l'esclusione."], summary: "La cifra della stagione è una serie di aperture incomplete, non un fallimento totale né una democratizzazione compiuta." },
        { title: "Attori, gruppi e conflitti: il paese entra in scena", paragraphs: ["Radicali, socialisti, operai, braccianti e cattolici organizzarono domande che il Parlamento non poteva rappresentare pienamente. La società divenne più politica prima che il sistema diventasse democratico.", "Il governo reagì con riforme selettive, cooptazione e repressione. Il trasformismo integrava i moderati, ma lasciava ai margini proprio le forze che stavano costruendo organizzazioni di massa."], summary: "La crescita della società organizzata rese insufficiente il Parlamento dei notabili." },
        { title: "Il processo storico: dal consenso interno al prestigio esterno", paragraphs: ["Spesa pubblica, ferrovie e protezionismo costruirono alleanze fra Stato, imprese e proprietari. Non risolsero la crisi agraria né i divari; contribuirono però alle condizioni della successiva industrializzazione.", "Triplice Alleanza e colonialismo cercarono riconoscimento internazionale. La politica estera divenne un modo per compensare fragilità interne, ma generò costi e contraddizioni che l'età di Crispi avrebbe ampliato."], summary: "Modernizzazione economica e prestigio esterno si sostennero a vicenda senza includere tutti nello stesso modo." },
        { title: "Conseguenze e nuovo assetto: verso la politica di massa", paragraphs: ["Alla morte di Depretis nel luglio 1887, l'Italia era più alfabetizzata, più collegata, più partecipata e più organizzata di undici anni prima. Era anche più protezionista, militarmente impegnata in Africa e legata agli imperi centrali.", "Il sistema liberale aveva allargato la propria base senza creare partiti capaci di organizzare stabilmente il consenso. Le tensioni fra riforma e autorità, società e Parlamento, nazione e impero restavano aperte."], summary: "La Sinistra preparò tanto l'allargamento della politica quanto le crisi del liberalismo notabilare." },
        { title: "Conclusione: modernizzazione contraddittoria", paragraphs: ["Democratizzazione descrive una direzione, non un risultato compiuto. Continuità liberale coglie le strutture, ma rischia di nascondere riforme e nuove forze sociali. La formula più precisa è modernizzazione contraddittoria.", "La Sinistra ampliò capacità e partecipazione mentre difendeva il centro notabilare; alleggerì alcune imposte mentre proteggeva interessi forti; cercò sicurezza mentre entrava nel colonialismo. La sua importanza sta proprio in queste tensioni."], summary: "Lo Stato divenne più aperto e più complesso, non ancora democratico in senso pieno." }
      ],
      source: { id: "corso-forzoso", title: "Banca d'Italia: l'abolizione del corso forzoso e i suoi effetti", prompt: "Usa la fonte per mostrare come una riforma finanziaria possa produrre fiducia, espansione e nuovi rischi nello stesso tempo." },
      activity: { title: "Costruisci il verdetto", prompt: "Scegli una delle tre formule — democratizzazione, continuità liberale, modernizzazione contraddittoria — e difendila con quattro prove. Poi formula l'obiezione più forte e rispondi." },
      coordinates: ["1876-1887: governi della Sinistra storica", "1882: suffragio allargato e Triplice", "1884: macinato abolito", "1885: ferrovie e Massaua", "1887: protezionismo e Dogali", "29 luglio 1887: morte di Depretis e ascesa di Crispi"],
      essentials: ["La Sinistra ereditò e conservò l'architettura centrale dello Stato.", "Le riforme ampliarono davvero scuola e voto.", "Il suffragio rimase maschile e minoritario.", "Il trasformismo integrò moderati ma indebolì l'alternanza.", "Nuove organizzazioni sociali superarono il solo notabilato.", "Il protezionismo distribuì benefici e costi in modo diseguale.", "La Triplice ridusse l'isolamento e creò contraddizioni irredentiste.", "Dogali mostrò i limiti del progetto coloniale.", "Modernizzazione contraddittoria collega risultati e costi senza annullarli."],
      vocab: { Democratizzazione: "Processo di ampliamento effettivo di diritti, partecipazione e controllo sul potere.", Liberalismo_notabilare: "Sistema costituzionale governato da élite locali e parlamentari senza partiti di massa.", Modernizzazione: "Trasformazione di istituzioni, economia e società; non implica automaticamente uguaglianza.", Cooptazione: "Integrazione di oppositori o gruppi dirigenti nell'area di governo.", Continuita: "Persistenza di strutture e pratiche nonostante il cambio di maggioranza." },
      answer: "La formula più completa è modernizzazione contraddittoria. La Sinistra democratizzò alcuni accessi ma conservò il liberalismo notabilare; promosse sviluppo selettivo e stabilità centrista, mentre nuove forze sociali e il colonialismo aprivano conflitti che il sistema non era ancora capace di rappresentare.",
      connections: { map: "Quattro tensioni della Sinistra storica", people: ["depretis", "crispi", "minghetti"] }
    },
    {
      id: "riforme", number: 2, title: "Scuola, voto e fisco: chi entra nello Stato?", eyebrow: "Promesse, risultati, limiti", period: "1877-1884",
      question: "Le riforme della Sinistra trasformarono gli amministrati in cittadini oppure ampliarono soltanto una minoranza politica?",
      lead: "Legge Coppino, riforma elettorale, abolizione del macinato e ritorno alla convertibilità modificarono il rapporto con lo Stato. I loro effetti furono però diseguali perché dipendevano da alfabetizzazione, risorse comunali, sesso e posizione sociale.",
      sections: [
        { title: "Il mondo precedente: obblighi senza mezzi uguali", paragraphs: ["La legge Casati aveva già dichiarato gratuita e obbligatoria l'istruzione elementare inferiore, ma affidava ai comuni gran parte delle spese. Nei territori poveri mancavano edifici, maestri e controlli; lavoro infantile e distanze rendevano difficile la frequenza.", "Il voto era riservato a uomini di almeno venticinque anni con requisiti di censo e capacità. Alla metà degli anni Settanta gli elettori erano circa seicentomila, poco più del due per cento della popolazione."], summary: "Scuola e rappresentanza esistevano, ma raggiungevano una parte minima e territorialmente diseguale della società." },
        { title: "Le fratture: l'obbligo scolastico diventa più esigente", paragraphs: ["La legge Coppino del 15 luglio 1877 rese obbligatoria la frequenza dai sei ai nove anni e introdusse sanzioni per i genitori inadempienti. Al posto dell'insegnamento religioso obbligatorio pose le prime nozioni dei doveri dell'uomo e del cittadino, rafforzando la laicità della scuola pubblica.", "La norma non trasferì però allo Stato tutti i costi. I comuni poveri continuarono a disporre di meno scuole e insegnanti. Una legge uguale produceva effetti diversi quando le capacità amministrative e familiari erano diseguali."], summary: "La Coppino rafforzò obbligo e cittadinanza laica, ma non colmò automaticamente il divario delle risorse." },
        { title: "Attori, gruppi e conflitti: nuovi elettori e grandi esclusi", paragraphs: ["La riforma del 1882 abbassò l'età a ventun anni e privilegiò il criterio della capacità: potevano votare uomini alfabetizzati o in possesso del titolo elementare, mentre il requisito fiscale restava come alternativa ridotta a 19,80 lire.", "Gli elettori superarono i due milioni, circa il 6,9 per cento della popolazione. Entrarono parti delle classi urbane e operaie alfabetizzate; restarono escluse tutte le donne e la grande maggioranza degli uomini analfabeti, soprattutto nelle campagne e nelle aree con scuola più debole."], summary: "L'elettorato triplicò, ma cittadinanza politica e popolazione continuarono a non coincidere." },
        { title: "Il processo storico: dal macinato alla moneta convertibile", paragraphs: ["La tassa sul macinato, simbolo della fiscalità impopolare, fu ridotta nel 1880 e abolita definitivamente nel 1884. La misura alleggerì i consumi popolari, ma ridusse entrate mentre la spesa per opere pubbliche e armamenti cresceva.", "La legge Magliani del 1881 preparò l'abolizione del corso forzoso, attuata nel 1883: le banconote tornarono convertibili in metallo. La fiducia e l'afflusso di capitali sostennero l'espansione, ma la convertibilità durò pochi anni e contribuì anche a un clima speculativo."], summary: "La Sinistra sostituì il rigore assoluto con maggiore spesa e alleggerimenti selettivi, riaprendo il problema del disavanzo." },
        { title: "Conseguenze e nuovo assetto: istruzione e voto si legano", paragraphs: ["La riforma elettorale fece della scuola una soglia di accesso alla politica. In teoria premiava la capacità; in pratica favoriva territori, ceti e generi che avevano già maggiore accesso all'alfabetizzazione.", "Nel 1882 Andrea Costa divenne il primo deputato socialista. Il suo ingresso mostrò che l'allargamento poteva aprire una breccia alle nuove forze; un solo eletto ricordava però quanto quella breccia fosse stretta."], summary: "L'alfabetizzazione divenne insieme diritto educativo e requisito politico, riproducendo differenze sociali preesistenti." },
        { title: "Conclusione: riforme vere, cittadinanza incompleta", paragraphs: ["La Sinistra non si limitò alle promesse: scuola, suffragio e fisco cambiarono. Sarebbe sbagliato liquidare tutto come propaganda. Sarebbe ugualmente sbagliato chiamare democratico un sistema che escludeva più di nove abitanti su dieci.", "Il criterio corretto non è chiedere se le riforme furono perfette, ma quali capacità ampliarono, quali vincoli lasciarono e quali nuovi conflitti resero politicamente visibili."], summary: "Lo Stato liberale si aprì, ma stabilì l'ingresso attraverso porte che molti non potevano ancora raggiungere." }
      ],
      source: { id: "legge-elettorale", title: "Legge elettorale del 1882: capacità, censo, sistema", prompt: "Ricostruisci chi acquisisce il voto, chi rimane escluso e perché l'alfabetizzazione non è un criterio socialmente neutrale." },
      activity: { title: "Una riforma, tre prospettive", prompt: "Valuta la riforma del 1882 dal punto di vista di un operaio alfabetizzato, una contadina analfabeta e un notabile. Per ciascuno indica opportunità, esclusione o timore." },
      coordinates: ["15 luglio 1877: legge Coppino", "1880-1884: riduzione e abolizione del macinato", "22 gennaio e 7 maggio 1882: riforma elettorale", "1882: oltre due milioni di elettori", "1883: ritorno alla convertibilità della lira"],
      essentials: ["La legge Coppino rese più effettivo l'obbligo dai sei ai nove anni.", "I comuni continuarono a sostenere gran parte dei costi scolastici.", "La riforma elettorale abbassò l'età a ventun anni.", "Il requisito di capacità divenne centrale, il censo restò come alternativa.", "Gli elettori passarono da circa 2,2 a 6,9 per cento della popolazione.", "Donne e gran parte degli analfabeti restarono esclusi.", "La tassa sul macinato fu abolita nel 1884.", "La convertibilità monetaria fu ristabilita nel 1883 ma durò poco."],
      vocab: { Legge_Coppino: "Legge del 1877 che rafforzò l'obbligo elementare e la laicità dell'insegnamento.", Suffragio_allargato: "Estensione del voto a nuovi gruppi senza raggiungere il suffragio universale.", Scrutinio_di_lista: "Sistema in cui un collegio elegge più deputati e l'elettore vota più candidati.", Corso_forzoso: "Inconvertibilità legale delle banconote in moneta metallica.", Imposta_indiretta: "Prelievo legato a consumi e scambi, spesso gravoso in proporzione sui redditi bassi." },
      answer: "Le riforme trasformarono realmente il rapporto con lo Stato: più bambini furono obbligati alla scuola, il corpo elettorale triplicò e un'imposta odiata scomparve. La cittadinanza rimase però incompleta, perché accesso all'istruzione, sesso e condizione economica continuarono a selezionare chi poteva partecipare.",
      connections: { map: "Più elettori, non suffragio universale", people: ["depretis", "crispi", "minghetti"] }
    },
    {
      id: "trasformismo", number: 3, title: "Governare trasformando le maggioranze", eyebrow: "Stabilità e opacità", period: "1882-1887",
      question: "Il trasformismo fu una soluzione ragionevole alla frammentazione o un sistema che svuotò il confronto politico?",
      lead: "Dopo l'allargamento del voto, Depretis cercò una grande maggioranza centrale con moderati provenienti da Sinistra e Destra. Il metodo stabilizzò i governi, ma legò consenso, amministrazione e interessi locali.",
      sections: [
        { title: "Il mondo precedente: partiti senza organizzazione", paragraphs: ["Destra e Sinistra erano raggruppamenti parlamentari, non partiti nazionali dotati di iscritti, sezioni e disciplina. I deputati dipendevano da prestigio personale, reti locali e capacità di ottenere opere o decisioni favorevoli al collegio.", "La distanza programmatica fra i moderati dei due schieramenti si era ridotta. Entrambi accettavano monarchia, Statuto, proprietà privata e centralismo; divergevano su tempi e intensità delle riforme."], summary: "Il trasformismo nacque in un sistema privo di partiti moderni e con una vasta area liberale condivisa." },
        { title: "Le fratture: il voto si allarga, il centro teme le estreme", paragraphs: ["La riforma del 1882 poteva rafforzare radicali, repubblicani e socialisti. Depretis temeva che una contrapposizione rigida spingesse il Parlamento verso una polarizzazione che il giovane Stato non fosse capace di assorbire.", "Tra 1882 e 1883 cercò quindi l'intesa con Marco Minghetti e con settori della vecchia Destra. La formula della trasformazione indicava il superamento delle appartenenze storiche in nome di un centro costituzionale."], summary: "L'apertura elettorale produsse anche una strategia di contenimento delle opposizioni." },
        { title: "Attori, gruppi e conflitti: Depretis, Minghetti e la Pentarchia", paragraphs: ["Depretis costruì maggioranze mobili; Minghetti riconobbe la possibilità di collaborazione fra moderati. Contro questa convergenza si raccolsero Crispi, Cairoli, Nicotera, Zanardelli e Baccarini, la cosiddetta Pentarchia, divisa però da rivalità personali e politiche.", "Prefetti, ministeri, appalti e lavori pubblici potevano orientare i collegi. Non ogni accordo era corruzione, ma la dipendenza dalle risorse amministrative favoriva clientelismo e scambio di favori."], summary: "Il centro si allargò mentre le opposizioni interne faticavano a costruire un'alternativa coerente." },
        { title: "Il processo storico: maggioranze plastiche", paragraphs: ["Il governo negoziava provvedimento per provvedimento con gruppi e singoli deputati. Questa elasticità permetteva di approvare riforme e di assorbire dissensi senza crisi definitive.", "La stessa elasticità rendeva difficile capire quale programma gli elettori avessero premiato e quale opposizione potesse sostituire il governo. La responsabilità politica si spostava dal confronto pubblico alla mediazione personale e amministrativa."], summary: "La flessibilità ridusse le fratture parlamentari, ma anche la leggibilità delle scelte." },
        { title: "Conseguenze e nuovo assetto: un centro senza alternanza", paragraphs: ["Il trasformismo contribuì alla continuità governativa e impedì una brusca divisione del campo liberale. Integrò parte della Destra nel nuovo equilibrio e isolò le forze considerate antisistema.", "Nel lungo periodo favorì personalismo, dipendenza dei collegi dal governo e sfiducia verso il Parlamento. Non fu un'esclusiva del Mezzogiorno: derivò dalle strutture generali dello Stato liberale, pur assumendo forme diverse nei territori."], summary: "Il sistema guadagnò stabilità, ma perse chiarezza programmatica e capacità di alternanza." },
        { title: "Conclusione: compromesso o svuotamento?", paragraphs: ["Il giudizio non deve essere automatico. In assenza di partiti disciplinati, il compromesso era parte del funzionamento parlamentare; una coalizione centrale poteva evitare avventure autoritarie o rivoluzionarie.", "Il problema nasce quando l'accordo non è fondato su obiettivi verificabili, ma su distribuzione di risorse e fedeltà personali. Il trasformismo fu quindi insieme risposta strutturale e moltiplicatore delle debolezze del sistema."], summary: "Non basta dire che il trasformismo fu corrotto: bisogna spiegare perché apparve utile e quali incentivi lo resero opaco." }
      ],
      source: { id: "trasformismo-fonte", title: "Trasformismo: origine, meccanismi e conseguenze", prompt: "Separa la definizione polemica del termine dalla ricostruzione delle strutture parlamentari che lo resero possibile." },
      activity: { title: "Patto pubblico o accordo personale?", prompt: "Scrivi tre condizioni che renderebbero legittima una grande coalizione e tre segnali che la trasformerebbero in clientelismo. Applica i criteri al caso Depretis-Minghetti." },
      coordinates: ["1882: allargamento del voto", "1883: consolidamento dell'accordo Depretis-Minghetti", "1883: formazione della Pentarchia", "Prefetti e amministrazione influenzano i collegi", "1887: morte di Depretis"],
      essentials: ["Il trasformismo fu favorito dall'assenza di partiti moderni.", "Moderati di Destra e Sinistra condividevano il quadro costituzionale.", "Depretis voleva isolare radicali, repubblicani e socialisti.", "Minghetti collaborò alla costruzione del centro.", "La Pentarchia non divenne un'opposizione compatta.", "Opere pubbliche e amministrazione potevano costruire consenso.", "Il fenomeno non va spiegato con stereotipi territoriali.", "Stabilità e responsabilità politica entrarono in tensione."],
      vocab: { Trasformismo: "Costruzione di maggioranze centriste e mobili mediante accordi fra deputati provenienti da schieramenti diversi.", Pentarchia: "Gruppo di cinque leader della Sinistra che si oppose al centro depetrisiano.", Clientelismo: "Scambio asimmetrico di favori e sostegno politico attraverso relazioni personali.", Maggioranza_mobile: "Coalizione che cambia composizione secondo provvedimenti e negoziazioni.", Opposizione: "Forze che controllano il governo e propongono un'alternativa riconoscibile." },
      answer: "Il trasformismo rispose a frammentazione, debolezza dei partiti e timore delle estreme. Poteva produrre compromessi e continuità, ma quando legava il voto a favori amministrativi riduceva responsabilità, opposizione e chiarezza programmatica. Fu una soluzione che rafforzò proprio i difetti da cui nasceva.",
      connections: { map: "La società entra in politica da porte diverse", people: ["depretis", "minghetti", "crispi"] }
    },
    {
      id: "societa-organizzata", number: 4, title: "Una società che si organizza fuori dal Parlamento", eyebrow: "Radicali, socialisti e cattolici", period: "1871-1886",
      question: "Perché nuove forze sociali cercarono organizzazione politica proprio mentre lo Stato liberale ampliava il voto?",
      lead: "L'apertura dello Stato non assorbì tutte le domande. Radicali, lavoratori e cattolici costruirono associazioni, giornali, leghe, opere sociali e primi partiti: la politica cominciò a uscire dal solo Parlamento dei notabili.",
      sections: [
        { title: "Il mondo precedente: mutuo soccorso e internazionalismo", paragraphs: ["Le società di mutuo soccorso fornivano ai lavoratori assistenza in caso di malattia, disoccupazione o morte. Erano luoghi di solidarietà e formazione civile, spesso influenzati da tradizioni mazziniane o moderate.", "Dopo la Comune di Parigi del 1871, l'Internazionale raccolse gruppi anarchici e rivoluzionari. I tentativi insurrezionali fallirono per isolamento sociale, debole organizzazione, scarsa preparazione e repressione."], summary: "Prima dei partiti di massa esistevano reti associative capaci di trasformare bisogni privati in domande collettive." },
        { title: "Le fratture: dalla rivolta episodica all'organizzazione", paragraphs: ["Nel 1879 Andrea Costa pubblicò Ai miei amici di Romagna. Senza rinnegare l'obiettivo rivoluzionario, sosteneva che un movimento dovesse occuparsi degli affari quotidiani, organizzarsi e utilizzare anche elezioni e amministrazioni.", "Nel 1881 nacque il Partito socialista rivoluzionario di Romagna; nel 1884 assunse dimensione italiana. Nel 1882 associazioni milanesi fondarono il Partito operaio, più nettamente classista e legato a leghe di lavoratori."], summary: "Il socialismo italiano cominciò a spostarsi dall'insurrezione alla politica organizzata e alle lotte quotidiane." },
        { title: "Attori, gruppi e conflitti: radicali, operai, braccianti", paragraphs: ["I radicali di Bertani e Cavallotti chiedevano suffragio universale maschile, laicità e riforme sociali. Operai urbani e braccianti rurali avevano condizioni e priorità diverse; collegarli in un'unica organizzazione fu difficile.", "Gli scioperi agricoli del 1884-1885 nella Bassa Padana mostrarono la crescita del conflitto rurale. Il governo alternò tolleranza e repressione; nel 1886 colpì duramente il Partito operaio italiano."], summary: "La questione sociale non apparteneva soltanto alla fabbrica: coinvolgeva campagne, città e forme di lavoro differenti." },
        { title: "Il processo storico: i cattolici costruiscono una società parallela", paragraphs: ["Dopo la presa di Roma, il non expedit invitò i cattolici a non partecipare alle elezioni politiche; formulato pubblicamente nel 1874, fu chiarito come divieto nel 1886. Non impediva nello stesso modo l'attività amministrativa e sociale.", "L'Opera dei congressi, nata nel 1874, coordinò associazioni, cooperative, casse rurali, scuole e opere assistenziali. Contestava il liberalismo laico e il socialismo, ma mobilitava migliaia di laici dentro la società italiana."], summary: "L'astensione politica nazionale non significò passività sociale: i cattolici costruirono reti durevoli." },
        { title: "Conseguenze e nuovo assetto: lo Stato non è più l'unico organizzatore", paragraphs: ["Socialisti e cattolici offrivano appartenenza, assistenza e linguaggi collettivi a persone quasi assenti dal Parlamento. Le loro reti anticipavano i partiti di massa e rendevano insufficiente una politica fondata soltanto sui notabili.", "La classe dirigente liberale oscillò fra integrazione, riforme, sorveglianza e repressione. Ogni scelta poteva rafforzare o delegittimare lo Stato presso gruppi che stavano imparando ad agire insieme."], summary: "La società organizzata impose allo Stato liberale interlocutori che non poteva più ignorare." },
        { title: "Conclusione: la massa prima della democrazia di massa", paragraphs: ["Negli anni Ottanta non esisteva ancora una piena società di massa, ma ne apparivano le infrastrutture: giornali, associazioni, partiti, leghe, cooperative e congressi.", "L'allargamento del voto fu una causa e insieme una risposta parziale. Le nuove forze non nacquero perché lo Stato le concesse: nacquero anche dai limiti dell'inclusione liberale."], summary: "La politica si allargò nello Stato e fuori dallo Stato, preparando conflitti che il trasformismo non poteva assorbire per sempre." }
      ],
      source: { id: "costa-lettera", title: "Andrea Costa, Ai miei amici di Romagna", prompt: "Individua quali strumenti politici Costa aggiunge all'insurrezione e perché la sua svolta non equivale ancora al riformismo moderato." },
      activity: { title: "Tre vie all'organizzazione", prompt: "Confronta società di mutuo soccorso, partito socialista e Opera dei congressi per base sociale, obiettivi, rapporto con lo Stato e strumenti d'azione." },
      coordinates: ["1871: Comune di Parigi e nuovo impulso internazionalista", "1874: Opera dei congressi e pronunciamento pubblico del non expedit", "1879: Ai miei amici di Romagna", "1881: partito socialista rivoluzionario in Romagna", "1882: Andrea Costa deputato e nascita del Partito operaio", "1884-1885: scioperi bracciantili", "1886: repressione del Partito operaio e conferma del non expedit"],
      essentials: ["Il mutuo soccorso precede i partiti di massa.", "L'internazionalismo italiano ebbe una forte componente anarchica.", "Costa propose organizzazione, propaganda e partecipazione politica.", "Nel 1882 fu eletto il primo deputato socialista.", "Il Partito operaio cercò autonomia di classe.", "Operai urbani e braccianti rurali non avevano interessi identici.", "Il non expedit riguardava soprattutto le elezioni politiche.", "L'Opera dei congressi sviluppò una vasta azione sociale cattolica."],
      vocab: { Mutuo_soccorso: "Associazione che assiste i soci attraverso contributi comuni.", Internazionalismo: "Movimento che collega l'emancipazione dei lavoratori oltre i confini nazionali.", Anarchismo: "Corrente socialista ostile allo Stato e favorevole all'azione diretta e federativa.", Non_expedit: "Indicazione pontificia di non partecipazione dei cattolici alle elezioni politiche italiane.", Opera_dei_congressi: "Rete nazionale del cattolicesimo intransigente attiva sul piano religioso e sociale." },
      answer: "Le nuove forze si organizzarono perché industrializzazione, crisi agricola, alfabetizzazione e associazionismo rendevano visibili bisogni che il Parlamento dei notabili non rappresentava. L'apertura elettorale offrì strumenti, ma esclusioni e repressione spinsero socialisti e cattolici a costruire reti autonome.",
      connections: { map: "La società entra in politica da porte diverse", people: ["depretis", "crispi", "pio-ix"] }
    }
  ],
  people: [
    { id: "depretis", name: "Agostino Depretis", dates: "1813-1887", role: "Presidente del Consiglio e leader della Sinistra", image: "assets/img/people/depretis.jpg", bio: "Protagonista del Risorgimento moderato, guidò otto governi fra 1876 e 1887. Collegò riforme, mediazione parlamentare e costruzione di maggioranze centriste.", idea: "Aprire gradualmente il sistema senza consegnarlo alle estreme; il metodo produsse riforme e trasformismo." },
    { id: "minghetti", name: "Marco Minghetti", dates: "1818-1886", role: "Ultimo presidente della Destra e interlocutore di Depretis", image: "assets/img/people/minghetti.jpg", bio: "Il suo governo cadde il 18 marzo 1876. Dopo l'alternanza collaborò alla convergenza dei moderati che avrebbe sostenuto il centro depetrisiano.", idea: "La continuità costituzionale contava più della sopravvivenza della distinzione storica fra Destra e Sinistra." },
    { id: "crispi", name: "Francesco Crispi", dates: "1818-1901", role: "Ex democratico, ministro e futuro presidente del Consiglio", image: "assets/img/people/crispi.jpg", bio: "Garibaldino e repubblicano divenuto monarchico, fu una delle personalità più forti della Sinistra. Si oppose al trasformismo nella Pentarchia e succedette a Depretis nel 1887.", idea: "Nazione, autorità e prestigio internazionale avrebbero trovato nell'età successiva una sintesi più aggressiva." },
    { id: "pio-ix", name: "Pio IX", dates: "1792-1878", role: "Pontefice e avversario dello Stato unitario", image: "assets/img/people/pio-ix.jpg", bio: "Dopo la perdita di Roma rifiutò di riconoscere la legittimità del nuovo assetto. Il non expedit orientò i cattolici lontano dalle elezioni politiche ma non dall'organizzazione sociale.", idea: "L'assenza dalle urne poteva convivere con una presenza capillare nella società." }
  ],
  timeline: [
    { date: "1874", title: "Opera dei congressi e non expedit", text: "Il cattolicesimo intransigente coordina associazioni e conferma la distanza dalle elezioni politiche.", scale: "Società" },
    { date: "10 ott. 1875", title: "Programma di Stradella", text: "Depretis presenta suffragio, scuola, fisco e autonomie come assi della futura Sinistra di governo.", scale: "Italia" },
    { date: "18 mar. 1876", title: "Rivoluzione parlamentare", text: "La Camera sconfigge Minghetti; la maggioranza passa alla Sinistra senza rottura istituzionale.", scale: "Parlamento" },
    { date: "15 lug. 1877", title: "Legge Coppino", text: "L'obbligo elementare viene rafforzato dai sei ai nove anni con sanzioni e contenuto civico laico.", scale: "Italia" },
    { date: "1877", title: "Inchiesta agraria", text: "Il Parlamento avvia l'indagine poi presieduta da Jacini sulle campagne e sulle classi agricole.", scale: "Economia" },
    { date: "1878", title: "Congresso di Berlino", text: "L'Italia mantiene le mani nette e non ottiene compensi territoriali.", scale: "Europa" },
    { date: "1879", title: "Ai miei amici di Romagna", text: "Andrea Costa propone organizzazione e lotta politica quotidiana oltre l'insurrezione episodica.", scale: "Società" },
    { date: "1880", title: "Riduzione del macinato", text: "Inizia l'eliminazione dell'imposta più simbolicamente legata ai costi popolari della costruzione statale.", scale: "Economia" },
    { date: "1881", title: "Tunisia francese", text: "Il trattato del Bardo instaura il protettorato e alimenta in Italia la percezione dello schiaffo di Tunisi.", scale: "Mediterraneo" },
    { date: "22 gen. 1882", title: "Suffragio allargato", text: "Età più bassa e criterio di capacità ampliano il corpo elettorale a oltre due milioni di uomini.", scale: "Parlamento" },
    { date: "20 mag. 1882", title: "Triplice Alleanza", text: "Italia, Germania e Austria-Ungheria firmano un patto segreto e difensivo.", scale: "Europa" },
    { date: "1882", title: "Costa deputato e Assab allo Stato", text: "Un socialista entra alla Camera mentre lo Stato acquisisce il primo possedimento sul Mar Rosso.", scale: "Italia" },
    { date: "1883", title: "Centro Depretis-Minghetti", text: "La collaborazione fra moderati consolida il trasformismo; la lira torna convertibile.", scale: "Parlamento" },
    { date: "1884", title: "Macinato abolito", text: "L'imposta scompare; si concludono le principali pubblicazioni dell'Inchiesta Jacini.", scale: "Economia" },
    { date: "1885", title: "Ferrovie e Massaua", text: "Le convenzioni affidano l'esercizio ferroviario a società private; l'Italia occupa Massaua.", scale: "Mediterraneo" },
    { date: "1886", title: "Organizzazioni sotto pressione", text: "Il Partito operaio è represso e il non expedit viene precisato come divieto.", scale: "Società" },
    { date: "26 gen. 1887", title: "Dogali", text: "Le forze di ras Alula distruggono la colonna De Cristoforis, mostrando i limiti dell'espansione italiana.", scale: "Africa" },
    { date: "1887", title: "Tariffa e fine della stagione", text: "Il protezionismo si rafforza; Depretis muore il 29 luglio e Crispi assume la guida del governo.", scale: "Italia" }
  ],
  maps: [
    { title: "Più elettori, non suffragio universale", image: "assets/img/maps/suffragio.svg", alt: "Grafico sul passaggio da circa 2,2 a 6,9 per cento della popolazione ammessa al voto", text: "La riforma triplicò il corpo elettorale. La scala del cambiamento è significativa; la quota mostra però che la politica restava affare di una minoranza maschile.", note: "Valori arrotondati sulla popolazione complessiva; non indicano la percentuale dei soli uomini adulti." },
    { title: "La società entra in politica da porte diverse", image: "assets/img/maps/forze-sociali.svg", alt: "Schema delle relazioni fra Stato, radicali, socialisti, lavoratori e cattolici", text: "Riforme e repressione non spiegano da sole la nuova politica: gruppi diversi costruiscono organizzazioni con interessi, linguaggi e rapporti differenti verso lo Stato.", note: "Schema relazionale, non misura numerica della forza dei movimenti." },
    { title: "Benefici e costi del protezionismo", image: "assets/img/maps/protezionismo.svg", alt: "Schema dei gruppi favoriti e penalizzati dalla tariffa del 1887", text: "La tariffa forma una coalizione fra industria e cerealicoltura protetta, mentre trasferisce costi su consumatori e produzioni esportatrici.", note: "La carta semplifica interessi prevalenti; territori e settori contenevano posizioni interne diverse." },
    { title: "Dall'isolamento al Mar Rosso", image: "assets/img/maps/mediterraneo.svg", alt: "Mappa schematica di Tunisia, Triplice Alleanza e direttrice verso il Mar Rosso", text: "Tunisia, alleanza europea e primi possedimenti africani appartengono alla stessa ricerca di sicurezza e prestigio, ma non costituiscono un piano unico già definito.", note: "Carta concettuale non in scala; i tracciati indicano relazioni politiche, non rotte precise." }
  ],
  sources: [
    { id: "sinistra-depretis", title: "Sinistra storica italiana e Depretis", type: "Sintesi accademica", date: "1875-1876", author: "Istituto della Enciclopedia Italiana", provenance: "Dizionario di Storia e Dizionario Biografico degli Italiani", verbatim: false, excerpt: ["La Sinistra riuniva tradizioni democratiche, garibaldine e liberali costituzionali.", "Come la Destra, era un raggruppamento di notabili privo di organizzazione permanente.", "Il programma riformatore non implicava l'abbandono di monarchia e Statuto."], context: "Passaggio dalla lunga egemonia della Destra ai governi della Sinistra.", audience: "Lettori di opere storico-enciclopediche.", purpose: "Definire composizione, programma e limiti della Sinistra.", limits: "Una sintesi ricostruisce il quadro generale e non sostituisce discorsi, atti elettorali e corrispondenza politica.", interpretation: "La svolta del 1876 è comprensibile solo tenendo insieme differenza di programma e continuità sociale.", questions: ["Quali tradizioni confluiscono nella Sinistra?", "Che cosa la rende simile alla Destra?", "Quale prova servirebbe per misurare il suo seguito sociale?"], url: "https://www.treccani.it/enciclopedia/sinistra-storica-italiana_%28Dizionario-di-Storia%29/" },
    { id: "coppino", title: "Legge 15 luglio 1877, n. 3961", type: "Legge dello Stato", date: "1877", author: "Parlamento e Corona del Regno d'Italia", provenance: "Normattiva", verbatim: false, excerpt: ["La frequenza dell'istruzione elementare inferiore viene resa obbligatoria.", "Sono previste procedure e sanzioni per gli inadempienti.", "L'educazione civica laica sostituisce l'obbligo dell'insegnamento religioso."], context: "Riforma della scuola elementare durante il primo governo Depretis.", audience: "Comuni, famiglie, autorità scolastiche e amministrative.", purpose: "Rendere più effettivo l'obbligo e formare cittadini.", limits: "Il testo normativo dice ciò che deve avvenire, non misura scuole, maestri, frequenza ed effetti territoriali.", interpretation: "Il diritto va confrontato con la capacità finanziaria dei comuni e con le condizioni delle famiglie.", questions: ["Chi deve applicare la legge?", "Quali costi non sono risolti dal testo?", "Perché la laicità ha significato politico?"], url: "https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:legge:1877-07-15;3961" },
    { id: "legge-elettorale", title: "Riforma elettorale del 1882", type: "Legge e dibattito parlamentare", date: "1882", author: "Parlamento del Regno d'Italia", provenance: "Normattiva, Senato e Portale storico della Camera", verbatim: false, excerpt: ["L'età elettorale scende a ventun anni.", "Capacità alfabetica o titolo elementare aprono il voto; resta un requisito fiscale alternativo.", "Lo scrutinio di lista introduce collegi plurinominali."], context: "Realizzazione di uno dei principali punti del programma di Stradella.", audience: "Cittadini maschi, amministrazioni elettorali e collegi.", purpose: "Ampliare e ridefinire il corpo elettorale.", limits: "La legge definisce criteri; gli effetti richiedono dati su alfabetizzazione, iscrizioni e comportamento elettorale.", interpretation: "Un criterio formalmente uguale può produrre accessi diseguali quando la scuola è distribuita in modo diseguale.", questions: ["Chi entra?", "Chi resta escluso?", "Perché alfabetizzazione e censo non sono equivalenti?"], url: "https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=082U0593&atto.dataPubblicazioneGazzetta=1882-01-22&tipoDettaglio=originario" },
    { id: "trasformismo-fonte", title: "Trasformismo", type: "Interpretazione storico-politica", date: "1882-1887", author: "Enciclopedia delle scienze sociali", provenance: "Istituto della Enciclopedia Italiana", verbatim: false, excerpt: ["L'accordo Depretis-Minghetti separò una sinistra radicale dall'area governativa.", "La maggioranza divenne mobile e capace di ricomporsi attorno ai leader.", "L'area della legittimità costituzionale tese a monopolizzare il centro e a isolare le opposizioni."], context: "Convergenza dei moderati dopo l'allargamento del suffragio.", audience: "Studiosi e lettori di scienze sociali.", purpose: "Spiegare il fenomeno oltre il suo uso polemico.", limits: "Una categoria interpretativa può riunire pratiche diverse; va verificata sui singoli governi e collegi.", interpretation: "Il trasformismo è struttura e pratica: nasce dalla forma del sistema e può favorire comportamenti clientelari.", questions: ["Quale problema risolve?", "Quale alternativa blocca?", "Quando il compromesso diventa opaco?"], url: "https://www.treccani.it/enciclopedia/trasformismo_%28Enciclopedia-delle-scienze-sociali%29/" },
    { id: "costa-lettera", title: "Ai miei amici di Romagna", type: "Lettera politica", date: "27 luglio 1879", author: "Andrea Costa", provenance: "Ricostruzione del Dizionario Biografico degli Italiani", verbatim: false, excerpt: ["Il movimento deve rinnovarsi o lasciare ad altri i frutti del lavoro compiuto.", "L'organizzazione stabile deve sostituire l'azione episodica.", "L'impegno quotidiano e politico non cancella l'obiettivo socialista."], context: "Crisi dell'internazionalismo insurrezionale dopo fallimenti e repressione.", audience: "Compagni socialisti e anarchici della Romagna.", purpose: "Promuovere un partito organizzato e strumenti politici più ampi.", limits: "È un testo programmatico e autobiografico: giustifica una svolta e non rappresenta tutte le correnti socialiste.", interpretation: "Costa non passa semplicemente dalla rivoluzione al moderatismo; ridefinisce tempi e strumenti.", questions: ["Che cosa conserva del passato?", "Che cosa cambia?", "Perché il destinatario regionale conta?"], url: "https://www.treccani.it/enciclopedia/andrea-costa_%28Dizionario-Biografico%29/" },
    { id: "non-expedit", title: "Il non expedit e l'Opera dei congressi", type: "Direttiva ecclesiastica e rete associativa", date: "1874-1886", author: "Santa Sede e cattolicesimo intransigente", provenance: "Cristiani d'Italia, Istituto della Enciclopedia Italiana", verbatim: false, excerpt: ["Nel 1874 il non expedit viene formulato pubblicamente.", "Nel 1886 viene precisato come divieto, non semplice consiglio.", "L'astensione dalle politiche convive con associazioni, opere sociali e partecipazione locale."], context: "Conflitto fra Chiesa e Stato dopo la presa di Roma.", audience: "Cattolici italiani e organizzazioni ecclesiali.", purpose: "Negare legittimazione politica allo Stato unitario e coordinare la risposta cattolica.", limits: "La direttiva non descrive automaticamente il comportamento di tutti i cattolici né tutte le differenze locali.", interpretation: "Assenza elettorale e mobilitazione sociale sono processi compatibili, non opposti.", questions: ["Quali elezioni sono coinvolte?", "Quali spazi di azione restano?", "Perché l'Opera dei congressi è politicamente importante?"], url: "https://www.treccani.it/enciclopedia/il-non-expedit_%28Cristiani-d%27Italia%29/" },
    { id: "jacini", title: "Inchiesta agraria e condizioni della classe agricola", type: "Inchiesta parlamentare", date: "1877-1885", author: "Giunta parlamentare presieduta da Stefano Jacini", provenance: "Archivio centrale dello Stato e Dizionario Biografico degli Italiani", verbatim: false, excerpt: ["L'indagine raccoglie dati sull'intero Regno in quindici volumi.", "Descrive differenze regionali, tecniche, contratti e condizioni di vita.", "Le relazioni concludono proponendo bonifiche, credito, istruzione e miglioramenti produttivi."], context: "Crisi dell'agricoltura e crescente questione sociale rurale.", audience: "Parlamento, governo, proprietari e opinione pubblica.", purpose: "Conoscere condizioni tecniche e sociali per orientare la politica.", limits: "Questionari, commissari ed élite agrarie selezionano categorie e testimonianze; i contadini non parlano sempre con voce diretta.", interpretation: "È una miniera di informazioni e insieme un documento dello sguardo governativo sulle campagne.", questions: ["Chi produce i dati?", "Quali differenze emergono?", "Quali voci mancano o sono mediate?"], url: "https://www.treccani.it/enciclopedia/stefano-jacini_%28Dizionario-Biografico%29/" },
    { id: "triplice-fonte", title: "Triplice Alleanza", type: "Trattato diplomatico segreto", date: "20 maggio 1882", author: "Italia, Germania e Austria-Ungheria", provenance: "Archivio storico-diplomatico del MAECI", verbatim: false, excerpt: ["Il patto è difensivo e contiene obblighi diversi secondo l'aggressore.", "Italia e Germania si garantiscono contro un'aggressione francese.", "L'Italia chiede che l'intesa non sia diretta contro la Gran Bretagna."], context: "Rivalità con la Francia e ricerca italiana di protezione dopo la Tunisia.", audience: "Governi contraenti; il contenuto resta segreto all'opinione pubblica.", purpose: "Garantire sicurezza reciproca e isolare la Francia nel sistema bismarckiano.", limits: "Il testo stabilisce obblighi formali; applicazione e interpretazione dipendono dalle crisi concrete.", interpretation: "Alleanza non significa automatismo: natura della guerra e clausole determinano gli obblighi.", questions: ["Quando scatta l'aiuto?", "Quando basta la neutralità?", "Perché la Gran Bretagna è esclusa?"], url: "https://www.esteri.it/it/sala_stampa/archivionotizie/eventi/2018/11/mostra-alla-farnesina-su-storia-politica-estera-italiana/" },
    { id: "dogali-fonte", title: "Dogali e ras Alula", type: "Ricostruzione storico-biografica", date: "26 gennaio 1887", author: "Istituto della Enciclopedia Italiana", provenance: "Dizionario di Storia", verbatim: false, excerpt: ["Una colonna italiana di circa cinquecento uomini viene intercettata presso Dogali.", "Le forze sono guidate da ras Alula, governatore dell'Hamasien per Giovanni IV.", "La battaglia appartiene alla resistenza etiopica contro l'espansione dalla costa."], context: "Avanzata italiana da Massaua verso territori legati all'Impero etiopico.", audience: "Lettori di storia contemporanea.", purpose: "Ricostruire evento, protagonisti e collocazione politica.", limits: "Una breve voce non restituisce tutta la memoria italiana ed etiopica né l'esperienza dei combattenti.", interpretation: "La denominazione di sconfitta italiana va affiancata a quella di vittoria etiopica e difesa della sovranità.", questions: ["Chi agisce politicamente?", "Come cambia il racconto cambiando soggetto?", "Che cosa smentisce l'idea di una conquista facile?"], url: "https://www.treccani.it/enciclopedia/dogali_%28Dizionario-di-Storia%29/" },
    { id: "corso-forzoso", title: "Abolizione del corso forzoso", type: "Storia economica istituzionale", date: "1881-1887", author: "Banca d'Italia", provenance: "Sezione storica Le origini", verbatim: false, excerpt: ["L'abolizione viene decretata nel 1881 e attuata nel 1883.", "Il ritorno alla convertibilità alimenta fiducia, capitali ed espansione.", "Il surriscaldamento e la speculazione mostrano che la stabilità monetaria formale non basta."], context: "Rientro dell'Italia nel sistema monetario internazionale dopo il corso forzoso del 1866.", audience: "Cittadini, studiosi e lettori di storia monetaria.", purpose: "Spiegare origini istituzionali e crisi che precedono la Banca d'Italia.", limits: "La sintesi nazionale non distribuisce tutti gli effetti per settore e gruppo sociale.", interpretation: "Una riforma può essere positiva nel breve periodo e generare nuovi rischi attraverso il credito.", questions: ["Quale fiducia produce?", "Perché dura poco?", "Quale rapporto emerge fra moneta e speculazione?"], url: "https://www.bancaditalia.it/chi-siamo/storia/origini/index.html" }
  ],
  workshop: [
    { title: "Definisci il cambiamento", prompt: "Quale dimensione pesa di più nel tuo giudizio?", options: ["Diritti e partecipazione", "Strutture dello Stato rimaste intatte", "Nuove organizzazioni sociali"] },
    { title: "Valuta il metodo di governo", prompt: "Come interpreti il trasformismo?", options: ["Compromesso necessario", "Sistema clientelare", "Soluzione necessaria divenuta un problema"] },
    { title: "Segui benefici e costi", prompt: "Quale campo mostra meglio la contraddizione?", options: ["Scuola e voto", "Protezionismo e territori", "Alleanze e colonialismo"] },
    { title: "Scegli il concetto finale", prompt: "Quale formula organizza meglio le prove?", options: ["Democratizzazione", "Continuità liberale", "Modernizzazione contraddittoria"] }
  ],
  quiz: [
    { q: "Perché il 1876 è definito rivoluzione parlamentare?", options: ["Per una nuova costituzione", "Per l'alternanza prodotta dalla Camera senza rottura", "Per un'insurrezione garibaldina", "Per l'abolizione della monarchia"], answer: 1, why: "Il governo Minghetti fu sostituito da Depretis attraverso il mutamento della maggioranza parlamentare.", recover: "Rivedi che cosa cambia e che cosa resta nel 1876.", lesson: "rivoluzione-parlamentare" },
    { q: "Quale elemento NON appartiene al programma di Stradella?", options: ["Suffragio più largo", "Scuola elementare", "Alleggerimento fiscale", "Repubblica immediata"], answer: 3, why: "Depretis operava ormai entro monarchia e Statuto.", recover: "Confronta programma riformatore e quadro costituzionale.", lesson: "rivoluzione-parlamentare" },
    { q: "Che cosa rafforza la legge Coppino?", options: ["Obbligo elementare e sanzioni", "Università gratuita", "Voto femminile", "Gestione statale di tutte le scuole"], answer: 0, why: "La legge rende più esigente la frequenza elementare, ma lascia ai comuni molti costi.", recover: "Rileggi risultato e limite della riforma scolastica.", lesson: "riforme" },
    { q: "Quanto cresce approssimativamente il corpo elettorale sulla popolazione?", options: ["Dal 20 al 70%", "Dal 2,2 al 6,9%", "Dal 40 al 60%", "Dal 7 al 50%"], answer: 1, why: "Gli elettori superano i due milioni ma restano meno di sette abitanti su cento.", recover: "Apri la visualizzazione sul suffragio.", lesson: "riforme" },
    { q: "Chi resta escluso dopo il 1882?", options: ["Solo i militari", "Tutte le donne e molti uomini analfabeti", "Tutti i proprietari", "Tutti i cittadini urbani"], answer: 1, why: "Il voto rimane maschile e legato a capacità o censo.", recover: "Distingui allargamento da universalità.", lesson: "riforme" },
    { q: "Quale struttura favorisce il trasformismo?", options: ["Partiti disciplinati di massa", "Assenza di partiti moderni e peso dei notabili", "Suffragio universale", "Presidenzialismo"], answer: 1, why: "Maggioranze personali e reti locali rendono più facile la mobilità dei deputati.", recover: "Rivedi il mondo precedente del trasformismo.", lesson: "trasformismo" },
    { q: "Quale può essere un effetto positivo del trasformismo?", options: ["Abolire il Parlamento", "Stabilizzare compromessi fra moderati", "Creare suffragio femminile", "Eliminare i prefetti"], answer: 1, why: "La convergenza centrale può evitare crisi e polarizzazione.", recover: "Valuta insieme vantaggi e limiti.", lesson: "trasformismo" },
    { q: "Perché non va spiegato come difetto esclusivamente meridionale?", options: ["Perché non esisteva nel Sud", "Perché derivava da strutture nazionali del sistema liberale", "Perché lo imposero i socialisti", "Perché riguardava solo il re"], answer: 1, why: "Notabilato, amministrazione e assenza di partiti erano caratteristiche generali, pur con differenze territoriali.", recover: "Rileggi conseguenze e nuovo assetto.", lesson: "trasformismo" },
    { q: "Che cosa propone Andrea Costa nel 1879?", options: ["Solo terrorismo individuale", "Organizzazione e lotta politica quotidiana", "Ritorno al mazzinianesimo puro", "Alleanza con l'Austria"], answer: 1, why: "Costa amplia gli strumenti del movimento oltre l'insurrezione episodica.", recover: "Riapri la fonte Ai miei amici di Romagna.", lesson: "societa-organizzata" },
    { q: "Il non expedit implica totale passività cattolica?", options: ["Sì, vieta ogni associazione", "No, convive con attività sociale e locale", "Sì, vieta le cooperative", "No, perché obbliga a votare"], answer: 1, why: "L'astensione dalle politiche non impedisce l'Opera dei congressi e le opere sociali.", recover: "Confronta voto e organizzazione sociale.", lesson: "societa-organizzata" },
    { q: "Che cosa rende importante l'Inchiesta Jacini?", options: ["Dimostra una campagna uniforme", "Raccoglie dati sulle differenze agricole e sociali", "Abolisce i dazi", "Nazionalizza le ferrovie"], answer: 1, why: "I quindici volumi mostrano la pluralità delle campagne e le condizioni contadine.", recover: "Rivedi uso e limiti dell'inchiesta.", lesson: "economia-crisi" },
    { q: "Chi è favorito dalla tariffa del 1887?", options: ["Industria protetta e grandi cerealicoltori", "Solo i consumatori poveri", "Tutte le colture esportatrici", "Solo le casse rurali"], answer: 0, why: "Dazi industriali e cerealicoli costruiscono una coalizione protezionista.", recover: "Apri lo schema benefici e costi.", lesson: "economia-crisi" },
    { q: "Perché le convenzioni ferroviarie non sono piena privatizzazione?", options: ["Perché abolivano le società", "Perché lo Stato conservava proprietà e sussidi", "Perché vietavano profitti", "Perché riguardavano solo tram urbani"], answer: 1, why: "La gestione privata si combina con obblighi e garanzie pubbliche.", recover: "Rileggi il processo storico della lezione 5.", lesson: "economia-crisi" },
    { q: "Che cosa accelera il riavvicinamento agli imperi centrali?", options: ["La conquista italiana di Parigi", "Il protettorato francese sulla Tunisia", "La fine del canale di Suez", "La vittoria di Dogali"], answer: 1, why: "Lo schiaffo di Tunisi rafforza la percezione dell'isolamento italiano.", recover: "Rivedi la frattura diplomatica del 1881.", lesson: "triplice" },
    { q: "La Triplice obbliga l'Italia a sostenere ogni guerra degli alleati?", options: ["Sì, sempre", "No, è difensiva e condizionata", "Solo contro la Gran Bretagna", "Solo nelle guerre coloniali"], answer: 1, why: "Aggressore, numero delle potenze e clausole determinano gli obblighi.", recover: "Apri la fonte sul trattato.", lesson: "triplice" },
    { q: "Quale contraddizione crea l'alleanza con Vienna?", options: ["Il contrasto con l'irredentismo", "L'abolizione del Parlamento", "La perdita di Roma", "La fine del protezionismo"], answer: 0, why: "L'Austria-Ungheria controlla territori rivendicati dagli irredentisti italiani.", recover: "Rivedi attori e conflitti della lezione 6.", lesson: "triplice" },
    { q: "Che cosa dimostra Dogali?", options: ["Che il Corno d'Africa era vuoto", "Che l'Etiopia aveva capacità politica e militare", "Che l'Italia conquistò subito Addis Abeba", "Che ras Alula era alleato italiano"], answer: 1, why: "La vittoria di ras Alula mostra la forza di uno Stato africano sovrano.", recover: "Cambia punto di vista nella lezione 7.", lesson: "colonialismo" },
    { q: "Assab nasce inizialmente come…", options: ["Capitale dell'Etiopia", "Acquisto commerciale privato della Rubattino", "Protettorato francese", "Base tedesca"], answer: 1, why: "Nel 1869 la baia è acquistata dalla compagnia Rubattino; lo Stato subentra nel 1882.", recover: "Rivedi la sequenza Assab-Massaua-Dogali.", lesson: "colonialismo" },
    { q: "Quale formula coglie meglio il bilancio proposto?", options: ["Rivoluzione socialista", "Immobilità assoluta", "Modernizzazione contraddittoria", "Democrazia universale"], answer: 2, why: "La formula tiene insieme riforme reali, strutture elitarie e costi selettivi.", recover: "Rileggi la conclusione del percorso.", lesson: "bilancio" },
    { q: "Quale affermazione è storicamente più precisa?", options: ["I limiti annullano tutte le riforme", "Le riforme annullano tutte le esclusioni", "Risultati e limiti vanno spiegati insieme", "La politica estera è separata dalla società"], answer: 2, why: "Il metodo del modulo rifiuta sia celebrazione sia liquidazione: ricostruisce capacità, esclusioni e conseguenze.", recover: "Usa il laboratorio finale per costruire la tesi.", lesson: "bilancio" }
  ]
};
window.HIST_DATA.lessons.sort((a, b) => a.number - b.number);
