
const DATA=window.SITE_DATA;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={chapter:null,lesson:null};
const completed=new Set(JSON.parse(localStorage.getItem('completedLessons')||'[]'));
let fontScale=Number(localStorage.getItem('fontScale')||1);
let theme=localStorage.getItem('theme')||'light';
document.documentElement.dataset.theme=theme==='dark'?'dark':'';
document.documentElement.style.fontSize=(16*fontScale)+'px';

function icon(name){const paths={menu:'<path d="M4 7h16M4 12h16M4 17h16"/>',search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>',moon:'<path d="M20 15.5A8 8 0 1 1 8.5 4 6.5 6.5 0 0 0 20 15.5Z"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/>',print:'<path d="M6 9V3h12v6M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"/><path d="M6 14h12v7H6z"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>',home:'<path d="m3 11 9-8 9 8v10h-6v-6H9v6H3z"/>'};return `<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||''}</svg>`}

function allLessons(){return DATA.chapters.flatMap(c=>c.lessons.map(l=>({...l,chapter:c})));}
function route(){const raw=location.hash.slice(1); if(!raw||raw==='/'){renderHome();return} const parts=raw.split('/').filter(Boolean); if(parts[0]==='chapter'){const ch=DATA.chapters.find(c=>c.id===parts[1]); if(!ch){renderHome();return} const lesson=ch.lessons.find(l=>l.id===parts[2])||ch.lessons[0]; renderLesson(ch,lesson);return} renderHome()}

function topbar(){return `<header class="topbar"><button class="icon-btn mobile-menu" aria-label="Apri indice">${icon('menu')}</button><a class="brand" href="#/"><span class="brand-mark">L</span><span class="brand-text">Corpus gbprof<small>Letteratura · Quarto anno</small></span></a><div class="top-actions"><button class="icon-btn" id="searchBtn" aria-label="Cerca">${icon('search')}</button><button class="icon-btn font-btn" id="fontDown" aria-label="Riduci testo">A−</button><button class="icon-btn font-btn" id="fontUp" aria-label="Aumenta testo">A+</button><button class="icon-btn" id="themeBtn" aria-label="Cambia tema">${theme==='dark'?icon('sun'):icon('moon')}</button><button class="icon-btn" id="printBtn" aria-label="Stampa">${icon('print')}</button></div></header>`}

function sidebar(ch,active){if(!ch)return ''; let n=0; const rows=ch.lessons.map(l=>{const isSpecial=['tools','anthology','biblio'].includes(l.kind); if(!isSpecial)n++; const label=isSpecial?'•':String(n).padStart(2,'0'); return `<button class="nav-btn ${l.id===active?'active':''} ${isSpecial?'special':''}" data-route="#/chapter/${ch.id}/${l.id}"><span class="num">${label}</span><span>${l.title}</span></button>`}).join(''); return `<aside class="sidebar"><button class="icon-btn mobile-close" aria-label="Chiudi indice">${icon('close')}</button><div class="nav-label">${ch.title}</div>${rows}<div class="future-nav"><div class="nav-label">Collegamenti futuri</div><div class="future-pill">Antologia completa <span>in progetto</span></div><div class="future-pill">Lezioni gbprof <span>in progetto</span></div></div></aside>`}

function shell(content,ch=null,active=null){document.querySelector('#app').innerHTML=`${topbar()}<div class="layout">${sidebar(ch,active)}<main class="main">${content}</main></div><section class="search-panel hidden" aria-label="Ricerca"><div class="search-box"><input id="searchInput" type="search" placeholder="Cerca concetti, autori, opere…" autofocus><div class="results"></div></div></section><div class="map-modal hidden"><button class="icon-btn" aria-label="Chiudi mappa">${icon('close')}</button><img alt="Mappa concettuale ingrandita"></div>`; bindGlobal();}

function renderHome(){state.chapter=null;state.lesson=null; const cards=DATA.chapters.map((c,i)=>`<article class="chapter-card"><span class="eyebrow">Modulo ${i+1}</span><h2>${c.title}</h2><p>${c.subtitle}</p><div class="chapter-meta"><span class="chip">${c.lessons.filter(l=>l.kind==='main').length} sezioni</span><span class="chip">mappe SVG</span><span class="chip">studio offline</span></div><button class="primary-btn" data-route="#/chapter/${c.id}/${c.lessons[0].id}">Entra nel capitolo</button></article>`).join(''); const content=`<section class="page"><div class="home"><span class="eyebrow">Parte I · Percorso classico</span><h1>Illuminismo.<br>Un sito-manuale che prepara i collegamenti.</h1><p class="subtitle">La prova integra la spiegazione tradizionale con sintesi, saperi irrinunciabili, vocabolario, mappe concettuali, testi antologici selezionati e spazi predisposti per le future lezioni di gbprof.</p><div class="chapter-grid">${cards}</div><section><span class="eyebrow">Struttura ricorrente</span><div class="system-strip"><div class="system-item"><b>Lezione</b><span>Il testo completo del capitolo.</span></div><div class="system-item"><b>Ripasso</b><span>Sintesi e nuclei irrinunciabili.</span></div><div class="system-item"><b>Vocabolario</b><span>Termine, definizione e contesto.</span></div><div class="system-item"><b>Mappa</b><span>SVG nitido, ingrandibile e stampabile.</span></div><div class="system-item"><b>Connessioni</b><span>Antologia e lezione di gbprof.</span></div></div></section><section class="pathway"><span class="eyebrow">Architettura del progetto</span><h2>Tre spazi distinti, un solo percorso</h2><div class="path-line"><span class="path-node active">Manuale di letteratura</span><span class="arrow">→</span><span class="path-node">Antologia</span><span class="arrow">→</span><span class="path-node">Lezioni di gbprof</span></div><p>In questa prova è attivo il manuale. I rimandi agli altri due spazi sono già progettati, ma non fingono di essere completi.</p></section></div></section>`; shell(content); document.title='Illuminismo · Corpus gbprof';}

function renderToolkit(t,lesson){if(!t)return ''; const ess=t.essentials.map(x=>`<li>${x}</li>`).join(''); const vocab=t.vocab.map(([a,b])=>`<div class="vocab-item"><dt>${a}</dt><dd>${b}</dd></div>`).join(''); const anth=t.anthology.map(([a,o,p,w])=>`<article class="anthology-card"><b>${a}</b><em>${o}</em><span>${p}</span><small>${w}</small></article>`).join(''); const qs=t.questions.map((q,i)=>`<details><summary>${i+1}. ${q}</summary><p>Apri il testo della lezione e costruisci una risposta in tre passaggi: tesi, prova dal testo, conclusione.</p></details>`).join(''); return `<section class="toolkit"><div class="toolkit-header"><div><span class="eyebrow">Dopo la lezione</span><h2>Consolida e collega</h2></div><p>Il nucleo didattico della sezione.</p></div><div class="tool-grid"><article class="tool-card summary-card"><h3>Riassunto ragionato</h3><p>${t.summary}</p></article><article class="tool-card"><h3>Saperi irrinunciabili</h3><ol class="essential-list">${ess}</ol></article><article class="tool-card"><h3>Vocabolario essenziale</h3><dl class="vocab-list">${vocab}</dl></article><article class="tool-card"><h3>Mappa concettuale</h3><div class="map-frame"><img src="${t.mapFile}" alt="Mappa concettuale: ${t.map[0]}" loading="lazy"></div><div class="map-actions"><button class="small-btn map-open" data-map="${t.mapFile}">Ingrandisci</button><a class="small-btn" href="${t.mapFile}" download>Scarica SVG</a></div></article><article class="tool-card full"><h3>Testi per capire</h3><div class="anthology-grid">${anth}</div></article><article class="tool-card future-box"><span class="status">Collegamento predisposto</span><h3>La lezione di gbprof</h3><b>${t.gbprof}</b><p>Questo spazio ospiterà la tua spiegazione, un video, una dispensa o un’esperienza immersiva. Il collegamento porterà direttamente alla lezione corrispondente.</p><button class="small-btn" disabled>Non ancora pubblicata</button></article><article class="tool-card quiz"><h3>Verifica rapida</h3>${qs}</article></div></section>`}

function renderLesson(ch,l){state.chapter=ch;state.lesson=l; const mainLessons=ch.lessons.filter(x=>x.kind==='main'); const idx=mainLessons.findIndex(x=>x.id===l.id); const progress=idx>=0?Math.round(((idx+1)/mainLessons.length)*100):100; const special=l.kind!=='main'; const content=`<section class="page ${special?'special-page':''}"><header class="lesson-hero"><div class="lesson-kicker"><a href="#/">Manuale</a><span>›</span><span>${ch.title}</span></div><h1>${l.title}</h1>${!special?`<div class="progress-shell"><div class="progress-bar" style="width:${progress}%"></div></div><div class="progress-text">Sezione ${idx+1} di ${mainLessons.length} · ${progress}% del capitolo</div>`:''}</header><article class="article">${l.body}<div class="source-note">Testo base: capitolo fornito da gbprof. La struttura web conserva i contenuti e aggiunge il livello didattico e i collegamenti progettuali.</div></article>${renderToolkit(l.tools,l)}${!special?`<footer class="lesson-footer"><button class="prev-btn">← Sezione precedente</button><button class="complete-btn ${completed.has(l.id)?'done':''}">${completed.has(l.id)?'✓ Studiata':'Segna come studiata'}</button><button class="next-btn">Sezione successiva →</button></footer>`:''}</section>`; shell(content,ch,l.id); bindLesson(ch,l); document.title=`${l.title} · Corpus gbprof`; window.scrollTo(0,0);}

function bindGlobal(){
 $$('.nav-btn,[data-route]').forEach(el=>el.addEventListener('click',()=>{location.hash=el.dataset.route; $('.sidebar')?.classList.remove('open')}));
 $('.mobile-menu')?.addEventListener('click',()=>$('.sidebar')?.classList.add('open')); $('.mobile-close')?.addEventListener('click',()=>$('.sidebar')?.classList.remove('open'));
 $('#themeBtn')?.addEventListener('click',()=>{theme=theme==='dark'?'light':'dark';localStorage.setItem('theme',theme);document.documentElement.dataset.theme=theme==='dark'?'dark':'';route()});
 $('#fontUp')?.addEventListener('click',()=>setFont(.08)); $('#fontDown')?.addEventListener('click',()=>setFont(-.08)); $('#printBtn')?.addEventListener('click',()=>window.print());
 $('#searchBtn')?.addEventListener('click',()=>{const p=$('.search-panel');p.classList.toggle('hidden');if(!p.classList.contains('hidden'))setTimeout(()=>$('#searchInput').focus(),50)});
 $('#searchInput')?.addEventListener('input',e=>search(e.target.value));
 $('.search-panel')?.addEventListener('click',e=>{if(e.target.classList.contains('search-panel'))e.currentTarget.classList.add('hidden')});
 $('.map-modal button')?.addEventListener('click',()=>$('.map-modal').classList.add('hidden'));
 document.addEventListener('keydown',escapeHandler,{once:true});
}
function escapeHandler(e){if(e.key==='Escape'){$('.search-panel')?.classList.add('hidden');$('.map-modal')?.classList.add('hidden')} document.addEventListener('keydown',escapeHandler,{once:true})}
function setFont(delta){fontScale=Math.min(1.35,Math.max(.85,fontScale+delta));localStorage.setItem('fontScale',fontScale);document.documentElement.style.fontSize=(16*fontScale)+'px'}
function stripHTML(s){const d=document.createElement('div');d.innerHTML=s;return d.textContent||''}
function search(q){const box=$('.results');q=q.trim().toLowerCase();if(q.length<2){box.innerHTML='<div class="empty">Scrivi almeno due caratteri.</div>';return} const found=allLessons().filter(l=>(l.title+' '+stripHTML(l.body)+' '+JSON.stringify(l.tools||{})).toLowerCase().includes(q)).slice(0,20); box.innerHTML=found.length?found.map(l=>`<button class="result" data-route="#/chapter/${l.chapter.id}/${l.id}"><b>${l.title}</b><small>${l.chapter.title}</small></button>`).join(''):'<div class="empty">Nessun risultato.</div>'; $$('.result').forEach(el=>el.addEventListener('click',()=>{location.hash=el.dataset.route;$('.search-panel').classList.add('hidden')}))}
function bindLesson(ch,l){const all=ch.lessons;const i=all.findIndex(x=>x.id===l.id);$('.prev-btn')?.addEventListener('click',()=>{if(i>0)location.hash=`#/chapter/${ch.id}/${all[i-1].id}`});$('.next-btn')?.addEventListener('click',()=>{if(i<all.length-1)location.hash=`#/chapter/${ch.id}/${all[i+1].id}`});$('.complete-btn')?.addEventListener('click',e=>{if(completed.has(l.id))completed.delete(l.id);else completed.add(l.id);localStorage.setItem('completedLessons',JSON.stringify([...completed]));e.currentTarget.classList.toggle('done');e.currentTarget.textContent=completed.has(l.id)?'✓ Studiata':'Segna come studiata'});$$('.map-open').forEach(b=>b.addEventListener('click',()=>{const m=$('.map-modal');m.querySelector('img').src=b.dataset.map;m.classList.remove('hidden')}));}
window.addEventListener('hashchange',route);route();
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
