window.PARINI_DATA = {
  title: 'Giuseppe Parini',
  lessons: [
    {
      id: 'mondo-precedente', short: 'Il mondo precedente', title: 'Quando il privilegio perde la sua funzione',
      lead: 'Prima di Parini viene una società che continua a distribuire rango e potere secondo la nascita, mentre le trasformazioni dello Stato moderno e la cultura illuminista chiedono che ogni ceto dimostri la propria utilità.',
      html: `
        <p class="lesson-number">01 · Il mondo precedente</p><h1>Quando il privilegio perde la sua funzione</h1>
        <p class="lead">Prima di Parini viene una società che continua a distribuire rango e potere secondo la nascita, mentre le trasformazioni dello Stato moderno e la cultura illuminista chiedono che ogni ceto dimostri la propria utilità.</p>
        <section data-visual="0"><h2>Una società divisa in ordini</h2>
        <p>Parini nasce nel 1729, dentro l’<strong>Ancien Régime</strong>: non una società composta anzitutto da cittadini uguali davanti alla legge, ma un sistema di ordini. Il clero costituisce il Primo Stato, la nobiltà il Secondo, mentre nel Terzo Stato convivono borghesi, artigiani e contadini. Diritti, obblighi, prestigio e accesso alle cariche dipendono ancora in larga parte dall’appartenenza.</p>
        <p>Questa struttura, però, non è immobile. I gruppi borghesi rivendicano il valore del lavoro e della competenza; le monarchie hanno ridotto l’autonomia militare dei nobili; la discussione illuminista sottopone istituzioni e consuetudini a una domanda nuova: <em>a che cosa servono?</em> Il privilegio ereditario diventa criticabile quando non corrisponde più a una funzione esercitata.</p></section>
        <section data-visual="1"><h2>Dalla nobiltà guerriera alla nobiltà dell’apparenza</h2>
        <div class="concept-grid"><div class="concept-card"><h3>Medioevo</h3><p>Il nobile è uomo d’armi: il suo potere si lega alla difesa del territorio, al comando militare e al rapporto feudale.</p></div><div class="concept-card"><h3>Età moderna</h3><p>Armi da fuoco, eserciti permanenti e monarchie assolute riducono la funzione militare autonoma dell’aristocrazia.</p></div><div class="concept-card"><h3>Versailles</h3><p>Il prestigio si sposta dalla spada al rito di corte: etichetta, lusso, abiti, vicinanza e dipendenza dal sovrano.</p></div><div class="concept-card"><h3>Settecento</h3><p>La nobiltà conserva privilegi e rendite, ma una sua parte appare priva di utilità sociale. Parini la osserva come classe da riformare, non semplicemente da insultare.</p></div></div>
        <p>La corte trasforma il comportamento quotidiano in spettacolo del rango. L’abito, la visita, il ricevimento e la conversazione non sono dettagli innocenti: diventano segni attraverso cui l’aristocrazia riconosce se stessa. Proprio per questo la <strong>Moda</strong> può essere rappresentata da Parini come una divinità politica: governa il bisogno di appartenenza senza emanare leggi.</p></section>
        <section data-visual="2"><h2>Milano e l’Illuminismo delle riforme</h2>
        <p>La Milano in cui Parini si forma appartiene alla Lombardia asburgica. Nel secondo Settecento la cultura delle riforme prova a rendere più razionali amministrazione, istruzione ed economia. L’Illuminismo lombardo non coincide con una sola dottrina: è un ambiente di discussione nel quale ragione, esperienza e pubblica utilità diventano criteri di giudizio.</p>
        <p>Parini accoglie questo impulso, ma conserva una propria autonomia. Non pensa che la dignità umana possa ridursi al piacere, al consumo o alla ricchezza. La sua critica unisce istanza illuminista e coscienza cristiana: il valore di una persona non dipende dal rango; chi gode di una posizione elevata ha una responsabilità verso la comunità.</p>
        <blockquote>Il problema iniziale non è dunque “perché i nobili sono ridicoli?”, ma “che cosa rende legittimo un ruolo sociale quando la sua funzione storica è scomparsa?”.</blockquote></section>`,
      visuals: [
        {src:'assets/schema_primo_stato_06.png',alt:'Schema sul Terzo Stato: lavoro, famiglia, ritmi naturali e dignità dell’uomo',caption:'Il Terzo Stato rappresentato attraverso lavoro, famiglia e dignità.'},
        {src:'assets/schema_primo_stato_02.png',alt:'Schema di confronto fra operosità del Terzo Stato e vita senza valore del nobile',caption:'Due modelli sociali messi a confronto.'},
        {src:'assets/schema_primo_stato_10.png',alt:'Schema sui rapporti di Parini con borghesia, cristianesimo e Illuminismo',caption:'Le tre matrici culturali dello sguardo pariniano.'}
      ],
      knowledge: [
        'Nell’Ancien Régime diritti e privilegi dipendono dall’appartenenza ai tre ordini, non dall’uguaglianza giuridica dei cittadini.',
        'La funzione militare autonoma della nobiltà diminuisce con eserciti permanenti e monarchie assolute.',
        'La vita di corte trasforma l’apparenza e l’etichetta in segni pubblici del rango.',
        'L’Illuminismo giudica istituzioni e consuetudini anche in base alla loro utilità sociale.',
        'Parini critica la nobiltà oziosa per richiamarla a una funzione morale, economica e civile.'
      ],
      vocabulary: [
        ['Ancien Régime','Sistema politico e sociale europeo precedente alla Rivoluzione francese, fondato su monarchia e ordini privilegiati.'],['Primo Stato','Il clero nella società per ordini.'],['Secondo Stato','La nobiltà nella società per ordini.'],['Terzo Stato','L’insieme dei non appartenenti a clero e nobiltà, socialmente molto diversi tra loro.'],['Pubblica utilità','Beneficio concreto prodotto per la comunità; criterio centrale della cultura riformatrice.']
      ],
      quiz: [
        {q:'Quale principio organizza la società dell’Ancien Régime?',o:['L’appartenenza agli ordini','L’uguaglianza giuridica','Il suffragio universale'],c:0,why:'La posizione giuridica e sociale dipende in larga parte dall’ordine di appartenenza.',concept:'Società per ordini',example:'Clero e nobiltà godono di uno statuto diverso da quello del Terzo Stato.',retry:{q:'Chi forma il Secondo Stato?',o:['La nobiltà','Il clero','La borghesia'],c:0}},
        {q:'Perché nell’età moderna cambia la funzione della nobiltà?',o:['Per la scomparsa del commercio','Perché eserciti stabili e monarchie riducono il suo ruolo militare','Perché tutti i nobili diventano sacerdoti'],c:1,why:'Lo Stato moderno concentra il potere militare e politico nelle istituzioni monarchiche.',concept:'Perdita di funzione',example:'Il prestigio si sposta dalla spada al rito di corte.',retry:{q:'Quale istituzione riduce l’autonomia militare nobiliare?',o:['L’esercito permanente','L’accademia poetica','La parrocchia'],c:0}},
        {q:'Che cosa domanda la cultura illuminista alle istituzioni?',o:['Se sono antiche','Se sono spettacolari','Se sono razionali e socialmente utili'],c:2,why:'La pubblica utilità è un criterio decisivo della cultura riformatrice.',concept:'Illuminismo riformatore',example:'Anche il privilegio viene giudicato in rapporto alla funzione svolta.',retry:{q:'Qual è un criterio illuminista?',o:['Pubblica utilità','Nascita aristocratica','Moda di corte'],c:0}},
        {q:'Perché la Moda assume un valore politico nella lezione?',o:['Perché orienta appartenenza e comportamento','Perché emana leggi','Perché abolisce la nobiltà'],c:0,why:'La Moda governa attraverso il desiderio di essere riconosciuti, non attraverso la forza.',concept:'Potere dell’apparenza',example:'Abito e rito di corte rendono visibile il rango.',retry:{q:'La Moda esercita soprattutto un potere…',o:['militare','persuasivo','giudiziario'],c:1}},
        {q:'Qual è il bersaglio preciso di Parini?',o:['Ogni persona nobile per nascita','La nobiltà oziosa e priva di funzione','Il lavoro produttivo'],c:1,why:'La critica mira all’inutilità sociale e al rovesciamento dei valori.',concept:'Critica riformatrice',example:'Parini vuole richiamare il ceto privilegiato alla responsabilità.',retry:{q:'Parini chiede alla nobiltà di recuperare…',o:['una funzione sociale','nuovi titoli','più lusso'],c:0}}
      ]
    },
    {
      id:'fratture',short:'Le fratture',title:'Dentro e fuori i tre Stati',
      lead:'La posizione di Parini è una soglia: nasce nel Terzo Stato, entra nel Primo come sacerdote e lavora a contatto con il Secondo come precettore. Da questa collocazione nasce uno sguardo interno e insieme critico.',
      html:`
        <p class="lesson-number">02 · Le fratture della vita</p><h1>Dentro e fuori i tre Stati</h1><p class="lead">La posizione di Parini è una soglia: nasce nel Terzo Stato, entra nel Primo come sacerdote e lavora a contatto con il Secondo come precettore. Da questa collocazione nasce uno sguardo interno e insieme critico.</p>
        <section data-visual="0"><h2>Un’origine non aristocratica</h2><p>Giuseppe Parini nasce a Bosisio, in Brianza, nel 1729, figlio di un piccolo commerciante di seta. La famiglia non dispone dei privilegi della nobiltà. Trasferito giovanissimo a Milano, studia nelle scuole dei barnabiti e riceve gli ordini sacerdotali nel 1754. La scelta ecclesiastica gli offre una collocazione sociale e la possibilità di continuare una vita intellettuale, ma non cancella l’esperienza dell’origine modesta.</p>
        <p>Dire che Parini “appartiene a tre Stati” non significa che cambi liberamente classe sociale. Significa che la sua biografia attraversa tre ambienti: nasce nel mondo non privilegiato, assume un ruolo nel clero e dipende economicamente da famiglie aristocratiche. È una posizione concreta, non una formula astratta.</p></section>
        <section data-visual="1"><h2>Parini: tre appartenenze, uno sguardo critico</h2><p>Parini nasce nel Terzo Stato, appartiene al Primo Stato come sacerdote e dipende economicamente dal Secondo Stato come precettore presso famiglie aristocratiche. Questa posizione gli permette di osservare la società da dentro e da fuori.</p>
        <div class="concept-grid"><div class="concept-card"><h3>Borghesia</h3><p>Valorizza lavoro, famiglia, utilità sociale. Parini ne assume l’etica dell’operosità, pur criticando l’attaccamento eccessivo alla ricchezza.</p></div><div class="concept-card"><h3>Cristianesimo</h3><p>Recupera dignità della persona, morale familiare, responsabilità verso i deboli. Rifiuta oscurantismo e degenerazioni storiche.</p></div><div class="concept-card"><h3>Illuminismo</h3><p>Accoglie ragione, uguaglianza, dignità individuale, ma non abbraccia l’antireligiosità estrema né l’edonismo superficiale.</p></div><div class="concept-card"><h3>Autonomia</h3><p>Le tre matrici non si sommano meccanicamente: Parini le sottopone a un criterio morale personale, cercando insieme utile e dignità.</p></div></div></section>
        <section data-visual="2"><h2>Il precettore osserva dall’interno</h2><p>Il lavoro di precettore porta Parini nelle case aristocratiche. Egli conosce dall’interno tempi, linguaggi e cerimonie di quel mondo. La satira del <em>Giorno</em> non nasce quindi da un’immagine lontana o fantastica: trasforma in costruzione poetica un’esperienza sociale ravvicinata.</p>
        <p>Qui avviene una frattura decisiva. La cultura nobiliare ama il tono elevato, la mitologia, la grazia e il decoro; Parini non rifiuta quelle forme, ma le usa per mostrare la sproporzione tra grandezza dello stile e piccolezza della vita rappresentata. Il linguaggio del privilegio diventa lo strumento della sua critica.</p>
        <blockquote>Parini non parla come un estraneo che osserva da lontano. Conosce il codice aristocratico abbastanza bene da poterlo far collassare dall’interno.</blockquote></section>
        <section data-visual="1"><h2>Una riforma, non una vendetta</h2><p>Ridurre Parini a “poeta contro i nobili” sarebbe comodo e falso. La sua polemica investe l’ozio, la perdita di responsabilità e l’indifferenza verso chi lavora. Il fine dichiarato è riportare la nobiltà a una funzione morale, sociale ed economica, rinnovandola. È un progetto riformatore: severo, ma diverso dall’idea di cancellare automaticamente ogni differenza sociale.</p>
        <p>Questa misura spiega anche la sua distanza da ogni estremismo. La ragione non deve distruggere la religione; l’utilità non deve cancellare la bellezza; la critica alla ricchezza non deve diventare disprezzo del lavoro e dell’iniziativa. La poesia tiene insieme tensioni che una formula ideologica renderebbe più semplici, ma anche più povere.</p></section>`,
      visuals:[
        {src:'assets/schema_primo_stato_08.png',alt:'Schema biografico di Parini fra Terzo Stato, clero e nobiltà',caption:'Parini attraversa tre ambienti sociali e osserva la nobiltà dall’interno.'},
        {src:'assets/schema_primo_stato_10.png',alt:'Schema su borghesia, cristianesimo e Illuminismo nel pensiero di Parini',caption:'Le tre matrici culturali, accolte e criticate da Parini.'},
        {src:'assets/parini_dipinto_originale.jpeg',alt:'Ritratto storico di Giuseppe Parini',caption:'Il ritratto storico conservato fra i materiali della PWA.'}
      ],
      knowledge:[
        'Parini nasce nel 1729 a Bosisio, in una famiglia del Terzo Stato, e si forma a Milano.',
        'L’ordinazione sacerdotale lo colloca nel clero senza cancellarne l’origine sociale.',
        'Come precettore presso famiglie aristocratiche, Parini conosce dall’interno il mondo che rappresenterà nel Giorno.',
        'La sua visione intreccia etica del lavoro, dignità cristiana e razionalità illuminista.',
        'La critica di Parini è riformatrice: vuole restituire al privilegio una responsabilità sociale.'
      ],
      vocabulary:[['Precettore','Insegnante privato incaricato dell’educazione dei giovani di una famiglia.'],['Barnabiti','Ordine religioso che gestiva le scuole milanesi frequentate da Parini.'],['Riformismo','Orientamento che modifica istituzioni e società gradualmente, senza rovesciarle integralmente.'],['Decoro','Adeguatezza dello stile al soggetto e alla situazione secondo la tradizione retorica.'],['Edonismo','Concezione che assume il piacere come fine principale dell’agire.']],
      quiz:[
        {q:'In quale Stato nasce Parini?',o:['Nel Terzo','Nel Primo','Nel Secondo'],c:0,why:'Parini nasce in una famiglia non privilegiata del Terzo Stato.',concept:'Origine sociale',example:'Il padre era un piccolo commerciante di seta.',retry:{q:'Quale gruppo comprende i non privilegiati?',o:['Terzo Stato','Primo Stato','Secondo Stato'],c:0}},
        {q:'Che cosa lo colloca nel Primo Stato?',o:['Il lavoro di precettore','L’ordinazione sacerdotale','La nascita'],c:1,why:'Il Primo Stato è il clero e Parini viene ordinato sacerdote nel 1754.',concept:'Ruolo ecclesiastico',example:'La condizione sacerdotale gli offre anche una collocazione sociale.',retry:{q:'Il Primo Stato corrisponde…',o:['alla nobiltà','al clero','alla borghesia'],c:1}},
        {q:'Perché il lavoro di precettore è decisivo?',o:['Lo rende nobile','Gli impedisce di scrivere','Gli permette di osservare la nobiltà dall’interno'],c:2,why:'L’esperienza ravvicinata alimenta la precisione della sua satira.',concept:'Osservazione interna',example:'Parini conosce rituali, tempi e linguaggio della vita aristocratica.',retry:{q:'Il precettore lavora soprattutto…',o:['in una bottega','presso una famiglia','in tribunale'],c:1}},
        {q:'Quale elemento Parini accoglie dall’Illuminismo?',o:['Ragione e dignità individuale','Il privilegio ereditario','L’ozio aristocratico'],c:0,why:'La ragione e l’uguaglianza morale sono nuclei illuministici importanti.',concept:'Matrice illuminista',example:'Le istituzioni vengono giudicate criticamente.',retry:{q:'Parini collega l’Illuminismo alla…',o:['ragione','superstizione','rendita'],c:0}},
        {q:'Qual è il fine della critica alla nobiltà?',o:['La vendetta personale','La riforma della sua funzione','La celebrazione del lusso'],c:1,why:'Parini mira a recuperare responsabilità morale, sociale ed economica.',concept:'Riforma del ceto',example:'Il bersaglio è la nobiltà oziosa, non ogni individuo nobile.',retry:{q:'La posizione di Parini è soprattutto…',o:['riformatrice','nichilista','nostalgica del feudalesimo'],c:0}}
      ]
    },
    {
      id:'immagine-mondo',short:'L’immagine del mondo',title:'Le dolci redini dell’apparenza',
      lead:'Parini vede una società nella quale il potere più efficace non ordina: persuade. La Moda governa perché rende desiderabile ciò che sostituisce ragione, responsabilità e dignità.',
      html:`
        <p class="lesson-number">03 · L’immagine del mondo</p><h1>Le dolci redini dell’apparenza</h1><p class="lead">Parini vede una società nella quale il potere più efficace non ordina: persuade. La Moda governa perché rende desiderabile ciò che sostituisce ragione, responsabilità e dignità.</p>
        <section data-visual="0"><h2>La Moda non veste soltanto: governa</h2><p>Parini dedica il suo poemetto alla Moda. In apparenza le rende omaggio. In realtà la mette sul trono per mostrarne il potere: una società può essere guidata non solo da leggi e sovrani, ma da modelli desiderabili.</p>
        <p>Questa è la chiave della lezione: <strong>l’autorevolezza può perdere contro ciò che persuade subito</strong>. La Moda, ieri come oggi, non ordina: fa desiderare. Non obbliga: orienta. Non dice “devi”, ma “se vuoi contare, devi apparire così”.</p>
        <blockquote><strong>Tesi:</strong> Parini smaschera il potere dell’apparenza usando la forma dell’elogio ironico.</blockquote></section>
        <section data-visual="1"><h2>Ciò che sembra e ciò che è</h2><div class="concept-grid"><div class="concept-card"><h3>La tesi apparente</h3><p>La Moda è una divinità benefica: guida la gioventù, libera il secolo, decide il gusto, protegge il poemetto.</p></div><div class="concept-card"><h3>La tesi vera</h3><p>Parini non celebra la Moda: la usa come maschera ironica per smascherare una società fondata sull’apparenza.</p></div><div class="concept-card"><h3>La parola chiave</h3><p><em>Redini dolci</em>: il potere più efficace non sembra costrizione, ma desiderio.</p></div><div class="concept-card"><h3>La domanda civile</h3><p>Chi decide oggi che cosa dobbiamo desiderare per sentirci riconosciuti?</p></div></div>
        <p>Il rovesciamento non è soltanto retorico. Indica un modo di interpretare la realtà: ciò che una società celebra può rivelare proprio ciò che ha perduto. Quando Ragione, Buon Senso e Ordine vengono descritti come nemici sconfitti, il lettore comprende che la vittoria della Moda coincide con una sconfitta collettiva.</p></section>
        <section data-visual="0"><h2>Dignità, natura, funzione</h2><p>All’apparenza Parini oppone tre misure. La prima è la <strong>dignità della persona</strong>: il servo e la sua famiglia valgono più del capriccio di una dama. La seconda è la <strong>natura</strong>, non intesa come ritorno ingenuo a una vita primitiva, ma come ordine dei bisogni, dei ritmi e dei legami che la vita artificiale non dovrebbe rovesciare. La terza è la <strong>funzione sociale</strong>: il rango acquista senso solo se produce responsabilità.</p>
        <p>Per questo il buon villano e il giovin signore diventano figure opposte. Il primo partecipa al mantenimento della vita attraverso lavoro e famiglia; il secondo consuma tempo e privilegi in una giornata spettacolare ma improduttiva. Il contrasto è costruito con forza poetica, non come descrizione sociologica neutrale: anche il mondo rurale è idealizzato per far emergere il rovesciamento aristocratico.</p></section>
        <section data-visual="1"><h2>Moda, persuasione, controllo: perché Parini parla ancora</h2><p>La Moda di Parini è un potere che non sembra potere. Oggi possiamo riconoscerla nei meccanismi che orientano identità, desiderio e appartenenza: social, trend, voto come passaporto, immagine pubblica, bisogno di essere visti.</p>
        <div class="concept-grid"><div class="concept-card"><h3>Non comanda: orienta</h3><p>La Moda non impone con la forza. Rende desiderabile una forma di vita.</p></div><div class="concept-card"><h3>Non educa: addestra</h3><p>Non chiede comprensione, ma adeguamento rapido ai codici del momento.</p></div><div class="concept-card"><h3>Non libera: sostituisce</h3><p>Sembra togliere vincoli, ma mette al loro posto nuove dipendenze.</p></div><div class="concept-card"><h3>Non smaschera: spettacolarizza</h3><p>Mostra reazioni e viscere, ma spesso non aiuta a capire i meccanismi.</p></div></div>
        <p>L’analogia con il presente non autorizza però scorciatoie. Un social network non è la corte settecentesca e un influencer non è un aristocratico. Il nesso utile riguarda il funzionamento della persuasione: la capacità di far apparire spontanea una norma sociale. Parini serve ancora se ci aiuta a interrogare quel meccanismo, non se lo trasformiamo in un facile moralista contro ogni novità.</p></section>`,
      visuals:[
        {src:'assets/mappa_dea_moda_tesi_apparente.png',alt:'Mappa della tesi apparente: la Moda come divinità benefica e guida del secolo',caption:'Mappa 1 · La finta celebrazione della Moda.'},
        {src:'assets/mappa_dea_moda_tesi_vera.png',alt:'Mappa della tesi vera: la dedica ironica smaschera il dominio della Moda',caption:'Mappa 2 · Il ribaltamento ironico e la tesi autentica.'}
      ],
      knowledge:[
        'La Moda esercita un potere persuasivo: orienta il desiderio senza presentarsi come costrizione.',
        'La tesi apparente celebra la Moda, mentre la tesi vera denuncia la sconfitta di ragione, buon senso e ordine.',
        'La dignità della persona è un criterio superiore al rango e al capriccio sociale.',
        'Parini contrappone ritmi naturali e funzione produttiva all’artificio ozioso del giovin signore.',
        'Il confronto con il presente è valido se analizza i meccanismi della persuasione, non se identifica epoche diverse.'
      ],
      vocabulary:[['Tesi apparente','Significato che il testo sembra sostenere alla prima lettura.'],['Tesi vera','Posizione effettiva che emerge interpretando l’ironia e il contesto.'],['Persuasione','Influenza esercitata sui desideri e sui giudizi senza imposizione diretta.'],['Apparenza','Immagine sociale che può sostituire valore, funzione e verità.'],['Dignità','Valore proprio di ogni persona, indipendente dal rango e dall’utilità economica.']],
      quiz:[
        {q:'Che cosa significa l’espressione “redini dolci”?',o:['Un potere persuasivo','Una legge severa','Una tecnica metrica'],c:0,why:'Le redini sono dolci perché guidano attraverso desiderio e piacere.',concept:'Persuasione',example:'La Moda non ordina: rende desiderabile un comportamento.',retry:{q:'Il potere della Moda appare…',o:['coercitivo','persuasivo','militare'],c:1}},
        {q:'Qual è la tesi apparente della dedica?',o:['La Moda distrugge la poesia','La Moda è una dea benefica','La nobiltà deve lavorare'],c:1,why:'Il testo finge di celebrare la Moda come guida del secolo.',concept:'Tesi apparente',example:'La Moda viene invocata come protettrice del poemetto.',retry:{q:'La dedica in superficie è…',o:['un elogio','un decreto','un’autobiografia'],c:0}},
        {q:'Qual è la tesi vera?',o:['La Moda garantisce libertà','La poesia deve seguire ogni novità','L’apparenza domina una società che perde ragione e responsabilità'],c:2,why:'L’elogio viene rovesciato e diventa denuncia.',concept:'Tesi vera',example:'Ragione, Buon Senso e Ordine sono ironicamente detti nemici.',retry:{q:'La vittoria della Moda indica una sconfitta della…',o:['ragione','nobiltà guerriera','lingua latina'],c:0}},
        {q:'Quale criterio vale più del rango per Parini?',o:['La dignità della persona','Il lusso','La visibilità'],c:0,why:'La persona non perde valore perché appartiene a un ceto subordinato.',concept:'Dignità',example:'Il servo della Vergin Cuccia ha una famiglia e una dignità ignorate dalla dama.',retry:{q:'Il valore umano dipende dal rango?',o:['Sì, sempre','No','Solo a corte'],c:1}},
        {q:'Come va usato il confronto con i social contemporanei?',o:['Identificando perfettamente le due epoche','Analizzando il comune meccanismo persuasivo','Condannando ogni tecnologia'],c:1,why:'Il confronto illumina un meccanismo, ma non annulla le differenze storiche.',concept:'Analogia controllata',example:'Influencer e aristocratico non sono la stessa figura sociale.',retry:{q:'Un’analogia storica corretta deve…',o:['ignorare le differenze','riconoscere somiglianze e differenze','trasformare tutto nel presente'],c:1}}
      ]
    },
    {
      id:'poetica',short:'La poetica',title:'L’elogio che distrugge',
      lead:'Parini non separa utilità e bellezza. La poesia educa proprio perché domina le forme del decoro, del mito e dello stile alto, poi le fa reagire con una materia quotidiana e moralmente vuota.',
      html:`
        <p class="lesson-number">04 · La poetica</p><h1>L’elogio che distrugge</h1><p class="lead">Parini non separa utilità e bellezza. La poesia educa proprio perché domina le forme del decoro, del mito e dello stile alto, poi le fa reagire con una materia quotidiana e moralmente vuota.</p>
        <section data-visual="0"><h2>Antifrasi: dire per rovesciare</h2><p>L’<strong>antifrasi</strong> consiste nel dire una cosa intendendo il contrario. In Parini non è un gioco ornamentale: è una macchina critica. Il poeta finge di lodare ciò che vuole smascherare.</p>
        <div class="warning"><strong>Esempio.</strong> La scelta tra caffè e cioccolata viene presentata come un evento importantissimo; il sarto che chiede di essere pagato diventa un disturbatore. Il comico nasce dallo squilibrio tra tono alto e realtà meschina.</div>
        <p>Il lettore deve compiere un lavoro: ascoltare la voce del precettore, riconoscere l’eccesso della lode e ricostruire il giudizio dell’autore. La satira, così, non consegna soltanto una morale; educa alla lettura critica di un linguaggio che nasconde i rapporti di valore.</p></section>
        <section data-visual="1"><h2>Gli endecasillabi sciolti</h2><p><em>Il Giorno</em> è scritto in endecasillabi sciolti. “Sciolti” significa che i versi non sono legati da uno schema regolare di rime. “Endecasillabo” non significa semplicemente “verso composto sempre da undici sillabe”: è il verso che ha come ultima sillaba tonica la decima. Per questo, secondo la parola conclusiva, può presentare normalmente dieci, undici o dodici sillabe metriche; casi particolari possono produrre un computo ulteriore.</p>
        <p>La forma è decisiva. L’endecasillabo porta con sé la tradizione alta della poesia italiana; Parini lo applica alle occupazioni insignificanti del giovin signore. La solennità del ritmo non nobilita davvero quella vita: ne rende più visibile il vuoto.</p></section>
        <section data-visual="2"><h2>Il testo: dedica «Alla Dea Moda»</h2><div class="source"><p>Lungi da queste carte i cisposi occhi già da un secolo rintuzzati, lungi i fluidi nasi de’ malinconici vegliardi. Qui non si tratta di gravi ministerj nella patria esercitati, non di severe leggi, non di annojante domestica economia, misero appannaggio della canuta età.</p><p>A te, vezzosissima Dea, che con sì dolci redini oggi temperi e governi la nostra brillante gioventù, a te sola questo piccolo Libretto si dedica, e si consagra.</p><p>Chi è che te, qual sommo Nume, oggimai non riverisca, ed onori, poiché in sì breve tempo se’ giunta a debellar la ghiacciata Ragione, il pedante Buon Senso e l’Ordine seccagginoso, tuoi capitali nemici, ed hai sciolto dagli antichissimi lacci questo secolo avventurato?</p><p>Piacciati adunque di accogliere sotto alla tua protezione, ché forse non n’è indegno, questo piccolo Poemetto. Tu il reca su i pacifici altari, ove le gentili Dame e gli amabili Garzoni sagrificano a se medesimi le mattutine ore.</p><p>Per esserti più caro egli ha scosso il giogo della servile rima, e se ne va libero in Versi Sciolti, sapendo che tu di questi specialmente ora godi, e ti compiaci.</p><p>Esso non aspira all’immortalità, come altri libri, troppo lusingati da’ loro Autori, che tu, repentinamente sopravvenendo, hai seppelliti nell’oblio. Siccome egli è per te nato, e consagrato a te sola, così fie pago di vivere quel solo momento, che tu ti mostri sotto un medesimo aspetto, e pensi a cangiarti, e risorgere in più graziose forme.</p><p>Se a te piacerà di riguardare con placid’occhio questo Mattino, forse gli succederanno il Mezzogiorno, e la Sera; e il loro Autore si studierà di comporli, ed ornarli in modo, che non men di questo abbiano ad esserti cari.</p></div></section>
        <section data-visual="3"><h2>Parafrasi ragionata</h2><div class="paraphrase"><p>Parini finge di allontanare dal suo libro i vecchi seriosi, gli uomini legati agli incarichi pubblici, alle leggi, all’economia domestica e al senso del dovere. Il suo poemetto, almeno in apparenza, non vuole rivolgersi a loro.</p><p>Si rivolge invece alla Moda, chiamata ironicamente “vezzosissima Dea”. La Moda governa la brillante gioventù con redini dolci: non costringe con la violenza, ma guida attraverso il piacere, il gusto, l’apparenza e il desiderio di appartenere.</p><p>Parini finge di celebrarla perché ha sconfitto la Ragione, il Buon Senso e l’Ordine. Ma proprio questa celebrazione è la sua accusa: se la Moda trionfa, allora una società intera ha messo da parte i valori che dovrebbero renderla adulta.</p><p>Il poemetto stesso finge di adeguarsi alla Moda: usa i versi sciolti perché sono graditi al gusto del momento, non pretende l’immortalità e si accontenta di vivere finché la Moda non cambierà aspetto. La letteratura viene così trascinata ironicamente nel mondo dell’effimero.</p></div>
        <p>La dedica contiene anche una traccia della prima progettazione dell’opera: dopo <em>Il Mattino</em> avrebbero dovuto seguire <em>Il Mezzogiorno</em> e <em>La Sera</em>. In seguito l’ultima parte si sdoppierà in <em>Il Vespro</em> e <em>La Notte</em>. Il testo non va quindi corretto: testimonia un momento reale del progetto.</p></section>`,
      visuals:[
        {src:'assets/schema_primo_stato_07.png',alt:'Schema che mostra l’antifrasi come scarto fra significato letterale e significato inteso',caption:'L’antifrasi: l’elogio apparente produce la critica.'},
        {src:'assets/schema_primo_stato_04.png',alt:'Schema corretto dell’endecasillabo: ultima sillaba tonica in decima e assenza di rime nei versi sciolti',caption:'Endecasillabi sciolti: accento finale in decima, nessuno schema di rime.'},
        {src:'assets/mappa_dea_moda_tesi_apparente.png',alt:'Mappa dei sette passaggi della tesi apparente nella dedica alla Moda',caption:'Prima lettura: la superficie elogiativa.'},
        {src:'assets/mappa_dea_moda_tesi_vera.png',alt:'Mappa dei sette ribaltamenti che rivelano la vera tesi di Parini',caption:'Seconda lettura: il significato ironico.'}
      ],
      knowledge:[
        'L’antifrasi afferma letteralmente una cosa e fa comprendere il contrario attraverso contesto e sproporzione.',
        'Il tono elevato applicato alla vita futile del giovin signore produce un effetto satirico.',
        'L’endecasillabo ha l’ultima sillaba tonica in decima; il numero complessivo delle sillabe metriche può variare.',
        'I versi sciolti non seguono uno schema regolare di rime.',
        'Nella dedica la vittoria della Moda su Ragione, Buon Senso e Ordine costituisce un elogio soltanto apparente.',
        'Il riferimento finale a Mattino, Mezzogiorno e Sera documenta la prima progettazione del Giorno.'
      ],
      vocabulary:[['Antifrasi','Figura retorica con cui si afferma il contrario di ciò che si vuole far intendere.'],['Endecasillabo','Verso la cui ultima sillaba tonica occupa la decima posizione metrica.'],['Versi sciolti','Versi non legati da uno schema regolare di rime.'],['Satira','Rappresentazione critica di vizi e costumi attraverso ironia, deformazione e contrasto.'],['Parafrasi','Riformulazione che rende esplicito il significato del testo senza sostituirne l’analisi.'],['Decoro stilistico','Rapporto tradizionale di convenienza fra livello dello stile e materia rappresentata.']],
      quiz:[
        {q:'Che cosa fa l’antifrasi?',o:['Dice il contrario di ciò che fa intendere','Aggiunge una rima','Elimina ogni giudizio'],c:0,why:'Il significato letterale viene rovesciato dal contesto.',concept:'Antifrasi',example:'La vittoria della Moda è descritta come liberazione, ma denuncia una sconfitta.',retry:{q:'Nell’antifrasi il senso vero coincide con quello letterale?',o:['Sempre','No','Solo nei titoli'],c:1}},
        {q:'Quando un verso è endecasillabo?',o:['Quando ha sempre undici sillabe totali','Quando l’ultima sillaba tonica è la decima','Quando termina con una rima'],c:1,why:'La posizione dell’ultimo accento tonico, non un conteggio rigido, definisce l’endecasillabo.',concept:'Endecasillabo',example:'Un verso piano ha normalmente undici sillabe, ma tronco o sdrucciolo varia.',retry:{q:'L’ultima sillaba tonica dell’endecasillabo è la…',o:['ottava','nona','decima'],c:2}},
        {q:'Che cosa significa “versi sciolti”?',o:['Senza metrica','Senza accenti','Senza schema regolare di rime'],c:2,why:'I versi conservano metro e ritmo, ma non una trama regolare di rime.',concept:'Versi sciolti',example:'Il Giorno usa endecasillabi sciolti.',retry:{q:'I versi sciolti possono essere endecasillabi?',o:['Sì','No','Solo in prosa'],c:0}},
        {q:'Da che cosa nasce il comico nella scelta fra caffè e cioccolata?',o:['Dallo squilibrio fra tono alto e fatto meschino','Dal tono basso','Da un errore grammaticale'],c:0,why:'La sproporzione smaschera la vacuità del mondo rappresentato.',concept:'Sproporzione satirica',example:'Una scelta quotidiana viene trattata come un evento epico.',retry:{q:'Il tono alto rende visibile la…',o:['grandezza reale','sproporzione','precisione scientifica'],c:1}},
        {q:'Perché la dedica nomina una futura “Sera”?',o:['Perché il testo è sbagliato','Perché riflette la prima progettazione dell’opera','Perché Vespro e Notte erano già pubblicati'],c:1,why:'Inizialmente Parini pensava a una terza parte chiamata Sera.',concept:'Storia redazionale',example:'La Sera sarà poi articolata nei progetti del Vespro e della Notte.',retry:{q:'La Sera appartiene alla progettazione…',o:['iniziale','postuma di Reina','medievale'],c:0}}
      ]
    },
    {
      id:'opere',short:'Le opere',title:'Il Giorno: un’epica del vuoto',
      lead:'Il capolavoro pariniano segue la giornata di un giovane aristocratico. La voce del precettore finge di insegnargli a vivere, ma la solennità della lezione rivela l’ozio e l’inutilità del protagonista.',
      html:`
        <p class="lesson-number">05 · Le opere più significative</p><h1><em>Il Giorno</em>: un’epica del vuoto</h1><p class="lead">Il capolavoro pariniano segue la giornata di un giovane aristocratico. La voce del precettore finge di insegnargli a vivere, ma la solennità della lezione rivela l’ozio e l’inutilità del protagonista.</p>
        <section data-visual="0"><h2>Lo specchio satirico della nobiltà</h2><ul><li><strong>Fine:</strong> riportare la nobiltà a una funzione morale, sociale ed economica.</li><li><strong>Struttura:</strong> <em>Mattino</em>, <em>Mezzogiorno</em>, <em>Vespro</em>, <em>Notte</em>.</li><li><strong>Forma:</strong> poema satirico in endecasillabi sciolti.</li><li><strong>Tecnica dominante:</strong> antifrasi.</li><li><strong>Critica sociale:</strong> ozio, cicisbeismo, culto dell’apparenza.</li></ul>
        <p><em>Il Mattino</em> esce nel 1763 e <em>Il Mezzogiorno</em> nel 1765. Parini continua poi a lavorare all’opera: la progettata <em>Sera</em> si articola in <em>Vespro</em> e <em>Notte</em>, rimasti incompiuti e pubblicati postumi. È quindi più esatto parlare di una lunga e non definitivamente conclusa storia redazionale, non di quattro parti tutte licenziate dall’autore nella stessa forma.</p></section>
        <section data-visual="1"><h2>Il giorno del giovin signore</h2><p>Il nobile segue ritmi innaturali, non vive le gioie della sua famiglia, violenta la natura. Si sveglia tardi perché ha trascorso la notte fra spettacoli e gioco; dedica il mattino alla toilette, agli incontri e alle visite; trasforma ogni gesto in cerimonia. Le ore notturne diventano, nel sonno prolungato, il suo mattino.</p>
        <p>Il narratore non dice semplicemente “quest’uomo è inutile”. Gli attribuisce un’importanza smisurata e descrive i suoi minimi gesti come imprese. Il lettore vede così il vuoto non attraverso una sentenza, ma attraverso la durata stessa del racconto.</p></section>
        <section data-visual="2"><h2>Due modelli di vita: buon villan e giovin signore</h2><div class="compare-grid"><div class="concept-card"><h3>Il buon villan</h3><p>Segue i ritmi naturali, lavora, vive la famiglia, partecipa al mantenimento della vita. Parini lo idealizza come figura di operosità e ordine morale.</p></div><div class="concept-card"><h3>Il giovin signore</h3><p>Capovolge giorno e notte, vive di spettacolo, gioco, toilette, visita mondana. Non serve la società: consuma tempo e privilegi.</p></div></div>
        <p>L’opposizione è morale e strutturale. Il contadino si alza quando la natura e il lavoro lo chiamano; il nobile si alza quando la notte mondana è finita. Uno produce le condizioni della vita, l’altro consuma il prodotto altrui. Il testo idealizza il primo per rendere giudicabile il secondo.</p></section>
        <section data-visual="3"><h2>Il cicisbeismo</h2><p>Il <strong>cicisbeo</strong>, o cavalier servente, accompagna pubblicamente una dama sposata secondo un costume aristocratico. Nel poema questo sistema mostra la distanza fra il rito mondano e il modello familiare difeso da Parini. Il rapporto coniugale viene svuotato, mentre la relazione sociale si organizza come una catena di apparenze e ruoli.</p>
        <p>La satira non dipende dal pettegolezzo. Il cicisbeismo diventa il segno di un ordine in cui la forma sociale pretende di sostituire la responsabilità affettiva. Parini collega così il costume privato a una più ampia inutilità pubblica.</p></section>
        <section data-visual="4"><h2>La “Vergin Cuccia”: quando i valori si rovesciano</h2><p>Nell’episodio della cagnolina, Parini mostra il capovolgimento morale della nobiltà. Una bestiola amata dalla dama viene trattata come idolo; il servo che l’ha colpita dopo essere stato morso viene licenziato e condannato alla miseria con la famiglia.</p>
        <div class="warning"><strong>Il nodo:</strong> la sensibilità aristocratica si commuove per l’animale, ma resta cieca davanti alla dignità umana. La pietà diventa moda; la giustizia scompare.</div>
        <p>L’episodio impedisce di ridurre il poema a una commedia leggera dei costumi. Dietro il gesto apparentemente raffinato emerge la violenza economica del privilegio: la dama può trasformare un’emozione in condanna perché il servo dipende da lei. La gerarchia sociale rende materiale il rovesciamento morale.</p></section>`,
      visuals:[
        {src:'assets/schema_primo_stato_03.png',alt:'Schema del Giorno: fine, struttura, forma, antifrasi e critica sociale',caption:'Il Giorno: progetto, forma e tre cardini del poema.'},
        {src:'assets/schema_primo_stato_01.png',alt:'Schema del giorno del giovin signore e dei suoi ritmi innaturali',caption:'Il giorno del giovin signore: il capovolgimento dei ritmi.'},
        {src:'assets/schema_primo_stato_05.png',alt:'Schema del buon villano: natura, lavoro, famiglia e dignità',caption:'Il modello positivo dei ritmi naturali e dell’operosità.'},
        {src:'assets/schema_primo_stato_09.png',alt:'Schema delle relazioni di cicisbeismo fra nobili, coniugi e cavalieri serventi',caption:'Il cicisbeismo come sistema sociale dell’apparenza.'},
        {src:'assets/schema_primo_stato_02.png',alt:'Confronto fra operosità del Terzo Stato e vita senza valore del nobile',caption:'Due modelli di vita e il loro incontro nel poema.'}
      ],
      knowledge:[
        'Il Giorno è un poema satirico-didascalico in cui un precettore finge di educare un giovane aristocratico.',
        'Mattino e Mezzogiorno furono pubblicati da Parini; Vespro e Notte, incompiuti, uscirono postumi.',
        'La giornata del giovin signore rende visibili ozio, ritmi innaturali e assenza di funzione sociale.',
        'Il buon villano è un modello poetico di lavoro, famiglia e accordo con i ritmi naturali.',
        'Il cicisbeismo esprime la trasformazione dei rapporti affettivi in rito mondano.',
        'La Vergin Cuccia denuncia il rovesciamento che antepone il capriccio aristocratico alla dignità del servo.'
      ],
      vocabulary:[['Giovin Signore','Giovane aristocratico protagonista del Giorno, figura dell’ozio privilegiato.'],['Poema didascalico','Componimento poetico che assume la forma dell’insegnamento; nel Giorno la didassi è ironica.'],['Cicisbeismo','Costume aristocratico del cavalier servente che accompagna una dama sposata.'],['Storia redazionale','Successione delle diverse progettazioni, stesure e revisioni di un’opera.'],['Vergin Cuccia','Cagnolina della dama al centro dell’episodio che rivela il rovesciamento dei valori.']],
      quiz:[
        {q:'Quale voce organizza Il Giorno?',o:['Un precettore che istruisce il giovin signore','Il servo licenziato','La Moda in prima persona'],c:0,why:'La finzione didascalica permette al narratore di lodare ironicamente il protagonista.',concept:'Precettore ironico',example:'I piccoli gesti del nobile vengono presentati come imprese.',retry:{q:'Il narratore finge soprattutto di…',o:['processare','istruire','confessarsi'],c:1}},
        {q:'Quali parti furono pubblicate da Parini?',o:['Vespro e Notte','Mattino e Mezzogiorno','Tutte e quattro'],c:1,why:'Le prime due uscirono nel 1763 e 1765; le ultime furono pubblicate postume.',concept:'Storia redazionale',example:'La Sera progettata si sdoppia in Vespro e Notte.',retry:{q:'Vespro e Notte uscirono…',o:['postumi','prima del Mattino','nel Medioevo'],c:0}},
        {q:'Che cosa rappresenta il buon villano?',o:['L’ozio raffinato','La carriera militare','Operosità e ritmi naturali'],c:2,why:'È costruito come modello positivo di lavoro e famiglia.',concept:'Modello positivo',example:'Si alza con il sole e partecipa al mantenimento della vita.',retry:{q:'Il buon villano segue ritmi…',o:['naturali','mondani','notturni'],c:0}},
        {q:'Che cos’è il cicisbeismo?',o:['Il costume del cavalier servente','Una forma metrica','Una riforma economica'],c:0,why:'Il cicisbeo accompagna una dama sposata nel sistema mondano aristocratico.',concept:'Costume aristocratico',example:'Il rito sociale svuota il rapporto coniugale.',retry:{q:'Il cicisbeo è detto anche…',o:['cavalier servente','precettore','villano'],c:0}},
        {q:'Qual è il nucleo morale della Vergin Cuccia?',o:['La condanna degli animali domestici','Il capriccio vale più della dignità del servo','La celebrazione della dama'],c:1,why:'La pietà selettiva per l’animale convive con l’indifferenza verso la famiglia umana.',concept:'Rovesciamento dei valori',example:'Il servo morso viene licenziato e ridotto alla miseria.',retry:{q:'Nell’episodio chi subisce la conseguenza economica?',o:['Il servo','La cagnolina','Il precettore'],c:0}}
      ]
    },
    {
      id:'conclusione',short:'Conclusione',title:'La responsabilità dello sguardo',
      lead:'Dalla crisi della funzione nobiliare alla forza civile della poesia: il percorso di Parini mostra che il linguaggio può servire il potere dell’apparenza oppure renderlo finalmente visibile.',
      html:`
        <p class="lesson-number">06 · Conclusione</p><h1>La responsabilità dello sguardo</h1><p class="lead">Dalla crisi della funzione nobiliare alla forza civile della poesia: il percorso di Parini mostra che il linguaggio può servire il potere dell’apparenza oppure renderlo finalmente visibile.</p>
        <section data-visual="0"><h2>Ricostruire la traiettoria</h2><p>Il mondo precedente consegna a Parini una nobiltà ancora privilegiata, ma in parte priva della funzione militare e politica che aveva giustificato il suo rango. La sua biografia gli permette di attraversare i tre ordini e di osservare da vicino il ceto aristocratico. Da qui nasce un’immagine del mondo fondata su dignità, natura, lavoro e responsabilità sociale.</p>
        <p>La poetica traduce questa visione in una forma precisa. Parini non abbandona lo stile alto: lo mette in attrito con la piccolezza delle azioni narrate. L’antifrasi obbliga il lettore a superare la superficie dell’elogio. <em>Il Giorno</em> diventa così un esperimento di educazione dello sguardo: insegna a non confondere prestigio e valore, sensibilità esibita e giustizia, desiderio e libertà.</p></section>
        <section data-visual="1"><h2>Che cosa resta di Parini</h2><p>Resta anzitutto un’idea esigente della letteratura. La poesia può cercare l’utile senza diventare un manuale; può essere civile senza rinunciare alla complessità della forma; può denunciare senza limitarsi allo slogan. Il lettore non riceve la tesi già pronta: deve riconoscere il doppio fondo della voce.</p>
        <p>Resta poi una domanda politica sul privilegio. Non basta possedere un ruolo, un titolo o una visibilità: occorre rispondere della funzione esercitata. Questa domanda attraversa epoche diverse, purché non venga usata per cancellarne le differenze.</p>
        <p>Resta infine l’analisi della Moda. Parini comprende che una norma è tanto più potente quanto meno appare come norma. Le “redini dolci” nominano il punto in cui il desiderio individuale incontra un codice collettivo. È lì che la libertà deve diventare consapevolezza.</p></section>
        <section data-visual="2"><h2>Attività per la classe</h2><div class="concept-grid"><div class="concept-card"><h3>Due letture dello stesso testo</h3><p>Dividi la classe in due gruppi: il primo difende la tesi apparente; il secondo ricostruisce la tesi vera. Poi sovrapponete le due mappe.</p></div><div class="concept-card"><h3>Chi è oggi la Dea Moda?</h3><p>Ogni gruppo sceglie una “dea” contemporanea: voto, smartphone, trend, corpo, relazione, successo. Deve spiegare quali redini dolci usa.</p></div><div class="concept-card"><h3>Antifrasi contemporanea</h3><p>Scrivi una dedica ironica a un potere del presente: “Alla Dea Notifica”, “Al Dio Voto”, “Alla Dea Apparenza”.</p></div><div class="concept-card"><h3>Verifica non mnemonica</h3><p>Spiega perché Parini usa l’elogio invece dell’accusa diretta. Poi applica lo stesso meccanismo a un fenomeno contemporaneo.</p></div></div></section>
        <section data-visual="0"><h2>La domanda conclusiva</h2><blockquote>Quando desideriamo qualcosa perché tutti la rendono desiderabile, siamo meno liberi — oppure la libertà comincia proprio dalla capacità di riconoscere quelle “redini dolci”?</blockquote>
        <p>La domanda non ammette una risposta comoda. Nessuno desidera in isolamento: linguaggio, esempi e relazioni formano sempre il nostro sguardo. Ma riconoscere questi condizionamenti non rende automaticamente liberi. Parini affida alla letteratura un primo compito più sobrio: creare la distanza necessaria perché ciò che sembrava naturale torni a essere discutibile.</p></section>
        <section data-visual="1"><h2>Fonti della PWA</h2><p>Materiali didattici di base: dispensa <em>Giuseppe Parini e la Dea Moda</em> e documento <em>Letteratura primo Stato</em>. Le immagini-schemi provengono dal documento allegato e dalle mappe generate per il percorso. Per il controllo biografico e della storia redazionale sono stati consultati la voce <em>Giuseppe Parini</em> dell’Enciclopedia Treccani e il relativo profilo del Dizionario Biografico degli Italiani.</p></section>`,
      visuals:[
        {src:'assets/schema_primo_stato_08.png',alt:'Mappa di sintesi di Parini fra origine borghese, clero, nobiltà e progetto di riforma',caption:'Dalla posizione biografica al progetto di riforma sociale.'},
        {src:'assets/schema_primo_stato_03.png',alt:'Mappa di sintesi del Giorno: struttura, forma, antifrasi e critica sociale',caption:'L’opera in cui confluiscono visione del mondo e poetica.'},
        {src:'assets/mappa_dea_moda_tesi_vera.png',alt:'Mappa conclusiva della vera tesi di Parini nella dedica alla Moda',caption:'La catena interpretativa: elogio apparente, critica reale.'}
      ],
      knowledge:[
        'La crisi della funzione nobiliare costituisce il problema storico da cui prende avvio il percorso.',
        'La posizione biografica di Parini gli consente uno sguardo interno e critico sul mondo aristocratico.',
        'Dignità, natura, lavoro e responsabilità sociale formano i criteri del suo giudizio.',
        'L’antifrasi trasforma il linguaggio elevato del privilegio in uno strumento di smascheramento.',
        'Il Giorno educa a distinguere prestigio e valore, emozione esibita e giustizia.',
        'Le redini dolci indicano il potere delle norme che agiscono attraverso il desiderio.'
      ],
      vocabulary:[['Coscienza civile','Capacità di giudicare comportamenti e istituzioni in rapporto al bene della comunità.'],['Privilegio','Vantaggio giuridico o sociale riservato a un gruppo o individuo.'],['Smascheramento','Procedimento che rende visibile ciò che un linguaggio o un rito nasconde.'],['Norma sociale','Aspettativa condivisa che orienta i comportamenti anche senza forza di legge.'],['Libertà consapevole','Capacità di riconoscere i condizionamenti che partecipano alla formazione dei desideri.']],
      quiz:[
        {q:'Da quale problema storico parte il percorso?',o:['Dalla crisi della funzione nobiliare','Dalla nascita del romanzo romantico','Dall’unità d’Italia'],c:0,why:'Il privilegio diventa criticabile quando non corrisponde più a una funzione.',concept:'Problema iniziale',example:'La nobiltà conserva rango ma perde il tradizionale ruolo militare.',retry:{q:'Il privilegio viene giudicato in rapporto alla…',o:['moda','funzione','genealogia soltanto'],c:1}},
        {q:'Che cosa collega vita e opera di Parini?',o:['Un viaggio in America','L’osservazione diretta del mondo aristocratico','La carriera militare'],c:1,why:'Il lavoro di precettore gli offre una conoscenza interna della nobiltà.',concept:'Nesso biografico',example:'Rituali e linguaggi di corte entrano nella costruzione del Giorno.',retry:{q:'Parini conosce la nobiltà come…',o:['precettore','generale','mercante'],c:0}},
        {q:'In che modo la forma serve la critica?',o:['Eliminando ogni stile','Usando soltanto accuse dirette','Accostando tono alto e materia futile'],c:2,why:'La sproporzione rende percepibile il vuoto della vita aristocratica.',concept:'Forma e giudizio',example:'I minimi gesti del giovin signore assumono una solennità epica.',retry:{q:'La satira nasce dalla…',o:['sproporzione','neutralità','casualità'],c:0}},
        {q:'Quale distinzione insegna l’episodio della Vergin Cuccia?',o:['Fra sensibilità esibita e giustizia','Fra metrica e prosa','Fra città e campagna'],c:0,why:'La dama prova pietà per l’animale ma ignora la dignità e la miseria del servo.',concept:'Giustizia',example:'Un’emozione raffinata produce una conseguenza umana violenta.',retry:{q:'La pietà della dama è moralmente…',o:['completa','selettiva','irrilevante'],c:1}},
        {q:'Quando le “redini dolci” diventano riconoscibili?',o:['Quando obbediamo senza riflettere','Quando analizziamo come il desiderio viene orientato','Quando una legge viene abolita'],c:1,why:'La consapevolezza comincia dal rendere discutibile ciò che appariva naturale.',concept:'Libertà consapevole',example:'La Moda presenta una norma collettiva come desiderio personale.',retry:{q:'La norma della Moda agisce attraverso…',o:['il desiderio','la forza militare','il tribunale'],c:0}}
      ]
    }
  ]
};
