// Eseguire con Node 22+: node tests/verify.mjs dalla cartella del modulo.
import fs from 'node:fs/promises';import path from 'node:path';import vm from 'node:vm';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../',import.meta.url)),repo=path.resolve(root,'../..');
const read=p=>fs.readFile(path.join(root,p),'utf8');let checks=0;function ok(value,message){assert.ok(value,message);checks++}
const context=vm.createContext({window:{}});vm.runInContext(await read('js/data.js'),context);vm.runInContext(await read('js/content.js'),context);const D=context.window.RA_DATA,T=context.window.RA_TEXTS;
ok(D.lessons.length===5,'Cinque lezioni');ok(D.approfondimenti.length===16,'Quattordici approfondimenti, libertà e riassunto');ok(D.biographies.length>=11,'Undici biografie');ok(D.maps.length>=17,'Mappe richieste');ok(D.quiz.length>=12&&D.quiz.length<=15,'Dimensione quiz finale');
const routes=new Set(['lezioni','home','liberta','riassunto','approfondimenti','mappe','biografie','timeline','quiz','fonti','installa',...D.lessons.map(x=>'lezione-'+x.id),...D.approfondimenti.map(x=>'approfondimento-'+x.id),...D.maps.map(x=>'mappa-'+x.id)]);
const allLinks=[];
for(const l of D.lessons){const g=D.guides[l.id],text=T.lessons[l.id];ok(g.sections.length===8,l.id+': otto sezioni');ok(g.essential.length>=10,l.id+': saperi');ok(g.quiz.length===3,l.id+': tre domande');ok(text.join(' ').split(/\s+/).length>=650,l.id+': lezione estesa');let indices=[];for(const s of g.sections){ok(s.from<=s.to,l.id+': sezione valida');for(let i=s.from;i<=s.to;i++)indices.push(i)}ok(indices.length===text.length&&new Set(indices).size===text.length,l.id+': nessun paragrafo perso');for(const r of g.resources)allLinks.push(r.href);for(const ls of Object.values(g.paragraphLinks))for(const x of ls)allLinks.push(x.href);}
for(const q of D.quiz){ok(q.a.length>=3&&q.ok>=0&&q.ok<q.a.length,'Opzioni quiz');ok(q.why.length>30,'Spiegazione quiz');allLinks.push(q.link)}
for(const t of D.timeline)allLinks.push(t.link);for(const b of D.biographies)allLinks.push(b.link);for(const link of allLinks)ok(routes.has(link.slice(1)),'Rotta valida '+link);
for(const group of [D.lessons,D.approfondimenti,D.biographies])for(const item of group)for(const key of item.sources)ok(!!D.sources[key],'Fonte definita '+key);
for(const m of D.maps){const svg=await read(m.img);ok(svg.includes('<title')&&svg.includes('<desc'),'SVG accessibile '+m.id);ok(m.items.length>0&&m.description.length>30,'Equivalente testuale '+m.id)}
const manifest=JSON.parse(await read('manifest.webmanifest'));ok(manifest.scope==='./'&&manifest.start_url==='./index.html','Scope relativo');for(const i of manifest.icons)ok((await fs.stat(path.join(root,i.src))).size>100,'Icona presente');
for(const f of ['index.html','app.html']){const html=await read(f);for(const match of html.matchAll(/(?:src|href)="([^"]+)"/g)){const u=match[1];if(u.startsWith('#')||u.startsWith('http')||u==='../index.html')continue;const filename=u.split(/[?#]/)[0];if(filename)ok((await fs.stat(path.resolve(root,filename))).isFile(),'Asset HTML '+filename)}ok(html.includes('lang="it"')&&html.includes('<main'),'Lingua e landmark');}
// Esegue il service worker reale in una rete simulata basata sui file del repository.
const base='https://example.test/IV-anno/Storia/Rivoluzione-americana/service-worker.js',listeners={},cacheStores=new Map([['rivoluzione-francese-v5',new Map()],['rivoluzione-americana-old',new Map()]]);let offline=false,claimed=false,skipped=false;
const key=r=>new URL(typeof r==='string'?r:r.url,base).href;
async function network(r){if(offline)throw Error('rete assente');let u=new URL(key(r)),rel=decodeURIComponent(u.pathname).replace(/^\/IV-anno\//,'');let p=path.join(repo,rel);if((await fs.stat(p)).isDirectory())p=path.join(p,'index.html');return new Response(await fs.readFile(p),{status:200})}
const caches={async keys(){return [...cacheStores.keys()]},async delete(k){return cacheStores.delete(k)},async open(k){if(!cacheStores.has(k))cacheStores.set(k,new Map());const entries=cacheStores.get(k);return {async addAll(urls){ok(urls.every(r=>r.cache==='reload'),'Precache aggiorna anche i componenti condivisi');const ready=await Promise.all(urls.map(async u=>[key(u),await network(u)]));for(const [u,r]of ready)entries.set(u,r)},async put(req,res){entries.set(key(req),res)},async match(req){return entries.get(key(req))?.clone()}}}};
const sw=vm.createContext({URL,Request,Response,Set,Promise,caches,fetch:network,self:{location:new URL(base),addEventListener:(n,f)=>listeners[n]=f,skipWaiting:async()=>{skipped=true},clients:{claim:async()=>{claimed=true}}}});const swText=await read('service-worker.js');vm.runInContext(swText,sw);let task;listeners.install({waitUntil:p=>task=p});await task;ok(skipped,'Installazione completata');listeners.activate({waitUntil:p=>task=p});await task;ok(claimed,'Clients claim');ok(cacheStores.has('rivoluzione-francese-v5'),'Cache delle altre PWA conservata');ok(!cacheStores.has('rivoluzione-americana-old'),'Vecchia cache locale rimossa');const assetList=vm.runInContext('ASSETS',sw);ok(assetList.length>=40,'Precache completo');
for(const asset of assetList){const u=new URL(asset,base);ok(u.pathname.startsWith('/IV-anno/'),'Compatibilità sottocartella Pages '+asset)}
offline=true;for(const asset of assetList){let result;listeners.fetch({request:{url:key(asset),method:'GET',mode:/html|^\.\/$/.test(asset)?'navigate':'cors'},respondWith:p=>result=p});const res=await result;ok(res?.ok,'Disponibile senza rete '+asset)}
let intercepted=false;listeners.fetch({request:{url:'https://external.test/source',method:'GET'},respondWith:()=>intercepted=true});ok(!intercepted,'Fonti esterne non intercettate');listeners.fetch({request:{url:'https://example.test/IV-anno/Storia/altro/app.html',method:'GET'},respondWith:()=>intercepted=true});ok(!intercepted,'Altre PWA non intercettate');
const ownApp=await read('js/app.js');ok(!/\bRF_DATA\b|\bRF_TEXTS\b|rf-notes/.test(ownApp),'Namespace americano');ok(!/fetch\s*\(|sendBeacon|XMLHttpRequest/.test(ownApp),'Nessun invio dati nel codice applicativo');
const common=await fs.readFile(path.join(repo,'pwa-common/gbprof-accessibility.js'),'utf8');ok(common.includes('["/storia/rivoluzione-americana/", ["ra-"], []]'),'Scope di cancellazione ra-');
console.log(`PASS: ${checks} controlli; ${D.lessons.length} lezioni; ${D.maps.length} mappe; ${assetList.length} risorse precache provate senza rete.`);
