window.NAP_DATA = {
  meta: {
    title: "Napoleone: figlio o traditore della Rivoluzione?",
    shortTitle: "Napoleone",
    question: "Napoleone conclude la Rivoluzione francese o la porta in Europa?",
    thesis: "Napoleone stabilizza e diffonde alcune conquiste del 1789 — uguaglianza civile, proprietà, amministrazione razionale — mentre restringe libertà politica, cittadinanza e autonomia dei popoli. La sua eredità è perciò inseparabile dalla sua contraddizione."
  },
  lessons: [
    {
      id: "figlio-rivoluzione", number: 1, title: "Figlio della Rivoluzione?", eyebrow: "Ascesa, merito e autorità", period: "1769-1797",
      lead: "Bonaparte non nasce dal nulla: la Rivoluzione apre carriere, crea eserciti di cittadini e rende possibile l'ascesa di un giovane ufficiale corso. Ma il generale impara presto a trasformare vittorie e propaganda in potere personale.",
      question: "In che senso l'ascesa di Napoleone sarebbe stata impossibile senza la Rivoluzione?",
      sections: [
        { title: "Un ufficiale di frontiera", paragraphs: [
          "Napoleone Bonaparte nasce ad Ajaccio nel 1769, poco dopo l'annessione francese della Corsica. Frequenta scuole militari del continente e diventa ufficiale d'artiglieria: una specializzazione tecnica in cui calcolo, formazione e capacità contano più dell'antichità del casato.",
          "La Rivoluzione sconvolge l'esercito dell'Antico regime. L'emigrazione di molti ufficiali nobili apre posti di comando; la guerra moltiplica le occasioni; la promozione per merito diventa più praticabile, anche se protezioni e relazioni restano importanti. Tolone nel 1793 e la repressione dell'insurrezione realista del 13 vendemmiaio 1795 lo rendono visibile al governo.",
          "Definirlo semplicemente un uomo che 'si è fatto da sé' sarebbe però ingannevole. Il suo talento opera dentro una trasformazione istituzionale: senza la crisi della monarchia, la mobilitazione di massa e il nuovo esercito rivoluzionario, quella rapidissima carriera non sarebbe stata possibile."
        ], summary: "Napoleone è insieme individuo eccezionale e prodotto delle opportunità create dalla Rivoluzione." },
        { title: "L'Italia: guerra, politica, racconto", paragraphs: [
          "Nel 1796 il Direttorio gli affida l'Armata d'Italia. Concentrazione delle forze, rapidità di movimento e capacità di dividere gli avversari permettono una serie di vittorie contro Piemonte e Austria. Il trattato di Campoformio del 1797 conferma la nuova centralità del generale.",
          "Napoleone parla ai soldati e ai popoli attraverso proclami, bollettini e giornali. Promette gloria, ricompense e liberazione, costruendo una relazione diretta fra il comandante e l'esercito. Le opere d'arte requisite e i tributi imposti alle repubbliche italiane ricordano però che la 'liberazione' finanzia anche la guerra francese.",
          "Le repubbliche sorelle introducono costituzioni e abolizioni di privilegi, ma dipendono dalle armi francesi. L'esperienza italiana contiene già la tensione fondamentale dell'età napoleonica: esportazione di principi universali e subordinazione politica dei territori occupati."
        ], summary: "La prima campagna d'Italia unisce innovazione militare, propaganda e dominio: è il laboratorio del potere napoleonico." },
        { title: "Continuità e prima frattura", paragraphs: [
          "Napoleone adotta il linguaggio del cittadino-soldato e difende proprietà e carriere aperte ai talenti. In questo senso è figlio del 1789. Ma la sua autorità nasce anche dall'obbedienza personale dell'esercito e dall'uso della vittoria come fonte di legittimità.",
          "Il Direttorio, debole e dipendente dai successi militari, lascia ai generali una crescente autonomia. Napoleone negozia trattati, ridisegna territori, orienta l'opinione pubblica. La distinzione fra comando militare e decisione politica si assottiglia.",
          "La domanda decisiva non è dunque se egli conservi o cancelli in blocco la Rivoluzione. Occorre seguire quali eredità seleziona, quali limita e a quali gruppi sociali offre sicurezza."
        ], summary: "Prima del colpo di Stato, il generale ha già trasformato il prestigio militare in una risorsa politica autonoma." }
      ],
      coordinates: ["1769: nascita ad Ajaccio", "1793: Tolone", "5 ottobre 1795: 13 vendemmiaio", "1796-1797: prima campagna d'Italia", "17 ottobre 1797: Campoformio"],
      essentials: ["La Rivoluzione apre nuove possibilità di carriera militare.", "Il merito non elimina reti di protezione e circostanze favorevoli.", "La campagna d'Italia lega vittoria, propaganda e potere.", "Le repubbliche sorelle combinano riforme e dipendenza.", "L'autorità personale del generale cresce dentro la crisi del Direttorio."],
      vocab: { "Armata d'Italia":"Esercito francese impiegato sul fronte italiano, comandato da Bonaparte dal 1796.", "Repubblica sorella":"Repubblica modellata sulla Francia e dipendente dalla sua protezione militare.", "Meritocrazia":"Principio di selezione fondato sulle capacità; nell'età napoleonica resta intrecciato a fedeltà e patronato.", "Propaganda":"Produzione orientata di immagini e racconti per costruire consenso.", "Plebiscito":"Votazione popolare chiamata a ratificare una scelta politica già formulata." }
    },
    {
      id: "repubblica-uomo-forte", number: 2, title: "La Repubblica e l'uomo forte", eyebrow: "Dal 18 brumaio al Consolato", period: "1797-1802",
      lead: "Dopo dieci anni di rivoluzione, una parte della società francese desidera ordine senza ritorno all'Antico regime. Il 18 brumaio risponde a questa domanda, ma trasferisce il centro della Repubblica dal cittadino all'esecutivo.",
      question: "Come può un colpo di Stato presentarsi come salvezza della Repubblica?",
      sections: [
        { title: "Una Repubblica in crisi", paragraphs: [
          "Il Direttorio vive fra guerra, difficoltà finanziarie, conflitti religiosi e colpi di forza contro realisti e giacobini. La Costituzione dell'anno III aveva cercato di impedire nuove dittature, ma l'equilibrio fra esecutivo e assemblee produce instabilità e sfiducia.",
          "La spedizione d'Egitto del 1798 mostra ambizione strategica e interesse scientifico, ma la distruzione della flotta francese ad Abukir isola l'esercito. Bonaparte rientra in Francia mentre la Seconda coalizione minaccia le conquiste repubblicane.",
          "Sieyès cerca una revisione costituzionale; militari e notabili cercano un esecutivo capace. Il progetto non è un semplice golpe di un uomo isolato: nasce da una coalizione di interessi, che Napoleone saprà poi dominare."
        ], summary: "La crisi del Direttorio crea una domanda di autorità che diversi attori cercano di utilizzare." },
        { title: "18-19 brumaio: la legalità forzata", paragraphs: [
          "Il 18 e 19 brumaio anno VIII, 9-10 novembre 1799, le assemblee vengono trasferite a Saint-Cloud con il pretesto di un complotto. Napoleone interviene davanti ai deputati; la resistenza del Consiglio dei Cinquecento viene superata dall'intervento dei soldati.",
          "Una commissione prepara la Costituzione dell'anno VIII. Formalmente la Repubblica continua e rimangono assemblee e suffragio maschile indiretto; nella pratica il Primo console propone le leggi, nomina funzionari e domina l'esecutivo. I cittadini scelgono liste di notabilità, ma il potere seleziona dall'alto.",
          "Il plebiscito ratifica la nuova Costituzione. Il voto offre una forma di consenso popolare, ma senza competizione aperta e con risultati manipolati. Nasce una legittimità ibrida: sovranità dichiarata del popolo, autorità effettiva del capo."
        ], summary: "Il Consolato conserva forme repubblicane mentre concentra la decisione nel Primo console." },
        { title: "Ordine sociale e pace", paragraphs: [
          "La vittoria di Marengo nel 1800 rafforza il regime. La pace di Lunéville con l'Austria e quella di Amiens con la Gran Bretagna sembrano chiudere il ciclo rivoluzionario. Nel 1802 un nuovo plebiscito rende Bonaparte console a vita.",
          "La formula politica è chiara: proteggere le proprietà nate dalle vendite dei beni nazionali, mantenere l'uguaglianza civile e chiudere l'instabilità. Notabili, proprietari e molti funzionari accettano un esecutivo forte in cambio di sicurezza.",
          "Non tutti vengono inclusi nel nuovo patto. La stampa è ridotta, l'opposizione sorvegliata, gli ex giacobini e i realisti possono essere deportati o esclusi. La stabilità non è il contrario della Rivoluzione: è una selezione autoritaria dei suoi risultati."
        ], summary: "Il Consolato promette di terminare la Rivoluzione conservandone i risultati sociali più compatibili con l'ordine." }
      ],
      coordinates: ["1798-1801: spedizione d'Egitto", "9-10 novembre 1799: 18-19 brumaio", "13 dicembre 1799: Costituzione dell'anno VIII", "1800: Marengo e prefetti", "1802: pace di Amiens e consolato a vita"],
      essentials: ["Il colpo di Stato nasce da una crisi istituzionale e da una coalizione di élite.", "La Costituzione dell'anno VIII concentra il potere esecutivo.", "Il plebiscito produce consenso senza vero pluralismo.", "Il regime difende le proprietà rivoluzionarie.", "Ordine e repressione sono due aspetti dello stesso progetto."],
      vocab: { "Direttorio":"Regime repubblicano francese del 1795-1799 con esecutivo collegiale.", "18 brumaio":"Data rivoluzionaria del colpo di Stato che porta Bonaparte al potere.", "Consolato":"Regime istituito dalla Costituzione dell'anno VIII.", "Notabile":"Persona dotata di proprietà, influenza e riconoscimento sociale.", "Suffragio indiretto":"Sistema in cui gli elettori non scelgono direttamente tutti i titolari delle cariche." }
    },
    {
      id: "salvare-controllando", number: 3, title: "Salvare la Rivoluzione controllandola", eyebrow: "Stato, Codice e società", period: "1800-1804",
      lead: "Il Consolato rende durature alcune trasformazioni rivoluzionarie costruendo uno Stato accentrato. L'uguaglianza davanti alla legge avanza; la libertà politica arretra; la famiglia resta gerarchica e la schiavitù viene ristabilita nelle colonie.",
      question: "Quale prezzo politico e sociale viene pagato per stabilizzare le conquiste del 1789?",
      sections: [
        { title: "Uno Stato che arriva ovunque", paragraphs: [
          "La legge del 28 piovoso anno VIII crea i prefetti, nominati dal centro per amministrare i dipartimenti. Bilanci, polizia, coscrizione e lavori pubblici vengono coordinati con maggiore uniformità. Lo Stato rivoluzionario diventa più efficiente, ma anche più verticale.",
          "La Banca di Francia e il franco germinale stabilizzano moneta e credito. I licei formano funzionari e ufficiali; la Legion d'onore premia il servizio. Non scompare la gerarchia sociale: cambia il criterio ufficiale con cui viene giustificata, dal privilegio di nascita al merito riconosciuto dallo Stato.",
          "Il Concordato del 1801 con Pio VII riconosce il cattolicesimo come religione della maggioranza dei francesi e reintegra la Chiesa nella vita pubblica. In cambio il governo controlla nomine e organizzazione: riconciliazione religiosa e subordinazione istituzionale procedono insieme."
        ], summary: "Le riforme consolari costruiscono uno Stato moderno, uniforme e accentrato." },
        { title: "Il Codice civile: uguaglianza e gerarchia", paragraphs: [
          "Promulgato nel 1804, il Codice civile unifica regole prima frammentate. Garantisce proprietà privata, uguaglianza civile dei cittadini maschi, libertà contrattuale e abolizione dei privilegi feudali. La chiarezza della legge diventa parte dell'eredità napoleonica in Europa.",
          "La stessa codificazione rafforza però l'autorità del marito e del padre. La moglie deve obbedienza al marito ed è limitata nella capacità di disporre dei beni o comparire in giudizio; i figli sono sottoposti alla patria potestà. L'uguaglianza giuridica è definita dentro un ordine di genere diseguale.",
          "Il Codice non è la pura trascrizione del 1789 né una semplice restaurazione patriarcale. È un compromesso: universalizza alcune conquiste, protegge l'ordine proprietario e stabilisce nuove esclusioni con la forza della legge."
        ], summary: "Il Codice rende universale l'uguaglianza civile maschile e legale una gerarchia familiare più netta." },
        { title: "Il limite coloniale", paragraphs: [
          "Nel 1794 la Convenzione aveva abolito la schiavitù nelle colonie francesi. La legge del 20 maggio 1802 mantiene la schiavitù nei territori restituiti dalla pace di Amiens e apre la via al suo ristabilimento altrove; decreti successivi la reintroducono dove era stata abolita.",
          "A Saint-Domingue la resistenza guidata anche da Toussaint Louverture e poi la guerra contro le truppe francesi conducono all'indipendenza di Haiti nel 1804. La rivoluzione antischiavista mostra che il linguaggio universale dei diritti può essere rivolto contro la Francia imperiale.",
          "Questo passaggio impedisce di raccontare Napoleone come semplice esportatore dell'uguaglianza. Cittadinanza, razza, genere e spazio coloniale stabiliscono confini concreti dell'universalismo rivoluzionario."
        ], summary: "Il ristabilimento della schiavitù rivela la frattura più radicale fra universalismo proclamato e politica napoleonica." }
      ],
      coordinates: ["1800: creazione dei prefetti e Banca di Francia", "1801: Concordato", "20 maggio 1802: legge coloniale", "1802: licei e Legion d'onore", "21 marzo 1804: Codice civile", "1 gennaio 1804: indipendenza di Haiti"],
      essentials: ["I prefetti rendono l'amministrazione più uniforme e dipendente dal centro.", "Il Concordato pacifica il conflitto religioso ma rafforza il controllo statale.", "Il Codice tutela proprietà e uguaglianza civile maschile.", "La famiglia codificata resta patriarcale.", "Il ristabilimento della schiavitù contraddice l'universalismo del 1789."],
      vocab: { "Prefetto":"Rappresentante del governo centrale nel dipartimento.", "Codificazione":"Raccolta organica e sistematica delle norme in un codice.", "Concordato":"Accordo fra uno Stato e la Santa Sede.", "Patria potestà":"Autorità giuridica del padre sulla famiglia nel Codice civile.", "Schiavitù coloniale":"Sistema di lavoro coatto e proprietà delle persone nelle colonie." }
    },
    {
      id: "repubblica-incorona", number: 4, title: "Quando la Repubblica si incorona", eyebrow: "Impero, simboli e consenso", period: "1804-1808",
      lead: "Nel 1804 la Repubblica affida il governo a un imperatore ereditario. Il lessico repubblicano non scompare: viene assorbito in una monarchia nuova, fondata su plebiscito, gloria militare e amministrazione.",
      question: "Che cosa significa un impero che continua a chiamarsi governo della Repubblica?",
      sections: [
        { title: "Dall'attentato alla successione", paragraphs: [
          "Complotti realisti e il timore di un vuoto di potere alimentano l'idea di una successione stabile. Il rapimento e la fucilazione del duca d'Enghien nel marzo 1804 mostrano insieme la vulnerabilità del regime e la sua disponibilità a violare confini giuridici.",
          "Il senatoconsulto del 28 floreale anno XII dichiara che il governo della Repubblica è affidato a un imperatore, Napoleone Bonaparte, e rende ereditaria la dignità. La formula unisce due linguaggi incompatibili solo in apparenza: la nazione ratifica tramite plebiscito una dinastia nuova.",
          "L'Impero non ripristina l'Antico regime. Titoli, nobiltà imperiale e corti premiano servizio e fedeltà; tuttavia ricreano distanze sociali e una politica dinastica. L'uguaglianza civile convive con una nuova élite."
        ], summary: "L'Impero converte la sovranità rivoluzionaria in legittimazione plebiscitaria di una dinastia." },
        { title: "L'incoronazione come manifesto", paragraphs: [
          "Il 2 dicembre 1804, a Notre-Dame, Pio VII assiste all'incoronazione. Napoleone pone la corona sul proprio capo e incorona Giuseppina: il gesto comunica che l'autorità non viene semplicemente ricevuta dal papa, pur ricercando una consacrazione religiosa.",
          "Il grande dipinto di Jacques-Louis David costruisce una memoria ordinata e solenne dell'evento. Assenze e tensioni vengono ricomposte nella scena; la madre di Napoleone, che non partecipò, compare nella tribuna. L'immagine non registra soltanto: interpreta e legittima.",
          "Aquile romane, api merovinge, alloro, ermellino e mano di giustizia formano un linguaggio visivo composito. L'Impero cerca antenati molteplici perché non può fondarsi su una sola tradizione: è monarchico, romano, nazionale e rivoluzionario insieme."
        ], summary: "La cerimonia e la pittura trasformano la presa del potere in un racconto di continuità, consenso e sacralità." },
        { title: "Il consenso sorvegliato", paragraphs: [
          "Il regime mantiene plebisciti, Consiglio di Stato e corpi legislativi, ma il dibattito pubblico è ristretto. La censura riduce il numero dei giornali; la polizia di Fouché raccoglie informazioni e controlla oppositori e opinione.",
          "Il consenso non dipende soltanto dalla paura. Vittorie, carriere, stabilità economica, riconciliazione religiosa e prestigio nazionale creano adesione reale. Per capire una dittatura moderna bisogna studiare insieme coercizione, benefici e partecipazione.",
          "La crisi del 1808 in Spagna e le difficoltà dinastiche mostrano il limite del sistema: quando la legittimità viene esportata con la forza, il plebiscito e la riforma non bastano a produrre obbedienza."
        ], summary: "Il regime è autoritario ma non si regge sulla sola repressione: costruisce consenso attraverso risultati, simboli e opportunità." }
      ],
      coordinates: ["21 marzo 1804: fucilazione del duca d'Enghien", "18 maggio 1804: senatoconsulto dell'anno XII", "2 dicembre 1804: incoronazione", "1805: Austerlitz", "1808: nuova nobiltà imperiale"],
      essentials: ["L'Impero mantiene formalmente la continuità con la Repubblica.", "L'ereditarietà stabilizza il regime e restringe l'alternanza politica.", "L'incoronazione è una costruzione simbolica complessa.", "David rappresenta una versione politica dell'evento.", "Consenso e sorveglianza funzionano insieme."],
      vocab: { "Senatoconsulto":"Atto del Senato che modifica o integra la Costituzione.", "Legittimità plebiscitaria":"Autorità fondata sulla ratifica popolare diretta del capo.", "Nobiltà imperiale":"Sistema di titoli creato da Napoleone per premiare servizio e fedeltà.", "Censura":"Controllo preventivo o repressivo della circolazione delle idee.", "Iconografia":"Insieme di immagini, simboli e loro significati." }
    },
    {
      id: "liberatore-conquistatore", number: 5, title: "Liberatore o conquistatore?", eyebrow: "L'Europa napoleonica", period: "1805-1811",
      lead: "Le armate francesi cancellano privilegi e ridisegnano Stati, ma impongono tributi, soldati e governi dinastici. L'Europa napoleonica è un sistema a geometria variabile, non una copia uniforme della Francia.",
      question: "Le riforme imposte da un occupante possono essere considerate liberazione?",
      sections: [
        { title: "Un sistema di cerchi", paragraphs: [
          "Dopo Austerlitz e Jena, il Sacro romano impero scompare e nasce la Confederazione del Reno. Il Regno d'Italia, quello di Napoli, la Vestfalia, il Granducato di Varsavia e altri Stati clienti vengono affidati a parenti o alleati di Napoleone.",
          "L'Impero francese direttamente annesso costituisce il centro; Stati satelliti e alleati formano cerchi esterni. La sovranità è diseguale: alcuni territori ricevono costituzioni e codici, ma devono contribuire alla strategia francese con denaro, merci e uomini.",
          "Non esiste una sola 'modernizzazione napoleonica'. Il Codice civile è adottato integralmente in alcuni Stati, adattato in altri, rifiutato o applicato solo in parte. Le élite locali negoziano, collaborano o resistono."
        ], summary: "L'Europa napoleonica è una gerarchia di territori con diversi gradi di riforma e subordinazione." },
        { title: "Riforme che restano", paragraphs: [
          "In molte regioni vengono aboliti privilegi feudali, resi più uniformi i sistemi fiscali e amministrativi, secolarizzati beni ecclesiastici e introdotta l'uguaglianza civile. Questi cambiamenti favoriscono proprietari, funzionari e professionisti.",
          "L'efficienza amministrativa serve però anche l'estrazione di risorse. Catasti, registri e prefetti rendono lo Stato più capace di tassare e reclutare. La stessa istituzione può essere letta come razionalizzazione e come strumento di dominio.",
          "Dopo il 1815 molti governi restaurati non cancellano tutto: conservano codici, burocrazie e assetti proprietari utili. La durata di una riforma non dimostra che fosse accettata, ma indica che aveva trasformato interessi e pratiche."
        ], summary: "Le riforme sopravvivono quando diventano strumenti utili e creano gruppi interessati a difenderle." },
        { title: "La Spagna e la nascita della resistenza", paragraphs: [
          "Nel 1808 Napoleone costringe i Borbone di Spagna ad abdicare e pone sul trono il fratello Giuseppe. La crisi di Bayonne trasforma un'alleanza instabile in occupazione e provoca insurrezione popolare, guerra regolare e guerriglia.",
          "La resistenza spagnola unisce motivazioni differenti: fedeltà dinastica, religione, difesa locale e progetto costituzionale. Le Cortes di Cadice approvano nel 1812 una Costituzione liberale mentre combattono i francesi: opposizione a Napoleone e appropriazione di idee rivoluzionarie possono convivere.",
          "Goya mostra la violenza della repressione e rende visibile chi paga la guerra. La Spagna è un punto di svolta perché nega l'equazione automatica fra conquista francese e progresso."
        ], summary: "La resistenza spagnola combina guerra nazionale, difesa religiosa e costituzionalismo liberale." }
      ],
      coordinates: ["1805: Austerlitz", "1806: Confederazione del Reno e Jena", "1807: Tilsit e Regno di Vestfalia", "1808: crisi di Bayonne e guerra di Spagna", "1810-1811: massima estensione del sistema napoleonico", "1812: Costituzione di Cadice"],
      essentials: ["L'Europa napoleonica è organizzata in cerchi gerarchici.", "Le riforme variano secondo i territori.", "Modernizzazione ed estrazione di risorse possono coincidere.", "La collaborazione locale è importante quanto l'imposizione francese.", "La Spagna rivela il limite della liberazione dall'alto."],
      vocab: { "Stato cliente":"Stato formalmente autonomo ma dipendente dalla potenza egemone.", "Secolarizzazione":"Trasferimento di beni o funzioni dalla Chiesa allo Stato o ai privati.", "Guerriglia":"Combattimento irregolare di piccoli gruppi contro un esercito più forte.", "Nazionalismo":"Dottrina o movimento che attribuisce alla nazione un primato politico.", "Modernizzazione":"Trasformazione di istituzioni e società; non implica automaticamente maggiore libertà." }
    },
    {
      id: "governare-guerra", number: 6, title: "Governare attraverso la guerra", eyebrow: "Blocco, coscrizione e costi", period: "1806-1812",
      lead: "Il sistema napoleonico è sostenuto dalle vittorie, ma proprio per questo deve continuare a produrle. La guerra finanzia lo Stato e diffonde riforme; allo stesso tempo consuma uomini, risorse e consenso.",
      question: "Un impero fondato sulla vittoria può smettere di combattere senza perdere autorità?",
      sections: [
        { title: "La Grande Armée e la società", paragraphs: [
          "La coscrizione, ereditata dalla Rivoluzione, permette di mobilitare centinaia di migliaia di uomini. Sorteggi, sostituzioni e quote locali distribuiscono il peso in modo diseguale; famiglie e comunità negoziano, eludono o resistono.",
          "L'esercito offre paga, bottino, promozione e appartenenza. Ma le campagne lontane producono morte, diserzione e mutilazione. Gli elenchi di leva mostrano lo Stato moderno nel suo rapporto più concreto con i corpi dei cittadini.",
          "Dopo il 1805 contingenti tedeschi, italiani, polacchi e olandesi entrano nelle armate imperiali. La Grande Armée diventa europea, ma non per libera federazione: è il prodotto della gerarchia imperiale."
        ], summary: "La coscrizione trasforma il cittadino in risorsa militare e lega la società alla capacità amministrativa dello Stato." },
        { title: "Il blocco continentale", paragraphs: [
          "Incapace di sconfiggere la Gran Bretagna sul mare dopo Trafalgar, Napoleone tenta la guerra economica. Il decreto di Berlino del 1806 chiude i porti continentali alle merci britanniche; Londra risponde con propri ordini commerciali.",
          "Il blocco stimola alcune produzioni continentali, ma provoca scarsità, contrabbando e conflitti con Stati alleati. Farlo rispettare richiede controlli, annessioni e nuove campagne: l'arma economica allarga il costo politico dell'Impero.",
          "L'invasione del Portogallo e la pressione sulla Spagna sono connesse al blocco. Anche il deterioramento dei rapporti con la Russia nasce in parte dalle difficoltà commerciali. Una strategia contro la Gran Bretagna produce fronti terrestri sempre più vasti."
        ], summary: "Il blocco continentale converte la guerra economica in espansione politica e militare." },
        { title: "1812: il sistema oltre il limite", paragraphs: [
          "Nel giugno 1812 la Grande Armée attraversa il Niemen. Napoleone cerca una battaglia decisiva, mentre l'esercito russo arretra e consuma risorse. Borodino apre la strada a Mosca, ma non costringe Alessandro I alla pace.",
          "La ritirata è distrutta da fame, malattie, freddo, combattimenti e collasso logistico. Ridurre tutto all'inverno cancella errori strategici precedenti: distanza, rifornimenti, cavalli, tempo e natura della guerra russa.",
          "La catastrofe non abbatte immediatamente Napoleone, ma spezza l'immagine d'invincibilità e offre ai nemici l'occasione di una nuova coalizione. La potenza fondata sulla mobilitazione continua raggiunge il proprio limite materiale."
        ], summary: "La campagna di Russia rivela che superiorità organizzativa e vittoria tattica non bastano senza logistica e obiettivo politico raggiungibile." }
      ],
      coordinates: ["21 novembre 1806: decreto di Berlino", "1805: Trafalgar", "1808-1814: guerra di Spagna", "24 giugno 1812: attraversamento del Niemen", "7 settembre 1812: Borodino", "14 settembre 1812: ingresso a Mosca", "novembre 1812: Beresina"],
      essentials: ["La coscrizione collega esercito, amministrazione e società.", "Il peso della leva è socialmente diseguale.", "Il blocco continentale mira a colpire l'economia britannica.", "Far rispettare il blocco spinge a nuove conquiste.", "La campagna di Russia fallisce per cause strategiche e logistiche, non solo climatiche."],
      vocab: { "Coscrizione":"Reclutamento obbligatorio regolato dallo Stato.", "Grande Armée":"Esercito multinazionale dell'Impero napoleonico.", "Blocco continentale":"Sistema di esclusione delle merci britanniche dai porti europei.", "Logistica":"Organizzazione di rifornimenti, trasporti e alloggi di un esercito.", "Guerra d'attrito":"Conflitto in cui il consumo progressivo di uomini e risorse diventa decisivo." }
    },
    {
      id: "caduta-eredita", number: 7, title: "Caduta ed eredità", eyebrow: "1813-1821 e oltre", period: "1813-1821",
      lead: "La sconfitta distrugge l'Impero, non tutte le sue istituzioni né il mito del suo fondatore. Nel 1815 i vincitori restaurano dinastie ma conservano parti dello Stato napoleonico; la memoria divide subito liberatori, vittime e ammiratori.",
      question: "Che cosa resta di Napoleone quando il suo sistema politico è sconfitto?",
      sections: [
        { title: "Dalla Germania a Waterloo", paragraphs: [
          "Nel 1813 Prussia, Russia, Austria e altri Stati uniscono risorse contro la Francia. La battaglia di Lipsia, detta delle Nazioni, costringe Napoleone a ritirarsi oltre il Reno. Nel 1814 gli alleati entrano a Parigi e l'imperatore abdica.",
          "Dall'isola d'Elba Napoleone torna in Francia nel marzo 1815. Durante i Cento giorni promette un Impero più liberale, ma deve ricostruire rapidamente esercito e alleanze. La sconfitta di Waterloo il 18 giugno chiude la possibilità del ritorno.",
          "L'esilio a Sant'Elena isola Napoleone fino alla morte nel 1821. Dettando ricordi e giudizi, egli contribuisce però a costruire il proprio futuro politico: il vinto diventa autore della propria leggenda."
        ], summary: "La caduta è un processo europeo; Waterloo chiude il ritorno, mentre Sant'Elena apre la battaglia della memoria." },
        { title: "Restaurare senza cancellare", paragraphs: [
          "Il Congresso di Vienna ridisegna l'equilibrio fra potenze e restaura dinastie. Tuttavia in Francia rimangono Codice civile, uguaglianza fiscale, vendite dei beni nazionali e molte strutture amministrative. Anche altrove i sovrani mantengono strumenti napoleonici utili.",
          "Le riforme non sopravvivono in modo uniforme. Alcune costituzioni vengono revocate, privilegi ripristinati o autonomie cancellate. La Restaurazione è una selezione, non un ritorno integrale al 1788.",
          "Le guerre hanno inoltre diffuso linguaggi nazionali e costituzionali. Chi aveva combattuto Napoleone in nome della libertà scopre che i vincitori non intendono sempre concederla: da questa contraddizione nasceranno nuove opposizioni."
        ], summary: "Il 1815 restaura il potere dinastico ma deve governare società trasformate da Rivoluzione e Impero." },
        { title: "Pronunciare una tesi", paragraphs: [
          "Per alcuni contemporanei Napoleone è il tiranno che ha sacrificato l'Europa alla propria ambizione; per altri è il garante dell'uguaglianza civile contro i privilegi. Entrambe le immagini selezionano prove reali e ne oscurano altre.",
          "Una tesi storica solida deve precisare soggetto, spazio e criterio. Napoleone può apparire liberatore a un proprietario che ottiene uguaglianza giuridica, conquistatore a una comunità sottoposta a requisizioni, restauratore dell'ordine per un notabile francese, traditore per una donna esclusa o per una persona ridotta in schiavitù.",
          "La risposta più utile alla domanda iniziale non è un verdetto morale unico. È l'argomentazione di una trasformazione: Napoleone rende durevoli e trasferibili alcune conquiste rivoluzionarie subordinandole a Stato, guerra e autorità personale."
        ], summary: "L'eredità napoleonica cambia secondo la prospettiva, ma la contraddizione fra uguaglianza civile e dominio politico resta il suo nucleo." }
      ],
      coordinates: ["16-19 ottobre 1813: Lipsia", "6 aprile 1814: prima abdicazione", "1 marzo-22 giugno 1815: Cento giorni", "9 giugno 1815: Atto finale di Vienna", "18 giugno 1815: Waterloo", "5 maggio 1821: morte a Sant'Elena"],
      essentials: ["La coalizione del 1813 combina guerra e mobilitazione nazionale.", "I Cento giorni mostrano insieme la forza del mito e la fragilità militare.", "La Restaurazione conserva diverse istituzioni napoleoniche.", "La memoria di Sant'Elena costruisce la leggenda napoleonica.", "Una tesi storica deve indicare prospettiva, criteri e prove."],
      vocab: { "Restaurazione":"Riassetto politico europeo successivo alla sconfitta napoleonica.", "Cento giorni":"Periodo del ritorno di Napoleone dall'Elba alla seconda abdicazione.", "Memoriale":"Racconto retrospettivo che seleziona e interpreta il passato.", "Mito napoleonico":"Insieme di immagini eroiche o negative costruite attorno a Napoleone.", "Eredità storica":"Persistenza e rielaborazione nel tempo di istituzioni, idee e memorie." }
    }
  ],
  people: [
    { id:"napoleone", name:"Napoleone Bonaparte", years:"1769-1821", role:"generale, console, imperatore", image:"assets/img/protagonisti/napoleone.jpg", lesson:"figlio-rivoluzione", bio:"Ufficiale d'artiglieria formatosi nelle scuole militari francesi, emerge durante la Rivoluzione, prende il potere nel 1799 e costruisce un Impero continentale. La sua azione lega amministrazione razionale, uguaglianza civile, controllo politico e guerra.", idea:"Non un'eccezione fuori dalla storia, ma il punto in cui Rivoluzione, Stato e guerra si saldano." },
    { id:"giuseppina", name:"Giuseppina de Beauharnais", years:"1763-1814", role:"imperatrice e mediatrice di reti", image:"assets/img/protagonisti/giuseppina.jpg", lesson:"repubblica-incorona", bio:"Sopravvissuta al Terrore e inserita nei circuiti del Direttorio, sposa Bonaparte nel 1796. Come imperatrice costruisce patronati e rappresentazione dinastica; il divorzio del 1810 rivela la subordinazione della relazione personale alla successione.", idea:"La corte imperiale è anche una rete di relazioni, mediazioni e aspettative dinastiche." },
    { id:"fouche", name:"Joseph Fouché", years:"1759-1820", role:"ministro della Polizia", image:"assets/img/protagonisti/fouche.jpg", lesson:"repubblica-incorona", bio:"Rivoluzionario regicida e poi ministro, organizza una vasta rete informativa. La sua traiettoria mostra la continuità di personale e tecniche fra Rivoluzione, Consolato e Impero.", idea:"L'informazione è una forma di potere: conoscere l'opinione permette di sorvegliarla e orientarla." },
    { id:"talleyrand", name:"Charles-Maurice de Talleyrand", years:"1754-1838", role:"diplomatico e ministro", image:"../Restaurazione/assets/img/protagonisti/talleyrand.jpg", lesson:"caduta-eredita", bio:"Vescovo dell'Antico regime, rivoluzionario moderato, ministro di Napoleone e negoziatore per Luigi XVIII. Sopravvive ai regimi perché legge interessi e rapporti di forza meglio delle fedeltà personali.", idea:"La diplomazia trasforma la sconfitta francese in reintegrazione nel concerto europeo." },
    { id:"toussaint", name:"Toussaint Louverture", years:"1743-1803", role:"leader della rivoluzione di Saint-Domingue", image:"assets/img/protagonisti/toussaint.jpg", lesson:"salvare-controllando", bio:"Nato schiavo, diventa generale e governatore di Saint-Domingue dopo l'abolizione del 1794. Arrestato dalla spedizione francese e morto in prigionia, lega la rivoluzione haitiana all'universalità concreta della libertà.", idea:"Se i diritti sono universali, gli schiavi possono reclamarli contro la potenza che li ha proclamati." },
    { id:"alessandro", name:"Alessandro I", years:"1777-1825", role:"zar di Russia", image:"../Restaurazione/assets/img/protagonisti/alessandro-i.jpg", lesson:"governare-guerra", bio:"Alleato e avversario di Napoleone in fasi diverse, firma Tilsit nel 1807 e resiste all'invasione del 1812. È decisivo nella coalizione finale e nell'ordine europeo del 1815.", idea:"La cooperazione con l'egemone dura finché i suoi costi non minacciano autonomia e interessi dell'alleato." },
    { id:"goya", name:"Francisco Goya", years:"1746-1828", role:"pittore e testimone", image:"assets/img/protagonisti/goya.jpg", lesson:"liberatore-conquistatore", bio:"Pittore di corte spagnolo, attraversa occupazione, guerra e restaurazione. Nel 3 maggio 1808 e nei Disastri della guerra sottrae il conflitto al linguaggio della gloria e concentra lo sguardo sulle vittime.", idea:"Un'immagine può essere fonte non perché fotografi l'evento, ma perché rende visibile una scelta di memoria." },
    { id:"wellington", name:"Arthur Wellesley, Wellington", years:"1769-1852", role:"comandante britannico", image:"assets/img/protagonisti/wellington.jpg", lesson:"caduta-eredita", bio:"Guida le forze anglo-portoghesi nella penisola iberica e l'esercito alleato a Waterloo. La sua carriera ricorda che la sconfitta di Napoleone dipende da coalizioni, finanza e capacità logistica oltre che da singole battaglie.", idea:"La vittoria alleata è un risultato collettivo, non il semplice duello fra due comandanti." }
  ],
  timeline: [
    {year:"1769",title:"Nasce ad Ajaccio",text:"Una periferia appena diventata francese entra nella biografia del futuro imperatore.",lesson:"figlio-rivoluzione"},
    {year:"1789",title:"Inizia la Rivoluzione",text:"Cittadinanza, guerra e crisi dell'esercito aprono il mondo in cui Bonaparte farà carriera.",lesson:"figlio-rivoluzione"},
    {year:"1796-1797",title:"Campagna d'Italia",text:"Il generale diventa attore politico e maestro della propria immagine.",lesson:"figlio-rivoluzione"},
    {year:"1798-1801",title:"Spedizione d'Egitto",text:"Ambizione imperiale, ricerca scientifica e fallimento navale convivono.",lesson:"repubblica-uomo-forte"},
    {year:"1799",title:"18 brumaio",text:"La Repubblica concentra il potere per salvarsi dall'instabilità.",lesson:"repubblica-uomo-forte"},
    {year:"1801",title:"Concordato",text:"La pacificazione religiosa passa attraverso il controllo dello Stato.",lesson:"salvare-controllando"},
    {year:"1802",title:"Schiavitù ristabilita",text:"L'universalismo dei diritti trova un confine coloniale e razziale.",lesson:"salvare-controllando"},
    {year:"1804",title:"Codice e Impero",text:"Uguaglianza civile, gerarchia familiare e potere ereditario vengono codificati nello stesso anno.",lesson:"repubblica-incorona"},
    {year:"1805",title:"Austerlitz e Trafalgar",text:"L'egemonia terrestre francese cresce mentre il mare resta britannico.",lesson:"liberatore-conquistatore"},
    {year:"1806",title:"Blocco continentale",text:"La guerra economica lega commercio, polizia e nuove conquiste.",lesson:"governare-guerra"},
    {year:"1808",title:"Guerra di Spagna",text:"L'occupazione genera guerriglia e costituzionalismo antifrancese.",lesson:"liberatore-conquistatore"},
    {year:"1812",title:"Campagna di Russia",text:"Logistica, spazio e strategia spezzano la Grande Armée.",lesson:"governare-guerra"},
    {year:"1813",title:"Lipsia",text:"La guerra di coalizione apre la strada all'invasione della Francia.",lesson:"caduta-eredita"},
    {year:"1814-1815",title:"Abdicazione, ritorno, Waterloo",text:"L'Impero cade due volte; la leggenda sopravvive alla sconfitta.",lesson:"caduta-eredita"},
    {year:"1821",title:"Morte a Sant'Elena",text:"La fine dell'uomo alimenta la costruzione del mito.",lesson:"caduta-eredita"}
  ],
  sources: [
    { id:"proclama-italia", type:"Proclama militare", date:"26 aprile 1796", title:"Ai soldati dell'Armata d'Italia", provenance:"Proclama di Bonaparte dopo le prime vittorie; trascrizione della Fondation Napoléon.", excerpt:["Soldati, in quindici giorni avete riportato sei vittorie, preso ventuno bandiere, cinquantacinque pezzi di cannone, parecchie fortezze e conquistato la parte più ricca del Piemonte.","Senza nulla avete supplito a tutto. Avete vinto battaglie senza cannoni, attraversato fiumi senza ponti, compiuto marce forzate senza scarpe."], audience:"I soldati dell'Armata d'Italia.", purpose:"Trasformare difficoltà e vittorie in identità collettiva legata al comandante.", limits:"È un testo persuasivo: seleziona i risultati, tace requisizioni e costruisce l'immagine dell'esercito.", question:"Quali parole trasformano una serie di operazioni militari in un patto fra comandante e soldati?", url:"https://napoleon.org/wp-content/themes/napoleon/annexes/hors-serie/premiere-campagne-italie/fr/lesecrits/articles/articles01.html", lesson:"figlio-rivoluzione" },
    { id:"costituzione-viii", type:"Testo costituzionale", date:"13 dicembre 1799", title:"Costituzione dell'anno VIII", provenance:"Testo ufficiale conservato dal Conseil constitutionnel francese.", excerpt:["Il Governo è affidato a tre consoli nominati per dieci anni e indefinitamente rieleggibili.","Il Primo console promulga le leggi; nomina e revoca a volontà i membri del Consiglio di Stato, i ministri, gli ambasciatori e gli altri agenti esterni principali."], audience:"Cittadini francesi e istituzioni della Repubblica.", purpose:"Dare forma legale al regime nato dal 18 brumaio.", limits:"La distribuzione formale degli organi non dice da sola come il potere operasse né quanto fosse libero il plebiscito.", question:"Confronta il numero degli organi previsti con il potere attribuito al Primo console: dove si trova la decisione effettiva?", url:"https://www.conseil-constitutionnel.fr/les-constitutions-dans-l-histoire/constitution-du-22-frimaire-an-viii", lesson:"repubblica-uomo-forte" },
    { id:"codice-civile", type:"Codice giuridico", date:"21 marzo 1804", title:"Uguaglianza civile, disuguaglianza familiare", provenance:"Code civil des Français, edizione ufficiale del 1804 digitalizzata da Gallica.", excerpt:["I coniugi si devono reciprocamente fedeltà, soccorso, assistenza.","Il marito deve protezione alla moglie, la moglie obbedienza al marito.","La moglie, anche non comune nei beni o separata, non può donare, alienare, ipotecare, acquistare [...] senza il concorso del marito."], audience:"Magistrati, funzionari e cittadini soggetti al diritto civile.", purpose:"Unificare e rendere prevedibili i rapporti civili e patrimoniali.", limits:"Gli articoli mostrano la norma, non tutte le pratiche sociali; il concetto di cittadino resta implicitamente maschile.", question:"Quale idea di uguaglianza emerge dagli articoli 212, 213 e 217? Chi ne resta ai margini?", url:"https://gallica.bnf.fr/ark:/12148/bpt6k1061517/f22.image", lesson:"salvare-controllando" },
    { id:"schiavitu-1802", type:"Legge coloniale", date:"20 maggio 1802", title:"La legge sulla schiavitù nelle colonie", provenance:"Legge del 30 floreale anno X, trascritta dalla Fondation Napoléon.", excerpt:["Nelle colonie restituite alla Francia in esecuzione del trattato di Amiens [...] la schiavitù sarà mantenuta conformemente alle leggi e ai regolamenti anteriori al 1789.","La tratta dei neri e la loro importazione nelle dette colonie avranno luogo conformemente alle leggi e ai regolamenti esistenti prima del detto periodo del 1789."], audience:"Amministratori, proprietari e popolazioni delle colonie francesi.", purpose:"Ripristinare l'ordine coloniale e la produzione schiavista nei territori indicati.", limits:"Il linguaggio amministrativo nasconde la violenza vissuta; la legge va letta con le voci e la resistenza degli schiavizzati.", question:"Come trasforma la legge persone e violenza in formule amministrative?", url:"https://www.napoleon.org/histoire-des-2-empires/articles/document-loi-relative-a-la-traite-des-noirs-et-au-regime-des-colonies-20-mai-1802-30-floreal-an-x/", lesson:"salvare-controllando" },
    { id:"costituzione-xii", type:"Testo costituzionale", date:"18 maggio 1804", title:"La Repubblica affidata a un imperatore", provenance:"Senatoconsulto organico del 28 floreale anno XII, Fondation Napoléon.", excerpt:["Il Governo della Repubblica è affidato a un Imperatore, che prende il titolo di Imperatore dei Francesi.","Napoleone Bonaparte, attuale Primo console della Repubblica, è Imperatore dei Francesi."], audience:"Cittadini e istituzioni francesi.", purpose:"Creare una dignità imperiale ereditaria senza dichiarare estinta la Repubblica.", limits:"Il testo istituzionale mostra la formula di legittimazione, non la libertà del consenso né le ragioni sociali dell'adesione.", question:"Perché il legislatore conserva la parola “Repubblica” proprio mentre istituisce l'Impero?", url:"https://www.napoleon.org/histoire-des-2-empires/articles/senatus-consulte-organique-du-28-floreal-xii-18-mai-1804/", lesson:"repubblica-incorona" },
    { id:"incoronazione-david", type:"Fonte visiva ufficiale", date:"1805-1807", title:"David, L'incoronazione di Napoleone", provenance:"Jacques-Louis David, olio su tela commissionato da Napoleone, Musée du Louvre, Parigi.", image:"assets/img/fonti/incoronazione-david.jpg", imageAlt:"Jacques-Louis David, L'incoronazione di Napoleone: Giuseppina inginocchiata davanti a Napoleone nella cattedrale di Notre-Dame", excerpt:["Napoleone occupa il centro e solleva la corona sopra Giuseppina; Pio VII siede dietro di lui.","La madre di Napoleone appare nella tribuna, benché non avesse partecipato alla cerimonia."], audience:"Il pubblico del Salon e la corte imperiale; la memoria futura dell'evento.", purpose:"Rendere naturale e concorde un potere nuovo attraverso gerarchia, rito, luce e presenza religiosa.", limits:"È un'immagine commissionata e costruita dopo l'evento: modifica la disposizione e include persone assenti.", question:"Quale potere vuole rendere naturale? Confronta ciò che il quadro mostra con ciò che sappiamo della cerimonia.", url:"https://collections.louvre.fr/en/ark:/53355/cl010065720", lesson:"repubblica-incorona" },
    { id:"goya-tre-maggio", type:"Fonte visiva critica", date:"1814", title:"Goya, Il 3 maggio 1808", provenance:"Francisco Goya, olio su tela, Museo del Prado, Madrid.", image:"assets/img/fonti/goya-tre-maggio.jpg", imageAlt:"Francisco Goya, Il 3 maggio 1808: un plotone francese fucila insorti spagnoli", excerpt:["A sinistra le vittime hanno volti e gesti differenti; a destra i soldati francesi formano una massa anonima di schiene e fucili.","La lanterna illumina l'uomo in bianco, non un eroe vittorioso ma una vittima sul punto di essere colpita."], audience:"Pubblico spagnolo dopo la fine dell'occupazione francese.", purpose:"Costruire memoria della repressione del 1808 concentrando lo sguardo sulla vittima.", limits:"Dipinto sei anni dopo l'evento: è elaborazione memoriale e politica, non riproduzione fotografica.", question:"Come composizione, luce e anonimato dei soldati rovesciano l'immagine tradizionale della gloria militare?", url:"https://www.museodelprado.es/en/the-collection/art-work/the-3rd-of-may-1808-in-madrid-or-the-executions/5e177409-2993-4240-97fb-847a02c6496c", lesson:"liberatore-conquistatore" }
  ],
  quiz: [
    {q:"Quale condizione rivoluzionaria favorì maggiormente la rapida carriera di Bonaparte?",options:["L'apertura dei comandi e la guerra di massa","Il ritorno dei privilegi nobiliari","La fine dell'artiglieria","La pace permanente"],answer:0,why:"La crisi del vecchio corpo ufficiali e la mobilitazione moltiplicarono le opportunità di comando.",lesson:"figlio-rivoluzione"},
    {q:"Perché le repubbliche sorelle non possono essere definite soltanto 'liberate'?",options:["Non abolirono mai privilegi","Dipendevano militarmente e fiscalmente dalla Francia","Erano tutte monarchie","Non avevano costituzioni"],answer:1,why:"Riforme e subordinazione convivevano nello stesso sistema.",lesson:"figlio-rivoluzione"},
    {q:"Qual è la principale trasformazione della Costituzione dell'anno VIII?",options:["Abolisce l'esecutivo","Concentra la decisione nel Primo console","Introduce il suffragio femminile","Restaura i Borbone"],answer:1,why:"Molti organi sopravvivono, ma nomina e iniziativa politica sono dominate dal Primo console.",lesson:"repubblica-uomo-forte"},
    {q:"Che cosa rende plebiscitaria la legittimità napoleonica?",options:["Il potere del papa","La ratifica popolare diretta del capo","L'elezione competitiva fra partiti","La successione feudale"],answer:1,why:"Il voto ratifica il capo e le trasformazioni costituzionali senza autentico pluralismo.",lesson:"repubblica-uomo-forte"},
    {q:"Quale doppio carattere presenta il sistema dei prefetti?",options:["Decentramento e autonomia","Uniformità amministrativa e controllo centrale","Privilegio e federalismo","Elezione e indipendenza"],answer:1,why:"Il prefetto rende efficace lo Stato proprio perché dipende dal centro.",lesson:"salvare-controllando"},
    {q:"Quale contraddizione rivela il Codice civile?",options:["Abolisce la proprietà","Unisce uguaglianza civile maschile e gerarchia familiare","Rifiuta ogni regola comune","Concede il voto universale"],answer:1,why:"La parità davanti alla legge non si estende ai rapporti di genere e familiari.",lesson:"salvare-controllando"},
    {q:"Perché il 1802 è decisivo nella storia coloniale francese?",options:["Abolisce definitivamente la tratta","Riapre il sistema schiavista napoleonico","Concede il voto ad Haiti","Rinuncia a ogni colonia"],answer:1,why:"La legge mantiene o prepara il ristabilimento della schiavitù e della tratta.",lesson:"salvare-controllando"},
    {q:"Che cosa comunica l'auto-incoronazione?",options:["Dipendenza assoluta dal papa","Autonomia dell'autorità imperiale pur dentro una cerimonia sacra","Rifiuto di ogni simbolo monarchico","Fine della successione"],answer:1,why:"Il rito cerca consacrazione ma mostra che la corona non è semplicemente concessa dalla Chiesa.",lesson:"repubblica-incorona"},
    {q:"Perché l'Europa napoleonica è definita 'a geometria variabile'?",options:["Non aveva confini","Riforme e dipendenza differivano fra territori","Ogni Stato era indipendente","Il Codice era identico ovunque"],answer:1,why:"Annessioni, Stati clienti e alleati ricevettero istituzioni diverse e subirono oneri differenti.",lesson:"liberatore-conquistatore"},
    {q:"Che cosa dimostra la Costituzione di Cadice del 1812?",options:["Ogni resistenza era assolutista","Antinapoleonismo e liberalismo potevano convivere","La Spagna accettò Giuseppe Bonaparte","La guerriglia scomparve"],answer:1,why:"La lotta contro l'occupazione produsse anche un progetto costituzionale liberale.",lesson:"liberatore-conquistatore"},
    {q:"Perché il blocco continentale allarga la guerra?",options:["Rende inutili i controlli","Per applicarlo occorrono pressioni, annessioni e campagne","Elimina la potenza britannica nel 1806","Libera tutti i porti"],answer:1,why:"L'embargo richiede controllo politico dei litorali e crea conflitti con alleati e popolazioni.",lesson:"governare-guerra"},
    {q:"Quale spiegazione della catastrofe del 1812 è più completa?",options:["Solo il freddo","Solo una battaglia persa","Logistica, strategia, distanze, malattie, combattimenti e clima","Un tradimento di Parigi"],answer:2,why:"L'inverno aggrava una crisi iniziata prima, legata all'obiettivo politico e ai rifornimenti.",lesson:"governare-guerra"},
    {q:"Che cosa significa 'restaurare senza cancellare'?",options:["Tornare esattamente al 1788","Conservare istituzioni napoleoniche utili dentro monarchie restaurate","Mantenere Napoleone al trono","Abolire il Codice civile ovunque"],answer:1,why:"I vincitori selezionano: restaurano dinastie ma mantengono molti strumenti statali e assetti sociali.",lesson:"caduta-eredita"},
    {q:"Qual è la tesi più storicamente fondata?",options:["Napoleone fu soltanto liberatore","Napoleone fu soltanto traditore","Trasformò alcune conquiste rivoluzionarie subordinandole ad autorità e guerra","La Rivoluzione non influì sul suo regime"],answer:2,why:"La risposta tiene insieme continuità, rotture e differenti esperienze sociali.",lesson:"caduta-eredita"}
  ]
};

{
  const metadata = {
    "proclama-italia":["Napoleone Bonaparte, comandante dell’Armata d’Italia","Prime vittorie della campagna del 1796 e necessità di consolidare il rapporto con soldati stanchi e male equipaggiati."],
    "costituzione-viii":["Commissione consolare e Repubblica francese","Dopo il 18 brumaio occorre dare forma legale al nuovo equilibrio dominato da Bonaparte."],
    "codice-civile":["Governo, Consiglio di Stato e legislatore francesi","La codificazione conclude anni di confronto fra diritto rivoluzionario, consuetudini e ordine familiare."],
    "schiavitu-1802":["Corpo legislativo francese su progetto del governo consolare","La pace di Amiens restituisce colonie alla Francia mentre Saint-Domingue resiste al controllo metropolitano."],
    "costituzione-xii":["Senato conservatore della Repubblica francese","Complotti, consolato a vita e questione della successione preparano l’ereditarietà imperiale."],
    "incoronazione-david":["Jacques-Louis David, pittore incaricato da Napoleone","La tela viene elaborata dopo la cerimonia del 2 dicembre 1804 ed esposta pubblicamente nel 1808."],
    "goya-tre-maggio":["Francisco Goya","Nel 1814, finita l’occupazione francese, il pittore rielabora la repressione madrilena del 1808."]
  };
  window.NAP_DATA.sources.forEach(source => [source.author, source.context] = metadata[source.id]);
}
