const root = "https://gbprof.it/IV-anno/Letteratura/Foscolo/lezioni/";
const node = (
  id,
  title,
  kind,
  x,
  z,
  text,
  question,
  choices,
  correct,
  why,
  quote = "",
) => ({ id, title, kind, x, z, text, question, choices, correct, why, quote });
export const poem = `Forse perché della fatal quïete
tu sei l’imago, a me sì cara vieni,
o sera! E quando ti corteggian liete
le nubi estive e i zeffiri sereni,

E quando dal nevoso aere inquïete
tenebre e lunghe all’universo meni,
sempre scendi invocata, e le secrete
vie del mio cor soavemente tieni.

Vagar mi fai co’ miei pensier su l’orme
che vanno al nulla eterno; e intanto fugge
questo reo tempo, e van con lui le torme

delle cure onde meco egli si strugge:
e mentre io guardo la tua pace, dorme
quello spirto guerrier ch’entro mi rugge.`;
export const levels = [
  {
    id: "mondo",
    title: "Il mondo precedente",
    tag: "L’ORDINE E LA PROMESSA",
    place: "Il giardino delle origini",
    line: "Prima della frattura, un mondo che sembrava immutabile.",
    mission: "Apri le tre porte della storia",
    hint: "Raggiungi i sigilli luminosi tra le colonne.",
    theme: "gold",
    source: root + "introduzione.html",
    intro:
      "Sei un viandante tra le idee di Foscolo. Nel giardino dell’ordine antico, tre sigilli custodiscono il mondo da cui nasce la sua inquietudine. Esplorali, interpreta ciò che trovi e apri la soglia.",
    gate: "Quale passaggio hai attraversato?",
    options: [
      "Da un ordine fondato sui privilegi alla promessa di libertà e cittadinanza.",
      "Da una società di cittadini uguali alla nascita dei privilegi.",
      "Da una scienza certa dell’aldilà a una religione meccanica.",
    ],
    answer: 0,
    summary:
      "Foscolo nasce nel 1778, nel mondo dell’Antico Regime, e cresce tra Rivoluzione e Napoleone. La promessa di libertà entra in conflitto con la realtà del potere.",
    nodes: [
      node(
        "ordine",
        "Il sigillo della nascita",
        "crown",
        -10,
        7,
        "Nell’Antico Regime, l’appartenenza a un ceto stabilisce diritti e privilegi. Trono, nobiltà e autorità tradizionale sorreggono l’ordine sociale. Per molti, il destino sembra già scritto alla nascita.",
        "Quale iscrizione appartiene a questa porta?",
        [
          "Uguali diritti politici per tutti.",
          "Il privilegio ricevuto per nascita.",
          "La libertà come conquista dei cittadini.",
        ],
        1,
        "Il privilegio di ceto distingue l’ordine dell’Antico Regime dalla cittadinanza moderna.",
      ),
      node(
        "rivoluzione",
        "La fiaccola del 1789",
        "flame",
        9,
        0,
        "La Rivoluzione francese porta in primo piano diritti, libertà e uguaglianza. La persona può pensarsi come cittadino. Il giovane Foscolo riconosce in questa promessa una possibilità di riscatto.",
        "Accendi la fiaccola con l’idea nuova.",
        [
          "Obbedire al proprio ceto.",
          "Affidare la patria al conquistatore.",
          "Essere cittadini portatori di diritti.",
        ],
        2,
        "La Rivoluzione apre una speranza: la libertà politica può essere costruita dagli uomini.",
      ),
      node(
        "ragione",
        "La lente della ragione",
        "sphere",
        -7,
        -12,
        "La cultura illuministica cerca spiegazioni razionali e leggi naturali. Nel suo versante materialistico, l’universo non ha bisogno di un fine provvidenziale per funzionare. Foscolo eredita anche questa visione.",
        "Dove orienti la lente?",
        [
          "Verso cause fisiche e leggi della natura.",
          "Verso privilegi che non si possono discutere.",
          "Verso prove scientifiche dell’immortalità.",
        ],
        0,
        "La ragione indaga la natura. Questa eredità liberatoria avrà anche conseguenze dolorose per Foscolo.",
      ),
    ],
  },
  {
    id: "fratture",
    title: "Le fratture",
    tag: "QUATTRO FERITE",
    place: "L’arcipelago dell’esilio",
    line: "La storia entra nella vita. La vita diventa poesia.",
    mission: "Ricongiungi quattro memorie",
    hint: "Ogni frammento illumina un tratto del cammino.",
    theme: "storm",
    source: root + "fratture.html",
    intro:
      "Il giardino è diventato un arcipelago di rovine. Quattro fratture segnano la vita di Foscolo. Raccogli i loro significati: il ponte si ricompone quando un evento diventa una forma letteraria.",
    gate: "Che cosa tiene insieme le quattro fratture?",
    options: [
      "Sono episodi che Foscolo separa sempre dalla scrittura.",
      "Trasformano perdite personali e storiche in temi e simboli poetici.",
      "Portano Foscolo a ritrovare definitivamente la patria.",
    ],
    answer: 1,
    summary:
      "Zante diventa l’origine perduta; Campoformio la libertà tradita; Giovanni il legame tra famiglia e tomba; l’esilio una condizione esistenziale.",
    nodes: [
      node(
        "zante",
        "Zante · l’origine",
        "shell",
        -11,
        7,
        "Foscolo nasce a Zante, isola greca allora veneziana. L’origine unisce infanzia, mare e mito. Il ritorno che Ulisse compie a Itaca resta negato al poeta: alla terra materna potrà arrivare il suo canto.",
        "Quale legame ricostruisce questo frammento?",
        [
          "Zante → il ritorno compiuto.",
          "Zante → il potere di Napoleone.",
          "Zante → patria perduta e ritorno poetico.",
        ],
        2,
        "In A Zacinto, la parola conserva un’appartenenza che la vita non può più restituire.",
      ),
      node(
        "campoformio",
        "1797 · Campoformio",
        "banner",
        10,
        3,
        "Con Campoformio, Napoleone cede Venezia all’Austria. La delusione nasce dalla distanza fra liberazione promessa e calcolo politico. Il giudizio di Foscolo su Napoleone conserva questa tensione.",
        "Quale ferita riconosci?",
        [
          "La patria sacrificata agli interessi del potere.",
          "La vittoria definitiva della libertà veneziana.",
          "Il ritorno di Foscolo nella Grecia libera.",
        ],
        0,
        "Foscolo condanna il tradimento della libertà: non basta ridurre il rapporto con Napoleone a semplice ammirazione o odio.",
      ),
      node(
        "giovanni",
        "1801 · Giovanni",
        "tomb",
        -9,
        -10,
        "La morte del fratello Giovanni intreccia dolore familiare, lontananza e desiderio di consolare la madre. Il poeta immagina il raccoglimento presso la tomba, proprio mentre l’esilio lo tiene lontano.",
        "Quale valore può avere la tomba?",
        [
          "Garantire scientificamente una vita oltre la morte.",
          "Raccogliere gli affetti e il ricordo dei vivi.",
          "Cancellare ciò che è accaduto.",
        ],
        1,
        "La pietra diventa un luogo di relazione, senza negare la morte.",
      ),
      node(
        "esilio",
        "1815 · senza ritorno",
        "boat",
        11,
        -16,
        "Dopo il ritorno del dominio austriaco, Foscolo lascia l’Italia nel 1815. Passa dalla Svizzera all’Inghilterra e muore nel 1827. L’esilio è anche una frattura dell’identità e dell’appartenenza.",
        "Che cosa porti oltre la distanza?",
        [
          "La certezza di un ritorno ormai vicino.",
          "L’indifferenza per ogni legame.",
          "Una patria e un’identità da custodire nella memoria.",
        ],
        2,
        "La lontananza geografica diventa esperienza interiore, non soltanto una voce della biografia.",
      ),
    ],
  },
  {
    id: "immagine",
    title: "L’immagine del mondo",
    tag: "MATERIA E LEGAMI",
    place: "La macchina e il cielo",
    line: "Tutto passa. Che cosa può ancora avere valore?",
    mission: "Comprendi la macchina del mondo",
    hint: "Osserva gli ingranaggi e accendi il legame umano.",
    theme: "machine",
    source: root + "immagine-del-mondo.html",
    intro:
      "Un meccanismo continua a girare tra le rovine. Non conosce i desideri degli uomini. Attraversa materia, nulla e illusioni: la macchina continuerà a muoversi anche quando avrai acceso le luci umane.",
    gate: "Le illusioni cambiano le leggi della materia?",
    options: [
      "Sì: rendono fisicamente immortale l’individuo.",
      "No: perciò non hanno alcun valore.",
      "No: costruiscono senso, affetti e dignità dentro una vita finita.",
    ],
    answer: 2,
    summary:
      "Materialismo e meccanicismo descrivono il mondo. La religione laica delle illusioni risponde al bisogno umano di senso, senza offrire una prova dell’aldilà.",
    nodes: [
      node(
        "materia",
        "La materia in movimento",
        "gear",
        -10,
        7,
        "La macchina non si ferma quando una ruota viene sostituita. È una metafora del meccanicismo: i fenomeni seguono cause fisiche, non intenzioni morali orientate alla felicità umana.",
        "Come interpreti questo moto?",
        [
          "La natura ricompensa sempre chi è buono.",
          "La natura segue leggi indipendenti dai desideri umani.",
          "La materia si muove soltanto per volontà del poeta.",
        ],
        1,
        "L’universo non è costruito per premiare o punire l’uomo. Gli ingranaggi sono un’immagine didattica di questa visione.",
      ),
      node(
        "nulla",
        "Il nulla eterno",
        "sphere",
        10,
        -2,
        "Nella visione materialistica di Foscolo, la morte conclude l’esistenza individuale. Non è il passaggio certo a un aldilà. Questa lucidità apre una domanda: come vivere, se nulla garantisce dall’alto il valore della vita?",
        "Quale parola assegni al vuoto?",
        [
          "Fine dell’individuo.",
          "Immortalità dell’anima dimostrata.",
          "Giudizio divino.",
        ],
        0,
        "Il nulla eterno riguarda la fine dell’individuo; non significa che la materia smetta di trasformarsi.",
      ),
      node(
        "illusioni",
        "Il fuoco dei legami",
        "flame",
        -7,
        -13,
        "Amore, patria, memoria, gloria, bellezza e poesia non eliminano la morte. Sono valori creati e riconosciuti dagli uomini: consentono di amare, ricordare, agire e trasmettere.",
        "Quale fuoco accendi senza spegnere la ragione?",
        [
          "Una certezza scientifica dell’eternità.",
          "La rinuncia a ogni valore.",
          "Un valore umano consapevole della propria fragilità.",
        ],
        2,
        "Le illusioni sono necessarie alla vita umana. La loro forza non dipende da una dimostrazione scientifica.",
      ),
    ],
  },
  {
    id: "poetica",
    title: "La poetica",
    tag: "DARE FORMA ALL’INQUIETUDINE",
    place: "Il giardino delle due voci",
    line: "La misura classica incontra una ferita moderna.",
    mission: "Accorda le due voci della poesia",
    hint: "Ricostruisci la lira tra armonia e inquietudine.",
    theme: "garden",
    source: root + "poetica.html",
    intro:
      "In questo giardino convivono marmo ordinato e alberi piegati dal vento. Una lira spezzata aspetta tre corde. Ritrova il valore della forma, la voce dell’io e il rapporto che le unisce.",
    gate: "Come si incontrano le due anime di Foscolo?",
    options: [
      "La forma classica dà ordine a un’inquietudine moderna.",
      "La classicità rende impossibile ogni sentimento.",
      "Il sentimento impone di rinunciare alla forma.",
    ],
    answer: 0,
    summary:
      "Mito, misura e bellezza appartengono alla ricerca neoclassica. Esilio, notte e conflitto dell’io avvicinano Foscolo alla sensibilità preromantica. Le due spinte convivono.",
    nodes: [
      node(
        "misura",
        "La corda della misura",
        "lyre",
        -11,
        6,
        "Il modello greco-romano offre misura, armonia e bellezza ideale. Nel disordine della vita, la forma artistica diventa un lavoro di costruzione: non è soltanto un rivestimento elegante.",
        "Quale elemento accorda questa corda?",
        [
          "Il rifiuto di ogni equilibrio.",
          "La disciplina della forma e il mito classico.",
          "La pura cronaca senza trasformazione.",
        ],
        1,
        "La forma cerca un ordine che la realtà non garantisce.",
      ),
      node(
        "inquietudine",
        "La corda dell’io",
        "flame",
        10,
        -1,
        "Esilio, notte, morte, nostalgia e passione portano al centro un soggetto inquieto. La natura può diventare uno specchio interiore. È la sensibilità preromantica che attraversa Foscolo.",
        "Quale voce ascolti qui?",
        [
          "La completa indifferenza dell’io.",
          "Un trattato sulle leggi della botanica.",
          "L’esperienza del dolore e del conflitto interiore.",
        ],
        2,
        "Il paesaggio diventa anche esperienza dell’anima, non semplice sfondo.",
      ),
      node(
        "forma",
        "Una forma per la ferita",
        "book",
        -6,
        -13,
        "Il sonetto contiene il pensiero in quattordici versi. La misura non impedisce al dolore di parlare: lo trasforma in una voce capace di essere condivisa e ricordata.",
        "Come riunisci le due corde?",
        [
          "Forma e inquietudine possono sostenersi a vicenda.",
          "L’armonia dimostra che Foscolo non soffre.",
          "Il dolore rende inutile ogni ricerca stilistica.",
        ],
        0,
        "La forza della poetica foscoliana è nella tensione fra ordine cercato e ferita persistente.",
      ),
    ],
  },
  {
    id: "ortis",
    title: "Ultime lettere di Jacopo Ortis",
    tag: "LE OPERE · I",
    place: "Le lettere tra le rovine",
    line: "Patria e amore: due promesse infrante.",
    mission: "Ritrova le tre lettere di Jacopo",
    hint: "Segui le pagine fino alla voce di Parini.",
    theme: "ortis",
    source: root + "ortis-parini.html",
    intro:
      "Sui colli Euganei, alcune lettere sono rimaste tra le rovine. Ricostruisci il conflitto di Jacopo. Il tuo compito è comprenderne il tragico esito e il rapporto con la storia.",
    gate: "Che cosa rivela il destino di Jacopo?",
    options: [
      "Che amore e patria sono ormai realizzati.",
      "Il crollo di patria e amore e l’impossibilità, per lui, di trovare una via d’uscita.",
      "Che la violenza garantisce la libertà.",
    ],
    answer: 1,
    summary:
      "Il romanzo epistolare intreccia delusione politica e amore impossibile. Le lettere a Lorenzo danno voce all’io lacerato; Parini interroga criticamente l’impulso eroico. Il suicidio di Jacopo è l’esito tragico narrato, non una vittoria da imitare.",
    nodes: [
      node(
        "lettere",
        "La voce a Lorenzo",
        "book",
        -10,
        7,
        "La vicenda arriva attraverso le lettere di Jacopo all’amico Lorenzo. Questa forma dà al lettore accesso immediato a pensieri, slanci e contraddizioni del protagonista.",
        "A chi affidi queste pagine?",
        [
          "A Napoleone, per una richiesta diplomatica.",
          "A Odoardo, narratore di tutta l’opera.",
          "A Lorenzo, destinatario delle lettere di Jacopo.",
        ],
        2,
        "L’Ortis è un romanzo epistolare: la scrittura delle lettere rende percepibile la voce dell’io.",
      ),
      node(
        "teresa",
        "Patria e Teresa",
        "rose",
        10,
        -1,
        "Campoformio infrange la speranza politica. Teresa, promessa a Odoardo, incarna un amore che Jacopo non può realizzare. Le due delusioni si rispecchiano e rendono più profonda la sua crisi.",
        "Quali frammenti accosti?",
        [
          "La patria tradita e l’amore impossibile.",
          "La conquista della patria e il matrimonio felice.",
          "Due vicende prive di ogni relazione.",
        ],
        0,
        "Storia e passione privata convergono: l’ideale urta contro un mondo che lo nega.",
      ),
      node(
        "parini",
        "Sotto gli alberi di Parini",
        "scroll",
        -7,
        -13,
        "Jacopo vorrebbe agire eroicamente. Nel colloquio milanese, Parini gli mostra i rischi dell’azione cieca: la passione può diventare strumento di una fazione o vittima del potere.",
        "Quale consiglio conservi?",
        [
          "Confondere il sacrificio con una garanzia di successo.",
          "Interrogare i mezzi dell’azione e non attendere libertà da un dominatore.",
          "Affidare ogni scelta al più forte.",
        ],
        1,
        "Parini non offre una soluzione facile: introduce una coscienza critica dentro l’entusiasmo di Jacopo.",
      ),
    ],
  },
  {
    id: "grazie",
    title: "Le Grazie",
    tag: "LE OPERE · II",
    place: "Il santuario dell’armonia",
    line: "La bellezza educa i gesti degli uomini.",
    mission: "Ricomponi il cerchio delle arti",
    hint: "Ridona luce a tre doni del santuario.",
    theme: "graces",
    source: root + "opere.html",
    intro:
      "Il santuario è incompleto. Musica, danza e parola possono restituirgli un’armonia, senza cancellare la violenza che esiste fuori di esso. Cerca nelle tre arti la funzione civilizzatrice della bellezza.",
    gate: "Quale mondo cercano Le Grazie?",
    options: [
      "Un mondo in cui la bellezza ingentilisce gli uomini e costruisce civiltà.",
      "Una fuga decorativa che rende inutili i rapporti umani.",
      "Una dimostrazione che la storia è già priva di violenza.",
    ],
    answer: 0,
    summary:
      "Le Grazie è un carme mitologico incompiuto. La bellezza e le arti hanno una funzione morale e civilizzatrice: mito e armonia rispondono alla brutalità della storia.",
    nodes: [
      node(
        "musica",
        "Il dono della musica",
        "lyre",
        -10,
        7,
        "L’armonia organizza suoni differenti in una relazione. Nel mondo simbolico delle Grazie, le arti educano la sensibilità: una comunità può apprendere gesti più misurati.",
        "Come accordi la lira?",
        [
          "Facendo tacere ogni voce diversa.",
          "Mettendo in relazione le voci attraverso misura e ascolto.",
          "Trasformando la musica in un ordine militare.",
        ],
        1,
        "Nel gioco, accordare la lira rende visibile l’idea dell’arte che ingentilisce. È una metafora dell’interpretazione dell’opera.",
      ),
      node(
        "danza",
        "Il dono della grazia",
        "statue",
        10,
        -2,
        "La grazia rende il gesto sensibile e misurato. Il mito non è qui un ornamento archeologico: offre un’immagine dell’umanità capace di uscire dalla brutalità.",
        "Quale gesto resta nel cerchio?",
        [
          "La sopraffazione come ideale.",
          "L’indifferenza per gli altri.",
          "Un movimento condiviso, armonico e rispettoso.",
        ],
        2,
        "La bellezza foscoliana coinvolge anche il modo di vivere insieme.",
      ),
      node(
        "incompiuto",
        "Il marmo incompiuto",
        "scroll",
        -7,
        -13,
        "Foscolo lavora al carme in più momenti, senza dargli una forma definitiva compiuta. Il richiamo alla Grecia, al mito e a Canova esprime la ricerca di un ideale artistico.",
        "Come descrivi questo monumento?",
        [
          "Un progetto poetico incompiuto di bellezza civilizzatrice.",
          "Un romanzo epistolare scritto da Lorenzo.",
          "Un manuale politico interamente concluso.",
        ],
        0,
        "L’incompiutezza appartiene alla storia delle Grazie. Il cerchio ricostruito nel gioco non cambia questo dato.",
      ),
    ],
  },
  {
    id: "sepolcri",
    title: "Dei sepolcri",
    tag: "LE OPERE · III",
    place: "Il viale della memoria",
    line: "La pietra si consuma. La voce può continuare.",
    mission: "Porta la memoria oltre la pietra",
    hint: "Dagli affetti agli esempi civili, fino alla poesia.",
    theme: "memory",
    source: root + "opere.html",
    intro:
      "Un viale di cipressi attraversa un luogo di memoria. Accendi tre fuochi: affetti, virtù civile, poesia. Vedrai le pietre consumarsi, mentre le parole continuano a trasmettere un’eredità.",
    gate: "Quando anche la pietra scompare, che cosa può custodire la memoria?",
    options: [
      "L’immortalità fisica concessa dalla sepoltura.",
      "Il silenzio assoluto dei vivi.",
      "La poesia, che trasmette affetti, esempi e nomi.",
    ],
    answer: 2,
    summary:
      "Pubblicato nel 1807, il carme parte dal tema delle sepolture e ne sviluppa il valore affettivo e civile. La poesia può conservare la memoria oltre la durata del monumento materiale.",
    nodes: [
      node(
        "affetti",
        "L’eredità d’affetti",
        "tomb",
        -10,
        7,
        "Se il morto non sente più nulla, una tomba non gli restituisce la vita. Il sepolcro ha però un valore per chi resta: custodisce un legame e rende possibile il ricordo condiviso.",
        "A chi consegni questa fiamma?",
        [
          "Ai vivi che ricordano e continuano ad amare.",
          "Alla pietra, perché renda immortale il corpo.",
          "Al tempo, perché cancelli ogni affetto.",
        ],
        0,
        "La memoria è una relazione tra esseri umani, non una smentita del materialismo.",
      ),
      node(
        "virtu",
        "Le urne dei forti",
        "flame",
        10,
        -2,
        "Le tombe dei grandi possono suscitare il desiderio di azioni degne. La memoria supera la dimensione privata e diventa educazione civile: un esempio passa da una generazione all’altra.",
        "Quale luce trasmetti ai posteri?",
        [
          "Il culto della forza fine a se stessa.",
          "Il ricordo come stimolo alla virtù e alla responsabilità.",
          "La certezza che il passato fosse senza conflitti.",
        ],
        1,
        "Nei Sepolcri, l’esempio dei grandi accende i vivi a grandi azioni.",
      ),
      node(
        "poesia",
        "La voce oltre il marmo",
        "book",
        -7,
        -13,
        "Anche il monumento è materia e si deteriora. La poesia può attraversare il tempo nella voce di chi legge: conserva una memoria quando il suo supporto di pietra non esiste più.",
        "Che cosa porti oltre le rovine?",
        [
          "La promessa che nessuna pietra cadrà.",
          "La rinuncia a ricordare.",
          "Una parola da leggere e trasmettere.",
        ],
        2,
        "La durata poetica è simbolica e umana: nasce dalla trasmissione della memoria.",
      ),
    ],
  },
  {
    id: "sera",
    title: "Alla sera",
    tag: "LE OPERE · IV · FINALE",
    place: "La scogliera della quiete",
    line: "La sera scende. Lo spirito guerriero riposa.",
    mission: "Segui il sonetto verso la quiete",
    hint: "Ritrova le tre immagini, nell’ordine del cammino.",
    theme: "evening",
    source: root + "alla-sera.html",
    intro:
      "Il viaggio si conclude su una scogliera. Segui tre immagini del sonetto, una dopo l’altra. A ogni passaggio il cielo cambia: la poesia offre una pausa al conflitto, senza cancellarlo.",
    gate: "Quale quiete raggiunge il poeta?",
    options: [
      "Una serenità definitiva che elimina tutte le contraddizioni.",
      "Una pace momentanea: la bellezza placa l’inquietudine senza negare il nulla.",
      "La certezza religiosa di un aldilà.",
    ],
    answer: 1,
    summary:
      "In Alla sera, sonetto del 1803, la sera è figura della fatal quiete. Il pensiero del nulla eterno e del reo tempo trova una forma armonica; lo spirito guerriero si placa per un momento. Qui si incontrano visione del mondo e poetica.",
    nodes: [
      node(
        "quiete",
        "I · La fatal quiete",
        "sphere",
        -10,
        7,
        "La sera è cara perché assomiglia alla quiete della morte. Arriva invocata sia nell’estate serena sia nelle tenebre invernali: il suo valore non dipende soltanto dal bel tempo.",
        "A quale immagine accosti la sera?",
        [
          "Alla vittoria militare.",
          "A una sola stagione dell’anno.",
          "Alla morte come quiete inevitabile.",
        ],
        2,
        "La sera è una presenza simbolica. Il paesaggio entra nel cuore e nel pensiero del poeta.",
        "Forse perché della fatal quïete\ntu sei l’imago, a me sì cara vieni,",
      ),
      node(
        "tempo",
        "II · Il reo tempo",
        "gear",
        10,
        -2,
        "Il pensiero vaga verso il nulla eterno. Intanto il tempo fugge e trascina con sé le cure, cioè gli affanni. “Reo” indica il tempo carico di tormento che consuma la vita.",
        "Che cosa lasciano andare queste parole?",
        [
          "Gli affanni che accompagnano il tempo della vita.",
          "Le leggi fisiche della natura.",
          "La consapevolezza della morte, ormai negata.",
        ],
        0,
        "La meditazione sospende la pressione degli affanni; non confuta la visione materialistica.",
        "Vagar mi fai co’ miei pensier su l’orme\nche vanno al nulla eterno;",
      ),
      node(
        "spirito",
        "III · Lo spirto guerrier",
        "lyre",
        -7,
        -13,
        "Davanti alla pace della sera, l’energia inquieta e combattiva del poeta si addormenta. Il conflitto rimane possibile: è una tregua, resa vivibile dalla forma poetica.",
        "Quale verbo conclude il tuo cammino?",
        [
          "Scompare per sempre.",
          "Dorme: si placa per un momento.",
          "Vince ogni conflitto.",
        ],
        1,
        "“Dorme” lascia aperta la possibilità del risveglio. La quiete è una conquista momentanea della poesia.",
        "e mentre io guardo la tua pace, dorme\nquello spirto guerrier ch’entro mi rugge.",
      ),
    ],
  },
];
