window.HIST_DATA = {
  meta: {
    title: "Crispi e la crisi di fine secolo. Riforme, autoritarismo e società di massa",
    shortTitle: "Crispi e fine secolo",
    storageKey: "storia-crispi-fine-secolo-v1",
    question: "Come può uno Stato modernizzarsi e, nello stesso tempo, restringere gli spazi della partecipazione politica e del conflitto sociale?",
    thesis: "Fra il 1887 e il 1901 lo Stato liberale italiano ampliò e razionalizzò amministrazione, sanità, giustizia, assistenza e sistema bancario, ma affrontò la crescita dei conflitti sociali e delle organizzazioni popolari con strumenti spesso eccezionali. Crispi rappresenta con particolare evidenza questa tensione: riformatore nella costruzione dello Stato, centralizzatore nell'esercizio del potere, aggressivo nella politica coloniale. La crisi del 1898-1900 mostrò i limiti di una risposta fondata soprattutto sull'ordine pubblico; dal 1901 Zanardelli e Giolitti tentarono una diversa integrazione del conflitto sociale nello Stato liberale.",
    workshopIntro: "Evita due scorciatoie: Crispi non fu soltanto un repressore, ma neppure la modernizzazione amministrativa rende secondarie le restrizioni delle libertà. Costruisci un giudizio storico tenendo insieme riforme, gruppi sociali, istituzioni, economia, colonialismo e alternative politiche.",
    previous: { title: "Sinistra storica", url: "../Sinistra-storica/" },
    next: { title: "L'età giolittiana - tappa futura", url: "#" }
  },
  lessons: [
    {
      id: "crispi-uomo-stato", number: 1, title: "Dal rivoluzionario all'uomo di Stato", eyebrow: "Una biografia dentro la costruzione nazionale", period: "1818-1887",
      question: "Come si passa dal mazzinianesimo alla convinzione che l'unità nazionale debba essere difesa da uno Stato forte?",
      lead: "Crispi arrivò alla presidenza del Consiglio nel 1887 con un passato democratico e garibaldino. La sua traiettoria mostra una trasformazione decisiva della politica postunitaria: dalla rivoluzione nazionale alla costruzione e difesa delle istituzioni monarchiche.",
      sections: [
        { title: "Il mondo precedente: rivoluzione e Risorgimento", paragraphs: ["Francesco Crispi nacque a Ribera nel 1818 in una famiglia arbëreshë. Partecipò alla rivoluzione siciliana del 1848, fu vicino a Mazzini e svolse un ruolo centrale nell'organizzazione della spedizione dei Mille. In questa fase la politica coincideva ancora, per lui, con la liberazione nazionale e la rottura rivoluzionaria.", "L'esperienza del 1860 lo convinse però che la conquista dell'unità richiedeva anche disciplina, amministrazione e capacità di governo. La rivoluzione non era più sufficiente: occorreva uno Stato capace di durare."], summary: "Crispi nacque politicamente nel campo democratico, ma maturò dentro l'esperienza concreta dell'unificazione." },
        { title: "La frattura: monarchia o repubblica", paragraphs: ["Dopo l'Unità Crispi abbandonò progressivamente l'intransigenza repubblicana. Nel 1864 dichiarò in Parlamento che la monarchia univa ciò che una nuova lotta istituzionale avrebbe potuto dividere. La scelta non cancellava il passato democratico, ma lo reinterpretava alla luce della priorità assegnata all'unità nazionale.", "Da quel momento il problema politico divenne riformare lo Stato dall'interno, non rifondarlo con una nuova rivoluzione. Questa conversione alla monarchia costituzionale spiega molte contraddizioni successive del crispismo."], summary: "La monarchia fu accettata come strumento dell'unità, non come semplice conversione conservatrice." },
        { title: "Un'idea dello Stato", paragraphs: ["Crispi temeva che uno Stato giovane, con forti differenze territoriali e nuove opposizioni sociali, potesse essere paralizzato da governi deboli e maggioranze instabili. Ammirava la capacità organizzativa della Germania bismarckiana e attribuiva grande importanza a esecutivo, prefetti, amministrazione e prestigio internazionale.", "Il suo modello non era una dittatura fuori dal Parlamento: Crispi operava nel sistema statutario e cercava maggioranze. Tuttavia concepiva il governo come centro propulsore della nazione e guardava con diffidenza alle forze che riteneva capaci di disgregarla."], summary: "Il crispismo nasce dall'idea che riforme e autorità debbano procedere insieme." },
        { title: "1887: l'arrivo alla guida del governo", paragraphs: ["Alla morte di Depretis, nel luglio 1887, Crispi divenne presidente del Consiglio. Era il primo siciliano e il primo meridionale a guidare stabilmente il governo del Regno. Il suo prestigio derivava dal Risorgimento, ma il programma di efficienza, ordine e potenza attirava anche settori moderati e conservatori.", "La sua prima fase di governo durò fino al gennaio 1891. Tornò al potere nel dicembre 1893, durante una crisi bancaria e sociale molto più grave, e rimase fino alla sconfitta di Adua nel marzo 1896."], summary: "Le due fasi crispine si collocano in contesti diversi: riforma dello Stato prima, emergenza sociale e coloniale poi." },
        { title: "Conclusione: una traiettoria, non un capovolgimento", paragraphs: ["Ridurre Crispi a un ex rivoluzionario diventato semplicemente reazionario non spiega abbastanza. Il filo continuo della sua politica fu la nazione: prima da costruire, poi da rendere autorevole e disciplinata.", "Proprio questa continuità rende più interessante la sua parabola. Le idee democratiche del Risorgimento non scomparvero, ma furono subordinate alla convinzione che lo Stato dovesse guidare la società dall'alto."], summary: "La trasformazione di Crispi è comprensibile se si segue il passaggio dalla rivoluzione nazionale alla statualità." }
      ],
      source: { id: "crispi-biografia", title: "Crispi: dal Risorgimento al governo", prompt: "Individua gli elementi di continuità e quelli di rottura tra il Crispi democratico e il Crispi presidente del Consiglio." },
      activity: { title: "Biografia politica, non psicologica", prompt: "Costruisci una linea in cinque passaggi che spieghi il cambiamento politico di Crispi senza ricorrere a giudizi sul carattere personale. Ogni passaggio deve collegare esperienza, problema e scelta." },
      coordinates: ["1818: nascita a Ribera", "1848: rivoluzione siciliana", "1860: spedizione dei Mille", "1864: accettazione della monarchia come quadro dell'unità", "29 luglio 1887: presidente del Consiglio", "1887-1891 e 1893-1896: le due fasi di governo"],
      essentials: ["Crispi proveniva dal movimento democratico e mazziniano.", "Partecipò alla rivoluzione del 1848 e alla spedizione dei Mille.", "Dopo l'Unità accettò la monarchia costituzionale.", "Il centro della sua politica divenne il rafforzamento dello Stato nazionale.", "Il riferimento a Bismarck riguardava soprattutto forza ed efficienza dello Stato.", "Governò in due fasi distinte.", "La sua politica va spiegata attraverso istituzioni e contesto, non soltanto attraverso la personalità."],
      vocab: { Crispismo: "Progetto di rafforzamento dello Stato nazionale attraverso riforme dall'alto, centralizzazione, politica di potenza e controllo delle opposizioni ritenute pericolose.", Statualita: "Capacità delle istituzioni pubbliche di esercitare stabilmente autorità, amministrazione e servizi sul territorio.", Esecutivo: "Il governo e gli organi che attuano le decisioni politiche e amministrative.", Prefetto: "Rappresentante del governo nella provincia, con importanti funzioni amministrative e di ordine pubblico.", Bismarckismo: "Nel lessico politico dell'epoca, riferimento a uno Stato nazionale forte, amministrativamente efficiente e autorevole in politica estera." },
      answer: "Crispi passò dal repubblicanesimo alla monarchia perché ritenne che, dopo l'Unità, la priorità non fosse più provocare una rivoluzione istituzionale ma consolidare lo Stato nazionale. Il suo passato democratico sopravvisse nelle riforme, mentre la paura della frammentazione e del conflitto sociale rafforzò la sua concezione autoritaria dell'esecutivo.",
      connections: { map: "Italia politica e centri della crisi", people: ["crispi", "zanardelli"] }
    },
    {
      id: "riforme-autorita", number: 2, title: "Riformare e controllare", eyebrow: "Il paradosso del crispismo", period: "1888-1890",
      question: "Perché le riforme crispine ampliarono alcune garanzie e, contemporaneamente, rafforzarono gli strumenti di controllo dello Stato?",
      lead: "Fra il 1888 e il 1890 il governo intervenne su comuni, province, sanità, giustizia amministrativa, diritto penale, pubblica sicurezza e assistenza. Il risultato non è classificabile con una sola etichetta: più diritti in alcuni campi, più controllo preventivo in altri.",
      sections: [
        { title: "Comuni e province: partecipazione sotto tutela", paragraphs: ["La legge comunale e provinciale del 1888 ampliò l'elettorato amministrativo e rese elettivi i sindaci nei comuni maggiori, oltre a rafforzare la componente elettiva nelle province. Fu un passo reale verso una maggiore partecipazione locale.", "La stessa architettura mantenne però un forte ruolo del prefetto e del governo centrale. L'autonomia locale cresceva senza mettere in discussione il controllo politico-amministrativo dello Stato unitario."], summary: "Più elezione locale non significò decentramento pieno." },
        { title: "Sanità e amministrazione: lo Stato entra nella società", paragraphs: ["La riforma sanitaria del 1888 organizzò in modo più coerente l'igiene pubblica e attribuì allo Stato maggiori responsabilità nella prevenzione e nella tutela sanitaria. La modernizzazione non riguardava più soltanto esercito, fisco e prefetture: investiva la vita quotidiana.", "Nel 1889 la riforma della giustizia amministrativa istituì la IV sezione del Consiglio di Stato, creando strumenti più efficaci per contestare atti della pubblica amministrazione. Lo Stato diventava più presente, ma anche più giuridicamente regolato."], summary: "La modernizzazione costruì nuovi servizi e nuove garanzie contro l'amministrazione." },
        { title: "Il Codice Zanardelli", paragraphs: ["Il nuovo codice penale, autorizzato nel 1888 ed entrato in vigore nel 1890, abolì la pena di morte per i reati comuni e rese il sistema penale più coerente con la cultura liberale. Lo sciopero pacifico non era più automaticamente trattato come reato, anche se potevano restare perseguibili violenze o minacce.", "Il codice porta il nome del ministro Giuseppe Zanardelli e rappresenta uno dei risultati più avanzati della legislazione liberale italiana dell'Ottocento. Il fatto che maturi sotto Crispi mostra quanto sia insufficiente separare rigidamente riforma e autorità."], summary: "Una grande riforma garantista nacque dentro un governo politicamente centralizzatore." },
        { title: "Pubblica sicurezza e prevenzione", paragraphs: ["La legge di pubblica sicurezza del 1888 ampliò gli strumenti preventivi disponibili contro persone considerate pericolose, attraverso misure come ammonizione e domicilio coatto. In questo campo la logica era diversa da quella del codice penale: non soltanto punire un reato accertato, ma prevenire un rischio politico o sociale.", "Qui emerge il cuore del problema: il cittadino otteneva garanzie nel processo penale, mentre l'amministrazione di polizia conservava margini ampi di intervento preventivo."], summary: "Il diritto penale diventava più liberale mentre la polizia restava uno strumento forte di governo della società." },
        { title: "Le opere pie: assistenza e laicizzazione", paragraphs: ["La legge del 1890 sulle istituzioni pubbliche di beneficenza sottopose a maggiore controllo pubblico molte opere pie e ne trasformò parte dell'attività in assistenza amministrata secondo criteri statali. Per i sostenitori era razionalizzazione; per gli oppositori, soprattutto cattolici, era statalizzazione e riduzione dell'autonomia religiosa.", "Anche questa riforma mostra il doppio movimento del crispismo: costruzione di servizi moderni e concentrazione delle decisioni nelle istituzioni pubbliche."], summary: "Modernizzare l'assistenza significò anche ridefinire il rapporto tra Stato, enti locali e Chiesa." },
        { title: "Conclusione: libertà e capacità dello Stato", paragraphs: ["Il primo crispismo non si comprende scegliendo tra due immagini opposte. Fu davvero riformatore, ma riteneva che i diritti dovessero essere compatibili con la capacità dello Stato di controllare il territorio e prevenire disordini.", "Questa tensione diventerà più grave quando il conflitto sociale non sarà più una possibilità astratta, ma un movimento organizzato di massa."], summary: "La stessa macchina statale che protegge diritti può essere usata per limitare il conflitto politico." }
      ],
      source: { id: "riforme-1888", title: "Le riforme del 1888-1890 negli atti parlamentari", prompt: "Classifica ogni riforma in base a due criteri separati: ampliamento di garanzie e aumento della capacità di controllo dello Stato." },
      activity: { title: "Due colonne non bastano", prompt: "Scegli quattro riforme e costruisci per ciascuna una scheda con: problema, innovazione, beneficiario, nuovo potere dello Stato, possibile rischio. Concludi spiegando perché 'liberale' e 'autoritario' non sono qui categorie totalmente alternative." },
      coordinates: ["1888: riforma comunale e provinciale", "1888: riforma sanitaria", "1888: nuova disciplina di pubblica sicurezza", "1889: testo definitivo del Codice Zanardelli", "1889: IV sezione del Consiglio di Stato", "1890: istituzioni pubbliche di beneficenza"],
      essentials: ["La riforma amministrativa ampliò il voto locale.", "Nei comuni maggiori il sindaco divenne elettivo.", "Il prefetto conservò un ruolo forte.", "La riforma sanitaria accrebbe la responsabilità pubblica.", "Il Codice Zanardelli abolì la pena di morte per i reati comuni.", "La pubblica sicurezza mantenne strumenti preventivi incisivi.", "Le opere pie furono sottoposte a maggiore controllo pubblico."],
      vocab: { Codice_Zanardelli: "Codice penale del 1889, in vigore dal 1890, che abolì la pena di morte per i reati comuni e riorganizzò il diritto penale del Regno.", Ammonizione: "Misura preventiva di polizia applicabile a persone considerate socialmente pericolose secondo la legislazione dell'epoca.", Domicilio_coatto: "Obbligo amministrativo di risiedere in un luogo stabilito dall'autorità, spesso usato contro oppositori o sospetti.", Giustizia_amministrativa: "Sistema di tutela contro atti illegittimi della pubblica amministrazione.", Opera_pia: "Ente tradizionalmente dedito ad assistenza e beneficenza, spesso di origine religiosa o privata." },
      answer: "Le riforme crispine modernizzarono lo Stato e ampliarono alcune garanzie perché l'obiettivo era costruire istituzioni più efficienti e legittime. Ma la stessa idea di Stato forte portava a conservare o rafforzare strumenti preventivi di polizia e controllo. La contraddizione non è accidentale: appartiene al progetto politico.",
      connections: { map: "Italia amministrativa e prefetture", people: ["crispi", "zanardelli"] }
    },
    {
      id: "protezionismo-crisi", number: 3, title: "Proteggere l'industria, redistribuire i costi", eyebrow: "Tariffe, grano e guerra doganale", period: "1887-1898",
      question: "Una politica economica presentata come nazionale può produrre vincitori e perdenti territorialmente e socialmente diversi?",
      lead: "La tariffa protezionistica del 1887 difese siderurgia, tessili e cereali. La rottura commerciale con la Francia dal 1888 colpì però duramente produzioni d'esportazione e capitali. La crisi economica fu il risultato di più fattori, non di una sola scelta.",
      sections: [
        { title: "La crisi agraria internazionale", paragraphs: ["Negli anni Ottanta i prezzi agricoli europei subirono la pressione dei cereali americani e russi trasportati a costi sempre più bassi. Proprietari e produttori italiani chiesero protezione; per molti governi europei il dazio divenne uno strumento per difendere redditi e produzione interna.", "L'Italia era però agricolarmente diversa: il grande cerealicoltore, il viticoltore, l'agrumicoltore e il piccolo contadino non avevano gli stessi interessi. Una tariffa favorevole al grano poteva danneggiare chi viveva di esportazioni specializzate."], summary: "La crisi globale trasformò differenze agricole interne in conflitti politici." },
        { title: "La tariffa del 1887", paragraphs: ["La tariffa doganale, preparata nella fase finale dei governi Depretis, aumentò i dazi su numerosi prodotti industriali e sul grano. Favorì settori siderurgici e tessili e sostenne i grandi produttori cerealicoli contro le importazioni a basso prezzo.", "Per i consumatori, però, la protezione del grano contribuiva a mantenere più alto il costo di un bene essenziale. Per molte aziende meridionali orientate all'esportazione, il problema era opposto: avevano bisogno di mercati esteri aperti."], summary: "Il protezionismo creò una coalizione di interessi, non un vantaggio uniforme per tutti gli italiani." },
        { title: "La guerra doganale con la Francia", paragraphs: ["Nel 1888 il mancato rinnovo dell'accordo commerciale portò a ritorsioni reciproche tra Italia e Francia. Vino, olio, agrumi, seta e altri prodotti italiani persero accesso favorevole a uno dei principali mercati di esportazione; diminuirono inoltre i capitali francesi disponibili in Italia.", "La crisi fu particolarmente dura nel Mezzogiorno esportatore, ma toccò anche finanza ed edilizia. La vera normalizzazione commerciale arrivò soltanto nel 1898."], summary: "La politica estera e quella doganale trasformarono una crisi agricola in una frattura commerciale più ampia." },
        { title: "Industria e Stato", paragraphs: ["La protezione era legata anche alla volontà di creare un'industria pesante nazionale utile alla difesa. Terni, fondata nel 1884, simboleggiava il rapporto crescente tra industria, commesse pubbliche, armamenti e ambizione di grande potenza.", "Il sostegno statale poteva favorire accumulazione e investimenti in settori strategici, ma rendeva più stretti i legami fra politica, banche e imprese. Questa connessione diventerà evidente nella crisi finanziaria dei primi anni Novanta."], summary: "La modernizzazione industriale fu sostenuta dallo Stato e quindi intrecciata a scelte fiscali, militari e finanziarie." },
        { title: "Non una causa unica", paragraphs: ["Sarebbe scorretto attribuire alla guerra doganale l'intera crisi economica di fine anni Ottanta. Depressione agricola internazionale, speculazione edilizia, fragilità bancaria, squilibri territoriali e problemi di finanza pubblica agirono contemporaneamente.", "La storia economica richiede quindi di distinguere cause, acceleratori e conseguenze. La tariffa e il conflitto con la Francia non crearono da soli la crisi, ma ne redistribuirono pesantemente i costi."], summary: "Una spiegazione monocausale semplifica troppo una crisi sistemica." },
        { title: "Conclusione: l'interesse nazionale va scomposto", paragraphs: ["Quando un governo parla di proteggere l'economia nazionale bisogna chiedere chi produce, chi consuma, chi esporta, chi importa e quali territori dipendono dai diversi mercati.", "La tariffa del 1887 mostra che una politica nazionale può produrre effetti opposti dentro la stessa nazione."], summary: "La politica economica è sempre anche politica sociale e territoriale." }
      ],
      source: { id: "tariffa-francia", title: "Tariffe e guerra commerciale Italia-Francia", prompt: "Ricostruisci chi otteneva protezione e chi invece dipendeva dall'apertura dei mercati francesi." },
      activity: { title: "Quattro bilanci della stessa tariffa", prompt: "Valuta la tariffa del 1887 dal punto di vista di un siderurgico, un grande cerealicoltore, un produttore di agrumi siciliano e una famiglia operaia urbana. Non cercare una risposta unica: confronta costi e benefici." },
      coordinates: ["1884: fondazione delle Acciaierie di Terni", "1887: tariffa protezionistica", "1888: inizio della guerra doganale con la Francia", "Anni 1880: crisi agraria europea", "Primi anni 1890: crisi bancaria e immobiliare", "1898: normalizzazione commerciale con la Francia"],
      essentials: ["La tariffa del 1887 nasce prima del pieno governo Crispi ma ne segna la politica economica.", "Dazi industriali e sul grano favorirono interessi diversi.", "Il protezionismo poteva aumentare i costi per i consumatori.", "Le colture meridionali d'esportazione furono esposte alle ritorsioni francesi.", "La guerra doganale iniziò nel 1888.", "La crisi economica ebbe cause multiple.", "Industria pesante, armamenti e commesse pubbliche erano sempre più collegati."],
      vocab: { Protezionismo: "Politica che usa dazi e altre barriere per ridurre la concorrenza delle importazioni.", Dazio: "Imposta applicata alle merci che attraversano una frontiera doganale.", Guerra_doganale: "Conflitto economico in cui Stati rivali aumentano reciprocamente tariffe e restrizioni commerciali.", Crisi_agraria: "Caduta o instabilità dei redditi agricoli provocata da prezzi, concorrenza, debiti, produttività e struttura della proprietà.", Commesse_pubbliche: "Acquisti e contratti finanziati dallo Stato, capaci di sostenere specifici settori produttivi." },
      answer: "Il protezionismo non proteggeva tutti nello stesso modo. Sosteneva industria e cerealicoltura, ma trasferiva costi sui consumatori e rendeva vulnerabili le produzioni esportatrici alle ritorsioni. La guerra commerciale con la Francia aggravò una crisi già determinata da fattori internazionali, bancari e immobiliari.",
      connections: { map: "Italia economica e mercato francese", people: ["crispi", "giolitti"] }
    },
    {
      id: "banca-romana", number: 4, title: "La moneta entra nella crisi politica", eyebrow: "Giolitti I e lo scandalo della Banca Romana", period: "1889-1893",
      question: "Che cosa rivela uno scandalo finanziario quando coinvolge banche, speculazione, giornali e politica?",
      lead: "La Banca Romana superò i limiti di emissione, mise in circolazione biglietti irregolari e finanziò il boom edilizio romano. L'inchiesta nascosta nel 1889 e lo scandalo esploso nel 1892 trasformarono una crisi bancaria in crisi di fiducia nelle istituzioni.",
      sections: [
        { title: "Un sistema di emissione frammentato", paragraphs: ["Dopo l'Unità più istituti conservavano il diritto di emettere banconote. Questo sistema rifletteva l'eredità degli Stati preunitari e rendeva più complesso il controllo della circolazione monetaria.", "Nel boom edilizio di Roma capitale le banche di emissione finanziarono investimenti e speculazioni. Quando i prezzi immobiliari rallentarono, crediti difficili da recuperare e irregolarità divennero più visibili."], summary: "La crisi nasce da un sistema bancario ancora incompletamente unificato e da una forte espansione del credito." },
        { title: "L'ispezione del 1889", paragraphs: ["Un'ispezione condotta nel 1889 scoprì gravi irregolarità nella Banca Romana, tra cui emissioni oltre i limiti e biglietti duplicati. La relazione non fu resa immediatamente pubblica.", "La scelta di non portare subito il problema all'opinione pubblica trasformò la successiva scoperta in una questione politica: non si discuteva più soltanto di cattiva gestione bancaria, ma di responsabilità e coperture istituzionali."], summary: "Il segreto sull'ispezione aumentò il peso politico dello scandalo." },
        { title: "1892: Colajanni porta il caso in Parlamento", paragraphs: ["Nel dicembre 1892 il deputato Napoleone Colajanni rese pubblici alla Camera i risultati dell'inchiesta. Il governatore Bernardo Tanlongo fu arrestato; emersero prestiti, favori e legami con ambienti politici e giornalistici.", "Lo scandalo coinvolse esponenti di schieramenti diversi. Giolitti fu duramente attaccato perché conosceva parte delle irregolarità e aveva proposto Tanlongo per il Senato, ma non fu poi condannato penalmente per queste vicende."], summary: "La Banca Romana mostrò una zona grigia tra finanziamento politico, credito e debole controllo pubblico." },
        { title: "La riforma del 1893", paragraphs: ["La risposta istituzionale fu la legge del 10 agosto 1893. La Banca d'Italia nacque dalla fusione della Banca Nazionale nel Regno con due istituti toscani; Banca Romana fu liquidata. Banco di Napoli e Banco di Sicilia conservarono per allora il diritto di emissione.", "Non nacque ancora una banca centrale moderna nel senso pieno del Novecento, ma fu compiuto un passo decisivo verso concentrazione, regole più rigide e controllo pubblico della circolazione."], summary: "La crisi produsse una riforma strutturale del sistema di emissione." },
        { title: "Giolitti e l'ordine pubblico", paragraphs: ["Il primo governo Giolitti, nato nel 1892, cercava anche una linea diversa nei conflitti sociali: lo Stato non doveva intervenire automaticamente a favore dei proprietari quando uno sciopero restava economico e non violento.", "Questa impostazione fu però travolta dalla combinazione di scandalo bancario, crisi economica e agitazioni siciliane. Nel novembre 1893 Giolitti si dimise; il ritorno di Crispi avrebbe segnato un cambio netto nella gestione dell'ordine pubblico."], summary: "La crisi finanziaria e quella sociale si saldarono, indebolendo il tentativo giolittiano di mediazione." },
        { title: "Conclusione: lo scandalo come lente", paragraphs: ["La Banca Romana è importante non perché dimostri che tutta la politica italiana fosse corrotta, ma perché rivela debolezze sistemiche: controlli insufficienti, finanziamento opaco, commistione fra affari e rappresentanza politica.", "La riforma del 1893 mostra anche la capacità dello Stato liberale di reagire istituzionalmente a una crisi che ne aveva danneggiato la credibilità."], summary: "Lo scandalo produsse delegittimazione, ma anche innovazione istituzionale." }
      ],
      source: { id: "banca-italia-1893", title: "Dalla Banca Romana alla Banca d'Italia", prompt: "Distingui tre livelli: illecito bancario, responsabilità politica e riforma istituzionale." },
      activity: { title: "Un diagramma della crisi", prompt: "Collega in un diagramma: boom edilizio, credito, banche di emissione, politica, giornali, ispezione del 1889, denuncia di Colajanni, dimissioni di Giolitti, legge bancaria del 1893. Per ogni freccia scrivi il nesso causale." },
      coordinates: ["1889: ispezione Alvisi-Biagini", "Dicembre 1892: denuncia di Colajanni", "Gennaio 1893: arresto di Tanlongo", "10 agosto 1893: legge n. 449", "Novembre 1893: dimissioni di Giolitti", "1 gennaio 1894: inizio dell'attività della Banca d'Italia"],
      essentials: ["La Banca Romana era uno degli istituti di emissione.", "Finanziò anche la speculazione edilizia romana.", "L'ispezione del 1889 scoprì gravi irregolarità.", "Colajanni rese il caso pubblico alla fine del 1892.", "Lo scandalo mostrò intrecci tra finanza e politica.", "La legge del 1893 istituì la Banca d'Italia.", "Banco di Napoli e Banco di Sicilia conservarono ancora l'emissione."],
      vocab: { Banca_di_emissione: "Istituto autorizzato dallo Stato a emettere banconote.", Circolazione: "Quantità di moneta cartacea in uso nell'economia.", Speculazione_edilizia: "Investimenti immobiliari ad alto rischio basati sull'attesa di aumenti di valore.", Liquidazione: "Procedura con cui si chiudono attività e passività di un'impresa o istituto.", Banca_d_Italia: "Istituto nato nel 1893 dalla fusione di tre banche, destinato progressivamente a diventare la banca centrale italiana." },
      answer: "Lo scandalo rivelò che il sistema di emissione e i controlli non erano adeguati alla crescita del credito e alla finanziarizzazione della politica. Non fu soltanto un caso di corruzione individuale: mostrò un problema istituzionale. La legge del 1893 rispose concentrando e regolando maggiormente l'emissione.",
      connections: { map: "Roma capitale e rete bancaria", people: ["giolitti", "colajanni", "crispi"] }
    },
    {
      id: "fasci-siciliani", number: 5, title: "Quando la questione sociale diventa ordine pubblico", eyebrow: "Fasci siciliani e stato d'assedio", period: "1891-1894",
      question: "Che cosa cambia quando un governo interpreta un movimento sociale come una minaccia all'unità dello Stato?",
      lead: "I Fasci dei lavoratori riunirono contadini, braccianti, minatori, artigiani e ceti popolari in una Sicilia segnata da crisi agraria, tassazione locale e rapporti di potere diseguali. Giolitti cercò inizialmente di distinguere sciopero e insurrezione; Crispi scelse lo stato d'assedio.",
      sections: [
        { title: "Che cosa significa fascio", paragraphs: ["Nell'Ottocento il termine fascio indicava un'unione organizzata. I Fasci siciliani non hanno relazione diretta con il fascismo nato decenni dopo: erano associazioni popolari e del lavoro, molte delle quali influenzate dal socialismo.", "Vi partecipavano braccianti, contadini, zolfatari, artigiani e lavoratori urbani. Il movimento era eterogeneo e variava molto da territorio a territorio."], summary: "Il nome va ricollocato nel lessico politico dell'Ottocento, senza proiezioni anacronistiche." },
        { title: "Le rivendicazioni", paragraphs: ["Le richieste riguardavano salari, contratti agrari, imposte comunali, accesso alla terra, usura e amministrazioni locali. In alcune zone furono elaborati patti agrari e si organizzarono scioperi coordinati.", "Dirigenti come Giuseppe De Felice Giuffrida, Nicola Barbato, Rosario Garibaldi Bosco e Bernardino Verro collegavano rivendicazioni economiche a un progetto politico di emancipazione e organizzazione dei lavoratori."], summary: "La protesta sociale diventò organizzazione politica, senza costituire un unico piano rivoluzionario nazionale." },
        { title: "Violenza, paura e interpretazioni", paragraphs: ["Nel 1893 alcuni conflitti degenerarono in assalti a municipi, uffici del dazio o proprietà; in diversi luoghi l'intervento delle forze dell'ordine provocò morti. Proprietari e amministratori lessero la crescita del movimento come minaccia rivoluzionaria.", "La difficoltà storica sta nel non confondere gli episodi di violenza con l'intero movimento. Le organizzazioni non erano tutte uguali e non esisteva una direzione unica capace di coordinare una rivoluzione dell'isola."], summary: "La paura delle élite trasformò un conflitto sociale plurale in un problema nazionale di sicurezza." },
        { title: "Giolitti: distinguere conflitto e insurrezione", paragraphs: ["Giolitti riteneva che lo Stato non dovesse usare automaticamente l'esercito contro scioperi e rivendicazioni economiche. Finché l'ordine pubblico non fosse realmente compromesso, la mediazione poteva ridurre il conflitto.", "Questa posizione fu considerata debole dai proprietari e da molti parlamentari. Lo scandalo della Banca Romana tolse a Giolitti la forza politica necessaria per difenderla."], summary: "La questione non era tollerare ogni violenza, ma stabilire quando il conflitto sociale diventasse materia militare." },
        { title: "Crispi: stato d'assedio e tribunali militari", paragraphs: ["Tornato al governo nel dicembre 1893, Crispi proclamò lo stato d'assedio in Sicilia il 3 gennaio 1894. L'esercito occupò l'isola, i Fasci furono sciolti e numerosi dirigenti processati da tribunali militari. Misure analoghe furono adottate in Lunigiana contro moti anarchici.", "Nel luglio 1894 furono approvate leggi eccezionali contro anarchici e organizzazioni ritenute sovversive. Il Partito socialista dei lavoratori italiani fu sciolto amministrativamente, ma continuò clandestinamente e si riorganizzò."], summary: "La risposta crispina spostò la questione sociale dal terreno della mediazione a quello dell'emergenza e della sicurezza." },
        { title: "Conclusione: ristabilire l'ordine non risolve le cause", paragraphs: ["La repressione disarticolò il movimento e ristabilì il controllo statale, ma non eliminò povertà rurale, rapporti agrari conflittuali, tassazione locale e concentrazione della proprietà.", "Per questo i Fasci sono una svolta: mostrano che lo Stato liberale deve ormai governare organizzazioni popolari e conflitti collettivi che non possono essere ridotti a devianza individuale."], summary: "L'ordine militare può chiudere una mobilitazione, non cancellare le condizioni che l'hanno prodotta." }
      ],
      source: { id: "fasci-documenti", title: "Fasci siciliani: movimento sociale o insurrezione?", prompt: "Confronta rivendicazioni, composizione sociale e reazione governativa. Distingui il movimento dai singoli episodi di violenza." },
      activity: { title: "Due governi davanti allo stesso conflitto", prompt: "Scrivi due memorandum di 150 parole: uno dal punto di vista del governo Giolitti, uno dal punto di vista del governo Crispi. Entrambi devono riconoscere rischi reali e costi della propria scelta." },
      coordinates: ["1891-1893: diffusione dei Fasci", "1893: crescita degli scioperi e dei conflitti agrari", "Novembre 1893: caduta di Giolitti", "15 dicembre 1893: ritorno di Crispi", "3 gennaio 1894: stato d'assedio in Sicilia", "Luglio 1894: leggi eccezionali"],
      essentials: ["I Fasci erano associazioni popolari e del lavoro.", "Il termine non va confuso con il fascismo novecentesco.", "Il movimento aveva una forte componente socialista ma non era omogeneo.", "Le rivendicazioni erano economiche, fiscali e politiche.", "Giolitti cercò inizialmente di evitare l'intervento militare generalizzato.", "Crispi proclamò lo stato d'assedio.", "La repressione non risolse le cause sociali del movimento."],
      vocab: { Fasci_siciliani: "Movimento di associazioni popolari e del lavoro sviluppato in Sicilia fra il 1891 e il 1894.", Stato_d_assedio: "Regime eccezionale che attribuisce ampi poteri all'autorità militare e limita le libertà ordinarie.", Tribunale_militare: "Organo giudiziario militare impiegato anche contro civili in determinate situazioni eccezionali dell'epoca.", Zolfataro: "Lavoratore delle miniere di zolfo siciliane.", Questione_sociale: "Insieme dei problemi prodotti da povertà, lavoro, disuguaglianze e organizzazione collettiva nella società industriale e rurale moderna." },
      answer: "Il passaggio da Giolitti a Crispi cambiò la categoria con cui lo Stato leggeva il conflitto: da problema sociale da distinguere dalla violenza a minaccia potenzialmente rivoluzionaria. Lo stato d'assedio ristabilì il controllo, ma trasferì il problema dalla negoziazione alla repressione senza risolverne le cause economiche e politiche.",
      connections: { map: "Sicilia dei Fasci e centri della repressione", people: ["crispi", "giolitti", "colajanni"] }
    },
    {
      id: "etiopia-adua", number: 6, title: "Adua: quando l'impero incontra un altro Stato", eyebrow: "Colonialismo, Uccialli e guerra d'Etiopia", period: "1882-1896",
      question: "Perché la guerra d'Etiopia non può essere spiegata come semplice espansione europea contro un territorio passivo?",
      lead: "L'Italia costruì una colonia sul Mar Rosso e cercò di trasformare il rapporto con Menelik II in dipendenza politica. La disputa sull'articolo 17 del trattato di Uccialli portò alla rottura. Ad Adua l'Etiopia dimostrò capacità diplomatica, logistica e militare autonoma.",
      sections: [
        { title: "Dal Mar Rosso alla colonia Eritrea", paragraphs: ["La presenza italiana iniziò dalla baia di Assab, acquistata dalla società Rubattino e poi trasferita allo Stato. Nel 1885 l'Italia occupò Massaua; nel 1890 proclamò ufficialmente la colonia Eritrea.", "Le motivazioni erano molteplici: prestigio internazionale, controllo di rotte strategiche, interessi commerciali, politica di potenza e speranza di nuovi sbocchi. La retorica coloniale presentava questi obiettivi come interesse nazionale, ma in Parlamento e nel paese esistevano forti opposizioni."], summary: "L'espansione coloniale fu una scelta politica contestata, non un destino inevitabile." },
        { title: "Uccialli: due testi, due sovranità", paragraphs: ["Nel 1889 Menelik, re dello Scioa e prossimo imperatore, firmò con l'Italia il trattato di Uccialli. L'articolo 17 aveva formulazioni differenti: il testo italiano poteva essere letto come obbligo di usare l'Italia per le relazioni estere; il testo amarico indicava una possibilità.", "La storiografia ha discusso responsabilità e intenzioni dei negoziatori, ma il punto politico è chiaro: Roma notificò alle potenze una pretesa di protettorato; Menelik rifiutò che la propria sovranità fosse limitata."], summary: "La controversia non fu un dettaglio linguistico: riguardava il diritto dell'Etiopia a condurre autonomamente la propria politica estera." },
        { title: "Menelik costruisce alleanze e capacità militare", paragraphs: ["L'Etiopia di Menelik non era uno Stato europeo, ma non era nemmeno una realtà politicamente informe. L'imperatore dovette coordinare autorità regionali, negoziare fedeltà, raccogliere risorse e mantenere un grande esercito sul campo.", "Acquistò armi moderne da più circuiti internazionali e sfruttò la diplomazia tra potenze europee. La capacità di evitare l'isolamento fu una parte della vittoria tanto quanto la superiorità numerica sul campo."], summary: "La resistenza etiopica fu politica, diplomatica, logistica e militare." },
        { title: "Dalla crisi alla battaglia", paragraphs: ["Nel 1893 Menelik denunciò il trattato di Uccialli. Nel dicembre 1895 un reparto italiano fu sconfitto ad Amba Alagi; seguì il difficile assedio di Macallè. Crispi esercitò forti pressioni perché la campagna producesse un successo decisivo.", "Nella notte tra il 29 febbraio e il 1 marzo 1896 le brigate italiane avanzarono separate, con ordini e carte insufficienti per un terreno complesso. Le forze etiopiche riuscirono ad attaccarle senza che potessero sostenersi efficacemente a vicenda."], summary: "La sconfitta fu il prodotto di scelte politiche e operative, non di un singolo errore sul campo." },
        { title: "Adua e i suoi significati", paragraphs: ["Il 1 marzo 1896 l'esercito italiano subì una sconfitta gravissima. Migliaia di soldati italiani ed eritrei morirono o furono catturati. L'evento provocò manifestazioni contro la guerra e la caduta definitiva di Crispi.", "Per l'Etiopia Adua divenne simbolo di indipendenza e resistenza alla conquista coloniale. La storiografia recente invita però a non trasformare la battaglia in un monumento senza problemi: l'Etiopia di Menelik era a sua volta un impero in espansione regionale. Riconoscere questa complessità non riduce il significato anticoloniale della vittoria."], summary: "Adua è insieme una sconfitta del colonialismo italiano, una vittoria della sovranità etiopica e un evento da leggere dentro la storia politica dell'Etiopia." },
        { title: "La pace di Addis Abeba", paragraphs: ["La pace del 26 ottobre 1896 annullò il trattato di Uccialli e riconobbe l'indipendenza etiopica. L'Italia conservò l'Eritrea, ma rinunciò per il momento alla conquista dell'interno etiopico.", "La vicenda mostrò che l'imperialismo europeo non procedeva in modo lineare e inevitabile: dipendeva da risorse, alleanze, decisioni locali e capacità di resistenza."], summary: "La pace riconobbe formalmente ciò che Adua aveva imposto militarmente: l'Etiopia restava sovrana." }
      ],
      source: { id: "uccialli-art17", title: "L'articolo 17 del trattato di Uccialli", prompt: "Confronta le interpretazioni del testo italiano e amarico e spiega perché una differenza verbale cambia la definizione stessa della sovranità." },
      activity: { title: "Rovesciare lo sguardo", prompt: "Spiega Adua due volte: prima partendo dalle decisioni italiane, poi partendo dalla strategia etiopica. Confronta ciò che diventa visibile e ciò che scompare nelle due narrazioni." },
      coordinates: ["1869: acquisto della baia di Assab da parte di Rubattino", "1882: Assab allo Stato italiano", "1885: occupazione di Massaua", "1889: trattato di Uccialli", "1890: colonia Eritrea", "1893: denuncia del trattato da parte di Menelik", "1 marzo 1896: Adua", "26 ottobre 1896: pace di Addis Abeba"],
      essentials: ["L'espansione italiana sul Mar Rosso precede Crispi.", "La colonia Eritrea fu proclamata nel 1890.", "L'articolo 17 aveva versioni italiana e amarica divergenti.", "Menelik rifiutò il protettorato italiano.", "L'Etiopia disponeva di alleanze, risorse e armi moderne.", "La sconfitta italiana dipese anche da dispersione delle forze e pressione politica.", "Adua provocò la caduta di Crispi.", "La pace riconobbe l'indipendenza etiopica."],
      vocab: { Colonialismo: "Politica di espansione con cui uno Stato impone controllo politico, militare ed economico su altri territori e popolazioni.", Protettorato: "Forma di subordinazione internazionale in cui uno Stato perde una parte della propria autonomia, soprattutto nelle relazioni estere.", Sovranita: "Capacità di un'autorità politica di governare senza dipendere giuridicamente da un potere superiore esterno.", Askari: "Soldati coloniali indigeni arruolati nelle forze italiane dell'Africa orientale.", Adua: "Battaglia del 1 marzo 1896 in cui l'esercito di Menelik II sconfisse le forze italiane." },
      answer: "La guerra non fu l'espansione di uno Stato moderno in uno spazio privo di politica. Menelik coordinò autorità regionali, diplomazia e armamenti e respinse la pretesa italiana di limitare la sovranità etiopica. La sconfitta di Adua derivò dall'aggressività del progetto coloniale, dalla sottovalutazione dell'avversario e da gravi problemi operativi italiani.",
      connections: { map: "Mar Rosso, Eritrea ed Etiopia", people: ["crispi", "menelik", "baratieri"] }
    },
    {
      id: "crisi-1898", number: 7, title: "Il pane, i cannoni e il Parlamento", eyebrow: "La crisi di fine secolo", period: "1898-1900",
      question: "Quando la difesa dell'ordine pubblico diventa una crisi delle stesse istituzioni liberali?",
      lead: "Dopo Adua, il caro pane e la disoccupazione alimentarono proteste diffuse. A Milano Bava Beccaris usò esercito e artiglieria. Il governo Pelloux tentò poi di rendere permanenti restrizioni a stampa, riunione, associazione e sciopero, ma incontrò resistenza parlamentare e giudiziaria.",
      sections: [
        { title: "1898: il prezzo del pane diventa politica", paragraphs: ["Cattivi raccolti, prezzo internazionale del grano, dazi e difficoltà delle importazioni contribuirono al rincaro del pane. In una società dove una parte rilevante del reddito popolare era assorbita dal cibo, l'aumento poteva trasformarsi rapidamente in protesta politica.", "Tumulti e manifestazioni attraversarono varie città. Non furono tutti identici né coordinati da un'unica organizzazione, ma il governo li lesse dentro il timore di una sovversione più generale."], summary: "Una crisi del costo della vita diventò crisi dell'ordine e della rappresentanza." },
        { title: "Milano e Bava Beccaris", paragraphs: ["Tra il 6 e il 9 maggio Milano fu teatro di scontri violentissimi. Il generale Fiorenzo Bava Beccaris, nominato commissario straordinario, impiegò truppe e artiglieria per reprimere le manifestazioni. Il numero esatto delle vittime resta discusso; le fonti ufficiali dell'epoca indicarono decine di morti e centinaia di feriti, mentre altre ricostruzioni proposero bilanci più alti.", "Furono arrestati esponenti socialisti, radicali, repubblicani e cattolici. La repressione colpì quindi un arco politico molto più vasto di chi aveva materialmente partecipato agli scontri."], summary: "La risposta militare trasformò il problema dell'ordine in un problema di legalità e libertà politica." },
        { title: "La monarchia entra nel conflitto", paragraphs: ["Umberto I conferì a Bava Beccaris un'alta onorificenza. Il gesto ebbe un valore politico enorme: rese più difficile separare la repressione milanese dalla responsabilità simbolica della Corona.", "Per le opposizioni non era più in discussione soltanto la condotta di un generale o di un ministero, ma il rapporto fra monarchia, governo e società in trasformazione."], summary: "La Corona si espose direttamente nella crisi, pagando un costo di legittimazione." },
        { title: "Pelloux e i provvedimenti politici", paragraphs: ["Luigi Pelloux divenne presidente del Consiglio nel giugno 1898. Nel 1899 presentò provvedimenti che restringevano libertà di stampa, riunione e associazione e limitavano il diritto di sciopero. Una parte dei liberali, oltre a radicali, repubblicani e socialisti, vide il rischio di trasformare l'emergenza in legislazione permanente.", "L'opposizione ricorse all'ostruzionismo: discorsi, emendamenti, richieste procedurali e uso delle regole parlamentari per impedire o rallentare l'approvazione. La battaglia sulle libertà diventò così una battaglia sul ruolo stesso della Camera."], summary: "Il Parlamento, spesso criticato come debole, divenne uno dei luoghi principali di resistenza alla svolta restrittiva." },
        { title: "Il decreto e la Cassazione", paragraphs: ["Il governo cercò di applicare parte delle misure attraverso decreto. Nel febbraio 1900 la Corte di cassazione dichiarò che il provvedimento non poteva continuare a produrre effetti senza la regolare conversione parlamentare dopo la chiusura della sessione.", "Lo scontro mostrò che la crisi non riguardava soltanto piazza e polizia: investiva il rapporto tra governo, Parlamento, magistratura e Statuto."], summary: "L'ordinamento liberale possedeva ancora contropoteri capaci di frenare la stabilizzazione dell'emergenza." },
        { title: "Le elezioni del 1900 e il fallimento della stretta", paragraphs: ["Pelloux sciolse la Camera sperando di ottenere una maggioranza più favorevole. Le elezioni del giugno 1900 rafforzarono invece le opposizioni di sinistra e la sinistra costituzionale. Il governo si dimise.", "Il fallimento non significò che la crisi fosse chiusa: poche settimane dopo, il 29 luglio, Gaetano Bresci uccise Umberto I a Monza."], summary: "La soluzione autoritaria non ottenne la legittimazione elettorale cercata dal governo." },
        { title: "Bresci e il regicidio", paragraphs: ["Bresci, operaio anarchico emigrato negli Stati Uniti, rientrò in Italia dopo i fatti del 1898 e uccise il re. Fu condannato all'ergastolo, poiché il Codice Zanardelli aveva abolito la pena di morte per i reati comuni.", "L'attentato fu un atto individuale, maturato nell'ambiente anarchico e legato anche alla volontà dichiarata di vendicare le vittime di Milano. Non va trasformato in prova di un piano unitario delle opposizioni socialiste, radicali o repubblicane."], summary: "Il regicidio fu l'esito estremo di una radicalizzazione, non la prosecuzione organizzata della lotta parlamentare." }
      ],
      source: { id: "camera-pelloux", title: "Ostruzionismo e provvedimenti politici", prompt: "Spiega perché una tecnica procedurale del Parlamento diventò uno strumento di difesa sostanziale delle libertà." },
      activity: { title: "Istituzioni sotto stress", prompt: "Costruisci una mappa con cinque nodi: piazza, esercito, governo, Parlamento, magistratura. Inserisci per ogni coppia almeno un conflitto o una relazione emersa tra 1898 e 1900." },
      coordinates: ["6-9 maggio 1898: moti di Milano", "7 maggio 1898: pieni poteri a Bava Beccaris", "Giugno 1898: governo Pelloux", "Febbraio 1899: disegno di legge sui provvedimenti politici", "Giugno 1899: decreto e ostruzionismo", "20 febbraio 1900: decisione della Cassazione", "Giugno 1900: elezioni e dimissioni Pelloux", "29 luglio 1900: uccisione di Umberto I"],
      essentials: ["Il caro pane fu una causa immediata delle proteste.", "A Milano fu impiegata anche l'artiglieria.", "Le cifre delle vittime non sono univoche.", "L'onorificenza a Bava Beccaris coinvolse simbolicamente la monarchia.", "Pelloux cercò di restringere diverse libertà pubbliche.", "Le opposizioni usarono l'ostruzionismo parlamentare.", "La Cassazione limitò l'efficacia del decreto non convertito.", "Le elezioni del 1900 non premiarono Pelloux.", "Bresci uccise Umberto I il 29 luglio 1900."],
      vocab: { Caro_pane: "Aumento del prezzo del pane e dei cereali, particolarmente grave per i bilanci popolari.", Commissario_straordinario: "Autorità investita di poteri eccezionali in una situazione di emergenza.", Ostruzionismo: "Uso intensivo delle procedure parlamentari per ritardare o impedire una decisione.", Decreto_legge: "Atto normativo del governo con efficacia immediata ma sottoposto, secondo l'ordinamento dell'epoca, al rapporto con l'approvazione parlamentare.", Regicidio: "Uccisione di un re." },
      answer: "La crisi divenne istituzionale quando l'emergenza sociale fu affrontata con strumenti militari e con il tentativo di rendere permanenti restrizioni delle libertà. Parlamento, magistratura ed elezioni impedirono che la stretta si stabilizzasse. Il regicidio mostrò però quanto profonda fosse diventata la frattura politica e simbolica.",
      connections: { map: "Milano, Monza e la geografia della crisi", people: ["bava", "pelloux", "bresci"] }
    },
    {
      id: "svolta-1901", number: 8, title: "Dalla repressione all'integrazione del conflitto", eyebrow: "Zanardelli-Giolitti e il bilancio di un'epoca", period: "1900-1901",
      question: "Perché il 1901 segna una svolta se monarchia, Statuto e struttura liberale dello Stato restano gli stessi?",
      lead: "Dopo il fallimento di Pelloux e il regicidio, Vittorio Emanuele III affidò nel febbraio 1901 il governo a Giuseppe Zanardelli, con Giolitti all'Interno. Il nuovo orientamento tentò di non identificare automaticamente sciopero, opposizione sociale e sovversione.",
      sections: [
        { title: "Saracco: un passaggio di stabilizzazione", paragraphs: ["Dopo Pelloux il governo Saracco evitò di riaprire immediatamente lo scontro sulle leggi eccezionali. Il regicidio del luglio 1900 avrebbe potuto produrre una nuova stretta, ma il sistema politico scelse una diversa direzione.", "Con Vittorio Emanuele III la Corona dovette anche ricostruire un rapporto meno esposto con le lotte parlamentari e sociali."], summary: "Il 1900 non portò automaticamente più repressione: aprì uno spazio di scelta politica." },
        { title: "Zanardelli e Giolitti", paragraphs: ["Nel febbraio 1901 Giuseppe Zanardelli divenne presidente del Consiglio e Giovanni Giolitti ministro dell'Interno. La nuova linea sosteneva che lo Stato non dovesse intervenire in ogni sciopero economico come forza al servizio dei proprietari.", "La neutralità non significava rinunciare all'ordine pubblico: violenze e reati restavano perseguibili. Cambiava però la soglia politica dell'intervento, con maggiore riconoscimento della legittimità delle organizzazioni sindacali e del conflitto del lavoro."], summary: "La svolta consiste nell'integrare il conflitto legale anziché trattarlo preventivamente come sovversione." },
        { title: "Crispi e Giolitti: due risposte al problema dello Stato", paragraphs: ["Crispi temeva che l'allargamento delle organizzazioni popolari indebolisse uno Stato nazionale ancora fragile; Giolitti pensava invece che la repressione automatica radicalizzasse il conflitto e delegittimasse le istituzioni.", "Entrambi volevano uno Stato capace di governare la modernizzazione. Differivano soprattutto su come costruire consenso e ordine: disciplina dall'alto per Crispi, integrazione e mediazione per Giolitti, almeno nella sua impostazione dichiarata."], summary: "La vera alternativa non è Stato forte o Stato debole, ma due modi diversi di produrre stabilità politica." },
        { title: "Bilancio di Crispi", paragraphs: ["Crispi contribuì alla modernizzazione amministrativa, sanitaria, penale e assistenziale dello Stato. Rafforzò però centralizzazione, prefetti e strumenti preventivi di polizia; nel 1894 usò stato d'assedio e leggi eccezionali contro movimenti popolari e socialisti.", "In politica estera cercò prestigio e potenza attraverso una più stretta collocazione nella Triplice Alleanza e l'espansione coloniale. Adua mostrò il limite politico e militare di quel progetto."], summary: "Modernizzazione e autorità sono entrambe parti costitutive del crispismo." },
        { title: "Bilancio della crisi di fine secolo", paragraphs: ["Il 1898-1900 dimostrò che la società italiana stava cambiando più rapidamente delle forme politiche create nell'età del notabilato. Sindacati, socialisti, radicali, cattolici organizzati, stampa di massa e conflitti urbani rendevano insufficiente una gestione fondata soltanto sui prefetti e sulla coercizione.", "La svolta del 1901 non trasformò l'Italia in una democrazia di massa: il suffragio restava limitato e le disuguaglianze profonde. Ma aprì una diversa stagione del liberalismo italiano, che avrebbe caratterizzato l'età giolittiana."], summary: "Lo Stato liberale sopravvisse alla crisi scegliendo, almeno temporaneamente, di allargare la propria capacità di integrazione." },
        { title: "Conclusione: il problema lasciato al Novecento", paragraphs: ["Il nodo storico non è stabilire se Crispi fosse 'buono' o 'cattivo'. È capire come uno Stato giovane affrontò simultaneamente modernizzazione, conflitto sociale, capitalismo, nazionalismo e imperialismo.", "La crisi di fine secolo consegna al Novecento una domanda ancora aperta: l'ordine politico si costruisce riducendo il conflitto o creando istituzioni capaci di rappresentarlo?"], summary: "Il passaggio al Novecento nasce dal fallimento di una risposta puramente coercitiva alla società organizzata." }
      ],
      source: { id: "giolitti-1901", title: "Giolitti e la neutralità nei conflitti del lavoro", prompt: "Distingui neutralità dello Stato, tutela dell'ordine pubblico e riconoscimento del conflitto sociale legale." },
      activity: { title: "Una tesi su tutto il modulo", prompt: "Rispondi alla domanda generale del percorso. Usa almeno una prova per ciascuna area: riforme, economia, conflitto sociale, colonialismo, crisi costituzionale. Inserisci un'obiezione alla tua tesi e confutala." },
      coordinates: ["Giugno 1900: fine del governo Pelloux", "29 luglio 1900: regicidio", "1900-1901: governo Saracco", "Febbraio 1901: governo Zanardelli", "1901: Giolitti ministro dell'Interno", "Dal 1901: apertura della fase liberale giolittiana"],
      essentials: ["Il fallimento di Pelloux precede il regicidio.", "Il regicidio non provocò una nuova svolta autoritaria permanente.", "Zanardelli divenne presidente del Consiglio nel 1901.", "Giolitti tornò all'Interno con una linea più neutrale nei conflitti economici.", "Crispi e Giolitti cercavano entrambi stabilità, ma con strategie differenti.", "Il crispismo produsse importanti riforme e forte centralizzazione.", "Adua chiuse la carriera politica di Crispi.", "La crisi di fine secolo preparò il passaggio all'età giolittiana."],
      vocab: { Neutralita_dello_Stato: "Principio per cui l'autorità pubblica non deve schierarsi automaticamente con una parte in un conflitto economico legale.", Integrazione: "Inclusione di nuovi gruppi e organizzazioni nel funzionamento politico e istituzionale.", Societa_di_massa: "Società caratterizzata da organizzazioni collettive, comunicazione diffusa, grandi aggregati urbani e partecipazione politica più ampia.", Liberalismo: "Tradizione politica fondata su diritti individuali, rappresentanza, limiti al potere e legalità costituzionale, storicamente declinata in forme diverse.", Eta_giolittiana: "Fase della storia italiana dei primi del Novecento segnata dalla centralità politica di Giovanni Giolitti." },
      answer: "Il 1901 fu una svolta perché cambiò il modo in cui il governo interpretava il conflitto sociale: non più automaticamente come minaccia da reprimere, ma come fenomeno che, entro la legalità, poteva essere mediato e integrato. Le istituzioni fondamentali restarono, ma mutò la strategia con cui cercavano consenso e stabilità.",
      connections: { map: "Dalla crisi alla nuova fase politica", people: ["zanardelli", "giolitti", "crispi"] }
    }
  ],
  people: [
    { id: "crispi", name: "Francesco Crispi", dates: "1818-1901", role: "Presidente del Consiglio, protagonista del Risorgimento e del crispismo", image: "../Sinistra-storica/assets/img/people/crispi.jpg", imageAlt: "Ritratto storico di Francesco Crispi", bio: "Mazziniano e garibaldino, accettò dopo l'Unità la monarchia come quadro della nazione. Presidente del Consiglio nel 1887-1891 e 1893-1896, guidò una vasta opera di riforma amministrativa, una forte centralizzazione e una politica coloniale culminata ad Adua.", idea: "Modernizzare lo Stato rafforzandone contemporaneamente autorità, amministrazione e prestigio internazionale." },
    { id: "zanardelli", name: "Giuseppe Zanardelli", dates: "1826-1903", role: "Giurista liberale, ministro della Giustizia e presidente del Consiglio", image: "assets/img/people/zanardelli.svg", imageAlt: "Scheda grafica dedicata a Giuseppe Zanardelli", bio: "Esponente della Sinistra liberale, legò il proprio nome al codice penale del 1889 che abolì la pena di morte per i reati comuni. Nel 1901 guidò il governo della svolta liberale con Giolitti all'Interno.", idea: "La legalità liberale può rafforzare lo Stato riducendo l'arbitrio punitivo e ampliando garanzie." },
    { id: "giolitti", name: "Giovanni Giolitti", dates: "1842-1928", role: "Presidente del Consiglio nel 1892-1893; ministro dell'Interno nel 1901", image: "assets/img/people/giolitti.svg", imageAlt: "Scheda grafica dedicata a Giovanni Giolitti", bio: "Funzionario e politico piemontese, nel primo governo cercò di distinguere sciopero economico e insurrezione. Travolto dallo scandalo della Banca Romana, tornò nel 1901 come ministro dell'Interno con una linea più neutrale nei conflitti del lavoro.", idea: "La stabilità può crescere integrando il conflitto legale invece di reprimerlo automaticamente." },
    { id: "colajanni", name: "Napoleone Colajanni", dates: "1847-1921", role: "Deputato repubblicano e denunciante dello scandalo della Banca Romana", image: "assets/img/people/colajanni.svg", imageAlt: "Scheda grafica dedicata a Napoleone Colajanni", bio: "Medico, garibaldino, studioso e parlamentare siciliano. Nel dicembre 1892 portò alla Camera i risultati dell'ispezione sulla Banca Romana, contribuendo a trasformare una crisi finanziaria in grande questione politica.", idea: "Il controllo parlamentare e la pubblicità degli atti possono rompere intrecci opachi fra finanza e potere." },
    { id: "menelik", name: "Menelik II", dates: "1844-1913", role: "Imperatore d'Etiopia", image: "assets/img/people/menelik.svg", imageAlt: "Scheda grafica dedicata a Menelik II", bio: "Re dello Scioa e poi imperatore, consolidò alleanze regionali, acquistò armi moderne e difese la sovranità etiopica contro la pretesa italiana di protettorato. Guidò il sistema politico che sconfisse l'Italia ad Adua.", idea: "L'Etiopia agisce come soggetto politico e diplomatico, non come oggetto passivo dell'espansione europea." },
    { id: "baratieri", name: "Oreste Baratieri", dates: "1841-1901", role: "Generale e governatore dell'Eritrea", image: "assets/img/people/baratieri.svg", imageAlt: "Scheda grafica dedicata a Oreste Baratieri", bio: "Veterano garibaldino, guidò le forze italiane in Eritrea. Sottoposto a pressioni politiche per ottenere un risultato decisivo, ordinò l'avanzata che precedette la sconfitta di Adua.", idea: "Le decisioni militari dipendono anche da obiettivi politici, informazioni disponibili e vincoli logistici." },
    { id: "bava", name: "Fiorenzo Bava Beccaris", dates: "1831-1924", role: "Generale e commissario straordinario a Milano nel 1898", image: "assets/img/people/bava.svg", imageAlt: "Scheda grafica dedicata a Fiorenzo Bava Beccaris", bio: "Comandante del III Corpo d'armata, ricevette pieni poteri durante i tumulti milanesi del maggio 1898 e impiegò duramente esercito e artiglieria. L'onorificenza ricevuta da Umberto I rese il suo nome simbolo della repressione.", idea: "L'emergenza può spostare il confine tra ordine pubblico, potere militare e legalità civile." },
    { id: "pelloux", name: "Luigi Pelloux", dates: "1839-1924", role: "Presidente del Consiglio 1898-1900", image: "assets/img/people/pelloux.svg", imageAlt: "Scheda grafica dedicata a Luigi Pelloux", bio: "Generale e politico, guidò due governi dopo i moti del 1898. Tentò di rendere più restrittiva la disciplina di stampa, riunione, associazione e sciopero, ma fu fermato dall'opposizione parlamentare, dalla Cassazione e dalle elezioni del 1900.", idea: "Rafforzare l'esecutivo restringendo libertà può produrre una crisi di legittimità anziché stabilità." },
    { id: "bresci", name: "Gaetano Bresci", dates: "1869-1901", role: "Operaio anarchico, autore del regicidio del 1900", image: "assets/img/people/bresci.svg", imageAlt: "Scheda grafica dedicata a Gaetano Bresci", bio: "Emigrato negli Stati Uniti e vicino agli ambienti anarchici di Paterson, rientrò in Italia e uccise Umberto I a Monza il 29 luglio 1900. Fu condannato all'ergastolo e morì in carcere nel 1901.", idea: "Il regicidio fu un'azione individuale dentro una radicalizzazione politica più ampia, non il piano unitario delle opposizioni." }
  ],
  timeline: [
    { date: "1887", title: "Crispi al governo e tariffa protezionistica", text: "La morte di Depretis apre la prima fase crispina; la nuova tariffa rafforza la svolta protezionistica.", scale: "Italia" },
    { date: "1888", title: "Riforme e guerra doganale", text: "Riforma comunale-provinciale, sanità e pubblica sicurezza; il conflitto commerciale con la Francia colpisce le esportazioni.", scale: "Italia/Europa" },
    { date: "1889", title: "Codice Zanardelli e Uccialli", text: "Il nuovo codice penale abolisce la pena di morte; il trattato con Menelik apre la disputa sulla sovranità etiopica.", scale: "Italia/Africa" },
    { date: "1890", title: "Colonia Eritrea e opere pie", text: "Lo Stato proclama l'Eritrea e amplia il controllo pubblico sull'assistenza.", scale: "Italia/Africa" },
    { date: "1891", title: "Caduta del primo Crispi", text: "Il governo perde sostegno parlamentare; segue il breve governo di Rudinì.", scale: "Italia" },
    { date: "1892", title: "Giolitti e Banca Romana", text: "Giolitti arriva alla presidenza; Colajanni rende pubblico lo scandalo bancario.", scale: "Italia" },
    { date: "1893", title: "Riforma bancaria e crisi siciliana", text: "Nasce la Banca d'Italia; Giolitti cade; Crispi torna al governo.", scale: "Italia/Sicilia" },
    { date: "3 gennaio 1894", title: "Stato d'assedio in Sicilia", text: "Esercito, scioglimento dei Fasci e tribunali militari segnano la nuova linea dell'ordine pubblico.", scale: "Sicilia" },
    { date: "1895", title: "La guerra d'Etiopia si allarga", text: "Amba Alagi mostra la capacità militare etiopica e aumenta la pressione politica per una vittoria italiana.", scale: "Africa" },
    { date: "1 marzo 1896", title: "Adua", text: "L'esercito di Menelik sconfigge le forze italiane; Crispi si dimette.", scale: "Africa/Italia" },
    { date: "1898", title: "Caro pane e repressione", text: "Moti in varie città; a Milano Bava Beccaris impiega anche l'artiglieria.", scale: "Italia" },
    { date: "1899", title: "Pelloux e ostruzionismo", text: "I provvedimenti restrittivi sulle libertà producono una lunga crisi parlamentare.", scale: "Italia" },
    { date: "1900", title: "Cassazione, elezioni e regicidio", text: "La stretta di Pelloux fallisce; Umberto I viene ucciso da Gaetano Bresci.", scale: "Italia" },
    { date: "1901", title: "Zanardelli-Giolitti", text: "Si apre una fase più liberale nella gestione delle organizzazioni e dei conflitti del lavoro.", scale: "Italia" }
  ],
  maps: [
    { title: "Italia: centri e fratture della crisi", image: "assets/img/maps/italia-crisi.svg", alt: "Carta schematica dell'Italia con Sicilia, Roma, Milano e Monza", text: "La crisi non ha un solo centro: Sicilia per i Fasci, Roma per banca e Parlamento, Milano per il 1898, Monza per il regicidio.", note: "Schema concettuale, non carta in scala." },
    { title: "Sicilia dei Fasci", image: "assets/img/maps/sicilia-fasci.svg", alt: "Carta schematica della Sicilia con aree dei Fasci e delle miniere di zolfo", text: "Campagne, città e distretti minerari produssero forme diverse di organizzazione popolare.", note: "La diffusione è indicativa e non rappresenta tutti i Fasci esistiti." },
    { title: "Mar Rosso, Eritrea ed Etiopia", image: "assets/img/maps/africa-orientale.svg", alt: "Carta schematica del Mar Rosso, Eritrea, Etiopia, Massaua, Assab, Addis Abeba e Adua", text: "Leggi la guerra come relazione tra basi costiere italiane, altopiano eritreo e centro politico etiopico.", note: "Schema didattico, non adatto a misurazioni territoriali." }
  ],
  sources: [
    { id: "crispi-biografia", type: "Storiografia", date: "Dizionario biografico", title: "Francesco Crispi: biografia politica", author: "Dizionario Biografico degli Italiani", provenance: "Istituto della Enciclopedia Italiana", verbatim: false, excerpt: ["La biografia mostra il passaggio dalla democrazia risorgimentale a un progetto di Stato nazionale forte.", "Le riforme amministrative crispine combinano ampliamento della partecipazione locale e nuovi strumenti di controllo centrale."], context: "Profilo storico di lungo periodo, utile per evitare spiegazioni esclusivamente psicologiche.", audience: "Lettori e studiosi", purpose: "Ricostruire criticamente la carriera politica e il contesto.", limits: "Una biografia organizza eventi attorno a una persona e va integrata con storia sociale ed economica.", interpretation: "Usa la biografia per individuare continuità e cambiamenti, non per trasformare Crispi nell'unica causa degli eventi.", questions: ["Quale idea di nazione resta costante?", "Quali scelte cambiano dopo l'Unità?", "Dove compaiono insieme riforma e centralizzazione?"], url: "https://www.treccani.it/enciclopedia/francesco-crispi_%28Dizionario-Biografico%29/" },
    { id: "riforme-1888", type: "Atti parlamentari", date: "1888-1890", title: "Riforme amministrative, penali e sanitarie", author: "Senato del Regno d'Italia", provenance: "Senato della Repubblica - archivio storico", verbatim: false, excerpt: ["La riforma comunale e provinciale ampliò l'elettorato amministrativo.", "Il nuovo codice penale abolì la pena di morte; sanità, pubblica sicurezza e giustizia amministrativa furono riorganizzate."], context: "Sintesi legislativa della XVI legislatura del Regno.", audience: "Cittadini e ricercatori", purpose: "Documentare l'attività normativa del Parlamento.", limits: "La cronologia legislativa non misura automaticamente gli effetti sociali delle leggi.", interpretation: "Confronta sempre norma, capacità amministrativa e uso politico concreto.", questions: ["Quali riforme ampliano diritti?", "Quali aumentano la capacità dello Stato?", "Perché le due funzioni possono coesistere?"], url: "https://www.senato.it/legislature/regno/italia/16/resoconti-volumi-e-indici" },
    { id: "tariffa-francia", type: "Storia economica", date: "1887-1898", title: "Protezionismo e guerra commerciale", author: "Senato del Regno / storiografia economica", provenance: "Senato della Repubblica e bibliografia del modulo", verbatim: false, excerpt: ["La tariffa del 1887 rispose alla crisi agraria e alla richiesta di protezione industriale.", "Il conflitto doganale con la Francia durò fino alla normalizzazione del 1898."], context: "Politica economica in una fase di crisi agricola internazionale e crescita industriale selettiva.", audience: "Lettori e studenti", purpose: "Collegare dazi, gruppi di interesse e rapporti internazionali.", limits: "Le tariffe non spiegano da sole l'intera crisi economica.", interpretation: "Scomponi l'espressione interesse nazionale in gruppi, prodotti e territori.", questions: ["Chi guadagna dalla protezione del grano?", "Chi perde dal conflitto con la Francia?", "Quali altre cause della crisi vanno considerate?"], url: "https://www.senato.it/legislature/regno/italia/16/resoconti-volumi-e-indici" },
    { id: "banca-italia-1893", type: "Storia istituzionale", date: "1892-1894", title: "Dalla Banca Romana alla Banca d'Italia", author: "Banca d'Italia", provenance: "Sezione Storia della Banca d'Italia", verbatim: false, excerpt: ["Lo scandalo della Banca Romana rese pubbliche gravi irregolarità negli istituti di emissione.", "La legge del 1893 istituì la Banca d'Italia e ridisegnò le regole della circolazione."], context: "Ricostruzione istituzionale della crisi bancaria dei primi anni Novanta.", audience: "Cittadini, studenti e ricercatori", purpose: "Spiegare la nascita e l'evoluzione dell'istituto centrale.", limits: "La prospettiva istituzionale va integrata con storia politica e giudiziaria.", interpretation: "Distingui gli illeciti della Banca Romana dalla successiva riforma del sistema.", questions: ["Perché l'ispezione del 1889 divenne un problema politico?", "Che cosa cambiò con la legge del 1893?", "Perché non esisteva ancora un monopolio pieno dell'emissione?"], url: "https://www.bancaditalia.it/chi-siamo/storia/origini/index.html" },
    { id: "fasci-documenti", type: "Storiografia sociale", date: "1891-1894", title: "Fasci siciliani", author: "Dizionario di Storia", provenance: "Istituto della Enciclopedia Italiana", verbatim: false, excerpt: ["Il movimento coinvolse contadini, artigiani e minatori e assunse una forte impronta socialista.", "La repressione crispina del 1894 seguì una fase di scioperi, conflitti e grave disagio sociale."], context: "Movimento popolare nella Sicilia della crisi agraria e dei conflitti locali.", audience: "Lettori e studenti", purpose: "Fornire una sintesi storica del movimento.", limits: "Una voce sintetica non restituisce tutte le differenze locali né il dibattito storiografico.", interpretation: "Non usare la parola insurrezione come etichetta per ogni associazione o ogni partecipante.", questions: ["Chi aderiva ai Fasci?", "Quali richieste economiche emergevano?", "Come cambia la politica statale tra Giolitti e Crispi?"], url: "https://www.treccani.it/enciclopedia/fasci-siciliani_%28Dizionario-di-Storia%29/" },
    { id: "uccialli-art17", type: "Ricerca accademica", date: "1889-1896", title: "L'articolo 17 del trattato di Uccialli", author: "Sven Rubenson e Carlo Giglio", provenance: "The Journal of African History, Cambridge University Press", verbatim: false, excerpt: ["Le versioni italiana e amarica dell'articolo 17 non coincidevano sulla natura dell'obbligo diplomatico.", "Il dibattito storiografico riguarda anche intenzioni e responsabilità, ma la controversia sulla sovranità etiopica è indiscutibile."], context: "Dibattito accademico sul testo che l'Italia usò per sostenere la pretesa di protettorato.", audience: "Storici e studiosi di storia africana", purpose: "Ricostruire filologicamente e diplomaticamente l'origine della controversia.", limits: "Gli articoli discutono in modo specialistico questioni interpretative e non riassumono l'intera guerra.", interpretation: "Mostra agli studenti che anche una fonte diplomatica può produrre interpretazioni storiografiche divergenti.", questions: ["Che cosa cambia tra obbligo e possibilità?", "Perché il termine protettorato riguarda la sovranità?", "Quali aspetti del dibattito restano aperti?"], url: "https://www.cambridge.org/core/journals/journal-of-african-history/article/abs/protectorate-paragraph-of-the-wichale-treaty/A3D4433C066D6FDA30C9F5D29482B0A8" },
    { id: "adua-storiografia", type: "Ricerca accademica", date: "1896 e memoria", title: "Adua: dal monumento al documento", author: "Alessandro Triulzi", provenance: "Modern Italy, Cambridge University Press", verbatim: false, excerpt: ["Adua è stata trasformata da diverse tradizioni nazionali in simbolo di sconfitta, vittoria, indipendenza o decadenza.", "Lo storico deve ricondurre il simbolo ai documenti e alle molte prospettive del conflitto."], context: "Riflessione storiografica sul modo in cui Italia ed Etiopia hanno ricordato Adua.", audience: "Storici contemporaneisti", purpose: "Criticare letture nazionali troppo rigide dell'evento.", limits: "La memoria non sostituisce la ricostruzione militare e diplomatica della battaglia.", interpretation: "Usa Adua per distinguere evento storico, memoria pubblica e mito nazionale.", questions: ["Quali significati assume Adua in Italia?", "Quali in Etiopia?", "Perché una vittoria anticoloniale può avere anche una storia interna etiopica complessa?"], url: "https://www.cambridge.org/core/journals/modern-italy/article/adwa-from-monument-to-document/BB83701D64D546BBD9717FC998CB08A6" },
    { id: "camera-pelloux", type: "Storia parlamentare", date: "1898-1900", title: "La crisi parlamentare e l'ostruzionismo", author: "Camera dei deputati", provenance: "Biblioteca e Portale storico della Camera", verbatim: false, excerpt: ["La crisi di fine secolo divise profondamente il Parlamento sulla restrizione delle libertà pubbliche.", "L'ostruzionismo divenne uno strumento con cui le opposizioni impedirono la stabilizzazione dei provvedimenti governativi."], context: "Ricostruzione istituzionale della XX legislatura.", audience: "Ricercatori e cittadini", purpose: "Documentare l'evoluzione del regolamento e dello scontro parlamentare.", limits: "La prospettiva parlamentare non esaurisce la storia sociale dei moti del 1898.", interpretation: "Leggi l'ostruzionismo non soltanto come tecnica, ma come parte del conflitto sulla natura del regime liberale.", questions: ["Quali libertà erano in discussione?", "Perché la procedura divenne politica sostanziale?", "Che ruolo ebbero elezioni e Cassazione?"], url: "https://bpr.camera.it/bpr/allegati/show/11168_1634_t" },
    { id: "giolitti-1901", type: "Sintesi storiografica", date: "1901", title: "La svolta liberale", author: "Storiografia sull'Italia liberale", provenance: "Bibliografia accademica del modulo", verbatim: false, excerpt: ["Dal 1901 il governo cercò di distinguere conflitti economici legali da minacce all'ordine pubblico.", "La neutralità dello Stato non eliminava la coercizione, ma ne spostava la soglia di intervento."], context: "Passaggio dalla crisi di fine secolo all'età giolittiana.", audience: "Studenti e lettori", purpose: "Confrontare due strategie di stabilizzazione dello Stato liberale.", limits: "La svolta del 1901 non abolì disuguaglianze, repressioni locali o limiti del suffragio.", interpretation: "Evita di trasformare Giolitti nel contrario perfetto di Crispi: confronta strumenti e soglie di intervento.", questions: ["Che cosa significa neutralità?", "Quali conflitti restano perseguibili?", "Perché il 1901 è una svolta pur nella continuità istituzionale?"], url: "https://www.treccani.it/enciclopedia/italia_%28Dizionario-di-Storia%29/" }
  ],
  workshop: [
    { title: "Quale modernizzazione?", prompt: "Scegli la formulazione più precisa.", options: ["Le riforme annullano il carattere autoritario del crispismo.", "Modernizzazione amministrativa e controllo politico possono crescere insieme.", "La modernizzazione riguarda soltanto l'economia."] },
    { title: "Quale causa della crisi?", prompt: "Come va spiegata la crisi economica e sociale?", options: ["Con una sola causa: la guerra doganale.", "Come intreccio di crisi agraria, finanza, commercio, prezzi e conflitti sociali.", "Come conseguenza esclusiva della politica coloniale."] },
    { title: "Come leggere i Fasci?", prompt: "Quale criterio evita l'anacronismo?", options: ["Identificarli con il fascismo del Novecento.", "Distinguere composizione sociale, rivendicazioni, direzioni politiche ed episodi di violenza.", "Considerarli un unico esercito rivoluzionario centralizzato."] },
    { title: "Come leggere Adua?", prompt: "Quale prospettiva è storicamente più completa?", options: ["Solo gli errori italiani.", "Solo l'eroismo etiopico.", "Decisioni italiane, strategia etiopica, sovranità, diplomazia e memoria dell'evento."] },
    { title: "Che cosa fallisce nel 1900?", prompt: "Individua il nodo istituzionale.", options: ["Il Parlamento come istituzione.", "Il tentativo di stabilizzare l'emergenza restringendo durevolmente le libertà.", "La monarchia come forma costituzionale viene abolita."] }
  ],
  quiz: [
    { q: "Quale elemento collega il Crispi risorgimentale al Crispi presidente del Consiglio?", options: ["Il rifiuto permanente della monarchia", "La centralità attribuita alla costruzione della nazione", "L'opposizione a ogni esercito permanente", "Il liberismo economico assoluto"], answer: 1, why: "Cambia il quadro istituzionale accettato, ma resta centrale l'idea di nazione da costruire e rafforzare.", recover: "Rivedi la traiettoria dal repubblicanesimo alla statualità.", lesson: "crispi-uomo-stato" },
    { q: "Che cosa rende complesso il giudizio sulle riforme del 1888-1890?", options: ["Non produssero alcuna legge importante", "Ampliarono garanzie e partecipazione ma rafforzarono anche il controllo amministrativo", "Abolirono i prefetti", "Trasformarono l'Italia in una repubblica"], answer: 1, why: "Il nucleo del crispismo è proprio la coesistenza di modernizzazione e autorità.", recover: "Confronta comune-provincia, Codice Zanardelli e pubblica sicurezza.", lesson: "riforme-autorita" },
    { q: "Quale affermazione sul Codice Zanardelli è corretta?", options: ["Reintrodusse la pena di morte", "Abolì la pena di morte per i reati comuni", "Vietò ogni sciopero", "Fu promulgato da Giolitti nel 1901"], answer: 1, why: "Il codice del 1889 abolì la pena di morte per i reati comuni e segnò una svolta garantista.", recover: "Rivedi la sezione sul Codice Zanardelli.", lesson: "riforme-autorita" },
    { q: "Perché la tariffa del 1887 produsse effetti sociali diversi?", options: ["Perché ogni settore pagava lo stesso prezzo", "Perché produttori protetti, esportatori e consumatori avevano interessi diversi", "Perché riguardava solo la Francia", "Perché eliminò tutti i dazi"], answer: 1, why: "La stessa barriera può proteggere un produttore e aumentare i costi di un consumatore o provocare ritorsioni contro un esportatore.", recover: "Rivedi i gruppi favoriti e penalizzati.", lesson: "protezionismo-crisi" },
    { q: "Che cosa mostrò soprattutto lo scandalo della Banca Romana?", options: ["Che l'Italia aveva già una banca centrale unica", "L'intreccio fra credito, speculazione, politica e controlli insufficienti", "Che la moneta cartacea non esisteva", "Che Tanlongo era presidente del Consiglio"], answer: 1, why: "Lo scandalo fu sistemico: riguardava il funzionamento degli istituti di emissione e i rapporti con la politica.", recover: "Rivedi ispezione, Colajanni e legge del 1893.", lesson: "banca-romana" },
    { q: "Quale istituzione nacque con la legge del 10 agosto 1893?", options: ["La Banca Commerciale Italiana", "La Banca d'Italia", "La Cassa per il Mezzogiorno", "La Banca Centrale Europea"], answer: 1, why: "La legge n. 449 del 1893 istituì la Banca d'Italia mediante fusione di tre istituti.", recover: "Rivedi la riforma bancaria.", lesson: "banca-romana" },
    { q: "Che cosa indica il termine Fasci siciliani in questo contesto?", options: ["Il Partito Nazionale Fascista", "Associazioni popolari e del lavoro dell'ultimo Ottocento", "Reparti dell'esercito coloniale", "Un'organizzazione segreta monarchica"], answer: 1, why: "Fascio significava unione o associazione e non va anacronisticamente collegato al fascismo novecentesco.", recover: "Rivedi l'apertura della lezione sui Fasci.", lesson: "fasci-siciliani" },
    { q: "Quale differenza separa la linea iniziale di Giolitti da quella di Crispi sui Fasci?", options: ["Giolitti voleva abolire lo Stato", "Giolitti cercava di distinguere sciopero economico e insurrezione; Crispi ricorse allo stato d'assedio", "Crispi abolì l'esercito", "Non vi era alcuna differenza"], answer: 1, why: "Il problema era la soglia dell'intervento coercitivo dello Stato.", recover: "Confronta le due risposte all'ordine pubblico.", lesson: "fasci-siciliani" },
    { q: "Perché l'articolo 17 di Uccialli fu decisivo?", options: ["Definiva il prezzo del grano", "Le versioni italiana e amarica implicavano rapporti diversi con la sovranità etiopica", "Aboliva la colonia Eritrea", "Stabiliva la neutralità francese"], answer: 1, why: "La differenza tra obbligo e facoltà nell'uso della mediazione italiana investiva direttamente l'autonomia internazionale di Menelik.", recover: "Rivedi Uccialli e il problema del protettorato.", lesson: "etiopia-adua" },
    { q: "Quale lettura di Adua è più corretta?", options: ["Solo superiorità numerica etiopica", "Solo incapacità individuale di Baratieri", "Intreccio di progetto coloniale, pressioni politiche, problemi operativi e capacità etiopica", "Evento privo di conseguenze politiche"], answer: 2, why: "Una spiegazione storica deve tenere insieme strategia etiopica e responsabilità politico-militari italiane.", recover: "Rivedi le cause della battaglia e il punto di vista etiopico.", lesson: "etiopia-adua" },
    { q: "Che cosa rende il 1898 una crisi politica oltre che sociale?", options: ["La completa assenza dello Stato", "L'uso dell'esercito, la repressione politica e il coinvolgimento simbolico della monarchia", "La fine del Parlamento", "L'abolizione del prezzo del pane"], answer: 1, why: "Milano mise in discussione il rapporto fra forza militare, diritti e responsabilità della Corona.", recover: "Rivedi Bava Beccaris e l'onorificenza reale.", lesson: "crisi-1898" },
    { q: "A che cosa servì l'ostruzionismo contro Pelloux?", options: ["A velocizzare il voto", "A impedire o rallentare provvedimenti restrittivi delle libertà", "A sciogliere automaticamente la monarchia", "A creare la Banca d'Italia"], answer: 1, why: "Le opposizioni usarono le procedure parlamentari come strumento di resistenza sostanziale.", recover: "Rivedi la battaglia parlamentare del 1899-1900.", lesson: "crisi-1898" },
    { q: "Quale istituzione limitò l'efficacia del decreto Pelloux non convertito?", options: ["La Corte di cassazione", "Il Vaticano", "La Banca d'Italia", "Il comune di Milano"], answer: 0, why: "La Cassazione dichiarò inapplicabile il decreto dopo la chiusura della sessione senza conversione.", recover: "Rivedi il rapporto tra governo, Parlamento e magistratura.", lesson: "crisi-1898" },
    { q: "Che cosa cambia soprattutto con Zanardelli-Giolitti nel 1901?", options: ["L'Italia diventa repubblica", "Lo Stato tende a non identificare automaticamente il conflitto economico legale con la sovversione", "Viene abolito il Parlamento", "Finisce il suffragio"], answer: 1, why: "La svolta riguarda la strategia di integrazione del conflitto, non la forma costituzionale dello Stato.", recover: "Rivedi la neutralità nei conflitti del lavoro.", lesson: "svolta-1901" },
    { q: "Qual è il miglior bilancio del crispismo?", options: ["Solo modernizzazione", "Solo repressione", "Modernizzazione istituzionale insieme a centralizzazione, repressione e politica coloniale", "Nessun cambiamento significativo"], answer: 2, why: "Ridurre Crispi a una sola dimensione impedisce di capire il periodo.", recover: "Rivedi la lezione conclusiva e confronta le aree del bilancio.", lesson: "svolta-1901" }
  ]
};
