window.HIST_DATA = {
  meta: {
    title: "L'Unità d'Italia",
    shortTitle: "Unità d'Italia",
    storageKey: "storia-unita-v1",
    question: "Come fu possibile unificare l'Italia tra il 1849 e il 1870, e perché lo Stato nato dall'unificazione non coincise pienamente con la nazione immaginata dai diversi progetti risorgimentali?",
    thesis: "L'unificazione non fu l'esecuzione di un piano già pronto. Nacque dall'interazione contingente fra monarchia sabauda, Parlamento, diplomazia francese, guerre, reti patriottiche, rivoluzioni locali, iniziativa garibaldina e crisi degli Stati preunitari. Il nuovo Regno estese istituzioni piemontesi a territori differenti, costruendo cittadinanza e amministrazione ma anche esclusioni, resistenze e conflitti.",
    workshopIntro: "Costruisci una spiegazione che distingua condizioni, occasioni, decisioni e risultati imprevisti. Usa almeno una carta e due fonti; indica anche un'alternativa allora possibile e una categoria sociale rimasta ai margini del voto.",
    previous: { title: "Rivoluzioni del 1848-1849", url: "../1849/" },
    next: { title: "Italia postunitaria - tappa futura", url: "#" }
  },
  lessons: [
    {
      id: "piemonte-laboratorio", number: 1, title: "Dopo il 1849: reazione e laboratorio piemontese", eyebrow: "Una costituzione sopravvive", period: "1849-1852",
      question: "Perché, dopo la sconfitta, proprio il Regno di Sardegna divenne il principale laboratorio politico del movimento nazionale?",
      lead: "La seconda Restaurazione colpì opposizioni e costituzioni in quasi tutta la penisola. In Piemonte, invece, lo Statuto Albertino restò in vigore: non per automatica vocazione democratica, ma per un equilibrio conflittuale fra Corona, Parlamento, moderati e opinione pubblica.",
      sections: [
        { title: "Il mondo precedente: una sconfitta non uniforme", paragraphs: ["Nel 1849 l'Austria ristabilì la propria influenza nell'Italia centro-settentrionale; Pio IX tornò a Roma con protezione francese; Ferdinando II represse l'opposizione nel Regno delle Due Sicilie; Leopoldo II rientrò in Toscana grazie alle armi austriache. Esuli, censura e processi ridussero gli spazi politici.", "Il Piemonte aveva perso a Novara, Carlo Alberto aveva abdicato e il nuovo re Vittorio Emanuele II doveva concludere la pace. Nulla garantiva che lo Statuto del 1848 sarebbe sopravvissuto."], summary: "La reazione fu generale, ma il suo esito dipese dalle istituzioni e dai rapporti di forza di ciascuno Stato." },
        { title: "Le fratture: Moncalieri e la sopravvivenza dello Statuto", paragraphs: ["La Camera eletta nel luglio 1849 esitò ad approvare il trattato con l'Austria. Il re la sciolse e il proclama di Moncalieri del 20 novembre invitò gli elettori a scegliere deputati disposti a ratificare la pace. Le nuove elezioni produssero una maggioranza moderata.", "Lo Statuto sopravvisse, ma la crisi mostrò quanto fossero ancora ampie le prerogative della Corona: il re nominava i ministri, scioglieva la Camera e controllava in larga misura politica estera ed esercito."], summary: "La continuità costituzionale nacque da un compromesso asimmetrico, non da una monarchia già pienamente parlamentare." },
        { title: "Attori e conflitti: Stato, Chiesa e maggioranze", paragraphs: ["Il governo d'Azeglio approvò nel 1850 le leggi Siccardi, che abolirono foro ecclesiastico, diritto d'asilo e altre prerogative. La scelta affermava la competenza dello Stato civile e apriva un conflitto con la Santa Sede.", "Cavour, ministro dell'Agricoltura, del Commercio e della Marina, si avvicinò alla sinistra moderata di Urbano Rattazzi. Il connubio del 1852 isolò destra clericale e democratici radicali e rese il centro parlamentare decisivo."], summary: "La modernizzazione politica fu anche una lotta su chi dovesse governare e su quali limiti avesse l'autorità ecclesiastica." },
        { title: "Il processo: dal ministero al governo Cavour", paragraphs: ["La crisi sul matrimonio civile divise d'Azeglio, il Senato e il sovrano. Dopo tentativi falliti di formare un gabinetto conservatore, Vittorio Emanuele II affidò il governo a Cavour nel novembre 1852.", "Cavour non possedeva nel 1852 un piano immutabile per unificare l'intera penisola. Mirava soprattutto a rafforzare e ampliare il Regno di Sardegna, sottraendo l'Italia settentrionale al predominio austriaco e impedendo che il malcontento alimentasse rivoluzioni repubblicane."], summary: "Il Piemonte divenne un laboratorio perché conservò istituzioni rappresentative e seppe attrarre esuli, capitali e progetti diversi." },
        { title: "Nodo interpretativo: eccezione liberale o espansione dinastica?", paragraphs: ["La lettura liberale sottolinea Parlamento, stampa e riforme; una lettura critica osserva il peso della Corona, il suffragio ristretto e l'uso governativo delle elezioni. Entrambe colgono aspetti reali.", "Il futuro Regno d'Italia erediterà questa ambivalenza: costituzione e rappresentanza, ma anche continuità dinastica e forti poteri esecutivi."], summary: "Il Piemonte fu insieme Stato costituzionale e monarchia espansiva." }
      ],
      source: { id: "statuto", title: "Statuto Albertino: il testo e la prassi", prompt: "Distingui ciò che la carta attribuisce al re da ciò che la prassi parlamentare cominciò a modificare." },
      activity: { title: "Mappa dei poteri", prompt: "Distribuisci cinque poteri - nomina dei ministri, leggi, bilancio, guerra, scioglimento della Camera - fra re, Camera e Senato. Indica dove il testo lascia spazio al conflitto." },
      coordinates: ["Torino e Moncalieri", "6 agosto e 20 novembre 1849", "Leggi Siccardi, 1850", "Connubio, febbraio 1852", "Governo Cavour, novembre 1852"],
      essentials: ["La seconda Restaurazione ebbe forme diverse nei vari Stati.", "Lo Statuto rimase in vigore in Piemonte.", "Moncalieri fu una pressione regia sugli elettori.", "Le leggi Siccardi ridefinirono i rapporti fra Stato e Chiesa.", "Il connubio costruì una maggioranza di centro.", "Cavour non partì con un piano completo di unità nazionale."],
      vocab: { Statuto: "Carta costituzionale concessa dal sovrano e modificabile con legge ordinaria.", Prerogativa_regia: "Potere attribuito direttamente alla Corona.", Connubio: "Accordo parlamentare tra il centro-destra di Cavour e il centro-sinistra di Rattazzi.", Laicizzazione: "Trasferimento di funzioni e autorità dall'ambito ecclesiastico a quello civile.", Seconda_Restaurazione: "Ripresa della repressione negli Stati italiani dopo il 1848-1849." },
      answer: "Il Piemonte divenne il principale laboratorio nazionale perché conservò lo Statuto, una vita parlamentare e una stampa relativamente libera. La monarchia non rinunciò però ai propri poteri: l'eccezione piemontese fu un equilibrio, non una democrazia compiuta."
    },
    {
      id: "piemonte-europa", number: 2, title: "Modernizzare il Piemonte, entrare in Europa", eyebrow: "Ferrovie, bilanci e diplomazia", period: "1852-1858",
      question: "Come poterono riforme economiche e una guerra lontana trasformare il peso politico del Piemonte?",
      lead: "La politica cavouriana collegò mercato, infrastrutture, credito e prestigio internazionale. I risultati non furono lineari: produssero crescita e debito, consolidarono il governo e aprirono nuove crisi con la Corona e la Chiesa.",
      sections: [
        { title: "Il mondo precedente: uno Stato medio nella periferia delle potenze", paragraphs: ["Il Regno di Sardegna non poteva sconfiggere da solo l'Impero austriaco. Le sconfitte del 1848-1849 avevano mostrato il limite di una guerra esclusivamente piemontese.", "Cavour guardava al mercato britannico e al parlamentarismo occidentale. Trattati commerciali, ferrovie, porti, canali e credito dovevano accrescere risorse fiscali e capacità militare."], summary: "Senza modernizzazione e alleanze, l'espansione piemontese restava improbabile." },
        { title: "Le fratture: Crimea e crisi calabiana", paragraphs: ["Nel 1855 il Piemonte entrò nella guerra di Crimea al fianco di Francia, Gran Bretagna e Impero ottomano. Il vantaggio immediato era incerto; la decisione serviva a sedere al tavolo diplomatico e anche a impedire che il re sostituisse Cavour con un governo conservatore favorevole alla guerra.", "Nello stesso anno il progetto di sopprimere gli ordini religiosi contemplativi provocò la crisi calabiana. Il tentativo della Corona e dell'episcopato di bloccare la legge fallì; Cavour tornò rafforzato, ma accettò un compromesso."], summary: "Politica estera e conflitto costituzionale si intrecciarono: nessuna scelta fu soltanto nazionale o soltanto interna." },
        { title: "Il processo: Parigi senza decisioni sull'Italia", paragraphs: ["Al Congresso di Parigi del 1856 Cavour denunciò l'occupazione austriaca e il malgoverno nella penisola. Le potenze discussero la questione italiana, ma non approvarono alcun piano per l'indipendenza o l'unità.", "Il successo fu di posizione: il Piemonte entrò nel sistema diplomatico europeo, mentre l'Austria usciva isolata dalla crisi orientale. Trasformare quella posizione in risultati territoriali richiedeva ancora una congiuntura favorevole e un alleato disposto alla guerra."], summary: "Parigi rese il Piemonte interlocutore; non decise l'Unità." },
        { title: "Attori e reti: la Società nazionale", paragraphs: ["Daniele Manin, Giuseppe La Farina e Garibaldi sostennero dal 1857 la Società nazionale italiana: indipendenza e unità sotto la monarchia sabauda. Democratici ed ex repubblicani accettavano così una collaborazione tattica con il Piemonte.", "Cavour utilizzò la rete senza controllarla completamente. Esuli, comitati locali, sottoscrizioni e stampa creavano una mobilitazione nazionale che la diplomazia ufficiale poteva sfruttare ma anche temere."], summary: "La politica nazionale unì apparati statali e reti volontarie, senza cancellarne le differenze." },
        { title: "Conseguenze e nodo interpretativo", paragraphs: ["Ferrovie e commercio aumentarono l'integrazione, ma anche spesa pubblica e indebitamento. La modernizzazione non fu un semplice preludio virtuoso: distribuì costi e vantaggi in modo diseguale.", "L'attentato di Felice Orsini a Napoleone III nel gennaio 1858 rischiò di compromettere l'alleanza; le lettere dal carcere e l'azione diplomatica piemontese contribuirono invece a riportare l'indipendenza italiana nell'agenda francese. Il terrorismo non 'creò' l'alleanza, ma mutò il contesto."], summary: "Lo Stato si rafforzò grazie a risorse, reti e occasioni che nessun attore controllava da solo." }
      ],
      source: { id: "parigi", title: "Il Congresso di Parigi e la questione italiana", prompt: "Individua la differenza fra discutere un problema e adottare una decisione internazionale." },
      activity: { title: "Bilancio di una strategia", prompt: "Valuta Crimea, ferrovie, trattati commerciali e Società nazionale: per ciascuno indica risorsa ottenuta, costo sostenuto e risultato non garantito." },
      coordinates: ["Crimea, 1855", "Crisi calabiana, aprile-maggio 1855", "Congresso di Parigi, febbraio-aprile 1856", "Società nazionale, 1857", "Attentato Orsini, 14 gennaio 1858"],
      essentials: ["La guerra di Crimea ebbe vantaggi incerti.", "Il Congresso di Parigi non deliberò l'unità italiana.", "La crisi calabiana coinvolse Corona, governo e Chiesa.", "Modernizzazione e debito crebbero insieme.", "La Società nazionale collegò moderati ed ex democratici.", "Orsini va studiato senza trasformare l'attentato in causa unica."],
      vocab: { Libero_scambio: "Riduzione di dazi e ostacoli al commercio internazionale.", Debito_pubblico: "Somma dei prestiti contratti dallo Stato e dei relativi obblighi.", Potenza_garante: "Stato capace di influire sull'assetto internazionale.", Rete_patriottica: "Collegamento non statale di comitati, esuli, stampa e finanziatori.", Questione_italiana: "Problema diplomatico dell'assetto politico della penisola." },
      answer: "Il Piemonte accrebbe capacità economica, credito e riconoscimento diplomatico. Crimea e Parigi non gli consegnarono l'Italia: lo resero però più credibile come partner di una potenza e come centro di reti nazionali."
    },
    {
      id: "diplomazia-guerra", number: 3, title: "Diplomazia e guerra nel 1858-1859", eyebrow: "Un'alleanza condizionata", period: "luglio 1858-novembre 1859",
      question: "Come nacque la guerra del 1859 e perché si concluse prima degli obiettivi immaginati a Plombières?",
      lead: "L'intesa fra Cavour e Napoleone III richiedeva che l'Austria apparisse aggressore. L'ultimatum di Vienna aprì la guerra; le vittorie franco-piemontesi non eliminarono però i vincoli militari, diplomatici e politici della Francia.",
      sections: [
        { title: "Il mondo precedente: progetti diversi nello stesso accordo", paragraphs: ["A Plombières, nel luglio 1858, Cavour e Napoleone III discussero una guerra contro l'Austria e una confederazione di quattro Stati italiani presieduta onorariamente dal papa. Il Piemonte avrebbe ottenuto un grande regno settentrionale; la Francia Nizza e Savoia.", "Non esiste un verbale firmato dell'incontro. La ricostruzione dipende soprattutto dalla lettera di Cavour a Vittorio Emanuele II e da testimonianze successive. L'intesa era reale, ma non definiva ogni dettaglio e non prevedeva il Regno d'Italia del 1861."], summary: "Plombières fu un'intesa segreta e condizionata, non il progetto esecutivo dell'Unità." },
        { title: "Le fratture: il grido di dolore e l'ultimatum", paragraphs: ["Il discorso della Corona del 10 gennaio 1859 dichiarò il Piemonte non insensibile al 'grido di dolore' proveniente dall'Italia. Mobilitazione, volontari e tensione diplomatica aumentarono.", "Il 23 aprile l'Austria intimò al Piemonte di disarmare entro tre giorni. Torino respinse la richiesta il 26 aprile. L'ultimatum permise alla Francia di presentare l'intervento come risposta a un'aggressione austriaca, secondo la condizione dell'alleanza."], summary: "L'ultimatum fu il fattore scatenante che rese praticabile un progetto già preparato." },
        { title: "Il processo militare e politico", paragraphs: ["L'esercito austriaco esitò oltre il Ticino. Le forze francesi raggiunsero il teatro di guerra; Montebello, Palestro e Magenta aprirono la Lombardia, mentre Solferino e San Martino il 24 giugno produssero perdite enormi.", "Nel frattempo i sovrani di Toscana, Modena e Parma fuggirono; in Romagna l'autorità pontificia crollò. Governi provvisori e comitati nazionali crearono fatti politici che andavano oltre i piani dei due alleati."], summary: "La guerra trasformò i territori anche attraverso rivoluzioni locali e vuoti di potere." },
        { title: "Villafranca e Zurigo: perché fermarsi", paragraphs: ["Napoleone III temeva costi, mobilitazione tedesca, reazione cattolica e difficoltà del Quadrilatero. L'11 luglio concordò con Francesco Giuseppe i preliminari di Villafranca senza Cavour: Lombardia al Piemonte tramite la Francia, Veneto all'Austria, restaurazione dei sovrani dell'Italia centrale e confederazione italiana.", "Vittorio Emanuele II accettò 'per quanto lo riguardava'; Cavour si dimise. La pace di Zurigo del 10 novembre recepì l'accordo, ma le restaurazioni previste non si realizzarono."], summary: "La Francia non tradì un piano unitario mai esistito: perseguì interessi propri e fermò una guerra divenuta più rischiosa." },
        { title: "Nodo interpretativo: vittoria incompleta o apertura imprevista?", paragraphs: ["Il Piemonte ottenne la Lombardia ma non il Veneto. Sul piano militare l'esito fu incompleto; sul piano politico, i governi provvisori dell'Italia centrale resero difficile tornare all'ordine precedente.", "La contingenza è decisiva: nel luglio 1859 nessuno sapeva che entro venti mesi sarebbe nato un Regno esteso alla Sicilia. L'esito dipese dalle decisioni successive."], summary: "La guerra non completò il progetto: aprì possibilità nuove." }
      ],
      source: { id: "ultimatum", title: "L'ultimatum austriaco del 23 aprile 1859", prompt: "Spiega perché la forma diplomatica del documento fu importante quanto la richiesta militare." },
      activity: { title: "Consiglio di crisi, 1858", prompt: "Scegli fra guerra immediata, congresso o attesa. Devi rispettare quattro vincoli: alleanza condizionata, superiorità austriaca, opinione francese e rischio rivoluzionario. Poi confronta la scelta con gli eventi reali." },
      coordinates: ["Plombières, 20-21 luglio 1858", "Grido di dolore, 10 gennaio 1859", "Ultimatum, 23 aprile", "Magenta, 4 giugno", "Solferino e San Martino, 24 giugno", "Villafranca, 11 luglio", "Zurigo, 10 novembre"],
      essentials: ["Plombières non prevedeva il Regno del 1861.", "La Francia interveniva solo dopo un'aggressione austriaca.", "L'ultimatum del 23 aprile fu decisivo.", "I governi provvisori modificarono il quadro.", "Villafranca rispose a vincoli francesi e militari.", "Zurigo non restaurò davvero l'ordine precedente."],
      vocab: { Intesa_segreta: "Accordo politico non formalizzato pubblicamente in ogni dettaglio.", Ultimatum: "Richiesta vincolante accompagnata dalla minaccia di conseguenze.", Quadrilatero: "Sistema fortificato austriaco di Peschiera, Mantova, Verona e Legnago.", Armistizio: "Sospensione concordata delle operazioni militari.", Governo_provvisorio: "Autorità temporanea nata durante una crisi di sovranità." },
      answer: "La guerra nacque da una strategia franco-piemontese, dalla pressione nazionale e soprattutto dall'ultimatum austriaco. Si fermò perché Napoleone III valutò costi e rischi superiori ai vantaggi; l'interruzione lasciò però aperta la questione dell'Italia centrale."
    },
    {
      id: "annessioni-rivoluzione", number: 4, title: "Annessioni e rivoluzione nazionale", eyebrow: "Voti senza competizione moderna", period: "luglio 1859-aprile 1860",
      question: "I plebisciti del 1860 furono espressione della volontà popolare, strumento diplomatico o entrambe le cose?",
      lead: "Toscana, Emilia e Romagna respinsero il ritorno dei vecchi sovrani. Le consultazioni legittimarono l'unione al Piemonte, ma furono organizzate da autorità annessioniste e non ebbero segretezza e pluralismo comparabili a quelli contemporanei.",
      sections: [
        { title: "Il mondo precedente: sovranità sospese", paragraphs: ["Dopo Villafranca i governi provvisori di Toscana, Modena, Parma e Romagna coordinarono amministrazione ed eserciti. Bettino Ricasoli in Toscana e Luigi Carlo Farini in Emilia costruirono autorità capaci di impedire le restaurazioni.", "La loro forza dipendeva da élite municipali, Guardia nazionale, Società nazionale, consenso urbano e protezione indiretta piemontese. Contadini e lavoratori partecipavano in forme diseguali e con aspettative non sempre coincidenti con l'annessione."], summary: "La crisi degli Stati preunitari produsse governi locali, non un vuoto riempito automaticamente da Torino." },
        { title: "Le fratture: Cavour e il compromesso francese", paragraphs: ["Cavour tornò al governo nel gennaio 1860. Per ottenere il riconoscimento francese delle annessioni accettò la cessione di Nizza e Savoia, ora prezzo della configurazione imprevista.", "Il trattato di Torino del 24 marzo subordinò formalmente la cessione al consenso delle popolazioni. A Nizza l'opposizione di Garibaldi mostrò che appartenenza dinastica, linguistica e nazionale non coincidevano."], summary: "Annessioni italiane e cessioni alla Francia furono parti dello stesso compromesso internazionale." },
        { title: "Il processo: i plebisciti dell'Italia centrale", paragraphs: ["L'11 e 12 marzo 1860 gli elettori di Toscana ed Emilia scelsero fra unione alla monarchia costituzionale e regno separato. Le maggioranze per l'unione furono schiaccianti.", "Il voto era più largo del suffragio politico ordinario, ma schede, urne separate e pressione delle autorità rendevano visibile la scelta; l'opposizione aveva spazi ridotti. Il risultato documenta una forte egemonia annessionista fra i partecipanti, non un consenso unanime misurato secondo standard moderni."], summary: "Il plebiscito fu insieme mobilitazione, decisione istituzionale e argomento diplomatico." },
        { title: "Attori invisibili e aspettative differenti", paragraphs: ["Comitati femminili raccoglievano fondi, ospitavano esuli, curavano feriti e diffondevano stampa; le donne restavano escluse dal voto. Anche molti uomini poveri non accedevano alla cittadinanza politica ordinaria.", "La parola 'popolo' nelle proclamazioni unificava soggetti diversi. Lo storico deve chiedere chi parlava, chi votava, chi organizzava e chi era rappresentato soltanto simbolicamente."], summary: "La mobilitazione nazionale fu più ampia della cittadinanza legale, ma non coincise con l'intera popolazione." },
        { title: "Conseguenze e nodo interpretativo", paragraphs: ["Le annessioni ampliarono il Piemonte oltre la Lombardia e resero impraticabile la confederazione di Villafranca. Napoleone III poté presentarle come volontà popolare, ma ottenne Nizza e Savoia.", "Non basta liquidare i plebisciti come falsi, né assumerli come referendum moderni. Vanno letti dentro una transizione rivoluzionaria, con consenso reale, organizzazione dall'alto e limitata competizione."], summary: "Il voto legittimò un processo reso possibile da rivoluzione, amministrazione e diplomazia." }
      ],
      source: { id: "plebisciti", title: "Quesiti e risultati dei plebisciti del 1860", prompt: "Confronta formulazione, condizioni del voto e funzione internazionale del risultato." },
      activity: { title: "Anatomia di un plebiscito", prompt: "Classifica quesito, corpo elettorale, segretezza, propaganda e conseguenze come prova di consenso, limite della consultazione o entrambe." },
      coordinates: ["Governi provvisori, 1859", "Ritorno di Cavour, 20 gennaio 1860", "Plebisciti, 11-12 marzo", "Trattato di Torino, 24 marzo", "Voti di Nizza e Savoia, aprile"],
      essentials: ["I governi provvisori ebbero iniziativa propria.", "I plebisciti non furono elezioni competitive moderne.", "Il consenso annessionista fu politicamente forte.", "Nizza e Savoia furono cedute alla Francia.", "Garibaldi si oppose alla cessione di Nizza.", "Mobilitazione e diritto di voto non coincidevano."],
      vocab: { Plebiscito: "Consultazione diretta su una scelta di sovranità.", Annessione: "Incorporazione di un territorio in uno Stato esistente.", Corpo_elettorale: "Insieme delle persone ammesse al voto.", Egemonia: "Capacità di rendere una scelta dominante e legittima.", Sovranità: "Potere ultimo riconosciuto su territorio e popolazione." },
      answer: "I plebisciti espressero un consenso annessionista ampio fra i partecipanti e fornirono legittimazione internazionale. Furono però consultazioni controllate, non referendum pluralisti moderni; il loro significato nasce dall'intreccio fra voto, rivoluzione e diplomazia."
    },
    {
      id: "mille-mezzogiorno", number: 5, title: "I Mille e la conquista del Mezzogiorno", eyebrow: "Rivolta, spedizione, collasso", period: "aprile 1860-marzo 1861",
      question: "Come poté una spedizione di poco più di mille volontari provocare il crollo del più grande Stato italiano?",
      lead: "La risposta non è il genio di un solo uomo. La rivolta siciliana, le reti democratiche, gli errori borbonici, l'afflusso di volontari, una congiuntura britannica favorevole e l'intervento piemontese trasformarono una spedizione rischiosa in conquista.",
      sections: [
        { title: "Il mondo precedente: Sicilia e crisi borbonica", paragraphs: ["L'autonomia siciliana restava irrisolta. La rivolta della Gancia del 4 aprile 1860 fu repressa a Palermo, ma continuò nelle campagne. Francesco Crispi e Rosolino Pilo lavorarono perché l'insurrezione locale precedesse i volontari.", "Francesco II aveva ereditato un esercito numeroso ma un regime isolato, diviso fra riforma e repressione. La concessione tardiva della Costituzione non ricompose le lealtà."], summary: "La spedizione entrò in una crisi già aperta; non la creò dal nulla." },
        { title: "Le fratture: Quarto, Marsala e Calatafimi", paragraphs: ["Garibaldi partì da Quarto nella notte fra 5 e 6 maggio. Cavour temeva il fallimento; reti patriottiche e ambienti monarchici facilitarono uomini, armi e navi mentre il governo mantenne una negazione plausibile.", "A Marsala erano presenti navi britanniche: la circostanza limitò i movimenti borbonici, ma non prova un ordine ufficiale di Londra. A Calatafimi il successo ebbe soprattutto effetto morale e politico."], summary: "Complicità informali, circostanze navali e mobilitazione locale contano più di una regia segreta unica." },
        { title: "Il processo: da Palermo a Napoli", paragraphs: ["Palermo e Milazzo ampliarono l'Esercito meridionale con siciliani e nuovi volontari. Garibaldi governò come dittatore in nome di Vittorio Emanuele II, rinviando l'annessione per proseguire la guerra.", "Le aspettative contadine su terre, imposte e demani entrarono in conflitto con la tutela della proprietà. A Bronte la repressione ordinata da Bixio e le fucilazioni dopo un processo sommario mostrarono il limite sociale della rivoluzione nazionale.", "Dopo lo sbarco in Calabria reparti borbonici si disgregarono o negoziarono; Francesco II lasciò Napoli e resistette sul Volturno e a Gaeta. La crisi dipese da comando, morale, lealtà e isolamento politico, non dall'inesistenza dell'esercito."], summary: "La conquista fu militare, politica e sociale; il successo cambiò la composizione stessa della spedizione." },
        { title: "Piemonte, Teano e plebisciti", paragraphs: ["Il progetto garibaldino di avanzare verso Roma minacciava un conflitto con la Francia. L'esercito piemontese invase Marche e Umbria, vinse a Castelfidardo e scese verso sud.", "Il plebiscito del 21 ottobre offriva annessione monarchica o rifiuto. Le testimonianze sull'incontro del 26 ottobre nei pressi di Teano divergono nei dettagli: la memoria nazionale trasformò una transizione conflittuale in scena di armonia."], summary: "L'iniziativa volontaria fu decisiva e poi ricondotta entro lo Stato monarchico." },
        { title: "Nodo interpretativo: liberazione, conquista, rivoluzione", paragraphs: ["Per molti liberali meridionali la caduta borbonica fu liberazione; per contadini e autonomisti l'annessione poteva significare promesse mancate; per la monarchia fu estensione della sovranità; per i democratici un successo incompleto.", "Una sola parola non esaurisce il processo. Occorre distinguere luoghi, gruppi, fasi e fonti, evitando tanto l'epopea uniforme quanto il complotto onnipotente."], summary: "Il Mezzogiorno non fu passivo: sostenne, contrastò e reinterpretò l'unificazione." }
      ],
      source: { id: "garibaldi-dittatura", title: "Garibaldi assume la dittatura in Sicilia", prompt: "Analizza la formula 'in nome di Vittorio Emanuele': che cosa legittima e che cosa lascia aperto?" },
      activity: { title: "Teano: fonte e memoria", prompt: "Confronta tre elementi certi con tre dettagli discordanti. Scrivi una didascalia che non trasformi la tradizione iconografica in fotografia dell'evento." },
      coordinates: ["Gancia, 4 aprile 1860", "Quarto, 5-6 maggio", "Marsala, 11 maggio", "Calatafimi, 15 maggio", "Palermo, 27-30 maggio", "Milazzo, 20 luglio", "Bronte, agosto", "Volturno, 1-2 ottobre", "Plebiscito, 21 ottobre", "Teano, 26 ottobre"],
      essentials: ["La rivolta siciliana precedette lo sbarco.", "Il sostegno piemontese fu ambiguo.", "La presenza britannica non equivale a sostegno ufficiale.", "L'esercito borbonico ebbe crisi di comando e lealtà.", "La rivoluzione nazionale non divenne agraria.", "Teano è un evento caricato da memoria successiva."],
      vocab: { Dittatura: "Magistratura straordinaria rivendicata da Garibaldi.", Negazione_plausibile: "Possibilità di negare il controllo su un'azione favorita indirettamente.", Demanio: "Terra pubblica o comunitaria oggetto di usi collettivi.", Esercito_meridionale: "Forze garibaldine ampliate oltre i Mille.", Memoria_nazionale: "Rielaborazione pubblica del passato per costruire identità." },
      answer: "I Mille ebbero successo perché entrarono in una rivoluzione siciliana, attrassero forze locali, sfruttarono la crisi borbonica e furono infine affiancati e controllati dal Piemonte. Furono il catalizzatore di un collasso, non un miracolo isolato."
    },
    {
      id: "costruire-stato", number: 6, title: "Il Regno d'Italia: costruire uno Stato, governare differenze", eyebrow: "Cittadinanza ed esclusione", period: "1861-1865",
      question: "Perché proclamare il Regno fu più rapido che trasformare territori differenti in uno Stato comune?",
      lead: "Il 17 marzo 1861 nacque il Regno, ma l'unificazione amministrativa, fiscale, militare e scolastica impose scelte concrete. La continuità piemontese rese possibile governare subito; produsse anche la percezione di una piemontesizzazione.",
      sections: [
        { title: "Il mondo precedente: molte Italie", paragraphs: ["Circa 22 milioni di abitanti vivevano in economie, sistemi amministrativi e culture linguistiche differenti. L'agricoltura occupava la maggioranza degli attivi; l'analfabetismo superava largamente i due terzi; gli italofoni abituali erano una minoranza difficile da quantificare.", "Mezzadria centro-italiana, aziende capitalistiche padane, latifondi meridionali e piccola proprietà convivevano. Ridurre il paese a un Nord moderno e un Sud immobile cancella differenze interne a entrambe le aree."], summary: "Lo Stato unitario ereditò non due, ma molte Italie." },
        { title: "Le fratture: una legge e una continuità dinastica", paragraphs: ["La legge 17 marzo 1861 attribuì a Vittorio Emanuele II il titolo di re d'Italia 'per grazia di Dio e per volontà della Nazione'. Il sovrano mantenne il numerale II; il Parlamento fu l'VIII legislatura; lo Statuto fu esteso.", "La continuità offriva un ordinamento funzionante, ma comunicava che il Regno era l'ampliamento dello Stato sabaudo. Progetti regionali e di decentramento furono discussi e accantonati."], summary: "L'Italia nacque come Stato nuovo nella geografia e continuazione giuridica del Regno di Sardegna." },
        { title: "Il processo: prefetti, bilanci, leva e scuola", paragraphs: ["Leggi, codici e ministeri piemontesi furono estesi; i prefetti rappresentarono il governo. Centralizzare sembrava una difesa contro restaurazioni e rivoluzioni, ma ridusse autonomie e sottovalutò conoscenze locali.", "Il nuovo Stato unificò debiti e sistemi fiscali, finanziò esercito e infrastrutture e introdusse la leva. Tassa, coscrizione e burocrazia resero lo Stato presente anche come imposizione.", "La legge Casati affidava ai comuni gran parte della scuola elementare: dove mancavano risorse, insegnanti ed edifici, l'obbligo restava fragile. La lingua comune fu un progetto lungo, non un dato del 1861."], summary: "Fare lo Stato significò uniformare servizi e obblighi con capacità territoriali diseguali." },
        { title: "Suffragio ristretto e paese legale", paragraphs: ["Votavano uomini di almeno venticinque anni, alfabetizzati e con censo sufficiente. Gli iscritti erano circa 419.000: meno del 2% della popolazione. Donne e quasi tutti i lavoratori e contadini erano esclusi.", "Destra e Sinistra storica erano gruppi di notabili, non partiti di massa. Il paese legale decideva per un paese reale mobilitato in guerra ma non ammesso alla rappresentanza."], summary: "La nazione invocata nei plebisciti era molto più ampia del corpo elettorale ordinario." },
        { title: "Brigantaggio, legge Pica e conflitto meridionale", paragraphs: ["Nel Mezzogiorno bande differenti unirono ex soldati borbonici, legittimisti, renitenti, criminali, contadini in conflitto con proprietari e comunità locali. 'Brigantaggio' è una categoria amministrativa che raggruppa fenomeni plurali.", "Lo Stato impiegò decine di migliaia di soldati. La legge Pica del 15 agosto 1863 introdusse tribunali militari, domicilio coatto e misure eccezionali nelle province dichiarate infestate.", "Alcuni storici usano 'guerra civile' per sottolineare intensità e schieramenti italiani contrapposti; altri temono che la formula uniformi conflitti diversi. È una categoria discussa, non un'etichetta risolutiva."], summary: "Il conflitto fu sociale, politico, criminale e militare in proporzioni variabili." }
      ],
      source: { id: "legge-pica", title: "La legge Pica e l'eccezione", prompt: "Individua quali garanzie ordinarie vengono sostituite da misure militari e preventive." },
      activity: { title: "Classificare senza semplificare", prompt: "Per ex soldato, contadino senza terra, legittimista, renitente, bandito e manutengolo indica motivazione possibile, fonte necessaria e rischio di generalizzazione." },
      coordinates: ["Parlamento, 18 febbraio 1861", "Legge del Regno, 17 marzo", "Morte di Cavour, 6 giugno", "Legge Pica, 15 agosto 1863", "Capitale Firenze, 1865"],
      essentials: ["Il Regno mantenne Statuto e numerazione sabauda.", "Il suffragio coinvolgeva meno del 2%.", "Centralizzazione e decentramento furono alternative.", "Debito, imposte e leva costruirono lo Stato.", "La scuola dipendeva da capacità comunali diseguali.", "Il brigantaggio ebbe componenti plurali.", "La legge Pica militarizzò la repressione."],
      vocab: { Piemontesizzazione: "Estensione al Regno di norme e apparati sabaudi.", Prefetto: "Rappresentante del governo nella provincia.", Paese_legale: "Minoranza ammessa alla vita elettorale.", Manutengolo: "Persona accusata di sostenere una banda.", Domicilio_coatto: "Obbligo di risiedere in un luogo imposto.", Legge_Pica: "Legge 1409 del 1863 con misure eccezionali." },
      answer: "Proclamare il Regno richiese una legge; costruire lo Stato richiese amministrazioni, risorse e obbedienza. La scelta centralista rese rapido il comando ma ampliò distanze, mentre suffragio ristretto e repressione mostrarono i limiti della cittadinanza liberale."
    },
    {
      id: "veneto-roma", number: 7, title: "Veneto, Roma e le eredità dell'Unità", eyebrow: "Completare non significa chiudere", period: "1862-1871",
      question: "Come entrarono Veneto e Roma nel Regno e quali problemi restarono aperti dopo il 1870?",
      lead: "Il completamento territoriale dipese ancora da guerre europee. Le sconfitte italiane del 1866 non impedirono l'annessione del Veneto; la caduta di Napoleone III rese possibile Roma. Il conflitto con il papato non si chiuse.",
      sections: [
        { title: "Il mondo precedente: due capitali fuori dal Regno", paragraphs: ["Nel 1861 il Veneto apparteneva all'Austria; Roma e il Lazio allo Stato pontificio protetto dalla Francia. La Camera indicò Roma come capitale futura, ma mancavano le condizioni.", "Garibaldi fu fermato ad Aspromonte nel 1862. La Convenzione di settembre del 1864 impegnò la Francia a ritirarsi e l'Italia a proteggere il papa; la capitale passò da Torino a Firenze."], summary: "Il governo conciliava obiettivo nazionale, alleanza francese e sovranità pontificia." },
        { title: "Le fratture: la guerra del 1866", paragraphs: ["L'alleanza con la Prussia inserì il Veneto nella guerra austro-prussiana. L'Italia fu sconfitta a Custoza e Lissa; Garibaldi vinse a Bezzecca ma ricevette l'ordine di ritirarsi.", "La vittoria prussiana costrinse l'Austria a cedere il Veneto alla Francia, che lo trasferì all'Italia dopo un plebiscito. L'annessione fu risultato diplomatico della guerra europea nonostante il rendimento militare contraddittorio."], summary: "Il Veneto entrò grazie all'alleanza e alla sconfitta austriaca sul fronte prussiano." },
        { title: "Mentana e il limite della soluzione volontaria", paragraphs: ["Nel 1867 una nuova spedizione garibaldina tentò di provocare l'insurrezione romana. A Mentana truppe pontificie e francesi sconfissero i volontari.", "Debole mobilitazione interna, superiorità militare e vincolo francese mostrarono che l'iniziativa volontaria non poteva risolvere da sola la questione romana."], summary: "Mentana confermò che Roma dipendeva dagli equilibri europei." },
        { title: "Porta Pia, plebiscito e capitale", paragraphs: ["La guerra franco-prussiana del 1870 provocò la caduta di Napoleone III e il ritiro francese. Dopo un ultimo negoziato con Pio IX, l'esercito italiano aprì il 20 settembre una breccia presso Porta Pia; il plebiscito del 2 ottobre approvò l'unione.", "La legge delle Guarentigie del 13 maggio 1871 riconobbe prerogative, immunità e dotazione economica al papa; Pio IX la rifiutò perché unilaterale. Nel luglio 1871 governo e corte si trasferirono a Roma."], summary: "Roma divenne capitale, ma la questione dei rapporti con la Chiesa rimase aperta." },
        { title: "Conclusione: unità senza teleologia", paragraphs: ["Trentino e Trieste restavano fuori; il conflitto con il papato allontanò parte dei cattolici; differenze sociali e regionali non erano risolte. Bilancio, scuola, lingua e partecipazione richiedevano decenni.", "La formula 'Fatta l'Italia, bisogna fare gli italiani' è spesso attribuita a d'Azeglio, ma forma esatta e attribuzione sono incerte. Va usata come memoria sintetica, non come citazione certa.", "La storiografia illumina piani diversi: Lucy Riall studia la mobilitazione politica e la costruzione successiva del mito garibaldino; Alberto Mario Banti ricostruisce immagini, parentele e linguaggi con cui la nazione fu resa pensabile; Maurizio Isabella segue esuli e circolazioni transnazionali; John A. Davis e Christopher Duggan insistono sui conflitti prodotti dall'integrazione statale. Non sono spiegazioni intercambiabili: cultura nazionale, reti politiche e capacità coercitiva dello Stato rispondono a domande differenti e vanno messe in relazione.", "Cavour non controllò i Mille; Garibaldi non controllò l'annessione; Napoleone III non ottenne la confederazione; il papato non conservò lo Stato. Proprio questi esiti imprevisti mostrano che l'Unità non era inevitabile."], summary: "Il 1870 chiuse una fase territoriale e aprì problemi di cittadinanza e legittimità." }
      ],
      source: { id: "guarentigie", title: "La legge delle Guarentigie", prompt: "Spiega perché una garanzia unilaterale poteva essere valida per lo Stato e inaccettabile per il papa." },
      activity: { title: "Tesi finale a prove", prompt: "Rispondi alla domanda generatrice usando una carta, una legge, una decisione internazionale, un gruppo escluso e un esito imprevisto. Aggiungi un'obiezione." },
      coordinates: ["Aspromonte, 29 agosto 1862", "Convenzione, 15 settembre 1864", "Custoza, 24 giugno 1866", "Lissa, 20 luglio", "Mentana, 3 novembre 1867", "Porta Pia, 20 settembre 1870", "Guarentigie, 13 maggio 1871", "Roma capitale, luglio 1871"],
      essentials: ["Roma e Veneto erano fuori nel 1861.", "Il Veneto fu ottenuto nel quadro della guerra prussiana.", "Custoza e Lissa furono sconfitte.", "Mentana bloccò Garibaldi.", "Porta Pia dipese dal ritiro francese.", "Le Guarentigie furono rifiutate da Pio IX.", "Roma divenne capitale nel 1871.", "Il territorio non risolse l'integrazione nazionale."],
      vocab: { Convenzione_di_settembre: "Accordo italo-francese del 1864.", Questione_romana: "Conflitto sulla sovranità di Roma e sul papato.", Guarentigie: "Garanzie offerte al pontefice nel 1871.", Completamento_territoriale: "Formula relativa: altri territori restavano esclusi.", Non_expedit: "Orientamento papale contrario alla partecipazione politica dei cattolici." },
      answer: "Veneto e Roma entrarono quando guerre europee indebolirono Austria e Francia. Nel 1870 l'unità territoriale fondamentale era raggiunta, ma restavano fratture con il papato, esclusione politica, differenze regionali e il compito di costruire una cittadinanza effettiva."
    }
  ],
  people: [
    { id: "cavour", name: "Camillo Benso di Cavour", dates: "1810-1861", role: "Presidente del Consiglio piemontese", image: "assets/img/people/cavour.jpg", bio: "Costruì maggioranze parlamentari, modernizzò lo Stato e cercò alleanze contro l'Austria. Prima del 1859 mirava soprattutto a un ampliamento settentrionale, non a un piano immutabile per tutta l'Italia.", idea: "La diplomazia crea possibilità; rivoluzioni e guerre possono portarla oltre il progetto iniziale." },
    { id: "vittorio", name: "Vittorio Emanuele II", dates: "1820-1878", role: "Re di Sardegna e poi d'Italia", image: "assets/img/people/vittorio-emanuele.jpg", bio: "Conservò lo Statuto ma rivendicò prerogative in politica estera e militare. Mantenne il numerale II nel nuovo Regno, segno della continuità dinastica sabauda.", idea: "Monarchia nazionale e governo parlamentare convivevano in tensione." },
    { id: "garibaldi", name: "Giuseppe Garibaldi", dates: "1807-1882", role: "Comandante volontario e democratico", image: "assets/img/people/garibaldi.jpg", bio: "Guidò i Mille e l'Esercito meridionale. Agì in nome del re pur restando democratico; fu poi fermato dallo Stato ad Aspromonte e sconfitto a Mentana.", idea: "L'iniziativa popolare può accelerare lo Stato e insieme esserne controllata." },
    { id: "mazzini", name: "Giuseppe Mazzini", dates: "1805-1872", role: "Repubblicano unitario", image: "assets/img/people/mazzini.jpg", bio: "Continuò a sostenere insurrezione, repubblica e unità. Criticò l'esito monarchico, ma le sue reti contribuirono alla mobilitazione nazionale.", idea: "L'unità senza sovranità popolare resta incompleta." },
    { id: "crispi", name: "Francesco Crispi", dates: "1818-1901", role: "Organizzatore siciliano dei Mille", image: "assets/img/people/crispi.jpg", bio: "Preparò la spedizione con Pilo, favorì il rapporto con l'insurrezione siciliana e fu segretario di Stato di Garibaldi. Difese l'autonomia della fase rivoluzionaria contro l'annessione immediata.", idea: "La rivoluzione locale deve coordinarsi con un progetto nazionale." },
    { id: "pilo", name: "Rosolino Pilo", dates: "1820-1860", role: "Rivoluzionario siciliano", image: "assets/img/people/pilo.jpg", bio: "Sbarcò prima dei Mille per organizzare insorti e collegamenti. Morì presso Palermo: la spedizione dipendeva dall'iniziativa locale.", idea: "L'insurrezione sul territorio precede e sostiene il corpo di spedizione." },
    { id: "manin", name: "Daniele Manin", dates: "1804-1857", role: "Promotore della Società nazionale", image: "assets/img/people/manin.jpg", bio: "Dopo la Repubblica veneziana abbandonò la pregiudiziale repubblicana e propose l'unità sotto i Savoia.", idea: "La sconfitta del 1849 produsse nuove alleanze." },
    { id: "dazeglio", name: "Massimo d'Azeglio", dates: "1798-1866", role: "Presidente del Consiglio e moderato", image: "assets/img/people/dazeglio.jpg", bio: "Guidò il Piemonte dopo Novara e sostenne leggi Siccardi e Moncalieri. La formula sul 'fare gli italiani' non è certa nella forma corrente.", idea: "Conservare lo Stato costituzionale richiese compromessi con la Corona." },
    { id: "rattazzi", name: "Urbano Rattazzi", dates: "1808-1873", role: "Leader della sinistra moderata", image: "assets/img/people/rattazzi.jpg", bio: "Il connubio con Cavour rese possibile la maggioranza centrista. Da presidente del Consiglio affrontò Aspromonte.", idea: "Le coalizioni parlamentari determinano la capacità del governo." },
    { id: "ricasoli", name: "Bettino Ricasoli", dates: "1809-1880", role: "Capo del governo provvisorio toscano", image: "assets/img/people/ricasoli.jpg", bio: "Consolidò l'autorità in Toscana e promosse l'annessione. Dopo Cavour guidò il governo del Regno.", idea: "L'annessione fu preparata da governi locali capaci di amministrare." },
    { id: "lamarmora", name: "Alfonso La Marmora", dates: "1804-1878", role: "Generale e uomo di governo", image: "assets/img/people/la-marmora.jpg", bio: "Comandò il contingente in Crimea, presiedette il governo dopo Villafranca e guidò l'esercito nella guerra del 1866.", idea: "Prestigio diplomatico e rendimento militare non coincidono." },
    { id: "napoleone", name: "Napoleone III", dates: "1808-1873", role: "Imperatore dei Francesi", image: "assets/img/people/napoleone-iii.jpg", bio: "Sostenne la guerra del 1859 per modificare l'ordine del 1815 e accrescere l'influenza francese. Fermò il conflitto e protesse Roma fino al 1870.", idea: "L'alleato agisce per i propri interessi." },
    { id: "francesco", name: "Francesco II", dates: "1836-1894", role: "Ultimo re delle Due Sicilie", image: "assets/img/people/francesco-ii.jpg", bio: "Ereditò un regime isolato, concesse tardi la Costituzione e perse Napoli. Resistette a Gaeta e dall'esilio sostenne la legittimità borbonica.", idea: "La crisi di uno Stato dipende da istituzioni e lealtà." },
    { id: "pio", name: "Pio IX", dates: "1792-1878", role: "Papa e sovrano temporale", image: "assets/img/people/pio-ix.jpg", bio: "Difese il potere temporale e condannò annessioni e legislazione laica. Rifiutò le Guarentigie perché unilaterali.", idea: "Autorità religiosa e sovranità territoriale erano ancora connesse." },
    { id: "adelaide", name: "Adelaide Cairoli", dates: "1806-1871", role: "Organizzatrice delle reti patriottiche", image: "assets/img/people/adelaide-cairoli.jpg", imageAlt: "Adelaide Cairoli con i figli in una tavola illustrata del 1889", bio: "Sostenne esuli, volontari e raccolte di fondi; trasformò la casa in nodo politico. La memoria dei figli caduti rischia di oscurarne l'azione autonoma.", idea: "Le donne parteciparono pur essendo escluse dal voto." },
    { id: "belgiojoso", name: "Cristina Trivulzio di Belgiojoso", dates: "1808-1871", role: "Giornalista e organizzatrice", image: "assets/img/people/belgiojoso.jpg", bio: "Continuò a scrivere su società e politica e osservò criticamente le condizioni dei contadini. Unì informazione, cura e finanziamento.", idea: "La nazione va giudicata anche dalle condizioni sociali." }
  ],
  timeline: [
    { date: "20 nov 1849", title: "Proclama di Moncalieri", text: "La Corona sollecita una Camera disposta ad approvare la pace.", scale: "Piemonte" },
    { date: "1850", title: "Leggi Siccardi", text: "Lo Stato abolisce privilegi ecclesiastici.", scale: "Istituzioni" },
    { date: "nov 1852", title: "Governo Cavour", text: "Il connubio sostiene il nuovo ministero.", scale: "Parlamento" },
    { date: "1855", title: "Crimea e crisi calabiana", text: "Diplomazia e conflitto costituzionale si sovrappongono.", scale: "Europa / Piemonte" },
    { date: "8 apr 1856", title: "Questione italiana a Parigi", text: "Le potenze discutono senza decidere l'unità.", scale: "Diplomazia" },
    { date: "1857", title: "Società nazionale", text: "Moderati ed ex democratici cooperano.", scale: "Reti politiche" },
    { date: "21 lug 1858", title: "Plombières", text: "Cavour e Napoleone III delineano guerra e confederazione.", scale: "Diplomazia segreta" },
    { date: "23 apr 1859", title: "Ultimatum austriaco", text: "La richiesta di disarmo attiva l'alleanza francese.", scale: "Fattore scatenante" },
    { date: "24 giu 1859", title: "Solferino e San Martino", text: "La vittoria costa perdite enormi.", scale: "Guerra" },
    { date: "11 lug 1859", title: "Villafranca", text: "Napoleone III interrompe la guerra.", scale: "Diplomazia" },
    { date: "11-12 mar 1860", title: "Plebisciti centrali", text: "Toscana ed Emilia scelgono l'unione.", scale: "Sovranità" },
    { date: "24 mar 1860", title: "Trattato di Torino", text: "Nizza e Savoia sono cedute alla Francia.", scale: "Confini" },
    { date: "5-11 mag 1860", title: "Dai Mille a Marsala", text: "La spedizione raggiunge la rivolta siciliana.", scale: "Mediterraneo" },
    { date: "27-30 mag", title: "Palermo", text: "La spedizione diventa governo rivoluzionario.", scale: "Sicilia" },
    { date: "18 set", title: "Castelfidardo", text: "Il Piemonte sconfigge l'esercito pontificio.", scale: "Stato / guerra" },
    { date: "21-26 ott", title: "Plebiscito e Teano", text: "Il Mezzogiorno è annesso; Garibaldi consegna il potere.", scale: "Transizione" },
    { date: "17 mar 1861", title: "Regno d'Italia", text: "Una legge attribuisce il nuovo titolo al re.", scale: "Istituzioni" },
    { date: "15 ago 1863", title: "Legge Pica", text: "Tribunali militari e misure preventive ampliano la repressione.", scale: "Mezzogiorno" },
    { date: "15 set 1864", title: "Convenzione di settembre", text: "Italia e Francia regolano la questione romana.", scale: "Diplomazia" },
    { date: "1866", title: "Veneto", text: "La vittoria prussiana costringe l'Austria alla cessione.", scale: "Europa" },
    { date: "3 nov 1867", title: "Mentana", text: "Forze pontificie e francesi fermano Garibaldi.", scale: "Roma" },
    { date: "20 set 1870", title: "Porta Pia", text: "Il ritiro francese rende possibile l'occupazione di Roma.", scale: "Europa / Roma" },
    { date: "13 mag-lug 1871", title: "Guarentigie e capitale", text: "Lo Stato offre garanzie al papa e trasferisce la capitale.", scale: "Nuovo assetto" }
  ],
  maps: [
    { title: "Gli Stati italiani dopo il 1849", image: "assets/img/maps/italia-1849.svg", alt: "Carta schematica degli Stati italiani e della presenza austriaca", text: "La presenza austriaca non coincideva soltanto con il Lombardo-Veneto: eserciti, trattati e dinastie condizionavano Toscana, ducati e Stato pontificio.", note: "Ricostruzione originale; confini e proporzioni generalizzati." },
    { title: "Trasformazioni 1859-1861", image: "assets/img/maps/trasformazioni-1859-1861.svg", alt: "Tre carte schematiche delle trasformazioni territoriali", text: "Guerra franco-piemontese, governi provvisori, plebisciti e conquista garibaldina furono processi diversi confluiti nello stesso Regno.", note: "Carta causale, non rappresentazione catastale o etnica." },
    { title: "Dal Regno incompleto a Roma", image: "assets/img/maps/completamento-1861-1870.svg", alt: "Carta schematica dell'annessione del Veneto e di Roma", text: "Veneto e Roma entrarono in congiunture europee differenti. Trentino e Trieste restavano fuori.", note: "Ricostruzione originale verificata su atlanti storici." }
  ],
  sources: [
    { id: "statuto", title: "Statuto Albertino: testo e prassi", author: "Carlo Alberto, re di Sardegna", date: "4 marzo 1848; esteso nel 1861", type: "Carta costituzionale concessa", provenance: "Senato della Repubblica", url: "https://www.senato.it/istituzione/la-costituzione/statuto-albertino", excerpt: ["Lo Stato è retto da un Governo Monarchico Rappresentativo.", "Il Re nomina e revoca i suoi Ministri."], context: "La carta rimase in vigore dopo Novara e fu estesa al Regno d'Italia.", audience: "Sudditi, istituzioni e funzionari.", purpose: "Definire diritti, Camere e poteri entro la sovranità dinastica.", limits: "Il testo non basta a ricostruire la prassi: maggioranze e intervento regio mutarono nel tempo.", questions: ["Quali poteri conserva il re?", "Rappresentanza significa già democrazia?", "Perché l'estensione segnala continuità?"] },
    { id: "parigi", title: "La questione italiana a Parigi", author: "Plenipotenziari delle potenze; intervento di Cavour", date: "8 aprile 1856", type: "Protocollo diplomatico", provenance: "Archivio di Stato di Torino, Archivio Cavour", url: "https://archiviodistatotorino.cultura.gov.it/", excerpt: ["[Sintesi del protocollo] I plenipotenziari espongono osservazioni sulla condizione degli Stati italiani.", "Nessuna deliberazione territoriale viene adottata."], context: "Dopo la pace di Crimea Cavour cercò di internazionalizzare il problema italiano.", audience: "Governi delle potenze firmatarie.", purpose: "Registrare discussione e posizioni dei partecipanti.", limits: "Una sintesi negoziata non equivale a un impegno per l'unità.", questions: ["Quale differenza c'è fra discussione e decisione?", "Chi controlla l'ordine del giorno?", "Quale risultato di posizione ottiene il Piemonte?"] },
    { id: "ultimatum", title: "L'ultimatum austriaco", author: "Governo dell'Impero austriaco", date: "23 aprile 1859", type: "Nota diplomatica", provenance: "Archivio di Stato di Torino, documentazione diplomatica", url: "https://archiviodistatotorino.cultura.gov.it/", excerpt: ["[Sintesi fedele] Il Governo sardo è invitato a ridurre l'esercito al piede di pace e a congedare i volontari.", "La risposta è richiesta entro tre giorni."], context: "La Francia era impegnata a intervenire soltanto se il Piemonte fosse stato aggredito.", audience: "Governo del Regno di Sardegna.", purpose: "Imporre il disarmo e recuperare l'iniziativa strategica.", limits: "Non dimostra da solo le responsabilità di lungo periodo; va confrontato con alleanza, mobilitazione e congresso proposto.", questions: ["Perché il termine è decisivo?", "Quale condizione dell'alleanza rende operativa?", "Che cosa non prova sulle intenzioni precedenti?"] },
    { id: "plebisciti", title: "I plebisciti del 1860", author: "Governi provvisori e autorità annessioniste", date: "11-12 marzo e 21 ottobre 1860", type: "Atti di consultazione", provenance: "Portale storico della Camera dei deputati", url: "https://storia.camera.it/cronologia/leg-sabaudo-VII/elenco", excerpt: ["Unione alla monarchia costituzionale del re Vittorio Emanuele.", "Il popolo vuole l'Italia una e indivisibile con Vittorio Emanuele re costituzionale e i suoi legittimi discendenti?"], context: "Le consultazioni legittimarono annessioni preparate da governi provvisori o conquista.", audience: "Popolazioni ammesse al voto e potenze europee.", purpose: "Trasformare una crisi rivoluzionaria in atto di sovranità riconoscibile.", limits: "Quesito, segretezza e propaganda non rispettavano standard moderni; il voto misura comunque una mobilitazione reale.", questions: ["Quali alternative offre il quesito?", "Perché il risultato serviva alla diplomazia?", "Come distinguere consenso, controllo e unanimità?"] },
    { id: "garibaldi-dittatura", title: "Garibaldi assume la dittatura in Sicilia", author: "Giuseppe Garibaldi", date: "14 maggio 1860", type: "Decreto", provenance: "Archivio di Stato di Palermo", url: "https://archiviodistatodipalermo.cultura.gov.it/", excerpt: ["In nome di Vittorio Emanuele Re d'Italia.", "Giuseppe Garibaldi, comandante in capo le forze nazionali in Sicilia, assume la dittatura in Sicilia."], context: "Tre giorni dopo lo sbarco la spedizione doveva creare un'autorità e collegarsi alla rivolta locale.", audience: "Siciliani, volontari, monarchia e governi esteri.", purpose: "Legittimare comando e amministrazione senza proclamare una repubblica.", limits: "Il decreto afferma autorità; non dimostra consenso uniforme o controllo dell'intera isola.", questions: ["Perché usare il nome del re?", "Che cosa significa qui dittatura?", "Quale conflitto futuro resta aperto?"] },
    { id: "legge-pica", title: "Provvedimenti contro il brigantaggio", author: "Parlamento e governo del Regno d'Italia", date: "15 agosto 1863", type: "Legge n. 1409, detta Pica", provenance: "Archivio storico del Senato", url: "https://www.senato.it/node/84602/printable/print", excerpt: ["[Sintesi del dispositivo] Nelle province dichiarate infestate i componenti di comitiva armata sono giudicati dai tribunali militari.", "Sono previste misure di domicilio coatto anche per sospetti manutengoli e camorristi."], context: "Il conflitto meridionale impegnava l'esercito e le autorità chiedevano strumenti eccezionali.", audience: "Tribunali militari, prefetti, forze armate e popolazioni delle province designate.", purpose: "Accelerare repressione e controllo preventivo.", limits: "La categoria legale di brigante non spiega motivazioni e sostegni; le misure colpiscono anche sospetti.", questions: ["Quali garanzie ordinarie sono ridotte?", "Chi definisce una provincia infestata?", "Perché la categoria amministrativa non basta allo storico?"] },
    { id: "guarentigie", title: "La legge delle Guarentigie", author: "Parlamento del Regno d'Italia", date: "13 maggio 1871", type: "Legge n. 214", provenance: "Senato della Repubblica", url: "https://www.senato.it/application/xmanager/projects/leg19/file/repository/relazioni/libreria/fascicoli_divulgativi/unit_2015_con_sovracopertina.pdf", excerpt: ["La persona del Sommo Pontefice è sacra ed inviolabile.", "Il Governo italiano rende al Sommo Pontefice gli onori sovrani."], context: "Dopo Porta Pia lo Stato cercò di regolare unilateralmente posizione, immunità e dotazione del pontefice.", audience: "Istituzioni italiane, Santa Sede, cattolici e potenze.", purpose: "Garantire libertà e prerogative personali senza restituire sovranità territoriale.", limits: "Pio IX non riconobbe la legge; un atto unilaterale non costituiva accordo.", questions: ["Quale distinzione fa fra persona e territorio?", "Perché la Santa Sede rifiuta?", "Che cosa resta irrisolto?"] }
  ],
  workshop: [
    { title: "Motore del cambiamento", prompt: "Quale intreccio spiega meglio l'unificazione?", options: ["Diplomazia e guerre", "Rivoluzioni e reti", "Crisi degli Stati preunitari", "Interazione contingente di tutti e tre"] },
    { title: "Sequenza territoriale", prompt: "Quale passaggio metti al centro?", options: ["Guerra del 1859", "Plebisciti e annessioni", "Conquista del Mezzogiorno", "Veneto e Roma nelle guerre europee"] },
    { title: "Prova primaria", prompt: "Quale documento sostiene la tesi?", options: ["Statuto o legge", "Ultimatum o atto diplomatico", "Plebiscito o decreto", "Legge Pica o Guarentigie"] },
    { title: "Attore escluso", prompt: "Quale prospettiva deve entrare?", options: ["Donne delle reti", "Contadini e comunità", "Soldati borbonici e renitenti", "Cattolici e popolazione pontificia"] },
    { title: "Obiezione", prompt: "Quale spiegazione semplice confuterai?", options: ["Cavour pianificò tutto", "Garibaldi fece tutto", "I plebisciti provarono unanimità", "Il 1870 risolse tutto"] }
  ],
  quiz: [
    { q: "Perché il Piemonte fu un'eccezione dopo il 1849?", options: ["Non perse la guerra", "Mantenne Statuto e Parlamento", "Era una repubblica"], answer: 1, why: "La continuità costituzionale lo rese polo politico, pur con forti poteri regi.", recover: "Statuto e seconda Restaurazione", lesson: "piemonte-laboratorio" },
    { q: "Il connubio fu…", options: ["Un trattato francese", "Un accordo Cavour-Rattazzi", "Una società segreta"], answer: 1, why: "Costruì una maggioranza centrista.", recover: "maggioranze parlamentari", lesson: "piemonte-laboratorio" },
    { q: "Che cosa decise Parigi sull'unità?", options: ["L'approvò", "La affidò a Cavour", "Nulla: discusse senza deliberare"], answer: 2, why: "Il risultato fu di posizione, non territoriale.", recover: "Crimea e Parigi", lesson: "piemonte-europa" },
    { q: "Plombières prevedeva il Regno del 1861?", options: ["Sì", "No: confederazione e regno settentrionale", "Prevedeva una repubblica"], answer: 1, why: "L'esito andò oltre l'intesa.", recover: "accordo e limiti", lesson: "diplomazia-guerra" },
    { q: "Perché l'ultimatum fu decisivo?", options: ["Cedette il Veneto", "Fece apparire l'Austria aggressore", "Sciolse la Società nazionale"], answer: 1, why: "Attivò la condizione dell'alleanza francese.", recover: "fattore scatenante", lesson: "diplomazia-guerra" },
    { q: "Perché Napoleone III fermò la guerra?", options: ["Per un solo ordine britannico", "Per costi, Quadrilatero e rischi politici", "Per la sconfitta di Magenta"], answer: 1, why: "Villafranca rispose a più vincoli.", recover: "armistizio", lesson: "diplomazia-guerra" },
    { q: "Come leggere i plebisciti?", options: ["Referendum perfetti", "Pura finzione", "Consenso reale in consultazioni controllate"], answer: 2, why: "Mobilitazione e organizzazione dall'alto coesistono.", recover: "voto e sovranità", lesson: "annessioni-rivoluzione" },
    { q: "Quali territori furono ceduti alla Francia?", options: ["Lombardia e Veneto", "Nizza e Savoia", "Toscana e Romagna"], answer: 1, why: "Fu il prezzo del riconoscimento francese.", recover: "Trattato di Torino", lesson: "annessioni-rivoluzione" },
    { q: "Che cosa precedette i Mille?", options: ["Una rivolta siciliana", "Porta Pia", "La legge Pica"], answer: 0, why: "La Gancia e la rivolta rurale furono decisive.", recover: "crisi siciliana", lesson: "mille-mezzogiorno" },
    { q: "Le navi britanniche a Marsala provano…", options: ["Un ordine ufficiale", "Una circostanza favorevole, non un ordine dimostrato", "Che lo sbarco non avvenne"], answer: 1, why: "Presenza navale e sostegno ufficiale vanno distinti.", recover: "fonte e inferenza", lesson: "mille-mezzogiorno" },
    { q: "Che cosa mostra Bronte?", options: ["Ogni domanda agraria fu accolta", "Il conflitto fra contadini e tutela della proprietà", "L'assenza dei contadini"], answer: 1, why: "Segna il limite sociale del governo garibaldino.", recover: "questione agraria", lesson: "mille-mezzogiorno" },
    { q: "Perché Vittorio Emanuele rimase II?", options: ["Errore", "Continuità sabauda", "Esisteva un altro re"], answer: 1, why: "VIII legislatura e Statuto segnalavano la stessa continuità.", recover: "legge del 1861", lesson: "costruire-stato" },
    { q: "Quanto era ampio il voto nel 1861?", options: ["Tutti gli adulti", "Circa 419.000 uomini, meno del 2%", "Metà della popolazione"], answer: 1, why: "Censo, alfabetismo, età e sesso restringevano il corpo.", recover: "paese legale", lesson: "costruire-stato" },
    { q: "Il brigantaggio fu…", options: ["Omogeneo", "Un insieme plurale di conflitti", "Solo protesta pacifica"], answer: 1, why: "Componenti politiche, sociali e criminali variarono.", recover: "pluralità", lesson: "costruire-stato" },
    { q: "Che cosa introdusse la legge Pica?", options: ["Suffragio universale", "Tribunali militari e domicilio coatto", "Autonomia siciliana"], answer: 1, why: "Fu legislazione eccezionale.", recover: "garanzie", lesson: "costruire-stato" },
    { q: "Come entrò il Veneto?", options: ["Con la vittoria di Lissa", "Nel quadro della vittoria prussiana", "Con i Mille"], answer: 1, why: "Custoza e Lissa furono sconfitte italiane.", recover: "1866", lesson: "veneto-roma" },
    { q: "Che cosa rese possibile Porta Pia?", options: ["Mentana", "Il ritiro francese", "La legge Pica"], answer: 1, why: "La protezione francese era il vincolo principale.", recover: "questione romana", lesson: "veneto-roma" },
    { q: "Perché le Guarentigie non chiusero la questione?", options: ["Pio IX le rifiutò", "Restituivano tutto", "Abolivano la libertà"], answer: 0, why: "Mancava un accordo fra le parti.", recover: "Roma dopo il 1870", lesson: "veneto-roma" }
  ]
};
