import vm from 'node:vm';
import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
const base=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const repo=path.resolve(base,'../..');
const source=await fs.readFile(path.join(base,'service-worker.js'),'utf8');
const swURL='https://example.test/IV-anno/Storia/schiavitu-liberta/service-worker.js';
const events={};let offline=false,claimed=false,skipped=false;
const key=q=>typeof q==='string'?q:q.url;
const network=async q=>{if(offline)throw Error('Offline simulato');const u=new URL(key(q));const p=path.join(repo,u.pathname.replace(/^\/IV-anno\//,''));return new Response(await fs.readFile(p));};
const buckets=new Map([['foscolo-v10',new Map()],['schiavitu-liberta-obsolete',new Map()]]);
const caches={keys:async()=>[...buckets.keys()],delete:async n=>buckets.delete(n),open:async n=>{if(!buckets.has(n))buckets.set(n,new Map());const b=buckets.get(n);return {addAll:async qs=>{const responses=await Promise.all(qs.map(network));qs.forEach((q,i)=>b.set(key(q),responses[i]));},match:async q=>b.get(key(q))?.clone()};}};
const self={location:new URL(swURL),addEventListener:(n,f)=>events[n]=f,clients:{claim:async()=>{claimed=true;}},skipWaiting:()=>{skipped=true;}};
vm.runInNewContext(source,{self,caches,URL,Request,Response,fetch:network});
let pending;events.install({waitUntil:p=>pending=p});await pending;
events.activate({waitUntil:p=>pending=p});await pending;
assert(claimed);assert(buckets.has('foscolo-v10'));assert(!buckets.has('schiavitu-liberta-obsolete'));
const fetchEvent=async (relative,mode='cors')=>{let response;events.fetch({request:{url:new URL(relative,swURL).href,method:'GET',mode},respondWith:p=>response=p});return response;};
offline=true;let checked=0;
const local=JSON.parse(source.match(/const LOCAL=(.*);/)[1]);const shared=JSON.parse(source.match(/const SHARED=(.*);/)[1]);
for(const p of [...local,...shared]){const r=await fetchEvent(p);assert.equal(r.status,200,p);assert((await r.arrayBuffer()).byteLength>0,p);checked++;}
assert.equal((await fetchEvent('./')).status,200);
assert.equal((await fetchEvent('lezioni/04-stati-uniti.html?from=test')).status,200);
assert((await (await fetchEvent('inesistente.html','navigate')).text()).includes('Sei offline'));
assert.equal(await fetchEvent('../../Letteratura/Foscolo/'),undefined);
assert.equal(await fetchEvent('https://archives.gov/'),undefined);
events.message({data:{type:'SKIP_WAITING'}});assert(skipped);
console.log(`PASS: ${checked} risorse leggibili senza rete; avvio, query, fallback, aggiornamento e isolamento cache verificati.`);
