window.HIST_DATA = {
  meta: {
    title: "L’Europa di fine Ottocento. Politica di massa, imperi e contraddizioni",
    shortTitle: "L’Europa di fine Ottocento",
    storageKey: "storia-europa-fine-ottocento-v1",
    question: "Come poté l’Europa ampliare la partecipazione politica mentre imponeva il proprio dominio a milioni di persone?",
    thesis: "Tra il 1871 e il 1905 l’Europa non seguì una sola via verso la modernità. Francia e Gran Bretagna ampliarono la partecipazione attraverso istituzioni parlamentari; Russia e Austria-Ungheria modernizzarono economia e amministrazione senza risolvere autocrazia e conflitti nazionali. Partiti, sindacati, stampa e alfabetizzazione portarono nuovi gruppi nella politica, ma donne, poveri e minoranze continuarono a incontrare esclusioni. Nello stesso tempo le potenze trasformarono superiorità tecnologica e competizione internazionale in dominio coloniale. La società di massa e l’imperialismo furono quindi processi contemporanei e intrecciati, non due storie separate.",
    workshopIntro: "Costruisci una risposta comparativa. Non basta opporre democrazia e autoritarismo o progresso e barbarie: individua istituzioni, gruppi ammessi ed esclusi, interessi strategici, ideologie di legittimazione, resistenze e conseguenze. Distingui sempre fatti documentati, interpretazioni e giustificazioni prodotte dagli attori dell’epoca.",
    previous: { title: "Crispi e la crisi di fine secolo", url: "../Crispi/" },
    next: { title: "La seconda rivoluzione industriale", url: "#" }
  },
  lessons: [
    {
      id: "europa-contraddittoria", number: 1, title: "Un continente moderno e contraddittorio",
      eyebrow: "Industria, alfabetizzazione e politica di massa", period: "1871-1905",
      question: "Perché il progresso tecnico non produsse automaticamente più libertà e uguaglianza?",
      lead: "Ferrovie, telegrafo, elettricità, chimica e siderurgia accelerarono produzione e comunicazioni. La politica coinvolse pubblici più vasti, ma la partecipazione restò diseguale e lo Stato moderno accrebbe anche la capacità di sorvegliare, mobilitare e reprimere.",
      sections: [
        { title: "Il mondo precedente: élite, notabili e Stati nazionali incompleti", paragraphs: [
          "Nella prima metà dell’Ottocento la politica europea era rimasta in gran parte nelle mani di monarchie, aristocrazie e ristrette élite proprietarie. Le rivoluzioni del 1848 avevano mostrato la forza di richieste nazionali, costituzionali e sociali, ma anche la capacità degli eserciti e delle burocrazie di contenerle.",
          "Dopo il 1871 l’unificazione tedesca e quella italiana modificarono l’equilibrio continentale. La Germania divenne una potenza industriale e militare; la Francia dovette ricostruire il proprio regime; gli imperi russo e asburgico governavano società vastissime e plurali."
        ], summary: "La nuova Europa nacque da rivoluzioni sconfitte, Stati nazionali rafforzati e imperi ancora estesi." },
        { title: "Le fratture: industria, città, scuola e comunicazioni", paragraphs: [
          "La seconda industrializzazione ampliò l’uso dell’acciaio, della chimica, dell’elettricità e del petrolio. Ferrovie e telegrafi ridussero tempi e distanze; banche e grandi imprese concentrarono capitali e decisioni. Le città crebbero attirando lavoratori dalle campagne.",
          "L’alfabetizzazione e la scuola elementare crearono nuovi lettori. Giornali, manifesti, comizi e associazioni trasformarono l’opinione pubblica in una forza politica. La stessa infrastruttura che diffondeva informazioni permetteva però allo Stato di censire, tassare, reclutare e controllare più efficacemente."
        ], summary: "La modernizzazione moltiplicò possibilità di partecipazione e strumenti di controllo." },
        { title: "Attori, gruppi e conflitti: nuovi pubblici, vecchie esclusioni", paragraphs: [
          "Operai, impiegati, insegnanti, piccoli proprietari e professionisti entrarono più stabilmente nella vita pubblica attraverso partiti, sindacati, cooperative e associazioni. I movimenti socialisti discussero se cambiare la società con rivoluzione, riforme o azione sindacale.",
          "La politica di massa non coincise con la democrazia piena. Le donne erano escluse dal voto quasi ovunque; molti uomini restavano fuori per requisiti di reddito, residenza o proprietà; minoranze nazionali e religiose subivano discriminazioni. Nazionalismo e antisemitismo potevano mobilitare le masse contro un nemico interno o esterno."
        ], summary: "La massa entrò nella politica come soggetto organizzato, ma anche come pubblico da conquistare e dirigere." },
        { title: "Il processo storico: organizzare consenso e conflitto", paragraphs: [
          "I vecchi raggruppamenti parlamentari si trasformarono gradualmente in partiti con programmi, sedi locali, giornali e funzionari. I sindacati coordinarono scioperi e rivendicazioni; le Chiese crearono proprie reti associative; gli Stati usarono scuola, esercito e cerimonie per costruire appartenenza nazionale.",
          "La politica divenne più visibile e competitiva. L’allargamento del voto costrinse i governi a cercare consenso, ma non eliminò brogli, clientelismo, repressione e legislazione d’emergenza. La società di massa fu un campo di conflitto, non un risultato già democratico."
        ], summary: "Partecipazione, organizzazione e propaganda crebbero insieme." },
        { title: "Le fonti in dialogo: chi è incluso nel popolo politico?", paragraphs: [
          "Le leggi elettorali mostrano con precisione chi poteva votare e a quali condizioni. Sono fonti normative: descrivono i criteri legali, ma non dicono da sole quanti cittadini riuscissero davvero a registrarsi, votare o influire sulle decisioni.",
          "Confrontare una legge con dati sulla partecipazione, stampa e organizzazioni permette di distinguere diritto formale e capacità politica concreta. Anche il silenzio sulle donne o sui soggetti coloniali è un’informazione storica."
        ], summary: "Per misurare la partecipazione occorre leggere insieme norme, pratiche e esclusioni." },
        { title: "Conseguenze e nuovo assetto: la modernità senza una sola direzione", paragraphs: [
          "La politica europea divenne irreversibilmente più ampia: governi e opposizioni non potevano più ignorare elettori, lavoratori organizzati e opinione pubblica. Crebbero legislazione sociale, istruzione e amministrazione pubblica.",
          "Nello stesso tempo nazionalismo, razzismo scientifico e competizione imperiale usarono strumenti moderni per produrre gerarchie e dominio. La modernità non conteneva una destinazione morale automatica: apriva possibilità che gli attori potevano usare in direzioni opposte."
        ], summary: "L’Europa moderna allargò diritti e capacità statale senza abolire disuguaglianza e coercizione." }
      ],
      source: { id: "suffragio-1884", title: "Il Third Reform Act britannico del 1884", prompt: "Individua chi viene incluso, chi resta escluso e perché una legge elettorale non coincide ancora con il suffragio universale." },
      activity: { type: "compare", title: "Quattro modernità politiche", prompt: "Confronta Francia, Gran Bretagna, Russia e Austria-Ungheria: quale indicatore useresti per misurare partecipazione, controllo e conflitto?" },
      coordinates: ["1871: nuovo equilibrio europeo dopo l’unità tedesca", "Anni 1870-1900: seconda industrializzazione", "1884: ampliamento del voto britannico", "1889: nascita della Seconda Internazionale", "1900: formazione del Labour Representation Committee"],
      essentials: ["La modernizzazione tecnica non determinò automaticamente democratizzazione.", "La politica di massa dipese da alfabetizzazione, stampa e organizzazioni.", "Partiti e sindacati stabilizzarono la partecipazione collettiva.", "L’allargamento del voto rimase incompleto e differenziato.", "Le donne furono escluse dal voto quasi ovunque.", "Lo Stato moderno ampliò insieme servizi e capacità di controllo.", "Nazionalismo e antisemitismo furono strumenti di mobilitazione.", "La società di massa fu un processo conflittuale."],
      vocab: { Politica_di_massa: "Partecipazione politica organizzata di pubblici vasti attraverso voto, partiti, sindacati, stampa e associazioni.", Opinione_pubblica: "Spazio di discussione e mobilitazione formato da stampa, riunioni e reti associative.", Partito_di_massa: "Organizzazione politica stabile con iscritti, sedi, programma, stampa e funzionari.", Nazionalismo: "Ideologia che attribuisce alla nazione un valore politico prioritario, talvolta esclusivo.", Società_di_massa: "Società industriale caratterizzata da grandi organizzazioni, comunicazioni estese e mobilitazione di ampi gruppi." },
      answer: "Il progresso creò risorse, reti e nuovi pubblici, ma non stabilì come usarli. Le istituzioni, i rapporti sociali e le scelte politiche decisero se ferrovie, scuola, stampa e amministrazione avrebbero sostenuto diritti, controllo o espansione imperiale.",
      connections: { map: "Quattro sistemi politici a confronto", people: ["ferry","gladstone","witte"] }
    },
    {
      id: "francia-repubblica", number: 2, title: "La Francia: Comune, Repubblica e affare Dreyfus",
      eyebrow: "Guerra civile, parlamentarismo e diritti", period: "1870-1906",
      question: "Come riuscì una Repubblica nata dalla sconfitta e dalla guerra civile a consolidarsi?",
      lead: "La caduta di Napoleone III aprì una crisi di regime. La Comune di Parigi mostrò la frattura fra capitale sociale e Francia conservatrice; l’incapacità dei monarchici di accordarsi e le leggi del 1875 resero possibile una Repubblica che dovette ancora misurarsi con nazionalismo, antisemitismo e potere militare.",
      sections: [
        { title: "Il mondo precedente: il Secondo Impero e la guerra franco-prussiana", paragraphs: [
          "Il regime di Napoleone III aveva combinato autorità personale, plebisciti e modernizzazione economica. La sconfitta di Sedan del 2 settembre 1870 provocò il crollo dell’Impero e la proclamazione della Repubblica a Parigi due giorni dopo.",
          "L’assedio prussiano, la fame e la capitolazione divisero il paese. Le elezioni del febbraio 1871 produssero un’Assemblea a maggioranza monarchica e favorevole alla pace, mentre Parigi restava armata attraverso la Guardia nazionale."
        ], summary: "La Repubblica nacque senza un consenso repubblicano uniforme e sotto la pressione della sconfitta." },
        { title: "Le fratture: la Comune e la Settimana sanguinosa", paragraphs: [
          "Il 18 marzo 1871 il tentativo governativo di recuperare i cannoni della Guardia nazionale a Montmartre innescò l’insurrezione. La Comune, eletta il 26 marzo, riunì repubblicani radicali, giacobini, blanquisti, proudhoniani e internazionalisti: non fu un governo ideologicamente omogeneo.",
          "La Comune introdusse misure di democrazia municipale e sociale, laicizzò l’istruzione e progettò la gestione operaia delle officine abbandonate. Rimase isolata. Tra il 21 e il 28 maggio l’esercito di Versailles riconquistò Parigi con uccisioni, arresti e deportazioni; i comunardi fucilarono anche alcuni ostaggi."
        ], summary: "La Comune fu insieme rivoluzione municipale, sociale e repubblicana; la sua repressione segnò a lungo la sinistra francese." },
        { title: "Attori, gruppi e conflitti: repubblicani, monarchici, esercito e lavoratori", paragraphs: [
          "Legittimisti e orleanisti condividevano l’avversione alla Repubblica ma non il pretendente al trono. I repubblicani moderati costruirono consenso attraverso amministrazioni locali, scuola e Parlamento; socialisti e movimento operaio si riorganizzarono dopo la repressione.",
          "L’esercito si presentava come custode della nazione. Proprio il prestigio militare rese più difficile riconoscere gli errori nel caso Dreyfus. Stampa, intellettuali, associazioni antisemite e difensori dei diritti trasformarono un processo militare in una crisi nazionale."
        ], summary: "La Repubblica si consolidò dentro un conflitto continuo su nazione, ordine sociale e autorità dell’esercito." },
        { title: "Il processo storico: dalle leggi costituzionali all’affare Dreyfus", paragraphs: [
          "Nel 1875 tre leggi costituzionali organizzarono i poteri pubblici. La Camera era eletta a suffragio universale maschile; il Senato moderava il sistema; il presidente aveva poteri formali rilevanti. La crisi del 1877 consolidò però la prevalenza parlamentare.",
          "Le leggi scolastiche del 1881-1882 resero la scuola primaria gratuita, obbligatoria e laica; nel 1884 i sindacati furono legalizzati. Nel 1894 il capitano ebreo Alfred Dreyfus fu condannato sulla base di prove fragili e manipolate. Il J’accuse di Zola del 1898 rese pubblica la responsabilità delle autorità; la sentenza fu annullata definitivamente nel 1906."
        ], summary: "Istituzioni, scuola e libertà pubbliche stabilizzarono la Repubblica; il caso Dreyfus ne mise alla prova i principi." },
        { title: "Le fonti in dialogo: una Repubblica racconta la propria crisi", paragraphs: [
          "La documentazione parlamentare sulla Comune registra il punto di vista delle istituzioni che combatterono l’insurrezione. È preziosa per date e decisioni, ma va confrontata con manifesti comunardi, testimonianze e studi sulle vittime.",
          "J’accuse è un intervento politico e giudiziario, non una sentenza. La sua forza sta nell’accusa nominativa e pubblica; il suo limite è l’intento polemico. Insieme agli atti processuali mostra come stampa e opinione pubblica possano riaprire un caso chiuso dalle istituzioni."
        ], summary: "Fonti istituzionali e interventi militanti illuminano aspetti diversi della stessa crisi." },
        { title: "Conseguenze e nuovo assetto: la Repubblica diventa una cultura politica", paragraphs: [
          "La sopravvivenza del regime non dipese soltanto dalle leggi del 1875. Scuola, municipi, rituali civili e pratica parlamentare resero la Repubblica un’esperienza quotidiana e una forma di appartenenza.",
          "La crisi Dreyfus rafforzò il campo repubblicano e la difesa dello Stato di diritto, ma rivelò la persistenza di antisemitismo, nazionalismo e autoritarismo. Una democrazia poteva correggersi, ma non era immune dall’ingiustizia."
        ], summary: "La Terza Repubblica si consolidò perché istituzioni e società impararono a difenderla e a correggerla." }
      ],
      source: { id: "comune-parigi", title: "La Comune nella documentazione dell’Assemblea nazionale", prompt: "Distingui cronologia verificabile, linguaggio istituzionale e interpretazione del conflitto." },
      activity: { type: "france", title: "Che cosa salva una Repubblica?", prompt: "Scegli l’elemento decisivo fra istituzioni, scuola, libertà di stampa e mobilitazione civica; poi mostra perché da solo non basta." },
      coordinates: ["4 settembre 1870: proclamazione della Repubblica", "18 marzo-28 maggio 1871: Comune di Parigi", "1875: leggi costituzionali", "1877: crisi e prevalenza parlamentare", "1881-1882: leggi scolastiche", "1894-1906: affare Dreyfus"],
      essentials: ["La Comune nacque dalla guerra, dall’assedio e dal conflitto politico-sociale.", "La Comune riuniva correnti diverse.", "La repressione della Settimana sanguinosa fu durissima.", "I monarchici non riuscirono ad accordarsi sul sovrano.", "Le leggi del 1875 fondarono la Terza Repubblica.", "La crisi del 1877 rafforzò il parlamentarismo.", "La scuola laica contribuì alla cultura repubblicana.", "L’affare Dreyfus rivelò antisemitismo e abuso dell’autorità militare.", "Dreyfus fu riabilitato nel 1906."],
      vocab: { Comune_di_Parigi: "Governo municipale rivoluzionario eletto a Parigi nel marzo 1871.", Settimana_sanguinosa: "Riconquista di Parigi da parte dell’esercito di Versailles, 21-28 maggio 1871.", Terza_Repubblica: "Regime repubblicano francese durato dal 1870 al 1940.", Dreyfusardi: "Sostenitori della revisione del processo a Dreyfus in nome della verità e dei diritti.", Antisemitismo: "Ostilità e discriminazione contro gli ebrei, trasformate nell’Ottocento anche in ideologia politica e razziale." },
      answer: "La Repubblica sopravvisse perché la divisione monarchica lasciò spazio a un compromesso costituzionale e perché i repubblicani costruirono istituzioni, scuola e consenso locale. Le crisi successive non la distrussero: obbligarono cittadini e parlamentari a scegliere se l’onore dello Stato valesse più della giustizia.",
      connections: { map: "Quattro sistemi politici a confronto", people: ["ferry","dreyfus"] }
    },
    {
      id: "gran-bretagna", number: 3, title: "La Gran Bretagna: riforme, Irlanda e Labour",
      eyebrow: "Monarchia parlamentare e integrazione graduale", period: "1884-1906",
      question: "Perché l’ampliamento del voto non risolse la questione sociale né quella irlandese?",
      lead: "Il sistema britannico integrò nuovi elettori senza una rottura rivoluzionaria, ma il suffragio restò incompleto. La Home Rule divise i liberali; sindacati e socialisti costruirono una rappresentanza autonoma dei lavoratori.",
      sections: [
        { title: "Il mondo precedente: Parlamento, impero e suffragio diseguale", paragraphs: [
          "La monarchia britannica era parlamentare, ma il sistema elettorale dell’Ottocento conservava requisiti di proprietà e residenza. Le riforme del 1832 e del 1867 avevano ampliato l’elettorato senza stabilire il principio di un voto per ogni adulto.",
          "Liberali e conservatori erano organizzazioni nazionali sempre più stabili. L’Impero forniva risorse e prestigio, mentre industrializzazione e urbanizzazione rendevano visibile il peso di lavoratori e nuovi ceti medi."
        ], summary: "La stabilità britannica si fondava su adattamenti successivi, non su una democrazia già compiuta." },
        { title: "Le fratture: il Third Reform Act e la mobilitazione irlandese", paragraphs: [
          "La riforma del 1884 uniformò in larga misura i requisiti di voto tra città e campagne, estendendo il diritto a circa due milioni di uomini. La redistribuzione dei collegi del 1885 rese il sistema più coerente.",
          "Restavano escluse tutte le donne e numerosi uomini poveri, domestici o privi di residenza stabile. In Irlanda la mobilitazione per l’autonomia collegava rappresentanza parlamentare, questione agraria e identità nazionale."
        ], summary: "L’elettorato crebbe, ma l’inclusione politica rimase parziale e territorialmente conflittuale." },
        { title: "Attori, gruppi e conflitti: Gladstone, unionisti, trade unions e socialisti", paragraphs: [
          "William Gladstone tentò di concedere l’Home Rule. Il progetto del 1886 fu respinto ai Comuni e provocò la scissione dei liberali unionisti; quello del 1893 passò ai Comuni ma fu bloccato dai Lord.",
          "La Social Democratic Federation guardava al marxismo; l’Independent Labour Party cercava autonomia elettorale; la Fabian Society proponeva riforme graduali fondate su studio e amministrazione. Le nuove trade unions organizzarono anche lavoratori non specializzati."
        ], summary: "La politica britannica integrò nuovi attori, ma Irlanda e lavoro misero in crisi il tradizionale bipartitismo." },
        { title: "Il processo storico: dal sindacato alla rappresentanza politica", paragraphs: [
          "Gli scioperi e la crescita sindacale mostrarono che la contrattazione economica aveva bisogno di tutela legislativa e rappresentanza parlamentare. Il sistema elettorale maggioritario rendeva difficile l’ingresso di piccoli gruppi separati.",
          "Nel 1900 sindacati e organizzazioni socialiste formarono il Labour Representation Committee. Nel 1906 assunse il nome di Labour Party. La nascita del Labour non cancellò differenze ideologiche: creò una sede comune per tradurle in azione parlamentare."
        ], summary: "Il Labour nacque dall’incontro pratico fra sindacato, socialismo e opportunità elettorale." },
        { title: "Le fonti in dialogo: una riforma descritta dal Parlamento", paragraphs: [
          "La pagina storica del Parlamento britannico presenta il Third Reform Act come tappa verso l’uniformità del suffragio. La fonte è autorevole sulla storia istituzionale, ma la formula progressiva può nascondere chi restò escluso.",
          "Il confronto con i dibattiti parlamentari e con le campagne suffragiste mostra che ogni riforma fu il risultato di pressioni e resistenze. La legge non fu un dono spontaneo delle élite."
        ], summary: "La storia istituzionale va completata con i conflitti che resero possibile la riforma." },
        { title: "Conseguenze e nuovo assetto: stabilità attraverso conflitto regolato", paragraphs: [
          "La Gran Bretagna ampliò la cittadinanza politica senza rivoluzione, ma non eliminò disuguaglianze sociali, plural voting e predominio maschile. La Camera dei Lord conservò un potere decisivo nel bloccare riforme.",
          "La questione irlandese rimase aperta; il Labour divenne un nuovo polo politico. L’adattabilità del sistema fu reale, ma dipese dalla capacità di trasformare mobilitazioni esterne in competizione parlamentare."
        ], summary: "La stabilità britannica fu una costruzione dinamica, non assenza di conflitto." }
      ],
      source: { id: "suffragio-1884", title: "Il Third Reform Act britannico del 1884", prompt: "Confronta l’uniformità dei requisiti con le esclusioni ancora presenti." },
      activity: { type: "suffrage", title: "Chi entra nel corpo elettorale?", prompt: "Modifica i criteri di genere, residenza e proprietà e osserva come cambia il significato di rappresentanza." },
      coordinates: ["1884: Third Reform Act", "1885: Redistribution Act", "1886: primo progetto di Home Rule", "1893: secondo progetto bloccato dai Lord", "1884: fondazione della Fabian Society", "1900: Labour Representation Committee", "1906: Labour Party"],
      essentials: ["La Gran Bretagna era una monarchia parlamentare stabile ma non ancora democratica in senso pieno.", "La riforma del 1884 ampliò il voto nelle campagne.", "Donne e molti uomini poveri restarono esclusi.", "La Home Rule mirava all’autonomia interna irlandese.", "Il progetto del 1886 divise i liberali.", "I Lord bloccarono il progetto del 1893.", "Il socialismo britannico comprendeva correnti diverse.", "Le nuove trade unions organizzarono anche lavoratori non specializzati.", "Il Labour nacque dalla collaborazione fra sindacati e gruppi socialisti."],
      vocab: { Third_Reform_Act: "Legge del 1884 che estese nelle contee requisiti elettorali già applicati nei borghi.", Home_Rule: "Progetto di autonomia politica interna per l’Irlanda.", Unionisti: "Avversari dell’autonomia irlandese e difensori dell’unione con la Gran Bretagna.", Fabian_Society: "Organizzazione socialista favorevole a trasformazioni graduali attraverso riforme e amministrazione.", Trade_unions: "Sindacati britannici dei lavoratori.", Labour: "Partito nato per dare rappresentanza parlamentare autonoma al movimento dei lavoratori." },
      answer: "L’ampliamento del voto integrò nuovi uomini nel sistema, ma non affrontò automaticamente proprietà, potere dei Lord, esclusione femminile e dominio sull’Irlanda. Per questo autonomia irlandese e rappresentanza del lavoro richiesero organizzazioni politiche specifiche.",
      connections: { map: "Quattro sistemi politici a confronto", people: ["gladstone"] }
    },
    {
      id: "russia-zarista", number: 4, title: "La Russia zarista: modernizzare senza rappresentare",
      eyebrow: "Autocrazia, campagne e industria", period: "1881-1905",
      question: "Perché la rapida industrializzazione rese più fragile, anziché più stabile, l’autocrazia?",
      lead: "Dopo l’assassinio di Alessandro II, Alessandro III e Nicola II rafforzarono censura, polizia e russificazione. Lo Stato promosse ferrovie e industria, concentrando un nuovo proletariato urbano dentro un sistema privo di rappresentanza nazionale.",
      sections: [
        { title: "Il mondo precedente: emancipazione incompleta e autocrazia", paragraphs: [
          "L’abolizione della servitù della gleba del 1861 liberò milioni di contadini, ma impose pagamenti di riscatto e lasciò spesso terre insufficienti. Il mir ridistribuiva gli appezzamenti e rispondeva collettivamente delle imposte.",
          "Lo zar rimaneva fonte suprema del potere. Non esisteva un parlamento nazionale capace di controllare il governo; burocrazia, Chiesa ortodossa, esercito e polizia sostenevano l’ordine imperiale."
        ], summary: "La riforma agraria modificò lo status personale senza risolvere povertà rurale e assenza di rappresentanza." },
        { title: "Le fratture: assassinio, reazione e russificazione", paragraphs: [
          "L’uccisione di Alessandro II nel 1881 da parte dell’organizzazione rivoluzionaria Narodnaja Volja convinse il nuovo zar Alessandro III a chiudere le aperture riformatrici. Censura e polizia politica furono rafforzate.",
          "Le nazionalità non russe subirono pressioni linguistiche, religiose e amministrative. Dopo i pogrom del 1881-1882 le Leggi di maggio limitarono ulteriormente residenza e attività economiche degli ebrei. La ricerca storica non sostiene un’unica regia statale per tutti i pogrom, ma documenta discriminazione legale, tolleranza e complicità locali."
        ], summary: "La reazione trasformò diversità nazionale e religiosa in un problema di sicurezza imperiale." },
        { title: "Attori, gruppi e conflitti: contadini, operai, minoranze e rivoluzionari", paragraphs: [
          "La maggioranza della popolazione restava contadina. Il mir offriva solidarietà e accesso alla terra, ma limitava mobilità e investimenti individuali. Carestie, tasse e pagamenti di riscatto alimentavano insicurezza.",
          "L’industrializzazione creò operai concentrati a San Pietroburgo, Mosca, nel Donec, in Polonia e a Baku. Liberali, populisti, socialisti rivoluzionari e marxisti proponevano vie diverse contro l’autocrazia; le minoranze nazionali intrecciavano diritti civili e autonomia."
        ], summary: "La Russia non aveva un’opposizione unica: gruppi diversi condividevano il rifiuto dell’autocrazia per ragioni differenti." },
        { title: "Il processo storico: Witte, ferrovie e capitale straniero", paragraphs: [
          "Negli anni Novanta il ministro Sergej Witte usò protezione doganale, investimenti pubblici, capitali stranieri e costruzione ferroviaria per accelerare siderurgia, carbone, petrolio e meccanica. La Transiberiana collegò territori e obiettivi strategici.",
          "La crescita fu rapida ma concentrata. Fabbriche grandi e disciplina severa facilitarono scioperi e organizzazione clandestina. Lo Stato voleva una società economicamente moderna senza accettarne le domande politiche."
        ], summary: "L’industrializzazione rafforzò lo Stato e, nello stesso tempo, concentrò nuovi soggetti capaci di sfidarlo." },
        { title: "Le fonti in dialogo: le Leggi di maggio e il loro contesto", paragraphs: [
          "Le norme del 1882 limitarono l’insediamento ebraico nei villaggi della Zona di residenza. Una legge documenta la discriminazione istituzionale; non spiega da sola i meccanismi locali della violenza.",
          "Gli studi YIVO invitano a distinguere politiche statali, iniziative locali, voci, interessi economici e azione delle folle. Questa distinzione evita sia di assolvere lo Stato sia di attribuirgli automaticamente ogni singolo episodio."
        ], summary: "Il rigore storico richiede di collegare discriminazione legale e violenza senza confonderne i livelli causali." },
        { title: "Conseguenze e nuovo assetto: verso la crisi del 1905", paragraphs: [
          "L’espansione in Estremo Oriente portò allo scontro con il Giappone. Le sconfitte militari del 1904-1905 indebolirono il prestigio dello zar e aggravarono la crisi economica.",
          "Scioperi, proteste contadine e rivendicazioni nazionali confluirono nella rivoluzione del 1905. La modernizzazione non aveva prodotto automaticamente liberalismo; aveva creato risorse e attori che l’autocrazia non sapeva rappresentare."
        ], summary: "La crisi nacque dall’incontro fra vecchi problemi agrari, repressione politica e nuove concentrazioni industriali." }
      ],
      source: { id: "leggi-maggio", title: "Le Leggi di maggio del 1882", prompt: "Separa il contenuto discriminatorio della norma dalle interpretazioni sulle responsabilità dei pogrom." },
      activity: { type: "autocracy", title: "Modernizzare l’Impero", prompt: "Bilancia investimenti industriali, repressione e rappresentanza: quali tensioni produci nel breve e nel lungo periodo?" },
      coordinates: ["1861: abolizione della servitù della gleba", "1881: assassinio di Alessandro II", "1882: Leggi di maggio", "1891: avvio della Transiberiana", "1894: ascesa di Nicola II", "1904-1905: guerra russo-giapponese", "1905: rivoluzione"],
      essentials: ["La Russia rimase un’autocrazia priva di governo parlamentare.", "L’emancipazione del 1861 non risolse la questione contadina.", "Il mir distribuiva terre ed era responsabile delle imposte collettive.", "Alessandro III rafforzò reazione e russificazione.", "Gli ebrei subirono pogrom e discriminazioni legali.", "Non tutti i pogrom ebbero la stessa dinamica o una regia centrale documentata.", "Witte promosse industrializzazione e ferrovie.", "Il capitale straniero ebbe un ruolo importante.", "Il proletariato era limitato ma concentrato.", "La contraddizione fra modernizzazione economica e chiusura politica preparò il 1905."],
      vocab: { Autocrazia: "Sistema nel quale il sovrano concentra il potere senza responsabilità verso un parlamento.", Mir: "Comunità rurale responsabile della distribuzione periodica delle terre e degli obblighi collettivi.", Russificazione: "Politica di imposizione della lingua, cultura e istituzioni russe alle nazionalità dell’Impero.", Pogrom: "Violenza collettiva contro comunità ebraiche, favorita da ostilità sociali, propaganda e tolleranza o complicità delle autorità.", Transiberiana: "Ferrovia costruita per collegare la Russia europea alla Siberia e al Pacifico." },
      answer: "L’industria accrebbe entrate, infrastrutture e potenza militare, ma concentrò lavoratori, conflitti e informazioni. Senza rappresentanza e libertà organizzativa, ogni rivendicazione tendeva a diventare opposizione al regime. La sconfitta militare del 1905 fece convergere queste tensioni.",
      connections: { map: "Quattro sistemi politici a confronto", people: ["witte","nicola"] }
    },
    {
      id: "austria-ungheria", number: 5, title: "L’Austria-Ungheria: una monarchia, molti popoli",
      eyebrow: "Compromesso, costituzioni e nazionalità", period: "1867-1905",
      question: "Perché il Compromesso del 1867 stabilizzò l’Impero senza risolverne la questione nazionale?",
      lead: "La duplice monarchia riconobbe l’autonomia politica dell’Ungheria ma lasciò tedeschi e magiari in posizione dominante. Parlamentarismo, sviluppo economico e vita culturale convivevano con conflitti linguistici e richieste di autonomia.",
      sections: [
        { title: "Il mondo precedente: un Impero dinastico multinazionale", paragraphs: [
          "Gli Asburgo governavano territori abitati da tedeschi, magiari, cechi, slovacchi, polacchi, ruteni, romeni, croati, serbi, sloveni, italiani e altri gruppi. Le rivoluzioni del 1848 avevano mostrato che costituzione e nazionalità potevano allearsi o scontrarsi.",
          "La sconfitta contro la Prussia nel 1866 escluse l’Austria dalla guida del mondo tedesco e rese necessario un accordo con l’élite magiara, capace di paralizzare il governo imperiale."
        ], summary: "La crisi del 1866 trasformò la pluralità nazionale in un problema costituzionale urgente." },
        { title: "Le fratture: l’Ausgleich del 1867", paragraphs: [
          "Il Compromesso creò due entità: Cisleitania austriaca e Transleitania ungherese. Avevano governi e parlamenti distinti, ma condividevano il sovrano e i ministeri degli Esteri, della Guerra e delle finanze comuni.",
          "L’accordo soddisfece soprattutto le élite tedesco-austriache e magiare. Non trasformò l’Impero in una federazione di popoli eguali e lasciò irrisolte molte domande di autonomia linguistica e politica."
        ], summary: "Il dualismo risolse il conflitto con l’Ungheria privilegiandolo rispetto agli altri." },
        { title: "Attori, gruppi e conflitti: élite dominanti e nazionalità organizzate", paragraphs: [
          "Partiti, giornali, associazioni culturali e scuole resero la nazionalità un’esperienza politica quotidiana. Cechi e slavi meridionali chiedevano autonomia; in Ungheria le politiche di magiarizzazione aumentarono le tensioni con slovacchi, romeni, croati e serbi.",
          "Identità nazionale, classe e territorio non coincidevano sempre. Nelle città multilingui un individuo poteva cambiare lingua d’uso o appartenenza dichiarata; contadini, aristocratici e borghesi dello stesso gruppo nazionale avevano interessi sociali differenti."
        ], summary: "Le nazionalità erano movimenti politici costruiti e plurali, non blocchi naturali immutabili." },
        { title: "Il processo storico: governare attraverso compromessi incompleti", paragraphs: [
          "Il sistema possedeva parlamenti, amministrazioni, stampa e tribunali; non era un semplice despotismo immobile. In Austria il suffragio si ampliò gradualmente, mentre in Ungheria rimase più ristretto e il predominio magiaro più forte.",
          "I governi negoziavano lingua amministrativa, scuola, bilanci e autonomie. Ogni concessione a un gruppo poteva apparire minaccia agli altri. L’assenza di una soluzione federale condivisa trasformò il Parlamento in luogo di rappresentanza e, insieme, di ostruzionismo."
        ], summary: "La costituzione rese visibili i conflitti senza creare un principio accettato per risolverli." },
        { title: "Le fonti in dialogo: la struttura costituzionale del dualismo", paragraphs: [
          "Le norme del 1867 chiariscono quali materie fossero comuni e quali separate. Sono indispensabili per evitare l’immagine di un Impero privo di istituzioni, ma riflettono il linguaggio giuridico dei soggetti riconosciuti.",
          "Ciò che la costituzione non concede è altrettanto importante: le altre nazionalità non possedevano un rapporto paritario con il sovrano. Le petizioni e i programmi nazionali mostrano il divario fra legalità del dualismo e richieste federali."
        ], summary: "La struttura costituzionale stabilizzò due centri di potere e rese periferiche molte altre domande." },
        { title: "Conseguenze e nuovo assetto: la questione balcanica", paragraphs: [
          "L’Impero conobbe crescita economica, urbanizzazione e grande vitalità culturale. La sua debolezza non fu semplice arretratezza, ma difficoltà nel trasformare pluralità e disuguaglianze in un patto politico legittimo.",
          "L’espansione nei Balcani e l’occupazione della Bosnia-Erzegovina dal 1878 accrebbero la rivalità con Russia e Serbia. Le tensioni interne si collegarono così alla competizione internazionale."
        ], summary: "La monarchia sopravvisse attraverso compromessi, ma ogni compromesso parziale accumulò nuove fratture." }
      ],
      source: { id: "ausgleich", title: "Le leggi costituzionali austro-ungariche del 1867", prompt: "Individua quali popoli diventano soggetti del compromesso e quali restano oggetto di governo." },
      activity: { type: "nationalities", title: "Progettare una federazione impossibile?", prompt: "Scegli quali autonomie riconoscere e valuta gli effetti su bilancio, esercito, lingue e rappresentanza." },
      coordinates: ["1866: sconfitta austriaca contro la Prussia", "1867: Compromesso austro-ungarico", "1868: accordo croato-ungherese", "1878: occupazione della Bosnia-Erzegovina", "1897: crisi linguistica in Austria"],
      essentials: ["L’Austria-Ungheria nacque dal Compromesso del 1867.", "Austria e Ungheria avevano governi e parlamenti distinti.", "Sovrano, Esteri, Guerra e alcune finanze erano comuni.", "Il sistema era costituzionale ma non pienamente democratico.", "Tedeschi e magiari conservarono posizioni dominanti.", "Le altre nazionalità chiedevano autonomia e uguaglianza linguistica.", "Nazionalità e classe non coincidevano automaticamente.", "Il Parlamento rappresentava i conflitti ma spesso non riusciva a comporli.", "La politica balcanica collegò tensioni interne e rivalità internazionali."],
      vocab: { Ausgleich: "Compromesso del 1867 che istituì la duplice monarchia austro-ungarica.", Cisleitania: "Nome informale della parte austriaca della duplice monarchia.", Transleitania: "Nome informale della parte ungherese della duplice monarchia.", Magiarizzazione: "Politiche volte a diffondere lingua e identità magiare nel Regno d’Ungheria.", Federalismo: "Sistema che distribuisce poteri costituzionalmente garantiti fra centro ed entità territoriali." },
      answer: "Il Compromesso stabilizzò il rapporto fra dinastia e Ungheria, ma trasformò un problema multinazionale in un accordo tra due élite dominanti. Le altre nazionalità ottennero spazi di organizzazione e rappresentanza, non una posizione paritaria; perciò ogni crisi interna poteva intrecciarsi con le rivalità balcaniche.",
      connections: { map: "Quattro sistemi politici a confronto", people: ["francesco"] }
    },
    {
      id: "imperialismo-cause", number: 6, title: "Imperialismo: potenza, mercato e ideologia",
      eyebrow: "Dalla colonia al sistema globale di dominio", period: "1875-1914",
      question: "Perché negli ultimi decenni dell’Ottocento la conquista coloniale accelerò così rapidamente?",
      lead: "Nessuna causa da sola spiega l’imperialismo. Interessi economici, controllo di rotte, prestigio nazionale, innovazioni militari e ideologie razziste interagirono in modo diverso da territorio a territorio.",
      sections: [
        { title: "Il mondo precedente: imperi commerciali e conquiste già esistenti", paragraphs: [
          "Il colonialismo europeo non nacque nel 1880. Spagna, Portogallo, Paesi Bassi, Francia e Gran Bretagna possedevano da secoli territori oltremare; l’India britannica passò direttamente alla Corona nel 1858 e l’Algeria era occupata dalla Francia dal 1830.",
          "La novità dell’ultimo quarto dell’Ottocento fu la velocità della conquista, la competizione simultanea fra potenze e la combinazione di annessione, protettorati, basi, sfere d’influenza e controllo finanziario."
        ], summary: "L’imperialismo fu una nuova intensità e organizzazione del dominio coloniale, non un inizio assoluto." },
        { title: "Le fratture: tecnologia, crisi economica e competizione strategica", paragraphs: [
          "Navi a vapore, telegrafo, ferrovie, armi a ripetizione e progressi della medicina tropicale ridussero alcuni costi della conquista. Il Canale di Suez rese decisivo il controllo della rotta verso l’India.",
          "Imprese e governi cercavano materie prime, investimenti e mercati, ma non tutte le colonie furono redditizie. La crisi economica e il protezionismo aumentarono la competizione; prestigio e sicurezza delle rotte potevano contare più del profitto immediato."
        ], summary: "La capacità tecnica rese possibile l’espansione; economia e strategia ne orientarono tempi e luoghi." },
        { title: "Attori, gruppi e conflitti: governi, imprese, missionari e società africane e asiatiche", paragraphs: [
          "Compagnie private, banche, ufficiali, esploratori, missionari e società geografiche produssero informazioni e pressioni. I governi non controllavano sempre l’avvio della penetrazione, ma intervenivano per proteggere investimenti e trasformare occupazioni precarie in sovranità.",
          "Le società colonizzate negoziarono, resistettero, combatterono o usarono rivalità europee. Trattati firmati in condizioni di disuguaglianza vennero spesso interpretati dagli europei come cessioni di sovranità che i firmatari locali non intendevano riconoscere."
        ], summary: "La conquista fu un processo di interazione violenta, non l’avanzata incontrastata di un solo attore." },
        { title: "Il processo storico: la Conferenza di Berlino e l’occupazione effettiva", paragraphs: [
          "La Conferenza di Berlino del 1884-1885 discusse commercio nei bacini del Congo e del Niger, navigazione e regole di notifica delle occupazioni costiere. Non tracciò da sola tutti i confini dell’Africa.",
          "Il principio di occupazione effettiva incoraggiò le potenze a trasformare pretese cartografiche in presenza amministrativa e militare. Accordi bilaterali, guerre e spedizioni completarono una spartizione che proseguì fino al primo Novecento."
        ], summary: "Berlino fissò regole della competizione e ne accelerò la materializzazione sul territorio." },
        { title: "Le fonti in dialogo: l’Atto generale di Berlino", paragraphs: [
          "Il testo presenta libero commercio, lotta alla tratta e tutela delle popolazioni come obiettivi dichiarati. Sono formule normative prodotte dalle potenze che organizzavano la conquista.",
          "Confrontare questi principi con lavoro forzato, espropriazioni e violenze permette di distinguere giustificazione e pratica. La fonte non è falsa perché interessata: documenta il linguaggio con cui il dominio cercava legittimità."
        ], summary: "La retorica civilizzatrice va studiata come parte attiva dell’imperialismo." },
        { title: "Conseguenze e nuovo assetto: un mondo gerarchizzato", paragraphs: [
          "L’imperialismo subordinò economie locali all’esportazione, impose tassazione e lavoro, ridisegnò territori e gerarchie. Porti e ferrovie furono costruiti soprattutto per controllo militare ed estrazione.",
          "Le potenze ottennero basi e prestigio, ma anche nuovi costi e rivalità. Non esiste un rapporto automatico fra imperialismo e Prima guerra mondiale; la competizione coloniale alimentò però diffidenza, nazionalismo e accettazione della forza."
        ], summary: "L’espansione creò imperi globali e società colonizzate trasformate, senza cancellarne l’azione e le resistenze." }
      ],
      source: { id: "berlino", title: "L’Atto generale della Conferenza di Berlino", prompt: "Confronta obiettivi dichiarati e meccanismi concreti dell’occupazione." },
      activity: { type: "causes", title: "Una spiegazione pluricausale", prompt: "Attribuisci peso a economia, strategia, politica, tecnologia e ideologia; poi giustifica perché la combinazione cambia nei diversi casi." },
      coordinates: ["1869: apertura del Canale di Suez", "1875: acquisto britannico delle azioni egiziane del canale", "1882: occupazione britannica dell’Egitto", "1884-1885: Conferenza di Berlino", "1898: crisi di Fashoda"],
      essentials: ["Colonialismo e imperialismo non sono sinonimi perfetti.", "L’imperialismo comprende anche protettorati, basi e controllo finanziario.", "Non esiste una causa unica dell’espansione.", "Tecnologia e medicina facilitarono conquista e amministrazione.", "Rotte e prestigio potevano contare quanto il profitto.", "Non tutte le colonie furono immediatamente redditizie.", "La missione civilizzatrice fu una giustificazione ideologica.", "Il razzismo scientifico trasformò differenze in gerarchie.", "La Conferenza di Berlino non disegnò da sola tutti i confini africani.", "Le popolazioni colonizzate agirono e resistettero."],
      vocab: { Colonialismo: "Possesso e amministrazione di territori esterni da parte di una potenza.", Imperialismo: "Sistema più ampio di dominio politico, economico e strategico, anche senza annessione formale.", Protettorato: "Territorio formalmente autonomo ma controllato da una potenza estera.", Sfera_d_influenza: "Area nella quale una potenza ottiene privilegi senza annessione completa.", Occupazione_effettiva: "Criterio secondo cui una pretesa coloniale richiedeva presenza e capacità di amministrazione.", Darwinismo_sociale: "Applicazione impropria della selezione naturale alle società umane per giustificare gerarchie." },
      answer: "L’accelerazione nacque dalla convergenza di capacità tecnica, competizione internazionale, interessi economici e linguaggi razzisti. La combinazione non fu identica ovunque: in alcuni casi dominò la rotta strategica, in altri imprese e risorse, in altri ancora il prestigio. Berlino rese la competizione più regolata fra europei e più violenta sui territori.",
      connections: { map: "Imperi, rotte e sfere d’influenza", people: ["ferry","leopoldo","rhodes"] }
    },
    {
      id: "africa-spartita", number: 7, title: "Africa: conquista, sfruttamento e resistenze",
      eyebrow: "Dalla carta al controllo del territorio", period: "1880-1914",
      question: "Come riuscirono poche potenze europee a conquistare gran parte dell’Africa e perché il dominio non fu mai totale?",
      lead: "Superiorità militare, rivalità locali, trattati diseguali e infrastrutture permisero conquiste rapide. Ma gli Stati e le società africane adottarono strategie diverse: guerra, diplomazia, migrazione, adattamento e ribellione.",
      sections: [
        { title: "Il mondo precedente: Stati, reti e sovranità africane", paragraphs: [
          "Prima della spartizione l’Africa non era uno spazio politico vuoto. Regni, imperi, città commerciali, comunità rurali e reti islamiche o cristiane organizzavano potere e scambi. Le relazioni con Europa e mondo islamico avevano già una lunga storia.",
          "Le conoscenze europee dell’interno erano incomplete e dipendevano spesso da guide, intermediari e autorità locali. Le mappe coloniali cancellarono questa pluralità rappresentando territori come disponibili."
        ], summary: "La conquista si impose su società politiche esistenti, non su un continente senza storia." },
        { title: "Le fratture: occupazioni britanniche, francesi, tedesche e italiane", paragraphs: [
          "La Gran Bretagna occupò l’Egitto nel 1882, riconquistò il Sudan nel 1896-1898 e consolidò territori in Africa occidentale e australe. La Francia costruì un vasto impero dall’Algeria verso Africa occidentale e centrale e rese il Madagascar colonia nel 1896.",
          "La Germania entrò tardi nella corsa con Togo, Camerun, Africa del Sud-Ovest e Africa orientale. L’Italia occupò Massaua nel 1885, proclamò l’Eritrea nel 1890 e avanzò in Somalia, ma fu sconfitta dall’Etiopia ad Adua nel 1896."
        ], summary: "Le potenze seguirono strategie diverse e incontrarono resistenze capaci, in alcuni casi, di arrestarle." },
        { title: "Attori, gruppi e conflitti: eserciti africani, intermediari e civili", paragraphs: [
          "Menelik II acquistò armi, costruì alleanze e mobilitò un grande esercito per difendere l’Etiopia. Samori Touré combatté a lungo contro l’espansione francese; il Mahdismo oppose al dominio egiziano e britannico un progetto politico-religioso.",
          "La conquista usò anche intermediari africani, truppe coloniali e rivalità regionali. Le categorie coloniale e africana non descrivono due blocchi uniformi. I civili pagarono tasse, requisizioni, deportazioni e lavoro forzato."
        ], summary: "Il dominio fu costruito attraverso guerre, collaborazioni forzate e conflitti interni alle società coinvolte." },
        { title: "Il processo storico: dal trattato alla coercizione", paragraphs: [
          "Accordi firmati con autorità locali vennero tradotti dalle potenze come protettorati; spedizioni militari trasformarono le pretese in controllo. Confini tracciati per negoziato europeo divisero comunità e unirono territori diversi sotto nuove amministrazioni.",
          "Nello Stato Libero del Congo, dal 1885 al 1908 sovranità personale di Leopoldo II e non normale colonia belga, concessioni e raccolta del caucciù produssero lavoro forzato, ostaggi, mutilazioni e spedizioni punitive. La denuncia internazionale contribuì al passaggio del territorio allo Stato belga nel 1908."
        ], summary: "La sovranità coloniale nacque dalla conversione di accordi e mappe in amministrazione armata e lavoro imposto." },
        { title: "Le fonti in dialogo: il Congo fra archivio e propaganda", paragraphs: [
          "I documenti ufficiali dello Stato Libero parlavano di commercio, ordine e lotta alla schiavitù. Rapporti missionari, testimonianze congolesi, fotografie e inchieste registrarono coercizione e violenza.",
          "Le fotografie non sono finestre neutrali: furono selezionate per denunciare o giustificare. Gli archivi del Royal Museum for Central Africa permettono di studiare insieme amministrazione coloniale, collezioni e memorie congolesi."
        ], summary: "La pluralità delle fonti è necessaria perché il dominio controllava anche la produzione del racconto." },
        { title: "Conseguenze e nuovo assetto: confini, economie e memorie", paragraphs: [
          "Tassazione e lavoro obbligarono molte famiglie a entrare nell’economia monetaria. Colture e miniere furono orientate all’esportazione; infrastrutture collegarono aree produttive a porti e centri amministrativi.",
          "I confini coloniali non causarono automaticamente ogni conflitto futuro, ma imposero nuovi Stati e gerarchie. Resistenze, scuole missionarie, lavoro urbano e nuove élite alimentarono nel tempo linguaggi nazionalisti e anticoloniali."
        ], summary: "Il colonialismo trasformò territori e società senza renderli passivi o privi di memoria politica." }
      ],
      source: { id: "congo", title: "Lo Stato Libero del Congo negli archivi del Royal Museum", prompt: "Confronta linguaggio amministrativo, testimonianze e uso pubblico delle immagini." },
      activity: { type: "empire", title: "Cambiare il punto di osservazione", prompt: "Leggi la stessa ferrovia dal punto di vista di governo coloniale, impresa, lavoratori reclutati e comunità attraversate." },
      coordinates: ["1882: occupazione britannica dell’Egitto", "1885: Stato Libero del Congo e occupazione italiana di Massaua", "1890: proclamazione dell’Eritrea", "1896: Adua e Madagascar colonia francese", "1898: sconfitta mahdista a Omdurman", "1899-1902: guerra anglo-boera", "1908: Congo allo Stato belga"],
      essentials: ["L’Africa precoloniale possedeva Stati e reti politiche diverse.", "Le potenze usarono tecnologia, trattati e rivalità locali.", "La Gran Bretagna controllò Egitto e Sudan.", "La Francia costruì un vasto impero in Africa occidentale e centrale.", "La Germania entrò tardi nella corsa coloniale.", "L’Italia conquistò Eritrea e Somalia ma fu sconfitta ad Adua.", "L’Etiopia e la Liberia conservarono formalmente l’indipendenza.", "Lo Stato Libero del Congo fu sovranità personale di Leopoldo II fino al 1908.", "Il lavoro forzato e la raccolta del caucciù provocarono violenze enormi.", "Le società africane resistettero con guerra, diplomazia e adattamento.", "I confini coloniali trasformarono le realtà politiche locali."],
      vocab: { Scramble_for_Africa: "Rapida competizione per la conquista dell’Africa dagli anni Ottanta dell’Ottocento.", Stato_Libero_del_Congo: "Territorio sotto sovranità personale di Leopoldo II dal 1885 al 1908.", Lavoro_forzato: "Prestazione imposta mediante legge, tassazione, coercizione o violenza.", Truppe_coloniali: "Soldati reclutati nei territori dominati e impiegati dagli eserciti imperiali.", Confine_coloniale: "Linea stabilita dalle potenze che spesso ignorava organizzazioni e reti locali." },
      answer: "Le potenze combinarono armi, infrastrutture, trattati e alleanze locali, ma il controllo richiese coercizione continua. Adua dimostrò che la superiorità europea non era inevitabile; ribellioni e adattamenti mostrarono che la sovranità coloniale rimase contestata. La conquista fu rapida, il dominio mai assoluto.",
      connections: { map: "Imperi, rotte e sfere d’influenza", people: ["leopoldo","rhodes","menelik"] }
    },
    {
      id: "asia-giappone", number: 8, title: "Asia: sovranità limitata e ascesa del Giappone",
      eyebrow: "Cina, sfere d’influenza e guerra russo-giapponese", period: "1894-1905",
      question: "Perché la vittoria giapponese del 1905 cambiò il significato mondiale dell’imperialismo?",
      lead: "Gran parte dell’Asia non fu annessa direttamente. Trattati diseguali, porti, concessioni e sfere d’influenza limitarono la sovranità di Stati esistenti. Il Giappone modernizzato entrò nel sistema imperiale e sconfisse una grande potenza europea.",
      sections: [
        { title: "Il mondo precedente: imperi asiatici e penetrazione europea", paragraphs: [
          "L’India era amministrata dalla Corona britannica dal 1858; Francia e Paesi Bassi consolidavano Indocina e Indie orientali; la Russia avanzava in Asia centrale. Persia e Impero ottomano subivano pressioni finanziarie e strategiche.",
          "L’Impero Qing conservava istituzioni e sovranità formale, ma le guerre dell’oppio avevano imposto porti aperti, extraterritorialità e cessioni territoriali. La penetrazione non richiedeva sempre una colonia diretta."
        ], summary: "In Asia il dominio operò spesso attraverso trattati e concessioni dentro Stati ancora esistenti." },
        { title: "Le fratture: la guerra sino-giapponese e le sfere d’influenza", paragraphs: [
          "La vittoria giapponese del 1894-1895 mostrò l’efficacia delle riforme Meiji. Con il Trattato di Shimonoseki la Cina riconobbe l’indipendenza della Corea, cedette Taiwan e le Pescadores e accettò indennità e concessioni.",
          "Russia, Francia e Germania imposero al Giappone la restituzione di Liaodong. Poco dopo ottennero propri territori in affitto e privilegi. La Cina non fu spartita completamente perché le potenze erano concorrenti e lo Stato Qing conservava capacità di resistenza."
        ], summary: "La sconfitta cinese accelerò la penetrazione straniera e rivelò una nuova potenza asiatica." },
        { title: "Attori, gruppi e conflitti: Qing, Boxer, potenze e Giappone", paragraphs: [
          "Funzionari riformatori cinesi cercavano di rafforzare esercito e amministrazione; gruppi diversi attribuivano la crisi a stranieri, missionari o dinastia. La rivolta dei Boxer del 1899-1901 attaccò presenze straniere e cristiani cinesi.",
          "Una coalizione internazionale represse la rivolta e impose nuove indennità. Il Giappone partecipò come potenza e non come semplice vittima dell’espansione europea: modernizzazione e imperialismo procedettero insieme."
        ], summary: "L’opposizione allo straniero non era un movimento unico, e il Giappone entrò attivamente nell’ordine imperiale." },
        { title: "Il processo storico: dalla Corea a Portsmouth", paragraphs: [
          "Russia e Giappone si scontrarono per Corea e Manciuria. Nella notte fra l’8 e il 9 febbraio 1904 il Giappone attaccò la flotta russa a Port Arthur prima della dichiarazione formale di guerra.",
          "Le vittorie terrestri e navali giapponesi culminarono nella distruzione della flotta russa a Tsushima. Il Trattato di Portsmouth del settembre 1905 riconobbe la prevalenza giapponese in Corea, diritti nella Manciuria meridionale e la cessione della parte meridionale di Sachalin."
        ], summary: "La guerra trasferì influenza e diritti imperiali dalla Russia al Giappone senza liberare Corea e Manciuria dal dominio esterno." },
        { title: "Le fonti in dialogo: il Trattato di Portsmouth", paragraphs: [
          "Un trattato di pace documenta ciò che gli Stati vincitori e sconfitti accettano formalmente. Non registra direttamente la voce delle popolazioni coreane, cinesi o mancesi sulle quali ricadono le decisioni.",
          "La sintesi dell’Office of the Historian consente di ricostruire negoziato e clausole; va confrontata con fonti asiatiche e con gli effetti successivi per evitare una storia limitata alla diplomazia delle grandi potenze."
        ], summary: "La diplomazia rende visibili i rapporti fra Stati e può rendere invisibili i popoli amministrati." },
        { title: "Conseguenze e nuovo assetto: il mito europeo è spezzato", paragraphs: [
          "La vittoria del Giappone dimostrò che una potenza asiatica industrializzata poteva battere un impero europeo. Nazionalisti e anticolonialisti dall’India all’Egitto lessero l’evento come prova che la supremazia europea non era inevitabile.",
          "Il risultato non fu però anticoloniale in sé. Il Giappone consolidò il controllo sulla Corea e costruì un proprio impero. Il 1905 aprì possibilità di emancipazione simbolica e una nuova competizione imperiale."
        ], summary: "La vittoria incrinò la gerarchia razziale europea ma non abolì la logica dell’impero." }
      ],
      source: { id: "portsmouth", title: "Il Trattato di Portsmouth del 1905", prompt: "Individua chi decide, su quali territori e quali soggetti non hanno voce nel testo diplomatico." },
      activity: { type: "asia", title: "Vittoria contro l’Europa o nuovo imperialismo?", prompt: "Valuta il 1905 con due lenti: significato anticoloniale e costruzione dell’impero giapponese." },
      coordinates: ["1894-1895: prima guerra sino-giapponese", "1895: Trattato di Shimonoseki", "1898: concessioni straniere in Cina", "1899-1901: rivolta dei Boxer", "1902: alleanza anglo-giapponese", "1904-1905: guerra russo-giapponese", "5 settembre 1905: Trattato di Portsmouth"],
      essentials: ["In Asia il dominio fu spesso indiretto.", "La Cina conservò sovranità formale ma subì trattati e concessioni.", "Il Giappone sconfisse la Cina nel 1894-1895.", "La Triplice interferenza impose la restituzione di Liaodong.", "Le potenze crearono sfere d’influenza in Cina.", "La rivolta dei Boxer fu repressa da una coalizione internazionale.", "Russia e Giappone si contesero Corea e Manciuria.", "Il Giappone vinse la guerra del 1904-1905.", "Portsmouth riconobbe interessi giapponesi e trasferì diritti russi.", "La vittoria ebbe enorme significato simbolico anticoloniale.", "Il Giappone divenne a sua volta una potenza imperiale."],
      vocab: { Trattati_diseguali: "Accordi imposti a Stati asiatici con privilegi commerciali, territoriali o giudiziari per potenze straniere.", Extraterritorialità: "Privilegio che sottrae stranieri alla giurisdizione locale.", Boxer: "Movimento cinese ostile alla presenza straniera e alle missioni cristiane.", Manciuria: "Regione della Cina nordorientale contesa da Russia e Giappone.", Trattato_di_Portsmouth: "Pace del 1905 che concluse la guerra russo-giapponese.", Impero_Meiji: "Giappone trasformato dalle riforme avviate nel 1868 e divenuto potenza industriale e militare." },
      answer: "Il 1905 distrusse l’idea dell’invincibilità europea e offrì un simbolo ai movimenti anticoloniali. Tuttavia il vincitore non rifiutò l’imperialismo: ne conquistò strumenti e territori. La svolta mondiale fu quindi ambivalente, emancipatrice nell’immaginario e imperiale nei rapporti di potere.",
      connections: { map: "Imperi, rotte e sfere d’influenza", people: ["mutsuhito","witte"] }
    }
  ],
  people: [
    { id:"ferry", name:"Jules Ferry", dates:"1832-1893", role:"Repubblicano francese, promotore della scuola laica e dell’espansione coloniale", image:"assets/img/people/ferry.svg", imageAlt:"Profilo illustrato di Jules Ferry", bio:"Fu uno dei principali repubblicani moderati della Terza Repubblica. Le leggi scolastiche legate al suo nome ampliarono istruzione gratuita, obbligatoria e laica. Difese anche l’espansione coloniale con argomenti economici e civilizzatori.", idea:"La stessa Repubblica che ampliava cittadinanza e scuola poteva giustificare gerarchie coloniali." },
    { id:"dreyfus", name:"Alfred Dreyfus", dates:"1859-1935", role:"Ufficiale francese ingiustamente condannato", image:"assets/img/people/dreyfus.svg", imageAlt:"Profilo illustrato di Alfred Dreyfus", bio:"Capitano ebreo dell’esercito francese, fu condannato nel 1894 per tradimento sulla base di prove fragili e manipolate. Graziato nel 1899, venne pienamente riabilitato nel 1906.", idea:"Il caso trasformò un errore giudiziario in una prova del rapporto fra Stato di diritto, esercito e antisemitismo." },
    { id:"gladstone", name:"William E. Gladstone", dates:"1809-1898", role:"Leader liberale e primo ministro britannico", image:"assets/img/people/gladstone.svg", imageAlt:"Profilo illustrato di William Gladstone", bio:"Guidò più governi liberali e tentò due volte di introdurre l’Home Rule irlandese. La proposta del 1886 divise il suo partito; quella del 1893 fu bloccata dalla Camera dei Lord.", idea:"L’adattamento parlamentare aveva limiti quando autonomia nazionale e assetti imperiali entravano in conflitto." },
    { id:"witte", name:"Sergej Witte", dates:"1849-1915", role:"Ministro delle finanze e modernizzatore russo", image:"assets/img/people/witte.svg", imageAlt:"Profilo illustrato di Sergej Witte", bio:"Promosse protezione doganale, investimenti ferroviari, capitale straniero e stabilizzazione monetaria. Partecipò ai negoziati di Portsmouth e divenne primo ministro durante la crisi del 1905.", idea:"La modernizzazione economica poteva rafforzare l’autocrazia e contemporaneamente creare forze sociali che la contestavano." },
    { id:"nicola", name:"Nicola II", dates:"1868-1918", role:"Ultimo zar di Russia", image:"assets/img/people/nicola.svg", imageAlt:"Profilo illustrato di Nicola II", bio:"Salì al trono nel 1894 e difese il principio autocratico. Espansione in Asia, guerra con il Giappone e repressione aggravarono le tensioni sfociate nella rivoluzione del 1905.", idea:"La difesa rigida dell’autocrazia ridusse la capacità del regime di assorbire conflitti prodotti dalla modernizzazione." },
    { id:"francesco", name:"Francesco Giuseppe", dates:"1830-1916", role:"Imperatore d’Austria e re d’Ungheria", image:"assets/img/people/francesco.svg", imageAlt:"Profilo illustrato di Francesco Giuseppe", bio:"Regnò dal 1848. Dopo la sconfitta del 1866 accettò il Compromesso che fondò la duplice monarchia. Divenne simbolo di continuità mentre nazionalità e parlamenti rendevano più complesso il governo.", idea:"La durata dinastica non risolse la domanda di un patto eguale fra i popoli dell’Impero." },
    { id:"leopoldo", name:"Leopoldo II", dates:"1835-1909", role:"Re dei Belgi e sovrano dello Stato Libero del Congo", image:"assets/img/people/leopoldo.svg", imageAlt:"Profilo illustrato di Leopoldo II", bio:"Ottenne il riconoscimento internazionale dello Stato Libero del Congo come propria sovranità personale. Il sistema delle concessioni e del caucciù usò coercizione e violenza; nel 1908 il territorio passò allo Stato belga.", idea:"Linguaggio umanitario, impresa privata e potere personale poterono combinarsi in una forma estrema di dominio coloniale." },
    { id:"rhodes", name:"Cecil Rhodes", dates:"1853-1902", role:"Imprenditore e politico dell’imperialismo britannico", image:"assets/img/people/rhodes.svg", imageAlt:"Profilo illustrato di Cecil Rhodes", bio:"Costruì un enorme potere economico nel settore diamantifero e fu primo ministro della Colonia del Capo. Legò espansione territoriale, interessi d’impresa e visione razziale dell’Impero.", idea:"L’imperialismo non fu soltanto politica statale: imprese e individui potevano orientare la conquista." },
    { id:"menelik", name:"Menelik II", dates:"1844-1913", role:"Imperatore d’Etiopia e vincitore di Adua", image:"assets/img/people/menelik.svg", imageAlt:"Profilo illustrato di Menelik II", bio:"Consolidò il regno, acquistò armi e costruì alleanze interne ed esterne. Nel 1896 l’esercito etiopico sconfisse quello italiano ad Adua, preservando l’indipendenza del paese.", idea:"La resistenza africana poteva usare diplomazia, tecnologia e organizzazione statale contro una potenza europea." },
    { id:"mutsuhito", name:"Imperatore Meiji", dates:"1852-1912", role:"Sovrano del Giappone durante la trasformazione Meiji", image:"assets/img/people/mutsuhito.svg", imageAlt:"Profilo illustrato dell’imperatore Meiji", bio:"Il suo regno accompagnò centralizzazione, coscrizione, industrializzazione e riforme istituzionali. Il Giappone divenne potenza militare e imperiale, vincendo contro Cina e Russia.", idea:"Uscire dalla subordinazione occidentale non significò rifiutare la logica dell’impero." }
  ],
  timeline: [
    {date:"1870-1871",title:"Caduta di Napoleone III e Comune di Parigi",text:"La sconfitta apre una crisi di regime; la guerra civile separa Repubblica sociale e ordine conservatore.",scale:"Politica"},
    {date:"1875",title:"Leggi costituzionali francesi e Canale di Suez",text:"La Terza Repubblica trova un ordinamento; Londra acquista le azioni egiziane del canale e rafforza la rotta imperiale.",scale:"Politica"},
    {date:"1877",title:"La crisi costituzionale francese",text:"La pratica parlamentare prevale sull’interpretazione presidenziale del regime.",scale:"Politica"},
    {date:"1878",title:"Congresso di Berlino e Bosnia-Erzegovina",text:"L’Austria-Ungheria occupa la Bosnia-Erzegovina; la questione balcanica si collega alle rivalità europee.",scale:"Imperi"},
    {date:"1881",title:"Assassinio di Alessandro II",text:"La reazione di Alessandro III rafforza autocrazia, censura e russificazione.",scale:"Russia"},
    {date:"1882",title:"Egitto e Leggi di maggio",text:"La Gran Bretagna occupa l’Egitto; in Russia nuove norme restringono la vita delle comunità ebraiche.",scale:"Imperi"},
    {date:"1884-1885",title:"Suffragio britannico e Conferenza di Berlino",text:"Nuovi uomini entrano nell’elettorato britannico mentre le potenze fissano regole per la conquista africana.",scale:"Politica"},
    {date:"1885",title:"Massaua e Stato Libero del Congo",text:"L’Italia occupa Massaua; Leopoldo II assume la sovranità personale sul Congo.",scale:"Africa"},
    {date:"1886",title:"Primo progetto di Home Rule",text:"La proposta di Gladstone fallisce e divide il Partito liberale.",scale:"Politica"},
    {date:"1890",title:"Eritrea colonia italiana",text:"La presenza italiana nel Mar Rosso diventa un possesso coloniale formalizzato.",scale:"Africa"},
    {date:"1891",title:"Transiberiana",text:"La grande ferrovia unisce modernizzazione economica, controllo territoriale e strategia asiatica russa.",scale:"Russia"},
    {date:"1894-1895",title:"Guerra sino-giapponese e caso Dreyfus",text:"Il Giappone emerge come potenza; la Francia entra in una crisi su esercito, diritti e antisemitismo.",scale:"Asia"},
    {date:"1896",title:"Adua e Madagascar",text:"L’Etiopia sconfigge l’Italia; la Francia trasforma il Madagascar in colonia.",scale:"Africa"},
    {date:"1898",title:"J’accuse e Fashoda",text:"Zola riapre il caso Dreyfus; Francia e Gran Bretagna arrivano vicino allo scontro in Sudan.",scale:"Imperi"},
    {date:"1899-1901",title:"Rivolta dei Boxer",text:"La coalizione internazionale reprime il movimento e impone nuove limitazioni alla Cina.",scale:"Asia"},
    {date:"1899-1902",title:"Seconda guerra anglo-boera",text:"Terra bruciata e campi di concentramento mostrano la violenza della guerra imperiale.",scale:"Africa"},
    {date:"1900",title:"Labour Representation Committee",text:"Sindacati e socialisti costruiscono una rappresentanza parlamentare comune.",scale:"Politica"},
    {date:"1904-1905",title:"Guerra russo-giapponese",text:"La vittoria giapponese rovescia il prestigio russo e spezza il mito dell’invincibilità europea.",scale:"Asia"},
    {date:"1905",title:"Portsmouth e rivoluzione russa",text:"La pace trasferisce diritti imperiali al Giappone; in Russia guerra e tensioni interne producono la rivoluzione.",scale:"Russia"},
    {date:"1906",title:"Dreyfus riabilitato e Labour Party",text:"La giustizia francese annulla la condanna; il nuovo partito britannico assume il nome definitivo.",scale:"Politica"}
  ],
  maps: [
    {title:"Quattro sistemi politici a confronto",image:"assets/img/maps/sistemi-politici.svg",alt:"Schema comparativo di Francia, Gran Bretagna, Russia e Austria-Ungheria",text:"La carta concettuale confronta fonte del governo, ampiezza della rappresentanza e conflitto principale.",note:"Non è una graduatoria lineare: ogni sistema combina partecipazione e controllo in modo diverso."},
    {title:"Politica di massa: inclusioni ed esclusioni",image:"assets/img/maps/politica-massa.svg",alt:"Schema dei soggetti e degli strumenti della politica di massa",text:"Scuola, stampa, partiti e sindacati ampliano la partecipazione; requisiti elettorali, genere e repressione ne delimitano i confini.",note:"Il voto è un indicatore decisivo, ma non esaurisce la capacità politica."},
    {title:"Imperi, rotte e sfere d’influenza",image:"assets/img/maps/imperi-rotte.svg",alt:"Mappa schematica delle principali direzioni imperiali europee in Africa e Asia",text:"La mappa evidenzia Suez, Africa, India, Cina, Corea e Manciuria come nodi di rotte e competizione.",note:"Carta schematica, non in scala e non adatta alla ricostruzione puntuale dei confini."},
    {title:"Dal dominio alle resistenze",image:"assets/img/maps/resistenze.svg",alt:"Schema delle forme di conquista coloniale e delle resistenze africane e asiatiche",text:"Trattati, occupazione e lavoro forzato incontrano guerra, diplomazia, migrazione, adattamento e nazionalismo.",note:"Resistere non significa sempre combattere in campo aperto; anche negoziazione e sopravvivenza sono azione storica."}
  ],
  sources: [
    {id:"suffragio-1884",title:"Il Third Reform Act britannico",type:"Legge e storia parlamentare",date:"1884",author:"Parlamento del Regno Unito",provenance:"UK Parliament, Living Heritage",verbatim:false,excerpt:["La riforma uniformò il diritto di voto fra contee e borghi e ampliò notevolmente l’elettorato maschile.","Non introdusse il suffragio universale: genere, residenza e condizione sociale continuarono a produrre esclusioni."],context:"Terza grande riforma elettorale britannica, completata dalla redistribuzione dei collegi del 1885.",audience:"Cittadini e studiosi della storia parlamentare.",purpose:"Ricostruire l’evoluzione istituzionale del diritto di voto.",limits:"La sintesi istituzionale privilegia la continuità e deve essere confrontata con movimenti, dibattiti e soggetti esclusi.",interpretation:"La legge amplia il popolo politico senza renderlo universale; mostra che la democratizzazione procede per conflitti e compromessi.",questions:["Quali requisiti diventano più uniformi?","Chi continua a non votare?","Perché una riforma legale non misura da sola il potere effettivo?"],url:"https://www.parliament.uk/about/living-heritage/evolutionofparliament/houseofcommons/reformacts/overview/one-man-one-vote/"},
    {id:"comune-parigi",title:"La Comune di Parigi nella storia parlamentare",type:"Dossier istituzionale",date:"1871",author:"Assemblée nationale française",provenance:"Histoire et patrimoine de l’Assemblée nationale",verbatim:false,excerpt:["Dal 18 marzo al 28 maggio 1871 Parigi si sollevò contro le condizioni della capitolazione e il rischio di restaurazione monarchica.","Le elezioni municipali del 26 marzo precedettero la proclamazione della Comune il 28 marzo."],context:"Ricostruzione istituzionale della crisi seguita alla guerra franco-prussiana.",audience:"Pubblico generale, studenti e cittadini.",purpose:"Presentare cronologia e documenti della nascita della Terza Repubblica.",limits:"Il punto di vista parlamentare non sostituisce fonti comunarde, testimonianze sociali e ricerca sulle vittime.",interpretation:"La fonte chiarisce il nesso fra sconfitta, pace, paura monarchica e insurrezione, ma va interrogata sul linguaggio usato per definire i contendenti.",questions:["Quali cause politiche e sociali sono indicate?","Quali soggetti parlano attraverso la pagina istituzionale?","Quali fonti servirebbero per ricostruire l’esperienza dei comunardi?"],url:"https://www.assemblee-nationale.fr/dyn/histoire-et-patrimoine/troisieme-republique/la-commune-de-paris"},
    {id:"leggi-maggio",title:"Le Leggi di maggio e la Zona di residenza",type:"Norme e voce enciclopedica accademica",date:"1882",author:"Governo dell’Impero russo; YIVO Institute",provenance:"YIVO Encyclopedia of Jews in Eastern Europe",verbatim:false,excerpt:["Le norme del 1882 ridussero la presenza ebraica nei villaggi della Zona di residenza.","La ricerca recente distingue discriminazione statale, violenza locale e dinamiche differenti dei pogrom."],context:"Dopo i pogrom del 1881-1882 il governo russo irrigidì le restrizioni sulla popolazione ebraica.",audience:"Studiosi, studenti e pubblico interessato alla storia ebraica dell’Europa orientale.",purpose:"Spiegare quadro giuridico, geografia e trasformazioni della Zona di residenza.",limits:"Una voce sintetica non ricostruisce ogni episodio locale; le responsabilità vanno verificate caso per caso.",interpretation:"La discriminazione normativa è documentata anche quando non è dimostrata una regia centrale per ogni violenza.",questions:["Che cosa limitano le norme?","Perché legge discriminatoria e pogrom non sono la stessa cosa?","Come evitare sia l’assoluzione sia la semplificazione causale?"],url:"https://yivoencyclopedia.org/article.aspx/pale_of_settlement"},
    {id:"ausgleich",title:"Il sistema costituzionale della duplice monarchia",type:"Costituzione e storia parlamentare",date:"1867",author:"Monarchia asburgica",provenance:"Parlamento austriaco, storia del parlamentarismo",verbatim:false,excerpt:["Austria e Ungheria ottennero governi e parlamenti distinti, mentre sovrano, politica estera e guerra rimasero comuni.","Il dualismo riconobbe due centri politici senza attribuire pari sovranità alle altre nazionalità."],context:"Riorganizzazione dell’Impero dopo la sconfitta contro la Prussia.",audience:"Cittadini dell’Impero e organi costituzionali; oggi studiosi della storia parlamentare.",purpose:"Definire distribuzione dei poteri e materie comuni.",limits:"Il testo giuridico rende visibili le istituzioni riconosciute e meno visibili le domande politiche escluse.",interpretation:"La stabilità del dualismo dipende da un compromesso selettivo: risolve il conflitto con l’Ungheria e ne gerarchizza altri.",questions:["Quali poteri sono condivisi?","Perché il sistema è costituzionale ma non federale in senso egualitario?","Quali popoli non sono soggetti paritari dell’accordo?"],url:"https://www.parlament.gv.at/en/explore/history/"},
    {id:"berlino",title:"Atto generale della Conferenza di Berlino",type:"Trattato internazionale",date:"26 febbraio 1885",author:"Potenze partecipanti alla Conferenza di Berlino",provenance:"Office of the Historian, U.S. Department of State",verbatim:false,excerpt:["Le potenze dichiararono libertà commerciale nel bacino del Congo, navigazione dei grandi fiumi e opposizione alla tratta.","Le regole sulla notifica e sull’autorità effettiva trasformarono la competizione diplomatica in occupazione territoriale."],context:"Conferenza convocata da Bismarck fra novembre 1884 e febbraio 1885.",audience:"Governi firmatari e comunità diplomatica internazionale.",purpose:"Regolare commercio, navigazione e riconoscimento delle occupazioni africane.",limits:"Le popolazioni africane non parteciparono alla definizione delle regole; il linguaggio umanitario non descrive la pratica coloniale.",interpretation:"La conferenza non disegnò da sola tutti i confini, ma stabilì criteri che accelerarono la conquista.",questions:["Quali obiettivi umanitari vengono dichiarati?","Quali meccanismi favoriscono l’occupazione?","Chi non ha voce nel documento?"],url:"https://history.state.gov/historicaldocuments/frus1928v01/d311"},
    {id:"congo",title:"Lo Stato Libero del Congo: archivi e violenza",type:"Archivio museale e ricerca storica",date:"1885-1908",author:"Royal Museum for Central Africa",provenance:"AfricaMuseum, Tervuren",verbatim:false,excerpt:["Leopoldo II fu sovrano personale dello Stato Libero del Congo dal 1885 al 1908.","Conquista, caucciù, lavoro forzato e spedizioni punitive produssero violenza estesa e sconvolgimenti demografici."],context:"Rilettura critica delle collezioni e degli archivi prodotti nel contesto coloniale belga.",audience:"Pubblico del museo, comunità scientifica e società coinvolte nella memoria coloniale.",purpose:"Esporre conoscenze e responsabilità della storia coloniale conservando accesso alle fonti.",limits:"Le collezioni stesse nacquero in rapporti di potere; occorre includere voci e prospettive congolesi.",interpretation:"L’archivio non è neutrale: documenta il dominio e il modo in cui il dominio volle rappresentarsi.",questions:["Perché non è corretto chiamarlo colonia belga già nel 1885?","Quali fonti documentano la coercizione?","Come cambia la lettura se si parte dalle comunità congolesi?"],url:"https://www.africamuseum.be/en/about_us/viewpoints"},
    {id:"adua",title:"Adua e l’indipendenza etiopica",type:"Ricerca storica universitaria",date:"1 marzo 1896",author:"Raymond Jonas",provenance:"University of Washington, Department of History",verbatim:false,excerpt:["L’esercito etiopico guidato da Menelik II sconfisse le forze italiane e difese l’indipendenza del paese.","La vittoria mise in dubbio la presunta inevitabilità del dominio europeo sull’Africa."],context:"Guerra nata dal contrasto sull’interpretazione del trattato di Uccialli e dall’espansione italiana.",audience:"Studiosi, studenti e pubblico interessato alla storia dell’imperialismo.",purpose:"Ricostruire Adua come evento militare, politico e simbolico nell’età degli imperi.",limits:"La memoria nazionale può trasformare un processo complesso in mito; servono fonti italiane, etiopiche e diplomatiche.",interpretation:"Adua mostra che organizzazione statale, diplomazia e approvvigionamento militare potevano rovesciare i calcoli europei.",questions:["Quale ruolo ebbe il trattato di Uccialli?","Perché la vittoria ebbe significato oltre l’Etiopia?","Quali semplificazioni producono le memorie nazionali?"],url:"https://history.washington.edu/research/books/battle-adwa-african-victory-age-empire"},
    {id:"portsmouth",title:"Il Trattato di Portsmouth",type:"Trattato di pace e dossier diplomatico",date:"5 settembre 1905",author:"Impero russo e Impero giapponese",provenance:"Office of the Historian, U.S. Department of State",verbatim:false,excerpt:["Il trattato concluse la guerra russo-giapponese e riconobbe la prevalenza giapponese in Corea e Manciuria meridionale.","Il Giappone ricevette la metà meridionale di Sachalin e diritti già detenuti dalla Russia."],context:"Negoziato mediato dal presidente statunitense Theodore Roosevelt dopo le vittorie giapponesi.",audience:"Governi, opinione pubblica internazionale e attori diplomatici.",purpose:"Concludere la guerra e redistribuire interessi e territori.",limits:"Coreani e cinesi non negoziarono alla pari decisioni che riguardavano i loro territori.",interpretation:"La pace ridimensionò la Russia e riconobbe il Giappone come grande potenza, trasferendo più che abolendo rapporti imperiali.",questions:["Quali diritti cambiano titolare?","Quali popolazioni restano senza voce?","Perché la vittoria fu insieme simbolo anticoloniale e fatto imperialista?"],url:"https://history.state.gov/milestones/1899-1913/portsmouth-treaty"}
  ],
  workshop: [
    {title:"Definisci la contraddizione",prompt:"Quale relazione descrive meglio il periodo?",options:["Partecipazione politica e dominio coloniale crescono insieme.","La democratizzazione europea elimina progressivamente ogni forma di coercizione.","L’imperialismo è soltanto una conseguenza economica dell’industria."]},
    {title:"Scegli le prove comparative",prompt:"Quale insieme sostiene meglio una tesi rigorosa?",options:["Leggi elettorali, istituzioni, movimenti sociali, pratiche coloniali e resistenze.","Solo le biografie dei capi di governo.","Solo la cronologia delle conquiste europee."]},
    {title:"Evita la teleologia",prompt:"Come interpreti le differenze fra i sistemi politici?",options:["Come esiti contingenti di conflitti, compromessi e rapporti di forza.","Come tappe inevitabili verso la democrazia liberale.","Come manifestazioni immutabili del carattere nazionale."]},
    {title:"Formula il limite",prompt:"Quale obiezione deve affrontare una tesi generale sull’Europa?",options:["Francia, Gran Bretagna, Russia e Austria-Ungheria non seguono la stessa traiettoria.","Ogni evento storico ha una sola causa verificabile.","Le popolazioni colonizzate non modificano mai il processo."]}
  ],
  quiz: [
    {q:"Che cosa distingue soprattutto l’imperialismo dal solo possesso coloniale?",options:["Il dominio può includere protettorati, basi e controllo finanziario senza annessione completa.","Riguarda esclusivamente l’Africa.","È sempre immediatamente redditizio.","Esclude l’uso della forza."],answer:0,why:"L’imperialismo è un sistema di dominio più ampio della colonia formale.",recover:"Rivedi definizioni e forme del dominio.",lesson:"imperialismo-cause"},
    {q:"Perché la politica di massa non coincide con la democrazia piena?",options:["Perché partiti e stampa scompaiono.","Perché partecipazione e organizzazione crescono mentre persistono esclusioni e repressione.","Perché tutti gli adulti ottengono subito il voto.","Perché riguarda solo la politica estera."],answer:1,why:"Nuovi pubblici entrano nella politica, ma genere, reddito, residenza e coercizione limitano l’inclusione.",recover:"Rileggi nuovi attori e vecchie esclusioni.",lesson:"europa-contraddittoria"},
    {q:"Quale fattore contribuì direttamente alla nascita della Comune di Parigi?",options:["La vittoria francese sulla Prussia.","Il tentativo di sottrarre i cannoni alla Guardia nazionale il 18 marzo 1871.","La riabilitazione di Dreyfus.","Il voto femminile."],answer:1,why:"Il tentativo governativo a Montmartre innescò l’insurrezione.",recover:"Rivedi la sezione sulle fratture francesi.",lesson:"francia-repubblica"},
    {q:"Che cosa consolidò la crisi francese del 1877?",options:["La restaurazione monarchica.","La prevalenza parlamentare sul presidente.","Il potere della Comune.","La fine del Senato."],answer:1,why:"La pratica costituzionale rafforzò la responsabilità politica verso le Camere.",recover:"Rileggi il processo della Terza Repubblica.",lesson:"francia-repubblica"},
    {q:"Perché l’affare Dreyfus fu più di un errore giudiziario?",options:["Perché coinvolse diritti, esercito, stampa, nazionalismo e antisemitismo.","Perché abolì il Parlamento.","Perché iniziò la Comune.","Perché riguardò la questione irlandese."],answer:0,why:"Il caso mise alla prova la capacità repubblicana di correggere un abuso coperto dalle istituzioni.",recover:"Rivedi attori e conseguenze della crisi.",lesson:"francia-repubblica"},
    {q:"Che cosa fece il Third Reform Act del 1884?",options:["Introdusse il voto universale femminile.","Uniformò in larga misura i requisiti tra contee e borghi, ampliando l’elettorato maschile.","Abolì la Camera dei Lord.","Concesse l’indipendenza irlandese."],answer:1,why:"La riforma ampliò il voto senza renderlo universale.",recover:"Rileggi le fratture britanniche.",lesson:"gran-bretagna"},
    {q:"Perché la Home Rule divise i liberali britannici?",options:["Una parte rifiutava l’autonomia irlandese e difendeva l’Unione.","Gladstone voleva abolire la monarchia.","I sindacati rifiutavano il voto.","La Francia impose il progetto."],answer:0,why:"I liberali unionisti si separarono dal partito e si allearono con i conservatori.",recover:"Rivedi attori e conflitti britannici.",lesson:"gran-bretagna"},
    {q:"Da quale incontro nacque il Labour?",options:["Aristocratici e Chiesa anglicana.","Sindacati e gruppi socialisti diversi.","Esercito e industriali coloniali.","Nazionalisti irlandesi e monarchici."],answer:1,why:"Il Labour Representation Committee coordinò trade unions e organizzazioni socialiste.",recover:"Rivedi il processo dal sindacato al Parlamento.",lesson:"gran-bretagna"},
    {q:"Quale contraddizione caratterizzò la Russia di Witte?",options:["Apertura politica senza industria.","Industrializzazione rapida dentro un’autocrazia politicamente chiusa.","Agricoltura capitalistica senza contadini.","Suffragio universale con censura assente."],answer:1,why:"Lo Stato modernizzò economia e ferrovie senza creare rappresentanza nazionale.",recover:"Rileggi industrializzazione e conseguenze.",lesson:"russia-zarista"},
    {q:"Che cos’era il mir?",options:["Un partito socialista.","La comunità rurale responsabile di terre e obblighi collettivi.","La polizia politica.","Una ferrovia asiatica."],answer:1,why:"Il mir distribuiva appezzamenti e rispondeva collettivamente di imposte e riscatti.",recover:"Rivedi il mondo precedente russo.",lesson:"russia-zarista"},
    {q:"Quale formulazione sui pogrom è storicamente più rigorosa?",options:["Ogni pogrom ebbe identica regia centrale documentata.","Lo Stato non ebbe alcuna responsabilità.","Discriminazione legale e tolleranza statale sono documentate, ma le dinamiche locali differirono.","I pogrom furono soltanto conflitti religiosi spontanei."],answer:2,why:"Occorre distinguere politica statale, complicità e dinamiche specifiche dei singoli episodi.",recover:"Rileggi la fonte sulle Leggi di maggio.",lesson:"russia-zarista"},
    {q:"Che cosa istituì l’Ausgleich del 1867?",options:["Una repubblica federale di tutti i popoli.","Due governi e parlamenti con sovrano e alcuni ministeri comuni.","L’indipendenza completa dell’Ungheria.","Il suffragio universale nell’Impero."],answer:1,why:"Il Compromesso creò la duplice monarchia austro-ungarica.",recover:"Rivedi struttura e poteri comuni.",lesson:"austria-ungheria"},
    {q:"Perché il Compromesso non risolse la questione nazionale?",options:["Riconobbe soprattutto il rapporto fra Austria e Ungheria, non una parità di tutti i popoli.","Eliminò ogni parlamento.","Abolì le lingue nazionali.","Sciolse immediatamente l’Impero."],answer:0,why:"Il dualismo privilegiò due élite e lasciò aperte molte altre domande.",recover:"Rileggi attori e conseguenze.",lesson:"austria-ungheria"},
    {q:"Quale affermazione sulla Conferenza di Berlino è corretta?",options:["Disegnò in una sola seduta tutti i confini africani.","Stabilì regole che accelerarono l’occupazione, senza completare da sola la spartizione.","Vi parteciparono su base paritaria tutti gli Stati africani.","Impedì la conquista del Congo."],answer:1,why:"La conferenza regolò competizione, commercio e riconoscimento delle occupazioni.",recover:"Rivedi processo e fonte di Berlino.",lesson:"imperialismo-cause"},
    {q:"Perché non basta una spiegazione solo economica dell’imperialismo?",options:["Perché le colonie non ebbero mai valore economico.","Perché strategia, prestigio, tecnologia e ideologia interagirono con interessi economici.","Perché l’economia europea era isolata.","Perché tutte le conquiste furono religiose."],answer:1,why:"Le cause variarono e si combinarono diversamente nei singoli casi.",recover:"Rivedi la spiegazione pluricausale.",lesson:"imperialismo-cause"},
    {q:"Che cos’era lo Stato Libero del Congo tra 1885 e 1908?",options:["Una normale provincia belga.","Una sovranità personale di Leopoldo II.","Uno Stato africano indipendente governato da un parlamento eletto.","Una colonia francese."],answer:1,why:"Il territorio dipese personalmente da Leopoldo II prima del passaggio al Belgio.",recover:"Rileggi il processo africano e la fonte Congo.",lesson:"africa-spartita"},
    {q:"Che cosa dimostrò la battaglia di Adua del 1896?",options:["Che ogni resistenza africana era destinata a fallire.","Che organizzazione, diplomazia e forza militare africane potevano sconfiggere una potenza europea.","Che l’Etiopia divenne colonia italiana.","Che terminò tutta la spartizione africana."],answer:1,why:"L’Etiopia di Menelik II preservò l’indipendenza sconfiggendo l’Italia.",recover:"Rivedi attori e fratture africane.",lesson:"africa-spartita"},
    {q:"Quale forma ebbe spesso il dominio straniero in Cina?",options:["Solo annessione totale.","Porti, concessioni, extraterritorialità e sfere d’influenza.","Assenza completa di intervento.","Un unico protettorato britannico."],answer:1,why:"La sovranità Qing rimase formalmente in vita ma fu gravemente limitata.",recover:"Rivedi il mondo precedente asiatico.",lesson:"asia-giappone"},
    {q:"Che cosa stabilì Portsmouth nel 1905?",options:["La vittoria russa e l’annessione del Giappone.","La prevalenza giapponese in Corea e diritti in Manciuria meridionale, oltre a parte di Sachalin.","L’indipendenza immediata della Corea.","La fine di ogni imperialismo in Asia."],answer:1,why:"Il trattato trasferì al Giappone parte dei vantaggi imperiali russi.",recover:"Rileggi il processo verso Portsmouth.",lesson:"asia-giappone"},
    {q:"Perché la vittoria giapponese fu ambivalente?",options:["Spezzò il mito dell’invincibilità europea ma rafforzò un nuovo impero giapponese.","Liberò tutte le colonie asiatiche.","Distrusse l’industrializzazione giapponese.","Non ebbe alcun significato fuori dalla Russia."],answer:0,why:"Fu un simbolo anticoloniale e insieme un passaggio nella costruzione imperiale del Giappone.",recover:"Rivedi conseguenze e nuovo assetto.",lesson:"asia-giappone"}
  ]
};
