window.AI_TEXTS = {
  "lessons": {
    "ordini": [
      "Immagina di entrare in un tribunale francese del Settecento: prima ancora di conoscere la tua vicenda, chi ti giudica può dover sapere a quale ordine appartieni. Questa è una scena didattica, non il resoconto di un processo particolare. Serve a porre il problema: la legge tratta tutti come individui uguali oppure riconosce condizioni differenti? Nell’Antico regime l’appartenenza sociale può modificare obblighi, onori, accesso agli incarichi e procedure. La disuguaglianza non è un difetto accidentale del sistema: è parte costitutiva del sistema.",
      "Con Antico regime indichiamo gli assetti politici e sociali precedenti alla Rivoluzione francese. È un’espressione retrospettiva: chi viveva sotto Luigi XIV non chiamava il proprio presente “antico”. Usiamo soprattutto la Francia come osservatorio, ma non come fotografia dell’intera Europa. Monarchie, repubbliche, parlamenti e rapporti agrari differivano molto. Dopo il 1688, per esempio, la monarchia inglese seguiva un percorso diverso dall’assolutismo francese.",
      "La società francese era rappresentata attraverso tre ordini o stati. Il clero, primo ordine, era legato alle funzioni religiose, ma anche a istruzione, assistenza e proprietà fondiaria. La nobiltà, secondo ordine, rivendicava distinzione ereditaria, onore e una tradizione di servizio militare o amministrativo. Il Terzo Stato comprendeva chi non apparteneva agli altri due: dal grande negoziante al bracciante, dall’avvocato alla domestica. Non era sinonimo di povertà e non costituiva una classe economicamente uniforme.",
      "Neppure clero e nobiltà erano blocchi compatti. Un vescovo di grande famiglia disponeva di redditi e relazioni lontanissimi da quelli di un parroco rurale. Un aristocratico di corte e un piccolo nobile provinciale potevano avere risorse molto diverse. La nascita pesava enormemente, ma esistevano anche promozioni, nobilitazioni e acquisto di uffici che, in determinate condizioni, aprivano l’accesso alla nobiltà. Il sistema ammetteva mobilità senza riconoscere l’uguaglianza generale.",
      "Il privilegio era una condizione particolare riconosciuta dal diritto a un gruppo, un territorio o una corporazione. Poteva consistere in esenzioni fiscali, prerogative giudiziarie, precedenze cerimoniali o riserve di incarichi. Non bisogna dire che nobili e clero “non pagavano nessuna tassa”: esistevano tributi, contributi negoziati, differenze regionali e continue dispute sull’imposizione. Il punto è che la distribuzione del carico non seguiva una regola uniforme di uguaglianza dei contribuenti.",
      "Oggi distinguiamo analiticamente disuguaglianza economica e disuguaglianza giuridica: due persone possono avere redditi diversi pur essendo formalmente uguali davanti alla legge. Nell’Antico regime anche la differenza di condizione legale è parte dell’ordinamento. Un ricco mercante può prestare denaro a un nobile indebitato e tuttavia non godere dei suoi onori o delle sue prerogative. Per capire quella società non basta chiedere “quanto possiedi?”: occorre chiedere “chi sei per il diritto?”.",
      "La terra sostiene gran parte dei redditi e del prestigio. Nobili, istituzioni ecclesiastiche, borghesi e contadini possono possederla in forme diverse. Essere contadino non significa necessariamente essere servo e lavorare una terra non significa possederla liberamente da ogni obbligo. Sul medesimo terreno possono gravare canoni, prestazioni o diritti signorili, oltre ai tributi regi e alla decima ecclesiastica dove dovuta.",
      "Un raccolto deve quindi nutrire la famiglia, conservare le sementi, pagare affitti e prelievi. Un cattivo anno agricolo non è soltanto un inconveniente privato: può produrre indebitamento, conflitti e proteste. Le comunità rurali non sono passive; difendono usi collettivi, contestano pretese e ricorrono ai tribunali. Ma lo fanno spesso invocando consuetudini e diritti acquisiti, non ancora un programma universale di uguaglianza.",
      "Una fonte normativa ci dice quali diritti sono riconosciuti; non dimostra da sola come ogni giorno siano applicati. Una caricatura dei tre ordini ci mostra una polemica; non è una statistica imparziale. Nel 1789 la rappresentazione del Terzo Stato che sostiene gli ordini privilegiati trasforma rapporti complessi in un’accusa politica. Bisogna interrogare autore, destinatario e momento: la società viene rappresentata da un punto di vista.",
      "In sintesi: nascita, appartenenza e diritto si sostengono reciprocamente. Il sistema appare legittimo a molti perché attribuisce funzioni e doveri differenti ai corpi della società, ma genera anche conflitti e contestazioni. Domanda: se un privilegio è legale, che cosa permette di giudicarlo ingiusto? Per rispondere dobbiamo prima capire chi custodisce e rappresenta quell’ordine: il re."
    ],
    "potere": [
      "Quando Luigi XIV assume personalmente la direzione del governo nel 1661, non inventa dal nulla lo Stato francese. Rafforza processi di accentramento già avviati e cerca di impedire che poteri concorrenti condizionino la monarchia. La memoria delle rivolte della Fronda aiuta a comprendere il problema politico: rendere stabile l’autorità del sovrano in un regno attraversato da interessi, giurisdizioni e privilegi differenti.",
      "Assolutismo significa rivendicazione della supremazia del re, non presenza di uno Stato capace di controllare ogni gesto di ogni abitante. Il sovrano pretende di non dipendere da un’autorità politica interna superiore. Nelle teorie del diritto divino il suo potere deriva da Dio: ne discendono sacralità e doveri religiosi. È una giustificazione storica del comando, non la prova che il re possa materialmente fare qualunque cosa.",
      "Per amministrare territori servono consigli, funzionari, informazioni e denaro. Gli intendenti rappresentano l’intervento regio nelle province; gli uffici comprati e trasmessi da famiglie mostrano invece quanto l’amministrazione resti intrecciata con interessi privati. Non bisogna immaginare una burocrazia già identica a quella contemporanea: lo Stato cresce utilizzando anche strutture ereditate e compromessi.",
      "Un esercito numeroso deve essere reclutato, equipaggiato e rifornito. La diplomazia cerca alleanze e negozia trattati; le guerre consumano risorse, incidono sul territorio e accrescono il bisogno di entrate. Fiscalità, credito e potenza militare formano così un circuito: più ambizioni internazionali richiedono più denaro; il prelievo provoca resistenze; il governo deve trovare nuovi mezzi senza distruggere gli equilibri sui quali si regge.",
      "La monarchia incontra privilegi provinciali, consuetudini, corporazioni, assemblee locali e parlamenti, che in Francia sono anzitutto alte corti di giustizia, non il Parlamento rappresentativo moderno. Deve misurarsi con distanze, lentezza delle comunicazioni e scarsità di personale. Inoltre le leggi fondamentali della monarchia, per esempio in materia di successione, delimitano ciò che il sovrano è ritenuto autorizzato a modificare.",
      "Questi vincoli non fanno della Francia una democrazia. Spiegano però perché “assoluto” e “onnipotente” non siano sinonimi. Un governo può proclamare la propria superiorità e dover negoziare l’applicazione concreta delle decisioni. Domanda intermedia: se il re possiede l’ultima parola, chi rende possibile trasformarla in imposte riscosse e ordini eseguiti?",
      "Nel 1682 Versailles diventa sede stabile della corte e del governo. La reggia non serve soltanto a ospitare il sovrano: organizza accessi, distanze e visibilità. Il risveglio, i pasti, gli spostamenti e il riposo del re sono regolati da cerimoniali. Essere ammessi a una determinata fase del lever, il rito del risveglio, rende visibile il rango. Il tempo quotidiano del monarca diventa una risorsa politica.",
      "La nobiltà cerca pensioni, incarichi e favori. La competizione per essere vista dal re può avvicinarla alla corte e legarla alla monarchia. Non tutti i nobili vivono a Versailles e non perdono automaticamente ogni potere locale: il rapporto è più complesso di una prigionia dorata. Eppure il centro della distinzione viene rappresentato come un punto preciso: la persona del sovrano.",
      "Tessuti costosi, ornamenti, postura e rispetto dell’etichetta comunicano condizione sociale. Una festa di corte esibisce ricchezza, controllo dello spazio, abilità artistiche e capacità di coordinare persone. La moda è anche lavoro: dietro il lusso ci sono sarti, ricamatrici, artigiani, commercianti e reti di approvvigionamento. Il costume rende visibili le gerarchie e collega la corte all’economia.",
      "Osserva il ritratto ufficiale di Luigi XIV dipinto da Hyacinthe Rigaud nel 1701, riprodotto nella copertina. Mantello, colonna, spada e posa costruiscono un’immagine della regalità. È una fonte della rappresentazione del potere, non una fotografia della vita comune. Domanda di lettura: quali dettagli chiedono allo spettatore di riconoscere un’autorità prima ancora di ascoltare un argomento?",
      "In sintesi: il potere viene esercitato attraverso amministrazione, esercito e fiscalità, ma anche rappresentato attraverso spazio, rituali e immagini. Il re regna dentro un sistema di vincoli e alleanze. Ora allontaniamoci dalla reggia: quale vita conduce chi produce il cibo, gli oggetti e i servizi che la sostengono?"
    ],
    "vita": [
      "Immaginiamo tre scene didattiche, costruite per confronto e non attribuite a persone documentate. In una casa contadina la famiglia controlla scorte e lavori stagionali. In città un artigiano apre una bottega in cui lavoro, formazione e vita domestica si sovrappongono. In una dimora aristocratica servitori e servitrici preparano abiti e pasti. Tutti abitano lo stesso secolo, ma non dispongono dello stesso spazio, dello stesso tempo o delle stesse possibilità.",
      "Gran parte della popolazione europea vive ancora nelle campagne. Le città concentrano mercati, amministrazioni, servizi, manifatture e poveri in cerca di lavoro. Non sono mondi separati: il grano arriva dalle campagne, i prodotti artigianali circolano nei villaggi, lavoratori e domestici si spostano. Regioni commercialmente vivaci convivono con aree meno integrate negli scambi.",
      "Nelle abitazioni modeste gli ambienti sono spesso pochi e affollati; riscaldare e illuminare costa. Non esiste però una sola “casa del povero”: materiali, clima, disponibilità di legname, ricchezza familiare e forma urbana cambiano le condizioni. Nelle dimore abbienti gli spazi possono distinguere maggiormente rappresentanza e vita privata. La separazione tra luoghi del lavoro e dell’abitare non è generale come diventerà in molte società industriali.",
      "Cereali, pane, minestre e legumi hanno un peso importante nelle diete popolari, con forti differenze locali. Carne, varietà e regolarità dell’approvvigionamento dipendono dalle risorse. Un rialzo del prezzo del pane assorbe una parte crescente del bilancio delle famiglie urbane. Nelle tavole ricche, zucchero, caffè e altri prodotti coloniali possono esibire distinzione: ciò che appare raffinato in Europa può dipendere dal lavoro coercitivo oltreoceano.",
      "L’abito protegge, ma comunica anche mestiere, genere, decoro e condizione. Rammendi, riuso e mercato dell’usato prolungano la vita dei tessuti. Le persone meno abbienti non cambiano guardaroba seguendo la corte; i modelli, però, circolano e possono essere imitati. Anche la borghesia usa il consumo per rendere riconoscibile una posizione conquistata.",
      "L’idea che nel Settecento “nessuno si lavasse” è falsa. Pratiche di pulizia, uso dell’acqua, cambio della biancheria e attenzione agli odori variano secondo periodo e ambiente. Non coincidono con la doccia quotidiana moderna né con conoscenze microbiologiche ancora da sviluppare. La disponibilità di acqua, smaltimento dei rifiuti e spazi conta quanto le convinzioni mediche. Evitiamo sia l’immagine di una corte profumata e quindi sana, sia quella di un’intera epoca indifferente alla pulizia.",
      "Medici, chirurghi, speziali, levatrici e guaritori offrono saperi e pratiche differenti. La medicina dotta conserva spiegazioni tradizionali del corpo, mentre osservazione e sperimentazione aprono nuove possibilità. Il vaiolo mostra quanto le malattie possano attraversare i ranghi sociali. L’inoculazione, discussa e non priva di rischi, precede la vaccinazione jenneriana del 1796: non vanno confuse. La ricchezza amplia l’accesso alle cure, ma non garantisce trattamenti efficaci secondo i criteri attuali.",
      "La speranza di vita alla nascita è una media condizionata dalla mortalità alle diverse età. Nella Francia di metà Settecento era molto bassa, soprattutto a causa delle morti precoci: non significa che ogni adulto morisse intorno ai venticinque anni. Chi superava l’infanzia poteva vivere molto più a lungo. Per confrontare due epoche bisogna distinguere speranza di vita alla nascita, anni attesi a un’età già raggiunta e massima longevità individuale. Nessun numero unico descrive tutti i paesi e tutti i ceti.",
      "La famiglia è unità affettiva, economica e giuridica. Matrimoni e trasmissione dei beni coinvolgono strategie familiari; età delle nozze, possibilità di scegliere e regole patrimoniali variano. Non tutti si sposano giovanissimi e non ogni matrimonio è combinato nello stesso modo. Autorità maschile e disuguaglianze di genere limitano molte scelte femminili, senza rendere le donne assenti dal lavoro: coltivano, vendono, lavorano nei servizi e nelle manifatture, gestiscono attività in condizioni diverse.",
      "I bambini possono contribuire presto all’economia domestica e apprendere un mestiere. L’accesso alla scuola è diseguale per ceto, sesso e territorio. Da questo non segue che i genitori non provino affetto: alta mortalità infantile e coinvolgimento precoce nel lavoro non dimostrano indifferenza. Le esperienze dell’infanzia devono essere ricostruite attraverso fonti, non dedotte da un pregiudizio sul passato.",
      "Campane, luce naturale, stagioni, mercati e feste scandiscono la vita. Nelle città gli orologi e gli orari del lavoro acquistano rilievo senza cancellare altri ritmi. La religione accompagna nascita, nozze e morte, sostiene assistenza e appartenenza, ma può anche legittimare gerarchie ed esclusioni. Credenza religiosa e superstizione non sono sinonimi: chiamare una pratica “superstiziosa” è spesso già una presa di posizione di chi la descrive.",
      "In sintesi: vivere nell’Antico regime significa affrontare vulnerabilità condivise con risorse molto diseguali. Per studiarle incrociamo registri parrocchiali, inventari domestici, oggetti e immagini: nessuna fonte racconta tutto. Domanda: quale differenza tra le tre mattine iniziali dipende dalla ricchezza, quale dal diritto e quale dalle conoscenze disponibili? Le trasformazioni economiche renderanno questa distinzione sempre più esplosiva."
    ],
    "cambiamento": [
      "Nel corso del Settecento la popolazione europea cresce, con ritmi e interruzioni diversi. L’aumento non va spiegato con una sola invenzione o con un improvviso trionfo della medicina. Condizioni alimentari, andamento delle epidemie, risorse agricole e comportamenti demografici interagiscono. Più persone significano domanda di cibo, terre e lavoro; possono favorire scambi e produzione, ma anche accrescere la pressione sulle risorse.",
      "Il cambiamento economico non abolisce automaticamente gli ordini. Una società può sviluppare commerci, tecniche e consumi mentre mantiene distinzioni giuridiche tradizionali. È proprio questa mancata coincidenza a creare tensioni: le capacità di produrre ricchezza e le possibilità di ottenere riconoscimento politico non procedono necessariamente alla stessa velocità.",
      "I porti e alcuni centri urbani beneficiano della crescita degli scambi. Mercanti organizzano reti di credito e distribuzione; artigiani e lavoratori rurali producono per mercati più ampi. La manifattura può concentrare persone e fasi di lavoro nello stesso luogo oppure coordinare produzione domestica dispersa. Non ogni manifattura è già una fabbrica meccanizzata: la rivoluzione industriale prende avvio in contesti specifici, soprattutto britannici, nella seconda metà del secolo.",
      "Borghesia è un termine utile, ma non descrive un soggetto unico con un programma già pronto. Un avvocato, un finanziere, un imprenditore e un piccolo commerciante non hanno necessariamente gli stessi interessi. Alcuni chiedono riforme; altri comprano terre e uffici o cercano di entrare nella nobiltà. La critica dei privilegi convive quindi con il desiderio di conquistarne uno.",
      "Con mercantilismo raggruppiamo politiche, non un unico sistema teorico identico ovunque. I governi cercano di rafforzare la potenza statale attraverso manifatture, regolazione degli scambi, dazi, compagnie privilegiate e controllo coloniale. Il commercio viene pensato anche come competizione tra Stati. Favorire una produzione nazionale può significare sostenerla e proteggerla, ma pure sottoporla a regole e monopoli.",
      "La questione non è semplicemente “Stato contro mercato”. Le imprese coloniali possono essere private e dipendere da concessioni pubbliche; la guerra difende rotte e possedimenti; le entrate commerciali alimentano le finanze. Nel Settecento fisiocratici e altri critici contestano alcuni vincoli agli scambi. Anche qui le idee economiche divergono: non tutti gli illuministi formulano la stessa ricetta.",
      "Zucchero, tabacco, caffè, tessuti e altri prodotti collegano continenti. Dietro le merci circolano capitali, informazioni e persone: alcune migrano, altre sono deportate e vendute. Nelle colonie americane il lavoro degli africani schiavizzati è centrale per molte produzioni destinate ai mercati europei. La tratta è un commercio organizzato di esseri umani, sostenuto da interessi economici e da ordinamenti che rendono persone proprietà altrui.",
      "Il noto schema triangolare aiuta a vedere connessioni fra Europa, Africa e Americhe, ma non descrive ogni viaggio o circuito commerciale. Navi e merci seguono anche percorsi diversi. Gli schiavizzati non sono soltanto vittime senza azione: resistono, conservano legami, fuggono e costruiscono possibilità di libertà. Per studiare tratta, resistenze e abolizioni apri il percorso collegato “Schiavitù e libertà”.",
      "Ecco un esempio di oggetto quotidiano che unisce costume ed economia: una tazza di caffè zuccherato consumata in un luogo di conversazione. Permette di discutere notizie e libri, ma porta sulla tavola prodotti legati a commerci imperiali e, in molti contesti, a piantagioni schiaviste. La crescita della discussione sulla libertà può convivere materialmente con sistemi di coercizione. Non è una contraddizione da cancellare per rendere il racconto più semplice.",
      "In sintesi: popolazione, produzione e commercio cambiano gli equilibri, mentre gli ordini continuano a distribuire status e prerogative. Un borghese può essere più ricco di un nobile e restare inferiore per rango. Domanda: questa tensione conduce necessariamente alla rivoluzione oppure può produrre anche compromessi e riforme? Perché diventi una critica generale serve un nuovo modo di giudicare il mondo."
    ],
    "scienza": [
      "Per comprendere l’Illuminismo occorre fermarsi sulla rivoluzione scientifica, senza ridurla alla storia di due eroi. Tra Cinquecento e Seicento strumenti, calcolo, osservazioni, esperimenti e discussioni modificano lo studio della natura. Nuove istituzioni e reti di studiosi permettono di confrontare risultati. L’autorità di un libro antico non basta più, da sola, a chiudere una questione sul funzionamento del mondo fisico.",
      "Questo non significa che prima nessuno ragionasse o osservasse. Significa che cambiano procedure, problemi e criteri di prova in determinati campi. La conoscenza non dipende dalla sola audacia del pensatore: richiede strumenti costruiti da artigiani, risorse, luoghi di lavoro e comunicazione. La ragione è una pratica che deve rendere controllabili le proprie affermazioni.",
      "Le osservazioni telescopiche di Galileo rese pubbliche nel 1610 mostrano fenomeni incompatibili con alcune immagini tradizionali dei cieli: irregolarità della Luna e satelliti di Giove incrinano aspettative consolidate. Il punto didattico non è attribuire al telescopio la dimostrazione immediata di ogni aspetto del sistema copernicano. È capire che nuove osservazioni possono costringere a rivedere un quadro teorico autorevole.",
      "Nel lavoro galileiano esperienza e matematica dialogano: non basta accumulare impressioni, bisogna formulare relazioni, isolare condizioni, confrontare previsioni e risultati. Il processo del 1633 rivela anche un conflitto fra ricerca, interpretazione delle Scritture e autorità ecclesiastica. Non autorizza a descrivere tutta la storia della scienza come una guerra senza eccezioni tra scienziati atei e credenti ostili alla conoscenza.",
      "Nei Principia del 1687 Newton collega fenomeni terrestri e celesti attraverso una costruzione matematica. Le stesse leggi possono spiegare movimenti che parevano appartenere a mondi separati. Il successo di questa impresa rafforza l’idea che la realtà possa essere compresa mediante relazioni generali, anziché soltanto raccontata attraverso qualità e finalità tradizionali.",
      "Da ciò non segue che Newton abbia già spiegato ogni aspetto della natura o che fosse estraneo alla religione. Il prestigio del metodo scientifico nasce dai risultati e alimenta nuove domande; non rende infallibile chi lo invoca. L’osservazione può correggere le teorie e i fenomeni non spiegati continuano a esistere. La fiducia nella ragione non deve essere confusa con la pretesa di sapere già tutto.",
      "Qui nasce la cerniera del percorso: se possiamo sottoporre la natura alla ragione, perché non dovremmo sottoporre alla ragione anche leggi, istituzioni, religione e potere? Una pratica antica può essere studiata per i suoi effetti. Una norma può essere confrontata con il fine che dichiara di perseguire. Il fatto che qualcosa esista da secoli non prova che sia utile o giusto.",
      "Attenzione al significato di “legge”. Una legge fisica descrive una regolarità naturale; una legge giuridica prescrive comportamenti ed è prodotta da istituzioni. La gravità non viene abrogata da un’assemblea. Un privilegio fiscale può esserlo. Il passaggio dalla scienza alla critica sociale è un’ispirazione e un allargamento delle domande, non un’equazione che consenta di ricavare la migliore costituzione dalla fisica.",
      "Considera una pena crudele giustificata con “si è sempre fatto così”. Un ragionamento critico domanda: riduce davvero i reati? Colpisce il colpevole o anche l’innocente? Esistono mezzi meno dannosi? L’esempio anticipa Beccaria e mostra un cambiamento di criterio: l’istituzione deve rispondere delle proprie ragioni e conseguenze.",
      "In sintesi: la scienza moderna fornisce esempi potenti di conoscenza controllabile, ma non causa da sola l’Illuminismo. Contano anche conflitti religiosi, circolazione dei libri, trasformazioni sociali e tradizioni filosofiche. Domanda: perché “è naturale” può descrivere correttamente un fenomeno fisico e diventare una giustificazione discutibile quando riguarda un privilegio di nascita? Da questa distinzione comincia la critica dei Lumi."
    ],
    "lumi": [
      "Lumi in francese, Enlightenment in inglese, Aufklärung in tedesco: la metafora della luce indica un’attività di chiarimento. Non descrive un continente improvvisamente uscito da un buio assoluto. È anche il modo in cui alcuni protagonisti rappresentano la propria impresa. Per lo storico il nome raccoglie correnti, luoghi e discussioni che non formano una dottrina unica.",
      "Parigi è un centro importante, ma i Lumi hanno molte geografie: Scozia, territori tedeschi, Milano, Napoli e reti transatlantiche. La critica riguarda conoscenza, morale, economia, educazione, religione e governo. Non tutti gli autori affrontano ogni tema e non arrivano alle stesse risposte. Ciò che li avvicina è il rifiuto di considerare una credenza intoccabile soltanto perché trasmessa da un’autorità.",
      "Ragione significa capacità di confrontare argomenti, cercare coerenza e distinguere prove da pregiudizi. Esperienza significa attenzione a ciò che osserviamo e a come vivono concretamente gli esseri umani. Le due dimensioni possono cooperare. I Lumi non sono semplicemente il trionfo di deduzioni astratte che ignorano i fatti: molte loro ricerche valorizzano osservazione, storia e confronto tra società.",
      "Quando si domanda se una legge favorisca il benessere pubblico, si rende discutibile ciò che prima poteva essere difeso attraverso genealogie e consuetudini. Anche la critica, però, deve giustificarsi. Gli autori possono usare conoscenze limitate, riprodurre stereotipi e formulare gerarchie tra popoli. Essere illuminista non significa essere immune dai pregiudizi del proprio tempo.",
      "Se ignoranza e dipendenza intellettuale sono almeno in parte prodotte socialmente, istruzione e circolazione del sapere possono modificarle. L’educazione diventa un problema pubblico: chi deve imparare, che cosa, con quali finalità? Accademie, libri e progetti editoriali cercano nuovi lettori. L’accesso resta comunque condizionato da alfabetizzazione, reddito, lingua e genere.",
      "La fiducia nel progresso è la speranza che conoscenze e riforme migliorino la vita. Non tutti immaginano un avanzamento lineare. Rousseau, in particolare, mette in discussione l’idea che lo sviluppo delle arti e delle scienze produca automaticamente una società moralmente migliore. Il dissenso appartiene ai Lumi: non è un disturbo da nascondere per ottenere un elenco di principi uniforme.",
      "Criticare il fanatismo non coincide necessariamente con negare Dio. Esistono illuministi deisti, pensatori religiosi riformatori, scettici e materialisti. Il deismo afferma un Dio accessibile alla ragione, senza affidarsi nello stesso modo alle rivelazioni e alle autorità confessionali. Voltaire non va quindi presentato come un semplice campione dell’ateismo; Diderot segue invece un percorso filosofico differente.",
      "La tolleranza chiede di limitare la persecuzione e la coercizione religiosa. È diversa dalla piena uguaglianza politica tra tutte le convinzioni così come oggi possiamo intenderla. Anche i suoi difensori pongono talvolta esclusioni. Una conquista concettuale può aprire possibilità senza essere già applicata universalmente: questo divario sarà decisivo per donne, minoranze e popolazioni colonizzate.",
      "Se alcuni diritti appartengono agli esseri umani in quanto tali, non possono dipendere soltanto dal sovrano o dalla nascita in un ordine. È un criterio capace di giudicare le leggi esistenti. I diritti naturali hanno radici precedenti al Settecento e fondamenti differenti secondo gli autori; non sono un’invenzione istantanea né un catalogo già identico alle dichiarazioni contemporanee.",
      "Il cosmopolitismo invita a pensarsi parte di un’umanità più ampia del proprio paese. Viaggi, traduzioni e corrispondenze favoriscono confronti, ma convivono con imperialismo e gerarchie culturali. Domanda: riconoscere in teoria una comune umanità basta se alcuni esseri umani sono esclusi dall’istruzione o ridotti a proprietà?",
      "In sintesi: i Lumi spostano il peso della prova. Tradizione e autorità devono offrire ragioni; la critica deve rispondere a ragioni migliori. Il movimento resta plurale, conflittuale e incompiuto. Ora seguiamo i suoi problemi: non “chi è nato quando?”, ma “come impedire l’arbitrio, perché obbedire, chi può sapere?”."
    ],
    "problemi": [
      "Domanda: basta affidare il potere a una persona buona? Montesquieu, nello Spirito delle leggi del 1748, sposta l’attenzione sulle istituzioni: il comando deve incontrare limiti. Distinguere funzione legislativa, esecutiva e giudiziaria aiuta a evitare che chi fa la legge la applichi e giudichi senza controllo. Non sta semplicemente proponendo una repubblica democratica moderna: studia forme di governo e apprezza l’equilibrio di poteri e corpi intermedi.",
      "Fonte guidata: Spirito delle leggi, libro XI, capitolo 6, qui parafrasato: quando legislativo ed esecutivo sono riuniti, la libertà è in pericolo; anche il giudicare deve essere distinto. Il testo interviene nel dibattito sul governo moderato e interpreta l’esperienza inglese, non offre un verbale neutrale della sua costituzione. Conseguenza storica: la limitazione istituzionale del potere diventa un linguaggio decisivo del costituzionalismo. Domanda: un tribunale può proteggerti dal governo se il governo controlla ogni sua decisione?",
      "Domanda: il comando si eredita oppure deve essere giustificato a chi obbedisce? John Locke, autore seicentesco fondamentale per il Settecento, collega il governo alla tutela di vita, libertà e proprietà. Gli individui possiedono diritti che precedono l’istituzione politica; il consenso rende possibile un’autorità capace di proteggerli con regole e giudici riconosciuti. Il contratto sociale non è un documento realmente firmato all’origine di ogni Stato, ma un modello per ragionare sulla legittimità.",
      "Fonte guidata: Secondo trattato sul governo, §§123–131, parafrasi. Si entra in società per godere dei diritti con maggiore sicurezza; il governo non riceve un potere arbitrario. Il contesto è quello delle lotte sulla monarchia inglese; la proposta non coincide con il suffragio universale odierno. Se l’autorità tradisce la fiducia e viola sistematicamente i diritti, può essere contrastata. Conseguenza: l’obbedienza non è più necessariamente incondizionata. Domanda: può essere legittimo un potere che distrugge il fine per cui è stato istituito?",
      "Rousseau, nel Contratto sociale del 1762, cerca un’associazione nella quale ciascuno, unendosi agli altri, partecipi a un corpo politico e obbedisca a una legge di cui è anche autore. La sovranità appartiene al popolo ed è inalienabile. Il governo esegue: non diventa proprietario della sovranità. La volontà generale mira all’interesse comune; non equivale alla somma dei desideri privati né a qualunque decisione presa dalla maggioranza.",
      "Fonte guidata: Contratto sociale, libro II, capitoli 1–3, parafrasi. Una decisione può perdere di vista il bene comune quando gruppi e interessi particolari dominano il giudizio. La tesi alimenta discussioni sulla partecipazione e pone un problema difficile: come riconoscere il bene comune senza permettere a qualcuno di appropriarsene? Locke insiste sulla protezione di diritti individuali preesistenti; Rousseau sulla formazione di una comunità politica libera attraverso la legge comune. Domanda: perché non basta chiamare “volontà del popolo” la volontà di chi comanda?",
      "Il caso Calas, protestante condannato a morte nel 1762, mobilita Voltaire contro il fanatismo e l’ingiustizia giudiziaria. Il Trattato sulla tolleranza del 1763 collega un caso concreto a un problema generale: differenze religiose possono autorizzare persecuzioni? Voltaire usa pubblicazioni e relazioni per raggiungere un pubblico capace di esercitare pressione. La ragione agisce anche attraverso campagne di opinione.",
      "Fonte guidata: Trattato sulla tolleranza, capitolo XXIII, parafrasi. La comune fragilità degli esseri umani dovrebbe favorire tolleranza invece di odio. È una presa di posizione polemica, non la descrizione di una libertà già realizzata. Voltaire resta deista e non sviluppa un programma democratico egualitario paragonabile a quelli successivi. Conseguenza: la persecuzione deve essere giustificata davanti a un pubblico critico. Domanda: rispettare il diritto di una persona a credere significa condividere ciò in cui crede?",
      "Cesare Beccaria pubblica Dei delitti e delle pene nel 1764. Domanda: una pena deve sfogare la violenza del sovrano o impedire nuovi danni? Una sanzione deve essere stabilita dalla legge, proporzionata al reato e necessaria. Certezza e prontezza contano più della spettacolarità della crudeltà. La tortura non è uno strumento affidabile per scoprire la verità: mette alla prova la resistenza fisica e può far confessare un innocente.",
      "Fonte: «Il fine dunque non è altro che d’impedire il reo dal far nuovi danni» (capitolo XII). Beccaria contesta la pena di morte e nega che sia necessaria nel normale governo delle leggi, discutendo anche ipotesi eccezionali: non attribuiamogli una formulazione identica a ogni abolizionismo contemporaneo. Conseguenza: il diritto di punire viene sottoposto al criterio dell’utilità pubblica e al limite della necessità. La riforma penale toscana del 1786 è un passaggio significativo. Domanda: una punizione più feroce è per questo una punizione più efficace?",
      "L’Encyclopédie, diretta da Diderot e d’Alembert, comincia a uscire nel 1751. Domanda: il sapere deve rimanere concentrato nelle autorità riconosciute oppure può essere organizzato per essere confrontato e discusso? Articoli, rinvii e tavole mettono in relazione discipline, tecniche e mestieri. Dare spazio al lavoro manuale significa riconoscere che anche una bottega produce conoscenze. L’opera affronta censura, proibizioni e difficoltà editoriali; non raggiunge indistintamente ogni abitante.",
      "Fonte guidata: Diderot, voce Encyclopédie, 1755, parafrasi. Raccogliere conoscenze disperse permette di trasmetterle e renderle utilizzabili dalle generazioni successive. È un progetto culturale con ambizioni di trasformazione, non soltanto un dizionario voluminoso. Conseguenza: l’autorità del sapere si lega anche alla circolazione e alle connessioni tra conoscenze. Domanda: perché mostrare il lavoro di un artigiano accanto a una disciplina erudita può cambiare una gerarchia culturale?",
      "Il problema attraversa tutti i precedenti: se la ragione e alcuni diritti appartengono alla persona, quale argomento autorizza un privilegio di nascita? Fonte guidata: Locke, Secondo trattato, §4, parafrasi. La condizione naturale è pensata come libertà e uguaglianza, non come subordinazione ereditaria a un sovrano. Non significa identità di capacità, ricchezza o funzione sociale. La discussione mette in questione il fondamento della disuguaglianza giuridica.",
      "In sintesi: questi autori non consegnano una costituzione comune. Offrono criteri differenti per interrogare potere, pena, fede e sapere. Le conseguenze politiche dipenderanno da lettori, conflitti e circostanze. Domanda conclusiva: quale dei problemi studiati colpisce più direttamente il mondo dei tre ordini? Argomenta collegando almeno due autori, senza renderli intercambiabili."
    ],
    "cittadini": [
      "Libri, giornali, pamphlet e corrispondenze collegano persone che non si conoscono direttamente. Caffè, salotti, accademie e biblioteche offrono luoghi per leggere, ascoltare e discutere. Non tutti funzionano allo stesso modo: un salotto seleziona gli invitati, un’accademia riconosce competenze e appartenenze, un caffè dipende da consumi e accessibilità. La novità non è che prima nessuno avesse opinioni, ma che cresce un pubblico capace di discutere questioni di interesse generale oltre i canali ufficiali della corte.",
      "Opinione pubblica indica qui uno spazio di giudizio che può essere invocato contro una decisione o una reputazione. È una trasformazione graduale e diseguale, non ancora l’opinione misurata dai sondaggi o una cittadinanza universale. Censura, costo dei libri, alfabetizzazione e disuguaglianze ne limitano l’accesso. Libri e notizie circolano anche attraverso lettura ad alta voce e reti clandestine.",
      "Nel Settecento si diffondono logge massoniche, associazioni con rituali, regole di ammissione e reti di sociabilità. Possono favorire conversazione, solidarietà e confronto tra persone di diversa provenienza. L’uguaglianza dichiarata fra membri non elimina però le selezioni sociali e di genere. Numerose logge mantengono riferimenti religiosi, e i loro aderenti assumono posizioni politiche differenti.",
      "Non è corretto far coincidere massoneria, Illuminismo e rivoluzione. La presenza di alcuni illuministi nelle logge non prova che esse progettino collettivamente gli eventi successivi. Per studiarne il ruolo servono statuti, elenchi di membri, corrispondenze e attività documentate. Una rete può facilitare la circolazione senza avere una volontà politica unica.",
      "Salottiere come Madame Geoffrin organizzano relazioni e conversazioni; scrittrici, traduttrici e lettrici partecipano alla diffusione delle idee. Émilie du Châtelet lavora su fisica e filosofia e traduce e commenta Newton. Non sono soltanto muse che ispirano uomini: producono sapere e rendono possibile la vita intellettuale. Questa partecipazione riguarda tuttavia condizioni particolari e non annulla gli ostacoli che limitano l’istruzione femminile.",
      "La contraddizione emerge storicamente: si ragiona di esseri umani universali mentre gran parte delle donne rimane esclusa dalla cittadinanza politica. Non tutti gli illuministi contestano allo stesso modo i ruoli di genere; Rousseau, nell’Emilio, propone per Sophie un’educazione orientata a compiti diversi da quelli maschili. Le rivendicazioni di Olympe de Gouges nel 1791 e Mary Wollstonecraft nel 1792 renderanno esplicita la richiesta di estendere i principi proclamati: sono sviluppi della fase rivoluzionaria, non diritti già acquisiti nei salotti.",
      "L’Europa dei diritti continua a trarre risorse da imperi coloniali e lavoro schiavizzato. Non basta dire che “gli illuministi erano abolizionisti”. Montesquieu usa l’ironia per smontare giustificazioni della schiavitù, ma il suo discorso complessivo conserva argomenti climatici problematici. Locke difende diritti naturali mentre la sua attività è intrecciata con l’amministrazione coloniale; il rapporto tra teoria e coinvolgimenti storici richiede attenzione, non assoluzioni automatiche.",
      "Voltaire denuncia in Candide la violenza della schiavitù attraverso l’incontro con lo schiavo di Suriname, senza per questo cancellare i propri stereotipi e ambivalenze. Diderot sviluppa critiche della dominazione coloniale; altri autori arrivano a posizioni diverse o meno radicali. Gli schiavizzati contribuiscono direttamente alla lotta per la libertà: le abolizioni non sono soltanto un dono di filosofi europei. Domanda: un principio universale può diventare un’arma anche nelle mani di chi i suoi primi enunciatori escludono?",
      "Il dispotismo illuminato, o assolutismo illuminato, raccoglie esperienze diverse di monarchie che promuovono riforme senza consegnare la sovranità al popolo. Federico II di Prussia associa cultura filosofica, razionalizzazione amministrativa e iniziative giudiziarie a potenza militare e gerarchie sociali. Maria Teresa, sovrana profondamente cattolica, riorganizza amministrazione e fiscalità e promuove la riforma scolastica del 1774: riformismo non significa adesione uniforme alla filosofia dei Lumi.",
      "Giuseppe II amplia la tolleranza religiosa con provvedimenti del 1781, interviene sulle istituzioni ecclesiastiche e riduce forme di dipendenza personale dei contadini. Non abolisce in un solo gesto tutti gli oneri signorili; applicazione, opposizioni e differenze territoriali contano. La razionalizzazione del governo può limitare privilegi e al tempo stesso rafforzare l’autorità centrale. I destinatari delle riforme restano spesso sudditi a cui si comunica una decisione.",
      "Caterina II di Russia dialoga con gli illuministi e nel Nakaz del 1767 riprende temi del dibattito giuridico. Il suo impero mantiene però servitù e potere nobiliare, consolidati durante il regno. La distanza fra linguaggio riformatore e rapporti sociali è parte del problema. La formula “Tutto per il popolo, niente attraverso il popolo” è usata qui soltanto come sintesi didattica del paternalismo riformatore, senza attribuirla come citazione letterale certa a un sovrano.",
      "Confrontiamo privilegio e diritto, ordine e individuo, suddito e cittadino, diritto divino e sovranità fondata politicamente, censura e libertà di pensiero, tradizione e critica. Queste coppie indicano tensioni: la seconda parola non cancella la prima alla fine del secolo. Inoltre sovranità e diritti non impongono da soli un’unica forma di governo. Uguaglianza giuridica, uguaglianza economica e partecipazione politica sono questioni connesse ma differenti.",
      "L’Illuminismo non abbatte l’Antico regime. Rende sempre più difficile giustificarlo.",
      "Da qui nasceranno le rivoluzioni politiche della fine del Settecento. “Da qui” indica anche questo laboratorio di idee, non una causa unica: crisi fiscali, guerre, conflitti coloniali, interessi sociali e decisioni concrete saranno indispensabili. Le rivoluzioni non erano inevitabili e non realizzeranno subito tutti i diritti proclamati.",
      "In sintesi: la nascita non scompare, ma perde evidenza come ragione sufficiente del comando. L’individuo può essere pensato come titolare di ragione e diritti, e il suddito può rivendicare di partecipare alla legge come cittadino. Domanda finale: perché un’istituzione può diventare culturalmente più fragile prima di essere politicamente abbattuta? Rispondi con un esempio tratto dalla società per ordini, uno dai Lumi e uno dai loro limiti."
    ]
  },
  "approfondimenti": {
    "versailles": [
      "Un privilegio può essere anche un posto in una stanza. Alla corte di Luigi XIV l’etichetta distribuisce accessi e riconoscimenti: chi assiste a un rito e chi ne resta fuori vede confermata la propria posizione. La reggia organizza così una gerarchia che tutti imparano a leggere. Il cerimoniale non è un ornamento aggiunto al governo; è una delle forme attraverso cui il governo costruisce dipendenza e consenso.",
      "La partecipazione alla corte comporta spese e relazioni. Un aristocratico può cercare un incarico per sé o per un parente, una pensione o una precedenza. Il sovrano dispone di risorse da distribuire e usa la vicinanza come segno di favore. Tuttavia non tutta la nobiltà è presente e le famiglie mantengono proprietà e reti autonome. La corte integra e disciplina, ma non annulla ogni forza sociale.",
      "Laboratorio sulla fonte: osserva il ritratto di Rigaud. Separa tre livelli: ciò che vedi (abiti, oggetti, posa), ciò che l’immagine vuole comunicare (maestà, continuità, autorità), ciò che non puoi ricavarne (bilancio dello Stato, obbedienza reale delle province). Confronta poi il sovrano isolato nel ritratto con la pluralità di persone nel salotto di Lemonnier. Stai confrontando due strategie di rappresentazione, non misurando con una fotografia la libertà del Settecento."
    ],
    "quotidiano": [
      "Un inventario post mortem elenca oggetti e beni appartenuti a una persona. Può documentare letti, stoviglie, abiti, utensili e libri. Permette di formulare domande concrete: quanti ambienti erano disponibili? Dove si lavorava? Quali oggetti erano abbastanza preziosi da essere registrati? Non restituisce però l’intera esperienza affettiva e può trascurare ciò che non aveva valore per chi redigeva il documento.",
      "Confrontare inventari di condizioni sociali diverse aiuta a non scambiare la vita della corte per la vita di tutti. Anche un dipinto di interni seleziona: può celebrare ordine domestico, moralità o lusso. Una scena elegante non prova la diffusione generale di quell’abitazione. Regioni, città e campagne richiedono confronti distinti.",
      "Per la salute, affianca fonti materiali e registri demografici. Una media bassa alla nascita risente delle molte morti infantili; non stabilisce l’età a cui ogni adulto muore. Anche pulizia, igiene e cura medica vanno separate: si può cercare di essere puliti senza conoscere i microrganismi, oppure disporre di medici senza cure efficaci per una determinata malattia. Domanda: quali prove ti servirebbero per affermare che una pratica era diffusa, invece che semplicemente possibile?"
    ],
    "borghesia": [
      "Un mercante può preferire la sicurezza di un privilegio alla libertà generale di commercio. Un professionista può criticare l’esclusione dagli incarichi; un finanziere può collaborare con la monarchia. Chiamarli tutti borghesi non autorizza a pensare che preparino insieme una rivoluzione. Il termine riunisce condizioni e interessi diversi, che in certe crisi possono convergere ma non sono sempre concordi.",
      "L’acquisto di uffici e la ricerca della nobilitazione rivelano la forza culturale della gerarchia. Se la ricchezza viene utilizzata per ottenere un rango superiore, l’ascesa individuale può rafforzare il sistema invece di distruggerlo. La stessa esclusione può però diventare ingiustificabile quando è confrontata con capacità, utilità sociale e diritti.",
      "Esercizio argomentativo: un mercante arricchito compra un titolo; un altro chiede che il titolo non dia più esenzioni. Quale scelta cambia la posizione della persona, quale cambia il principio dell’ordinamento? Spiega perché entrambe sono possibili nello stesso contesto. La trasformazione storica nasce anche da scelte alternative, non soltanto dall’aumento della ricchezza."
    ],
    "salotti": [
      "Una notizia stampata può raggiungere lettori lontani e venire ripresa in discussioni, lettere e altri fogli. La pubblicazione produce un pubblico che non coincide con i presenti in una sala. I luoghi della conversazione alimentano questo circuito: si legge insieme, si discute un libro, si giudica un fatto. La critica acquista durata perché può essere riprodotta e contestata.",
      "Caffè e salotti non sono istituzioni democratiche aperte indistintamente. Nei salotti conta l’invito; nei caffè contano costo, reputazione e consuetudini di accesso. Le salottiere selezionano e mediano, contribuendo a dare forma alla discussione. L’apertura culturale può convivere con l’esclusione sociale: è questo intreccio, non una libertà già compiuta, a rendere interessante la loro storia.",
      "L’immagine di Lemonnier usata nella copertina fu dipinta nel 1812 e ricostruisce idealmente il salotto di Geoffrin nel 1755. Non documenta una riunione realmente avvenuta in quella composizione. La lettura rappresentata riguarda L’orfano della Cina di Voltaire, non l’Encyclopédie. Serve quindi a studiare anche la memoria dei Lumi: perché un pittore successivo riunisce così tanti protagonisti nello stesso spazio?"
    ],
    "enciclopedia": [
      "Un ordinamento del sapere compie scelte: stabilisce quali conoscenze meritino una voce, come collegarle e a quali autorità riferirsi. Nell’Encyclopédie la presenza di arti meccaniche e mestieri rende leggibili competenze che la cultura erudita poteva subordinare al lavoro intellettuale. Le tavole mostrano strumenti e procedimenti: rendono osservabile un sapere pratico.",
      "L’impresa comincia nel 1751 e la prima grande raccolta comprende diciassette volumi di testo e undici di tavole, pubblicati entro il 1772. Collaboratori numerosi e posizioni non uniformi impediscono di leggerla come la voce di un solo filosofo. D’Alembert lascia la direzione prima del completamento; Diderot continua il lavoro tra ostacoli politici ed editoriali. Il pubblico iniziale è condizionato dal costo e dalla competenza dei lettori.",
      "Un rinvio tra voci non è soltanto una comodità: invita a controllare un’affermazione attraverso un’altra. Prova a immaginare un’enciclopedia che includa “sovrano”, “diritto” e “cittadino” senza permettere alcun collegamento. Che cosa perderebbe? Non chiamiamo però l’opera “Internet del Settecento”: la metafora nasconderebbe differenze di accesso, produzione e controllo."
    ],
    "logge": [
      "Le logge massoniche sono associazioni con rituali, simboli, gerarchie interne e regole di appartenenza. Nel Settecento favoriscono reti di relazione oltre alcuni confini territoriali e confessionali. Per comprendere questa sociabilità non serve attribuire ai simboli poteri misteriosi: servono documenti sulle pratiche, sui membri e sui legami.",
      "Una dichiarazione di fratellanza fra soci non equivale all’uguaglianza dell’intera società. Se l’accesso seleziona per sesso, risorse o reputazione, l’uguaglianza interna si regge su esclusioni esterne. Anche le forme di partecipazione femminile, dove esistono, vanno studiate nelle loro specifiche regole, senza inventare una condizione uniforme.",
      "La domanda storica corretta non è “quale evento hanno segretamente deciso?”, ma “quali persone hanno messo in relazione e quali attività documentate hanno svolto?”. L’appartenenza di due protagonisti alla massoneria non prova che concordassero politicamente. È la stessa cautela necessaria nello studio di accademie e salotti: una rete permette contatti, ma non produce automaticamente un programma comune."
    ],
    "donne": [
      "Geoffrin rende possibili incontri e relazioni; du Châtelet traduce, commenta e produce filosofia naturale. Queste attività non sono equivalenti, ma mostrano che le donne non stanno tutte ai margini della cultura dei Lumi. La loro visibilità dipende spesso da risorse e reti particolari: non possiamo trasformare alcune figure eccezionali nella prova di una parità diffusa.",
      "Il problema diventa politico quando un discorso sull’essere umano universale distribuisce diversamente istruzione, autonomia e partecipazione secondo il sesso. Rousseau critica la dipendenza sociale ma nell’Emilio assegna a Sophie un’educazione diversa da quella del protagonista maschile. La tensione non va cancellata scegliendo soltanto le pagine che corrispondono alle nostre aspettative.",
      "Nel 1791 Olympe de Gouges usa la forma della dichiarazione dei diritti per denunciare l’esclusione delle donne; nel 1792 Wollstonecraft insiste sull’educazione e sulla capacità razionale. Sono interventi collocati nella fase rivoluzionaria. Attività: distinguere tre piani — partecipare alla cultura, possedere diritti civili, partecipare al potere politico — e spiegare perché il primo non garantisce automaticamente gli altri due."
    ],
    "liberta": [
      "La domanda “libertà per chi?” impedisce di separare artificialmente storia europea e storia coloniale. Un diritto presentato come naturale dovrebbe valere indipendentemente dalla nascita; il sistema schiavista istituisce invece condizioni ereditarie di dominio. La contraddizione riguarda la struttura del mondo atlantico, non soltanto l’incoerenza privata di qualche autore.",
      "Le posizioni vanno distinte. Nel libro XV dello Spirito delle leggi Montesquieu mette in ridicolo giustificazioni dello schiavismo, ma conserva nel quadro generale argomenti climatici che richiedono lettura critica. In Candide, capitolo XIX, Voltaire rappresenta il prezzo umano dello zucchero attraverso lo schiavo di Suriname. Il racconto denuncia una violenza: non autorizza a cancellare ogni altro pregiudizio dell’autore. Il rapporto fra la filosofia dei diritti di Locke e i suoi coinvolgimenti coloniali è oggetto di discussione storiografica.",
      "Nessuna di queste posizioni esaurisce la storia della libertà. Fuga, resistenza, rivolte, testimonianze e organizzazione degli schiavizzati modificano concretamente i rapporti di forza. Prosegui nella PWA “Schiavitù e libertà” per passare dai principi ai soggetti che li mettono alla prova, fino ad Haiti e alle abolizioni. Domanda: chi deve poter definire il significato della libertà perché essa smetta di essere soltanto una concessione?"
    ],
    "dispotismo": [
      "Un sovrano può finanziare scuole, semplificare procedure e contrastare alcuni privilegi per migliorare il benessere e rendere più efficace lo Stato. Le motivazioni possono combinare convinzioni filosofiche, bisogni fiscali, reclutamento militare e competizione internazionale. Chiedere che cosa una riforma produce è più utile che classificare ogni sovrano come “buono” o “cattivo”.",
      "Federico II, Maria Teresa, Giuseppe II e Caterina II non realizzano lo stesso programma. Maria Teresa riforma mantenendo forti convinzioni confessionali; Giuseppe II interviene più energicamente sui rapporti religiosi e sulla dipendenza personale contadina; Caterina abbina linguaggio illuminista e consolidamento di poteri nobiliari. Le resistenze e le applicazioni territoriali rendono i risultati diseguali.",
      "La formula “Tutto per il popolo, niente attraverso il popolo” è una sintesi didattica, non una citazione qui attribuita a un autore verificato. Il nodo è distinguere beneficio e partecipazione: ricevere una scuola non significa scegliere il governo. Domanda: una riforma concessa dall’alto può ampliare la libertà concreta e insieme rafforzare chi governa? Indica un possibile meccanismo per ciascuno dei due effetti."
    ],
    "riassunto": [
      "L’Antico regime è il nome retrospettivo degli assetti precedenti alla Rivoluzione francese. La Francia ne è un caso centrale, non il modello identico di tutta l’Europa. La società per ordini distingue clero, nobiltà e Terzo Stato; ogni ordine contiene condizioni economiche molto diverse. Il privilegio è una prerogativa giuridica: la ricchezza da sola non spiega lo status di una persona.",
      "La monarchia assoluta rivendica la supremazia politica del sovrano, spesso giustificata attraverso il diritto divino. Governa mediante amministrazione, esercito, fiscalità e diplomazia, ma incontra autonomie, consuetudini e resistenze. Versailles rende visibile la gerarchia attraverso cerimoniali, moda, rituali e accessi. Il potere viene rappresentato oltre che esercitato.",
      "La vita quotidiana dipende da ceto, genere, territorio e risorse. La terra e i raccolti sostengono molte famiglie; prezzi, malattie e mortalità infantile rendono la vita vulnerabile. Una bassa speranza di vita alla nascita non significa che tutti gli adulti muoiano giovani. Non è corretto immaginare un’epoca in cui nessuno si lava o nessun genitore ama i figli.",
      "Popolazione, manifatture, città e commerci crescono con ritmi diversi. I circuiti coloniali mettono in relazione merci, denaro e persone, comprese quelle deportate attraverso la tratta atlantica. Un borghese può diventare ricco senza ottenere lo status di un nobile; può cercare di entrare nell’élite o criticarne i privilegi. Il cambiamento economico non produce automaticamente una rivoluzione.",
      "La rivoluzione scientifica fornisce modelli di ricerca fondati su osservazione, esperienza, matematica e argomentazione. Galileo e Newton mostrano la forza di nuove procedure e spiegazioni. Da questo successo nasce anche una domanda più ampia: perché le istituzioni umane dovrebbero sottrarsi alla critica? Le leggi naturali descrivono fenomeni; quelle giuridiche sono norme storicamente modificabili.",
      "L’Illuminismo è una pluralità di correnti, non una dottrina unica. Ragione, esperienza, educazione, tolleranza e discussione pubblica mettono alla prova tradizioni e autorità. Esistono religiosità riformatrici, deismo, scetticismo e materialismo. La fiducia nel progresso non è uniforme; Rousseau ne contesta interpretazioni troppo semplici.",
      "Montesquieu studia limiti ed equilibrio dei poteri. Locke giustifica il governo attraverso consenso e tutela dei diritti individuali. Rousseau pone al centro sovranità popolare e volontà generale orientata al bene comune. Voltaire combatte fanatismo e persecuzione; Beccaria vuole pene legali, necessarie e proporzionate e critica tortura e pena di morte. Diderot e d’Alembert organizzano la diffusione critica del sapere nell’Encyclopédie.",
      "Caffè, salotti, giornali, libri, accademie, biblioteche e logge alimentano nuove reti di opinione. La partecipazione resta diseguale. Le donne contribuiscono alla cultura, ma sono largamente escluse dal potere politico. Gli imperi mantengono schiavitù e dominio mentre circolano diritti universali. Le resistenze degli esclusi obbligano a misurare i principi con la loro applicazione.",
      "Il dispotismo illuminato riforma dall’alto senza trasferire la sovranità al popolo. Le riforme di Federico II, Maria Teresa, Giuseppe II e Caterina II hanno orientamenti e limiti diversi. I Lumi rendono discutibile la nascita come fondamento del privilegio, ma non realizzano immediatamente democrazia e uguaglianza. Guerre, crisi fiscali e scelte politiche concorreranno alle rivoluzioni americana e francese.",
      "L’Illuminismo non abbatte l’Antico regime. Rende sempre più difficile giustificarlo."
    ]
  }
};
