(() => {
  const D = window.HIST_DATA, app = document.getElementById('app');
  const storage = D.meta.storageKey;
  let currentLesson = null, quizState = { index: 0, answers: [] }, deferredInstall;
  const $ = id => document.getElementById(id);
  const esc = v => String(v).replace(/[&<>\"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
  const norm = v => String(v).normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();
  const storageGet = (key, fallback = '') => { try { const value = localStorage.getItem(key); return value === null ? fallback : value; } catch (_) { return fallback; } };
  const storageSet = (key, value) => { try { localStorage.setItem(key, value); return true; } catch (_) { toast('Salvataggio locale non disponibile'); return false; } };
  const parseStored = (key, fallback) => { try { return JSON.parse(storageGet(key, JSON.stringify(fallback))); } catch (_) { return fallback; } };
  const completed = () => { const value = parseStored(`${storage}:completed`, []); return Array.isArray(value) ? value : []; };
  const saveCompleted = value => storageSet(`${storage}:completed`, JSON.stringify(value));
  const lessonById = id => D.lessons.find(l => l.id === id) || D.lessons[0];
  const toast = message => { const el = $('toast'); el.textContent = message; el.classList.add('show'); clearTimeout(el._t); el._t = setTimeout(() => el.classList.remove('show'), 2200); };
  $('brandTitle').textContent = D.meta.shortTitle;

  function hero(kicker, title, lead) { return `<header class="page-hero"><p class="overline">${kicker}</p><h1>${title}</h1><p>${lead}</p></header>`; }
  function toolsBar(lesson) { const done = completed().includes(lesson.id); return `<div class="lesson-tools"><button class="button button-ghost" data-notes>✎ Taccuino</button><button class="button button-ghost" data-highlight>▰ Evidenzia</button><button class="button ${done ? 'button-gold' : 'button-accent'}" data-complete>${done ? 'Completata ✓' : 'Segna come completata'}</button><a class="button button-ghost" href="assets/pdf/lezioni/${lesson.number}-${lesson.id}.pdf" target="_blank">PDF ↗</a></div>`; }
  function routeProgress() { const done = completed(); return `<section class="progress-panel"><span>Avanzamento</span><div class="progress-track"><i style="width:${done.length / D.lessons.length * 100}%"></i></div><strong>${done.length}/${D.lessons.length}</strong></section>`; }
  function relatedLinks(lesson) { const links = lesson.connections; return `<section class="lesson-connections"><p class="overline">Connessioni per verificare</p><h2>Segui attori, spazio e cronologia</h2><div><a href="#mappe"><small>Carta</small>${links.map} →</a><a href="#timeline"><small>Tempo</small>Timeline ragionata →</a>${links.people.map(id => { const p = D.people.find(person => person.id === id); return `<a href="#biografia/${id}"><small>Biografia</small>${p.name} →</a>`; }).join('')}</div></section>`; }
  function specialActivity(lesson) {
    if (lesson.activity.type === 'budget') return `<div class="budget-lab" aria-labelledby="budget-title"><h3 id="budget-title">Distribuisci 100 punti di spesa</h3><p class="lab-note">Modello concettuale: non riproduce il bilancio storico in lire.</p><div class="budget-controls">${[['Esercito',25],['Scuola',10],['Ferrovie',20],['Amministrazione',10],['Debito',25],['Opere pubbliche',10]].map(([name,value]) => `<label>${name}<span><input type="range" min="0" max="45" value="${value}" data-budget="${name}"><output>${value}</output></span></label>`).join('')}</div><fieldset class="revenue-choice"><legend>Prelievo prevalente</legend><label><input type="radio" name="revenue" value="indiretto" checked> Consumi e macinato</label><label><input type="radio" name="revenue" value="diretto"> Redditi e proprietà</label><label><input type="radio" name="revenue" value="debito"> Nuovo debito</label></fieldset><div class="budget-result" id="budgetResult" role="status" aria-live="polite"></div></div>`;
    if (lesson.activity.type === 'data') return `<div class="data-lab"><div class="data-tabs" role="tablist" aria-label="Scegli un indicatore"><button class="active" data-metric="literacy">Alfabetizzazione</button><button data-metric="school">Scuola</button><button data-metric="rail">Ferrovie</button></div><div class="metric-panel" id="metricPanel" role="status" aria-live="polite"></div><p class="lab-note">Indicatori con popolazioni e denominatori diversi non vanno sommati né trasformati in un'unica classifica dello sviluppo.</p></div>`;
    if (lesson.activity.type === 'decision') return `<div class="decision-grid" role="group" aria-label="Modelli amministrativi"><button data-model="Accentrato"><strong>Accentrato</strong><small>Decisione rapida, minore autonomia</small></button><button data-model="Regionale"><strong>Regionale</strong><small>Unità con competenze territoriali</small></button><button data-model="Federale"><strong>Federale</strong><small>Autogoverno ampio, coordinamento più difficile</small></button></div><p class="decision-result" id="decisionResult" aria-live="polite">Seleziona un modello e poi argomenta nel testo.</p>`;
    return '';
  }
  function renderLessons() { currentLesson = null; const next = D.meta.next?.url && D.meta.next.url !== '#' ? `<a href="${D.meta.next.url}"><small>Modulo successivo</small>${D.meta.next.title} →</a>` : `<span class="future-link"><small>Prossima tappa</small>${D.meta.next?.title || 'In preparazione'}</span>`; app.innerHTML = `<div class="app-container">${hero('Indice ragionato', 'Sette lezioni, una domanda', D.meta.question)}${routeProgress()}<div class="lesson-index">${D.lessons.map(l => `<a class="lesson-index-card" href="#lezione/${l.id}"><span>${l.number}</span><div><p class="overline">${l.period}</p><h2>${l.title}</h2><p>${l.lead}</p></div><b>→</b></a>`).join('')}</div><nav class="module-links"><a href="${D.meta.previous.url}"><small>Modulo precedente</small>← ${D.meta.previous.title}</a>${next}</nav></div>`; }
  function renderLesson(id) {
    const l = lessonById(id); currentLesson = l;
    const idx = D.lessons.indexOf(l), prev = D.lessons[idx - 1], next = D.lessons[idx + 1];
    app.innerHTML = `<div class="app-container reading-container">${hero(`Lezione ${l.number} · ${l.period}`, l.title, l.question)}${toolsBar(l)}<article class="lesson-body"><div class="problem-card"><p class="overline">Problema storico</p><p>${l.lead}</p></div>${l.sections.map(s => `<section class="reading-section"><h2>${s.title}</h2>${s.paragraphs.map(p => `<p>${p}</p>`).join('')}<aside class="summary"><strong>In sintesi.</strong> ${s.summary}</aside></section>`).join('')}<section class="source-link"><p class="overline">Fonte o immagine da interrogare</p><h2>${l.source.title}</h2><p>${l.source.prompt}</p><a class="text-link" href="#fonti/${l.source.id}">Apri il laboratorio sulla fonte →</a></section>${relatedLinks(l)}<section class="activity-card"><p class="overline">Attività</p><h2>${l.activity.title}</h2><p>${l.activity.prompt}</p>${specialActivity(l)}<label for="activity-${l.id}">Risposta argomentata</label><textarea id="activity-${l.id}" data-activity="${l.id}" placeholder="Scrivi una risposta usando almeno due prove…"></textarea><button class="button button-gold" data-save-activity="${l.id}">Salva attività</button></section><section class="apparatus-grid"><article class="apparatus"><h2>Coordinate</h2><ul>${l.coordinates.map(x => `<li>${x}</li>`).join('')}</ul></article><article class="apparatus"><h2>Saperi irrinunciabili</h2><ul>${l.essentials.map(x => `<li>${x}</li>`).join('')}</ul></article><article class="apparatus wide"><h2>Vocabolario essenziale</h2><div class="vocab-grid">${Object.entries(l.vocab).map(([k,v]) => `<div><h3>${k.replaceAll('_',' ')}</h3><p>${v}</p></div>`).join('')}</div></article><article class="apparatus wide"><h2>Risposta progressiva</h2><p>${l.answer}</p></article></section></article><nav class="lesson-nav">${prev ? `<a href="#lezione/${prev.id}">← ${prev.title}</a>` : '<span></span>'}${next ? `<a href="#lezione/${next.id}">${next.title} →</a>` : `<a href="#laboratorio">Costruisci la tesi →</a>`}</nav></div>`;
    const field = $(`activity-${l.id}`); field.value = storageGet(`${storage}:activity:${l.id}`, '');
    bindLesson(); bindSpecialActivity(l);
  }
  function bindSpecialActivity(lesson) {
    if (lesson.activity.type === 'budget') {
      const update = () => { const values = [...document.querySelectorAll('[data-budget]')].map(input => ({ name: input.dataset.budget, value: Number(input.value) })); values.forEach((item,i) => document.querySelectorAll('[data-budget]')[i].nextElementSibling.value = item.value); const total = values.reduce((sum,item) => sum + item.value,0), revenue = document.querySelector('input[name=revenue]:checked').value, low = values.filter(item => item.value < 10).map(item => item.name), high = values.filter(item => item.value > 30).map(item => item.name); const balance = total === 100 ? 'Bilancio in equilibrio' : total > 100 ? `Deficit di ${total-100} punti` : `Margine di ${100-total} punti`; const tax = revenue === 'indiretto' ? 'Consenso popolare in calo: il prelievo sui consumi è regressivo.' : revenue === 'diretto' ? 'Resistenza dei proprietari e dei contribuenti più influenti.' : 'Liquidità immediata, ma interessi e dipendenza futura aumentano.'; $('budgetResult').innerHTML = `<strong>${balance}</strong><p>${tax}</p>${low.length ? `<p><b>Settori sacrificati:</b> ${low.join(', ')}.</p>` : ''}${high.length ? `<p><b>Priorità dominante:</b> ${high.join(', ')}.</p>` : ''}`; };
      document.querySelectorAll('[data-budget], input[name=revenue]').forEach(el => el.addEventListener('input', update)); update();
    }
    if (lesson.activity.type === 'data') {
      const metrics = { literacy: { title: 'Capacità di leggere e scrivere, popolazione sopra i 15 anni', bars: [['Nord-Ovest',48,'48%'],['Mezzogiorno',15,'15%']], note: 'Stima comparativa: Bastasin e Toniolo, Cambridge University Press, 2023.' }, school: { title: 'Iscritti a scuola fra 5 e 19 anni', bars: [['Italia 1861',15.7,'15,7%'],['Non iscritti',84.3,'84,3%']], note: 'Primo censimento dell’Italia unita; modulo didattico Istat.' }, rail: { title: 'Rete ferroviaria complessiva', bars: [['1861',34,'2.189 km'],['1870',100,'6.429 km']], note: 'Valori nazionali approssimati; le serie possono variare in base alla data e alla definizione adottata. La densità regionale rimane diseguale.' } };
      const show = key => { const m=metrics[key]; $('metricPanel').innerHTML=`<h3>${m.title}</h3>${m.bars.map(([label,value,display])=>`<div class="metric-row"><span>${label}</span><i><b style="width:${Math.min(value,100)}%"></b></i><strong>${display}</strong></div>`).join('')}<small>${m.note}</small>`; document.querySelectorAll('[data-metric]').forEach(b=>b.classList.toggle('active',b.dataset.metric===key)); };
      document.querySelectorAll('[data-metric]').forEach(button => button.addEventListener('click',()=>show(button.dataset.metric))); show('literacy');
    }
    if (lesson.activity.type === 'decision') document.querySelectorAll('[data-model]').forEach(button => button.addEventListener('click',()=>{ document.querySelectorAll('[data-model]').forEach(b=>b.classList.toggle('active',b===button)); $('decisionResult').innerHTML=`Hai scelto <strong>${button.dataset.model}</strong>. Ora indica un vantaggio, un rischio e una garanzia contro l'abuso di potere.`; }));
  }
  function bindLesson() {
    document.querySelector('[data-notes]')?.addEventListener('click', openNotes);
    document.querySelector('[data-highlight]')?.addEventListener('click', () => { document.body.classList.toggle('highlight-mode'); toast(document.body.classList.contains('highlight-mode') ? 'Seleziona un testo per evidenziarlo' : 'Evidenziazione disattivata'); });
    document.querySelector('[data-complete]')?.addEventListener('click', e => { let done = completed(); done = done.includes(currentLesson.id) ? done.filter(x => x !== currentLesson.id) : [...done, currentLesson.id]; saveCompleted(done); e.currentTarget.textContent = done.includes(currentLesson.id) ? 'Completata ✓' : 'Segna come completata'; toast('Avanzamento aggiornato'); });
    document.querySelector('[data-save-activity]')?.addEventListener('click', e => { const id = e.currentTarget.dataset.saveActivity; if (storageSet(`${storage}:activity:${id}`, $(`activity-${id}`).value)) toast('Attività salvata'); });
    document.querySelectorAll('.reading-section p').forEach(p => p.addEventListener('mouseup', () => { if (!document.body.classList.contains('highlight-mode')) return; const sel = window.getSelection(); if (sel && !sel.isCollapsed && p.contains(sel.anchorNode)) { const range = sel.getRangeAt(0); const mark = document.createElement('mark'); try { range.surroundContents(mark); sel.removeAllRanges(); } catch (_) { toast('Seleziona parole all’interno dello stesso paragrafo'); } } }));
  }
  function renderPeople(id) { const list = id ? D.people.filter(p => p.id === id) : D.people; app.innerHTML = `<div class="app-container">${hero('Attori e vincoli', id ? list[0].name : 'Biografie essenziali', id ? list[0].role : 'Nessun protagonista agisce da solo: idee, risorse, alleati e avversari ne limitano le scelte.')}<div class="people-grid">${list.map(p => `<article class="person-card"><img src="${p.image}" alt="${esc(p.imageAlt || `Ritratto di ${p.name}`)}" loading="lazy"><div><p class="overline">${p.dates}</p><h2>${p.name}</h2><p><strong>${p.role}</strong></p><p>${p.bio}</p><aside class="summary"><strong>Nodo.</strong> ${p.idea}</aside>${id ? '' : `<a class="text-link" href="#biografia/${p.id}">Scheda completa →</a>`}</div></article>`).join('')}</div>${id ? '<p><a class="button button-ghost" href="#biografie">← Tutte le biografie</a></p>' : ''}</div>`; }
  function renderTimeline() { const scales = [...new Set(D.timeline.map(t => t.scale))]; app.innerHTML = `<div class="app-container">${hero('Tempo e causalità', 'Timeline ragionata', 'Ogni data chiarisce che cosa cambia, non sostituisce la spiegazione. Filtra per scala per vedere come eventi locali, italiani ed europei si incrociano.')}<div class="timeline-filters" aria-label="Filtra la timeline"><button class="active" data-timeline-filter="all">Tutte</button>${scales.map(s => `<button data-timeline-filter="${esc(s)}">${s}</button>`).join('')}</div><p class="timeline-status" id="timelineStatus" aria-live="polite">${D.timeline.length} eventi visibili</p><div class="timeline">${D.timeline.map(t => `<article data-scale="${esc(t.scale)}"><time>${t.date}</time><div><h2>${t.title}</h2><p>${t.text}</p><small>${t.scale}</small></div></article>`).join('')}</div></div>`; document.querySelectorAll('[data-timeline-filter]').forEach(button => button.addEventListener('click', () => { const value = button.dataset.timelineFilter; let visible = 0; document.querySelectorAll('.timeline article').forEach(item => { const show = value === 'all' || item.dataset.scale === value; item.hidden = !show; if (show) visible++; }); document.querySelectorAll('[data-timeline-filter]').forEach(b => b.classList.toggle('active', b === button)); $('timelineStatus').textContent = `${visible} ${visible === 1 ? 'evento visibile' : 'eventi visibili'}`; })); }
  function renderMaps() { app.innerHTML = `<div class="app-container">${hero('Geografia del conflitto', 'Mappe ragionate', 'Carte schematiche, non in scala: servono a leggere relazioni, velocità e vincoli.')}<div class="maps-grid">${D.maps.map(m => `<article class="map-card"><button class="map-open" data-image="${m.image}" data-title="${esc(m.title)}"><img src="${m.image}" alt="${esc(m.alt)}" loading="lazy"></button><h2>${m.title}</h2><p>${m.text}</p><p class="map-note">${m.note}</p><button class="button button-ghost map-open" data-image="${m.image}" data-title="${esc(m.title)}">Ingrandisci</button></article>`).join('')}</div><p><a class="button button-gold" href="assets/pdf/approfondimenti/mappe-e-schemi.pdf" target="_blank">Dossier cartografico PDF ↗</a></p></div>`; bindMapButtons(); }
  function renderSources(id) {
    const sources = id ? D.sources.filter(s => s.id === id) : D.sources;
    app.innerHTML = `<div class="app-container">${hero('Laboratorio documentario', id ? sources[0].title : 'Fonti in dialogo', 'Una fonte non è la realtà: è un atto prodotto da qualcuno, per qualcuno e con uno scopo.')}<div class="sources-grid">${sources.map(s => `<article class="source-card"><p class="overline">${s.type} · ${s.date}</p><h2>${s.title}</h2><p><strong>${s.author}</strong> · ${s.provenance}</p>${s.image ? `<button class="map-open source-image" data-image="${s.image}" data-title="${esc(s.title)}"><img src="${s.image}" alt="${esc(s.imageAlt || s.title)}" loading="lazy"></button>` : ''}<p class="source-mode">${s.verbatim ? 'Estratti testuali brevi' : 'Sintesi e passi modernizzati: consultare l’originale collegato'}</p><blockquote>${s.excerpt.map(q => `<p>${q}</p>`).join('')}</blockquote><dl><dt>Contesto</dt><dd>${s.context}</dd><dt>Destinatario</dt><dd>${s.audience}</dd><dt>Scopo</dt><dd>${s.purpose}</dd><dt>Limiti</dt><dd>${s.limits}</dd><dt>Lettura guidata</dt><dd>${s.interpretation}</dd></dl><div class="guided"><strong>Domande guidate</strong><ol>${s.questions.map(q => `<li>${q}</li>`).join('')}</ol></div><a class="text-link" href="${s.url}" target="_blank" rel="noopener">Fonte originale ↗</a>${id ? '' : `<a class="text-link second" href="#fonti/${s.id}">Apri singolarmente →</a>`}</article>`).join('')}</div>${id ? '<p><a class="button button-ghost" href="#fonti">← Tutte le fonti</a></p>' : '<p><a class="button button-gold" href="assets/pdf/approfondimenti/fonti-in-dialogo.pdf" target="_blank">Dossier delle fonti PDF ↗</a></p>'}</div>`;
    bindMapButtons();
  }
  function renderWorkshop() { const saved = parseStored(`${storage}:thesis`, {}); app.innerHTML = `<div class="app-container">${hero('Laboratorio finale', 'Costruire una tesi', D.meta.question)}<section class="workshop"><p>${D.meta.workshopIntro}</p>${D.workshop.map((w,i) => `<fieldset><legend>${i+1}. ${w.title}</legend><p>${w.prompt}</p>${w.options.map(o => `<label><input type="radio" name="w${i}" value="${esc(o)}" ${saved[`w${i}`] === o ? 'checked' : ''}> ${o}</label>`).join('')}</fieldset>`).join('')}<label for="thesisText"><strong>Formula la tua tesi</strong></label><textarea id="thesisText" placeholder="Rispondi alla domanda, indica almeno tre prove e una possibile obiezione…">${esc(saved.text || '')}</textarea><div class="notes-actions"><button class="button button-gold" id="saveThesis">Salva</button><button class="button button-accent" id="exportThesis">Esporta .txt</button></div></section></div>`; $('saveThesis').addEventListener('click', saveThesis); $('exportThesis').addEventListener('click', () => { saveThesis(); downloadText('tesi-storica.txt', storageGet(`${storage}:thesisText`, '')); }); }
  function saveThesis() { const obj = { text: $('thesisText').value }; D.workshop.forEach((_,i) => { obj[`w${i}`] = document.querySelector(`input[name=w${i}]:checked`)?.value || ''; }); const ok = storageSet(`${storage}:thesis`, JSON.stringify(obj)) && storageSet(`${storage}:thesisText`, `${D.meta.question}\n\n${obj.text}`); if (ok) toast('Tesi salvata'); }
  function renderQuiz(reset=false) { if(reset) quizState={index:0,answers:[]}; const q=D.quiz[quizState.index]; app.innerHTML=`<div class="app-container">${hero('Verifica finale','Quiz con recupero',`${D.quiz.length} domande su cause, attori, fonti, spazio e interpretazioni.`)}<div class="quiz-shell">${q ? quizQuestion(q) : quizResult()}</div></div>`; bindQuiz(); }
  function quizQuestion(q){return `<div class="quiz-progress"><span>Domanda ${quizState.index+1} di ${D.quiz.length}</span><div class="progress-track"><i style="width:${(quizState.index+1)/D.quiz.length*100}%"></i></div></div><article class="quiz-card"><h2>${q.q}</h2><div class="quiz-options">${q.options.map((o,i)=>`<button data-answer="${i}"><span>${String.fromCharCode(65+i)}</span>${o}</button>`).join('')}</div><div id="quizFeedback"></div></article>`}
  function bindQuiz(){document.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>{if(document.querySelector('.quiz-options .correct,.quiz-options .wrong'))return;const q=D.quiz[quizState.index],selected=Number(b.dataset.answer);quizState.answers.push({selected,correct:q.answer,q});document.querySelectorAll('[data-answer]').forEach(x=>{const i=Number(x.dataset.answer);if(i===q.answer)x.classList.add('correct');else if(i===selected)x.classList.add('wrong')});$('quizFeedback').innerHTML=`<div class="quiz-feedback"><strong>${selected===q.answer?'Esatto.':'Errore da correggere.'}</strong> ${q.why}${selected!==q.answer?`<br><strong>Recupera:</strong> ${q.recover} <a class="text-link" href="#lezione/${q.lesson}">Vai alla lezione ↗</a>`:''}</div><button class="button button-accent" id="quizNext">${quizState.index===D.quiz.length-1?'Mostra il report':'Prossima domanda'} →</button>`;$('quizNext').addEventListener('click',()=>{quizState.index++;renderQuiz()})}));$('quizRestart')?.addEventListener('click',()=>renderQuiz(true));}
  function quizResult(){const score=quizState.answers.filter(a=>a.selected===a.correct).length,p=Math.round(score/D.quiz.length*100),miss=[...new Set(quizState.answers.filter(a=>a.selected!==a.correct).map(a=>a.q.lesson))],good=[...new Set(quizState.answers.filter(a=>a.selected===a.correct).map(a=>a.q.lesson))].filter(x=>!miss.includes(x));return `<article class="quiz-card result"><p class="overline">Risultato</p><strong class="score">${p}%</strong><h2>${score} risposte corrette su ${D.quiz.length}</h2><p>${p>=80?'Conoscenze e nessi sono solidi.':p>=60?'La struttura è compresa, ma alcuni nessi vanno consolidati.':'Il report è una mappa di recupero, non un verdetto.'}</p>${good.length?`<h3>Concetti consolidati</h3><div class="chip-list">${good.map(id=>`<span>${lessonById(id).title}</span>`).join('')}</div>`:''}${miss.length?`<h3>Concetti da rivedere</h3><div class="chip-list">${miss.map(id=>`<a href="#lezione/${id}">${lessonById(id).title}</a>`).join('')}</div>`:''}<div class="result-list">${quizState.answers.map((a,i)=>`<p class="${a.selected===a.correct?'good':'bad'}"><strong>${i+1}. ${a.q.q}</strong><br>${a.selected===a.correct?'Corretta.':`Hai scelto: ${a.q.options[a.selected]}.`} ${a.q.why}</p>`).join('')}</div><button class="button button-accent" id="quizRestart">Ricomincia</button></article>`}
  function bindMapButtons(){document.querySelectorAll('.map-open').forEach(b=>b.addEventListener('click',()=>openImage(b.dataset.title,b.dataset.image)))}
  function openImage(title,src){$('modalTitle').textContent=title;$('modalBody').innerHTML=`<img src="${src}" alt="${esc(title)}">`;$('modal').hidden=false;$('modalClose').focus()}
  function openNotes(){if(!currentLesson)return;$('notesBox').value=storageGet(`${storage}:notes:${currentLesson.id}`,'');$('notesDrawer').hidden=false;$('notesBox').focus()}
  function saveNotes(){if(!currentLesson)return;if(storageSet(`${storage}:notes:${currentLesson.id}`,$('notesBox').value))toast('Appunti salvati')}
  function downloadText(name,text){const blob=new Blob([text],{type:'text/plain;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
  function exportNotes(){if(!currentLesson)return;downloadText(`appunti-${currentLesson.id}.txt`,`${D.meta.title}\n${currentLesson.title}\n\n${$('notesBox').value}`)}
  function search(query){const n=norm(query.trim());if(n.length<2){$('searchResults').innerHTML='';return}const rs=[];D.lessons.forEach(l=>{const h=norm([l.title,l.lead,...l.sections.flatMap(s=>[s.title,...s.paragraphs]),...Object.keys(l.vocab)].join(' '));if(h.includes(n))rs.push({t:l.title,k:'Lezione',u:`#lezione/${l.id}`,x:l.eyebrow})});D.people.forEach(p=>{if(norm(`${p.name} ${p.role} ${p.bio}`).includes(n))rs.push({t:p.name,k:'Biografia',u:`#biografia/${p.id}`,x:p.role})});D.sources.forEach(s=>{if(norm(`${s.title} ${s.author} ${s.excerpt.join(' ')}`).includes(n))rs.push({t:s.title,k:'Fonte',u:`#fonti/${s.id}`,x:s.date})});$('searchResults').innerHTML=rs.length?rs.slice(0,12).map(r=>`<a class="search-result" href="${r.u}"><p class="overline">${r.k}</p><h3>${r.t}</h3><p>${r.x}</p></a>`).join(''):'<p>Nessun risultato.</p>'}
  function render(){scrollTo(0,0);const [route,id]=location.hash.replace('#','').split('/');$('mainNav').classList.remove('open');$('menuToggle').setAttribute('aria-expanded','false');if(route==='lezione')renderLesson(id);else if(route==='fonti')renderSources(id);else if(route==='mappe')renderMaps();else if(route==='biografie')renderPeople();else if(route==='biografia')renderPeople(id);else if(route==='timeline')renderTimeline();else if(route==='laboratorio')renderWorkshop();else if(route==='quiz')renderQuiz(true);else renderLessons();app.focus({preventScroll:true})}
  $('menuToggle').addEventListener('click',e=>{const o=$('mainNav').classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(o))});$('searchToggle').addEventListener('click',()=>{$('searchDrawer').hidden=false;$('globalSearch').focus()});$('closeSearch').addEventListener('click',()=>{$('searchDrawer').hidden=true});$('globalSearch').addEventListener('input',e=>search(e.target.value));$('searchResults').addEventListener('click',()=>{$('searchDrawer').hidden=true});$('closeNotes').addEventListener('click',()=>{$('notesDrawer').hidden=true});$('saveNotes').addEventListener('click',saveNotes);$('exportNotes').addEventListener('click',exportNotes);$('modalClose').addEventListener('click',()=>{$('modal').hidden=true});$('modal').addEventListener('click',e=>{if(e.target===$('modal'))$('modal').hidden=true});document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('modal').hidden=true;$('notesDrawer').hidden=true;$('searchDrawer').hidden=true}});addEventListener('hashchange',render);addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('installButton').hidden=false});$('installButton').addEventListener('click',async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('installButton').hidden=true});if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('service-worker.js');render();
})();
