window.HIST_DATA = {
  meta: {
    title: "La Destra storica. Costruire lo Stato italiano",
    shortTitle: "Destra storica",
    storageKey: "storia-destra-storica-v1",
    question: "Come si costruisce realmente uno Stato dopo averne proclamato l'esistenza, chi sostiene i costi di questa costruzione e quali fratture produce il modello scelto dalla Destra storica?",
    thesis: "Fra il 1861 e il 1876 la Destra storica rese governabile il nuovo Regno: uniformò istituzioni e codici, allargò infrastrutture e mercato, consolidò il credito pubblico e completò quasi interamente l'unità territoriale. Lo fece però con un suffragio strettissimo, un'amministrazione accentrata, un prelievo fiscale socialmente diseguale e un uso esteso della forza. Il risultato fu uno Stato più solido, ma non ancora una comunità politica capace di includere la maggioranza degli italiani.",
    workshopIntro: "Valuta insieme capacità e costi della classe dirigente. Una buona tesi deve distinguere ciò che nel 1861 appariva necessario, le alternative allora discusse, chi poteva decidere, chi pagava e quali problemi rimasero aperti.",
    previous: { title: "Unità d'Italia", url: "../Unita/" },
    next: { title: "Sinistra storica - tappa futura", url: "#" }
  },
  lessons: [
    {
      id: "stato-sulla-carta", number: 1, title: "Uno Stato che esiste solo sulla carta", eyebrow: "Istituzioni comuni, società escluse", period: "1861-1864",
      question: "Che cosa significava davvero fare lo Stato quando il Regno d'Italia era già stato proclamato?",
      lead: "Il 17 marzo 1861 nacque giuridicamente il Regno d'Italia, ma leggi, uffici, debiti, monete e pratiche amministrative restavano diversi. La Destra storica dovette trasformare un atto politico in un potere quotidiano, senza poter contare su una partecipazione di massa.",
      sections: [
        { title: "Il mondo precedente: sette Stati, molte appartenenze", paragraphs: ["L'unificazione aveva riunito territori governati fino a poco prima da ordinamenti differenti. Non esisteva un unico catasto, un sistema fiscale omogeneo o una burocrazia nazionale già pronta. Le distanze non erano soltanto geografiche: il rapporto con la legge, con la Chiesa, con l'esercito e con le autorità locali variava da regione a regione.", "Il Regno ereditò lo Statuto Albertino, il re Vittorio Emanuele II e la numerazione dinastica sabauda. Fu una continuità utile a evitare un vuoto istituzionale, ma rese visibile che il nuovo Stato nasceva per ampliamento del Regno di Sardegna, non da un'assemblea costituente nazionale."], summary: "L'Italia unita possedeva una sovranità riconosciuta, ma non ancora istituzioni uniformi né una cittadinanza politicamente larga." },
        { title: "Le fratture: la morte di Cavour e l'emergenza permanente", paragraphs: ["Cavour morì il 6 giugno 1861, meno di tre mesi dopo la proclamazione. I suoi successori ereditarono confini incompleti, finanze fragili, opposizioni democratiche, conflitti nel Mezzogiorno e la questione di Roma. L'emergenza rese più facile presentare l'accentramento come necessità.", "Nessun esito era inevitabile. Minghetti e Farini avevano immaginato forme regionali e un decentramento amministrativo; altri temevano che autonomie estese favorissero il ritorno delle dinastie deposte o la disgregazione."], summary: "La fragilità dello Stato orientò le scelte, ma non cancellò le alternative discusse dai contemporanei." },
        { title: "Attori, gruppi e conflitti: chi era la Destra storica", paragraphs: ["La Destra storica non era un partito moderno. Era una costellazione parlamentare di liberali moderati, monarchici costituzionali, proprietari e professionisti, divisa in gruppi regionali e legami personali. Ricasoli, Minghetti, La Marmora, Lanza, Sella e Spaventa condividevano l'ordine costituzionale e l'affidabilità finanziaria, ma non sempre strategie e interessi.", "Gli elettori erano una minoranza maschile definita da censo, età, alfabetizzazione e cittadinanza. Nel 1861 gli aventi diritto erano circa 419.000, meno del due per cento della popolazione; partecipò poco più della metà. Il Parlamento era rappresentativo in senso liberale ottocentesco, non democratico in senso contemporaneo."], summary: "Il paese legale era reale, ma socialmente ristretto e lontano dalla maggioranza del paese reale." },
        { title: "Il processo storico: monarchia costituzionale e governo parlamentare", paragraphs: ["Lo Statuto attribuiva al re il potere esecutivo, la nomina dei ministri, il comando delle forze armate e una parte decisiva della politica estera. Nella pratica, però, i governi dovevano conservare il sostegno della Camera elettiva per approvare bilanci e leggi. La forma di governo si parlamentarizzò senza che il testo costituzionale fosse modificato.", "Il Senato era nominato a vita dal re; la Camera era eletta a suffragio ristretto. Le maggioranze non dipendevano da partiti organizzati, ma da accordi tra notabili e gruppi regionali. Questo favoriva flessibilità, ma anche instabilità e negoziazioni poco trasparenti."], summary: "Il sistema combinava prerogative monarchiche, fiducia parlamentare di fatto e una base elettorale minima." },
        { title: "Conseguenze e nuovo assetto: governare prima di integrare", paragraphs: ["La scelta prioritaria fu rendere riconoscibile l'autorità dello Stato: una catena amministrativa, un esercito, un bilancio e leggi comuni. L'inclusione politica della popolazione rimase secondaria. Le élite ritenevano spesso che l'alfabetizzazione e l'educazione civile dovessero precedere l'allargamento del voto.", "Questa logica produsse uno Stato capace di decidere, ma alimentò estraneità. Per molti italiani il primo contatto con il Regno avvenne attraverso il fisco, la leva, un funzionario o un carabiniere, non attraverso il voto."], summary: "La capacità statale crebbe più rapidamente della partecipazione politica." },
        { title: "Conclusione: uno Stato già legittimo, non ancora condiviso", paragraphs: ["La Destra non partì da zero: utilizzò istituzioni sabaude, personale degli antichi Stati e reti locali. Ma scelse di privilegiare continuità, uniformità e controllo. La proclamazione del Regno fu dunque l'inizio di una costruzione conflittuale, non la fine del Risorgimento."], summary: "Fare l'Italia aveva creato un soggetto internazionale; governare gli italiani richiedeva decisioni su poteri, diritti e obblighi." }
      ],
      source: { id: "statuto", title: "Statuto Albertino: Corona, Parlamento e diritti", prompt: "Individua quali poteri appartengono al re e quali limiti emergono dalla necessità di approvare leggi e bilanci." },
      activity: { title: "Chi poteva decidere?", prompt: "Costruisci una mappa dei poteri fra re, ministri, Camera, Senato, prefetti ed elettori. Poi indica due gruppi sociali sottoposti alle leggi ma esclusi dal voto." },
      coordinates: ["17 marzo 1861: proclamazione del Regno", "6 giugno 1861: morte di Cavour", "Torino capitale fino al 1865", "Circa 419.000 aventi diritto nel 1861", "Statuto Albertino esteso al Regno"],
      essentials: ["La Destra storica era un raggruppamento parlamentare, non un partito di massa.", "Il Regno ereditò lo Statuto e la dinastia sabauda.", "L'unificazione politica non coincideva con quella amministrativa.", "Il suffragio era maschile, censitario e molto ristretto.", "La forma di governo si parlamentarizzò nella prassi.", "Accentramento e decentramento erano alternative realmente discusse.", "Paese legale e paese reale indicano una distanza politica, non due Italie separate."],
      vocab: { Destra_storica: "Raggruppamento liberale moderato che governò prevalentemente dal 1861 al 1876.", Suffragio_censitario: "Diritto di voto subordinato, fra l'altro, al pagamento di un'imposta minima.", Statuto_Albertino: "Carta costituzionale concessa nel 1848 e divenuta legge fondamentale del Regno d'Italia.", Paese_legale: "Insieme ristretto di istituzioni, elettori e notabili ammessi alla vita politica.", Notabile: "Persona influente localmente per ricchezza, professione, relazioni e prestigio." },
      answer: "Nel 1861 fare lo Stato significava trasformare territori appena uniti in un sistema capace di imporre leggi, raccogliere entrate e rappresentare l'Italia. La Destra privilegiò continuità istituzionale e capacità di governo; ottenne stabilità, ma rinviò l'inclusione politica della maggioranza.",
      connections: { map: "Italia amministrativa dopo l'unificazione", people: ["ricasoli", "minghetti", "vittorio"] }
    },
    {
      id: "accentramento", number: 2, title: "Unificare o decentrare?", eyebrow: "La macchina amministrativa", period: "1859-1865",
      question: "Perché prevalse uno Stato accentrato e quali alternative furono abbandonate?",
      lead: "L'uniformità non fu la semplice conseguenza dell'Unità: fu una scelta politica. La legge comunale e provinciale del 1865 estese una gerarchia che collegava ministeri, prefetti, province e comuni.",
      sections: [
        { title: "Il mondo precedente: amministrazioni incompatibili", paragraphs: ["Gli Stati preunitari possedevano codici, circoscrizioni, corpi burocratici e rapporti centro-periferia differenti. Uniformare significava rendere prevedibili atti pubblici e competenze; significava anche sostituire pratiche locali e carriere consolidate.", "La legge Rattazzi del 23 ottobre 1859 aveva organizzato comuni e province nel Regno di Sardegna durante la guerra. Fu estesa ai territori annessi e divenne il nucleo del successivo ordinamento nazionale."], summary: "L'unificazione amministrativa rispondeva a un problema reale, ma poteva essere realizzata in modi diversi." },
        { title: "Le fratture: i progetti regionali vengono accantonati", paragraphs: ["Fra 1860 e 1861 Farini e Minghetti proposero grandi regioni dotate di competenze amministrative. La guerra nel Mezzogiorno, le resistenze locali e la paura di centrifughe politiche indebolirono il progetto. Il Parlamento non lo trasformò in legge.", "Il termine piemontesizzazione descrive l'estensione di norme e modelli sabaudi, ma può ingannare se suggerisce una copia meccanica e totale. Funzionari e pratiche degli antichi Stati sopravvissero; il centro dovette negoziare con élite locali."], summary: "L'accentramento prevalse per scelta e per timore; non cancellò ogni continuità locale." },
        { title: "Attori e conflitti: prefetti, sindaci e consigli", paragraphs: ["Il prefetto rappresentava il governo nella provincia, curava l'ordine pubblico e vigilava sugli enti locali. I consigli comunali erano eletti da una minoranza; il sindaco era nominato dal re fra i consiglieri. Il comune esisteva come ente rappresentativo, ma era sottoposto a controlli penetranti.", "Silvio Spaventa interpretò l'amministrazione come strumento di legalità nazionale. Le opposizioni federaliste e autonomiste temevano invece che il centro ignorasse bisogni e competenze territoriali."], summary: "Gli enti locali non furono aboliti, ma inseriti in una gerarchia governativa." },
        { title: "Il processo storico: la grande legge del 1865", paragraphs: ["La legge 20 marzo 1865, n. 2248, composta da più allegati, riordinò comuni e province, sicurezza pubblica, sanità, Consiglio di Stato, contenzioso amministrativo e lavori pubblici. Nello stesso anno entrarono in vigore il Codice civile e altri codici unitari.", "Uniformare consentiva a cittadini e imprese di operare entro regole comuni. Tuttavia la qualità degli uffici, le risorse dei comuni e l'accesso alla giustizia restavano diseguali. Uguale norma non significava uguale capacità di applicarla."], summary: "Il 1865 rese comune l'architettura giuridica; non rese omogenei territori e servizi." },
        { title: "Conseguenze e nuovo assetto: una catena verticale", paragraphs: ["Il governo poté trasmettere ordini e informazioni lungo una struttura relativamente uniforme. Prefetti e sottoprefetti divennero nodi essenziali, soprattutto durante elezioni, proteste ed emergenze.", "Il prezzo fu una debole autonomia politica locale. La responsabilità saliva verso il ministero più che scendere verso una cittadinanza larga; questo alimentò pratiche clientelari e dipendenza dal centro, pur senza annullare il potere dei notabili locali."], summary: "L'accentramento aumentò coordinamento e controllo, ma ridusse gli spazi di autogoverno." },
        { title: "Gli storici discutono: piemontesizzazione, necessità o errore?", paragraphs: ["Non esiste una risposta unica. In uno Stato fragile, l'uniformità offriva rapidità e prevedibilità; poteva però confondere unità con identità amministrativa. Il giudizio storico deve confrontare il rischio percepito di disgregazione con i costi duraturi della centralizzazione."], summary: "La piemontesizzazione fu insieme una soluzione praticabile e una scelta che lasciò irrisolta la gestione delle differenze." }
      ],
      source: { id: "unificazione-amministrativa", title: "Legge 20 marzo 1865, n. 2248", prompt: "Leggi la catena delle competenze e chiediti a chi risponde ciascun livello amministrativo." },
      activity: { type: "decision", title: "Centralizzare senza cancellare", prompt: "Sei un parlamentare nel 1861. Scegli fra modello accentrato, regionale o federale; assegna competenze a Stato e territori e indica un rischio concreto della tua proposta." },
      coordinates: ["23 ottobre 1859: legge Rattazzi", "1860-1861: progetti Farini-Minghetti", "20 marzo 1865: legge n. 2248", "1 gennaio 1866: Codice civile pienamente operativo", "Prefetto, provincia, comune"],
      essentials: ["La legge Rattazzi precede l'Unità.", "Minghetti propose un ordinamento regionale.", "La guerra civile meridionale rafforzò la scelta accentratrice.", "La legge 2248/1865 comprendeva sei allegati.", "Il prefetto rappresentava il governo nella provincia.", "Il sindaco non era eletto direttamente dalla popolazione.", "Uniformità normativa e omogeneità sociale non coincidono."],
      vocab: { Accentramento: "Sistema nel quale le decisioni principali dipendono dal governo centrale e dai suoi funzionari.", Prefetto: "Rappresentante del governo nella provincia, con funzioni di vigilanza e ordine pubblico.", Piemontesizzazione: "Formula storiografica per l'estensione di istituzioni sabaude; non implica cancellazione totale delle continuità locali.", Decentramento: "Attribuzione di funzioni a enti territoriali entro uno Stato unitario.", Codificazione: "Raccolta organica e uniforme di norme in un codice." },
      answer: "Prevalse l'accentramento perché offriva una macchina pronta e sembrava ridurre il rischio di disgregazione. Non fu però l'unica via: i progetti regionali mostrarono che si poteva pensare l'unità senza uniformità completa. Il modello scelto coordinò lo Stato, ma indebolì l'autogoverno locale.",
      connections: { map: "Italia amministrativa dopo l'unificazione", people: ["minghetti", "spaventa", "rattazzi"] }
    },
    {
      id: "cittadini", number: 3, title: "Costruire cittadini italiani", eyebrow: "Scuola, esercito, moneta e reti", period: "1861-1876",
      question: "Si può costruire una nazione attraverso scuola, leva, infrastrutture e istituzioni comuni?",
      lead: "Lo Stato poteva uniformare leggi in pochi anni; lingua, alfabetizzazione, fiducia e appartenenze richiedevano generazioni. La Destra tentò di costruire cittadini attraverso istituzioni che offrivano opportunità ma imponevano anche obblighi.",
      sections: [
        { title: "Il mondo precedente: un paese plurale e poco alfabetizzato", paragraphs: ["Il censimento del 1861 registrò circa diciassette milioni di analfabeti su quasi ventidue milioni di abitanti, includendo tutte le età. Le differenze territoriali e di genere erano enormi. I dialetti costituivano la lingua quotidiana della maggioranza; l'italiano era padroneggiato da una minoranza.", "Nel primo censimento soltanto il 15,7 per cento dei giovani fra 5 e 19 anni risultava iscritto a scuola. Parlare di arretratezza nazionale è corretto; ridurre il quadro a Nord alfabetizzato e Sud interamente immobile non lo è."], summary: "La nazione doveva essere costruita dentro una società agricola, plurilingue e scarsamente scolarizzata." },
        { title: "Le fratture: la legge Casati diventa nazionale", paragraphs: ["La legge Casati del 1859 organizzava il sistema piemontese-lombardo e fu estesa al Regno. Stabiliva due gradi elementari; il primo biennio era gratuito e obbligatorio, ma edifici, maestri e spese gravavano soprattutto sui comuni.", "L'obbligo senza risorse e controlli efficaci rimase spesso sulla carta. Povertà familiare, lavoro infantile, distanze e resistenze culturali limitarono la frequenza. La legge Coppino del 1877, già sotto la Sinistra, avrebbe rafforzato obbligo e laicità."], summary: "La scuola nazionale nacque prima che lo Stato fosse in grado di garantirla in modo uguale." },
        { title: "Attori e conflitti: maestri, famiglie, coscritti", paragraphs: ["I maestri furono mediatori dello Stato ma ricevevano stipendi bassi e irregolari. Le famiglie dovevano scegliere fra scuola e lavoro dei figli. L'alfabetizzazione fu dunque una politica pubblica e una negoziazione quotidiana.", "La leva obbligatoria riunì uomini di regioni diverse e insegnò disciplina, lingua di comando e appartenenza statale. Ma sottraeva braccia alle famiglie contadine, durava anni e provocò renitenza e diserzione. Fu strumento di nazionalizzazione e fonte di conflitto."], summary: "Scuola ed esercito formarono cittadini in modi diversi: una prometteva competenze, l'altro imponeva servizio." },
        { title: "Il processo storico: collegare e misurare", paragraphs: ["La lira italiana fu istituita nel 1862 secondo un sistema bimetallico; pesi e misure furono uniformati con il sistema metrico. La Banca d'Italia ricorda che nei territori unificati circolavano 236 tipi di monete metalliche: sostituirle richiese tempo, coniazione e fiducia.", "La rete ferroviaria passò da poco più di duemila chilometri nel 1861 a oltre seimila nel 1870, ma le linee iniziali erano frammentate e finanziate anche da capitali esteri. Poste e telegrafi ridussero tempi amministrativi. Le infrastrutture integrarono mercati e apparati più rapidamente di quanto integrassero le esperienze sociali."], summary: "Moneta, misure e trasporti resero l'Italia più comunicante, senza distribuire benefici in modo uniforme." },
        { title: "Conseguenze e nuovo assetto: Stato e nazione non coincidono", paragraphs: ["Uno Stato è un insieme di istituzioni sovrane; una nazione è anche memoria, linguaggio, simboli e riconoscimento reciproco. La Destra costruì soprattutto il primo, sperando che il secondo seguisse.", "La scuola creò possibilità di mobilità e una lingua pubblica; la leva e il fisco resero concreto l'obbligo nazionale. Per alcuni furono accesso alla cittadinanza, per altri l'esperienza di un potere distante."], summary: "La nazionalizzazione fu un processo diseguale, non un effetto automatico dell'Unità." },
        { title: "Conclusione: cittadini o amministrati?", paragraphs: ["Le istituzioni comuni produssero abitudini e spazi nazionali, ma senza suffragio largo e servizi omogenei molti italiani rimasero soprattutto amministrati. La domanda non è se scuola ed esercito crearono la nazione, ma come e per chi lo fecero."], summary: "Lo Stato costruì cittadini offrendo regole e strumenti, ma li costruì anche imponendo obblighi prima di ampliare la partecipazione." }
      ],
      source: { id: "casati", title: "Legge Casati: obbligo, gratuità e responsabilità comunale", prompt: "Distingui il diritto dichiarato dai mezzi concreti necessari per realizzarlo." },
      activity: { title: "Due vite nel 1865", prompt: "Scrivi due brevi prospettive documentate: un maestro comunale e una famiglia contadina chiamata a mandare un figlio a scuola e un altro alla leva. Quali vantaggi e costi vedono?" },
      coordinates: ["13 novembre 1859: legge Casati", "24 agosto 1862: lira italiana", "Censimento 1861", "Leva nazionale consolidata nel 1862-1863", "Oltre 6.000 km di ferrovie entro il 1870"],
      essentials: ["Nel 1861 circa tre italiani su quattro erano analfabeti.", "L'iscrizione scolastica 5-19 anni era molto bassa.", "La legge Casati affidava molte spese ai comuni.", "La leva fu strumento di integrazione e causa di resistenza.", "La lira non eliminò immediatamente tutte le monete precedenti.", "Il sistema metrico rese confrontabili scambi e atti.", "Stato e nazione sono processi collegati ma distinti."],
      vocab: { Alfabetizzazione: "Diffusione delle capacità di leggere e scrivere, misurata con criteri variabili nel tempo.", Nazionalizzazione: "Processo con cui istituzioni e pratiche costruiscono appartenenza a una comunità nazionale.", Coscrizione: "Reclutamento obbligatorio per il servizio militare.", Sistema_metrico: "Sistema comune di misure fondato su metro, litro e grammo.", Bimetallismo: "Sistema monetario basato su un rapporto legale fra oro e argento." },
      answer: "Scuola, esercito, moneta e ferrovie resero possibile una vita nazionale, ma non crearono immediatamente un'identità condivisa. La loro efficacia dipese da risorse locali e condizioni sociali; gli stessi strumenti che integravano potevano essere percepiti come imposizioni.",
      connections: { map: "Indicatori territoriali: leggere senza stereotipi", people: ["lanza", "sella", "vittorio"] }
    },
    {
      id: "bilancio", number: 4, title: "Chi paga lo Stato?", eyebrow: "Debito, imposte e pareggio", period: "1861-1876",
      question: "Era possibile costruire l'Italia senza un forte prelievo fiscale e chi sopportò la parte più pesante del risanamento?",
      lead: "Il nuovo Regno assunse i debiti degli Stati preunitari e finanziò esercito, amministrazione, guerre e infrastrutture. Per la Destra il credito pubblico era indipendenza politica; per i contribuenti il risanamento significava imposte visibili su terra e consumi.",
      sections: [
        { title: "Il mondo precedente: debiti diversi, un'unica responsabilità", paragraphs: ["L'unificazione sommò debiti, rendite e sistemi fiscali differenti. Il debito piemontese era elevato per guerre e modernizzazione; altri Stati avevano esposizioni minori ma strutture fiscali diverse. Il Regno scelse di riconoscere gli impegni pregressi per tutelare continuità giuridica e credibilità.", "Il servizio del debito assorbiva una quota rilevante delle entrate. A ciò si aggiungevano esercito, burocrazia, ferrovie e completamento territoriale. Ridurre drasticamente la spesa avrebbe indebolito lo Stato proprio mentre cercava di consolidarsi."], summary: "Il bilancio unitario ereditò obblighi e ambizioni che non potevano essere finanziati senza nuove entrate." },
        { title: "Le fratture: guerra del 1866 e corso forzoso", paragraphs: ["La crisi finanziaria e la guerra contro l'Austria portarono nel maggio 1866 al corso forzoso: i biglietti della Banca Nazionale non furono più convertibili in moneta metallica e dovettero essere accettati. La misura fornì liquidità, ma alterò cambi e fiducia.", "Lo Stato mantenne un pluralismo di banche di emissione. Il corso forzoso non fu soltanto una scorciatoia: fu una risposta emergenziale che mostrava quanto finanza, guerra e sovranità fossero intrecciate."], summary: "La moneta divenne uno strumento diretto della crisi statale, con effetti distribuiti sull'intera economia." },
        { title: "Attori e conflitti: Sella e i contribuenti", paragraphs: ["Quintino Sella divenne il simbolo del rigore, ma la politica finanziaria attraversò più governi e ministri. Il pareggio serviva a ridurre il rischio di insolvenza e dipendenza dai creditori; era anche un criterio morale della classe dirigente.", "Imposte dirette e indirette non colpivano allo stesso modo. Le tasse sui consumi pesavano proporzionalmente di più sui redditi bassi. Proprietari, commercianti, comuni e contadini reagirono secondo interessi differenti; non esisteva un unico contribuente nazionale."], summary: "Il conflitto non opponeva semplicemente Stato e popolo: riguardava la distribuzione del carico fiscale." },
        { title: "Il processo storico: macinato e asse ecclesiastico", paragraphs: ["La tassa sul macinato, approvata il 7 luglio 1868 ed entrata in vigore il 1 gennaio 1869, colpiva la macinazione dei cereali mediante contatori applicati ai mulini. Divenne odiosa perché incideva su pane e polenta ed era percepita materialmente ogni giorno.", "La soppressione di molti enti religiosi nel 1866 e la liquidazione dell'asse ecclesiastico nel 1867 trasferirono e misero in vendita patrimoni. Le entrate aiutarono il bilancio, ma le aste favorirono spesso acquirenti dotati di capitale e non produssero una riforma agraria."], summary: "Il risanamento combinò imposte, vendite patrimoniali, credito e controllo della spesa." },
        { title: "Conseguenze e nuovo assetto: un pareggio politico", paragraphs: ["Il consuntivo del 1875 segnò il raggiungimento del pareggio, celebrato politicamente nel 1876. Il risultato rafforzò l'affidabilità dello Stato, ma non cancellò il debito né il malcontento. Il pareggio è un saldo contabile, non la misura completa del benessere sociale.", "Le proteste del gennaio 1869 furono particolarmente intense nell'Italia centro-settentrionale; l'intervento militare provocò vittime e arresti. Questo dato corregge l'idea che ogni resistenza fiscale della fase postunitaria fosse esclusivamente meridionale."], summary: "La stabilità finanziaria fu reale; furono reali anche i costi sociali e politici con cui venne ottenuta." },
        { title: "Conclusione: il bilancio come scelta di società", paragraphs: ["Nessun bilancio era davvero impossibile, ma ogni alternativa spostava costi: più debito sui contribuenti futuri, meno esercito sulla sicurezza, meno scuole sull'alfabetizzazione, più imposte sui consumi popolari. La Destra scelse credibilità e continuità statale, distribuendo però il sacrificio in modo regressivo."], summary: "Il problema storico non è se servissero entrate, ma quali entrate, quali priorità e quale rappresentanza dei contribuenti." }
      ],
      source: { id: "macinato", title: "Legge 7 luglio 1868 sulla tassa del macinato", prompt: "Osserva come un meccanismo tecnico di riscossione trasforma una scelta fiscale in esperienza quotidiana." },
      activity: { type: "budget", title: "Bilancio impossibile", prompt: "Distribuisci 100 punti di spesa e scegli il prelievo. Il simulatore non ricostruisce cifre di bilancio reali: rende visibili i conflitti fra priorità, consenso e credito." },
      coordinates: ["1861: unificazione del debito", "1 maggio 1866: corso forzoso", "7 luglio 1868: tassa sul macinato", "1 gennaio 1869: entrata in vigore", "1875-1876: pareggio e celebrazione politica"],
      essentials: ["Il Regno riconobbe i debiti degli Stati preunitari.", "Il debito piemontese era elevato anche per guerra e infrastrutture.", "Il corso forzoso sospese la convertibilità dei biglietti.", "Il macinato era un'imposta sulla trasformazione dei cereali.", "Le imposte indirette gravavano proporzionalmente di più sui poveri.", "La vendita dell'asse ecclesiastico non fu una riforma agraria.", "Il pareggio del 1875-1876 non equivaleva all'estinzione del debito."],
      vocab: { Debito_pubblico: "Insieme dei prestiti contratti dallo Stato e degli interessi dovuti.", Corso_forzoso: "Obbligo di accettare banconote non convertibili in metallo.", Imposta_indiretta: "Tributo applicato a consumi o scambi, senza misurare direttamente il reddito.", Macinato: "Imposta calcolata sulla macinazione dei cereali.", Pareggio: "Equilibrio contabile fra entrate e spese di un esercizio." },
      answer: "Costruire il Regno senza nuove entrate era irrealistico, ma la distribuzione del sacrificio non era predeterminata. La Destra difese credito e continuità dello Stato; ricorse però a imposte sui consumi e misure repressive che fecero pagare un costo proporzionalmente maggiore ai ceti popolari.",
      connections: { map: "Indicatori territoriali: leggere senza stereotipi", people: ["sella", "minghetti", "lanza"] }
    },
    {
      id: "brigantaggio", number: 5, title: "Una guerra dentro il nuovo Stato", eyebrow: "Brigantaggio, violenze e interpretazioni", period: "1861-1865",
      question: "Che cosa fu il brigantaggio postunitario e perché nessuna etichetta unica riesce a spiegarlo?",
      lead: "Nel Mezzogiorno continentale bande armate, esercito, guardie nazionali, comunità e reti legittimiste combatterono una guerra irregolare. Criminalità, controrivoluzione borbonica, protesta sociale e conflitti locali si sovrapposero senza fondersi in un solo progetto.",
      sections: [
        { title: "Il mondo precedente: terra, violenza e debolezza pubblica", paragraphs: ["Il brigantaggio aveva una storia precedente al 1861. In vaste aree rurali lo Stato borbonico faticava a controllare territorio, faide, clientele e mercati illegali. La proprietà della terra e l'uso dei demani alimentavano conflitti fra contadini, comuni e possidenti.", "La caduta del Regno delle Due Sicilie sciolse esercito e fedeltà politiche senza creare immediatamente un nuovo ordine riconosciuto. Ex soldati, renitenti, contadini, criminali e agenti borbonici trovarono nelle bande risorse e protezione."], summary: "Il nuovo Stato incontrò fratture antiche, aggravate dalla rivoluzione politica del 1860-1861." },
        { title: "Le fratture: leva, fiscalità e controrivoluzione", paragraphs: ["La leva obbligatoria e il ritorno dell'imposta fondiaria furono percepiti come rotture. Le attese di terra non soddisfatte e le vendite demaniali accrebbero delusioni. Il legittimismo borbonico fornì simboli, denaro e collegamenti, soprattutto nella prima fase.", "Non tutte le bande avevano la stessa composizione o durata. Alcune cercavano di restaurare Francesco II; altre vivevano di sequestro, rapina e protezione; molte combinavano politica, sopravvivenza e vendetta. Le donne operarono come combattenti, informatrici e figure di collegamento, spesso descritte dalle fonti con stereotipi."], summary: "Cause sociali, politiche e criminali variarono nello spazio e nel tempo." },
        { title: "Attori e conflitti: bande, paesi, esercito", paragraphs: ["Carmine Crocco guidò formazioni mobili in Basilicata e aree vicine, alleandosi temporaneamente con il legittimista catalano José Borjes. La rottura fra i due mostra che restaurazione dinastica e autonomia delle bande non coincidevano.", "Lo Stato impiegò decine di migliaia di soldati, carabinieri e guardie nazionali. Le bande uccisero civili, funzionari e militari; la repressione ricorse a fucilazioni, incendi, arresti e punizioni collettive. Le fonti statali contano e classificano, ma tendono a leggere ogni conflitto come ordine pubblico."], summary: "La violenza fu asimmetrica per risorse, ma non appartenne a un solo campo." },
        { title: "Il processo storico: inchiesta e legge Pica", paragraphs: ["La Commissione parlamentare presieduta da Giuseppe Massari raccolse informazioni nel 1862-1863. La relazione riconobbe cause sociali e amministrative, ma operava dentro l'obiettivo di ristabilire l'autorità statale.", "La legge 15 agosto 1863, n. 1409, detta Pica, introdusse nelle province dichiarate infestate tribunali militari e misure eccezionali contro briganti, complici e oziosi. La fase più intensa diminuì entro il 1865; bande e repressione continuarono oltre quella soglia."], summary: "Lo Stato combinò conoscenza parlamentare e legislazione eccezionale, privilegiando la soluzione militare." },
        { title: "Gli storici discutono: guerra civile, rivolta o criminalità?", paragraphs: ["Chiamare il fenomeno guerra civile mette in luce lo scontro per la legittimità e la partecipazione di italiani su fronti opposti; non significa affermare che esistesse un esercito meridionale unitario. Parlare di rivolta sociale evidenzia terra e povertà; non prova l'esistenza di un programma agrario comune.", "La storiografia recente, da Salvatore Lupo a Carmine Pinto, insiste sulla pluralità del conflitto e sulla necessità di tenere insieme controrivoluzione, guerra irregolare e costruzione statale. La categoria criminale descrive pratiche reali, ma da sola non spiega consenso, reti politiche e intensità territoriale."], summary: "Le categorie sono strumenti parziali: diventano false quando pretendono di escludersi a vicenda." },
        { title: "Conclusione: vittoria militare, problema irrisolto", paragraphs: ["Il Regno ristabilì il controllo e sconfisse il progetto borbonico. Non risolse però la questione agraria, la povertà rurale o la distanza fra amministrazione e comunità. La vittoria dello Stato non equivalse a integrazione politica."], summary: "Il brigantaggio fu una guerra irregolare plurale; la repressione consolidò lo Stato e insieme ne rese visibili i limiti." }
      ],
      source: { id: "pica", title: "Legge Pica: l'eccezione dentro lo Stato liberale", prompt: "Confronta garanzie statutarie e poteri eccezionali. Quale definizione di sicurezza emerge?" },
      activity: { title: "Processo alle interpretazioni", prompt: "Costruisci quattro colonne: criminalità, legittimismo, rivolta sociale, guerra civile. Inserisci per ciascuna due prove e un limite; concludi spiegando quale combinazione ritieni più adeguata." },
      coordinates: ["1861-1865: fase più intensa", "1862-1863: inchiesta Massari", "15 agosto 1863: legge Pica", "Basilicata, Capitanata, Irpinia, Terra di Lavoro", "Crocco e Borjes: alleanza e rottura"],
      essentials: ["Il brigantaggio esisteva prima dell'Unità.", "Le bande non avevano comando e programma unici.", "Legittimismo, protesta sociale e criminalità potevano coesistere.", "La leva fu una causa importante ma non unica.", "La relazione Massari è una fonte statale con scopi politici.", "La legge Pica introdusse giurisdizione militare ed eccezione.", "La fase intensa diminuì entro il 1865 senza eliminare tutte le bande.", "Guerra civile è una categoria storiografica, non uno slogan identitario."],
      vocab: { Brigantaggio_postunitario: "Insieme eterogeneo di conflitti armati nel Mezzogiorno dopo il 1860.", Legittimismo: "Fedeltà politica alla dinastia borbonica deposta.", Renitenza: "Sottrazione all'obbligo di leva.", Legislazione_eccezionale: "Norme temporanee che ampliano poteri e riducono garanzie ordinarie.", Guerra_irregolare: "Conflitto condotto da forze non organizzate come eserciti regolari." },
      answer: "Il brigantaggio fu una combinazione variabile di controrivoluzione, conflitto sociale, renitenza, vendette e attività criminali. Lo Stato vinse militarmente attraverso un impiego massiccio di forze e norme eccezionali, ma non trasformò le condizioni che avevano reso possibile la rivolta.",
      connections: { map: "Aree del brigantaggio postunitario", people: ["crocco", "la-marmora", "spaventa"] }
    },
    {
      id: "mezzogiorno", number: 6, title: "Esisteva già una questione meridionale?", eyebrow: "Divari, dati e politiche uniformi", period: "1861-1876",
      question: "L'unificazione creò il divario Nord-Sud oppure rese visibili e trasformò differenze precedenti?",
      lead: "La risposta seria è meno comoda delle narrazioni identitarie. Nel 1861 tutta l'Italia era povera e agricola, ma non nello stesso modo. Esistevano differenze di alfabetizzazione, infrastrutture, istituzioni e produttività; le politiche unitarie ne modificarono alcune e ne aggravarono altre.",
      sections: [
        { title: "Il mondo precedente: molte economie regionali", paragraphs: ["Il Nord non era interamente industriale e il Sud non era un blocco feudale. Agricolture intensive e arretratezze convivevano in entrambe le aree; città, manifatture e commerci formavano sistemi locali. Il Mezzogiorno possedeva poli produttivi e finanziari, ma soffriva in media di minore alfabetizzazione e infrastrutturazione.", "Le stime retrospettive del reddito regionale non coincidono. Per questo il confronto usa indicatori diversi: salari reali, altezza, speranza di vita, alfabetizzazione, ferrovie, struttura occupazionale. Nessun indicatore da solo misura sviluppo e benessere."], summary: "Il divario iniziale era reale in alcuni aspetti e discusso in altri; non autorizza caricature." },
        { title: "Le fratture: un mercato, effetti differenti", paragraphs: ["L'abolizione delle dogane interne e l'estensione della tariffa liberista piemontese ampliarono il mercato. Alcune produzioni agricole d'esportazione beneficiarono degli scambi; manifatture deboli furono esposte a nuova concorrenza. I confini rimossi crearono opportunità soprattutto dove esistevano strade, credito e reti commerciali.", "Fiscalità, leva, vendita dei demani e beni ecclesiastici furono formalmente nazionali, ma pesarono diversamente su territori con strutture sociali differenti. Una politica uniforme può produrre effetti diseguali."], summary: "L'integrazione economica non fu né pura rapina coloniale né beneficio automatico." },
        { title: "Attori e conflitti: proprietari, contadini, comuni", paragraphs: ["La distribuzione della terra condizionava redditi, potere locale e accesso alle risorse comuni. Il latifondo era importante in molte aree meridionali e insulari, ma non esauriva la geografia agraria. Nel Nord esistevano povertà contadina, mezzadria e grandi proprietà.", "Le élite locali meridionali parteciparono al nuovo Stato, occupando Parlamento, comuni e amministrazioni. Ridurre il rapporto a un Nord dominatore e a un Sud passivo cancella alleanze, conflitti interni e responsabilità condivise."], summary: "Le fratture territoriali attraversavano anche classi e istituzioni locali." },
        { title: "Il processo storico: dai dati all'inchiesta sociale", paragraphs: ["Il censimento del 1861 mostrò un analfabetismo nazionale vicino ai tre quarti, con livelli più alti nelle regioni meridionali e insulari. Nel 1861 la rete ferroviaria superava appena duemila chilometri ed era concentrata nel Centro-Nord; l'espansione successiva fu rapida anche nel Sud, senza colmare tutte le differenze di accesso.", "Pasquale Villari pubblicò nel 1875 le prime Lettere meridionali, collegando criminalità, miseria e responsabilità dei ceti dirigenti. Franchetti e Sonnino avviarono nel 1876 l'inchiesta in Sicilia; la grande inchiesta Jacini cominciò nel 1877. Il meridionalismo nacque dunque come critica interna allo Stato liberale, non come dottrina unica."], summary: "La questione meridionale divenne oggetto di indagine quando l'ordine pubblico non bastò più a spiegarla." },
        { title: "Gli storici discutono: quando nasce il divario?", paragraphs: ["Una linea di ricerca sottolinea differenze preunitarie in capitale umano, istituzioni e infrastrutture; un'altra ridimensiona il divario iniziale di reddito e insiste sulla divergenza successiva. Gli studi recenti sui salari reali e sull'accesso ai mercati non hanno chiuso il confronto.", "Il consenso minimo è più preciso degli slogan: nel 1861 non esistevano due economie semplicemente opposte; l'unificazione non inventò ogni differenza, ma cambiò incentivi, spesa, mercati e poteri. La divergenza va spiegata per periodi e indicatori."], summary: "La discussione storiografica riguarda misure e meccanismi, non l'esistenza morale di vincitori e vinti." },
        { title: "Conclusione: rendere visibile non significa risolvere", paragraphs: ["Lo Stato raccolse dati nazionali e costruì infrastrutture, ma affrontò spesso il Mezzogiorno prima come problema di sicurezza. Le differenze regionali divennero una questione nazionale proprio perché esisteva ormai un bilancio, un Parlamento e un'opinione pubblica comuni."], summary: "La questione meridionale nacque dall'incontro fra squilibri precedenti e modalità concrete dell'unificazione." }
      ],
      source: { id: "villari", title: "Pasquale Villari, Lettere meridionali", prompt: "Distingui la denuncia delle condizioni sociali dalle generalizzazioni dell'osservatore liberale." },
      activity: { type: "data", title: "Nord e Sud: leggere i dati", prompt: "Confronta alfabetizzazione, ferrovie e struttura economica. Formula due conclusioni sostenibili e una conclusione che i dati non autorizzano." },
      coordinates: ["31 dicembre 1861: primo censimento", "1861: oltre 2.000 km di ferrovie", "1870: oltre 6.000 km", "1875: Lettere meridionali", "1876-1877: inchiesta Franchetti-Sonnino"],
      essentials: ["Tutta l'Italia del 1861 era prevalentemente agricola.", "Le differenze regionali non coincidevano con una linea semplice Nord-Sud.", "Alfabetizzazione e infrastrutture mostravano forti squilibri.", "Le stime del reddito regionale preunitario sono discusse.", "La tariffa liberista produsse vincitori e perdenti.", "Le élite meridionali parteciparono al nuovo Stato.", "Villari trasformò la miseria in questione politica nazionale.", "Il meridionalismo comprende interpretazioni diverse."],
      vocab: { Questione_meridionale: "Problema storico degli squilibri economici, sociali e istituzionali del Mezzogiorno nell'Italia unita.", Latifondo: "Grande proprietà fondiaria; assume forme e rapporti di lavoro differenti.", Indicatore: "Misura parziale usata per osservare un fenomeno complesso.", Divario_regionale: "Differenza persistente fra aree in uno o più aspetti misurabili.", Meridionalismo: "Insieme plurale di studi e proposte sulla condizione del Mezzogiorno." },
      answer: "L'unificazione non creò dal nulla il divario e non trovò due blocchi omogenei. Integrò economie diverse con regole comuni, producendo effetti asimmetrici. La questione meridionale nacque quando squilibri precedenti, nuove politiche e mancata riforma sociale furono letti come problema dell'intero Stato.",
      connections: { map: "Indicatori territoriali: leggere senza stereotipi", people: ["villari", "spaventa", "crocco"] }
    },
    {
      id: "roma-1876", number: 7, title: "Completare l'Italia, dividere gli italiani?", eyebrow: "Veneto, Roma, Chiesa e caduta", period: "1862-1876",
      question: "Perché il completamento territoriale rafforzò lo Stato e insieme aggravò il conflitto con una parte decisiva della società italiana?",
      lead: "Veneto e Roma completarono il progetto territoriale della Destra, ma furono ottenuti dentro guerre europee e sconfitte italiane. Roma capitale risolse una questione nazionale e ne aprì una religiosa e politica destinata a durare.",
      sections: [
        { title: "Il mondo precedente: confini incompleti e protezione francese", paragraphs: ["Nel 1861 Veneto, Trentino e Roma restavano fuori dal Regno. Lo Stato pontificio era ridotto al Lazio ma protetto da Napoleone III. Garibaldi e i democratici premevano per l'azione; i governi temevano guerra con la Francia e isolamento diplomatico.", "Cavour aveva indicato Roma come capitale e immaginato una 'libera Chiesa in libero Stato'. La formula separava potere temporale e missione religiosa, ma non offriva un accordo accettabile a Pio IX."], summary: "Il completamento dell'Unità dipendeva da equilibri internazionali e dal problema della sovranità pontificia." },
        { title: "Le fratture: Aspromonte, Convenzione e Mentana", paragraphs: ["Nel 1862 l'esercito fermò Garibaldi all'Aspromonte. La Convenzione di settembre del 1864 impegnò l'Italia a rispettare il territorio pontificio e la Francia a ritirare gradualmente le truppe; il trasferimento della capitale a Firenze mostrava una rinuncia almeno temporanea a Roma.", "Nel 1867 una nuova spedizione garibaldina fallì a Mentana contro truppe pontificie e francesi. Il governo italiano oscillò fra simpatia nazionale e obblighi diplomatici. L'iniziativa volontaria non poteva più determinare da sola la politica estera."], summary: "Lo Stato nazionale dovette contenere gli stessi volontari che avevano contribuito alla sua nascita." },
        { title: "Attori e conflitti: esercito, Garibaldi, papa e potenze", paragraphs: ["La Marmora guidò nel 1866 l'alleanza con la Prussia. L'esercito italiano fu sconfitto a Custoza e la flotta a Lissa; Garibaldi vinse a Bezzecca. Il Veneto arrivò perché la Prussia sconfisse l'Austria e l'Italia apparteneva all'alleanza vincitrice, non perché le sconfitte fossero irrilevanti.", "Pio IX vedeva la perdita del potere temporale come aggressione alla libertà della Chiesa. Molti cattolici distinguevano fede, obbedienza ecclesiastica e appartenenza nazionale; non esistevano due campi perfettamente compatti."], summary: "Il completamento territoriale intrecciò capacità militare limitata, diplomazia e identità concorrenti." },
        { title: "Il processo storico: Veneto, Porta Pia, Guarentigie", paragraphs: ["Il Veneto fu ceduto dall'Austria alla Francia e trasferito all'Italia dopo il trattato di Vienna e il plebiscito dell'ottobre 1866. Nel 1870 la sconfitta francese contro la Prussia rimosse la protezione di Roma. Dopo un tentativo di accordo, l'esercito entrò dalla breccia di Porta Pia il 20 settembre.", "Roma divenne capitale con la legge del 3 febbraio 1871. La legge delle Guarentigie del 13 maggio riconobbe inviolabilità, onori, comunicazioni e dotazione al papa. Pio IX la rifiutò perché era un atto unilaterale e continuò a non riconoscere il Regno."], summary: "Lo Stato risolse territorialmente la questione romana senza raggiungere una conciliazione." },
        { title: "Conseguenze e nuovo assetto: non expedit e cittadinanza cattolica", paragraphs: ["Nel 1874 la Santa Sede dichiarò non conveniente la partecipazione dei cattolici alle elezioni politiche: il non expedit divenne progressivamente più vincolante. Non escluse ogni attività municipale o sociale, ma limitò l'integrazione parlamentare di una popolazione largamente cattolica.", "La laicizzazione del diritto, il matrimonio civile e la soppressione degli enti ecclesiastici avevano già ampliato il conflitto. La questione romana divenne così una questione di cittadinanza e legittimità, non soltanto di confini."], summary: "Roma capitale rafforzò il Regno e mantenne fuori dalla sua piena vita politica una parte del mondo cattolico." },
        { title: "Conclusione ed epilogo: 1876, fallimento o compimento?", paragraphs: ["Il 18 marzo 1876 il governo Minghetti fu battuto alla Camera sulla gestione delle ferrovie. Divisioni interne alla Destra, opposizione fiscale e nuove coalizioni parlamentari resero possibile l'arrivo di Depretis. La 'rivoluzione parlamentare' avvenne dentro lo Statuto, non nelle piazze.", "La Destra cadeva dopo aver costruito amministrazione, credito e capitale; cadeva anche perché quei risultati avevano prodotto interessi, critiche e domande nuove. Dire che avesse soltanto fallito è falso; dire che avesse concluso felicemente il proprio compito cancella esclusioni e fratture."], summary: "Il 1876 fu insieme alternanza politica e giudizio sui modi con cui lo Stato era stato costruito." }
      ],
      source: { id: "guarentigie", title: "Legge delle Guarentigie e rifiuto pontificio", prompt: "Confronta ciò che lo Stato garantisce con ciò che il papa ritiene di perdere: le parole condividono la stessa idea di sovranità?" },
      activity: { title: "Roma o conciliazione?", prompt: "Nel settembre 1870 scegli fra intervento immediato, negoziato prolungato o rinuncia temporanea. Valuta consenso nazionale, libertà della Chiesa, rischio internazionale e autorità dello Stato." },
      coordinates: ["29 agosto 1862: Aspromonte", "15 settembre 1864: Convenzione", "1866: Veneto", "3 novembre 1867: Mentana", "20 settembre 1870: Porta Pia", "1871: Roma capitale e Guarentigie", "1874: non expedit", "18 marzo 1876: caduta Minghetti"],
      essentials: ["La Francia protesse militarmente Roma fino al 1870.", "Aspromonte mostrò il conflitto fra volontari e Stato.", "Il Veneto fu ottenuto dentro la vittoria prussiana.", "Custoza e Lissa furono sconfitte militari reali.", "Porta Pia fu resa possibile dalla guerra franco-prussiana.", "La legge delle Guarentigie era un atto unilaterale.", "Il non expedit limitò la partecipazione politica cattolica.", "Il governo Minghetti cadde sulla questione ferroviaria e per divisioni parlamentari."],
      vocab: { Questione_romana: "Conflitto sulla sovranità di Roma e sui rapporti fra Stato italiano e papato.", Guarentigie: "Garanzie unilaterali riconosciute dallo Stato al pontefice nel 1871.", Non_expedit: "Indicazione pontificia che scoraggiò e poi vietò ai cattolici la partecipazione alle elezioni politiche.", Potere_temporale: "Sovranità politica e territoriale esercitata dal papa.", Rivoluzione_parlamentare: "Nome dato al passaggio di maggioranza del 1876, avvenuto attraverso un voto della Camera." },
      answer: "Veneto e Roma consolidarono territorio e prestigio dello Stato, ma dipendevano da guerre europee e mostrarono limiti militari italiani. Roma capitale risolse la sovranità territoriale senza conciliare il papa: lo Stato divenne più completo mentre una parte dei cattolici rimaneva politicamente distante. La caduta del 1876 fu quindi successo istituzionale e crisi del modello della Destra.",
      connections: { map: "Completamento territoriale 1861-1870", people: ["lanza", "garibaldi", "pio"] }
    }
  ],
  people: [
    { id: "ricasoli", name: "Bettino Ricasoli", dates: "1809-1880", role: "Presidente del Consiglio e leader toscano", image: "assets/img/people/ricasoli.jpg", bio: "Succedette a Cavour e difese monarchia costituzionale, unità amministrativa e una soluzione liberale della questione ecclesiastica. Il suo rigore non eliminò le divisioni interne alla Destra.", idea: "Mostra la difficoltà di trasformare l'eredità cavouriana in una maggioranza stabile." },
    { id: "minghetti", name: "Marco Minghetti", dates: "1818-1886", role: "Presidente del Consiglio e riformatore", image: "assets/img/people/minghetti.jpg", bio: "Propose inizialmente un ordinamento regionale, poi governò dentro il sistema accentrato. Il suo secondo ministero raggiunse il pareggio e cadde nel 1876 sulla questione ferroviaria.", idea: "La sua traiettoria impedisce di ridurre la Destra a un blocco sempre e soltanto centralista." },
    { id: "lamarmora", name: "Alfonso La Marmora", dates: "1804-1878", role: "Generale e presidente del Consiglio", image: "assets/img/people/la-marmora.jpg", bio: "Guidò il governo e l'esercito nella guerra del 1866. Le sconfitte di Custoza e i contrasti di comando mostrarono la difficile integrazione militare del Regno.", idea: "Un esercito nazionale non nasce automaticamente dall'unione di reparti e comandi." },
    { id: "lanza", name: "Giovanni Lanza", dates: "1810-1882", role: "Presidente del Consiglio, 1869-1873", image: "assets/img/people/lanza.jpg", bio: "Il suo governo affrontò Porta Pia, Roma capitale e la legge delle Guarentigie. Medico e proprietario piemontese, rappresentò la sobrietà amministrativa della Destra.", idea: "Con lui il completamento territoriale diventa governo quotidiano della nuova capitale." },
    { id: "sella", name: "Quintino Sella", dates: "1827-1884", role: "Ministro delle Finanze", image: "assets/img/people/sella.jpg", bio: "Scienziato e politico, difese imposte e contenimento della spesa come condizione dell'indipendenza. Il pareggio fu un obiettivo collettivo della Destra, non un risultato ottenuto da lui solo.", idea: "Il rigore finanziario può essere insieme costruzione di sovranità e distribuzione ineguale dei sacrifici." },
    { id: "spaventa", name: "Silvio Spaventa", dates: "1822-1893", role: "Politico e teorico dell'amministrazione", image: "assets/img/people/spaventa.jpg", bio: "Meridionale, patriota e ministro, difese uno Stato forte regolato dalla legge e l'autonomia dell'amministrazione dagli interessi privati. Fu protagonista della politica ferroviaria.", idea: "La classe dirigente della Destra non fu esclusivamente settentrionale e conteneva progetti diversi di Stato." },
    { id: "rattazzi", name: "Urbano Rattazzi", dates: "1808-1873", role: "Leader del centro-sinistra e capo di governo", image: "assets/img/people/rattazzi.jpg", bio: "La sua legge comunale e provinciale del 1859 divenne base dell'accentramento. Da presidente del Consiglio gestì ambiguamente l'iniziativa garibaldina conclusa all'Aspromonte.", idea: "Le architetture della Destra nacquero anche da figure non riducibili a quel raggruppamento." },
    { id: "depretis", name: "Agostino Depretis", dates: "1813-1887", role: "Leader della Sinistra costituzionale", image: "assets/img/people/depretis.jpg", bio: "Garibaldino moderato e parlamentare, raccolse gruppi della Sinistra e dissidenti della Destra. Nel 1876 inaugurò la nuova maggioranza senza rovesciare monarchia o Statuto.", idea: "Il 1876 fu alternanza dentro lo Stato costruito dalla Destra, non una seconda rivoluzione nazionale." },
    { id: "vittorio", name: "Vittorio Emanuele II", dates: "1820-1878", role: "Re d'Italia", image: "assets/img/people/vittorio-emanuele.jpg", bio: "Conservò ampie prerogative in politica estera, esercito e nomina dei ministri. Dovette però operare con governi capaci di ottenere bilanci e maggioranze alla Camera.", idea: "La monarchia fu un centro attivo del sistema, non una figura puramente cerimoniale." },
    { id: "garibaldi", name: "Giuseppe Garibaldi", dates: "1807-1882", role: "Generale volontario e deputato", image: "assets/img/people/garibaldi.jpg", bio: "Dopo il 1861 tentò due volte di raggiungere Roma. Fermato dallo Stato all'Aspromonte e dai franco-pontifici a Mentana, incarnò la tensione fra rivoluzione nazionale e diplomazia governativa.", idea: "Lo Stato dovette controllare l'iniziativa che aveva contribuito a crearlo." },
    { id: "pio", name: "Pio IX", dates: "1792-1878", role: "Papa e sovrano dello Stato pontificio", image: "assets/img/people/pio-ix.jpg", bio: "Rifiutò la perdita del potere temporale e la legge delle Guarentigie. Il Sillabo e il non expedit espressero un conflitto profondo con lo Stato liberale, senza esaurire la pluralità del cattolicesimo italiano.", idea: "La questione romana opponeva due idee di sovranità e libertà della Chiesa." },
    { id: "crocco", name: "Carmine Crocco", dates: "1830-1905", role: "Capobanda lucano", image: "assets/img/people/crocco.jpg", bio: "Ex soldato borbonico e poi garibaldino, guidò bande in Basilicata. Collaborò con il legittimista Borjes ma difese autonomia e interessi propri; fu catturato nello Stato pontificio e condannato.", idea: "La sua biografia unisce mobilità politica, conflitto sociale e pratica criminale: nessuna etichetta basta." },
    { id: "villari", name: "Pasquale Villari", dates: "1827-1917", role: "Storico e meridionalista", image: "assets/img/people/villari.jpg", bio: "Esule napoletano del 1848, docente e parlamentare, nelle Lettere meridionali del 1875 collegò camorra, miseria, lavoro e responsabilità delle classi dirigenti.", idea: "Trasformò un problema trattato come polizia in questione sociale dello Stato nazionale." }
  ],
  timeline: [
    { date: "17 mar 1861", title: "Nasce il Regno d'Italia", text: "La proclamazione apre la costruzione amministrativa e finanziaria.", scale: "Stato" },
    { date: "6 giu 1861", title: "Muore Cavour", text: "La classe dirigente perde il proprio mediatore più autorevole.", scale: "Politica" },
    { date: "1862", title: "Lira e leva nazionale", text: "Moneta e servizio militare rendono concreti unità e obblighi.", scale: "Società" },
    { date: "29 ago 1862", title: "Aspromonte", text: "L'esercito ferma Garibaldi per evitare la guerra con la Francia.", scale: "Europa" },
    { date: "15 ago 1863", title: "Legge Pica", text: "La lotta al brigantaggio entra nella legislazione eccezionale.", scale: "Conflitti" },
    { date: "15 set 1864", title: "Convenzione di settembre", text: "Italia e Francia regolano temporaneamente la questione romana.", scale: "Europa" },
    { date: "1865", title: "Firenze capitale e codici", text: "La capitale si sposta; amministrazione e diritto vengono uniformati.", scale: "Stato" },
    { date: "1 mag 1866", title: "Corso forzoso", text: "La crisi sospende la convertibilità delle banconote.", scale: "Finanza" },
    { date: "24 giu-20 lug 1866", title: "Custoza e Lissa", text: "Esercito e flotta subiscono sconfitte nella guerra contro l'Austria.", scale: "Europa" },
    { date: "ott 1866", title: "Il Veneto entra nel Regno", text: "La vittoria prussiana e il trattato di Vienna completano il passaggio.", scale: "Europa" },
    { date: "1866-1867", title: "Asse ecclesiastico", text: "Soppressioni e vendite finanziano lo Stato senza riformare la terra.", scale: "Finanza" },
    { date: "3 nov 1867", title: "Mentana", text: "Francesi e pontifici sconfiggono i volontari garibaldini.", scale: "Europa" },
    { date: "1 gen 1869", title: "Tassa sul macinato", text: "L'imposta entra in vigore e provoca proteste represse.", scale: "Società" },
    { date: "20 set 1870", title: "Porta Pia", text: "La guerra franco-prussiana rende possibile l'ingresso italiano a Roma.", scale: "Europa" },
    { date: "1871", title: "Roma capitale e Guarentigie", text: "Lo Stato regola unilateralmente la posizione del papa.", scale: "Stato" },
    { date: "1874", title: "Non expedit", text: "La Santa Sede scoraggia la partecipazione alle elezioni politiche.", scale: "Società" },
    { date: "1875-1876", title: "Pareggio del bilancio", text: "Il risultato contabile diviene simbolo della Destra.", scale: "Finanza" },
    { date: "18 mar 1876", title: "Cade Minghetti", text: "La sconfitta sulle ferrovie apre il governo Depretis.", scale: "Politica" }
  ],
  maps: [
    { title: "Italia amministrativa dopo l'unificazione", image: "assets/img/maps/italia-amministrativa.svg", alt: "Schema dell'Italia con la catena Stato, prefetti, province e comuni", text: "La carta collega territorio e gerarchia: il prefetto rappresenta il governo; comuni e province hanno organi propri ma restano sottoposti a vigilanza.", note: "Ricostruzione didattica originale basata sulla legge 20 marzo 1865, n. 2248. Confini schematici, non utilizzabili per misure." },
    { title: "Aree del brigantaggio postunitario", image: "assets/img/maps/brigantaggio.svg", alt: "Carta schematica delle principali aree del brigantaggio nel Mezzogiorno continentale", text: "L'intensità maggiore riguarda zone interne dell'ex Regno delle Due Sicilie. Le bande sono mobili: le campiture indicano aree ricorrenti, non controllo territoriale continuo.", note: "Sintesi prudenziale da studi di Lupo, Pinto, Davis e documentazione parlamentare. Non rappresenta un fronte militare stabile." },
    { title: "Completamento territoriale 1861-1870", image: "assets/img/maps/completamento.svg", alt: "Tre fasi schematiche dei confini italiani nel 1861, 1866 e 1870", text: "La sequenza distingue proclamazione del Regno, acquisizione del Veneto e annessione di Roma e Lazio.", note: "Carta didattica originale. Trentino, Trieste e altre terre rivendicate restano fuori dal Regno nel 1870." },
    { title: "Indicatori territoriali: leggere senza stereotipi", image: "assets/img/maps/indicatori.svg", alt: "Grafico comparativo su alfabetizzazione e ferrovie con avvertenze metodologiche", text: "Gli indicatori mostrano svantaggi meridionali in capitale umano e infrastrutture, ma non autorizzano a trasformare regioni diverse in due blocchi uniformi.", note: "Dati e ordini di grandezza: Censimento 1861, Istat; Bastasin-Toniolo 2023; serie storiche ferroviarie Istat. Le stime retrospettive restano dipendenti da definizioni e confini." }
  ],
  sources: [
    { id: "statuto", title: "Statuto Albertino", type: "Carta costituzionale", date: "4 marzo 1848, vigente nel Regno dal 1861", author: "Carlo Alberto; istituzioni del Regno", provenance: "Senato della Repubblica", verbatim: true, excerpt: ["Il Re solo appartiene il potere esecutivo.", "Il potere legislativo sarà collettivamente esercitato dal Re e da due Camere.", "Tutti i regnicoli, qualunque sia il loro titolo o grado, sono eguali dinanzi alla legge."], context: "Carta concessa nel Regno di Sardegna e rimasta legge fondamentale dell'Italia unita.", audience: "Sudditi e istituzioni del Regno.", purpose: "Definire poteri della Corona, Camere e diritti civili.", limits: "Il testo non descrive da solo la prassi parlamentare e non stabilisce suffragio universale.", interpretation: "L'uguaglianza civile dichiarata conviveva con un accesso politico censitario; la prassi trasformò inoltre la carta concessa in una monarchia progressivamente più parlamentare.", questions: ["Quali poteri dipendono direttamente dal re?", "Quale distanza esiste fra uguaglianza civile e accesso al voto?", "Perché una carta del 1848 poté reggere uno Stato nato nel 1861?"], url: "https://www.senato.it/istituzione/la-costituzione/statuto-albertino" },
    { id: "unificazione-amministrativa", title: "Legge per l'unificazione amministrativa", type: "Legge", date: "20 marzo 1865", author: "Parlamento e Corona del Regno d'Italia", provenance: "Normattiva / Senato della Repubblica", verbatim: false, excerpt: ["Il Regno si divide in Provincie, Circondari, Mandamenti e Comuni.", "Il Prefetto rappresenta il potere esecutivo in tutta la Provincia.", "Il Sindaco è nominato dal Re fra i consiglieri comunali."], context: "La legge n. 2248 e i suoi allegati uniformano settori decisivi dell'amministrazione.", audience: "Amministrazioni, funzionari e cittadini.", purpose: "Creare una struttura comune di governo territoriale.", limits: "Gli estratti isolano la gerarchia e non mostrano tutte le competenze e i controlli previsti.", interpretation: "La catena verticale rendeva governabile il nuovo Regno, ma subordinava la rappresentanza locale a funzionari responsabili soprattutto verso il centro.", questions: ["Verso chi è responsabile il prefetto?", "Quale rappresentanza possiede il comune?", "Dove vedi il compromesso fra elezione e nomina?"], url: "https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:legge:1865-03-20;2248" },
    { id: "casati", title: "Legge Casati sull'istruzione", type: "Regio decreto legislativo", date: "13 novembre 1859", author: "Governo del Regno di Sardegna", provenance: "Archivio storico della normativa italiana", verbatim: false, excerpt: ["L'istruzione elementare è di due gradi, ciascuno dei quali dura due anni.", "L'istruzione del grado inferiore è data gratuitamente in tutti i Comuni.", "I Comuni provvedono agli stipendi dei maestri e alle scuole necessarie."], context: "Nata durante la guerra del 1859, viene estesa al Regno d'Italia.", audience: "Comuni, scuole, famiglie e amministrazione.", purpose: "Ordinare l'intero sistema scolastico e fissare un primo obbligo elementare.", limits: "Il diritto formale non dice quante risorse avessero i comuni né quanta frequenza effettiva esistesse.", interpretation: "Il diritto nazionale alla scuola dipendeva da comuni diseguali: la distanza fra norma e capacità finanziaria aiuta a spiegare l'applicazione territoriale irregolare.", questions: ["Chi paga concretamente l'istruzione primaria?", "Perché gratuità e obbligo non garantiscono frequenza?", "Quali territori rischiano di restare indietro?"], url: "https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:regio.decreto.legislativo:1859-11-13;3725" },
    { id: "macinato", title: "Imposta sulla macinazione dei cereali", type: "Legge fiscale", date: "7 luglio 1868", author: "Parlamento e Corona del Regno d'Italia", provenance: "Raccolta ufficiale delle leggi del Regno", verbatim: false, excerpt: ["È stabilita una tassa sulla macinazione dei cereali.", "La tassa è riscossa mediante contatori applicati ai mulini.", "L'esercente del mulino è responsabile verso l'erario."], context: "La legge n. 4490 entra in vigore il 1 gennaio 1869 durante il risanamento finanziario.", audience: "Mugnai, contribuenti e amministrazione fiscale.", purpose: "Ottenere un gettito diffuso e controllabile su un consumo essenziale.", limits: "Il testo normativo non mostra il peso sui bilanci familiari né la violenza delle proteste.", interpretation: "Un meccanismo tecnico rese quotidiano il rapporto fiscale con lo Stato e trasferì una quota rilevante del sacrificio sui consumatori di cereali.", questions: ["Perché il contatore al mulino rende l'imposta visibile?", "Chi anticipa il pagamento e chi lo sopporta infine?", "Quale alternativa fiscale sarebbe stata possibile?"], url: "https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:legge:1868-07-07;4490" },
    { id: "massari", title: "Relazione della Commissione sul brigantaggio", type: "Inchiesta parlamentare", date: "1863", author: "Giuseppe Massari e Commissione della Camera", provenance: "Camera dei deputati, atti parlamentari", verbatim: false, excerpt: ["Il brigantaggio non è che il sintomo di un male profondo.", "Le condizioni economiche e sociali delle popolazioni rurali offrono alimento alle bande.", "La repressione è necessaria, ma non basta senza buon governo e giustizia."], context: "La Commissione viaggia e raccoglie informazioni mentre lo Stato prepara misure eccezionali.", audience: "Camera, governo e opinione pubblica.", purpose: "Spiegare il fenomeno e legittimare una strategia di contrasto.", limits: "È una voce istituzionale; dipende da informatori locali e opera dentro l'obiettivo di consolidare lo Stato.", interpretation: "La relazione riconosce cause sociali, ma le ordina dentro il problema statale dell'ordine pubblico; diagnosi e finalità politica vanno lette insieme.", questions: ["Quale rapporto stabilisce fra cause sociali e reato?", "Che cosa vede una commissione parlamentare e che cosa può non vedere?", "La diagnosi è coerente con la soluzione proposta?"], url: "https://storia.camera.it/" },
    { id: "pica", title: "Legge Pica", type: "Legge eccezionale", date: "15 agosto 1863", author: "Parlamento e Corona del Regno d'Italia", provenance: "Senato della Repubblica", verbatim: false, excerpt: ["Il Governo avrà facoltà di dichiarare in istato di brigantaggio le Provincie nelle quali sia d'uopo.", "Gli imputati di brigantaggio saranno giudicati dai Tribunali militari.", "Il domicilio coatto potrà essere assegnato agli oziosi, vagabondi e persone sospette."], context: "La legge n. 1409 viene adottata nella fase più intensa del conflitto.", audience: "Autorità militari, amministrative e popolazioni delle province interessate.", purpose: "Accelerare repressione, giudizio e controllo preventivo.", limits: "Le categorie di sospetto sono ampie; l'applicazione concreta varia e richiede altre fonti.", interpretation: "L'emergenza fu incorporata nella legalità liberale mediante tribunali militari e categorie preventive ampie: sicurezza e garanzie entrarono in tensione.", questions: ["Quali garanzie ordinarie vengono ridotte?", "Perché la categoria di sospetto è problematica?", "Come cambia la natura liberale dello Stato durante l'emergenza?"], url: "https://www.senato.it/node/84602/printable/print" },
    { id: "villari", title: "Lettere meridionali", type: "Inchiesta giornalistica e saggio", date: "1875", author: "Pasquale Villari", provenance: "Sistema Bibliotecario di Ateneo, Università di Firenze", verbatim: false, excerpt: ["La questione non è soltanto di polizia: è una questione sociale.", "Dove la legge non protegge il debole, la violenza privata diviene governo.", "Noi abbiamo unificato le istituzioni, ma non ancora le condizioni civili del paese."], context: "Villari scrive al direttore dell'Opinione dopo aver osservato Napoli e il lavoro nelle zolfare siciliane.", audience: "Opinione pubblica liberale e classe dirigente.", purpose: "Trasformare miseria, camorra e sfruttamento in problemi politici nazionali.", limits: "È lo sguardo riformatore di un intellettuale liberale; gli estratti sono adattamenti didattici controllati sulle edizioni digitali e vanno confrontati con l'opera.", interpretation: "La denuncia sposta criminalità e miseria dal solo terreno di polizia a quello della responsabilità sociale, restando però una critica interna al liberalismo del tempo.", questions: ["Perché rifiuta una spiegazione solo criminale?", "Chi è incluso nel 'noi' di Villari?", "Quale responsabilità attribuisce allo Stato e alle élite locali?"], url: "https://www.sba.unifi.it/p583.html" },
    { id: "guarentigie", title: "Legge delle Guarentigie", type: "Legge e risposta pontificia", date: "13 maggio 1871", author: "Regno d'Italia; Pio IX", provenance: "Senato della Repubblica", verbatim: false, excerpt: ["La persona del Sommo Pontefice è sacra ed inviolabile.", "È assicurata al Sommo Pontefice una dotazione annua di lire 3.225.000.", "La Santa Sede non riconosce una garanzia concessa unilateralmente dal potere che ha occupato il suo territorio."], context: "Dopo Porta Pia lo Stato tenta di garantire indipendenza e comunicazioni del pontefice senza trattato.", audience: "Santa Sede, cattolici italiani e potenze straniere.", purpose: "Separare sovranità territoriale italiana e libertà spirituale del papa.", limits: "La legge e il rifiuto parlano linguaggi giuridici diversi; gli estratti non esauriscono il conflitto.", interpretation: "Lo Stato offrì garanzie dall'interno della propria sovranità; il rifiuto pontificio contestò proprio la legittimità di quella concessione unilaterale.", questions: ["Quale sovranità presuppone la legge?", "Perché una garanzia può apparire insufficiente a chi la riceve?", "Quali effetti politici produce il mancato accordo?"], url: "https://www.senato.it/application/xmanager/projects/leg19/file/repository/relazioni/libreria/fascicoli_divulgativi/unit_2015_con_sovracopertina.pdf" }
  ],
  workshop: [
    { title: "Scegli il criterio di giudizio", prompt: "Quale risultato pesa di più nella tua valutazione?", options: ["Capacità dello Stato di sopravvivere e governare", "Inclusione politica e sociale dei cittadini", "Equilibrio fra unità e differenze territoriali"] },
    { title: "Individua il costo decisivo", prompt: "Quale frattura limita maggiormente il successo della Destra?", options: ["Suffragio ristretto e notabilato", "Fiscalità regressiva e repressione", "Conflitto con Chiesa e autonomie locali"] },
    { title: "Valuta l'alternativa", prompt: "Quale scelta diversa era più plausibile nel contesto?", options: ["Più decentramento amministrativo", "Prelievo meno centrato sui consumi popolari", "Allargamento graduale più rapido del voto"] },
    { title: "Formula il verdetto provvisorio", prompt: "Come interpreti il 1876?", options: ["Caduta per fallimenti accumulati", "Alternanza resa possibile dai successi istituzionali", "Combinazione di compimento e crisi del modello"] }
  ],
  quiz: [
    { q: "Perché la Destra storica non può essere definita un partito moderno?", options: ["Rifiutava il Parlamento", "Era una rete di gruppi e notabili senza organizzazione di massa", "Non aveva ministri", "Esisteva solo in Toscana"], answer: 1, why: "Era un raggruppamento parlamentare eterogeneo, fondato su notabili e legami regionali.", recover: "Rivedi attori e paese legale.", lesson: "stato-sulla-carta" },
    { q: "Quale affermazione descrive meglio il suffragio del 1861?", options: ["Universale maschile", "Esteso alla maggioranza dei contribuenti", "Maschile, censitario, alfabetizzato e inferiore al 2% della popolazione", "Riservato ai militari"], answer: 2, why: "Circa 419.000 persone avevano diritto al voto su quasi 22 milioni di abitanti.", recover: "Rivedi la prima lezione.", lesson: "stato-sulla-carta" },
    { q: "Che cosa rende impreciso usare piemontesizzazione come spiegazione totale?", options: ["Il Piemonte non aveva leggi", "Sopravvissero personale, pratiche e negoziazioni locali", "Tutte le regioni votarono contro", "Il modello era francese"], answer: 1, why: "L'estensione sabauda fu forte, ma non cancellò ogni continuità territoriale.", recover: "Rivedi accentramento e alternative.", lesson: "accentramento" },
    { q: "Quale funzione aveva il prefetto?", options: ["Rappresentava il papa", "Era eletto a suffragio universale", "Rappresentava il governo e vigilava sulla provincia", "Dirigeva soltanto le scuole"], answer: 2, why: "Era il nodo territoriale dell'esecutivo e dell'ordine pubblico.", recover: "Rivedi la legge del 1865.", lesson: "accentramento" },
    { q: "Perché la legge Casati ebbe applicazione diseguale?", options: ["Vietava scuole rurali", "Affidava costi decisivi a comuni con risorse molto diverse", "Aboliva l'obbligo", "Era valida solo a Roma"], answer: 1, why: "Gratuità e obbligo richiedevano edifici, maestri e controlli che molti comuni non potevano garantire.", recover: "Rivedi costruire cittadini.", lesson: "cittadini" },
    { q: "Quale rapporto esiste fra leva e nazionalizzazione?", options: ["Solo positivo", "Solo repressivo", "Integrava uomini e lingua di comando ma sottraeva lavoro e generava renitenza", "Nessuno"], answer: 2, why: "Lo stesso istituto poteva costruire appartenenza ed essere vissuto come imposizione.", recover: "Rivedi scuola ed esercito.", lesson: "cittadini" },
    { q: "Che cosa fu il corso forzoso del 1866?", options: ["Un prestito volontario", "La sospensione della convertibilità con obbligo di accettare banconote", "L'abolizione delle monete", "Una tassa sul pane"], answer: 1, why: "Fu una risposta monetaria alla crisi finanziaria e bellica.", recover: "Rivedi il bilancio.", lesson: "bilancio" },
    { q: "Perché il macinato era socialmente regressivo?", options: ["Colpiva soltanto i titoli pubblici", "Incideva su consumi essenziali e pesava proporzionalmente di più sui redditi bassi", "Era pagato solo dai ministri", "Favoriva i comuni poveri"], answer: 1, why: "Pane e polenta assorbivano una quota maggiore dei bilanci popolari.", recover: "Rivedi imposte dirette e indirette.", lesson: "bilancio" },
    { q: "Il pareggio del 1875-1876 significò che il debito era estinto?", options: ["Sì", "No, indicava equilibrio annuo fra entrate e spese", "Solo il debito borbonico", "Solo quello ferroviario"], answer: 1, why: "Un saldo di esercizio non cancella lo stock del debito.", recover: "Rivedi conseguenze del risanamento.", lesson: "bilancio" },
    { q: "Quale interpretazione del brigantaggio è storicamente più solida?", options: ["Solo criminalità", "Un esercito nazionale meridionale unitario", "Combinazione variabile di politica, società, renitenza e crimine", "Una guerra straniera senza italiani"], answer: 2, why: "Composizione, obiettivi e territori delle bande erano plurali.", recover: "Rivedi gli storici discutono.", lesson: "brigantaggio" },
    { q: "Quale limite presenta la relazione Massari come fonte?", options: ["Non parla del Mezzogiorno", "È prodotta da un'istituzione impegnata a consolidare lo Stato", "È scritta nel Novecento", "Non contiene osservazioni sociali"], answer: 1, why: "Riconosce cause sociali ma resta uno sguardo statale con obiettivi politici.", recover: "Rivedi il laboratorio sulla fonte.", lesson: "brigantaggio" },
    { q: "Che cosa introdusse la legge Pica?", options: ["Suffragio universale", "Regioni autonome", "Tribunali militari e misure eccezionali", "Abolizione della leva"], answer: 2, why: "La legge ampliò poteri repressivi nelle province dichiarate in stato di brigantaggio.", recover: "Rivedi il processo storico.", lesson: "brigantaggio" },
    { q: "Quale frase sui divari del 1861 è più corretta?", options: ["Nord industriale e Sud feudale senza eccezioni", "Nessuna differenza misurabile", "Italia agricola con differenze regionali reali e indicatori non coincidenti", "Il divario nacque interamente nel 1861"], answer: 2, why: "La storiografia rifiuta sia la caricatura duale sia la negazione delle differenze.", recover: "Rivedi dati e interpretazioni.", lesson: "mezzogiorno" },
    { q: "Perché una politica uniforme può produrre effetti diseguali?", options: ["Perché la legge cambia lingua", "Perché opera su territori con risorse e strutture differenti", "Perché i dati sono inutili", "Perché non si applica mai"], answer: 1, why: "Uguale imposta o tariffa incide diversamente secondo redditi, credito e infrastrutture.", recover: "Rivedi la questione meridionale.", lesson: "mezzogiorno" },
    { q: "Perché l'Italia ottenne il Veneto nonostante Custoza e Lissa?", options: ["Le sconfitte furono inventate", "L'Austria lo regalò", "La vittoria prussiana e l'alleanza determinarono l'esito diplomatico", "Lo conquistò Garibaldi da solo"], answer: 2, why: "L'Italia apparteneva alla coalizione vincitrice guidata dalla Prussia.", recover: "Rivedi la guerra del 1866.", lesson: "roma-1876" },
    { q: "Che cosa rese possibile Porta Pia nel 1870?", options: ["Un accordo già firmato da Pio IX", "Il ritiro francese durante la guerra franco-prussiana", "La vittoria di Mentana", "La caduta di Minghetti"], answer: 1, why: "La crisi e sconfitta di Napoleone III rimossero la protezione militare di Roma.", recover: "Rivedi il contesto europeo.", lesson: "roma-1876" },
    { q: "Perché Pio IX rifiutò le Guarentigie?", options: ["Non prevedevano alcuna libertà religiosa", "Erano un atto unilaterale dello Stato di cui non riconosceva la sovranità su Roma", "Abolivano il papa", "Imponevano il voto"], answer: 1, why: "Accettarle avrebbe significato riconoscere implicitamente il quadro politico italiano.", recover: "Rivedi la questione romana.", lesson: "roma-1876" },
    { q: "Come va interpretata la caduta della Destra nel 1876?", options: ["Come invasione straniera", "Solo come fallimento totale", "Come alternanza parlamentare prodotta da divisioni, costi e risultati del modello", "Come abolizione dello Statuto"], answer: 2, why: "La Sinistra governò dentro istituzioni consolidate dalla stessa Destra.", recover: "Rivedi l'epilogo.", lesson: "roma-1876" }
  ]
};
