window.HIST_DATA = {
  meta: {
    title: "Bismarck e l'unità tedesca. Nazione, Stato e potenza",
    shortTitle: "Bismarck e il Reich",
    storageKey: "storia-bismarck-reich-v1",
    question: "Come fu possibile realizzare l'unità nazionale desiderata dai liberali del 1848 sotto la guida di una monarchia che ne limitava il potere?",
    thesis: "L'unità tedesca non fu l'opera solitaria di Bismarck né l'esito inevitabile del nazionalismo. La resero possibile l'integrazione economica dello Zollverein, la potenza industriale e militare prussiana, il fallimento liberale del 1848, scelte diplomatiche contingenti e tre guerre. Bismarck trasformò queste condizioni in una soluzione piccolo-tedesca dominata dalla Prussia: nazionale e federale, dotata di suffragio universale maschile, ma non parlamentare. Dopo il 1871 cercò di consolidarla mediante integrazione giuridica, repressione, assicurazioni sociali e un equilibrio diplomatico tanto efficace quanto fragile.",
    workshopIntro: "Evita sia il culto del grande uomo sia l'idea di un processo automatico. Una tesi storica deve distinguere condizioni strutturali, decisioni, occasioni e conseguenze: che cosa esisteva prima di Bismarck, quali alternative furono sconfitte, come operarono Parlamento ed esercito, e perché il Reich combinò modernità politica e autorità monarchica.",
    previous: { title: "Indice delle lezioni di Storia", url: "../" },
    next: { title: "La Sinistra storica", url: "../Sinistra-storica/" }
  },
  lessons: [
    {
      id: "germania-prima", number: 1, title: "Una nazione senza Stato", eyebrow: "Vienna, Zollverein e 1848", period: "1815-1850",
      question: "Perché l'integrazione economica e il sentimento nazionale non bastarono a creare uno Stato tedesco?",
      lead: "Dopo Vienna il mondo germanico era una confederazione di Stati sovrani. Lo Zollverein collegò mercati e ferrovie sotto la guida prussiana; il Parlamento di Francoforte tentò di collegare unità e libertà, ma non possedeva la forza necessaria per imporre la propria costituzione.",
      sections: [
        { title: "Il mondo precedente: trentanove Stati e due potenze", paragraphs: ["Nel 1815 il Congresso di Vienna sostituì il dissolto Sacro Romano Impero con la Confederazione germanica. I trentanove Stati conservavano sovranità, dinastie ed eserciti; la Dieta di Francoforte, presieduta dall'Austria, non era un governo nazionale eletto.", "Austria e Prussia appartenevano entrambe alla Confederazione, ma erano potenze diverse. L'Impero asburgico era multinazionale; la Prussia possedeva territori discontinui, ma una burocrazia e un esercito capaci di coordinarli."], summary: "Il problema tedesco nasceva dall'intreccio fra pluralità statale, rivalità austro-prussiana e aspirazione nazionale." },
        { title: "Le fratture: nazionalismo, repressione e mercato", paragraphs: ["Le guerre contro Napoleone avevano diffuso simboli nazionali e richieste costituzionali. Metternich rispose con i decreti di Karlsbad del 1819: censura, controllo delle università e repressione delle associazioni studentesche.", "Dal 1834 lo Zollverein eliminò molte barriere doganali fra gli Stati aderenti e adottò una tariffa esterna comune. L'Austria restò fuori. Ferrovie, commercio e industria rafforzarono la centralità prussiana, ma interessi economici condivisi non cancellarono dinastie e autonomie."], summary: "La repressione non spense il problema nazionale; il mercato lo spostò progressivamente verso la Prussia." },
        { title: "Attori, gruppi e conflitti: liberali, principi e lavoratori", paragraphs: ["Borghesi, professori, studenti e professionisti immaginavano spesso una Germania costituzionale. Non concordavano però su confini, forma dello Stato e ampiezza della partecipazione popolare.", "I principi difendevano la sovranità dei propri Stati; artigiani e lavoratori urbani portavano nel 1848 anche richieste sociali. Ridurre la rivoluzione alla sola domanda nazionale cancella il conflitto fra libertà politica, ordine sociale e questione del lavoro."], summary: "L'unità era un obiettivo comune soltanto in apparenza: gruppi diversi le attribuivano significati incompatibili." },
        { title: "Il processo storico: Francoforte tenta la via parlamentare", paragraphs: ["Il 18 maggio 1848 l'Assemblea nazionale si riunì nella Paulskirche di Francoforte. Elaborò diritti fondamentali e una costituzione federale, discutendo fra soluzione grande-tedesca con l'Austria e piccolo-tedesca senza l'Austria.", "Nel marzo 1849 prevalse la soluzione piccolo-tedesca e la corona fu offerta al re di Prussia Federico Guglielmo IV. Egli la rifiutò: non accettava che un'assemblea nata dalla rivoluzione fondasse la legittimità imperiale. Il Parlamento non disponeva di un esercito proprio."], summary: "Francoforte progettò uno Stato, ma dipendeva dai poteri dinastici che avrebbe dovuto subordinare." },
        { title: "Le fonti in dialogo: la costituzione che non divenne Stato", paragraphs: ["La Costituzione di Francoforte documenta una possibilità storica reale: una monarchia costituzionale federale con rappresentanza popolare. Non va letta come anticipazione inevitabile del futuro, ma come progetto sconfitto.", "La fonte normativa dice come avrebbe dovuto funzionare il Reich; non prova che le istituzioni previste possedessero mezzi e obbedienza sufficienti. Il rifiuto del re rende visibile la distanza fra legittimità parlamentare e forza statale."], summary: "Una costituzione può descrivere un ordine politico senza avere ancora la capacità di produrlo." },
        { title: "Conseguenze e nuovo assetto: l'unità resta, cambia la via", paragraphs: ["Il fallimento del 1848-1849 non cancellò nazionalismo, reti economiche e simboli comuni. Dimostrò però che il Parlamento, senza accordo con almeno una grande monarchia e senza forza militare, non poteva sostituire la Confederazione.", "La domanda nazionale passò progressivamente dall'iniziativa rivoluzionaria alla competizione fra Austria e Prussia. Bismarck non inventò il problema: trovò un movimento nazionale vivo e un'alternativa liberale già sconfitta."], summary: "Il 1848 lasciò un progetto e una lezione politica: l'unità avrebbe richiesto il potere di uno Stato." }
      ],
      source: { id: "francoforte", title: "La Costituzione di Francoforte e il rifiuto della corona", prompt: "Confronta il principio rappresentativo del progetto con i mezzi reali dell'assemblea." },
      activity: { type: "decision", title: "Tre vie per la Germania", prompt: "Scegli fra confederazione riformata, grande Germania e piccola Germania. Indica alleato, ostacolo e prezzo politico." },
      coordinates: ["1815: Confederazione germanica di 39 Stati", "1819: decreti di Karlsbad", "1834: Zollverein", "18 maggio 1848: Parlamento di Francoforte", "28 marzo 1849: Costituzione", "Aprile 1849: rifiuto della corona"],
      essentials: ["La Confederazione germanica non era uno Stato nazionale.", "Austria e Prussia competevano per la guida del mondo tedesco.", "Lo Zollverein integrò mercati senza produrre automaticamente unità politica.", "L'Austria rimase fuori dall'unione doganale guidata dalla Prussia.", "Il Parlamento di Francoforte collegò unità e costituzione.", "Grande Germania e piccola Germania indicavano soluzioni diverse.", "Federico Guglielmo IV rifiutò la corona parlamentare.", "Il Parlamento non disponeva di forza militare propria."],
      vocab: { Confederazione_germanica: "Unione di Stati sovrani creata nel 1815 e presieduta dall'Austria.", Zollverein: "Unione doganale guidata dalla Prussia, operativa dal 1834.", Soluzione_grande_tedesca: "Progetto di uno Stato tedesco comprendente l'Austria tedesca.", Soluzione_piccolo_tedesca: "Progetto di unità senza l'Austria e sotto guida prussiana.", Paulskirche: "Chiesa di Francoforte sede dell'Assemblea nazionale." },
      answer: "Economia e nazionalismo crearono connessioni e aspettative, non un'autorità capace di subordinare gli Stati. Francoforte fallì perché dipendeva dalla collaborazione dei principi e non disponeva della forza necessaria. Da allora la questione nazionale si legò ancora più strettamente alla potenza prussiana.",
      connections: { map: "Dalla Confederazione allo Zollverein", people: ["bismarck", "guglielmo", "moltke"] }
    },
    {
      id: "crisi-prussiana", number: 2, title: "Governare senza bilancio", eyebrow: "La crisi costituzionale prussiana", period: "1858-1866",
      question: "Bismarck difese lo Stato nella crisi o svuotò il diritto del Parlamento di controllare il governo?",
      lead: "La Camera liberale voleva l'unità nazionale ma temeva un esercito sottratto al controllo parlamentare. Bismarck usò una lacuna della Costituzione per governare e riscuotere imposte senza bilancio approvato.",
      sections: [
        { title: "Il mondo precedente: costituzione senza governo parlamentare", paragraphs: ["La Costituzione prussiana del 1850 prevedeva due Camere e la partecipazione parlamentare alle leggi e alle imposte. Il governo, però, dipendeva dal re e non dalla fiducia della Camera dei deputati.", "Il sistema elettorale delle tre classi distribuiva gli elettori secondo il contributo fiscale: una minoranza ricca eleggeva tanti rappresentanti quanto gruppi assai più numerosi."], summary: "La Prussia possedeva istituzioni rappresentative, ma la Corona conservava il controllo dell'esecutivo." },
        { title: "Le fratture: la riforma dell'esercito", paragraphs: ["Guglielmo I, il ministro della Guerra Albrecht von Roon e il capo di Stato maggiore Helmuth von Moltke volevano aumentare gli effettivi, prolungare il servizio e ridurre il ruolo della Landwehr.", "La maggioranza liberale non rifiutava la potenza nazionale. Temeva però che l'esercito permanente rafforzasse la monarchia contro il Parlamento. Il bilancio era un conflitto su chi dovesse dirigere lo Stato."], summary: "La stessa forza necessaria all'unificazione poteva diventare lo strumento dell'autorità monarchica." },
        { title: "Attori, gruppi e conflitti: Bismarck entra nella crisi", paragraphs: ["Otto von Bismarck proveniva dall'aristocrazia terriera degli Junker ed era un conservatore leale alla Corona. Le esperienze diplomatiche gli avevano mostrato che Austria e Prussia difficilmente avrebbero condiviso la guida della Germania.", "Il 23 settembre 1862 Guglielmo I lo nominò ministro-presidente e ministro degli Esteri. Bismarck intendeva usare il movimento nazionale per rafforzare la monarchia prussiana."], summary: "Bismarck collegò la questione tedesca alla difesa della prerogativa regia." },
        { title: "Il processo storico: lacuna, imposte e ferro e sangue", paragraphs: ["La Costituzione non stabiliva come risolvere un conflitto insanabile sul bilancio. Bismarck sostenne che, non potendo lo Stato fermarsi, il governo potesse continuare a riscuotere imposte sulla base del bilancio precedente.", "Il 30 settembre 1862 ricordò alla commissione del bilancio che le grandi questioni non erano state risolte da discorsi e decisioni di maggioranza, ma dal ferro e dal sangue. La frase apparteneva a una disputa concreta, non a una teoria di guerra permanente."], summary: "Bismarck trasformò un silenzio costituzionale in una superiorità pratica dell'esecutivo." },
        { title: "Le fonti in dialogo: leggere il discorso nel suo conflitto", paragraphs: ["Il verbale mostra Bismarck mentre discute articoli costituzionali, spese e durata del servizio. Isolare soltanto ferro e sangue produce un personaggio più semplice del politico reale.", "La fonte va interrogata per destinatario e intenzione: convincere o intimidire una commissione liberale. Non prova che Bismarck possedesse già nel 1862 un piano dettagliato delle tre guerre."], summary: "La citazione è autentica; l'idea di un copione già scritto è un'interpretazione non dimostrata." },
        { title: "Conseguenze e nuovo assetto: vittoria e legge di indennità", paragraphs: ["Dal 1862 al 1866 il governo operò senza bilancio regolarmente approvato. Dopo la vittoria sull'Austria, Bismarck chiese una legge di indennità che sanasse retroattivamente le spese.", "Molti liberali accettarono: l'obiettivo nazionale prevalse sulla battaglia costituzionale e nacque il Partito nazional-liberale. Il compromesso consentì riforme, ma lasciò il cancelliere non responsabile davanti alla maggioranza."], summary: "Il successo militare chiuse politicamente il conflitto a favore della monarchia." }
      ],
      source: { id: "ferro-sangue", title: "Il discorso del ferro e del sangue", prompt: "Ricostruisci il contesto e distingui ciò che Bismarck dice dal progetto retrospettivo attribuitogli." },
      activity: { type: "constitution", title: "Chi controlla l'esercito?", prompt: "Distribuisci il potere fra re, governo e Camera. Commenta capacità decisionale e garanzie." },
      coordinates: ["1850: Costituzione prussiana", "1861: Guglielmo I re", "23 settembre 1862: Bismarck ministro-presidente", "30 settembre 1862: discorso", "1862-1866: governo senza bilancio approvato", "Settembre 1866: legge di indennità"],
      essentials: ["La Prussia era costituzionale ma non parlamentare.", "Il sistema delle tre classi favoriva i più ricchi.", "Roon e Moltke progettarono la riforma militare.", "I liberali difendevano il diritto di bilancio.", "Bismarck interpretò la lacuna a favore dell'esecutivo.", "Il discorso nacque nella commissione del bilancio.", "Non prova un piano completo già fissato nel 1862.", "La legge di indennità divise i liberali."],
      vocab: { Monarchia_costituzionale: "Monarchia limitata da una costituzione, senza necessaria responsabilità parlamentare.", Monarchia_parlamentare: "Sistema in cui il governo deve conservare la fiducia della maggioranza.", Lacuna_costituzionale: "Questione non regolata esplicitamente dalla costituzione.", Junker: "Grande proprietario terriero dell'est prussiano.", Legge_di_indennità: "Legge del 1866 che approvò retroattivamente le spese." },
      answer: "Bismarck evitò la paralisi dello Stato, ma scelse l'interpretazione più favorevole alla Corona e limitò il controllo parlamentare. La vittoria del 1866 rese accettabile ciò che restava costituzionalmente controverso.",
      connections: { map: "Poteri nella monarchia prussiana", people: ["bismarck", "guglielmo", "roon"] }
    },
    {
      id: "ducati", number: 3, title: "Una guerra condivisa prepara il conflitto", eyebrow: "Schleswig, Holstein e Danimarca", period: "1863-1865",
      question: "La crisi dei ducati fu un semplice pretesto o un problema reale trasformato in occasione politica?",
      lead: "Schleswig e Holstein erano legati alla monarchia danese da rapporti dinastici e giuridici complessi. Prussia e Austria combatterono insieme nel 1864; la vittoria creò un'amministrazione comune destinata ad aggravare la rivalità.",
      sections: [
        { title: "Il mondo precedente: confini che non coincidono", paragraphs: ["Lo Schleswig aveva popolazione mista danese e tedesca; Holstein e Lauenburg erano prevalentemente tedeschi e membri della Confederazione. I tre ducati erano collegati alla Corona danese, ma non incorporati nello stesso modo.", "Nazionalisti danesi e tedeschi proponevano confini diversi. Diritto dinastico, appartenenza confederale, lingua e volontà nazionale non conducevano alla stessa soluzione."], summary: "La crisi nasceva da sovranità sovrapposte e criteri nazionali concorrenti." },
        { title: "Le fratture: la Costituzione di novembre", paragraphs: ["Nel 1863 la Danimarca adottò una costituzione che legava più strettamente lo Schleswig al regno. Prussia e Austria considerarono la scelta incompatibile con gli accordi precedenti.", "La morte di Federico VII riaprì anche la successione. L'opinione nazionale tedesca sosteneva Federico di Augustenburg, mentre Bismarck preferiva conservare il controllo della decisione nelle mani delle grandi potenze."], summary: "Una modifica costituzionale trasformò un conflitto latente in crisi internazionale." },
        { title: "Attori, gruppi e conflitti: alleati con obiettivi diversi", paragraphs: ["Prussia e Austria volevano impedire che la Danimarca imponesse unilateralmente la propria soluzione. La Dieta e i piccoli Stati difendevano però procedure confederali che Bismarck considerava vincolanti.", "I nazionalisti tedeschi chiedevano l'annessione o un ducato indipendente; i danesi difendevano l'integrità della monarchia. Le popolazioni locali non erano un blocco omogeneo."], summary: "La coalizione contro la Danimarca univa soggetti che immaginavano esiti diversi." },
        { title: "Il processo storico: guerra e amministrazione comune", paragraphs: ["Nel febbraio 1864 le truppe prussiane e austriache entrarono nei ducati. La superiorità militare e l'assalto prussiano a Dybbøl costrinsero la Danimarca alla sconfitta.", "La Pace di Vienna del 30 ottobre cedette i ducati ai vincitori. Con la Convenzione di Gastein del 1865 la Prussia amministrò lo Schleswig, l'Austria l'Holstein e il Lauenburg passò alla Prussia."], summary: "La vittoria non risolse la questione: creò una gestione duale dentro la rivalità austro-prussiana." },
        { title: "Le fonti in dialogo: trattati e popolazioni", paragraphs: ["Trattati e protocolli documentano titoli giuridici e rapporti fra Stati. Dicono molto meno su identità miste, paure locali e preferenze delle popolazioni.", "La clausola del 1866 su un possibile voto nello Schleswig settentrionale mostra che l'idea di consultazione esisteva, ma non venne applicata allora. Il plebiscito arrivò soltanto nel 1920."], summary: "Il diritto internazionale regolò i trasferimenti; non offrì immediata autodeterminazione." },
        { title: "Conseguenze e nuovo assetto: il condominio impossibile", paragraphs: ["La Prussia ottenne accesso strategico al Mare del Nord. L'Austria, lontana geograficamente, amministrava l'Holstein circondato dall'area prussiana.", "Bismarck non inventò la questione, ma usò la gestione comune per aumentare la pressione su Vienna. Il confine fra problema reale e sfruttamento dell'occasione è il nodo storico."], summary: "La prima guerra risolse il conflitto con la Danimarca e preparò quello per l'egemonia tedesca." }
      ],
      source: { id: "vienna-1864", title: "Pace di Vienna e Convenzione di Gastein", prompt: "Individua che cosa viene ceduto, chi amministra e quali soggetti non partecipano alla decisione." },
      activity: { type: "strategy", title: "Una crisi, quattro mosse", prompt: "Ordina le mosse diplomatiche e militari cercando di ottenere i ducati senza isolare la Prussia." },
      coordinates: ["Novembre 1863: costituzione danese", "1 febbraio 1864: ingresso austro-prussiano", "18 aprile 1864: Dybbøl", "30 ottobre 1864: Pace di Vienna", "14 agosto 1865: Gastein"],
      essentials: ["Schleswig e Holstein avevano status e popolazioni differenti.", "La crisi conteneva elementi dinastici, giuridici e nazionali.", "Prussia e Austria combatterono insieme.", "Dybbøl fu uno snodo decisivo.", "La Danimarca cedette i ducati.", "Gastein separò l'amministrazione.", "Le popolazioni non furono consultate direttamente.", "La questione fu reale e politicamente sfruttabile."],
      vocab: { Ducati_dell_Elba: "Schleswig, Holstein e Lauenburg.", Condominio: "Esercizio congiunto o coordinato di diritti su un territorio.", Convenzione_di_Gastein: "Accordo del 1865 sull'amministrazione dei ducati.", Nazionalismo_danese: "Movimento che voleva integrare lo Schleswig.", Nazionalismo_tedesco: "Movimento che rivendicava i ducati per la Germania." },
      answer: "La crisi coinvolgeva successione, trattati, lingue e appartenenza nazionale. Bismarck trasformò però il problema in occasione, usando la vittoria comune e la difficile amministrazione per rendere più probabile lo scontro con l'Austria.",
      connections: { map: "I ducati e la rivalità", people: ["bismarck", "guglielmo", "moltke"] }
    },
    {
      id: "guerra-austria", number: 4, title: "Escludere l'Austria senza distruggerla", eyebrow: "La guerra delle sette settimane", period: "1866-1867",
      question: "Perché Bismarck volle una vittoria decisiva ma una pace relativamente moderata con l'Austria?",
      lead: "Diplomazia, alleanza italiana, ferrovie, comando di Moltke e fucile ad ago favorirono la Prussia; la pace escluse Vienna dalla Germania ma ne preservò l'Impero come possibile partner futuro.",
      sections: [
        { title: "Il mondo precedente: un dualismo instabile", paragraphs: ["Dal 1815 Austria e Prussia avevano condiviso la guida della Confederazione. Zollverein ed espansione prussiana avevano reso sempre più difficile quel compromesso.", "Dopo il 1864 la gestione dei ducati portò le due potenze a contatto diretto. Dietro l'Holstein stava la domanda decisiva: chi avrebbe riorganizzato la Germania?"], summary: "La crisi locale divenne il punto di rottura di una rivalità strutturale." },
        { title: "Le fratture: isolamento diplomatico e alleanza italiana", paragraphs: ["Bismarck lavorò perché Russia e Gran Bretagna restassero neutrali e Napoleone III attendesse compensi. L'8 aprile 1866 l'Italia si alleò con la Prussia per ottenere il Veneto.", "Quando l'Austria portò l'Holstein davanti alla Dieta, la Prussia occupò il ducato e propose una riforma federale. La Dieta votò la mobilitazione; Berlino dichiarò sciolta la Confederazione."], summary: "La guerra fu preparata isolando l'avversario e collegando interessi tedeschi e italiani." },
        { title: "Attori, gruppi e conflitti: Bismarck, Moltke e i liberali", paragraphs: ["Moltke organizzò la concentrazione di eserciti separati attraverso ferrovie e telegrafo. Il fucile Dreyse offriva vantaggi tattici, ma nessuna singola tecnologia spiega da sola la vittoria.", "I liberali furono divisi fra condanna della guerra dinastica e accettazione della guida prussiana. L'Italia aprì un secondo fronte pur subendo sconfitte a Custoza e Lissa."], summary: "La vittoria dipese da comando, logistica, tecnologia, alleanze e scelte avversarie." },
        { title: "Il processo storico: Sadowa cambia la Germania", paragraphs: ["La campagna iniziò nel giugno 1866. Il 3 luglio, a Königgrätz-Sadowa, gli eserciti prussiani si concentrarono e sconfissero quello austriaco.", "Guglielmo I e parte dei militari volevano avanzare su Vienna. Bismarck si oppose a condizioni distruttive: l'obiettivo era escludere l'Austria dagli affari tedeschi, non provocarne la rivincita."], summary: "La moderazione dopo la vittoria fu una scelta strategica, non un gesto sentimentale." },
        { title: "Le fonti in dialogo: il preliminare di Nikolsburg", paragraphs: ["Il testo del 26 luglio conserva l'integrità territoriale austriaca, riconosce lo scioglimento della Confederazione e consente una nuova organizzazione senza l'Austria.", "Il trattato parla la lingua dei sovrani e delle potenze. Non rappresenta soldati, cittadini o piccoli Stati annessi; per ricostruire il costo umano e politico servono altre fonti."], summary: "La pace documenta una rivoluzione geopolitica formulata come accordo fra monarchie." },
        { title: "Conseguenze e nuovo assetto: Confederazione del Nord", paragraphs: ["La Pace di Praga sciolse la vecchia Confederazione. La Prussia annesse Hannover, Assia-Cassel, Nassau, Francoforte e i ducati; nel 1867 ventidue Stati a nord del Meno formarono la Confederazione della Germania del Nord.", "Gli Stati meridionali restarono formalmente indipendenti, ma firmarono alleanze militari segrete. L'Austria si riorganizzò nel 1867 come duplice monarchia austro-ungarica."], summary: "Il 1866 risolse il dualismo a favore della Prussia e creò lo Stato che sarebbe diventato il Reich." }
      ],
      source: { id: "nikolsburg", title: "Il preliminare di Nikolsburg", prompt: "Individua gli obiettivi raggiunti e ciò che Bismarck rinuncia a ottenere." },
      activity: { type: "strategy", title: "Vincere la pace", prompt: "Scegli condizioni territoriali, indennità e rapporti futuri con Vienna. Valuta il rischio di una coalizione ostile." },
      coordinates: ["8 aprile 1866: alleanza italo-prussiana", "3 luglio 1866: Sadowa", "26 luglio 1866: Nikolsburg", "23 agosto 1866: Pace di Praga", "1867: Confederazione del Nord", "1867: Compromesso austro-ungarico"],
      essentials: ["La guerra decise l'egemonia sul mondo tedesco.", "Bismarck cercò la neutralità delle grandi potenze.", "L'Italia entrò per il Veneto.", "Ferrovie, comando e fucile ad ago contribuirono alla vittoria.", "Sadowa fu decisiva.", "Bismarck rifiutò una pace distruttiva.", "La Confederazione germanica fu sciolta.", "La Confederazione del Nord fu uno Stato federale.", "L'Austria non cedette territori direttamente alla Prussia."],
      vocab: { Dualismo_austro_prussiano: "Competizione per la guida della Germania.", Sadowa: "Battaglia decisiva del 3 luglio 1866.", Pace_moderata: "Accordo che raggiunge l'obiettivo evitando di distruggere l'avversario.", Confederazione_della_Germania_del_Nord: "Stato federale creato nel 1867.", Ausgleich: "Compromesso austro-ungarico del 1867." },
      answer: "Bismarck aveva bisogno di eliminare l'influenza austriaca sulla Germania, non l'Impero asburgico. Una pace punitiva avrebbe favorito rivincita e coalizioni future; la moderazione rese possibile la successiva alleanza con Vienna.",
      connections: { map: "Il 1866 e la piccola Germania", people: ["bismarck", "moltke", "guglielmo"] }
    },
    {
      id: "francia-reich", number: 5, title: "Dalla crisi di Ems al Reich", eyebrow: "Guerra franco-prussiana e proclamazione", period: "1870-1871",
      question: "Bismarck provocò la guerra con la Francia o sfruttò una crisi nella quale anche Parigi scelse l'escalation?",
      lead: "La candidatura Hohenzollern al trono di Spagna, la richiesta francese di garanzie e la versione abbreviata del dispaccio di Ems trasformarono una crisi diplomatica in questione d'onore.",
      sections: [
        { title: "Il mondo precedente: una Germania quasi unita", paragraphs: ["Dopo il 1866 il Nord formava uno Stato federale, mentre Baviera, Württemberg, Baden e Assia meridionale conservavano autonomia. Alleanze militari segrete li collegavano però a Berlino.", "Napoleone III temeva una potenza tedesca sul Reno. I governi meridionali diffidavano della Prussia protestante, ma temevano anche le pressioni francesi. L'unità completa restava possibile, non inevitabile."], summary: "Il 1870 trovò una Germania istituzionalmente divisa ma strategicamente collegata." },
        { title: "Le fratture: una corona spagnola e la richiesta francese", paragraphs: ["Dopo la rivoluzione spagnola del 1868, la corona fu offerta a Leopoldo di Hohenzollern-Sigmaringen. La Francia temeva di trovarsi fra due monarchie legate alla stessa dinastia; la candidatura venne ritirata.", "Parigi chiese però a Guglielmo I di garantire che non sarebbe mai stata riproposta. Il re rifiutò cortesemente a Bad Ems e informò Bismarck attraverso un dispaccio redatto da Heinrich Abeken."], summary: "La rinuncia alla candidatura non chiuse la crisi perché Parigi cercò una garanzia permanente." },
        { title: "Attori, gruppi e conflitti: onore, stampa e decisione", paragraphs: ["Bismarck abbreviò il testo eliminando formule concilianti e rese pubblico un comunicato più tagliente, senza inventare una nuova richiesta o un nuovo rifiuto. Stampa e opinioni pubbliche lo lessero come offesa nazionale.", "Il governo francese aveva margini di scelta e il 19 luglio dichiarò guerra. Parlare di manipolazione bismarckiana è corretto; trasformare la Francia in un automa cancella decisioni, pressioni interne e cultura dell'onore."], summary: "Bismarck accelerò l'escalation, ma la guerra richiese scelte politiche da entrambe le parti." },
        { title: "Il processo storico: Sedan, Repubblica, assedio", paragraphs: ["Gli Stati meridionali applicarono gli accordi militari. Mobilitazione ferroviaria, Stato maggiore e superiorità numerica permisero agli eserciti tedeschi di accerchiare forze francesi; Napoleone III si arrese a Sedan il 2 settembre 1870.", "La caduta dell'Impero non terminò la guerra. La Repubblica proclamata a Parigi continuò la resistenza; la capitale fu assediata fino all'armistizio del gennaio 1871."], summary: "La guerra dinastica divenne guerra nazionale anche dopo la cattura dell'imperatore." },
        { title: "Le fonti in dialogo: due versioni del dispaccio", paragraphs: ["Il confronto fra testo originale e versione pubblicata permette di osservare materialmente un intervento diplomatico. Le omissioni riducono il contesto e cambiano il tono senza falsificare ogni fatto.", "Le memorie successive di Bismarck aggiungono una narrazione autobiografica nella quale il cancelliere presenta la decisione come calcolo magistrale. Vanno confrontate con i documenti contemporanei."], summary: "La selezione può modificare il significato politico di informazioni vere." },
        { title: "Conseguenze e nuovo assetto: Versailles e Francoforte", paragraphs: ["Il 18 gennaio 1871 Guglielmo I fu proclamato imperatore tedesco nella Sala degli Specchi. Il Reich nacque dall'adesione negoziata degli Stati meridionali alla Confederazione del Nord.", "Il Trattato di Francoforte impose cinque miliardi di franchi e la cessione dell'Alsazia e di parte della Lorena. L'annessione rafforzò il Reich ma alimentò in Francia il revanscismo."], summary: "La vittoria completò l'unità e incorporò nel nuovo ordine una ferita internazionale duratura." }
      ],
      source: { id: "ems", title: "Il dispaccio di Ems: originale e versione pubblicata", prompt: "Segna omissioni e variazioni di tono. Distingui manipolazione, causalità e responsabilità della dichiarazione di guerra." },
      activity: { type: "ems", title: "Redazione diplomatica", prompt: "Confronta una versione conciliante e una provocatoria dello stesso rapporto. Quali fatti restano e quali elementi orientano il lettore?" },
      coordinates: ["1868: rivoluzione in Spagna", "13 luglio 1870: dispaccio di Ems", "19 luglio 1870: dichiarazione di guerra francese", "2 settembre 1870: Sedan", "18 gennaio 1871: proclamazione del Reich", "10 maggio 1871: Trattato di Francoforte"],
      essentials: ["Gli Stati meridionali erano autonomi ma legati militarmente alla Prussia.", "La candidatura spagnola riguardava Leopoldo di Hohenzollern.", "La candidatura fu ritirata prima della guerra.", "La Francia chiese una garanzia permanente.", "Bismarck abbreviò il dispaccio rendendolo più tagliente.", "La Francia dichiarò guerra.", "Sedan abbatté il Secondo Impero ma non concluse il conflitto.", "Il Reich fu proclamato il 18 gennaio 1871.", "Alsazia e parte della Lorena furono annesse."],
      vocab: { Dispaccio_di_Ems: "Comunicazione sull'incontro fra Guglielmo I e l'ambasciatore francese, abbreviata da Bismarck.", Casus_belli: "Fatto presentato come motivo sufficiente per iniziare una guerra.", Mobilitazione: "Richiamo, trasporto e concentrazione delle forze armate.", Imperatore_tedesco: "Titolo federale assunto da Guglielmo I.", Revanscismo: "Desiderio politico di rivincita e recupero dei territori perduti." },
      answer: "Bismarck sfruttò deliberatamente la crisi e modificò il tono pubblico del dispaccio. Non costrinse però meccanicamente la Francia: il governo di Parigi scelse la dichiarazione di guerra. L'esito completò l'unità sotto la Prussia e aprì il problema dell'Alsazia-Lorena.",
      connections: { map: "Dalla Confederazione del Nord al Reich", people: ["bismarck", "napoleone", "guglielmo"] }
    },
    {
      id: "costituzione-reich", number: 6, title: "Un Parlamento senza governo parlamentare", eyebrow: "Costituzione e politica interna", period: "1871-1879",
      question: "Il Reich era autoritario con un Parlamento decorativo o costituzionale con un Parlamento reale ma limitato?",
      lead: "Il Reichstag era eletto a suffragio universale maschile e approvava leggi e bilancio; il cancelliere dipendeva però dall'imperatore. La Prussia dominava esercito, burocrazia e Bundesrat.",
      sections: [
        { title: "Il mondo precedente: la costituzione del Nord", paragraphs: ["La Costituzione del 1871 riprese in gran parte quella della Confederazione della Germania del Nord. L'Impero comprendeva venticinque Stati federati; Alsazia-Lorena ebbe inizialmente lo status di territorio imperiale.", "Gli Stati conservarono scuole, amministrazioni e molte competenze interne. Politica estera, dogane, moneta, poste e forze armate vennero coordinate a livello imperiale."], summary: "Il Reich fu un vero Stato federale, non una Prussia semplicemente ingrandita sul piano giuridico." },
        { title: "Le fratture: rappresentanza popolare e prerogativa monarchica", paragraphs: ["Il Reichstag era eletto da tutti i maschi adulti con voto diretto e segreto. Nessuna legge poteva entrare in vigore senza Reichstag e Bundesrat.", "L'imperatore nominava il cancelliere, comandava le forze armate e rappresentava il Reich. Il cancelliere non doveva ottenere la fiducia della maggioranza. Democrazia elettorale e governo parlamentare non coincidevano."], summary: "Il popolo partecipava alla legislazione senza determinare direttamente la formazione del governo." },
        { title: "Attori, gruppi e conflitti: Bundesrat, Reichstag, partiti", paragraphs: ["Il Bundesrat rappresentava i governi degli Stati e disponeva di importanti poteri legislativi ed esecutivi. La Prussia possedeva diciassette voti e poteva bloccare modifiche costituzionali.", "Nazional-liberali, conservatori, Zentrum e socialdemocratici organizzarono una politica nazionale. Bismarck doveva costruire maggioranze per approvare le leggi, pur non dipendendo dalla fiducia del Reichstag."], summary: "Il Parlamento non governava, ma il cancelliere non poteva ignorarlo stabilmente." },
        { title: "Il processo storico: integrare e combattere i nemici interni", paragraphs: ["Con i nazional-liberali furono unificati moneta, diritto economico e istituzioni. Il Kulturkampf tentò invece di subordinare la Chiesa cattolica al nuovo Stato mediante controllo del clero, espulsioni e sanzioni.", "Il Zentrum non scomparve: aumentò il consenso e costrinse Bismarck a cercare un compromesso con Leone XIII. La politica mostrò il limite di unificazione imposta contro circa un terzo della popolazione."], summary: "Costruire istituzioni comuni riuscì meglio che cancellare identità e organizzazioni autonome." },
        { title: "Le fonti in dialogo: che cosa dice la Costituzione", paragraphs: ["Gli articoli permettono di mappare nomina del cancelliere, legislazione, bilancio, comando militare e rappresentanza federale. È necessario separare poteri formali e prassi politica.", "La Costituzione non dimostra che il Reichstag fosse irrilevante, né che il sistema fosse parlamentare. Servono votazioni, campagne e negoziati fra governo e partiti."], summary: "Il testo costituzionale stabilisce possibilità e limiti; la storia politica mostra come furono usati." },
        { title: "Conseguenze e nuovo assetto: modernità sotto tutela", paragraphs: ["Il Reich creò uno spazio politico nazionale e milioni di uomini parteciparono alle elezioni. Partiti, stampa e associazioni ampliarono la mobilitazione.", "Esercito ed esecutivo conservarono però forte autonomia. La modernizzazione non eliminò le strutture autoritarie: le rese compatibili con una società elettorale di massa."], summary: "Il Reich fu un costituzionalismo federale a prevalenza monarchica." }
      ],
      source: { id: "costituzione-1871", title: "La Costituzione del Reich", prompt: "Attribuisci ogni potere a imperatore, cancelliere, Bundesrat o Reichstag. Distingui elezione e responsabilità del governo." },
      activity: { type: "constitution", title: "Costruisci il diagramma del potere", prompt: "Sposta il baricentro fra imperatore, Stati e Reichstag. Spiega quale assetto è vicino al 1871." },
      coordinates: ["16 aprile 1871: Costituzione", "1871-1878: Kulturkampf", "1871: integrazione monetaria e giuridica", "1873: leggi di maggio prussiane", "1879: svolta protezionistica"],
      essentials: ["Il Reich comprendeva 25 Stati più l'Alsazia-Lorena.", "La Costituzione riprese quella del Nord.", "Il Reichstag era eletto a suffragio universale maschile.", "Reichstag e Bundesrat partecipavano alla legislazione.", "Il cancelliere dipendeva dall'imperatore.", "La Prussia dominava esercito e Bundesrat.", "Il Kulturkampf rafforzò il Zentrum.", "Il Parlamento possedeva poteri reali ma non formava il governo.", "Il Reich era federale e monarchico-costituzionale."],
      vocab: { Reichstag: "Assemblea eletta che approvava leggi e bilancio.", Bundesrat: "Organo dei governi degli Stati federati.", Cancelliere: "Capo del governo nominato dall'imperatore.", Kulturkampf: "Conflitto fra Stato bismarckiano e Chiesa cattolica.", Zentrum: "Partito cattolico attivo nel Reichstag." },
      answer: "Il Reichstag non era decorativo: nessuna legge passava senza di esso. Tuttavia il cancelliere non dipendeva dalla sua fiducia, mentre imperatore, esercito e Prussia conservavano prerogative decisive. Il sistema era rappresentativo ma non parlamentare.",
      connections: { map: "La costituzione a due legittimità", people: ["bismarck", "guglielmo", "windthorst"] }
    },
    {
      id: "stato-sociale", number: 7, title: "Reprimere e assicurare", eyebrow: "Socialismo, protezionismo e Stato sociale", period: "1878-1889",
      question: "Perché Bismarck combatté il socialismo e nello stesso tempo costruì le prime grandi assicurazioni sociali europee?",
      lead: "Leggi antisocialiste e assicurazioni non erano opposte nella logica del cancelliere: entrambe miravano a integrare i lavoratori nello Stato monarchico, separandoli dalla socialdemocrazia.",
      sections: [
        { title: "Il mondo precedente: industrializzazione e nuova politica", paragraphs: ["Carbone, ferro, chimica, ferrovie e banche trasformarono la Germania. Ruhr, Saar e Slesia attrassero popolazione; città e fabbriche crearono nuovi rischi di malattia, infortunio e vecchiaia.", "La socialdemocrazia offriva organizzazione politica e linguaggio di classe. La crescita elettorale mostrava che l'unità nazionale non aveva eliminato il conflitto sociale."], summary: "Il Reich divenne una società industriale attraversata da nuovi rischi e movimenti." },
        { title: "Le fratture: attentati e svolta del 1878", paragraphs: ["Nel 1878 due attentati colpirono Guglielmo I. Gli autori non agivano per ordine del partito socialista, ma Bismarck collegò politicamente violenza e socialdemocrazia e ottenne nuove elezioni.", "La legge del 21 ottobre vietò associazioni, riunioni e giornali socialisti. I candidati potevano tuttavia presentarsi al Reichstag."], summary: "L'emergenza monarchica divenne occasione per restringere spazi politici e associativi." },
        { title: "Attori, gruppi e conflitti: lavoratori, imprenditori e Stato", paragraphs: ["Operai e famiglie sopportavano costi che il salario non copriva. Imprenditori temevano oneri; enti locali e casse mutualistiche possedevano esperienze sulle quali lo Stato poté costruire.", "Bismarck voleva che il lavoratore riconoscesse nello Stato una protezione concreta e che la monarchia conquistasse lealtà sociale."], summary: "La legislazione nacque da conflitti e istituzioni preesistenti, non da benevolenza isolata." },
        { title: "Il processo storico: malattia, infortuni, vecchiaia", paragraphs: ["L'assicurazione sanitaria del 1883 finanziava prestazioni attraverso contributi; quella contro gli infortuni del 1884 attribuiva un ruolo centrale ai datori; nel 1889 arrivò l'assicurazione per invalidità e vecchiaia.", "Coperture e prestazioni erano limitate secondo criteri odierni. La novità stava nella responsabilità pubblica e obbligatoria per rischi sociali della società industriale."], summary: "Lo Stato sociale nacque incompleto, ma trasformò rischi privati in questione pubblica." },
        { title: "Le fonti in dialogo: il messaggio imperiale del 1881", paragraphs: ["Il messaggio di Guglielmo I presenta la questione sociale come problema da affrontare non soltanto con repressione, ma con misure positive per i lavoratori.", "La fonte chiarisce intenzioni dichiarate, non gli effetti. Va confrontata con legge antisocialista, testi delle assicurazioni, contributi e crescita elettorale socialdemocratica."], summary: "Una politica può proteggere materialmente e limitare politicamente gli stessi soggetti." },
        { title: "Conseguenze e nuovo assetto: successo istituzionale, fallimento politico", paragraphs: ["Le assicurazioni divennero un modello europeo e sopravvissero a Bismarck. Non eliminarono povertà e disuguaglianze, ma stabilirono nuovi diritti e apparati.", "La socialdemocrazia continuò a crescere. Nel 1890 la legge eccezionale non fu rinnovata. Il tentativo di separare lavoratori e socialismo fallì, mentre la protezione entrò stabilmente nello Stato."], summary: "Bismarck non sconfisse il socialismo; cambiò però il significato della cittadinanza sociale." }
      ],
      source: { id: "politica-sociale", title: "Dal messaggio sociale alla legge antisocialista", prompt: "Confronta destinatari e strumenti. In che modo protezione e repressione appartengono allo stesso progetto?" },
      activity: { type: "welfare", title: "Bastone, assicurazione o rappresentanza?", prompt: "Distribuisci tre strumenti di governo della questione sociale e osserva gli effetti." },
      coordinates: ["1878: attentati contro Guglielmo I", "21 ottobre 1878: legge antisocialista", "17 novembre 1881: messaggio sociale", "1883: malattie", "1884: infortuni", "1889: invalidità e vecchiaia", "1890: fine delle leggi eccezionali"],
      essentials: ["L'industrializzazione creò nuovi rischi.", "Gli attentatori non agivano per ordine della socialdemocrazia.", "La legge vietò organizzazioni e stampa socialista.", "I candidati socialdemocratici continuarono a concorrere.", "Le assicurazioni miravano anche a rafforzare la lealtà allo Stato.", "Tre grandi leggi furono approvate fra 1883 e 1889.", "Le prestazioni iniziali erano limitate.", "La socialdemocrazia continuò a crescere.", "Repressione e protezione erano complementari."],
      vocab: { Leggi_antisocialiste: "Norme eccezionali contro associazioni, riunioni e stampa socialiste.", Assicurazione_sociale: "Protezione obbligatoria contro rischi sociali.", Questione_sociale: "Problemi di lavoro, povertà e conflitto della società industriale.", Socialdemocrazia: "Movimento politico organizzato dei lavoratori.", Paternalismo: "Protezione concessa dall'alto per ottenere lealtà." },
      answer: "Bismarck voleva indebolire la socialdemocrazia senza lasciare i lavoratori esclusi dalla protezione statale. La repressione fallì nel fermare il movimento; le assicurazioni modificarono stabilmente le funzioni dello Stato.",
      connections: { map: "Bastone e assicurazioni", people: ["bismarck", "guglielmo", "windthorst"] }
    },
    {
      id: "equilibrio-eredita", number: 8, title: "Una potenza sazia in un sistema fragile", eyebrow: "Diplomazia, colonie e caduta", period: "1871-1894",
      question: "Il sistema di Bismarck mantenne la pace europea o rinviò conflitti che la sua complessità rendeva difficili da controllare?",
      lead: "Dopo il 1871 Bismarck dichiarò la Germania soddisfatta territorialmente. Cercò di isolare la Francia, evitare una coalizione franco-russa e mediare fra Vienna e San Pietroburgo.",
      sections: [
        { title: "Il mondo precedente: il Reich al centro dell'Europa", paragraphs: ["La nuova Germania possedeva popolazione, industria ed esercito capaci di alterare ogni equilibrio. L'annessione dell'Alsazia-Lorena rese la Francia un avversario prevedibile.", "Austria-Ungheria e Russia competevano nei Balcani; la Gran Bretagna difendeva rotte e impero. La posizione centrale offriva influenza e rischio di guerra su due fronti."], summary: "Il successo trasformò la Prussia da sfidante in potenza responsabile dell'ordine." },
        { title: "Le fratture: crisi d'Oriente e Congresso di Berlino", paragraphs: ["La guerra russo-ottomana del 1877-1878 produsse Santo Stefano e una grande Bulgaria legata alla Russia. Austria-Ungheria e Gran Bretagna temettero l'espansione russa.", "Al Congresso di Berlino la Bulgaria fu ridotta, l'Austria ottenne l'amministrazione della Bosnia-Erzegovina e la Gran Bretagna Cipro con un accordo separato. La Russia si sentì privata di parte della vittoria."], summary: "La mediazione evitò una crisi immediata ma non eliminò la rivalità balcanica." },
        { title: "Attori, gruppi e conflitti: alleanze in tensione", paragraphs: ["La Duplice del 1879 legò Germania e Austria-Ungheria contro un attacco russo. La Triplice del 1882 aggiunse l'Italia e contribuì a isolare la Francia.", "Bismarck cercò contemporaneamente la cooperazione con la Russia: intese dei Tre Imperatori e controassicurazione del 1887. La strategia richiedeva segretezza e interpretazioni sottili."], summary: "Il sistema produceva sicurezza finché nessun alleato chiedeva di applicare fino in fondo tutte le promesse." },
        { title: "Il processo storico: colonie prudenti, potere personale, caduta", paragraphs: ["Dal 1884 Bismarck accettò protettorati in Africa e Pacifico. La Conferenza di Berlino stabilì regole per Congo, Niger e riconoscimento delle occupazioni; non assegnò semplicemente l'Africa alla Germania.", "Guglielmo II, imperatore dal 1888, non accettò la supremazia del cancelliere. Contrasti su leggi antisocialiste, governo e autorità portarono alle dimissioni di Bismarck nel marzo 1890."], summary: "La prudenza europea conviveva con l'espansione coloniale e dipendeva fortemente dal cancelliere." },
        { title: "Le fonti in dialogo: il trattato di controassicurazione", paragraphs: ["Il trattato segreto del 1887 prometteva neutralità benevola, salvo un attacco tedesco alla Francia o russo all'Austria. Il testo mostra il tentativo di evitare due fronti senza abbandonare Vienna.", "La segretezza rendeva possibile il compromesso ma ne limitava trasparenza e continuità. Nel 1890 il nuovo governo non lo rinnovò; Francia e Russia si avvicinarono."], summary: "Lo strumento che teneva aperte più relazioni era difficile da trasmettere a successori diversi." },
        { title: "Conseguenze e conclusione: l'eredità di Bismarck", paragraphs: ["Il sistema contribuì a evitare una guerra generale fra 1871 e 1890, ma non risolse Alsazia-Lorena, Balcani e competizione imperiale. Non esiste una linea automatica dal 1890 al 1914.", "L'eredità fu un Reich potente, federale, industriale e socialmente organizzato, ma con esecutivo e militari poco dipendenti dal Parlamento. Successo nazionale e problema costituzionale restarono inseparabili."], summary: "Bismarck costruì un ordine efficace ma personale; dopo di lui restarono la potenza e le tensioni amministrate." }
      ],
      source: { id: "controassicurazione", title: "Il trattato segreto di controassicurazione", prompt: "Traccia obblighi ed eccezioni. Quale problema risolve e quale contraddizione crea rispetto a Vienna?" },
      activity: { type: "alliances", title: "L'incubo delle coalizioni", prompt: "Costruisci una rete che isoli la Francia senza spingere la Russia verso Parigi." },
      coordinates: ["1873: intesa dei Tre Imperatori", "1878: Congresso di Berlino", "1879: Duplice", "1882: Triplice", "1884-1885: svolta coloniale", "1887: controassicurazione", "1890: dimissioni", "1891-1894: alleanza franco-russa"],
      essentials: ["Bismarck considerò il Reich soddisfatto in Europa.", "La Francia doveva restare isolata.", "Austria-Ungheria e Russia competevano nei Balcani.", "Berlino rivide Santo Stefano senza risolvere la crisi.", "La Duplice legò Germania e Austria.", "La Triplice aggiunse l'Italia.", "La controassicurazione cercò la neutralità russa.", "La Germania acquisì protettorati dal 1884.", "Bismarck si dimise nel 1890.", "Il mancato rinnovo favorì l'avvicinamento franco-russo.", "Il sistema dipendeva da gestione personale e segreta."],
      vocab: { Potenza_sazia: "Stato soddisfatto territorialmente e orientato a conservare l'ordine.", Congresso_di_Berlino: "Conferenza del 1878 sugli equilibri balcanici.", Duplice_Alleanza: "Patto difensivo fra Germania e Austria-Ungheria.", Trattato_di_controassicurazione: "Accordo segreto del 1887 fra Germania e Russia.", Weltpolitik: "Politica mondiale e navale sviluppata soprattutto dopo Bismarck." },
      answer: "Il sistema contribuì a evitare una guerra generale e impedì per anni l'alleanza franco-russa. Non eliminò i conflitti e dipendeva da impegni segreti, capacità personale e moderazione degli alleati. La dissoluzione ridusse la flessibilità europea senza rendere inevitabile il 1914.",
      connections: { map: "La rete diplomatica", people: ["bismarck", "guglielmo-ii", "gorcakov"] }
    }
  ],
  people: [
    { id: "bismarck", name: "Otto von Bismarck", dates: "1815-1898", role: "Ministro-presidente prussiano e cancelliere", image: "assets/img/people/bismarck.svg", imageAlt: "Ritratto didattico originale di Otto von Bismarck", bio: "Conservatore di origine Junker e diplomatico, guidò la Prussia dal conflitto costituzionale all'unità. Dopo il 1871 combinò maggioranze, autorità monarchica, politiche sociali e diplomazia d'equilibrio.", idea: "Usò il nazionalismo come forza dello Stato; il successo non cancellò i limiti costituzionali del sistema." },
    { id: "guglielmo", name: "Guglielmo I", dates: "1797-1888", role: "Re di Prussia e primo imperatore tedesco", image: "assets/img/people/guglielmo-i.svg", imageAlt: "Ritratto didattico originale di Guglielmo I", bio: "Sostenne la riforma dell'esercito e nominò Bismarck nel 1862. La prerogativa monarchica rimase un pilastro del nuovo Reich.", idea: "L'unità fu proclamata come federazione di principi sotto il re di Prussia, non come sovranità parlamentare." },
    { id: "moltke", name: "Helmuth von Moltke", dates: "1800-1891", role: "Capo di Stato maggiore prussiano", image: "assets/img/people/moltke.svg", imageAlt: "Ritratto didattico originale di Helmuth von Moltke", bio: "Riorganizzò pianificazione e comando, impiegando ferrovie e telegrafo per concentrare eserciti separati. Fu decisivo nel 1866 e nel 1870.", idea: "La vittoria deriva da istituzioni, logistica, comando e addestramento, non da un'arma miracolosa." },
    { id: "roon", name: "Albrecht von Roon", dates: "1803-1879", role: "Ministro della Guerra prussiano", image: "assets/img/people/roon.svg", imageAlt: "Ritratto didattico originale di Albrecht von Roon", bio: "Progettò l'ampliamento dell'esercito che provocò il conflitto sul bilancio e collaborò con Moltke e Bismarck.", idea: "Prima delle guerre venne il conflitto su chi dovesse finanziare e controllare l'esercito." },
    { id: "napoleone", name: "Napoleone III", dates: "1808-1873", role: "Imperatore dei Francesi", image: "assets/img/people/napoleone-iii.svg", imageAlt: "Ritratto didattico originale di Napoleone III", bio: "Vide con crescente timore l'espansione prussiana. La crisi spagnola e la dichiarazione di guerra portarono a Sedan e alla caduta dell'Impero.", idea: "La Francia fu manipolata nella crisi di Ems, ma conservò responsabilità e margini di scelta." },
    { id: "windthorst", name: "Ludwig Windthorst", dates: "1812-1891", role: "Leader del Zentrum cattolico", image: "assets/img/people/windthorst.svg", imageAlt: "Ritratto didattico originale di Ludwig Windthorst", bio: "Giurista hannoveriano e avversario parlamentare di Bismarck, difese cattolici, federalismo e minoranze.", idea: "Anche senza governo parlamentare, partiti e Reichstag potevano limitare la politica del cancelliere." },
    { id: "gorcakov", name: "Aleksandr Gorčakov", dates: "1798-1883", role: "Ministro degli Esteri russo", image: "assets/img/people/gorcakov.svg", imageAlt: "Ritratto didattico originale di Aleksandr Gorcakov", bio: "Interlocutore e rivale diplomatico di Bismarck, cercò di restaurare la posizione russa dopo la guerra di Crimea.", idea: "L'equilibrio dipendeva da attori che non accettavano di essere pedine del sistema tedesco." },
    { id: "guglielmo-ii", name: "Guglielmo II", dates: "1859-1941", role: "Imperatore tedesco dal 1888", image: "assets/img/people/guglielmo-ii.svg", imageAlt: "Ritratto didattico originale di Guglielmo II", bio: "Volle governare personalmente e si scontrò con Bismarck su politica sociale, leggi antisocialiste e autorità. Nel 1890 lo costrinse alle dimissioni.", idea: "Un sistema troppo dipendente da un uomo diventa fragile quando cambia il vertice monarchico." }
  ],
  timeline: [
    { date: "1815", title: "Confederazione germanica", text: "Trentanove Stati sovrani coordinati da una Dieta presieduta dall'Austria.", scale: "Germania" },
    { date: "1819", title: "Decreti di Karlsbad", text: "Censura e controllo delle università reprimono liberalismo e nazionalismo.", scale: "Società" },
    { date: "1834", title: "Zollverein", text: "L'unione doganale guidata dalla Prussia integra il mercato escludendo l'Austria.", scale: "Economia" },
    { date: "1848-1849", title: "Parlamento di Francoforte", text: "L'unità costituzionale fallisce dopo il rifiuto della corona.", scale: "Parlamento" },
    { date: "1850", title: "Costituzione prussiana", text: "Rappresentanza e prerogativa regia convivono con le tre classi.", scale: "Prussia" },
    { date: "23 set. 1862", title: "Bismarck al governo", text: "La Corona affida a Bismarck la crisi sulla riforma militare.", scale: "Prussia" },
    { date: "1864", title: "Guerra dei ducati", text: "Prussia e Austria sconfiggono la Danimarca.", scale: "Europa" },
    { date: "3 lug. 1866", title: "Sadowa", text: "La vittoria prussiana esclude l'Austria dalla riorganizzazione tedesca.", scale: "Europa" },
    { date: "1867", title: "Confederazione del Nord", text: "Ventidue Stati formano uno Stato federale sotto presidenza prussiana.", scale: "Germania" },
    { date: "13 lug. 1870", title: "Dispaccio di Ems", text: "La pubblicazione abbreviata trasforma la crisi in conflitto d'onore.", scale: "Diplomazia" },
    { date: "2 set. 1870", title: "Sedan", text: "Napoleone III si arrende; la Repubblica continua la guerra.", scale: "Europa" },
    { date: "18 gen. 1871", title: "Proclamazione del Reich", text: "Guglielmo I diventa imperatore tedesco a Versailles.", scale: "Germania" },
    { date: "16 apr. 1871", title: "Costituzione imperiale", text: "Federalismo, Reichstag eletto e forte esecutivo definiscono il Reich.", scale: "Parlamento" },
    { date: "1873-1878", title: "Kulturkampf", text: "Lo Stato tenta di subordinare il cattolicesimo e rafforza il Zentrum.", scale: "Società" },
    { date: "1878", title: "Congresso e legge antisocialista", text: "Bismarck media a Berlino e restringe le organizzazioni socialiste.", scale: "Europa" },
    { date: "1879", title: "Duplice e protezionismo", text: "Alleanza con Vienna e dazi segnano una svolta.", scale: "Diplomazia" },
    { date: "1882", title: "Triplice Alleanza", text: "L'Italia entra nell'alleanza di Germania e Austria-Ungheria.", scale: "Diplomazia" },
    { date: "1883-1889", title: "Assicurazioni sociali", text: "Malattia, infortuni, invalidità e vecchiaia diventano rischi pubblici.", scale: "Società" },
    { date: "1884-1885", title: "Svolta coloniale", text: "La Germania acquisisce protettorati e ospita la Conferenza di Berlino.", scale: "Imperi" },
    { date: "1887", title: "Controassicurazione", text: "Germania e Russia promettono neutralità con precise eccezioni.", scale: "Diplomazia" },
    { date: "mar. 1890", title: "Caduta di Bismarck", text: "Il conflitto con Guglielmo II conclude la sua direzione politica.", scale: "Germania" },
    { date: "1891-1894", title: "Alleanza franco-russa", text: "La Francia esce dall'isolamento e aumenta il rischio di due fronti.", scale: "Europa" }
  ],
  maps: [
    { title: "Dalla Confederazione al Reich", image: "assets/img/maps/germania-1815-1871.svg", alt: "Schema in quattro fasi dalla Confederazione germanica al Reich", text: "Cambiano soggetto politico, confini della Germania e rapporto con l'Austria.", note: "Schema concettuale, non carta di confine in scala." },
    { title: "Tre guerre, tre trasformazioni", image: "assets/img/maps/tre-guerre.svg", alt: "Sequenza delle guerre del 1864, 1866 e 1870-1871", text: "Ogni guerra risolve un problema e ne apre un altro: ducati, egemonia, integrazione del Sud.", note: "Le frecce indicano nessi politici, non inevitabilità." },
    { title: "La costituzione a due legittimità", image: "assets/img/maps/costituzione-reich.svg", alt: "Diagramma di imperatore, cancelliere, Bundesrat e Reichstag", text: "Principi ed elettori partecipano alla legislazione, ma la formazione del governo resta monarchica.", note: "Diagramma dei poteri essenziali del 1871." },
    { title: "L'incubo delle coalizioni", image: "assets/img/maps/alleanze.svg", alt: "Rete delle alleanze bismarckiane", text: "Isolare la Francia richiede di legare Vienna senza perdere San Pietroburgo.", note: "Schema delle funzioni prevalenti; ogni trattato aveva clausole specifiche." }
  ],
  sources: [
    { id: "francoforte", title: "Rivoluzione e Assemblea nazionale di Francoforte", type: "Ricostruzione istituzionale", date: "1848-1849", author: "Deutscher Bundestag", provenance: "Storia del parlamentarismo", verbatim: false, excerpt: ["L'assemblea progettò una monarchia costituzionale federale con rappresentanza popolare.", "La soluzione piccolo-tedesca prevalse nel marzo 1849.", "Il rifiuto della corona rese evidente l'assenza di forza esecutiva autonoma."], context: "Tentativo rivoluzionario di creare uno Stato nazionale e costituzionale.", audience: "Cittadini, studenti e visitatori del Parlamento tedesco.", purpose: "Ricostruire il primo grande esperimento parlamentare nazionale.", limits: "La sintesi istituzionale non restituisce tutte le correnti sociali e regionali.", interpretation: "Il fallimento riguardò legittimità, esercito e potere dei principi.", questions: ["Quale forma di Stato proponeva?", "Perché la corona era decisiva?", "Quali mezzi mancavano?"], url: "https://www.bundestag.de/parlament/geschichte/parlamentarismus/1848" },
    { id: "ferro-sangue", title: "Il discorso del ferro e del sangue", type: "Discorso politico", date: "30 settembre 1862", author: "Otto von Bismarck", provenance: "German History in Documents and Images, GHI", verbatim: false, excerpt: ["Bismarck discute il diritto di bilancio e il conflitto fra Corona e Camera.", "Rimprovera ai liberali di non tradurre l'obiettivo nazionale in forza statale.", "La formula ferro e sangue chiude un intervento alla commissione del bilancio."], context: "Crisi costituzionale sulla riforma dell'esercito prussiano.", audience: "Commissione del bilancio della Camera prussiana.", purpose: "Difendere la riforma militare e la posizione del governo.", limits: "Il verbale non è un piano operativo delle guerre future.", interpretation: "La fonte lega questione nazionale e conflitto costituzionale.", questions: ["Qual è il conflitto immediato?", "A chi parla?", "Che cosa aggiunge la lettura retrospettiva?"], url: "https://germanhistorydocs.org/en/from-vormaerz-to-prussian-dominance-1815-1866/excerpt-from-bismarcks-blood-and-iron-speech-1862" },
    { id: "vienna-1864", title: "Pace di Vienna e questione dei ducati", type: "Trattato internazionale", date: "30 ottobre 1864", author: "Danimarca, Prussia e Austria", provenance: "Cronologia GHDI", verbatim: false, excerpt: ["La Danimarca rinuncia ai diritti sui ducati.", "I territori passano alle due potenze vincitrici.", "Gastein distribuisce l'amministrazione senza risolvere la sovranità."], context: "Conclusione della guerra contro la Danimarca.", audience: "Governi e corti europee.", purpose: "Terminare la guerra e trasferire i diritti.", limits: "Il linguaggio statale non rappresenta direttamente le popolazioni miste.", interpretation: "Il trattato chiude un conflitto e ne crea uno fra i vincitori.", questions: ["Che cosa viene trasferito?", "Chi non firma?", "Perché la gestione è instabile?"], url: "https://germanhistorydocs.org/en/teaching/forging-an-empire-chronology" },
    { id: "nikolsburg", title: "Preliminare di Nikolsburg", type: "Trattato di pace", date: "26 luglio 1866", author: "Prussia e Austria", provenance: "German History in Documents and Images", verbatim: false, excerpt: ["L'integrità territoriale austriaca viene preservata.", "L'Austria riconosce lo scioglimento della Confederazione.", "La Germania potrà essere riorganizzata senza Vienna."], context: "Dopo la vittoria prussiana di Sadowa.", audience: "Sovrani, governi e diplomazie.", purpose: "Fissare le condizioni politiche della pace.", limits: "Non descrive costi sociali né il punto di vista degli Stati annessi.", interpretation: "La moderazione territoriale serve l'esclusione politica dell'Austria.", questions: ["Che cosa conserva l'Austria?", "A che cosa rinuncia?", "Perché il risultato basta a Bismarck?"], url: "https://germanhistorydocs.org/en/forging-an-empire-bismarckian-germany-1866-1890/preliminary-peace-of-nikolsburg-july-26-1866" },
    { id: "ems", title: "Versioni originale e pubblicata del dispaccio di Ems", type: "Comunicazione diplomatica", date: "13 luglio 1870", author: "Heinrich Abeken, Guglielmo I e Bismarck", provenance: "German History in Documents and Images", verbatim: false, excerpt: ["Il rapporto originale contiene formule contestuali.", "La versione abbreviata elimina elementi concilianti.", "La modifica orienta le reazioni senza inventare richiesta e rifiuto."], context: "Crisi sulla candidatura Hohenzollern in Spagna.", audience: "Prima il cancelliere; poi stampa e opinione pubblica.", purpose: "Informare nell'originale; produrre un effetto politico nella pubblicazione.", limits: "Il documento non determina da solo tutte le cause della guerra.", interpretation: "La selezione di fatti veri può cambiare il significato pubblico.", questions: ["Che cosa viene omesso?", "Come cambia il tono?", "Chi decide la guerra?"], url: "https://germanhistorydocs.org/en/forging-an-empire-bismarckian-germany-1866-1890/original-and-edited-versions-of-the-ems-dispatch-july-13-1870" },
    { id: "costituzione-1871", title: "Costituzione dell'Impero tedesco", type: "Costituzione", date: "16 aprile 1871", author: "Imperatore, Bundesrat e Reichstag", provenance: "Deutscher Bundestag", verbatim: false, excerpt: ["Il Bundesrat rappresenta i governi federati.", "Il Reichstag eletto partecipa a leggi e bilancio.", "Il cancelliere è nominato dall'imperatore."], context: "Istituzionalizzazione del Reich nato dalla guerra.", audience: "Stati federati, istituzioni e cittadini.", purpose: "Definire competenze e organi federali.", limits: "I poteri formali non descrivono da soli prassi e influenza dei partiti.", interpretation: "Il sistema combina rappresentanza democratica e predominio monarchico.", questions: ["Chi nomina il cancelliere?", "Chi approva le leggi?", "Perché il Reichstag è reale ma non sovrano?"], url: "https://www.bundestag.de/parlament/geschichte/parlamentarismus/kaiserreich/kaiserreich-199616" },
    { id: "politica-sociale", title: "Legge antisocialista e messaggio sociale", type: "Legge e proclama", date: "1878-1881", author: "Reichstag, Bundesrat e Guglielmo I", provenance: "German History in Documents and Images", verbatim: false, excerpt: ["La legge vieta organizzazioni, riunioni e stampa socialiste.", "Il messaggio chiede misure positive per i lavoratori.", "Repressione e assicurazione procedono nello stesso progetto statale."], context: "Crescita socialista e attentati del 1878.", audience: "Amministrazioni, lavoratori, Parlamento e opinione pubblica.", purpose: "Limitare il movimento e rafforzare la lealtà allo Stato.", limits: "Le intenzioni non misurano coperture, costi e repressione.", interpretation: "La contraddizione è apparente osservando l'obiettivo conservatore comune.", questions: ["Quali libertà vengono limitate?", "Quali rischi riconosciuti?", "Perché la SPD cresce?"], url: "https://germanhistorydocs.org/en/forging-an-empire-bismarckian-germany-1866-1890/kaiser-wilhelm-i-s-royal-proclamation-on-social-policy-november-17-1881" },
    { id: "controassicurazione", title: "Trattato di controassicurazione", type: "Trattato segreto", date: "18 giugno 1887", author: "Germania e Russia", provenance: "German History in Documents and Images", verbatim: false, excerpt: ["Le potenze promettono neutralità benevola.", "La garanzia non vale per un attacco tedesco alla Francia o russo all'Austria.", "Il protocollo segreto complica la compatibilità con Vienna."], context: "Scadenza dell'intesa dei Tre Imperatori.", audience: "I governi contraenti.", purpose: "Evitare l'avvicinamento franco-russo e due fronti.", limits: "Il testo definisce obblighi formali, non percezioni e crisi future.", interpretation: "La segretezza permette flessibilità e rende fragile la continuità.", questions: ["Quando vale la neutralità?", "Quali eccezioni?", "Perché il mancato rinnovo conta?"], url: "https://germanhistorydocs.org/en/forging-an-empire-bismarckian-germany-1866-1890/secret-reinsurance-treaty-with-russia-june-18-1887" }
  ],
  workshop: [
    { title: "Distingui le condizioni", prompt: "Quale fattore esisteva prima di Bismarck?", options: ["Zollverein e nazionalismo", "Un piano completo di tre guerre", "Un Reich già istituito"] },
    { title: "Valuta la svolta", prompt: "Che cosa decide davvero il 1866?", options: ["La forma repubblicana", "L'esclusione dell'Austria", "La fine di ogni autonomia"] },
    { title: "Definisci il regime", prompt: "Quale formula descrive meglio il Reich?", options: ["Assolutismo senza Parlamento", "Democrazia parlamentare", "Federalismo rappresentativo a prevalenza monarchica"] },
    { title: "Costruisci il giudizio", prompt: "Quale tesi tiene insieme risultati e limiti?", options: ["Culto del grande uomo", "Unità dall'alto e modernizzazione autoritaria", "Processo economico automatico"] }
  ],
  quiz: [
    { q: "Che cos'era la Confederazione germanica?", options: ["Uno Stato unitario", "Unione di Stati sovrani presieduta dall'Austria", "Una repubblica", "Un'alleanza solo prussiana"], answer: 1, why: "Coordinava Stati sovrani e non possedeva un governo nazionale.", recover: "Rivedi la lezione 1.", lesson: "germania-prima" },
    { q: "Perché lo Zollverein non basta a spiegare l'unità?", options: ["Integrò mercati ma non eliminò sovranità", "Creò subito l'imperatore", "Comprendeva l'Austria", "Abolì gli eserciti"], answer: 0, why: "L'integrazione rafforzò la Prussia, ma la decisione politica restava aperta.", recover: "Distingui mercato e Stato.", lesson: "germania-prima" },
    { q: "Perché fallì Francoforte?", options: ["Non scrisse una costituzione", "Non ebbe forza per imporla ai principi", "Scelse la repubblica austriaca", "Fu sciolta da Bismarck"], answer: 1, why: "Deliberò una costituzione, ma dipendeva dai poteri dinastici.", recover: "Riapri la fonte.", lesson: "germania-prima" },
    { q: "Qual era il centro del conflitto prussiano?", options: ["La bandiera", "Bilancio e controllo dell'esercito", "Le colonie", "Il voto femminile"], answer: 1, why: "Camera e Corona si scontrarono sulle spese militari.", recover: "Rileggi la lezione 2.", lesson: "crisi-prussiana" },
    { q: "Che cosa NON prova il discorso del 1862?", options: ["Il conflitto con i liberali", "La centralità dell'esercito", "Un piano dettagliato delle tre guerre", "La preferenza per la forza statale"], answer: 2, why: "La sequenza futura è una ricostruzione retrospettiva.", recover: "Distingui fonte e mito.", lesson: "crisi-prussiana" },
    { q: "Perché i ducati non furono un puro pretesto?", options: ["Esistevano problemi dinastici, giuridici e nazionali", "La Danimarca invase Berlino", "Non c'erano abitanti", "Erano già prussiani"], answer: 0, why: "Status e nazionalismi concorrenti rendevano reale la crisi.", recover: "Rivedi la lezione 3.", lesson: "ducati" },
    { q: "Che cosa stabilì Gastein?", options: ["Distruzione dell'Austria", "Amministrazione separata dei ducati", "Alleanza franco-prussiana", "Nascita del Reich"], answer: 1, why: "Divise l'amministrazione senza risolvere la sovranità.", recover: "Segui 1864-1865.", lesson: "ducati" },
    { q: "Che cosa contribuì alla vittoria del 1866?", options: ["Una sola arma", "Comando, logistica, ferrovie e tecnologia", "L'intervento francese", "La resa italiana"], answer: 1, why: "La vittoria derivò da una combinazione organizzativa e militare.", recover: "Rivedi la lezione 4.", lesson: "guerra-austria" },
    { q: "Perché la pace con l'Austria fu moderata?", options: ["Per una futura collaborazione", "La Prussia aveva perso", "L'Austria entrò nel Reich", "Lo impose l'Italia"], answer: 0, why: "L'obiettivo era escludere Vienna senza farne un nemico permanente.", recover: "Apri Nikolsburg.", lesson: "guerra-austria" },
    { q: "Che cosa fece Bismarck al dispaccio?", options: ["Inventò l'ambasciatore", "Lo abbreviò rendendolo tagliente", "Dichiarò guerra", "Lo mantenne segreto"], answer: 1, why: "Omissioni e montaggio cambiarono il tono.", recover: "Confronta le versioni.", lesson: "francia-reich" },
    { q: "Chi dichiarò guerra nel luglio 1870?", options: ["La Francia", "La Prussia", "L'Austria", "La Spagna"], answer: 0, why: "La scelta francese completò l'escalation.", recover: "Distingui provocazione e decisione.", lesson: "francia-reich" },
    { q: "Quando fu proclamato il Reich?", options: ["18 gennaio 1871", "3 luglio 1866", "30 settembre 1862", "10 maggio 1871"], answer: 0, why: "Guglielmo I fu proclamato a Versailles.", recover: "Rivedi la timeline.", lesson: "francia-reich" },
    { q: "Quale potere aveva il Reichstag?", options: ["Nessuno", "Approvava leggi e bilancio", "Nominava l'imperatore", "Comandava l'esercito"], answer: 1, why: "Era necessario alla legislazione pur non formando il governo.", recover: "Riapri il diagramma.", lesson: "costituzione-reich" },
    { q: "Da chi dipendeva il cancelliere?", options: ["Dal Reichstag", "Dall'imperatore", "Da Vienna", "Dagli elettori direttamente"], answer: 1, why: "La responsabilità dell'esecutivo era monarchica.", recover: "Distingui elezione e governo.", lesson: "costituzione-reich" },
    { q: "Effetto del Kulturkampf?", options: ["Scomparsa del Zentrum", "Rafforzamento cattolico", "Fine del federalismo", "Conversione di Bismarck"], answer: 1, why: "La repressione aumentò la mobilitazione del Zentrum.", recover: "Rivedi la lezione 6.", lesson: "costituzione-reich" },
    { q: "La legge antisocialista impedì ogni candidatura?", options: ["Sì", "No, vietò organizzazioni e stampa", "Solo in Baviera", "Solo dopo il 1890"], answer: 1, why: "La presenza elettorale rimase possibile.", recover: "Rileggi la lezione 7.", lesson: "stato-sociale" },
    { q: "Quale assicurazione arrivò per prima?", options: ["Malattia nel 1883", "Vecchiaia nel 1871", "Disoccupazione nel 1862", "Maternità nel 1848"], answer: 0, why: "La sequenza iniziò con la malattia.", recover: "Rivedi la cronologia.", lesson: "stato-sociale" },
    { q: "Perché protezione e repressione erano complementari?", options: ["Rafforzavano lo Stato e indebolivano la SPD", "Erano socialiste", "Non furono applicate", "Abolivano la monarchia"], answer: 0, why: "Appartenevano allo stesso progetto conservatore.", recover: "Confronta le fonti.", lesson: "stato-sociale" },
    { q: "Obiettivo della controassicurazione?", options: ["Alleanza franco-russa", "Neutralità russa e prevenzione dei due fronti", "Distruzione dell'Austria", "Conquista britannica"], answer: 1, why: "Bismarck voleva legare Vienna senza perdere la Russia.", recover: "Apri la rete.", lesson: "equilibrio-eredita" },
    { q: "Quale giudizio è più preciso?", options: ["Bismarck creò tutto da solo", "L'unità fu automatica", "Trasformò condizioni precedenti in unità a guida monarchico-prussiana", "Il Reich fu subito parlamentare"], answer: 2, why: "La tesi integra strutture, scelte e forma del risultato.", recover: "Costruisci la tesi finale.", lesson: "equilibrio-eredita" }
  ]
};
window.HIST_DATA.lessons.sort((a, b) => a.number - b.number);
