(() => {
 'use strict';
 const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
 const root=document.body.dataset.root||'./',id=document.body.dataset.lesson,KEY='gbprof-goldoni-v1';
 const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const slug=s=>s.toLowerCase().normalize('NFD').replace(/[^\x00-\x7F]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
 let state={lessons:{},font:1.12},timer,storageOK=true;
 try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved&&typeof saved==='object'&&saved.lessons&&typeof saved.lessons==='object')state={...state,...saved};}catch{}
 const say=text=>{const n=$('#notice');if(!n)return;n.textContent=text;n.classList.add('visible');clearTimeout(timer);timer=setTimeout(()=>n.classList.remove('visible'),4000)};
 const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true;return true}catch{storageOK=false;say('Il browser non permette il salvataggio. Scarica gli appunti prima di uscire.');return false}};
 const lesson=n=>{if(!state.lessons[n]||typeof state.lessons[n]!=='object')state.lessons[n]={};const l=state.lessons[n];if(!Array.isArray(l.attempts))l.attempts=[];if(!Array.isArray(l.highlights))l.highlights=[];if(!Array.isArray(l.citations))l.citations=[];if(typeof l.notes!=='string')l.notes='';if(!l.recovery||typeof l.recovery!=='object')l.recovery={};return l};
 const download=(name,text)=>{const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 const titles=['Il mondo precedente','Le fratture','L’immagine del mondo','La poetica','Le opere: La locandiera','Conclusione'];
 const slugs=['mondo-precedente','fratture','immagine-del-mondo','poetica','opere','conclusione'];
 const dlg=$('#map-dialog');let previousFocus;
 function closeMap(){if(!dlg)return;if(dlg.close)dlg.close();else{dlg.removeAttribute('open');dlg.classList.remove('no-dialog')}previousFocus?.focus()}
 $$('[data-map]').forEach(b=>b.addEventListener('click',()=>{previousFocus=b;const img=$('#zoomed-map');img.src=b.dataset.map;img.alt=b.dataset.description;img.style.width='100%';$('#map-description').textContent=b.dataset.description;$('#map-zoom').value='100';$('#map-download').href=b.dataset.map;if(dlg.showModal)dlg.showModal();else{dlg.setAttribute('open','');dlg.classList.add('no-dialog')}$('.map-viewport')?.scrollTo(0,0)}));
 $('[data-close-dialog]')?.addEventListener('click',closeMap);
 dlg?.addEventListener('click',e=>{if(e.target===dlg)closeMap()});
 dlg?.addEventListener('close',()=>previousFocus?.focus());
 $('#map-zoom')?.addEventListener('input',e=>{$('#zoomed-map').style.width=e.target.value+'%'});
 const scenes={citta:['IL MONDO PRECEDENTE','Nascere in un ruolo. Essere giudicati nelle azioni.','A Venezia rango, denaro e reputazione non coincidono. Osserva la città da cui nasce la domanda di Goldoni.','Entra nella città →','mondo-precedente'],teatro:['LA POETICA','La vita offre la materia. Il teatro le dà forma.','Autore, attori e pubblico trasformano insieme la commedia. Esplora il passaggio dalla maschera al carattere e dal canovaccio al copione.','Entra nel teatro →','poetica'],locanda:['LE OPERE','Mirandolina dirige la recita. Ma può dirigerne l’esito?','Una locanda riunisce titolo, denaro e lavoro. Segui la conquista del Cavaliere e il momento in cui la vittoria diventa pericolo.','Entra nella locanda →','opere']};
 $$('[data-scene]').forEach(b=>b.addEventListener('click',()=>{const s=scenes[b.dataset.scene];$$('[data-scene]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));['kicker','title','text'].forEach((x,i)=>$('#scene-'+x).textContent=s[i]);$('#scene-link').textContent=s[3];$('#scene-link').href='lezioni/'+s[4]+'.html';$('.cover').dataset.scene=b.dataset.scene;}));
 function updateHome(){let read=0;$$('[data-step-card]').forEach(c=>{const l=lesson(c.dataset.stepCard);if(l.read)read++;c.classList.toggle('is-read',!!l.read);$('.step-state',c).textContent=l.read?'✓ Letto':l.visited?'Lettura iniziata':'Da esplorare'});if($('#course-progress')){$('#course-progress').value=read;$('#progress-label').textContent=read+' di 6 step letti'}if(state.last&&slugs[state.last-1]&&$('#resume')){const l=lesson(state.last);$('#resume').hidden=false;$('#resume').href='lezioni/'+slugs[state.last-1]+'.html'+(l.anchor?'#'+l.anchor:'');$('#resume').textContent='Riprendi: '+titles[state.last-1]+' →'}}
 if(document.body.dataset.page==='home')updateHome();
 const notebookText=(l)=>l.notes+'\n\nCITAZIONI DALLA LEZIONE\n'+(l.citations||[]).map(c=>'«'+c.text+'»\n'+c.source).join('\n\n');
 $('#export-all')?.addEventListener('click',()=>download('Goldoni-tutti-gli-appunti.txt',titles.map((t,i)=>`${i+1}. ${t}\n\n${notebookText(lesson(i+1))}\n`).join('\n────────────\n\n')));
 $('#reset-data')?.addEventListener('click',()=>{if(confirm('Cancellare appunti, evidenziature, letture e risultati di Goldoni su questo dispositivo?')){try{localStorage.removeItem(KEY);state={lessons:{},font:1.12};location.reload()}catch{say('Il browser non consente di cancellare i dati. Usa le impostazioni del sito.')}}});
 if(id){
  const l=lesson(id);l.visited=true;state.last=Number(id);save();
  document.documentElement.style.setProperty('--reading',Math.max(1,Math.min(1.6,Number(state.font)||1.12))+'rem');
  const panelNames={verifica:'test',appunti:'appunti',sintesi:'sintesi',saperi:'saperi',vocabolario:'vocabolario',mappa:'mappa',lezione:'lezione'};
  function tab(name,changeHash=true){const review=$('#learning-dialog');if(name==='appunti'||name==='mappa'){review?.close();window.GoldoniWorkspace?.side(name==='appunti'?'notes':'visual');}else if(name==='lezione'){review?.close();window.GoldoniWorkspace?.read();}else if($('[data-panel="'+name+'"]')){$$('[data-panel]').forEach(p=>p.hidden=p.dataset.panel!==name);$$('[data-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tab===name)));if(review&&!review.open)review.showModal();}else name='lezione';l.panel=name;if(changeHash)history.replaceState(null,'','#'+(name==='test'?'verifica':name));save();}
  window.GoldoniStudy={tab};
  $$('[data-tab]').forEach(b=>b.addEventListener('click',()=>tab(b.dataset.tab)));
  function route(){const h=decodeURIComponent(location.hash.slice(1));if(panelNames[h])tab(panelNames[h],false);else if(h&&document.getElementById(h)){tab('lezione',false);requestAnimationFrame(()=>document.getElementById(h).scrollIntoView())}else tab(l.panel||'lezione',false)}
  window.addEventListener('hashchange',route);window.addEventListener('goldoni-workspace-ready',route);
  function setFont(delta){state.font=Math.round(Math.max(1,Math.min(1.6,(Number(state.font)||1.12)+delta))*100)/100;document.documentElement.style.setProperty('--reading',state.font+'rem');save()}
  $('#font-minus').addEventListener('click',()=>setFont(-.08));$('#font-plus').addEventListener('click',()=>setFont(.08));
  $('#focus-toggle').addEventListener('click',e=>{const on=document.body.classList.toggle('focus-mode');e.currentTarget.setAttribute('aria-pressed',String(on));e.currentTarget.textContent=on?'Esci dalla modalità lettura':'Modalità lettura'});
  const readButton=$('#read-toggle');function readLabel(){readButton.textContent=l.read?'✓ Letto · annulla':'Segna come letto';readButton.setAttribute('aria-pressed',String(!!l.read))}readLabel();readButton.addEventListener('click',()=>{l.read=!l.read;readLabel();save()});
  const notes=$('#notes');notes.value=l.notes;$('#note-status').textContent=storageOK?'Salvataggio automatico su questo dispositivo.':'Salvataggio non disponibile.';
  notes.addEventListener('input',()=>{l.notes=notes.value;const ok=save();$('#note-status').textContent=ok?'Appunti salvati su questo dispositivo.':'Appunti non salvati: usa «Scarica gli appunti».'});
  $('#download-notes').addEventListener('click',()=>download('Goldoni-step-'+id+'-appunti.txt',titles[id-1]+'\n\n'+notebookText(l)));
  const reading=$('#reading-text');let selected=null;
  document.addEventListener('selectionchange',()=>{const selection=getSelection();const bar=$('.focus-selection-tools');if(!selection||selection.isCollapsed||!selection.rangeCount){if(bar)bar.hidden=true;return}const r=selection.getRangeAt(0);if(!reading.contains(r.startContainer)||!reading.contains(r.endContainer)){if(bar)bar.hidden=true;return}const pre=document.createRange();pre.selectNodeContents(reading);pre.setEnd(r.startContainer,r.startOffset);selected={start:pre.toString().length,end:pre.toString().length+r.toString().length,text:r.toString()};if(bar)bar.hidden=false});
  $$('.focus-selection-tools button').forEach(b=>b.addEventListener('pointerdown',e=>e.preventDefault()));
  function applyHighlights(){ $$('mark',reading).forEach(m=>m.replaceWith(...m.childNodes));reading.normalize();const walker=document.createTreeWalker(reading,NodeFilter.SHOW_TEXT);let node,pos=0;const nodes=[];while(node=walker.nextNode()){nodes.push({node,start:pos,end:pos+node.length});pos+=node.length}for(const {node,start,end} of nodes.reverse()){const ranges=l.highlights.filter(h=>h.start<end&&h.end>start).sort((a,b)=>b.start-a.start);for(const h of ranges){const a=Math.max(h.start-start,0),b=Math.min(h.end-start,node.length);if(a>=b)continue;const range=document.createRange();range.setStart(node,a);range.setEnd(node,b);const mark=document.createElement('mark');range.surroundContents(mark);}}}
  function currentSelection(){if(!selected||!selected.text.trim()){say('Seleziona prima un passo della lezione.');return null}return selected}
  function renderCitations(){const list=$('#citation-list');if(!list)return;list.innerHTML=l.citations.map((c,i)=>`<article class="citation-card"><q>${escape(c.text)}</q><small>${escape(c.source)}</small><button data-remove-citation="${i}" aria-label="Rimuovi questa citazione">×</button></article>`).join('');$('#empty-citations').hidden=l.citations.length>0;const text=reading.textContent;const waiting=l.highlights.filter(h=>!l.citations.some(c=>c.text===text.slice(h.start,h.end).trim()));$('#highlight-count').textContent=waiting.length;$('#paste-highlights').disabled=!waiting.length;$('#clear-highlights').disabled=!l.highlights.length;}
  function addCitation(text){text=text.trim();if(text&&!l.citations.some(c=>c.text===text))l.citations.push({text,source:titles[id-1]});}
  $('#highlight').addEventListener('click',()=>{const s=currentSelection();if(!s)return;l.highlights.push({start:s.start,end:s.end});l.highlights.sort((a,b)=>a.start-b.start);l.highlights=l.highlights.reduce((out,h)=>{const last=out[out.length-1];if(last&&h.start<=last.end)last.end=Math.max(last.end,h.end);else out.push({...h});return out},[]);applyHighlights();save();renderCitations();say('Passo evidenziato.');selected=null;$('.focus-selection-tools').hidden=true;getSelection()?.removeAllRanges()});
  $('#clear-highlights').addEventListener('click',()=>{l.highlights=[];applyHighlights();save();renderCitations();say('Evidenziature rimosse; citazioni conservate.');});
  $('#selection-note').addEventListener('click',()=>{const s=currentSelection();if(!s)return;addCitation(s.text);const ok=save();renderCitations();say(ok?'Passo aggiunto alle citazioni del taccuino.':'Passo aggiunto: scarica gli appunti per conservarlo.');selected=null;$('.focus-selection-tools').hidden=true;getSelection()?.removeAllRanges()});
  $('#paste-highlights').addEventListener('click',()=>{const text=reading.textContent;l.highlights.forEach(h=>addCitation(text.slice(h.start,h.end)));save();renderCitations();say('Passaggi raccolti nelle citazioni del taccuino.');});
  $('#citation-list').addEventListener('click',e=>{const b=e.target.closest('[data-remove-citation]');if(!b)return;l.citations.splice(Number(b.dataset.removeCitation),1);save();renderCitations()});
  $('#clear-notes').addEventListener('click',()=>{if(confirm('Cancellare appunti e citazioni di questa lezione?')){l.notes='';l.citations=[];notes.value='';save();renderCitations();$('#note-status').textContent='Taccuino cancellato.';}});
  applyHighlights();renderCitations();
  const article=$('#panel-lezione');let progressTimer;
  article.addEventListener('scroll',()=>{clearTimeout(progressTimer);progressTimer=setTimeout(()=>{l.scrollTop=article.scrollTop;save()},150)},{passive:true});
  window.GoldoniStudy.resume=()=>{if(Number.isFinite(l.scrollTop))article.scrollTop=l.scrollTop;else if(l.anchor)document.getElementById(l.anchor)?.scrollIntoView({block:'start'})};
  if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>{const visible=entries.filter(e=>e.isIntersecting);if(visible.length){l.anchor=visible[0].target.id;const h=$('h2',visible[0].target);if(h&&$('#context-status'))$('#context-status').textContent='Collegato a: '+h.textContent;save()}},{root:article,rootMargin:'-15% 0px -60% 0px',threshold:0});$$('.reading-section').forEach(s=>observer.observe(s))}
  fetch(root+'assets/quizzes.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(all=>initQuiz(all[id],l)).catch(()=>{$('#quiz').innerHTML='<p>Le domande non sono disponibili. Ricarica la pagina con una connessione e attendi la preparazione offline.</p><button id="retry-load">Ricarica</button>';$('#retry-load').onclick=()=>location.reload()});
  function initQuiz(questions,l){
   let active=questions.map(q=>q.id),answers={},mode='completo';
   const last=l.attempts[l.attempts.length-1];if(last&&last.answers)answers={...last.answers};
   const score=a=>{const correct=questions.filter(q=>a[q.id]===q.correct).length;return {correct,total:questions.length,percent:Math.round(correct/questions.length*100),grade:Math.max(1,Math.round(correct/questions.length*10))}};
   function historyList(){$('#history-list').innerHTML=l.attempts.length?l.attempts.slice().reverse().map((a,index)=>{const s=score(a.answers);return `<div class="history-item"><strong>Tentativo ${l.attempts.length-index} · ${a.mode==='recupero'?'Recupero dei soli errori':'Verifica completa'}</strong>${new Date(a.date).toLocaleString('it-IT')} · ${s.correct}/${s.total} · voto ${s.grade}/10</div>`}).join(''):'<p>Nessun tentativo ancora concluso.</p>'}
   function form(){const subset=questions.filter(q=>active.includes(q.id));$('#quiz').innerHTML=`<form id="quiz-form"><p>${mode==='recupero'?'Recupero: '+subset.length+' domande da rivedere. Le risposte già corrette sono conservate.':'Rispondi a tutte le sei domande, poi correggi.'}</p>${subset.map((q,i)=>`<fieldset class="quiz-question" id="question-${q.id}"><legend>${i+1}. ${escape(q.question)}</legend>${q.options.map((o,j)=>`<label class="quiz-option"><input type="radio" name="q-${q.id}" value="${j}" ${answers[q.id]===j?'checked':''}><span>${String.fromCharCode(65+j)}. ${escape(o)}</span></label>`).join('')}<div class="feedback-slot"></div></fieldset>`).join('')}<button type="submit" class="primary">Correggi ${mode==='recupero'?'il recupero':'la verifica'}</button><p id="quiz-warning" role="alert"></p></form>`;
    $('#quiz-form').addEventListener('submit',e=>{e.preventDefault();const next={...answers};for(const q of subset){const checked=$(`input[name="q-${q.id}"]:checked`);if(!checked){$('#quiz-warning').textContent='Manca una risposta. Completa tutte le domande prima di correggere.';$(`input[name="q-${q.id}"]`).focus();return}next[q.id]=Number(checked.value)}answers=next;const attempt={date:new Date().toISOString(),mode,answers:{...answers},questions:[...active]};l.attempts.push(attempt);save();renderResult();historyList();$$('input,button[type=submit]',$('#quiz-form')).forEach(el=>el.disabled=true);$('#quiz-result').scrollIntoView({block:'start',behavior:'smooth'});});
   }
   function renderResult(){const s=score(answers),wrong=questions.filter(q=>answers[q.id]!==q.correct);
    questions.filter(q=>active.includes(q.id)).forEach(q=>{const slot=$(`#question-${q.id} .feedback-slot`);if(slot)slot.innerHTML=`<div class="quiz-feedback ${answers[q.id]===q.correct?'':'wrong'}"><strong>${answers[q.id]===q.correct?'✓ Risposta corretta':'Da rivedere · risposta corretta: '+String.fromCharCode(65+q.correct)}</strong><p>${escape(q.explanation)}</p></div>`});
    $('#quiz-result').innerHTML=`<div class="score"><h3>${s.correct} su ${s.total} · ${s.percent}%</h3><p>Voto: <strong>${s.grade}/10</strong>${mode==='recupero'?' · Risultato aggiornato dell’intera verifica':''}</p><p>${wrong.length?'Riprendi i '+wrong.length+' nessi qui sotto.':'Tutti i nessi sono corretti. Prova ora a spiegarli con parole tue.'}</p></div>${wrong.length?'<h3>Il recupero dei tuoi errori</h3>':''}${wrong.map(q=>`<section class="recovery"><h4>${escape(q.recovery.concept)}</h4><p><strong>La tua risposta:</strong> ${escape(q.options[answers[q.id]]||'Non risposta')}</p><p>${escape(q.recovery.clarification)}</p><p><strong>Un esempio:</strong> ${escape(q.recovery.example)}</p><a href="#${slug(q.anchor)}">Rileggi: ${escape(q.anchor)} →</a><p><strong>Prova di nuovo:</strong> ${escape(q.recovery.prompt)}</p><label for="recovery-${q.id}" class="small">La tua spiegazione</label><textarea id="recovery-${q.id}" data-recovery="${q.id}" rows="2">${escape(l.recovery[q.id]||'')}</textarea><details><summary>Confronta la tua spiegazione</summary><p>${escape(q.recovery.answer)}</p></details></section>`).join('')}<div class="quiz-actions">${wrong.length?'<button id="retry-errors">Rifai soltanto le domande sbagliate</button>':''}<button id="retry-all">Nuovo tentativo completo</button></div>`;
    $$('[data-recovery]').forEach(t=>t.addEventListener('input',()=>{l.recovery[t.dataset.recovery]=t.value;save()}));
    $('#retry-errors')?.addEventListener('click',()=>{active=wrong.map(q=>q.id);mode='recupero';for(const q of wrong)delete answers[q.id];$('#quiz-result').innerHTML='';form();$('#quiz').scrollIntoView({block:'start'});});
    $('#retry-all').addEventListener('click',()=>{active=questions.map(q=>q.id);answers={};mode='completo';$('#quiz-result').innerHTML='';form();$('#quiz').scrollIntoView({block:'start'});});
   }
   form();historyList();if(last){mode=last.mode;renderResult();$$('input,button[type=submit]',$('#quiz-form')).forEach(el=>el.disabled=true)}
  }
 }
 let installEvent;
 window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installEvent=e;if($('#install'))$('#install').hidden=false});
 $('#install')?.addEventListener('click',async()=>{if(installEvent){await installEvent.prompt();installEvent=null;$('#install').hidden=true}});
 const offline=$('#offline-status');
 if('serviceWorker'in navigator&&/^https?:$/.test(location.protocol)){
  navigator.serviceWorker.register(root+'sw.js',{scope:root}).then(()=>navigator.serviceWorker.ready).then(()=>{if(offline)offline.textContent='Lezioni e mappe pronte offline';}).catch(()=>{if(offline)offline.textContent='Uso online · preparazione offline non riuscita';});
 }else if(offline)offline.textContent='Apri il sito via HTTPS per attivare l’uso offline';
})();
