window.RA_TEXTS = {
  "lessons": {
    "colonie": [
      "Nel 1763 la maggior parte dei coloni non desidera fondare gli Stati Uniti. Si considera parte dell’Impero britannico e rivendica le libertà dei sudditi britannici. Proprio questa appartenenza rende esplosiva una domanda: chi deve decidere sulle imposte, sul commercio e sulle terre? La rivoluzione nascerà dentro un impero vittorioso, non dalla sua sconfitta.",
      "In sintesi: l’autogoverno locale può entrare in conflitto con l’autorità imperiale. Per comprendere la rottura bisogna ricostruire ciò che prima teneva insieme le colonie e Londra.",
      "Le tredici colonie occupano la costa atlantica: New Hampshire, Massachusetts (che comprende anche l’odierno Maine), Rhode Island e Connecticut nel New England; New York, New Jersey, Pennsylvania e Delaware nel Centro; Maryland, Virginia, North Carolina, South Carolina e Georgia nel Sud. Non sono ancora uno Stato unitario. Hanno origini religiose, statuti e istituzioni diversi: colonie regie, proprietarie o rette da carte con ampie autonomie.",
      "Le assemblee locali votano tributi e spese, mentre i governatori e le autorità imperiali difendono gli interessi della Corona. L’elettorato è ristretto e varia secondo la colonia: sesso, proprietà, condizione personale e talvolta religione limitano la partecipazione. Autogoverno non significa quindi democrazia universale.",
      "Nel New England agricoltura familiare, pesca, cantieristica e commercio si intrecciano. Nel Centro contano cereali, aziende agricole e porti come New York e Filadelfia. Nel Sud tabacco, riso e indaco alimentano economie di piantagione, accanto a piccoli coltivatori. Non bisogna proiettare qui il dominio ottocentesco del cotone. La schiavitù africana è presente e legalmente riconosciuta in tutte le tredici colonie alla vigilia della rivoluzione, con intensità e forme diverse. Mercanti settentrionali partecipano alla tratta atlantica e riforniscono le piantagioni caraibiche: Nord e Sud appartengono a reti economiche connesse.",
      "In sintesi: differenze regionali e legami atlantici convivono. La crescita di queste società aumenta anche la pressione sulle terre delle nazioni native.",
      "Il conflitto nordamericano tra Francia e Gran Bretagna comincia nel 1754; la Guerra dei Sette anni su scala europea si sviluppa dal 1756 al 1763. La vittoria britannica elimina il principale rivale coloniale in Canada, ma accresce debiti, costi militari e problemi di governo. Londra ritiene che le colonie debbano contribuire più direttamente alla difesa dell’impero; molti coloni ritengono invece di avere già sostenuto sacrifici.",
      "L’espansione degli insediamenti provoca resistenze native, tra cui la guerra legata a Pontiac. La Royal Proclamation del 1763 limita gli insediamenti oltre la linea degli Appalachi e riserva alla Corona la gestione degli acquisti di terre native. Non è la fine dell’espansione né il riconoscimento di una piena parità politica: è anche uno strumento per governare la frontiera e ridurre i conflitti.",
      "In sintesi: la pace apre due contese, sulle risorse fiscali e sulla terra. Entrambe pongono il problema di chi eserciti l’autorità.",
      "I ministri britannici vogliono ordine, entrate e controllo commerciale. Le élite coloniali vogliono difendere assemblee, affari e investimenti fondiari. I piccoli agricoltori possono desiderare nuove terre, ma non condividono tutti gli interessi dei grandi proprietari. Gli schiavizzati cercano spazi di libertà in una società che sfrutta il loro lavoro.",
      "Le nazioni native — fra cui Haudenosaunee, Cherokee e Shawnee — non sono un ostacolo indistinto sul cammino dei coloni. Sono società politiche con territori, relazioni diplomatiche e strategie differenti. Il colonialismo d’insediamento consiste nell’occupazione permanente delle loro terre e nella progressiva imposizione di un altro potere: implica guerre, trattati contestati, espulsioni e anche schiavizzazione indigena. Non si può ridurre a un movimento spontaneo “verso l’interno”.",
      "In sintesi: ciò che un colono chiama libertà di insediarsi può significare per una comunità nativa perdita di territorio e sovranità.",
      "Il Trattato di Parigi del 1763 ridisegna i possedimenti imperiali senza chiedere alle nazioni native di rinunciare consensualmente alle proprie terre. I nuovi confini sulle carte europee non cancellano quindi le sovranità e le resistenze locali. La proclamazione tenta di frenare l’occupazione occidentale, ma viene spesso violata.",
      "Parallelamente Londra prepara controlli doganali e provvedimenti fiscali più incisivi. Il rapporto imperiale cambia: pratiche locali a lungo tollerate vengono sottoposte a un controllo più stretto. La protesta cresce perché una società abituata a contrattare le decisioni incontra una pretesa di obbedienza più forte.",
      "In sintesi: non c’è ancora una scelta collettiva per l’indipendenza. Si sta però restringendo lo spazio del compromesso.",
      "Fonte da interrogare: Royal Proclamation, emanata da Giorgio III il 7 ottobre 1763, destinata a governatori, funzionari e sudditi. Il suo scopo è regolare l’assetto imperiale dopo la guerra. Nella scheda collegata trovi una spiegazione documentata e il riferimento istituzionale. Il linguaggio della Corona esprime il suo punto di vista, non quello delle nazioni native.",
      "Attività: confronta le aspettative di un investitore della Virginia e di una comunità nativa. Per ciascuno indica che cosa protegge la proclamazione e che cosa lascia irrisolto. Distingui sempre la norma scritta dalla sua applicazione concreta.",
      "In sintesi: una fonte politica mostra un progetto di governo; da sola non prova che quel progetto sia stato rispettato.",
      "La vittoria britannica rafforza l’impero sulla carta, ma ne rende più difficili i rapporti interni. I coloni non hanno più lo stesso bisogno di protezione contro la Francia; Londra ha maggiori spese e pretende maggiore disciplina. Le autonomie locali, il commercio e la terra diventano terreni di scontro.",
      "In sintesi: l’equilibrio precedente si incrina. La nuova politica fiscale trasformerà queste tensioni in mobilitazione.",
      "Una società abituata all’autogoverno può accettare decisioni comuni se riconosce chi le prende e come sono negoziate. Dopo il 1763 questo riconoscimento entra in crisi. I coloni non contestano inizialmente ogni autorità britannica: difendono spazi politici che sentono propri.",
      "Sintesi finale: le tredici colonie sono diverse ma connesse; dispongono di assemblee e partecipazione ristretta; condividono economie che impiegano lavoro schiavizzato; si espandono su territori nativi. La guerra modifica l’equilibrio imperiale. Il debito spinge Londra verso nuove entrate e la frontiera verso nuovi controlli. Nasce così il conflitto tra libertà coloniali, autorità britannica e sovranità native."
    ],
    "tasse": [
      "Una tassa può essere economicamente sopportabile e politicamente inaccettabile. La crisi americana non nasce soltanto dalla quantità di denaro richiesta: riguarda il diritto di imporre un tributo a persone che non eleggono deputati nel Parlamento di Westminster. Da una vertenza sulle entrate emerge un conflitto sulla rappresentanza.",
      "In sintesi: per capire la protesta occorre distinguere il peso fiscale dalla legittimità dell’autorità che lo impone.",
      "I coloni conoscono già dazi, vincoli commerciali e tributi locali. Le assemblee coloniali controllano una parte delle imposte interne. La Gran Bretagna, dopo il 1763, vuole invece rendere più efficiente il prelievo e finanziare la presenza militare. Il Parlamento si ritiene sovrano sull’intero impero.",
      "I sostenitori della politica britannica parlano di rappresentanza “virtuale”: i parlamentari rappresenterebbero l’interesse di tutti i sudditi, anche di chi non li elegge. I contestatori americani rivendicano il consenso espresso attraverso rappresentanti scelti nelle colonie. Non tutti propongono lo stesso rimedio, ma molti difendono il potere fiscale delle proprie assemblee.",
      "In sintesi: lo scontro nasce fra due concezioni incompatibili della rappresentanza e della sovranità.",
      "Il Sugar Act del 1764 riduce il dazio legale sulla melassa straniera rispetto alla normativa precedente, ma rafforza controlli e riscossione: non è soltanto un aumento di aliquote. Lo Stamp Act del 1765 impone una marca fiscale su documenti legali e stampati, raggiungendo attività quotidiane di avvocati, tipografi e commercianti. Le proteste e i boicottaggi contribuiscono alla sua abrogazione nel 1766.",
      "La vittoria non risolve il nodo: con il Declaratory Act il Parlamento ribadisce la propria autorità legislativa sulle colonie. I Townshend Acts del 1767 introducono dazi su merci importate, fra cui carta, vetro e tè, e riaprono il conflitto. La distinzione fra tasse interne e dazi non basta più a pacificare il rapporto.",
      "In sintesi: ogni concessione economica lascia aperta la domanda politica. La crisi riparte perché le due parti interpretano diversamente l’autorità parlamentare.",
      "Mercanti, artigiani, stampatori, associazioni come i Sons of Liberty e comitati di corrispondenza costruiscono reti di protesta. Anche le donne partecipano ai boicottaggi e alla produzione domestica di beni sostitutivi, pur restando quasi sempre escluse dalla rappresentanza formale. Altri coloni rifiutano la radicalizzazione e temono danni agli affari o disordine.",
      "Il 5 marzo 1770 soldati britannici uccidono cinque persone negli scontri di Boston. Il Boston Massacre diventa un evento di propaganda e memoria: immagini e racconti selezionano responsabilità e significati. John Adams difende in giudizio soldati accusati, mostrando che opposizione politica e garanzie processuali non coincidono con la richiesta di condanne automatiche.",
      "In sintesi: la mobilitazione costruisce solidarietà, ma le colonie restano attraversate da divisioni e scelte diverse.",
      "Nel 1770 vengono eliminati molti dazi Townshend, ma resta quello sul tè. Il Tea Act del 1773 non introduce una nuova tassa: conserva il dazio precedente e concede alla East India Company condizioni privilegiate per vendere direttamente nelle colonie attraverso agenti selezionati. Il tè può costare meno, ma comprarlo significa anche accettare il prelievo parlamentare; commercianti e contrabbandieri temono inoltre di perdere mercato.",
      "Il 16 dicembre 1773 a Boston i contestatori gettano in mare il tè. Alcuni adottano travestimenti e simboli associati ai Mohawk per celare la propria identità e rappresentare una distinzione americana. Non è un’azione compiuta dalla nazione Mohawk: la scelta dei simboli va spiegata, non confusa con l’identità dei partecipanti.",
      "Nel 1774 i Coercive Acts, definiti Intolerable Acts dagli oppositori, colpiscono Boston e l’autonomia del Massachusetts. Dodici colonie inviano delegati al Primo Congresso continentale a Filadelfia; la Georgia non partecipa. Il Congresso coordina il boicottaggio e le rivendicazioni, senza dichiarare ancora l’indipendenza.",
      "In sintesi: la repressione di una colonia favorisce una risposta intercoloniale. Una controversia locale diventa questione comune.",
      "Fonte da interrogare: i provvedimenti fiscali britannici, letti attraverso la ricostruzione dell’Office of the Historian, e il resoconto NPS del Boston Tea Party. Distingui la funzione di una legge da quella della protesta: la prima cerca entrate e controllo, la seconda delegittima quella pretesa di autorità.",
      "Attività: costruisci due argomenti di quattro righe. Un ministro sostiene che chi riceve protezione deve contribuire alle spese; un rappresentante coloniale risponde che il contributo deve essere consentito. Quale problema resta aperto anche abbassando il prezzo del tè?",
      "In sintesi: il prezzo di una merce e il principio politico incorporato nel suo acquisto possono spingere in direzioni opposte.",
      "Le colonie imparano a coordinarsi attraverso congressi, comitati, stampa e boicottaggi. La repressione rende più credibile la paura che Londra voglia svuotare le autonomie. Tuttavia nel 1774 molti desiderano ancora una riconciliazione basata sul riconoscimento dei diritti coloniali.",
      "In sintesi: la protesta produce istituzioni comuni prima di produrre uno Stato indipendente. Il passaggio alle armi renderà più difficile fermarsi.",
      "Il problema non è scegliere fra “soldi” e “idee”: interessi economici e principi politici si rafforzano reciprocamente. Il Tea Act lo mostra bene: un vantaggio di prezzo non rende legittima una tassa contestata.",
      "Sintesi finale: fra 1764 e 1774 la politica fiscale britannica incontra boicottaggi e mobilitazione. Il ritiro dello Stamp Act non chiude la disputa. I Townshend Acts, il Boston Massacre e il Tea Party aggravano la sfiducia. I Coercive Acts uniscono gli oppositori. Il Primo Congresso continentale crea un coordinamento comune, ancora aperto alla riconciliazione ma pronto a difendere le autonomie."
    ],
    "indipendenza": [
      "Nell’aprile 1775 inizia la guerra, ma l’indipendenza non è ancora un obiettivo condiviso. Per molti è possibile combattere i provvedimenti britannici e restare sudditi del re. In poco più di un anno questa posizione perde terreno. La rottura politica richiede una nuova giustificazione: non più soltanto difendere diritti dentro l’impero, ma fondare un’autorità fuori da esso.",
      "In sintesi: guerra e indipendenza sono due passaggi distinti. Le scelte del 1776 non erano già decise nel 1775.",
      "Il Primo Congresso ha coordinato le proteste, mentre milizie e autorità britanniche si preparano a un possibile scontro. In Massachusetts il controllo delle armi e dei rifornimenti diventa cruciale. Le assemblee e i comitati coloniali cominciano ad assumere compiti prima affidati alle strutture imperiali.",
      "Nella cultura politica coloniale si intrecciano tradizione dei diritti britannici, repubblicanesimo, religione e giusnaturalismo. Le idee illuministe non arrivano in un mondo vuoto: vengono selezionate e trasformate da esperienze locali di autogoverno.",
      "In sintesi: esistono risorse politiche e culturali per la rottura, ma resta da costruire un consenso sufficiente.",
      "Il 19 aprile 1775, a Lexington e Concord, reparti britannici e milizie coloniali si scontrano durante un’operazione volta a sequestrare armi. L’inizio delle ostilità cambia la scala della crisi. Il Secondo Congresso continentale si riunisce a maggio e a giugno crea il Continental Army, affidandone il comando a George Washington.",
      "La scelta di un comandante della Virginia contribuisce a rendere comune una guerra iniziata nel New England. Il Congresso tenta ancora una riconciliazione con la Olive Branch Petition; la Corona considera invece le colonie in ribellione. Combattere e negoziare restano per un periodo strategie contemporanee.",
      "In sintesi: la guerra costruisce un potere continentale e indebolisce, senza eliminarla subito, la speranza di riconciliazione.",
      "I patrioti favorevoli alla rottura non sono tutti i coloni. I lealisti restano fedeli alla Corona; altri cercano di evitare il conflitto o cambiano posizione. La rivoluzione è anche guerra civile fra vicini e parenti. Per gli schiavizzati, offerte di libertà legate al servizio militare possono aprire possibilità, sia nel campo britannico sia in quello americano, senza garantire un’emancipazione generale.",
      "Thomas Paine, immigrato britannico, pubblica Common Sense nel gennaio 1776. Attacca il principio ereditario della monarchia e rende pensabile una repubblica indipendente con un linguaggio destinato a un pubblico ampio. Non inventa da solo l’indipendenza, ma dà forza e chiarezza a una scelta ancora discussa.",
      "In sintesi: la propaganda interviene in una società divisa e contribuisce a trasformare le possibilità in un progetto politico.",
      "Il Congresso vota la risoluzione d’indipendenza il 2 luglio 1776 e approva la Dichiarazione il 4 luglio. Thomas Jefferson è il principale estensore, ma lavora nel Committee of Five con John Adams, Benjamin Franklin, Roger Sherman e Robert R. Livingston. Il Congresso discute e modifica il testo: si tratta di un atto collettivo, non dell’opera intatta di un solo autore.",
      "La Dichiarazione presenta una catena argomentativa: gli esseri umani possiedono diritti naturali; il governo nasce per proteggerli; il suo potere legittimo dipende dal consenso dei governati; quando un governo distrugge sistematicamente questi fini, il popolo può cambiarlo. Seguono accuse contro Giorgio III e l’annuncio della separazione. Il testo deve convincere anche interlocutori internazionali che la ribellione è una causa legittima.",
      "In sintesi: il diritto di resistenza diventa giustificazione pubblica per la nascita di Stati indipendenti. Proclamare questa nascita non significa aver già vinto la guerra.",
      "Fonte: Dichiarazione d’indipendenza, Congresso continentale, 4 luglio 1776. «All men are created equal» significa, in traduzione didattica, “tutti gli uomini sono creati uguali”. Il documento richiama vita, libertà e ricerca della felicità; non elenca un sistema elettorale e non abolisce la schiavitù. Il facsimile e il testo commentato sono collegati alla lezione.",
      "Attività: separa nel ragionamento della Dichiarazione tre livelli: un principio generale, un’accusa storica e una decisione politica. Poi confronta il principio di uguaglianza con la presenza di persone schiavizzate. Il fatto che Jefferson sia un proprietario di schiavi non cancella il significato del principio; rende necessaria una domanda sulla sua applicazione e su chi possa rivendicarlo.",
      "In sintesi: la fonte proclama una legittimità e cerca consenso. Non è una fotografia imparziale della società che la produce.",
      "Le colonie diventano Stati che elaborano nuove costituzioni, mentre il Congresso cerca alleati e riconoscimento. Il nemico non è più soltanto una politica fiscale: è il legame di dipendenza dalla Corona. Ma la libertà politica dei nuovi Stati non coincide con libertà individuale e partecipazione per tutti i loro abitanti.",
      "In sintesi: l’indipendenza amplia l’orizzonte dei diritti e conserva profonde esclusioni. Questa tensione accompagnerà la costruzione della repubblica.",
      "Una protesta diventa progetto di un nuovo Stato quando i contestatori non riconoscono più la possibilità di correggere il governo esistente e rivendicano un diverso fondamento del potere. Nel caso americano la guerra, il fallimento della riconciliazione e la mobilitazione delle idee rendono possibile quel passaggio.",
      "Sintesi finale: Lexington e Concord aprono la guerra nel 1775; il Congresso organizza un esercito comune; Paine sostiene la rottura nel 1776. La Dichiarazione approvata il 4 luglio giustifica l’indipendenza attraverso diritti naturali e consenso. L’atto nasce da un lavoro collettivo e non produce subito uguaglianza effettiva. Per diventare duratura, la separazione deve ancora ottenere vittoria militare e riconoscimento internazionale."
    ],
    "guerra": [
      "La Dichiarazione non mette a disposizione un esercito invincibile. I nuovi Stati affrontano una potenza capace di trasportare truppe attraverso l’Atlantico e controllare grandi porti. La domanda sugli aiuti esterni serve a capire come si vince concretamente una guerra: armi, denaro, rifornimenti, comando, diplomazia e controllo dei mari contano quanto la motivazione politica.",
      "In sintesi: l’indipendenza deve essere sostenuta da risorse. La scala internazionale cambia i rapporti di forza.",
      "La Gran Bretagna possiede un esercito professionale e una grande flotta, ma combatte lontano dalle basi di rifornimento e deve controllare territori estesi. I ribelli conoscono i luoghi e possono mobilitare reti locali, ma soffrono mancanza di denaro, equipaggiamento, addestramento e continuità negli arruolamenti. Le milizie non sostituiscono da sole un esercito stabile.",
      "La guerra non è una semplice opposizione fra due popoli compatti. Lealisti combattono al fianco britannico, nazioni native scelgono alleanze differenti, schiavizzati cercano vie di fuga e libertà. Famiglie e comunità subiscono requisizioni, distruzioni e spostamenti.",
      "In sintesi: ogni schieramento ha vantaggi e vulnerabilità. Per Washington sopravvivere alle sconfitte è già un obiettivo strategico.",
      "Nel 1776 i britannici occupano New York e costringono Washington a ritirarsi. Le vittorie americane di Trenton e Princeton tra fine 1776 e inizio 1777 sostengono il morale, ma non risolvono la guerra. Nel 1777 la campagna britannica lungo l’asse del fiume Hudson mira a isolare il New England.",
      "A Saratoga l’esercito di John Burgoyne viene costretto alla resa il 17 ottobre 1777. Il successo americano non conclude il conflitto, ma dimostra che i ribelli possono sconfiggere un’importante forza britannica. È una svolta diplomatica oltre che militare.",
      "In sintesi: una vittoria locale cambia il giudizio delle potenze straniere sulla possibilità di successo della rivoluzione.",
      "Benjamin Franklin agisce in Francia per ottenere credito, armi e riconoscimento. La monarchia di Luigi XVI, guidata in politica estera da Vergennes, vuole indebolire la Gran Bretagna e recuperare prestigio dopo la sconfitta del 1763. Simpatia per la causa americana e rivalità imperiale possono convergere senza essere la stessa cosa.",
      "La Fayette rappresenta l’impegno volontario di un aristocratico favorevole alla causa; Rochambeau comanda l’esercito francese inviato nel 1780 e de Grasse guida la flotta decisiva nella Chesapeake. La Spagna entra in guerra contro la Gran Bretagna nel 1779 come alleata della Francia, senza stipulare la stessa alleanza politica con gli Stati Uniti. Anche il conflitto anglo-olandese dal 1780 amplia gli impegni britannici.",
      "In sintesi: gli alleati possono cooperare pur perseguendo fini differenti. La rivoluzione entra nel sistema delle rivalità fra potenze.",
      "I trattati franco-americani del 6 febbraio 1778 formalizzano commercio, riconoscimento e alleanza militare. L’aiuto francese, già iniziato in forme riservate, diventa aperto. Intanto l’inverno di Valley Forge mostra quanto rifornimenti e organizzazione restino fragili. Dal 1778 i britannici intensificano la strategia meridionale: occupano Savannah e poi Charleston, ma non ottengono il controllo stabile sperato.",
      "Nel 1781 Washington e Rochambeau concentrano le forze contro Cornwallis a Yorktown, in Virginia. La flotta francese impedisce un efficace soccorso via mare. Il 19 ottobre si arrende l’esercito di Cornwallis: non si arrende l’intero Stato britannico. La sconfitta rende molto più difficile sostenere politicamente la prosecuzione della guerra americana, ma le ostilità e i negoziati non finiscono nello stesso giorno.",
      "Il Trattato di Parigi del 3 settembre 1783 riconosce l’indipendenza degli Stati Uniti e ne definisce i confini. Franklin, John Adams e John Jay trattano per gli americani. Altri accordi regolano la pace britannica con Francia e Spagna: per il riconoscimento statunitense il nome da ricordare è Trattato di Parigi.",
      "In sintesi: Saratoga favorisce l’alleanza; la cooperazione franco-americana rende possibile Yorktown; la diplomazia traduce la vittoria in riconoscimento.",
      "Fonte: Trattato di Parigi del 1783, accordo fra rappresentanti britannici e statunitensi. L’articolo iniziale riconosce gli Stati come liberi, sovrani e indipendenti. Il trattato serve a chiudere il conflitto e regolare rapporti e confini, non a rappresentare tutti gli abitanti dei territori coinvolti.",
      "Attività: osserva chi firma e chi manca. Le nazioni native non partecipano come contraenti a questo accordo, benché il territorio rivendicato dagli Stati Uniti si estenda su terre abitate e governate da esse. Spiega perché riconoscimento internazionale e consenso delle popolazioni coinvolte sono problemi diversi.",
      "In sintesi: una pace può chiudere una guerra e lasciare aperti altri conflitti.",
      "Gli Stati Uniti ottengono riconoscimento e un territorio rivendicato fino al Mississippi. La sovranità effettiva resta però contestata, soprattutto dalle nazioni native. Lealisti emigrano e molte persone schiavizzate rimangono tali, mentre altre sfruttano il conflitto per conquistare la libertà. La Francia ottiene un successo strategico ma sostiene costi che aggravano le sue difficoltà finanziarie.",
      "In sintesi: la vittoria produce effetti diversi per gruppi diversi e non risolve l’organizzazione interna dell’Unione.",
      "Non possiamo dimostrare con certezza che senza la Francia ogni esito diverso fosse impossibile: sarebbe una storia alternativa. Possiamo invece documentare che nella guerra realmente combattuta credito, esercito e flotta francesi ebbero un ruolo decisivo. Questa è la distinzione fra spiegazione storica e controfattuale.",
      "Sintesi finale: i ribelli resistono a gravi sconfitte e costruiscono un esercito. Saratoga rende più credibile la loro causa; l’alleanza del 1778 internazionalizza apertamente la guerra. Yorktown dipende dalla cooperazione terrestre e navale franco-americana. Il Trattato di Parigi del 1783 riconosce l’indipendenza. Resta ora da trasformare l’unione di guerra in un ordinamento stabile."
    ],
    "costituzione": [
      "I vincitori della guerra hanno combattuto contro un potere giudicato oppressivo. Ora devono decidere quanta autorità concedere a un governo comune. Se il centro è troppo debole, l’Unione non riesce a pagare debiti e coordinare interessi; se è troppo forte, può apparire una nuova minaccia alle libertà. La Costituzione nasce da questa tensione, non da un accordo privo di conflitti.",
      "In sintesi: costruire l’Unione significa distribuire il potere e renderlo controllabile.",
      "Gli Articoli della Confederazione sono approvati dal Congresso il 15 novembre 1777. Entrano in vigore il 1° marzo 1781, dopo la ratifica di tutti gli Stati, e restano operativi fino al nuovo ordinamento del 1789. Ogni Stato conserva un’ampia sovranità; nel Congresso ciascuno dispone di un voto.",
      "Il centro può condurre la guerra e la diplomazia, ma dipende dai contributi statali per le entrate. Non dispone di un autonomo potere generale di imposizione fiscale e non regola efficacemente il commercio fra gli Stati. Manca un esecutivo separato paragonabile alla futura presidenza. Per modificare gli Articoli è necessaria l’unanimità.",
      "In sintesi: la Confederazione unisce Stati gelosi della propria autonomia. Le sue debolezze diventano più evidenti nella pace.",
      "Debiti, dispute commerciali e difficoltà fiscali alimentano la richiesta di revisione. La Shays’ Rebellion del 1786–1787, in Massachusetts, mobilita agricoltori colpiti da tasse e debiti e accresce nelle élite il timore dell’instabilità. Non è l’unica causa della Convenzione, ma contribuisce a rendere urgente la discussione.",
      "A Filadelfia nel 1787 i delegati passano dalla revisione degli Articoli alla costruzione di un nuovo ordinamento. Stati grandi e piccoli litigano sulla rappresentanza; proprietari schiavisti e loro oppositori sui rapporti fra popolazione, potere e schiavitù. La Costituzione viene firmata il 17 settembre 1787, ma deve ancora essere ratificata.",
      "In sintesi: il nuovo testo è il risultato di negoziati e compromessi. La firma non equivale al suo avvio operativo.",
      "James Madison sostiene un’Unione più solida e contribuisce alla sua architettura. I Federalisti difendono la ratifica; gli Antifederalisti temono che il centro schiacci autonomie e libertà e chiedono garanzie esplicite. Non sono due partiti moderni perfettamente omogenei, né una divisione semplice fra amici e nemici della libertà.",
      "Il compromesso dei tre quinti include una parte della popolazione schiavizzata nel calcolo della rappresentanza e delle imposte dirette, senza conferirle il voto. Accresce quindi il peso politico dei territori schiavisti. Altre clausole proteggono la restituzione dei fuggitivi e impediscono al Congresso di vietare determinate importazioni di schiavi prima del 1808. Non è prevista l’abolizione automatica della schiavitù a quella data.",
      "In sintesi: distribuire il potere fra gli Stati significa anche decidere chi trae vantaggio dalle persone escluse dalla cittadinanza politica.",
      "La repubblica costituzionale federale combina un governo dell’Unione con governi statali dotati di competenze proprie. Il Congresso comprende Camera e Senato. La Camera è eletta ogni due anni dagli elettori qualificati secondo le regole statali; la rappresentanza è collegata alla popolazione. Il Senato ha due membri per Stato, con mandato di sei anni; nel sistema originario sono scelti dalle legislature statali.",
      "Il Presidente esercita il potere esecutivo con mandato quadriennale. È scelto mediante elettori designati da ciascuno Stato secondo modalità decise dalla sua legislatura: il Collegio elettorale è un procedimento indiretto, non un’unica elezione nazionale a suffragio universale. I giudici federali sono nominati dal Presidente con il consenso del Senato e mantengono l’incarico durante buona condotta.",
      "I checks and balances creano controlli reciproci: il Presidente può porre il veto a una legge, ma due terzi di ciascuna Camera possono superarlo; il Congresso vota le leggi, le entrate e la spesa. I trattati conclusi dal Presidente richiedono il consenso di due terzi dei senatori presenti; il Senato interviene anche su importanti nomine. Il Congresso ha il potere di dichiarare guerra. Il potere giudiziario è distinto, ma il testo del 1787 non formula esplicitamente il judicial review delle leggi federali: Marbury v. Madison lo affermerà in modo decisivo nel 1803.",
      "La nona ratifica, del New Hampshire, arriva il 21 giugno 1788 e raggiunge la soglia prevista. Il nuovo governo federale si avvia nel 1789; Washington assume la presidenza il 30 aprile. Il Congresso propone dodici emendamenti nel settembre 1789; dieci vengono ratificati entro il 15 dicembre 1791 e costituiscono il Bill of Rights.",
      "In sintesi: 1787 è la firma, 1788 la soglia di ratifica, 1789 l’avvio del governo e la proposta degli emendamenti, 1791 la ratifica dei dieci diritti.",
      "Fonti: Costituzione del 1787 e Bill of Rights. Osserva nel facsimile della Costituzione il preambolo e la divisione in articoli. Gli articoli I, II e III organizzano rispettivamente legislativo, esecutivo e giudiziario. Il documento del Bill of Rights conservato dai National Archives contiene dodici proposte del 1789: la sua immagine non coincide con un elenco originario di soli dieci emendamenti.",
      "Attività: ricostruisci il percorso di una legge respinta dal Presidente. Poi confronta le garanzie della parola e del processo con le clausole sulla schiavitù. Le prime limitano il governo; le seconde proteggono anche rapporti di dominio. Una stessa costituzione può svolgere entrambe le funzioni.",
      "In sintesi: leggere una costituzione richiede di collegare organizzazione dei poteri, diritti e compromessi sociali.",
      "L’Unione ottiene strumenti più efficaci per governare e riscuotere imposte. Il Bill of Rights tutela religione, parola, stampa, riunione, petizione e garanzie giudiziarie. Nel contesto originario limita soprattutto il governo federale: la successiva applicazione di molte garanzie agli Stati appartiene a una storia ulteriore.",
      "La partecipazione politica resta limitata e diseguale. La condizione di donne, schiavizzati, nativi e uomini privi dei requisiti elettorali impedisce di descrivere il 1787 come una democrazia universale già compiuta. Le istituzioni creano strumenti per conflitti e trasformazioni future, senza garantirne in anticipo l’esito.",
      "In sintesi: il nuovo assetto accresce capacità di governo e limiti al potere, ma non elimina le gerarchie sociali.",
      "Il potere viene reso più forte attribuendo competenze al centro e più controllabile dividendolo fra organi e livelli territoriali. Questo equilibrio non è una macchina che impedisce automaticamente ogni abuso: dipende anche da conflitti, interpretazioni e pratiche politiche.",
      "Sintesi finale: la Confederazione mostra limiti fiscali e politici; la Convenzione del 1787 elabora un nuovo patto federale. Rappresentanza, presidenza indiretta e controlli reciproci cercano di unire efficacia e libertà. La ratifica apre il governo del 1789 e il Bill of Rights del 1791 rafforza le garanzie. La repubblica nasce però dentro una società che continua a escludere molti abitanti. La sua domanda incompiuta resta: libertà per chi?"
    ]
  },
  "approfondimenti": {
    "proclamazione": [
      "La Royal Proclamation del 7 ottobre 1763 tenta di ordinare i territori acquisiti dalla Gran Bretagna. Limita gli insediamenti coloniali oltre una linea legata agli Appalachi e sottopone gli acquisti di terre native al controllo della Corona. Lo scopo è contenere conflitti e spese, oltre a governare l’espansione: non è una politica disinteressata di tutela.",
      "Molti coloni e investitori vedono nella misura un ostacolo alle proprie possibilità economiche. Le nazioni native, invece, difendono territori che non diventano vuoti perché Francia e Gran Bretagna hanno firmato un trattato. La guerra legata a Pontiac mostra la capacità di iniziativa di queste comunità e il fallimento di un ordine imposto senza consenso.",
      "La linea viene ripetutamente violata. Distinguere confine proclamato, insediamento effettivo e sovranità rivendicata evita di leggere le carte come fotografie neutrali. Una mappa imperiale rappresenta anche una pretesa di potere.",
      "Per ragionare: perché la stessa misura può apparire un limite alla libertà di un colono e una difesa, per quanto incompleta, della terra di una comunità nativa?"
    ],
    "rappresentanza": [
      "La formula significa “nessuna tassazione senza rappresentanza”. Il punto non è che tutti gli abitanti delle colonie chiedano di votare, ma che molti contestatori rivendicano il consenso dei rappresentanti locali alle imposte. Chi non elegge membri di Westminster non considera sufficiente l’autorità di quel Parlamento a tassarlo.",
      "La teoria britannica della rappresentanza virtuale sostiene che i deputati curino l’interesse generale dell’impero, compresi i sudditi senza voto. Gli americani oppongono la rappresentanza effettiva nelle assemblee coloniali. Dietro una tassa si nasconde quindi una disputa su quale corpo politico abbia l’ultima parola.",
      "Non confondere questa rivendicazione con il suffragio universale: una comunità può domandare autonomia da Londra e mantenere forti esclusioni al proprio interno. Per il confronto, distingui sempre chi chiede rappresentanza da chi rimane fuori dalla richiesta.",
      "Domanda di recupero: se Londra avesse dimezzato ogni imposta mantenendo immutata la propria pretesa di sovranità, avrebbe risolto il conflitto di principio? Motiva senza fingere di sapere con certezza che cosa sarebbe accaduto."
    ],
    "tea-act": [
      "Il Tea Act del 1773 concede alla East India Company privilegi commerciali che le permettono di collocare il tè nelle colonie a condizioni vantaggiose. Il precedente dazio sul tè rimane. Non nasce una nuova tassa: cambia l’organizzazione del commercio, con agenti selezionati e una posizione dominante della compagnia.",
      "Il prezzo più basso non elimina il problema. I mercanti esclusi temono perdite; gli oppositori dell’autorità parlamentare temono che l’acquisto legittimi il prelievo. Interessi materiali e principio costituzionale si intrecciano. Il Boston Tea Party del 16 dicembre distrugge i carichi come atto pubblico di rifiuto.",
      "Alcuni partecipanti usano travestimenti e simboli associati ai Mohawk. Questo non significa che siano Mohawk o che rappresentino una decisione di quella nazione. I travestimenti servono a celare identità e costruiscono un linguaggio simbolico della protesta coloniale. Le punizioni del 1774 trasformano Boston in un problema comune alle colonie.",
      "Da ricordare: tassa precedente + privilegi commerciali + autorità contestata. Dire soltanto “rivolta per una nuova tassa” cancella proprio ciò che occorre spiegare."
    ],
    "paine": [
      "Common Sense esce a Filadelfia nel gennaio 1776, quando la guerra è già iniziata ma molti coloni sperano ancora nella riconciliazione. Paine critica la monarchia ereditaria e presenta l’indipendenza come una scelta ragionevole. Il titolo stesso promette un ragionamento accessibile, non riservato agli esperti.",
      "L’opuscolo unisce argomenti politici, immagini efficaci e richiami comprensibili ai lettori del tempo. Sposta il bersaglio: non soltanto cattivi ministri o provvedimenti sbagliati, ma il principio monarchico. Una repubblica indipendente diventa un’alternativa di cui discutere apertamente.",
      "È una fonte di persuasione, non un verbale delle opinioni di tutti gli americani. Non prova che il consenso sia unanime e non causa da solo l’indipendenza. Agisce insieme alla guerra, al fallimento dei negoziati e alle decisioni dei congressi.",
      "Attività: spiega in cinque righe perché una protesta contro le tasse può restare monarchica, mentre l’attacco alla successione ereditaria apre un diverso progetto di Stato."
    ],
    "dichiarazione": [
      "Il Congresso affida la preparazione del testo al Committee of Five. Jefferson redige la parte principale, Adams e Franklin intervengono e il Congresso modifica la proposta prima di approvarla il 4 luglio 1776. La scelta dell’indipendenza è stata votata il 2 luglio: decisione e giustificazione pubblica non sono lo stesso atto.",
      "Il giusnaturalismo offre l’idea di diritti anteriori al governo; Locke contribuisce alla tradizione del consenso e del diritto di resistenza. Pesano anche diritti britannici, repubblicanesimo e testi americani come la Dichiarazione dei diritti della Virginia. L’Illuminismo è una risorsa rielaborata in un conflitto concreto, non una ricetta applicata meccanicamente.",
      "La struttura del testo procede dai principi alle accuse, poi alla separazione. Il suo destinatario è anche internazionale: occorre mostrare che la ribellione possiede ragioni legittime. Il facsimile della pergamena è una fonte autentica; l’incisione Stone, spesso riprodotta altrove, è invece del 1823.",
      "Attività: individua dove finisce un principio universale e comincia un’accusa contro il sovrano. Quale prova servirebbe per verificare ciascuna accusa?"
    ],
    "diritti-schiavitu": [
      "Alla vigilia della rivoluzione la schiavitù africana è legalmente presente in tutte le tredici colonie. La sua centralità nelle piantagioni del Sud non rende il Nord estraneo: esistono persone schiavizzate nelle case, nei campi e nelle città settentrionali, oltre a commerci legati alla tratta e ai prodotti delle piantagioni.",
      "La proclamazione dei diritti non determina un’emancipazione generale. In alcuni Stati settentrionali si avviano processi di abolizione, spesso graduali e incapaci di liberare subito tutti. Altrove i proprietari mantengono il sistema, che trova protezioni nei compromessi costituzionali.",
      "La contraddizione non è un problema inventato dagli osservatori di oggi: persone schiavizzate, liberi neri e oppositori della schiavitù la contestano già allora. Phillis Wheatley utilizza la scrittura per intervenire nello spazio pubblico che tende a negarne l’autorità intellettuale.",
      "Domanda: come può un principio non applicato a tutti diventare un argomento nelle mani degli esclusi? La risposta richiede di considerare le loro iniziative, non solo le intenzioni dei fondatori."
    ],
    "saratoga": [
      "La campagna britannica del 1777 mira a separare il New England dalle altre colonie attraverso il corridoio del lago Champlain e dell’Hudson. L’esercito di Burgoyne incontra resistenza e problemi di coordinamento e rifornimento. Il 17 ottobre deve arrendersi a Saratoga.",
      "Per i ribelli la vittoria significa più di un risultato sul campo: rende credibile la capacità americana di continuare la guerra. La Francia, già impegnata in aiuti riservati, valuta diversamente il rischio di intervenire apertamente. Franklin e gli altri diplomatici trasformano il successo militare in opportunità negoziale.",
      "Il 6 febbraio 1778 vengono firmati i trattati di amicizia e commercio e di alleanza. L’intervento non nasce soltanto dall’ammirazione per la libertà: la monarchia francese vuole colpire la Gran Bretagna. La causa americana e il calcolo imperiale convergono.",
      "Nesso da ricordare: vittoria → maggiore credibilità → alleanza → risorse e apertura di nuovi fronti. Saratoga non conclude la guerra."
    ],
    "francia": [
      "La Francia sostiene la guerra con armi, prestiti, soldati e navi. La Fayette è una figura importante, ma non riassume l’intero intervento: Rochambeau guida il corpo di spedizione e de Grasse rende decisivo il controllo marittimo nella campagna di Yorktown.",
      "Nel 1781 le forze di Washington e Rochambeau concentrano l’assedio in Virginia, mentre la flotta francese impedisce un efficace soccorso britannico. La cooperazione unisce logistica, informazioni, operazioni terrestri e navali. La resa riguarda Cornwallis e il suo esercito, non l’intera Gran Bretagna.",
      "L’alleanza risponde a fini diversi: gli americani vogliono l’indipendenza, la monarchia francese cerca vantaggi contro un rivale. Le spese di guerra aggravano i problemi finanziari francesi, senza costituire da sole una spiegazione della successiva rivoluzione.",
      "Attività: elimina mentalmente una delle tre risorse — denaro, truppe, flotta — e indica quale difficoltà concreta aumenta. È un esercizio sui nessi causali, non la dimostrazione di un esito alternativo certo."
    ],
    "confederazione": [
      "Gli Articoli sono approvati nel 1777 e diventano operativi nel 1781. Il Congresso dipende dagli Stati per le risorse; ogni Stato ha un voto e le modifiche richiedono unanimità. Questo sistema protegge autonomie appena conquistate, ma rende difficile finanziare decisioni comuni.",
      "La Costituzione del 1787 crea un governo federale con poteri propri, compresi imposizione fiscale e regolazione del commercio fra Stati. Introduce un esecutivo separato e un potere giudiziario federale, mentre gli Stati mantengono istituzioni e competenze. Il cambiamento è operativo nel 1789.",
      "Non si passa semplicemente da “nessun governo” a “governo”: la Confederazione ha già organi e capacità diplomatiche. Cambiano strumenti, rapporto con i cittadini e forza del centro. La crisi fiscale e le dispute interne rendono più convincente la proposta, ma non la rendono inevitabile.",
      "Confronta nella mappa quattro dimensioni: entrate, rappresentanza, esecutivo e modifica del patto. Per ogni differenza indica quale problema si cerca di risolvere e quale timore si può creare."
    ],
    "federalismo": [
      "Il federalismo distribuisce costituzionalmente competenze fra l’Unione e gli Stati. Non è la stessa cosa della separazione fra legislativo, esecutivo e giudiziario: quella divide le funzioni, questo distingue livelli di governo. Le due architetture si sovrappongono.",
      "Nel nuovo assetto il governo federale può esercitare competenze comuni, come la politica monetaria e la regolazione del commercio interstatale, mentre gli Stati conservano ampi ambiti interni. La Costituzione e le leggi federali adottate secondo essa sono superiori alle norme statali incompatibili.",
      "Il Senato assegna due membri a ogni Stato, mentre la Camera lega la rappresentanza alla popolazione secondo i criteri storici del testo originario. L’equilibrio non elimina le controversie: crea istituzioni nelle quali negoziarle e combatterle politicamente.",
      "Verifica: “il Congresso e il Presidente” è una distinzione fra funzioni; “Unione e Virginia” è una distinzione fra livelli territoriali. Spiega perché confonderle impedisce di capire il sistema."
    ],
    "federalisti": [
      "I Federalisti sostengono la ratifica della Costituzione perché vedono nella debolezza del centro un rischio per la sopravvivenza dell’Unione. Hamilton, Madison e Jay difendono il nuovo ordinamento nei Federalist Papers. Un governo più ampio e articolato dovrebbe controllare fazioni e interessi contrapposti.",
      "Gli Antifederalisti temono distanza dai cittadini, predominio delle élite e riduzione dell’autonomia statale. Alcuni contestano la presidenza, altri l’ampiezza dei poteri del Congresso o l’assenza di un elenco esplicito di garanzie. Non propongono tutti lo stesso modello alternativo.",
      "Il dibattito contribuisce alla promessa di emendamenti a tutela dei diritti. Madison, che aveva difeso la Costituzione, partecipa poi alla preparazione delle proposte del 1789. La ratifica e il Bill of Rights mostrano così un esito costruito anche attraverso le obiezioni.",
      "Attività: scrivi una tesi federalista e un’obiezione antifederalista sul potere di tassare. Evita di attribuire a un solo campo la difesa esclusiva della libertà."
    ],
    "controlli": [
      "La separazione dei poteri assegna funzioni diverse; i checks and balances permettono a un organo di intervenire su alcune decisioni degli altri. Il Presidente può porre il veto a una legge, ma il Congresso può superarlo con due terzi di entrambe le Camere. Il potere di spesa rimane parlamentare.",
      "Il Presidente nomina i giudici federali e importanti funzionari con il consenso del Senato. Per i trattati è richiesto il consenso di due terzi dei senatori presenti. La Camera formula l’impeachment e il Senato giudica le accuse: l’impeachment non equivale automaticamente alla rimozione.",
      "Il potere giudiziario interpreta e applica il diritto; nel 1803 Marbury v. Madison afferma in modo decisivo il controllo sulle leggi federali incompatibili con la Costituzione. Non attribuire questa formulazione esplicita al testo del 1787.",
      "Nessun meccanismo garantisce automaticamente il buon governo. I controlli possono impedire concentrazioni di potere, ma anche creare blocchi. Per studiarli, segui una decisione concreta: chi propone, chi approva, chi può fermarla?"
    ],
    "bill-rights": [
      "Il 25 settembre 1789 il Congresso propone dodici emendamenti. Dieci raggiungono la ratifica necessaria nel 1791 e diventano il Bill of Rights. La distinzione fra proposta e ratifica spiega perché sul facsimile autentico siano presenti dodici articoli.",
      "Il primo protegge religione, parola, stampa, riunione e petizione. Il secondo riguarda il possesso e porto delle armi nel suo contesto storico legato anche alla milizia. Il terzo limita l’alloggiamento di soldati nelle abitazioni. Dal quarto all’ottavo si trovano protezioni contro perquisizioni irragionevoli e garanzie processuali, fra cui il giusto processo, la giuria nei casi previsti e il divieto di pene crudeli e inusuali.",
      "Il nono chiarisce che l’elenco non esaurisce tutti i diritti; il decimo riserva agli Stati o al popolo i poteri non delegati all’Unione e non vietati agli Stati. Nel contesto originario queste garanzie limitano il governo federale; la loro successiva applicazione agli Stati è un processo ulteriore.",
      "Da ricordare: il Bill of Rights limita il potere ma non abolisce la schiavitù né introduce il suffragio universale. Non è identico alla Dichiarazione d’indipendenza."
    ],
    "marbury": [
      "Nel 1803 la Corte Suprema, presieduta da John Marshall, affronta il caso di William Marbury, che chiede un ordine giudiziario per ottenere la consegna della propria nomina. La controversia nasce dal passaggio politico fra l’amministrazione Adams e quella Jefferson.",
      "La Corte conclude che non può concedere quell’ordine sulla base di una previsione del Judiciary Act del 1789 che amplia la sua competenza originaria oltre quanto stabilito dalla Costituzione. La legge ordinaria incompatibile con la Costituzione non può prevalere su di essa.",
      "Il caso afferma decisivamente il judicial review delle leggi federali. Esistevano precedenti e dibattiti sul controllo giudiziario: non si tratta di un’idea comparsa dal nulla. Il testo costituzionale del 1787 stabilisce la supremazia della Costituzione e il potere giudiziario, ma non formula esplicitamente questo potere nei termini spesso usati nei riassunti scolastici.",
      "Distinzione essenziale: 1787 è il testo costituzionale; 1803 è una svolta della sua interpretazione. La storia delle istituzioni comprende entrambi."
    ],
    "liberta": [
      "«All men are created equal»: la Dichiarazione del 1776 formula un principio generale. Per comprenderne la portata occorre però distinguere quattro piani: indipendenza degli Stati, diritti individuali, partecipazione politica e sovranità sul territorio. Una vittoria sul primo piano non comporta automaticamente un’uguaglianza sugli altri.",
      "La schiavitù africana non è un’eccezione confinata al Sud: è presente in tutte le tredici colonie. Il lavoro forzato sostiene piantagioni, attività domestiche e urbane; commerci e porti settentrionali partecipano alle reti atlantiche. Nel dopoguerra alcuni Stati avviano abolizioni graduali, mentre altri conservano e rafforzano il sistema. Non si deve trasformare questo percorso diseguale in una liberazione nazionale già compiuta nel 1776.",
      "Molti dirigenti rivoluzionari sono proprietari di schiavi. La Costituzione evita la parola “schiavitù”, ma contiene compromessi che ne proteggono gli interessi. Il conteggio dei tre quinti serve a distribuire rappresentanza e imposte dirette, non riconosce una quota di umanità o un diritto di voto. Chi è schiavizzato aumenta il peso politico dei proprietari senza partecipare alla decisione.",
      "Le persone escluse non restano passive. Fuga, petizioni, servizio militare, scrittura e relazioni comunitarie possono diventare strumenti di rivendicazione. La poetessa Phillis Wheatley, rapita in Africa e venduta a Boston, dimostra con la propria opera la falsità dei pregiudizi sulle capacità intellettuali dei neri. La sua emancipazione personale non equivale alla fine della struttura schiavista.",
      "Anche le donne partecipano alla rivoluzione: organizzano boicottaggi, producono beni, sostengono famiglie e reti politiche. Abigail Adams chiede al marito nel 1776 di ricordare le donne nella costruzione del nuovo ordinamento. La sua lettera non va trasformata automaticamente in un programma elettorale moderno: contesta soprattutto il potere maschile e l’assenza di protezioni adeguate. La rappresentanza politica resta largamente maschile.",
      "Le regole elettorali dipendono dagli Stati e non producono un unico blocco immutabile di esclusioni. Nel New Jersey alcune donne non sposate proprietarie e alcune persone nere libere possono votare fra 1776 e 1807, rispettando i requisiti previsti; nel 1807 il diritto viene ristretto ai maschi bianchi. Questa eccezione non annulla la disuguaglianza generale, ma mostra che i diritti possono essere aperti, contesi e poi ritirati.",
      "Le nazioni native difendono un’altra dimensione della libertà: conservare territori, istituzioni e capacità di decidere. Alcune si alleano con i britannici, altre con gli americani, altre cercano neutralità; esistono divisioni anche interne. Non sono un popolo unico e non diventano sovrane soltanto quando una potenza europea le riconosce. Il Trattato di Parigi del 1783 disegna confini senza includerle fra i contraenti.",
      "Il colonialismo d’insediamento continua dopo l’indipendenza. La libertà di espandersi rivendicata da molti coloni entra in conflitto con la sovranità nativa. Qui non basta chiedere chi voti: occorre chiedere chi possieda la terra, chi la governi e chi possa decidere su di essa.",
      "Il collegamento con la Rivoluzione francese riguarda la stessa distanza fra universalità dei principi e applicazione concreta. La Dichiarazione francese del 1789 non elimina immediatamente esclusioni politiche e schiavitù coloniale. Il confronto non deve diventare una gara fra rivoluzioni “più buone”: bisogna confrontare istituzioni, interessi, conflitti e iniziativa degli esclusi nei due contesti.",
      "Laboratorio: scegli fra una donna coinvolta nei boicottaggi, una persona schiavizzata e una comunità nativa. Scrivi una richiesta rivolta ai nuovi governanti usando un principio proclamato dalla rivoluzione e un problema concreto documentato. Segnala che si tratta di una ricostruzione didattica, non di una citazione autentica.",
      "Conclusione: la rivoluzione apre un linguaggio politico potente e nello stesso tempo costruisce istituzioni entro una società gerarchica. Comprendere la contraddizione significa spiegare come funziona e chi la contesta già allora. Non basta né celebrare i principi né considerarli vuoti: occorre seguire la lotta sulla loro applicazione."
    ],
    "riassunto": [
      "1. Prima della rivoluzione. Le tredici colonie britanniche della costa atlantica hanno economie e istituzioni diverse. Nel New England agricoltura, pesca, cantieri e commercio; nel Centro cereali e porti; nel Sud piantagioni di tabacco, riso e indaco, accanto a piccole aziende agricole. Queste regioni sono collegate dal commercio atlantico. La schiavitù africana è presente e riconosciuta dalla legge in tutte le colonie, anche se pesa maggiormente nelle grandi economie di piantagione. Assemblee locali e autogoverno alimentano una cultura politica autonoma, ma il voto resta ristretto.",
      "Le colonie si espandono su territori di nazioni native dotate di proprie istituzioni. Non si tratta semplicemente di popolazioni “respinte verso l’interno”: il colonialismo d’insediamento produce occupazioni, guerre, trattati contestati e perdita di sovranità. Il conflitto nordamericano inizia nel 1754; la Guerra dei Sette anni europea dura dal 1756 al 1763. La vittoria britannica accresce debito e costi di governo. La Royal Proclamation del 1763 limita gli insediamenti oltre gli Appalachi, scontentando coloni e investitori.",
      "2. Tasse e rappresentanza. Londra cerca entrate e maggiore controllo con il Sugar Act del 1764, lo Stamp Act del 1765 e i Townshend Acts del 1767. “No taxation without representation” esprime il rifiuto di imposte decise senza il consenso dei rappresentanti coloniali. Boicottaggi e comitati coordinano la protesta. Il Boston Massacre del 1770 aggrava la sfiducia. Il Tea Act del 1773 mantiene il precedente dazio sul tè e favorisce la East India Company: non introduce una nuova tassa. La protesta riguarda anche la posizione dominante della compagnia e il principio dell’autorità parlamentare.",
      "Il 16 dicembre 1773, nel Boston Tea Party, i contestatori distruggono carichi di tè; alcuni utilizzano travestimenti e simboli associati ai Mohawk. Londra risponde con i Coercive Acts del 1774. Il Primo Congresso continentale riunisce delegati di dodici colonie e coordina il boicottaggio; la Georgia non partecipa. L’indipendenza non è ancora una scelta condivisa.",
      "3. Dalla guerra all’indipendenza. Gli scontri di Lexington e Concord del 19 aprile 1775 aprono la guerra. Il Secondo Congresso continentale organizza il Continental Army, guidato da George Washington. Dopo tentativi di riconciliazione falliti, Common Sense di Thomas Paine, pubblicato nel gennaio 1776, rafforza la scelta repubblicana e indipendentista. Il Congresso vota l’indipendenza il 2 luglio e approva la Dichiarazione il 4 luglio 1776.",
      "Jefferson è il principale estensore, all’interno del Committee of Five; il Congresso modifica la proposta. Il testo unisce giusnaturalismo, idee illuministe e tradizione dei diritti: vita, libertà e ricerca della felicità precedono il governo, che deve proteggerle e fondarsi sul consenso. Un potere che distrugge questi fini può essere cambiato. La Dichiarazione giustifica la separazione ma non abolisce la schiavitù né crea il suffragio universale.",
      "4. Una guerra internazionale. Gli americani affrontano sconfitte, scarsità di risorse e problemi di arruolamento. La vittoria di Saratoga nel 1777 rafforza la loro credibilità. Franklin contribuisce all’alleanza con la Francia del 1778, che porta sostegno finanziario, militare e navale. La Francia agisce anche per indebolire la Gran Bretagna. La cooperazione fra Washington, Rochambeau e la flotta di de Grasse è decisiva a Yorktown: nel 1781 si arrende l’esercito di Cornwallis, non lo Stato britannico.",
      "Il Trattato di Parigi del 3 settembre 1783 riconosce l’indipendenza degli Stati Uniti. I confini concordati non risolvono i diritti territoriali delle nazioni native, escluse dai negoziati. La guerra lascia inoltre debiti, migrazioni e divisioni fra patrioti e lealisti.",
      "5. Costruire la repubblica. Gli Articoli della Confederazione, approvati nel 1777, entrano in vigore nel 1781 e restano operativi fino al 1789. Il centro dipende dai contributi statali e fatica a coordinare economia e finanze. La Convenzione di Filadelfia elabora una nuova Costituzione, firmata il 17 settembre 1787. La nona ratifica arriva nel 1788; il nuovo governo federale si avvia nel 1789.",
      "La repubblica costituzionale federale distribuisce competenze fra Unione e Stati. Il Congresso comprende Camera, collegata alla popolazione, e Senato, con due membri per Stato. Il Presidente ha mandato quadriennale e viene scelto attraverso il Collegio elettorale. Il sistema originario non coincide con un voto nazionale diretto e universale. Trattati e importanti nomine coinvolgono il Senato; il Congresso decide leggi e spesa e può dichiarare guerra. Veto, maggioranze qualificate e altre procedure creano controlli reciproci.",
      "La Corte Suprema appartiene al potere giudiziario indipendente. Il controllo giudiziario sulle leggi federali incompatibili con la Costituzione non è formulato esplicitamente dal testo del 1787: viene affermato in modo decisivo nel 1803 in Marbury v. Madison. Federalisti e Antifederalisti discutono forza del centro e garanzie. Nel 1789 il Congresso propone dodici emendamenti; dieci vengono ratificati nel 1791 e formano il Bill of Rights, che protegge libertà e garanzie processuali soprattutto contro il governo federale nel contesto originario.",
      "Conclusione. La rivoluzione produce indipendenza e istituzioni rappresentative, ma conserva schiavitù, restrizioni al voto e pressione sulle terre native. Le donne restano largamente escluse dalla rappresentanza, con limitate eccezioni statali. Non nasce una democrazia universale già compiuta: nasce una repubblica il cui linguaggio dei diritti permette anche agli esclusi di contestarne i limiti. La domanda unitaria del modulo è la distanza fra diritti proclamati e libertà effettivamente riconosciute."
    ]
  }
};
