const CACHE_NAME = 'rivoluzione-francese-v1';
const ASSETS = [
  "./",
  "index.html",
  "app.html",
  "manifest.webmanifest",
  "css/style.css",
  "js/data.js",
  "js/app.js",
  "assets/img/cartina-europea.png",
  "assets/video/sieyes-intro-lezioni.mp4",
  "assets/pdf/lezioni/1-premessa-breve.pdf",
  "assets/pdf/lezioni/2-1789.pdf",
  "assets/pdf/lezioni/3-monarchia-costituzionale.pdf",
  "assets/pdf/lezioni/4-repubblica.pdf",
  "assets/pdf/approfondimenti/sieyes-terzo-stato.pdf",
  "assets/pdf/approfondimenti/girondini-giacobini.pdf",
  "assets/pdf/approfondimenti/terrore.pdf",
  "assets/pdf/approfondimenti/pensiero-liberale.pdf",
  "assets/pdf/approfondimenti/club-politici.pdf",
  "assets/pdf/approfondimenti/forme-governo.pdf",
  "assets/pdf/approfondimenti/tre-stati-stati-generali.pdf",
  "assets/pdf/approfondimenti/schiavitu-cittadinanza.pdf",
  "assets/pdf/approfondimenti/sanculotti.pdf",
  "assets/pdf/approfondimenti/diritti-uomo-cittadino.pdf",
  "assets/img/schemi/1-premessa.png",
  "assets/img/schemi/2-1789.png",
  "assets/img/schemi/3-monarchia-costituzionale.png",
  "assets/img/schemi/4-repubblica.png",
  "assets/img/schemi/tre-stati.png",
  "assets/img/schemi/diritti-uomo-cittadino.png",
  "assets/img/schemi/schiavitu.png",
  "assets/img/schemi/forme-governo.png",
  "assets/img/schemi/pensiero-liberale.png",
  "assets/img/schemi/girondini-giacobini.png",
  "assets/img/schemi/club-politici.png",
  "assets/img/schemi/sanculotti.png",
  "assets/img/schemi/terrore.png",
  "assets/img/covers/index-preview.png",
  "assets/img/covers/copertina.png",
  "assets/img/icons/icon-192.png",
  "assets/img/icons/icon-512.png",
  "assets/img/protagonisti/foto/luigi-xvi.png",
  "assets/img/protagonisti/foto/maria-antonietta.png",
  "assets/img/protagonisti/foto/sieyes.png",
  "assets/img/protagonisti/foto/la-fayette.png",
  "assets/img/protagonisti/foto/robespierre.png",
  "assets/img/protagonisti/foto/danton.png",
  "assets/img/protagonisti/foto/marat.png",
  "assets/img/protagonisti/foto/olympe-de-gouges.png",
  "assets/img/protagonisti/foto/charlotte-corday.png",
  "assets/img/protagonisti/foto/madame-roland.png",
  "assets/img/protagonisti/foto/tricoteuses.png"
];
self.addEventListener('install', event => { event.waitUntil(caches.open(CACHE_NAME).then(cache => cache.addAll(ASSETS)).then(()=>self.skipWaiting())); });
self.addEventListener('activate', event => { event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k=>k!==CACHE_NAME).map(k=>caches.delete(k)))).then(()=>self.clients.claim())); });
self.addEventListener('fetch', event => { if(event.request.method !== 'GET') return; event.respondWith(caches.match(event.request).then(cached => cached || fetch(event.request).then(resp => { const copy = resp.clone(); caches.open(CACHE_NAME).then(cache => cache.put(event.request, copy)); return resp; }).catch(()=> caches.match('index.html')))); });
