# Testi originali per gbprof. Ricostruzione didattica, non trascrizione del Google Site.
SOURCES = {
 'origine': ('Il sito di partenza di gbprof', 'https://sites.google.com/view/rivoluzionefrancese-lezioni/home-page', 'Modello della struttura: protagonisti, gruppi, documenti, diario. I testi sono stati riscritti e ampliati; il sito originale non è assunto come autorità per le date.'),
 'archivio': ('Liberty, Equality, Fraternity · archivio GMU / CUNY', 'https://revolution.chnm.org/', 'Raccolta universitaria di documenti, immagini, cronologie e saggi, curata da Lynn Hunt e Jack Censer. Le traduzioni inglesi vanno distinte dagli originali francesi.'),
 'donne': ('Donne e Rivoluzione · GMU / CUNY', 'https://revolution.chnm.org/exhibits/show/liberty--equality--fraternity/women-and-the-revolution', 'Introduzione storiografica e accesso a petizioni, regolamenti, dibattiti e atti processuali.'),
 'guerra': ('Guerra, Terrore e resistenza · GMU / CUNY', 'https://revolution.chnm.org/exhibits/show/liberty--equality--fraternity/war-terror-and-resistance', 'Percorso tematico con documenti sul governo rivoluzionario e sulle opposizioni.'),
 'monarchia': ('La caduta della monarchia · GMU / CUNY', 'https://revolution.chnm.org/exhibits/show/liberty--equality--fraternity/monarchy-falls', 'Documenti e interpretazioni sul passaggio dalla monarchia alla repubblica.'),
 'colonie': ('Schiavitù e Rivoluzione haitiana · GMU / CUNY', 'https://revolution.chnm.org/exhibits/show/liberty--equality--fraternity/slavery-and-the-haitian-revolu', 'Percorso sulle colonie, sulle gerarchie razziali e sull’azione degli schiavi insorti.'),
 'bastiglia': ('Il 14 luglio · Presidenza della Repubblica francese', 'https://www.elysee.fr/la-presidence/la-fete-nationale-du-14-juillet', 'Ricostruzione istituzionale dell’evento del 1789 e della successiva festa nazionale. Anche una memoria ufficiale seleziona il passato.'),
 'comitato': ('Raphaël Matta-Duvignau · Il Comitato di salute pubblica', 'https://journals.openedition.org/lrf/773', 'Ricerca sul Comitato: istituzione il 6 aprile 1793, funzioni e durata. Riferimento per la correzione della cronologia.'),
 '1789': ('Dichiarazione dei diritti dell’uomo e del cittadino · 1789', 'https://www.conseil-constitutionnel.fr/le-bloc-de-constitutionnalite/declaration-des-droits-de-l-homme-et-du-citoyen-de-1789', 'Testo francese sul sito del Conseil constitutionnel. Fonte normativa: dice quali principi si affermano, non prova che siano già realizzati.'),
 '1791': ('Costituzione del 3 settembre 1791', 'https://www.conseil-constitutionnel.fr/les-constitutions-dans-l-histoire/constitution-de-1791', 'Testo costituzionale: monarchia, rappresentanza e limiti all’esercizio dei diritti politici.'),
 '1793': ('Costituzione del 24 giugno 1793', 'https://www.conseil-constitutionnel.fr/les-constitutions-dans-l-histoire/constitution-du-24-juin-1793', 'Dichiarazione e atto costituzionale dell’Anno I, mai entrato effettivamente in funzione.'),
 '1795': ('Costituzione del 5 fruttidoro Anno III · 22 agosto 1795', 'https://www.conseil-constitutionnel.fr/les-constitutions-dans-l-histoire/constitution-du-5-fructidor-an-iii', 'Dichiarazione dei diritti e dei doveri; organizzazione del Direttorio.'),
 'olympe': ('Olympe de Gouges · Dichiarazione del 1791', 'https://revolution.chnm.org/exhibits/show/liberty--equality--fraternity/item/557', 'Documento dell’epoca in traduzione inglese. La scheda didattica usa una parafrasi italiana dichiarata.'),
 'processo': ('Il processo di Olympe de Gouges', 'https://revolution.chnm.org/exhibits/show/liberty--equality--fraternity/item/375', 'Resoconto processuale da leggere criticamente: la voce dell’accusa non coincide con un giudizio storico neutrale.'),
 'societa': ('Regolamento delle Repubblicane rivoluzionarie · 9 luglio 1793', 'https://revolution.chnm.org/exhibits/show/liberty--equality--fraternity/item/382', 'Fonte primaria per studiare un’organizzazione politica femminile, senza confondere tutte le donne con le sue aderenti.'),
 'brumaio': ('Fondation Napoléon · Il colpo di Stato di brumaio', 'https://www.napoleon.org/en/enseignants/documents/1799-le-coup-detat-du-18-brumaire-le-general-napoleon-bonaparte-prend-le-pouvoir-cours/', 'Ricostruzione delle due giornate del 9–10 novembre 1799. Per l’esito istituzionale distinguere consolato provvisorio e Costituzione dell’Anno VIII.'),
}
PHASES = [
('antefatto','Prima del 1789','Un regno ricco, una monarchia in crisi','Perché una crisi di bilancio diventa una crisi del potere?',[
('Il mondo precedente','La Francia di Luigi XVI è una grande monarchia europea, con una popolazione numerosa, città commerciali, manifatture e un vasto mondo rurale. Ricchezza del paese e disponibilità finanziaria dello Stato, però, non sono la stessa cosa. La monarchia deve pagare interessi e rimborsare prestiti; le guerre, compreso l’intervento a fianco degli insorti americani, hanno aggravato il debito. Il problema non si riduce alle spese della corte: riguarda il costo della politica di potenza, le difficoltà di riscossione e una distribuzione diseguale del prelievo.\nLa società è divisa in ordini giuridici. Clero e nobiltà godono di privilegi diversi, ma non sono blocchi uniformi: un parroco di campagna non vive come un vescovo, un nobile povero non dispone delle risorse di un grande cortigiano. Anche i privilegi fiscali non equivalgono a un’esenzione totale da qualsiasi imposta. Il Terzo Stato raccoglie tutti gli altri, dal ricco negoziante al bracciante. Condividere una condizione giuridica non significa avere gli stessi interessi economici.'),
('Le fratture','Tra il 1787 e il 1788 i tentativi di riformare le imposte incontrano la resistenza dei privilegiati e dei parlamenti, tribunali superiori che rivendicano il controllo sulla registrazione degli atti regi. Il sovrano scopre di non poter far accettare facilmente una riforma generale. La convocazione degli Stati Generali, che non si riunivano dal 1614, apre una questione nuova: chi ha titolo per autorizzare i sacrifici richiesti al paese?\nIl cattivo raccolto del 1788 e la crisi del pane trasformano il malessere in emergenza quotidiana. Le famiglie popolari spendono una parte decisiva del reddito per nutrirsi; l’aumento del prezzo del pane riduce anche gli acquisti di altri beni e danneggia artigiani e lavoratori. La crisi finanziaria dello Stato e quella della sussistenza sono distinte, ma si rafforzano.'),
('Attori, idee e conflitti','Gli illuministi hanno criticato l’arbitrio e i privilegi, ma non propongono un unico programma e non sono tutti democratici. Separazione dei poteri, libertà civile e sovranità popolare sono risposte diverse. L’esperienza americana mostra che un ordine politico può essere rifondato con dichiarazioni e costituzioni. Giornali, opuscoli e discussioni diffondono il linguaggio dei diritti.\nI cahiers de doléances raccolgono richieste di comunità e ordini: contengono progetti di riforma, lamentele locali e conflitti. Molti chiedono ancora un buon re e una monarchia riformata. Leggere il 1788 come preparazione consapevole alla repubblica del 1792 cancellerebbe l’incertezza dei protagonisti.'),
('Che cosa cambia','La monarchia convoca un’assemblea per risolvere una crisi, ma rende possibile una discussione sulla propria legittimità. La domanda passa dal denaro al potere: chi rappresenta la Francia? La Rivoluzione non è già scritta nelle idee illuministe o nella fame. Nasce dall’incontro fra condizioni di lunga durata e decisioni prese durante una crisi aperta.')], 'La crisi dello Stato, i privilegi e la mobilitazione dell’opinione pubblica aprono un conflitto sulla rappresentanza.', ['archivio','1789']),
('1789','1789','Dai sudditi alla nazione','Chi può parlare in nome della Francia?',[
('Dagli Stati Generali alla Costituente','Il 5 maggio si aprono gli Stati Generali. Il raddoppio dei deputati del Terzo Stato non risolve il problema del voto: se ogni ordine dispone di un voto collettivo, il vantaggio numerico perde efficacia. Nel contrasto sulla verifica dei mandati e sulle deliberazioni si decide se la nazione sia la somma di corpi separati o un insieme di cittadini.\nIl 17 giugno il Terzo Stato, con l’adesione di alcuni ecclesiastici, si proclama Assemblea nazionale. Il 20 giugno, trovata chiusa la sala abituale, i deputati si riuniscono nella sala della Pallacorda e si impegnano a non separarsi prima di aver dato una costituzione al regno. Il 9 luglio l’assemblea si definisce costituente. Il potere di stabilire le regole fondamentali viene rivendicato dai rappresentanti della nazione.'),
('La rivoluzione delle città e delle campagne','La concentrazione di truppe e il licenziamento di Necker alimentano a Parigi il timore di una repressione. Il 14 luglio gli insorti cercano armi e polvere da sparo; la Bastiglia è conquistata dopo negoziati, scontri e resa della guarnigione. L’uccisione del governatore rivela anche la violenza della giornata. L’intervento popolare modifica i rapporti di forza: l’assemblea non opera isolata dentro un’aula.\nNelle campagne la Grande Paura combina voci di complotti, timore dei briganti e ostilità verso i diritti signorili. Contadini attaccano castelli e documenti che attestano obblighi e rendite. L’obiettivo non coincide sempre con quello dei proprietari borghesi: abolire un privilegio giuridico e cancellare un pagamento sulla terra sono questioni collegate ma diverse.'),
('Principi nuovi, applicazioni contrastate','La notte del 4 agosto l’assemblea avvia lo smantellamento dei privilegi. Una parte dei diritti signorili rimane però inizialmente riscattabile: non tutti gli oneri spariscono in una notte. Solo nel luglio 1793 si arriverà alla loro abolizione senza indennizzo. Il 26 agosto la Dichiarazione dei diritti afferma libertà, uguaglianza giuridica e sovranità nazionale. La legge deve esprimere una volontà generale, non la nascita privilegiata.\nL’universalità del linguaggio apre domande che il nuovo ordine non risolve: le donne avranno rappresentanza? Chi non possiede ricchezza potrà votare? I diritti varranno nelle colonie schiaviste? Queste esclusioni non sono un dettaglio esterno alla Rivoluzione; diventano terreno di lotta proprio perché i principi proclamati possono essere rivolti contro chi li limita.'),
('La monarchia sotto gli occhi di Parigi','Il 5–6 ottobre le donne che marciano su Versailles, insieme ad altri manifestanti e alla Guardia nazionale, chiedono pane e garanzie politiche. La famiglia reale viene condotta a Parigi e l’assemblea la segue. Il re non è ancora deposto, ma la distanza protettiva della corte si riduce. Nel 1789 convivono così tre rivoluzioni: dei rappresentanti, delle città e delle campagne, alleate senza diventare identiche.')], 'La sovranità nazionale prende forma grazie all’intreccio fra assemblea e mobilitazioni popolari.', ['1789','bastiglia','monarchia']),
('monarchia-costituzionale','1790–1792','La fiducia spezzata','Può il re governare una rivoluzione che limita il suo potere?',[
('Rifondare il paese','La Costituente ridisegna amministrazione e giustizia, crea i dipartimenti, mette in vendita beni ecclesiastici e tenta di rendere uniforme il territorio. Gli assegnati, inizialmente legati a quei beni, diventano moneta cartacea; la loro moltiplicazione contribuirà in seguito all’inflazione. La riforma offre opportunità soprattutto a chi dispone di denaro per comprare.\nLa Costituzione civile del clero del 12 luglio 1790 riorganizza diocesi e cariche ecclesiastiche. Il successivo obbligo di giuramento provoca una divisione fra sacerdoti giurati e refrattari. Per molti fedeli la fedeltà religiosa entra in conflitto con l’obbedienza alla nuova legge. Non si tratta semplicemente di una lotta fra credenti e atei: numerosi rivoluzionari sono cattolici.'),
('Il re fugge, la nazione si divide','La festa della Federazione del 14 luglio 1790 rappresenta un progetto di unità fra nazione, legge e re. Ma la fuga della famiglia reale il 20–21 giugno 1791, interrotta a Varennes, distrugge molta di quella fiducia. Luigi XVI cercava di recuperare libertà d’azione e forza politica vicino al confine; la sua dichiarazione lasciata a Parigi criticava il nuovo assetto.\nIl 17 luglio la Guardia nazionale spara sui manifestanti al Campo di Marte. La frattura attraversa ormai il campo rivoluzionario: i moderati temono la pressione delle piazze, i radicali denunciano una libertà riservata ai proprietari. La legge Le Chapelier, approvata nel giugno 1791, aveva vietato coalizioni professionali e associazioni operaie, presentando la libertà individuale come incompatibile con i corpi intermedi.'),
('Una costituzione già fragile','La Costituzione approvata il 3 settembre 1791 mantiene il re con potere esecutivo e veto sospensivo; l’assemblea detiene quello legislativo. Il suffragio è maschile e censitario, con elezioni indirette: i diritti civili non implicano eguali diritti politici. La distinzione fra cittadini attivi e passivi contrasta con le aspettative di parte del movimento popolare.\nNella nuova Assemblea legislativa la guerra diventa oggetto di scontro. Brissot e i suoi sostenitori pensano che possa difendere e diffondere la Rivoluzione; il re spera di recuperare potere anche attraverso una sconfitta francese. Robespierre teme invece la militarizzazione e la libertà imposta con le armi. Il 20 aprile 1792 la Francia dichiara guerra al re di Boemia e Ungheria, cioè al sovrano asburgico.'),
('La guerra trasforma il conflitto interno','Le prime sconfitte, il sospetto di tradimento e il manifesto di Brunswick esasperano il clima. La patria in pericolo mobilita volontari e sezioni parigine. Il 10 agosto 1792 l’assalto alle Tuileries provoca la sospensione del re. Il compromesso monarchico è crollato: la guerra non è soltanto un fatto esterno, ma una forza che cambia istituzioni e criteri della lealtà politica.')], 'Varennes, il conflitto religioso e la guerra rendono impraticabile il compromesso del 1791.', ['1791','monarchia']),
('repubblica-terrore','1792–1794','La Repubblica sotto assedio','Come può la difesa della libertà produrre un governo d’eccezione?',[
('La repubblica nasce nella guerra','Dopo il 10 agosto vengono indette elezioni per una Convenzione, con suffragio maschile molto più ampio ma partecipazione limitata e forte pressione del contesto. I massacri nelle carceri del settembre 1792 mostrano il collasso delle garanzie sotto il timore di un complotto interno. Valmy, il 20 settembre, ferma l’avanzata prussiana. Il 21 settembre la Convenzione abolisce la monarchia; dal 22 settembre gli atti sono datati nell’Anno I della Repubblica.\nIl processo a Luigi XVI pone un problema giuridico e politico: si giudica un individuo, un tradimento o la monarchia stessa? L’esecuzione del 21 gennaio 1793 rende irreversibile la rottura dinastica e inasprisce la guerra europea, già iniziata nel 1792. Non bisogna far nascere l’intero conflitto dall’esecuzione del re.'),
('Emergenze e lotte per il potere','Nel 1793 le sconfitte militari, l’inflazione e la leva obbligatoria alimentano crisi e rivolte. In Vandea si intrecciano opposizione alla leva, religione, conflitti locali e fedeltà monarchica. Dopo la caduta dei girondini si sviluppano anche rivolte dette federaliste, diverse dalla Vandea per composizione e obiettivi. Ridurle tutte a un unico complotto aristocratico significa accettare il linguaggio degli avversari.\nIl Comitato di salute pubblica nasce il 6 aprile 1793. Danton vi esercita inizialmente un ruolo importante; Robespierre entra il 27 luglio, quando Danton non ne fa più parte. La pressione delle sezioni e della Guardia nazionale porta il 2 giugno all’arresto dei principali deputati girondini. La Convenzione continua a esistere: il governo rivoluzionario è una rete di assemblea, comitati, rappresentanti in missione e poteri locali, non il semplice comando personale di un uomo.'),
('Diritti promessi e diritti sospesi','La Costituzione del 24 giugno 1793 prevede una repubblica democratica e una dichiarazione che riconosce assistenza e istruzione. Viene approvata ma non attuata: in ottobre il governo è dichiarato rivoluzionario fino alla pace. La leva in massa mobilita risorse e popolazione; il maximum limita prezzi e salari; la legge dei sospetti amplia gli arresti. Le misure economiche rispondono alla pressione popolare e alle necessità della guerra, ma generano nuovi conflitti.\nIl Terrore comprende strumenti legali d’eccezione e violenze in contesti diversi. I massacri, le esecuzioni e la repressione in Vandea richiedono spiegazioni specifiche; comprenderne le condizioni non li giustifica. Anche donne rivoluzionarie e oppositori repubblicani subiscono la repressione. Il 30 ottobre 1793 i club femminili sono vietati; nel marzo e nell’aprile 1794 vengono eliminati hébertisti e dantonisti.'),
('La vittoria non spegne la repressione','Il decreto del 4 febbraio 1794 abolisce la schiavitù nelle colonie francesi, dopo le iniziative locali a Saint-Domingue e l’insurrezione degli schiavi. L’applicazione è diseguale. In Francia la legge del 22 pratile, 10 giugno, riduce le garanzie del Tribunale rivoluzionario. Le vittorie militari, compresa Fleurus, non producono automaticamente una distensione. Crescono paure e conflitti nei comitati e nella Convenzione. Il 9 termidoro, 27 luglio, Robespierre viene arrestato; il giorno seguente è giustiziato con Saint-Just e altri. L’alleanza che lo abbatte include uomini compromessi nella repressione: non è una semplice vittoria degli innocenti sui colpevoli.')], 'La Repubblica difende conquiste rivoluzionarie mentre sospende garanzie e reprime anche parte dei suoi sostenitori.', ['guerra','comitato','1793','colonie']),
('direttorio','1794–1799','Chiudere la Rivoluzione?','Come stabilizzare una repubblica divisa senza restituire il potere al re?',[
('Dopo termidoro','La caduta di Robespierre non cancella in un giorno l’apparato repressivo. La Convenzione termidoriana ridimensiona progressivamente i comitati, chiude il club dei giacobini e smantella il controllo dei prezzi. La liberalizzazione in un contesto di inflazione e scarsità colpisce duramente i ceti popolari. In alcune regioni il Terrore bianco prende di mira ex giacobini e militanti: anche la reazione produce violenze.\nLe giornate di germinale e pratile dell’Anno III, nella primavera 1795, chiedono pane e la Costituzione del 1793. La repressione riduce il peso politico dei sanculotti. Il problema dei governanti è doppio: evitare tanto una restaurazione monarchica quanto il ritorno della democrazia popolare che associano al Terrore.'),
('La costituzione dei proprietari','La Costituzione del 22 agosto 1795 crea due camere, Consiglio dei Cinquecento e Consiglio degli Anziani, e un esecutivo di cinque direttori. Il voto torna censitario e indiretto; un sistema di rinnovi parziali tenta di limitare le concentrazioni di potere. La dichiarazione premessa al testo comprende ora anche i doveri, con forte enfasi su proprietà e ordine.\nLa separazione fra esecutivo e legislativo non prevede un efficace meccanismo ordinario per risolvere uno scontro insanabile. Il regime dispone di elezioni, discussione politica e vita culturale, ma ricorre anche a esclusioni e interventi militari. Il 13 vendemmiaio, 5 ottobre 1795, Bonaparte contribuisce a reprimere un’insurrezione realista contro la Convenzione, prima dell’insediamento del Direttorio.'),
('Elezioni, congiure e colpi di Stato','La congiura degli Eguali di Babeuf e dei suoi compagni, scoperta nel 1796, denuncia l’uguaglianza solo formale e propone una trasformazione dei rapporti economici. La repressione non elimina però il malessere. Dall’altro lato, i successi elettorali dei monarchici spaventano i direttori repubblicani. Il colpo di Stato del 18 fruttidoro Anno V, 4 settembre 1797, annulla risultati elettorali e allontana avversari con l’appoggio dell’esercito.\nNel 1798 vengono colpiti anche eletti neogiacobini. Quando chi governa corregge con la forza il voto che non gradisce, le istituzioni perdono credibilità. Non è soltanto una storia di corruzione: si tratta di una repubblica che fatica a riconoscere avversari legittimi e a rendere stabile il trasferimento del potere.'),
('Il peso crescente dei generali','Le vittorie militari procurano denaro, prestigio e influenza. La campagna d’Italia del 1796–1797 rende Bonaparte un interlocutore politico autonomo. Le repubbliche sorelle diffondono riforme e costituzioni, ma subiscono prelievi, requisizioni e dipendenza francese. La pace di Campoformio mostra che l’autodeterminazione può essere sacrificata alla diplomazia di potenza.\nLa spedizione d’Egitto del 1798 unisce obiettivi strategici e impresa scientifica; la distruzione della flotta francese ad Abukir ne rivela i limiti. Nel 1799, fra guerra della Seconda coalizione e crisi politica, Sieyès cerca una revisione autoritaria dell’assetto istituzionale. Il ritorno di Bonaparte rende disponibile il generale capace di darle forza armata.')], 'Il Direttorio difende la repubblica, ma elezioni invalidate e dipendenza dall’esercito ne indeboliscono le basi.', ['1795','guerra','brumaio']),
('brumaio','9–10 novembre 1799','La repubblica e il generale','Napoleone conclude la Rivoluzione o se ne appropria?',[
('Le condizioni e il progetto','Nel 1799 il Direttorio affronta difficoltà militari e politiche. Non tutto è fermo e non ogni francese attende un dittatore: si confrontano soluzioni diverse. Sieyès e altri promotori del colpo vogliono un esecutivo più forte e cercano l’appoggio di un generale. Bonaparte, tornato dall’Egitto, dispone di prestigio e di una rete di sostenitori. Il colpo è quindi un’operazione insieme civile e militare.\nLucien Bonaparte presiede il Consiglio dei Cinquecento. Il suo ruolo istituzionale sarà decisivo nel trasformare un’iniziativa contestata in una pretesa difesa della rappresentanza. Le forme giuridiche non scompaiono: vengono piegate e ricostruite sotto la pressione delle armi.'),
('18 brumaio: isolare le assemblee','Il 9 novembre, 18 brumaio Anno VIII, il Consiglio degli Anziani dispone il trasferimento dei consigli a Saint-Cloud, adducendo una minaccia contro le istituzioni. Bonaparte riceve il comando delle truppe. Dimissioni e neutralizzazione dei direttori disarticolano l’esecutivo. Spostare i deputati fuori Parigi limita la possibilità di una mobilitazione cittadina in loro appoggio.\nIl piano punta a ottenere dalle assemblee una trasformazione del regime. Non è ancora il trionfo sicuro che le immagini celebrative successive lasceranno immaginare. Occorre distinguere la preparazione del 18 dall’intervento decisivo del giorno seguente.'),
('19 brumaio: la forza decide','Il 10 novembre l’ingresso di Bonaparte nei consigli incontra resistenza. Il generale non riesce a imporre il proprio discorso al Consiglio dei Cinquecento. Lucien contribuisce a presentare l’opposizione come un pericolo per l’assemblea e per il generale. I soldati sgomberano la sala: la deliberazione perde la libertà necessaria per essere considerata un normale procedimento costituzionale.\nUna parte dei deputati rimasti approva misure che sopprimono il Direttorio e affidano il governo a tre consoli provvisori: Bonaparte, Sieyès e Roger Ducos. Il passaggio non coincide ancora con l’Impero e va distinto dalla Costituzione dell’Anno VIII, elaborata nelle settimane successive, che concentrerà il potere nel Primo console.'),
('Conseguenze e conclusione','Brumaio è una cesura convenzionale della storia della Rivoluzione: finisce l’esperienza del Direttorio e si apre il Consolato. Sopravvivono l’abolizione dei privilegi di nascita, la nuova distribuzione di molte proprietà e l’amministrazione trasformata; si restringono invece la competizione politica e la possibilità di partecipare liberamente al governo. L’ordine nuovo conserva e seleziona eredità rivoluzionarie.\nLa risposta alla domanda iniziale non è che la libertà conduca inevitabilmente alla dittatura. Dieci anni di conflitti hanno creato istituzioni, aspettative e paure; la guerra ha accresciuto il prestigio dell’esercito; uomini concreti hanno scelto di abbattere le regole vigenti. Napoleone si appropria della legittimità della Rivoluzione promettendo di stabilizzarne alcune conquiste e di chiuderne la stagione politica aperta.')], 'Il colpo di Stato si compie in due giornate e fonda un consolato provvisorio: l’Impero arriverà nel 1804.', ['brumaio','1795'])
]
SOURCES.update({
 'vieux': ('Camille Desmoulins · Le Vieux Cordelier, 15 dicembre 1793','https://revolution.chnm.org/exhibits/show/liberty--equality--fraternity/item/419','Fonte primaria, in traduzione inglese, sul dissenso repubblicano contro la logica del sospetto.'),
 'pere': ('Hébert · Il Père Duchesne sostiene il Terrore','https://revolution.chnm.org/exhibits/show/liberty--equality--fraternity/item/418','Fonte primaria della stampa rivoluzionaria, da confrontare con Desmoulins.'),
 'pratile': ('Legge del 22 pratile Anno II','https://revolution.chnm.org/exhibits/show/liberty--equality--fraternity/item/415','Testo della legge del 10 giugno 1794, in traduzione inglese.'),
 'houel': ('Jean-Pierre Houël · La presa della Bastiglia, 1789','https://commons.wikimedia.org/wiki/File:Prise_de_la_Bastille.jpg','Acquerello, Bibliothèque nationale de France. Riproduzione di opera in pubblico dominio, via Wikimedia Commons. Ridimensionata in WebP, senza alterazione del contenuto.'),
 'bouchot': ('François Bouchot · Bonaparte nei Cinquecento, 1840','https://commons.wikimedia.org/wiki/File:Bouchot_-_Le_general_Bonaparte_au_Conseil_des_Cinq-Cents.jpg','Dipinto storico conservato a Versailles, pubblico dominio, via Wikimedia Commons. Rappresentazione posteriore della giornata del 10 novembre 1799; riproduzione ridimensionata in WebP.'),
 'keralio': ('Annie Geffroy · Louise de Kéralio-Robert','https://journals.openedition.org/ahrf/6113','Annales historiques de la Révolution française, 344, 2006, pp. 107–124. Ricerca su repubblicanesimo e ruolo dei sessi; adotta la cronologia 1756–1822.'),
})
