ESSENTIALS = [
'La crisi finanziaria dello Stato non coincide con la povertà dell’intero paese: debito, privilegi e resistenza alle riforme si intrecciano.',
'Il Terzo Stato è un ordine giuridico eterogeneo, non una classe economica unica.',
'Gli Stati Generali diventano un conflitto sulla rappresentanza: voto per ordine e voto per testa producono rapporti di forza diversi.',
'Nel giugno–luglio 1789 l’assemblea rivendica il potere di rappresentare la nazione e scrivere una costituzione.',
'Nel 1789 si intrecciano rivoluzione parlamentare, mobilitazione urbana e rivolte contadine.',
'L’abolizione dei privilegi avviata in agosto non cancella subito ogni diritto signorile senza riscatto: il processo prosegue fino al 1793.',
'La Dichiarazione del 1789 afferma diritti universali, ma la loro applicazione incontra esclusioni politiche, di genere e coloniali.',
'La Costituzione civile del clero apre un conflitto religioso e politico che attraversa le comunità.',
'Varennes precede la Costituzione del settembre 1791 e indebolisce la fiducia nel re.',
'La guerra comincia nell’aprile 1792, prima dell’abolizione della monarchia e dell’esecuzione del re.',
'Il 10 agosto sospende il re; il 21 settembre 1792 abolisce la monarchia; il 22 settembre apre la datazione repubblicana.',
'Il Comitato di salute pubblica nasce il 6 aprile 1793; Robespierre entra il 27 luglio.',
'La Costituzione del 1793 è approvata ma non attuata: il governo resta rivoluzionario fino alla pace.',
'Il Terrore unisce poteri d’eccezione e repressione; guerra, conflitti sociali, idee e scelte politiche concorrono a spiegarlo.',
'Le donne partecipano alla Rivoluzione senza ottenere piena cittadinanza politica; nel 1793 i loro club sono vietati.',
'L’abolizione della schiavitù del 4 febbraio 1794 è legata anche all’insurrezione di Saint-Domingue; applicazione e durata non sono uniformi.',
'Robespierre viene arrestato il 27 luglio 1794 e giustiziato il 28; lo smantellamento dell’eccezione richiede tempo.',
'Il Direttorio divide i poteri e restringe la partecipazione; i colpi di forza ne contraddicono la legalità.',
'Il 18 fruttidoro corrisponde al 4 settembre 1797. Il crescente ricorso all’esercito rafforza il peso politico dei generali.',
'Il colpo del 18–19 brumaio si svolge il 9–10 novembre 1799 e apre il Consolato, non l’Impero.'
]
GLOSSARY = {
'Antico regime':'Assetto politico e sociale precedente alla Rivoluzione, fondato su monarchia, ordini e privilegi. Il nome nasce da uno sguardo retrospettivo.',
'Ordine':'Gruppo definito giuridicamente da status, diritti e obblighi: clero, nobiltà o Terzo Stato. Non equivale a classe economica.',
'Privilegio':'Diritto particolare riconosciuto a un corpo, un territorio o una categoria; contrasta con l’idea di legge uguale per tutti.',
'Parlamenti':'Nella Francia prerivoluzionaria sono tribunali superiori, non assemblee legislative elette come quelle contemporanee.',
'Cahier de doléances':'Quaderno di richieste e rimostranze redatto in preparazione degli Stati Generali.',
'Sovranità':'Potere ultimo di stabilire l’ordine politico. La Rivoluzione lo trasferisce dal principio dinastico alla nazione o al popolo.',
'Potere costituente':'Autorità che stabilisce o rifonda le regole fondamentali da cui dipendono i poteri ordinari.',
'Costituzione':'Insieme delle regole fondamentali che organizzano i poteri e definiscono diritti e garanzie.',
'Suffragio censitario':'Diritto di voto subordinato a requisiti economici, fiscali o patrimoniali.',
'Suffragio universale maschile':'Espressione convenzionale per un voto maschile molto ampio: restano requisiti di età e cittadinanza, possibili esclusioni e, sempre, l’esclusione delle donne.',
'Veto sospensivo':'Facoltà di rinviare l’efficacia di una decisione legislativa senza poterla impedire per sempre.',
'Assegnati':'Titoli garantiti inizialmente da beni nazionali, poi impiegati come carta moneta; emissioni crescenti contribuiscono al deprezzamento.',
'Clero refrattario':'Sacerdoti che rifiutano il giuramento richiesto nel quadro della riforma rivoluzionaria della Chiesa.',
'Comune di Parigi':'Governo cittadino, particolarmente influente nelle giornate rivoluzionarie. Non coincide con l’assemblea nazionale.',
'Sezioni':'Circoscrizioni e assemblee locali parigine che diventano centri di mobilitazione e partecipazione.',
'Convenzione':'Assemblea eletta nel 1792 per rifondare l’ordine costituzionale; governa la Repubblica fino al 1795.',
'Comitato di salute pubblica':'Organo di deputati istituito il 6 aprile 1793, con funzioni crescenti di coordinamento e direzione del governo rivoluzionario.',
'Governo d’eccezione':'Esercizio del potere che sospende o riduce regole e garanzie ordinarie invocando un’emergenza.',
'Maximum':'Limite legale ai prezzi; nel maximum generale del 1793 vengono disciplinati anche i salari.',
'Federalismo del 1793':'Etichetta data a rivolte contro il predominio montagnardo e parigino; non tutte mirano a uno Stato federale.',
'Scristianizzazione':'Insieme di campagne contro culto e simboli cristiani; non è un programma uniforme di tutti i rivoluzionari.',
'Deismo':'Credenza in un principio divino conoscibile con la ragione, distinta dall’adesione a una Chiesa rivelata.',
'Termidoro':'Mese estivo del calendario repubblicano. Il 9 termidoro Anno II, 27 luglio 1794, indica la caduta politica di Robespierre.',
'Direttorio':'Regime del 1795–1799; in senso stretto l’esecutivo composto da cinque direttori.',
'Repubbliche sorelle':'Repubbliche nate sotto influenza o protezione francese, con riforme ispirate alla Rivoluzione e forte dipendenza politico-militare.',
'Colpo di Stato':'Conquista o trasformazione del potere attraverso la rottura delle regole vigenti, spesso con sostegno di apparati statali o militari.',
'Brumaio':'Mese autunnale del calendario repubblicano. Il 18 e 19 brumaio Anno VIII corrispondono al 9 e 10 novembre 1799.',
'Consolato':'Regime aperto nel 1799. Dal consolato provvisorio si passa alla concentrazione dei poteri nel Primo console Bonaparte.',
'Saint-Domingue':'Colonia francese nella parte occidentale di Hispaniola; la rivoluzione degli schiavi porterà all’indipendenza di Haiti nel 1804.',
'Fonte primaria':'Testimonianza o documento del periodo studiato. È vicina ai fatti, ma ha autore, finalità e limiti: non è automaticamente imparziale.'
}
# domanda, corretta, distrattori, spiegazione, pagina di recupero, fase
QUIZ = [
('Perché il raddoppio dei deputati del Terzo Stato non risolve il conflitto?','Il voto per ordine può ancora lasciare due voti contro uno.','Il Terzo Stato non può redigere quaderni di richieste.','Il re ha già abolito gli Stati Generali.','Il numero dei deputati conta diversamente secondo la regola di voto.','evento-stati-generali.html','1789'),
('Che cosa rivendica l’Assemblea il 17 giugno 1789?','Il diritto di rappresentare la nazione.','L’abolizione immediata di ogni proprietà.','L’istituzione del Direttorio.','La sovranità nazionale è rivendicata prima della repubblica.','evento-assemblea-nazionale.html','1789'),
('Quale affermazione sulla Bastiglia è corretta?','Gli insorti cercano anche polvere da sparo.','Vi vengono liberati migliaia di deputati.','Il suo assalto abolisce formalmente la monarchia.','Munizioni, paura della repressione e significato politico si intrecciano.','evento-bastiglia.html','1789'),
('Che cosa rende imprecisa la formula “tutti gli oneri feudali spariscono il 4 agosto”?','Diversi diritti restano inizialmente riscattabili.','Il 4 agosto è una festa napoleonica.','I deputati ristabiliscono i privilegi.','Il completamento senza indennizzo arriva nel luglio 1793.','evento-quattro-agosto.html','1789'),
('La Dichiarazione del 1789 garantisce subito il voto alle donne?','No: principi universali e applicazione politica divergono.','Sì, ma soltanto alle nobili.','Sì, in tutte le assemblee nazionali.','La partecipazione femminile non coincide con il riconoscimento elettorale.','documento-dichiarazione-donna.html','1789'),
('Quale sequenza è corretta?','Varennes → Campo di Marte → Costituzione del 1791.','Costituzione del 1791 → Varennes → Campo di Marte.','Campo di Marte → Costituzione del 1791 → Varennes.','Giugno, luglio e settembre 1791: la carta nasce dopo la crisi di fiducia.','fase-monarchia-costituzionale.html','monarchia-costituzionale'),
('Quale conflitto produce la Costituzione civile del clero?','Una frattura fra fedeltà religiosa e obblighi verso il nuovo Stato.','L’immediata scomparsa di ogni culto in Francia.','L’elezione del papa da parte dei sanculotti.','Giuramento, riorganizzazione ecclesiastica e condanna papale dividono comunità e sacerdoti.','evento-clero.html','monarchia-costituzionale'),
('Perché Robespierre si oppone alla guerra nel 1792?','Teme militarizzazione e libertà imposta con le armi.','Vuole restaurare subito il potere assoluto del re.','È già a capo dell’esercito prussiano.','Le posizioni sulla guerra attraversano e complicano le etichette politiche.','evento-guerra-1792.html','monarchia-costituzionale'),
('Quale atto avviene il 10 agosto 1792?','La sospensione del re dopo l’assalto alle Tuileries.','L’incoronazione di Napoleone.','L’approvazione della Costituzione dell’Anno III.','L’abolizione formale della monarchia segue il 21 settembre.','evento-tuileries.html','repubblica-terrore'),
('Quando nasce il Comitato di salute pubblica?','6 aprile 1793.','14 luglio 1789.','9 novembre 1799.','Robespierre vi entrerà soltanto il 27 luglio 1793.','evento-comitato.html','repubblica-terrore'),
('Quale rapporto esiste fra Costituzione del 1793 e governo effettivo?','La carta è approvata ma non attuata.','La carta regola stabilmente il Direttorio.','La carta ristabilisce la monarchia.','L’eccezione rivoluzionaria viene mantenuta fino alla pace.','documento-costituzione-1793.html','repubblica-terrore'),
('Perché non si possono identificare Vandea e rivolte federaliste?','Hanno composizioni, tempi e obiettivi differenti.','La Vandea si trova nelle colonie caraibiche.','Le rivolte federaliste precedono il 1789.','La guerra cattolica e monarchica dell’ovest non coincide con tutte le opposizioni provinciali alla Montagna.','evento-vandea.html','repubblica-terrore'),
('Che cosa distingue il maximum generale?','Disciplina prezzi e anche salari.','Introduce il suffragio femminile.','Abolisce tutte le imposte.','La tutela dell’approvvigionamento convive con tensioni fra salariati, produttori e governo.','evento-sospetti-maximum.html','repubblica-terrore'),
('Quale fattore è decisivo per comprendere l’abolizione della schiavitù del 1794?','L’insurrezione degli schiavi e la guerra a Saint-Domingue.','La sola generosità personale di Luigi XVI.','La fine dell’Impero napoleonico.','L’emancipazione è anche il risultato dell’azione dei soggetti schiavizzati.','evento-abolizione-schiavitu.html','repubblica-terrore'),
('Quale precisazione serve sulla condanna di Olympe de Gouges?','Va collegata anche al manifesto delle Tre urne del 1793.','È dovuta a una sua carica nel Direttorio.','Avviene prima della Dichiarazione del 1791.','Il contesto politico del processo e i pregiudizi di genere vanno analizzati insieme.','persona-olympe.html','repubblica-terrore'),
('Quale sequenza riguarda Robespierre?','Arresto il 27 luglio, esecuzione il 28 luglio 1794.','Arresto ed esecuzione il 14 luglio 1789.','Arresto nel 1795, liberazione nel 1799.','Il 9 e il 10 termidoro sono due giornate distinte.','evento-termidoro.html','direttorio'),
('Quanti membri compongono l’esecutivo del Direttorio?','Cinque.','Uno.','Dodici.','L’esecutivo collegiale affianca due camere legislative.','documento-anno-iii.html','direttorio'),
('A quale data corrisponde il 18 fruttidoro Anno V?','4 settembre 1797.','18 giugno 1797.','9 novembre 1799.','Il colpo colpisce i monarchici e altera i risultati elettorali.','evento-fruttidoro.html','direttorio'),
('Quale contraddizione emerge nelle repubbliche sorelle?','Riforme liberatrici e dipendenza dalla potenza francese convivono.','La Francia vieta qualunque riforma giuridica.','I generali francesi non intervengono mai nella politica.','Campoformio mostra il peso degli interessi strategici rispetto all’autodeterminazione.','evento-italia.html','direttorio'),
('Che cosa apre il colpo di brumaio?','Il Consolato.','L’Impero già il 9 novembre.','La monarchia costituzionale di Luigi XVI.','L’Impero nascerà nel 1804; nel novembre 1799 si istituisce un consolato provvisorio.','evento-19-brumaio.html','brumaio'),
('Perché il ruolo di Lucien Bonaparte è importante?','Presiede i Cinquecento e favorisce l’intervento delle truppe.','Comanda la flotta ad Abukir.','Scrive la Dichiarazione del 1789.','Una carica parlamentare contribuisce a dare una giustificazione all’azione militare.','persona-lucien.html','brumaio'),
('Un dipinto del 1840 su brumaio è soprattutto…','Una fonte della memoria successiva da confrontare con testimonianze del 1799.','Una fotografia dell’avvenimento.','La prova che ogni dettaglio rappresentato è accaduto.','La data e la funzione dell’opera cambiano ciò che essa può documentare.','documento-brumaio-immagine.html','brumaio'),
('Il Terzo Stato comprende…','Gruppi economicamente diversi uniti da una condizione giuridica.','Soltanto i poveri delle città.','Soltanto i proprietari di fabbriche.','Ordine e classe economica non sono sinonimi.','gruppo-ordini.html','antefatto'),
('Quale domanda guida il confronto fra 1793 e 1795?','Come cambiano partecipazione, garanzie sociali e idea di ordine?','Quale re torna sul trono nel 1795?','Perché entrambe le carte affidano tutto a Napoleone?','La prima carta resta inattuata; la seconda organizza il Direttorio.','documenti.html#confronto','direttorio'),
('Perché il Terrore non si spiega con un solo uomo?','Coinvolge istituzioni, guerra, conflitti e decisioni di molti attori.','Perché non vi sono responsabilità individuali.','Perché tutte le violenze sono inventate.','Spiegare la complessità non cancella responsabilità e vittime.','fase-repubblica-terrore.html','repubblica-terrore'),
('Che cosa contesta Babeuf?','Un’uguaglianza giuridica che lascia intatte forti dipendenze economiche.','L’esistenza di ogni forma di uguaglianza.','Il ritorno dell’Impero nel 1796.','Gli Eguali pongono la questione delle condizioni materiali della libertà.','persona-babeuf.html','direttorio'),
('Come vanno studiate le tricoteuses?','Distinguendo militanza femminile e stereotipo polemico.','Come un partito formalmente guidato da Maria Antonietta.','Come un gruppo identico a tutte le donne francesi.','Una rappresentazione ostile non descrive da sola un’intera categoria sociale.','persona-tricoteuses.html','repubblica-terrore'),
('Il governo di brumaio è costituzionalmente regolare perché alcuni deputati votano?','No: la deliberazione avviene dopo pressione armata e sgombero.','Sì: qualsiasi voto cancella automaticamente la coercizione.','Sì: la Costituzione del 1795 prevede l’espulsione militare dei consigli.','Le forme giuridiche non bastano senza libertà effettiva della rappresentanza.','fase-brumaio.html','brumaio'),
]
ACTIVITIES = [
('Tre voci nel 1789','Confronta un deputato proprietario, una venditrice dei mercati e un contadino. Per ciascuno indica un problema, una richiesta e una possibile divergenza dagli altri.','Non attribuire a tutti lo stesso obiettivo. Collega rappresentanza, pane e diritti signorili; distingui interessi plausibili da parole documentate.',['fase-1789.html','gruppo-ordini.html']),
('Diritti messi alla prova','Confronta le schede delle Dichiarazioni del 1789 e del 1791 di Olympe. Individua un principio comune e una contraddizione nell’applicazione.','La risposta deve distinguere uguaglianza proclamata, cittadinanza politica e partecipazione di fatto. Cita gli articoli pertinenti dopo aver aperto le fonti.',['documento-dichiarazione-1789.html','documento-dichiarazione-donna.html']),
('Spiegare senza giustificare','Ricostruisci tre condizioni che favoriscono i massacri di settembre. Spiega poi perché quelle condizioni non rendono legittime le uccisioni.','La spiegazione storica ricostruisce paure, autorità e scelte. Il giudizio sulle violenze richiede di considerare vittime e garanzie negate.',['evento-settembre.html','documento-pratile.html']),
('Un confronto fra giornali','Metti a confronto Hébert e Desmoulins. Che cosa presenta ciascuno come minaccia per la Repubblica? Quale azione vuole ottenere dai lettori?','Analizza destinatari, linguaggio e obiettivo. Entrambi parlano in nome della Repubblica; la diversità riguarda il modo di difenderla.',['documento-pere-duchesne.html','documento-vieux-cordelier.html']),
('Il dibattito su brumaio','Argomenta la tesi “Bonaparte stabilizza alcune conquiste rivoluzionarie” e la tesi “Bonaparte riduce la libertà politica”. Possono essere entrambe fondate?','Usa istituzioni, proprietà e partecipazione come criteri distinti. Non anticipare il 1804 al 1799 e non descrivere l’esito come inevitabile.',['fase-direttorio.html','fase-brumaio.html']),
]
