
const D = window.RF_DATA;
const app = document.getElementById('app');
const modal = document.getElementById('modal');
const modalTitle = document.getElementById('modalTitle');
const modalBody = document.getElementById('modalBody');
const closeBtn = document.getElementById('modalClose');
closeBtn?.addEventListener('click', closeModal); modal?.addEventListener('click', e=>{ if(e.target===modal) closeModal(); });
function closeModal(){ modal.classList.remove('open'); modalBody.innerHTML=''; }
function openImage(title, src){ modalTitle.textContent=title; modalBody.innerHTML=`<img src="${src}" alt="${escapeHtml(title)}">`; modal.classList.add('open'); }
function openPdf(title, src){ modalTitle.textContent=title; modalBody.innerHTML=`<iframe class="pdf-frame" src="${src}" title="${escapeHtml(title)}"></iframe><p class="offline-note"><a class="btn" href="${src}" target="_blank" rel="noopener">Apri o scarica il PDF</a></p>`; modal.classList.add('open'); }
function escapeHtml(s){ return String(s).replace(/[&<>"]/g, m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m])); }
function btn(label, cls='btn'){return `<span class="${cls}">${label}</span>`}
function pageHeader(kicker,title,lead){return `<section class="hero-mini"><div><div class="kicker">${kicker}</div><h1 class="hero-title">${title}</h1><p class="lead">${lead}</p></div><img src="assets/img/covers/copertina.png" alt="Copertina" style="width:100%;max-height:460px;object-fit:cover;border-radius:22px;border:1px solid rgba(213,168,91,.4);box-shadow:var(--shadow)"></section>`}
function renderCard(item, type='lesson'){
  const schema = item.schema ? `<a class="btn" href="javascript:void(0)" onclick="openImage('${escapeHtml(item.title)} — schema','${item.schema}')">Apri schema</a>` : '';
  const pdf = item.pdf ? `<a class="btn" href="javascript:void(0)" onclick="openPdf('${escapeHtml(item.title)} — PDF','${item.pdf}')">Leggi PDF</a>` : '';
  const video = item.video ? `<a class="btn" href="javascript:void(0)" onclick="openVideo('${escapeHtml(item.title)}','${item.video}')">Video</a>` : '';
  const detail = `<a class="btn btn-red" href="#${type}-${item.id}">Dettagli</a>`;
  return `<article class="card"><div class="card-content"><div class="num">${item.n||item.icon||'•'}</div><span class="tag">${item.tag||type}</span><h3>${item.title}</h3><p>${item.subtitle||''}</p><div class="card-actions">${detail}${pdf}${schema}${video}</div></div></article>`;
}
function openVideo(title, src){ modalTitle.textContent=title; modalBody.innerHTML=`<video src="${src}" controls style="max-width:100%;max-height:78vh;border-radius:14px;background:#000"></video>`; modal.classList.add('open'); }
function renderHome(){app.innerHTML=pageHeader('PWA didattica','La Rivoluzione <span>francese</span>','Percorso interattivo per studiare cause, eventi, protagonisti e concetti politici della Rivoluzione francese.')+`<div class="card-grid"><a class="card" href="#lezioni"><div class="card-content"><div class="num">1</div><h3>Lezioni</h3><p>Le quattro parti principali del percorso.</p></div></a><a class="card" href="#approfondimenti"><div class="card-content"><div class="num">2</div><h3>Approfondimenti</h3><p>Documenti, confronti, club, forme di governo, liberalismo.</p></div></a><a class="card" href="#mappe"><div class="card-content"><div class="num">3</div><h3>Mappe e schemi</h3><p>Infografiche pronte per ripasso e LIM.</p></div></a><a class="card" href="#quiz"><div class="card-content"><div class="num">?</div><h3>Quiz finale</h3><p>Domande interattive con correzione.</p></div></a></div>`;}
function renderLessons(){app.innerHTML=pageHeader('Percorso principale','Lezioni','Le quattro parti della lezione principale, con PDF e mappe concettuali.')+`<div class="card-grid">${D.lessons.map(x=>renderCard(x,'lezione')).join('')}</div>`;}
function renderLesson(id){const l=D.lessons.find(x=>x.id===id); if(!l)return renderLessons(); app.innerHTML=`<a class="btn" href="#lezioni">← Torna alle lezioni</a><h1 class="section-title">${l.title}</h1><p class="lead">${l.subtitle}</p><div class="tools-row"><a class="btn btn-red" onclick="openPdf('${escapeHtml(l.title)} — PDF','${l.pdf}')">Leggi la lezione</a><a class="btn" onclick="openImage('${escapeHtml(l.title)} — schema','${l.schema}')">Apri la mappa</a><a class="btn" href="${l.pdf}" download>Scarica PDF</a><a class="btn" href="${l.schema}" download>Scarica mappa</a></div><div class="panel"><img src="${l.schema}" alt="Schema ${escapeHtml(l.title)}" style="width:100%;border-radius:18px;background:#fff"></div>`;}
function renderApprofondimenti(){app.innerHTML=pageHeader('Finestre di studio','Approfondimenti','Schede laterali e concetti chiave per collegare la Rivoluzione a cittadinanza, economia, diritti e forme politiche.')+`<input class="searchbar" id="search" placeholder="Cerca negli approfondimenti…"><div class="card-grid" id="cards">${D.approfondimenti.map(x=>renderCard(x,'approfondimento')).join('')}</div>`; document.getElementById('search').addEventListener('input', e=>{ const q=e.target.value.toLowerCase(); document.getElementById('cards').innerHTML = D.approfondimenti.filter(x=>(x.title+x.subtitle).toLowerCase().includes(q)).map(x=>renderCard(x,'approfondimento')).join('') || '<p>Nessun risultato.</p>'; });}
function renderApprofondimento(id){const a=D.approfondimenti.find(x=>x.id===id); if(!a)return renderApprofondimenti(); app.innerHTML=`<a class="btn" href="#approfondimenti">← Torna agli approfondimenti</a><h1 class="section-title">${a.title}</h1><p class="lead">${a.subtitle}</p><div class="tools-row"><a class="btn btn-red" onclick="openPdf('${escapeHtml(a.title)} — PDF','${a.pdf}')">Leggi PDF</a><a class="btn" onclick="openImage('${escapeHtml(a.title)} — schema','${a.schema}')">Apri schema</a>${a.video?`<a class="btn" onclick="openVideo('${escapeHtml(a.title)}','${a.video}')">Guarda video</a>`:''}<a class="btn" href="${a.pdf}" download>Scarica PDF</a></div><div class="panel"><img src="${a.schema}" alt="Schema ${escapeHtml(a.title)}" style="width:100%;border-radius:18px;background:#fff"></div>${a.video?`<div class="panel"><h2>Video</h2><video src="${a.video}" controls style="width:100%;border-radius:18px;background:#000"></video></div>`:''}`;}
function renderMappe(){ const items=[...D.lessons.map(x=>({title:x.title,src:x.schema,subtitle:x.subtitle})),...D.approfondimenti.map(x=>({title:x.title,src:x.schema,subtitle:x.subtitle}))]; app.innerHTML=pageHeader('Ripasso visivo','Mappe e schemi','Tutte le mappe concettuali e gli schemi in un’unica galleria.')+`<div class="card-grid">${items.map(x=>`<article class="card image-card" onclick="openImage('${escapeHtml(x.title)}','${x.src}')"><img src="${x.src}" alt="${escapeHtml(x.title)}"><div class="card-content"><h3>${x.title}</h3><p>${x.subtitle||''}</p><div class="card-actions"><a class="btn" href="${x.src}" download onclick="event.stopPropagation()">Scarica</a></div></div></article>`).join('')}</div>`;}
function renderBiografie(){ app.innerHTML=pageHeader('Persone nella storia','Biografie','Le figure principali della Rivoluzione: monarchia, teorici, radicali, donne, popolo.')+`<input class="searchbar" id="search" placeholder="Cerca una figura…"><div class="bio-grid" id="bios">${D.biographies.map(renderBioCard).join('')}</div>`; document.getElementById('search').addEventListener('input',e=>{const q=e.target.value.toLowerCase(); document.getElementById('bios').innerHTML=D.biographies.filter(b=>(b.name+b.role+b.text).toLowerCase().includes(q)).map(renderBioCard).join('')||'<p>Nessun risultato.</p>'});}
function renderBioCard(b){return `<article class="card bio-card"><img src="${b.img}" alt="${escapeHtml(b.name)}"><div><h3>${b.name}</h3><small>${b.role}</small><p>${b.text.slice(0,170)}…</p><a class="btn" href="#bio-${b.id}">Leggi scheda</a></div></article>`}
function renderBio(id){const b=D.biographies.find(x=>x.id===id); if(!b)return renderBiografie(); app.innerHTML=`<a class="btn" href="#biografie">← Torna alle biografie</a><section class="panel" style="display:grid;grid-template-columns:minmax(220px,340px) 1fr;gap:26px;align-items:start"><img src="${b.img}" alt="${escapeHtml(b.name)}" style="width:100%;border-radius:22px;border:1px solid var(--gold);box-shadow:var(--shadow)"><div><div class="kicker">Biografia</div><h1 class="section-title">${b.name}</h1><p class="lead"><strong>${b.role}</strong></p><p style="font-size:1.18rem;line-height:1.75;color:#f5ead2">${b.text}</p></div></section>`;}
function renderTimeline(){app.innerHTML=pageHeader('Ordine cronologico','Timeline interattiva','Gli eventi principali dal 1789 al 1799, dalla crisi degli Stati Generali al colpo di Stato di Napoleone.')+`<section class="timeline">${D.timeline.map(e=>`<article class="event"><div class="year">${e.year}</div><div class="text"><h3>${e.title}</h3><p>${e.text}</p></div></article>`).join('')}</section>`}
let qi=0, score=0, answered=false;
function renderQuiz(){qi=0; score=0; answered=false; drawQuestion();}
function drawQuestion(){const q=D.quiz[qi]; if(!q){app.innerHTML=`<h1 class="section-title">Quiz concluso</h1><p class="score">Punteggio: ${score} / ${D.quiz.length}</p><p class="lead">${score>=9?'Ottimo lavoro. La rivoluzione, almeno per oggi, non ti ghigliottina.':'Da rivedere: la Rivoluzione perdona poco, ma il ripasso sì.'}</p><a class="btn btn-red" href="#quiz">Ricomincia</a>`;return;} app.innerHTML=`<h1 class="section-title">Quiz finale</h1><div class="card quiz-card"><div class="card-content"><span class="tag">Domanda ${qi+1} di ${D.quiz.length}</span><h3>${q.q}</h3><div class="answers">${q.a.map((ans,i)=>`<button class="answer" onclick="answer(${i})">${escapeHtml(ans)}</button>`).join('')}</div><p id="feedback"></p></div></div>`;}
window.answer=function(i){ if(answered)return; answered=true; const q=D.quiz[qi]; const buttons=[...document.querySelectorAll('.answer')]; buttons.forEach((b,idx)=>{ if(idx===q.ok)b.classList.add('correct'); if(idx===i && idx!==q.ok)b.classList.add('wrong'); }); if(i===q.ok)score++; document.getElementById('feedback').innerHTML=`<strong>${i===q.ok?'Corretto.':'Non corretto.'}</strong> ${q.why}<br><br><button class="btn btn-red" onclick="qi++;answered=false;drawQuestion()">Prosegui →</button>`;}
function router(){const h=(location.hash||'#home').slice(1); app.focus(); if(h==='home')return renderHome(); if(h==='lezioni')return renderLessons(); if(h.startsWith('lezione-'))return renderLesson(h.replace('lezione-','')); if(h==='approfondimenti')return renderApprofondimenti(); if(h.startsWith('approfondimento-'))return renderApprofondimento(h.replace('approfondimento-','')); if(h==='mappe')return renderMappe(); if(h==='biografie')return renderBiografie(); if(h.startsWith('bio-'))return renderBio(h.replace('bio-','')); if(h==='timeline')return renderTimeline(); if(h==='quiz')return renderQuiz(); renderHome();}
window.addEventListener('hashchange',router); router();
let deferredPrompt; window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;document.getElementById('installBtn')?.classList.add('show')}); document.getElementById('installBtn')?.addEventListener('click',async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null;}});
